<definitions
     name="ItemMasterAQ"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/aq/ItemMasterAQ/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/aq/ItemMasterAQ/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:imp1="http://www.openapplications.org/officedepot/merchandising/foundation/1"
     xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/aq/inbound/"
    >
    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/aq/inbound/" location="aqAdapterInboundHeader.wsdl"/>
    <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://www.openapplications.org/officedepot/merchandising/foundation/1" schemaLocation="http://chilsoa01d.na.odcorp.net:7778/orabpel/xmllib/merchFndXml/officedepot/merchandising/foundation/v1/message/bod/ODSyncItemMaster.xsd" />
      </schema>
    </types>
    <message name="SYNC_ITEM_MASTER_msg">
        <part name="SYNC_ITEM_MASTER" element="imp1:SYNC_ITEM_MASTER"/>
    </message>
    <portType name="Dequeue_ptt">
        <operation name="Dequeue">
            <input message="tns:SYNC_ITEM_MASTER_msg"/>
        </operation>
    </portType>
    <binding name="Dequeue_binding" type="tns:Dequeue_ptt">
    <pc:inbound_binding  />
        <operation name="Dequeue">
      <jca:operation
          ActivationSpec="oracle.tip.adapter.aq.inbound.AQDequeueActivationSpec"
          QueueName="OD_BPEL_ITEM_AQ"
          DatabaseSchema="RMS10_AQADM"
          OpaqueSchema="false" >
      </jca:operation>
      <input>
        <jca:header message="hdr:Header" part="Header"/>
      </input>
        </operation>
    </binding>
    <service name="ItemMasterAQ">
        <port name="Dequeue_pt" binding="tns:Dequeue_binding">
<!--Your runtime connection is declared in 
J2EE_HOME/application-deployments/default/AqAdapter/oc4j-ra.xml 
These mcf properties here are from your design time connection and 
save you from having to edit that file and restart the application server 
if eis/aq/RtkRms10 is missing. 
These mcf properties are safe to remove.-->
      <jca:address location="eis/aq/RtkRms10" UIConnectionName="rtk_rms10_rmsdev02"
          ManagedConnectionFactory="oracle.tip.adapter.aq.AQManagedConnectionFactory"
          mcf.ConnectionString="jdbc:oracle:thin:@//uschus0106.na.odcorp.net:1540/rmsdev02.na.odcorp.net"
          mcf.UserName="rms10"
          mcf.Password="53B2483DBDC7F7B8878987BFEF48E656D62D1A19DF561D1E" />
        </port>
    </service>
  <plt:partnerLinkType name="Dequeue_plt" >
    <plt:role name="Dequeue_role" >
      <plt:portType name="tns:Dequeue_ptt" />
    </plt:role>
  </plt:partnerLinkType>
</definitions>
