<definitions
     name="EnqueueMsg"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/aq/EnqueueMsg/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/aq/EnqueueMsg/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:imp1="http://www.openapplications.org/oagis/9"
     xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/aq/outbound/"
    >
    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/aq/outbound/" location="aqAdapterOutboundHeader.wsdl"/>
    <import namespace="http://www.openapplications.org/oagis/9" location="DPSCancel_SendNowDocsMsgProcess.wsdl"/>
    <message name="SalesOrderCancel_msg">
        <part name="SalesOrderCancel" element="imp1:SalesOrderCancel"/>
    </message>
    <portType name="Enqueue_ptt">
        <operation name="Enqueue">
            <input message="tns:SalesOrderCancel_msg"/>
        </operation>
    </portType>
    <binding name="Enqueue_binding" type="tns:Enqueue_ptt">
    <jca:binding  />
        <operation name="Enqueue">
      <jca:operation
          InteractionSpec="oracle.tip.adapter.aq.outbound.AQEnqueueInteractionSpec"
          QueueName="XX_OM_DPS_ERR_MSG_Q"
          DatabaseSchema="BPEL_AQADM"
          ObjectFieldName="ERR_MSG_T"
          Correlation="DPSCancelSendNowDocsFailure"
          OpaqueSchema="false" >
      </jca:operation>
      <input>
        <jca:header message="hdr:Header" part="Header"/>
      </input>
        </operation>
    </binding>
    <service name="EnqueueMsg">
        <port name="Enqueue_pt" binding="tns:Enqueue_binding">
<!--Your runtime connection is declared in 
J2EE_HOME/application-deployments/default/AqAdapter/oc4j-ra.xml 
These mcf properties here are from your design time connection and 
save you from having to edit that file and restart the application server 
if eis/db/bpeleh is missing. 
These mcf properties are safe to remove.-->
      <jca:address location="eis/db/bpeleh" UIConnectionName="b2b_b2b_common_soadev03"
          ManagedConnectionFactory="oracle.tip.adapter.aq.AQManagedConnectionFactory"
          mcf.ConnectionString="jdbc:oracle:thin:@//choldbr05d-vip.na.odcorp.net:1540/soadev03.na.odcorp.net"
          mcf.UserName="b2b_common"
          mcf.Password="730473F8077A93908579B129F36FE52CDDC048307AFA162A" />
        </port>
    </service>
  <plt:partnerLinkType name="Enqueue_plt" >
    <plt:role name="Enqueue_role" >
      <plt:portType name="tns:Enqueue_ptt" />
    </plt:role>
  </plt:partnerLinkType>
</definitions>
