<wsdl:definitions
     name="SerializedCouponGetMQAdapter"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/mq/CouponSerialization/ProcessSerializedCouponProviderABCSImpl/SerializedCouponGetMQAdapter"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/mq/CouponSerialization/ProcessSerializedCouponProviderABCSImpl/SerializedCouponGetMQAdapter"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:imp1="http://xmlns.officedepot.com/ApplicationMessage/POS/Custom/ABM/SerializedCouponMQResponseABM/V1"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    >
  <plt:partnerLinkType name="Dequeue_plt" >
    <plt:role name="Dequeue_role" >
      <plt:portType name="tns:Dequeue_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.officedepot.com/ApplicationMessage/POS/Custom/ABM/SerializedCouponMQResponseABM/V1" schemaLocation="xsd/SerializedCouponMQResponseABM.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Dequeue_msg">
        <wsdl:part name="body" element="imp1:SerializedCouponMQResponseABM"/>
    </wsdl:message>
    <wsdl:portType name="Dequeue_ptt">
        <wsdl:operation name="Dequeue">
            <wsdl:input message="tns:Dequeue_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
