package od.oracle.apps.xxcrm.mps.reports.server;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import od.oracle.apps.xxcrm.mps.reports.lov.server.XXCSMPSPartyNameVOImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class XXCSMPSTotalAssetsUnderContractAMImpl extends OAApplicationModuleImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public XXCSMPSTotalAssetsUnderContractAMImpl()
  {
  }

  /**
   * 
   * Container's getter for XXCSMPSTotalAssetsUnderContractVO1
   */
  public XXCSMPSTotalAssetsUnderContractVOImpl getXXCSMPSTotalAssetsUnderContractVO1()
  {
    return (XXCSMPSTotalAssetsUnderContractVOImpl)findViewObject("XXCSMPSTotalAssetsUnderContractVO1");
  }

  /**
   * 
   * Container's getter for XXCSMPSProgramTypeVO1
   */
  public XXCSMPSProgramTypeVOImpl getXXCSMPSProgramTypeVO1()
  {
    return (XXCSMPSProgramTypeVOImpl)findViewObject("XXCSMPSProgramTypeVO1");
  }

  /**
   * 
   * Container's getter for XXCSMPSPartyNameVO1
   */
  public XXCSMPSPartyNameVOImpl getXXCSMPSPartyNameVO1()
  {
    return (XXCSMPSPartyNameVOImpl)findViewObject("XXCSMPSPartyNameVO1");
  }

  /**
   * 
   * Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("od.oracle.apps.xxcrm.mps.reports.server", "XXCSMPSTotalAssetsUnderContractAMLocal");
  }

   public void initMPSAssetsundercontractRpt(String customerName, String ProgramType ,String StartDate, String EndDate, String managedStatus, String activeStatus)
  {
    System.out.println("##### in AM initMPSTOPCustRpt ProgramType="+ProgramType);
    XXCSMPSTotalAssetsUnderContractVOImpl mpsTotalAssetsundercontractVO = getXXCSMPSTotalAssetsUnderContractVO1();
    mpsTotalAssetsundercontractVO.initMPSAssetsundercontractRpt(customerName,ProgramType,StartDate,EndDate, managedStatus, activeStatus);
  } 
}