/*=========================================================================================+
 |   Copyright (c) 2013    Oracle Corporation, Redwood Shores, CA, USA                     |
 |                         All rights reserved.                                            |
 +=========================================================================================+
 |  HISTORY                                                                                |
 |  Date           Authors                       Remarks                                   |
 |  12-Aug-2013    Darshini                      I2186 - Modified for R12 Upgrade Retrofit |
 |  16-Feb-2017    Havish Kasina                 Closing the leaked connection/statement   |
 |  13-Oct-2018    Reddy Sekhar K                Code Added for Req# NAIT-61952            |
 |  30-Oct-2018    Rafi Mohammed                 Code Added for Req# NAIT-66520            |
 +=========================================================================================*/
package od.oracle.apps.xxcrm.cdh.ebl.custdocs.schema.server;

/* Subversion Info:
 * $HeadURL: http://svn.na.odcorp.net/svn/od/common/trunk/xxcomn/java/od/oracle/apps/xxcrm/cdh/ebl/custdocs/schema/server/ODEbillCustDocEOImpl.java $
 * $Rev: 291471 $
 * $Date: 2018-11-20 09:48:40 -0500 (Tue, 20 Nov 2018) $
*/



import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.AttributeList;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.RowID;

//  ---------------------------------------------------------------

//  ---    File	generated by Oracle Business Components	for Java.

//  ---------------------------------------------------------------

//Added by Mangala
import oracle.apps.fnd.framework.server.OAPlsqlEntityImpl;
import java.sql.SQLException;
/*Commented and added by Darshini for R12 Upgrade Retrofit
import oracle.jdbc.driver.OracleCallableStatement;*/
import oracle.jdbc.OracleCallableStatement;
import oracle.apps.fnd.framework.OAException;
import oracle.apps.fnd.framework.server.OADBTransactionImpl;
import oracle.apps.fnd.framework.server.OADBTransaction;
import java.sql.Types;
import oracle.jbo.Key;

import od.oracle.apps.xxcrm.cdh.ebl.server.ODUtil;

public class ODEbillCustDocEOImpl extends OAPlsqlEntityImpl {

    public static final int EXTENSIONID = 0;
    public static final int CUSTACCOUNTID = 1;
    public static final int ATTRGROUPID = 2;
    public static final int CREATEDBY = 3;
    public static final int CREATIONDATE = 4;
    public static final int LASTUPDATEDBY = 5;
    public static final int LASTUPDATEDATE = 6;
    public static final int LASTUPDATELOGIN = 7;
    public static final int CEXTATTR1 = 8;
    public static final int CEXTATTR2 = 9;
    public static final int CEXTATTR3 = 10;
    public static final int CEXTATTR4 = 11;
    public static final int CEXTATTR5 = 12;
    public static final int CEXTATTR6 = 13;
    public static final int CEXTATTR7 = 14;
    public static final int CEXTATTR8 = 15;
    public static final int CEXTATTR9 = 16;
    public static final int CEXTATTR10 = 17;
    public static final int CEXTATTR11 = 18;
    public static final int CEXTATTR12 = 19;
    public static final int CEXTATTR13 = 20;
    public static final int CEXTATTR14 = 21;
    public static final int CEXTATTR15 = 22;
    public static final int CEXTATTR16 = 23;
    public static final int CEXTATTR17 = 24;
    public static final int CEXTATTR18 = 25;
    public static final int CEXTATTR19 = 26;
    public static final int CEXTATTR20 = 27;
    public static final int NEXTATTR1 = 28;
    public static final int NEXTATTR2 = 29;
    public static final int NEXTATTR3 = 30;
    public static final int NEXTATTR4 = 31;
    public static final int NEXTATTR5 = 32;
    public static final int NEXTATTR6 = 33;
    public static final int NEXTATTR7 = 34;
    public static final int NEXTATTR8 = 35;
    public static final int NEXTATTR9 = 36;
    public static final int NEXTATTR10 = 37;
    public static final int NEXTATTR11 = 38;
    public static final int NEXTATTR12 = 39;
    public static final int NEXTATTR13 = 40;
    public static final int NEXTATTR14 = 41;
    public static final int NEXTATTR15 = 42;
    public static final int NEXTATTR16 = 43;
    public static final int NEXTATTR17 = 44;
    public static final int NEXTATTR18 = 45;
    public static final int NEXTATTR19 = 46;
    public static final int NEXTATTR20 = 47;
    public static final int DEXTATTR1 = 48;
    public static final int DEXTATTR2 = 49;
    public static final int DEXTATTR3 = 50;
    public static final int DEXTATTR4 = 51;
    public static final int DEXTATTR5 = 52;
    public static final int DEXTATTR6 = 53;
    public static final int DEXTATTR7 = 54;
    public static final int DEXTATTR8 = 55;
    public static final int DEXTATTR9 = 56;
    public static final int DEXTATTR10 = 57;
    public static final int ROWID = 58;
    public static final int BCPODFLAG = 59;


    private static oracle.apps.fnd.framework.server.OAEntityDefImpl mDefinitionObject;

  /**
   *
   * This is the default constructor (do not remove)
   */

  public ODEbillCustDocEOImpl()
  {
  }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("od.oracle.apps.xxcrm.cdh.ebl.custdocs.schema.server.ODEbillCustDocEO");
        }
        return mDefinitionObject;
    }

    /**
     *
     * Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList)
  {
    super.create(attributeList);
  }

  /**
   *
   * Add entity	remove logic in	this method.
   */
  public void remove()
  {
    super.remove();
  }
  /**
   *
   * Add Entity	validation code	in this	method.
   */
  protected void validateEntity()
  {
   super.validateEntity();
  }

  public String validateCustDoc(String pCustAcctId)
  {
     int payDocCnt =0;
     int payDocId1 = 0;
     int payDocId2 = 0;
     String comboType = null;
     String consFlag = null;
     String errMsg = null;
     //OAViewObject CustDocVO1 = (OAViewObject) this.findViewObject("ODEbillCustDocVO");
     OracleCallableStatement ocs=null;
     OADBTransactionImpl	db = (OADBTransactionImpl)getDBTransaction();
     //OADBTransaction db=this.getOADBTransaction();
     String stmt = "BEGIN XX_CDH_CUST_ACCT_EXT_W_PKG.VALIDATE_CUST_DOC("
            + "p_cust_account_id    => :1"
            + ",x_vld_pay_doc_cnt   => :2"
            + ",x_vld_pay_doc_id1   => :3"
            + ",x_vld_pay_doc_id2   => :4"
            + ",x_combo_type        => :5"
            + ",x_cons_flag         => :6"
            + ",x_error_msg         => :7);"
            + " END;";

      ocs = (OracleCallableStatement)db.createCallableStatement(stmt,1);
        try
        {
          Number custAcctId = new Number(pCustAcctId);
          ocs.registerOutParameter(2,Types.INTEGER);
          ocs.registerOutParameter(3,Types.INTEGER);
          ocs.registerOutParameter(4,Types.INTEGER);
          ocs.registerOutParameter(5,Types.VARCHAR);
          ocs.registerOutParameter(6,Types.VARCHAR);
          ocs.registerOutParameter(7,Types.VARCHAR);
          ocs.setNUMBER(1,custAcctId);
          ocs.execute();
          payDocCnt = ocs.getInt(2);
          payDocId1 = ocs.getInt(3);
          payDocId2 = ocs.getInt(4);
          comboType  = ocs.getString(5);
          consFlag   = ocs.getString(6);
          errMsg     = ocs.getString(7);
          ocs.close();

        }
        catch(SQLException e)
        {
          getOADBTransaction().rollback();
          throw new OAException(e.toString(),OAException.ERROR);
        }
		finally
        {
           try{
                if(ocs != null)
                   ocs.close();
              }
		   catch(Exception e){}
        }
        return errMsg;

  } // End of validateCustDoc

  /**
   *
   * Add locking logic here.
   */
 public void lock()
  {
    super.lock();
  }
/**
   *
  * Custom DML	update/insert/delete logic here.
   */
//commented by Mangala

 /* protected void doDML(int operation, TransactionEvent e)
 {
    super.doDML(operation, e);
  } */
  /**
   *
   * Gets the attribute	value for ExtensionId, using the alias name ExtensionId
   */
 public	Number getExtensionId()
  {
    return (Number)getAttributeInternal(EXTENSIONID);
  }
  /**
   *
   * Sets <code>value</code> as	the attribute value for	ExtensionId
   */
  public void setExtensionId(Number value)
  {
    setAttributeInternal(EXTENSIONID, value);
  }
  /**
   *
   * Gets the attribute	value for CustAccountId, using the alias name CustAccountId
   */
  public Number	getCustAccountId()
 {
    return (Number)getAttributeInternal(CUSTACCOUNTID);
  }
  /**
   *
   * Sets <code>value</code> as	the attribute value for	CustAccountId
   */
  public void setCustAccountId(Number value)
  {
   setAttributeInternal(CUSTACCOUNTID, value);
  }
  /**
   *
   * Gets the attribute	value for AttrGroupId, using the alias name AttrGroupId
   */

  public Number	getAttrGroupId()
  {
   return (Number)getAttributeInternal(ATTRGROUPID);
  }
  /**
   *
   * Sets <code>value</code> as	the attribute value for	AttrGroupId
   */
  public void setAttrGroupId(Number value)
  {
    setAttributeInternal(ATTRGROUPID, value);
  }

  /**
   *
   * Gets the attribute	value for CreatedBy, using the alias name CreatedBy
   */
  public Number	getCreatedBy()
  {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	CreatedBy
   */

  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
  *
   * Gets the attribute	value for CreationDate,	using the alias	name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   *
   * Gets the attribute	value for LastUpdatedBy, using the alias name LastUpdatedBy
   */

  public Number	getLastUpdatedBy()
  {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }



  /**
   *
   * Sets <code>value</code> as	the attribute value for	LastUpdatedBy
   */

  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY,	value);
  }

  /**
   *
   * Gets the attribute	value for LastUpdateDate, using	the alias name LastUpdateDate
   */

  public Date getLastUpdateDate()
  {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }
  /**
   *
   * Gets the attribute	value for LastUpdateLogin, using the alias name	LastUpdateLogin
   */

  public Number	getLastUpdateLogin()
  {
    return (Number)getAttributeInternal(LASTUPDATELOGIN);
  }
  /**
   *
   * Sets <code>value</code> as	the attribute value for	LastUpdateLogin
   */

  public void setLastUpdateLogin(Number	value)
  {
   setAttributeInternal(LASTUPDATELOGIN, value);
  }
  /**
   *
   * Gets the attribute	value for CExtAttr1, using the alias name CExtAttr1
   */

  public String	getCExtAttr1()
 {
   return (String)getAttributeInternal(CEXTATTR1);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr1
   */

  public void setCExtAttr1(String value)
  {
    setAttributeInternal(CEXTATTR1, value);
  }
  /**
   *
   * Gets the attribute	value for CExtAttr2, using the alias name CExtAttr2
   */
  public String	getCExtAttr2()
  {
    return (String)getAttributeInternal(CEXTATTR2);
  }
  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr2
   */

 public	void setCExtAttr2(String value)
  {
   setAttributeInternal(CEXTATTR2, value);
  }
  /**
   *
   * Gets the attribute	value for CExtAttr3, using the alias name CExtAttr3
   */

  public String	getCExtAttr3()
 {
   return (String)getAttributeInternal(CEXTATTR3);
  }
  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr3
   */

  public void setCExtAttr3(String value)
 {
   setAttributeInternal(CEXTATTR3, value);
  }
  /**
   *
   * Gets the attribute	value for CExtAttr4, using the alias name CExtAttr4
   */

  public String	getCExtAttr4()
  {
    return (String)getAttributeInternal(CEXTATTR4);
  }
  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr4
   */
  public void setCExtAttr4(String value)
  {
    setAttributeInternal(CEXTATTR4, value);
  }

  /**
   *
   * Gets the attribute	value for CExtAttr5, using the alias name CExtAttr5
   */

  public String	getCExtAttr5()
  {
    return (String)getAttributeInternal(CEXTATTR5);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr5
   */

  public void setCExtAttr5(String value)
  {
    setAttributeInternal(CEXTATTR5, value);
  }
  /**
   *
   * Gets the attribute	value for CExtAttr6, using the alias name CExtAttr6
   */
  public String	getCExtAttr6()
  {
    return (String)getAttributeInternal(CEXTATTR6);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr6
   */
  public void setCExtAttr6(String value)
  {
    setAttributeInternal(CEXTATTR6, value);
  }
  /**
   *
   * Gets the attribute	value for CExtAttr7, using the alias name CExtAttr7
   */

  public String	getCExtAttr7()
  {
    return (String)getAttributeInternal(CEXTATTR7);
  }
  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr7
   */
  public void setCExtAttr7(String value)
  {
    setAttributeInternal(CEXTATTR7, value);
  }
  /**
   *
   * Gets the attribute	value for CExtAttr8, using the alias name CExtAttr8
   */

  public String	getCExtAttr8()
  {
    return (String)getAttributeInternal(CEXTATTR8);
  }
  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr8
   */
  public void setCExtAttr8(String value)
  {
    setAttributeInternal(CEXTATTR8, value);
  }
  /**

   *

   * Gets the attribute	value for CExtAttr9, using the alias name CExtAttr9

   */

 public	String getCExtAttr9()
  {
    return (String)getAttributeInternal(CEXTATTR9);
  }
  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr9
   */
  public void setCExtAttr9(String value)
  {
    setAttributeInternal(CEXTATTR9, value);
  }
  /**

   *

   * Gets the attribute	value for CExtAttr10, using the	alias name CExtAttr10

   */
  public String	getCExtAttr10()
  {
    return (String)getAttributeInternal(CEXTATTR10);
  }
  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr10
   */
  public void setCExtAttr10(String value)
  {
    setAttributeInternal(CEXTATTR10, value);
  }

  /**
   *
   * Gets the attribute	value for CExtAttr11, using the	alias name CExtAttr11
   */

  public String	getCExtAttr11()
  {
    return (String)getAttributeInternal(CEXTATTR11);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr11
   */

  public void setCExtAttr11(String value)

  {
    setAttributeInternal(CEXTATTR11, value);
  }
  /**
   *
   * Gets the attribute	value for CExtAttr12, using the	alias name CExtAttr12
   */

  public String	getCExtAttr12()
  {
    return (String)getAttributeInternal(CEXTATTR12);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr12
   */

  public void setCExtAttr12(String value)
  {
    setAttributeInternal(CEXTATTR12, value);
  }


  /**
   *
   * Gets the attribute	value for CExtAttr13, using the	alias name CExtAttr13
   */
  public String	getCExtAttr13()
  {
    return (String)getAttributeInternal(CEXTATTR13);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr13
   */

  public void setCExtAttr13(String value)
  {
    setAttributeInternal(CEXTATTR13, value);
  }

  /**
   *
   * Gets the attribute	value for CExtAttr14, using the	alias name CExtAttr14
   */

  public String	getCExtAttr14()
  {
    return (String)getAttributeInternal(CEXTATTR14);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr14
   */

  public void setCExtAttr14(String value)
  {
    setAttributeInternal(CEXTATTR14, value);
  }


  /**
   *
   * Gets the attribute	value for CExtAttr15, using the	alias name CExtAttr15
   */

  public String	getCExtAttr15()
 {
    return (String)getAttributeInternal(CEXTATTR15);
  }


 /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr15
   */
  public void setCExtAttr15(String value)
 {
    setAttributeInternal(CEXTATTR15, value);
  }


  /**
   *
   * Gets the attribute	value for CExtAttr16, using the	alias name CExtAttr16
   */
  public String	getCExtAttr16()
  {
    return (String)getAttributeInternal(CEXTATTR16);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr16
   */

  public void setCExtAttr16(String value)
  {
    setAttributeInternal(CEXTATTR16, value);
  }

  /**
   *
   * Gets the attribute	value for CExtAttr17, using the	alias name CExtAttr17
   */

  public String	getCExtAttr17()
  {
    return (String)getAttributeInternal(CEXTATTR17);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr17
   */

  public void setCExtAttr17(String value)

  {
    setAttributeInternal(CEXTATTR17, value);
  }

  /**
   *
   * Gets the attribute	value for CExtAttr18, using the	alias name CExtAttr18
   */
  public String	getCExtAttr18()
  {
    return (String)getAttributeInternal(CEXTATTR18);
  }
  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr18
   */

  public void setCExtAttr18(String value)
  {
    setAttributeInternal(CEXTATTR18, value);
  }

  /**
  *
   * Gets the attribute	value for CExtAttr19, using the	alias name CExtAttr19
   */

  public String	getCExtAttr19()
  {
    return (String)getAttributeInternal(CEXTATTR19);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr19
   */
  public void setCExtAttr19(String value)
  {
    setAttributeInternal(CEXTATTR19, value);
  }

  /**
   *
   * Gets the attribute	value for CExtAttr20, using the	alias name CExtAttr20
   */
  public String	getCExtAttr20()
  {
    return (String)getAttributeInternal(CEXTATTR20);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	CExtAttr20
   */
  public void setCExtAttr20(String value)
  {
    setAttributeInternal(CEXTATTR20, value);
  }
  /**
   *
   * Gets the attribute	value for NExtAttr1, using the alias name NExtAttr1
   */
  public Number	getNExtAttr1()
  {
    return (Number)getAttributeInternal(NEXTATTR1);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr1
   */
  public void setNExtAttr1(Number value)
  {
    setAttributeInternal(NEXTATTR1, value);
  }

  /**
   *
   * Gets the attribute	value for NExtAttr2, using the alias name NExtAttr2
   */
  public Number	getNExtAttr2()
  {
    return (Number)getAttributeInternal(NEXTATTR2);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr2
   */
  public void setNExtAttr2(Number value)
  {
    setAttributeInternal(NEXTATTR2, value);
  }

  /**
   *
   * Gets the attribute	value for NExtAttr3, using the alias name NExtAttr3
   */
  public Number	getNExtAttr3()
  {
    return (Number)getAttributeInternal(NEXTATTR3);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr3
   */
  public void setNExtAttr3(Number value)
  {
    setAttributeInternal(NEXTATTR3, value);
  }

  /**
   *
   * Gets the attribute	value for NExtAttr4, using the alias name NExtAttr4
   */
  public Number	getNExtAttr4()
  {
    return (Number)getAttributeInternal(NEXTATTR4);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr4
   */
  public void setNExtAttr4(Number value)
  {
    setAttributeInternal(NEXTATTR4, value);
  }

  /**
   *
   * Gets the attribute	value for NExtAttr5, using the alias name NExtAttr5
   */
  public Number	getNExtAttr5()
  {
    return (Number)getAttributeInternal(NEXTATTR5);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr5
   */
  public void setNExtAttr5(Number value)
  {
    setAttributeInternal(NEXTATTR5, value);
  }

  /**
   *
   * Gets the attribute	value for NExtAttr6, using the alias name NExtAttr6
   */
  public Number	getNExtAttr6()
  {
    return (Number)getAttributeInternal(NEXTATTR6);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr6
   */
  public void setNExtAttr6(Number value)
  {
    setAttributeInternal(NEXTATTR6, value);
  }

  /**
   *
   * Gets the attribute	value for NExtAttr7, using the alias name NExtAttr7
   */
  public Number	getNExtAttr7()
  {
    return (Number)getAttributeInternal(NEXTATTR7);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr7
   */
  public void setNExtAttr7(Number value)
  {
    setAttributeInternal(NEXTATTR7, value);
  }

  /**
   *
   * Gets the attribute	value for NExtAttr8, using the alias name NExtAttr8
   */
  public Number	getNExtAttr8()
  {
    return (Number)getAttributeInternal(NEXTATTR8);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr8
   */
  public void setNExtAttr8(Number value)
  {
    setAttributeInternal(NEXTATTR8, value);
  }

  /**
   *
   * Gets the attribute	value for NExtAttr9, using the alias name NExtAttr9
   */
  public Number	getNExtAttr9()
  {
    return (Number)getAttributeInternal(NEXTATTR9);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr9
   */
  public void setNExtAttr9(Number value)
  {
    setAttributeInternal(NEXTATTR9, value);
  }

  /**
   *
   * Gets the attribute	value for NExtAttr10, using the	alias name NExtAttr10
   */
  public Number	getNExtAttr10()
  {
    return (Number)getAttributeInternal(NEXTATTR10);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr10
   */
  public void setNExtAttr10(Number value)
  {
    setAttributeInternal(NEXTATTR10, value);
  }

  /**
   *
   * Gets the attribute	value for NExtAttr11, using the	alias name NExtAttr11
   */
  public Number	getNExtAttr11()
  {
    return (Number)getAttributeInternal(NEXTATTR11);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr11
   */
  public void setNExtAttr11(Number value)
  {
    setAttributeInternal(NEXTATTR11, value);
  }

  /**
   *
   * Gets the attribute	value for NExtAttr12, using the	alias name NExtAttr12
   */
  public Number	getNExtAttr12()
  {
    return (Number)getAttributeInternal(NEXTATTR12);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr12
   */
  public void setNExtAttr12(Number value)
  {
    setAttributeInternal(NEXTATTR12, value);
  }

  /**
   *
   * Gets the attribute	value for NExtAttr13, using the	alias name NExtAttr13
   */
  public Number	getNExtAttr13()
  {
    return (Number)getAttributeInternal(NEXTATTR13);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr13
   */
  public void setNExtAttr13(Number value)
  {
    setAttributeInternal(NEXTATTR13, value);
  }

 /**
   *
   * Gets the attribute	value for NExtAttr14, using the	alias name NExtAttr14
   */
  public Number	getNExtAttr14()
  {
    return (Number)getAttributeInternal(NEXTATTR14);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr14
   */
  public void setNExtAttr14(Number value)
  {
    setAttributeInternal(NEXTATTR14, value);
  }

  /**
   *
   * Gets the attribute	value for NExtAttr15, using the	alias name NExtAttr15
   */
  public Number	getNExtAttr15()
  {
    return (Number)getAttributeInternal(NEXTATTR15);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr15
   */
  public void setNExtAttr15(Number value)
  {
    setAttributeInternal(NEXTATTR15, value);
  }

  /**
   *
   * Gets the attribute	value for NExtAttr16, using the	alias name NExtAttr16

  */
  public Number	getNExtAttr16()
  {
    return (Number)getAttributeInternal(NEXTATTR16);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr16
   */
  public void setNExtAttr16(Number value)
  {
   setAttributeInternal(NEXTATTR16, value);
  }

  /**
   *
   * Gets the attribute	value for NExtAttr17, using the	alias name NExtAttr17
   */
  public Number	getNExtAttr17()
  {
    return (Number)getAttributeInternal(NEXTATTR17);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr17
   */
  public void setNExtAttr17(Number value)

 {
    setAttributeInternal(NEXTATTR17, value);
 }

  /**
   *
   * Gets the attribute	value for NExtAttr18, using the	alias name NExtAttr18
   */
  public Number	getNExtAttr18()
  {
    return (Number)getAttributeInternal(NEXTATTR18);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr18
   */
  public void setNExtAttr18(Number value)
  {
    setAttributeInternal(NEXTATTR18, value);
  }

  /**
   *
   * Gets the attribute	value for NExtAttr19, using the	alias name NExtAttr19
   */
  public Number	getNExtAttr19()
  {
    return (Number)getAttributeInternal(NEXTATTR19);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr19
   */
  public void setNExtAttr19(Number value)
  {
    setAttributeInternal(NEXTATTR19, value);
  }

  /**
   *
   * Gets the attribute	value for NExtAttr20, using the	alias name NExtAttr20
   */

 public Number	getNExtAttr20()

 {
    return (Number)getAttributeInternal(NEXTATTR20);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	NExtAttr20
   */
  public void setNExtAttr20(Number value)
  {
    setAttributeInternal(NEXTATTR20, value);
  }

  /**
   *
   * Gets the attribute	value for DExtAttr1, using the alias name DExtAttr1
   */
  public Date getDExtAttr1()
  {
    return (Date)getAttributeInternal(DEXTATTR1);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	DExtAttr1
   */
  public void setDExtAttr1(Date	value)
  {
    setAttributeInternal(DEXTATTR1, value);
  }

  /**
   *
   * Gets the attribute	value for DExtAttr2, using the alias name DExtAttr2
   */
  public Date getDExtAttr2()
  {
    return (Date)getAttributeInternal(DEXTATTR2);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	DExtAttr2
   */
  public void setDExtAttr2(Date	value)
  {
    setAttributeInternal(DEXTATTR2, value);
  }

  /**
   *
   * Gets the attribute	value for DExtAttr3, using the alias name DExtAttr3
   */
  public Date getDExtAttr3()
  {
    return (Date)getAttributeInternal(DEXTATTR3);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	DExtAttr3
   */
  public void setDExtAttr3(Date	value)
  {
    setAttributeInternal(DEXTATTR3, value);
  }

  /**
   *
   * Gets the attribute	value for DExtAttr4, using the alias name DExtAttr4
   */
  public Date getDExtAttr4()
  {
    return (Date)getAttributeInternal(DEXTATTR4);
  }


 /**
   *
   * Sets <code>value</code> as	the attribute value for	DExtAttr4
   */
  public void setDExtAttr4(Date	value)
  {
    setAttributeInternal(DEXTATTR4, value);
  }

  /**
   *
   * Gets the attribute	value for DExtAttr5, using the alias name DExtAttr5
   */
  public Date getDExtAttr5()
  {
    return (Date)getAttributeInternal(DEXTATTR5);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	DExtAttr5
   */
  public void setDExtAttr5(Date	value)
  {
    setAttributeInternal(DEXTATTR5, value);
  }

  /**
   *
   * Gets the attribute	value for DExtAttr6, using the alias name DExtAttr6
   */
  public Date getDExtAttr6()
  {
    return (Date)getAttributeInternal(DEXTATTR6);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	DExtAttr6
   */
  public void setDExtAttr6(Date	value)
  {
    setAttributeInternal(DEXTATTR6, value);
  }

  /**
   *
   * Gets the attribute	value for DExtAttr7, using the alias name DExtAttr7
   */
  public Date getDExtAttr7()
  {
    return (Date)getAttributeInternal(DEXTATTR7);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	DExtAttr7
   */
  public void setDExtAttr7(Date	value)
 {
    setAttributeInternal(DEXTATTR7, value);
  }

/**
   *
 * Gets the attribute	value for DExtAttr8, using the alias name DExtAttr8
   */
  public Date getDExtAttr8()
  {
    return (Date)getAttributeInternal(DEXTATTR8);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	DExtAttr8
   */
  public void setDExtAttr8(Date	value)
  {
    setAttributeInternal(DEXTATTR8, value);
  }

  /**
   *
   * Gets the attribute	value for DExtAttr9, using the alias name DExtAttr9
   */
  public Date getDExtAttr9()
  {
    return (Date)getAttributeInternal(DEXTATTR9);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	DExtAttr9
   */
  public void setDExtAttr9(Date	value)
  {
    setAttributeInternal(DEXTATTR9, value);
  }

  /**
   *
   * Gets the attribute	value for DExtAttr10, using the	alias name DExtAttr10
   */
  public Date getDExtAttr10()
  {
    return (Date)getAttributeInternal(DEXTATTR10);
  }

  /**
   *
   * Sets <code>value</code> as	the attribute value for	DExtAttr10
   */
  public void setDExtAttr10(Date value)
  {
    setAttributeInternal(DEXTATTR10, value);
  }

  /**
   *
   * Gets the attribute	value for RowID, using the alias name RowID
   */
  public RowID getRowID()
  {
    return (RowID)getAttributeInternal(ROWID);
  }
  //  Generated	method.	Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case EXTENSIONID:
            return getExtensionId();
        case CUSTACCOUNTID:
            return getCustAccountId();
        case ATTRGROUPID:
            return getAttrGroupId();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case CEXTATTR1:
            return getCExtAttr1();
        case CEXTATTR2:
            return getCExtAttr2();
        case CEXTATTR3:
            return getCExtAttr3();
        case CEXTATTR4:
            return getCExtAttr4();
        case CEXTATTR5:
            return getCExtAttr5();
        case CEXTATTR6:
            return getCExtAttr6();
        case CEXTATTR7:
            return getCExtAttr7();
        case CEXTATTR8:
            return getCExtAttr8();
        case CEXTATTR9:
            return getCExtAttr9();
        case CEXTATTR10:
            return getCExtAttr10();
        case CEXTATTR11:
            return getCExtAttr11();
        case CEXTATTR12:
            return getCExtAttr12();
        case CEXTATTR13:
            return getCExtAttr13();
        case CEXTATTR14:
            return getCExtAttr14();
        case CEXTATTR15:
            return getCExtAttr15();
        case CEXTATTR16:
            return getCExtAttr16();
        case CEXTATTR17:
            return getCExtAttr17();
        case CEXTATTR18:
            return getCExtAttr18();
        case CEXTATTR19:
            return getCExtAttr19();
        case CEXTATTR20:
            return getCExtAttr20();
        case NEXTATTR1:
            return getNExtAttr1();
        case NEXTATTR2:
            return getNExtAttr2();
        case NEXTATTR3:
            return getNExtAttr3();
        case NEXTATTR4:
            return getNExtAttr4();
        case NEXTATTR5:
            return getNExtAttr5();
        case NEXTATTR6:
            return getNExtAttr6();
        case NEXTATTR7:
            return getNExtAttr7();
        case NEXTATTR8:
            return getNExtAttr8();
        case NEXTATTR9:
            return getNExtAttr9();
        case NEXTATTR10:
            return getNExtAttr10();
        case NEXTATTR11:
            return getNExtAttr11();
        case NEXTATTR12:
            return getNExtAttr12();
        case NEXTATTR13:
            return getNExtAttr13();
        case NEXTATTR14:
            return getNExtAttr14();
        case NEXTATTR15:
            return getNExtAttr15();
        case NEXTATTR16:
            return getNExtAttr16();
        case NEXTATTR17:
            return getNExtAttr17();
        case NEXTATTR18:
            return getNExtAttr18();
        case NEXTATTR19:
            return getNExtAttr19();
        case NEXTATTR20:
            return getNExtAttr20();
        case DEXTATTR1:
            return getDExtAttr1();
        case DEXTATTR2:
            return getDExtAttr2();
        case DEXTATTR3:
            return getDExtAttr3();
        case DEXTATTR4:
            return getDExtAttr4();
        case DEXTATTR5:
            return getDExtAttr5();
        case DEXTATTR6:
            return getDExtAttr6();
        case DEXTATTR7:
            return getDExtAttr7();
        case DEXTATTR8:
            return getDExtAttr8();
        case DEXTATTR9:
            return getDExtAttr9();
        case DEXTATTR10:
            return getDExtAttr10();
        case ROWID:
            return getRowID();
        case BCPODFLAG:
            return getBcPodFlag();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }
  //  Generated	method.	Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value,	AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case EXTENSIONID:
            setExtensionId((Number)value);
            return;
        case CUSTACCOUNTID:
            setCustAccountId((Number)value);
            return;
        case ATTRGROUPID:
            setAttrGroupId((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case CEXTATTR1:
            setCExtAttr1((String)value);
            return;
        case CEXTATTR2:
            setCExtAttr2((String)value);
            return;
        case CEXTATTR3:
            setCExtAttr3((String)value);
            return;
        case CEXTATTR4:
            setCExtAttr4((String)value);
            return;
        case CEXTATTR5:
            setCExtAttr5((String)value);
            return;
        case CEXTATTR6:
            setCExtAttr6((String)value);
            return;
        case CEXTATTR7:
            setCExtAttr7((String)value);
            return;
        case CEXTATTR8:
            setCExtAttr8((String)value);
            return;
        case CEXTATTR9:
            setCExtAttr9((String)value);
            return;
        case CEXTATTR10:
            setCExtAttr10((String)value);
            return;
        case CEXTATTR11:
            setCExtAttr11((String)value);
            return;
        case CEXTATTR12:
            setCExtAttr12((String)value);
            return;
        case CEXTATTR13:
            setCExtAttr13((String)value);
            return;
        case CEXTATTR14:
            setCExtAttr14((String)value);
            return;
        case CEXTATTR15:
            setCExtAttr15((String)value);
            return;
        case CEXTATTR16:
            setCExtAttr16((String)value);
            return;
        case CEXTATTR17:
            setCExtAttr17((String)value);
            return;
        case CEXTATTR18:
            setCExtAttr18((String)value);
            return;
        case CEXTATTR19:
            setCExtAttr19((String)value);
            return;
        case CEXTATTR20:
            setCExtAttr20((String)value);
            return;
        case NEXTATTR1:
            setNExtAttr1((Number)value);
            return;
        case NEXTATTR2:
            setNExtAttr2((Number)value);
            return;
        case NEXTATTR3:
            setNExtAttr3((Number)value);
            return;
        case NEXTATTR4:
            setNExtAttr4((Number)value);
            return;
        case NEXTATTR5:
            setNExtAttr5((Number)value);
            return;
        case NEXTATTR6:
            setNExtAttr6((Number)value);
            return;
        case NEXTATTR7:
            setNExtAttr7((Number)value);
            return;
        case NEXTATTR8:
            setNExtAttr8((Number)value);
            return;
        case NEXTATTR9:
            setNExtAttr9((Number)value);
            return;
        case NEXTATTR10:
            setNExtAttr10((Number)value);
            return;
        case NEXTATTR11:
            setNExtAttr11((Number)value);
            return;
        case NEXTATTR12:
            setNExtAttr12((Number)value);
            return;
        case NEXTATTR13:
            setNExtAttr13((Number)value);
            return;
        case NEXTATTR14:
            setNExtAttr14((Number)value);
            return;
        case NEXTATTR15:
            setNExtAttr15((Number)value);
            return;
        case NEXTATTR16:
            setNExtAttr16((Number)value);
            return;
        case NEXTATTR17:
            setNExtAttr17((Number)value);
            return;
        case NEXTATTR18:
            setNExtAttr18((Number)value);
            return;
        case NEXTATTR19:
            setNExtAttr19((Number)value);
            return;
        case NEXTATTR20:
            setNExtAttr20((Number)value);
            return;
        case DEXTATTR1:
            setDExtAttr1((Date)value);
            return;
        case DEXTATTR2:
            setDExtAttr2((Date)value);
            return;
        case DEXTATTR3:
            setDExtAttr3((Date)value);
            return;
        case DEXTATTR4:
            setDExtAttr4((Date)value);
            return;
        case DEXTATTR5:
            setDExtAttr5((Date)value);
            return;
        case DEXTATTR6:
            setDExtAttr6((Date)value);
            return;
        case DEXTATTR7:
            setDExtAttr7((Date)value);
            return;
        case DEXTATTR8:
            setDExtAttr8((Date)value);
            return;
        case DEXTATTR9:
            setDExtAttr9((Date)value);
            return;
        case DEXTATTR10:
            setDExtAttr10((Date)value);
            return;
        case BCPODFLAG:
            setBcPodFlag((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
 //Overridden method to call custom PLSQL API -- Added	by Mangala
 public void insertRow()
  {
         OracleCallableStatement oraclecallablestatement=null;
    try
    {
      String x_rowid = null;
	    OADBTransactionImpl	oadbtransactionimpl = (OADBTransactionImpl)getDBTransaction();

	    String s= "BEGIN"
		      +" XX_CDH_CUST_ACCT_EXT_W_PKG.insert_row(x_rowid    => :1"
		      +"    ,p_extension_id         =>   :2 "
		      +"    ,p_cust_account_id      =>   :3 "
		      +"    ,p_attr_group_id        =>   :4 "
		      +"    ,p_c_ext_attr1          =>   :5 "
		      +"    ,p_c_ext_attr2          =>   :6 "
		      +"    ,p_c_ext_attr3          =>   :7 "
		      +"    ,p_c_ext_attr4          =>   :8 "
		      +"    ,p_c_ext_attr5          =>   :9 "
		      +"    ,p_c_ext_attr6          =>   :10 "
		      +"    ,p_c_ext_attr7          =>   :11 "
		      +"    ,p_c_ext_attr8          =>   :12 "
		      +"    ,p_c_ext_attr9          =>   :13 "
		      +"    ,p_c_ext_attr10         =>   :14 "
		      +"    ,p_c_ext_attr11         =>   :15 "
		      +"    ,p_c_ext_attr12         =>   :16 "
		      +"    ,p_c_ext_attr13         =>   :17 "
		      +"    ,p_c_ext_attr14         =>   :18 "
		      +"    ,p_c_ext_attr15         =>   :19 "
		      +"    ,p_c_ext_attr16         =>   :20 "
		      +"    ,p_c_ext_attr17         =>   :21 "
		      +"    ,p_c_ext_attr18         =>   :22 "
		      +"    ,p_c_ext_attr19         =>   :23 "
		      +"    ,p_c_ext_attr20         =>   :24 "
		      +"    ,p_n_ext_attr1          =>   :25 "
		      +"    ,p_n_ext_attr2          =>   :26 "
		      +"    ,p_n_ext_attr3          =>   :27 "
		      +"    ,p_n_ext_attr4          =>   :28 "
		      +"    ,p_n_ext_attr5          =>   :29 "
		      +"    ,p_n_ext_attr6          =>   :30 "
		      +"    ,p_n_ext_attr7          =>   :31 "
		      +"    ,p_n_ext_attr8          =>   :32 "
		      +"    ,p_n_ext_attr9          =>   :33 "
		      +"    ,p_n_ext_attr10         =>   :34 "
		      +"    ,p_n_ext_attr11         =>   :35 "
		      +"    ,p_n_ext_attr12         =>   :36 "
		      +"    ,p_n_ext_attr13         =>   :37 "
		      +"    ,p_n_ext_attr14         =>   :38 "
		      +"    ,p_n_ext_attr15         =>   :39 "
		      +"    ,p_n_ext_attr16         =>   :40 "
		      +"    ,p_n_ext_attr17         =>   :41 "
		      +"    ,p_n_ext_attr18         =>   :42 "
		      +"    ,p_n_ext_attr19         =>   :43 "
		      +"    ,p_n_ext_attr20         =>   :44 "
		      +"    ,p_d_ext_attr1          =>   :45 "
		      +"    ,p_d_ext_attr2          =>   :46 "
		      +"    ,p_d_ext_attr3          =>   :47 "
		      +"    ,p_d_ext_attr4          =>   :48 "
		      +"    ,p_d_ext_attr5          =>   :49 "
		      +"    ,p_d_ext_attr6          =>   :50 "
		      +"    ,p_d_ext_attr7          =>   :51 "
		      +"    ,p_d_ext_attr8          =>   :52 "
		      +"    ,p_d_ext_attr9          =>   :53 "
		      +"    ,p_d_ext_attr10         =>   :54 "
		      +"    ,p_creation_date        =>   :55 "
		      +"    ,p_created_by           =>   :56 "
		      +"    ,p_last_update_date     =>   :57 "
		      +"    ,p_last_updated_by      =>   :58 "
		      +"    ,p_last_update_login    =>   :59 "
                      +"    ,p_bc_pod_flag          =>   :60); "  //Code Added by Reddy Sekar for Req# NAIT-61952 and 66520 
		      +" END; ";
	     oraclecallablestatement = (OracleCallableStatement)oadbtransactionimpl.createCallableStatement(s, -1);
      oraclecallablestatement.registerOutParameter(1,Types.CHAR);
	    oraclecallablestatement.setNUMBER(2,this.getExtensionId());
	    oraclecallablestatement.setNUMBER(3,this.getCustAccountId());
	    oraclecallablestatement.setNUMBER(4,this.getAttrGroupId());
      oraclecallablestatement.setString(5,this.getCExtAttr1());
      oraclecallablestatement.setString(6,this.getCExtAttr2());
      oraclecallablestatement.setString(7,this.getCExtAttr3());
      oraclecallablestatement.setString(8,this.getCExtAttr4());
      oraclecallablestatement.setString(9,this.getCExtAttr5());
      oraclecallablestatement.setString(10,this.getCExtAttr6());
      oraclecallablestatement.setString(11,this.getCExtAttr7());
      oraclecallablestatement.setString(12,this.getCExtAttr8());
      oraclecallablestatement.setString(13,this.getCExtAttr9());
      oraclecallablestatement.setString(14,this.getCExtAttr10());
      oraclecallablestatement.setString(15,this.getCExtAttr11());
      oraclecallablestatement.setString(16,this.getCExtAttr12());
      oraclecallablestatement.setString(17,this.getCExtAttr13());
      oraclecallablestatement.setString(18,this.getCExtAttr14());
      oraclecallablestatement.setString(19,this.getCExtAttr15());
      oraclecallablestatement.setString(20,this.getCExtAttr16());
      oraclecallablestatement.setString(21,this.getCExtAttr17());
      oraclecallablestatement.setString(22,this.getCExtAttr18());
      oraclecallablestatement.setString(23,this.getCExtAttr19());
      oraclecallablestatement.setString(24,this.getCExtAttr20());
      oraclecallablestatement.setNUMBER(25,this.getNExtAttr1());
      oraclecallablestatement.setNUMBER(26,this.getNExtAttr2());
      oraclecallablestatement.setNUMBER(27,this.getNExtAttr3());
      oraclecallablestatement.setNUMBER(28,this.getNExtAttr4());
      oraclecallablestatement.setNUMBER(29,this.getNExtAttr5());
      oraclecallablestatement.setNUMBER(30,this.getNExtAttr6());
      oraclecallablestatement.setNUMBER(31,this.getNExtAttr7());
      oraclecallablestatement.setNUMBER(32,this.getNExtAttr8());
      oraclecallablestatement.setNUMBER(33,this.getNExtAttr9());
      oraclecallablestatement.setNUMBER(34,this.getNExtAttr10());
      oraclecallablestatement.setNUMBER(35,this.getNExtAttr11());
      oraclecallablestatement.setNUMBER(36,this.getNExtAttr12());
      oraclecallablestatement.setNUMBER(37,this.getNExtAttr13());
      oraclecallablestatement.setNUMBER(38,this.getNExtAttr14());
      oraclecallablestatement.setNUMBER(39,this.getNExtAttr15());
      oraclecallablestatement.setNUMBER(40,this.getNExtAttr16());
      oraclecallablestatement.setNUMBER(41,this.getNExtAttr17());
      oraclecallablestatement.setNUMBER(42,this.getNExtAttr18());
      oraclecallablestatement.setNUMBER(43,this.getNExtAttr19());
      oraclecallablestatement.setNUMBER(44,this.getNExtAttr20());
      oraclecallablestatement.setDATE(45,this.getDExtAttr1());
      oraclecallablestatement.setDATE(46,this.getDExtAttr2());
      oraclecallablestatement.setDATE(47,this.getDExtAttr3());
      oraclecallablestatement.setDATE(48,this.getDExtAttr4());
      oraclecallablestatement.setDATE(49,this.getDExtAttr5());
      oraclecallablestatement.setDATE(50,this.getDExtAttr6());
      oraclecallablestatement.setDATE(51,this.getDExtAttr7());
      oraclecallablestatement.setDATE(52,this.getDExtAttr8());
      oraclecallablestatement.setDATE(53,this.getDExtAttr9());
      oraclecallablestatement.setDATE(54,this.getDExtAttr10());
      oraclecallablestatement.setDATE(55,this.getCreationDate());
      oraclecallablestatement.setNUMBER(56,this.getCreatedBy());
      oraclecallablestatement.setDATE(57,this.getLastUpdateDate());
      oraclecallablestatement.setNUMBER(58,this.getLastUpdatedBy());
      oraclecallablestatement.setNUMBER(59,this.getLastUpdateLogin());
      oraclecallablestatement.setString(60,this.getBcPodFlag()); //Code Added by Reddy Sekar for Req# NAIT-61952 and 66250
        oraclecallablestatement.execute();
      x_rowid = oraclecallablestatement.getString(1);
	}
	catch(SQLException sqlexception)
	{
	    throw OAException.wrapperException(sqlexception);
	}
  catch(Exception	exception)
  {
      throw OAException.wrapperException(exception);
  }
  finally
        {
           try{
                if(oraclecallablestatement != null)
                   oraclecallablestatement.close();
              }
		   catch(Exception e){}
        }
  }//Insert Row

 public	void updateRow()
    {
        OracleCallableStatement oraclecallablestatement=null;
    try
    {
        OADBTransactionImpl	oadbtransactionimpl = (OADBTransactionImpl)getDBTransaction();
        String s= "BEGIN"
              +" XX_CDH_CUST_ACCT_EXT_W_PKG.update_row(p_extension_id    => :1"
              +"    ,p_cust_account_id      =>   :2 "
              +"    ,p_attr_group_id        =>   :3 "
              +"    ,p_c_ext_attr1          =>   :4 "
              +"    ,p_c_ext_attr2          =>   :5 "
              +"    ,p_c_ext_attr3          =>   :6 "
              +"    ,p_c_ext_attr4          =>   :7 "
              +"    ,p_c_ext_attr5          =>   :8"
              +"    ,p_c_ext_attr6          =>   :9 "
              +"    ,p_c_ext_attr7          =>   :10 "
              +"    ,p_c_ext_attr8          =>   :11 "
              +"    ,p_c_ext_attr9          =>   :12 "
              +"    ,p_c_ext_attr10         =>   :13 "
              +"    ,p_c_ext_attr11         =>   :14 "
              +"    ,p_c_ext_attr12         =>   :15 "
              +"    ,p_c_ext_attr13         =>   :16 "
              +"    ,p_c_ext_attr14         =>   :17 "
              +"    ,p_c_ext_attr15         =>   :18 "
              +"    ,p_c_ext_attr16         =>   :19 "
              +"    ,p_c_ext_attr17         =>   :20 "
              +"    ,p_c_ext_attr18         =>   :21 "
              +"    ,p_c_ext_attr19         =>   :22 "
              +"    ,p_c_ext_attr20         =>   :23 "
              +"    ,p_n_ext_attr1          =>   :24 "
              +"    ,p_n_ext_attr2          =>   :25 "
              +"    ,p_n_ext_attr3          =>   :26 "
              +"    ,p_n_ext_attr4          =>   :27 "
              +"    ,p_n_ext_attr5          =>   :28 "
              +"    ,p_n_ext_attr6          =>   :29 "
              +"    ,p_n_ext_attr7          =>   :30 "
              +"    ,p_n_ext_attr8          =>   :31 "
              +"    ,p_n_ext_attr9          =>   :32 "
              +"    ,p_n_ext_attr10         =>   :33 "
              +"    ,p_n_ext_attr11         =>   :34 "
              +"    ,p_n_ext_attr12         =>   :35 "
              +"    ,p_n_ext_attr13         =>   :36 "
              +"    ,p_n_ext_attr14         =>   :37 "
              +"    ,p_n_ext_attr15         =>   :38 "
              +"    ,p_n_ext_attr16         =>   :39 "
              +"    ,p_n_ext_attr17         =>   :40 "
              +"    ,p_n_ext_attr18         =>   :41 "
              +"    ,p_n_ext_attr19         =>   :42 "
              +"    ,p_n_ext_attr20         =>   :43 "
              +"    ,p_d_ext_attr1          =>   :44 "
              +"    ,p_d_ext_attr2          =>   :45 "
              +"    ,p_d_ext_attr3          =>   :46 "
              +"    ,p_d_ext_attr4          =>   :47 "
              +"    ,p_d_ext_attr5          =>   :48 "
              +"    ,p_d_ext_attr6          =>   :49 "
              +"    ,p_d_ext_attr7          =>   :50 "
              +"    ,p_d_ext_attr8          =>   :51 "
              +"    ,p_d_ext_attr9          =>   :52 "
              +"    ,p_d_ext_attr10         =>   :53 "
              +"    ,p_last_update_date     =>   :54 "
              +"    ,p_last_updated_by      =>   :55 "
              +"    ,p_last_update_login    =>   :56 "                      
              +"    ,p_bc_pod_flag          =>   :57); "    //Code Added by Reddy Sekar for Req# NAIT-61952 and 66520
               +" END; ";
     oraclecallablestatement = (OracleCallableStatement)oadbtransactionimpl.createCallableStatement(s, -1);
      oraclecallablestatement.setNUMBER(1,this.getExtensionId());
      oraclecallablestatement.setNUMBER(2,this.getCustAccountId());
      oraclecallablestatement.setNUMBER(3,this.getAttrGroupId());
      oraclecallablestatement.setString(4,this.getCExtAttr1());
      oraclecallablestatement.setString(5,this.getCExtAttr2());
      oraclecallablestatement.setString(6,this.getCExtAttr3());
      oraclecallablestatement.setString(7,this.getCExtAttr4());
      oraclecallablestatement.setString(8,this.getCExtAttr5());
      oraclecallablestatement.setString(9,this.getCExtAttr6());
      oraclecallablestatement.setString(10,this.getCExtAttr7());
      oraclecallablestatement.setString(11,this.getCExtAttr8());
      oraclecallablestatement.setString(12,this.getCExtAttr9());
      oraclecallablestatement.setString(13,this.getCExtAttr10());
      oraclecallablestatement.setString(14,this.getCExtAttr11());
      oraclecallablestatement.setString(15,this.getCExtAttr12());
      oraclecallablestatement.setString(16,this.getCExtAttr13());
      oraclecallablestatement.setString(17,this.getCExtAttr14());
      oraclecallablestatement.setString(18,this.getCExtAttr15());
      oraclecallablestatement.setString(19,this.getCExtAttr16());
      oraclecallablestatement.setString(20,this.getCExtAttr17());
      oraclecallablestatement.setString(21,this.getCExtAttr18());
      oraclecallablestatement.setString(22,this.getCExtAttr19());
      oraclecallablestatement.setString(23,this.getCExtAttr20());
      oraclecallablestatement.setNUMBER(24,this.getNExtAttr1());
      oraclecallablestatement.setNUMBER(25,this.getNExtAttr2());
      oraclecallablestatement.setNUMBER(26,this.getNExtAttr3());
      oraclecallablestatement.setNUMBER(27,this.getNExtAttr4());
      oraclecallablestatement.setNUMBER(28,this.getNExtAttr5());
      oraclecallablestatement.setNUMBER(29,this.getNExtAttr6());
      oraclecallablestatement.setNUMBER(30,this.getNExtAttr7());
      oraclecallablestatement.setNUMBER(31,this.getNExtAttr8());
      oraclecallablestatement.setNUMBER(32,this.getNExtAttr9());
      oraclecallablestatement.setNUMBER(33,this.getNExtAttr10());
      oraclecallablestatement.setNUMBER(34,this.getNExtAttr11());
      oraclecallablestatement.setNUMBER(35,this.getNExtAttr12());
      oraclecallablestatement.setNUMBER(36,this.getNExtAttr13());
      oraclecallablestatement.setNUMBER(37,this.getNExtAttr14());
      oraclecallablestatement.setNUMBER(38,this.getNExtAttr15());
      oraclecallablestatement.setNUMBER(39,this.getNExtAttr16());
      oraclecallablestatement.setNUMBER(40,this.getNExtAttr17());
      oraclecallablestatement.setNUMBER(41,this.getNExtAttr18());
      oraclecallablestatement.setNUMBER(42,this.getNExtAttr19());
      oraclecallablestatement.setNUMBER(43,this.getNExtAttr20());
      oraclecallablestatement.setDATE(44,this.getDExtAttr1());
      oraclecallablestatement.setDATE(45,this.getDExtAttr2());
      oraclecallablestatement.setDATE(46,this.getDExtAttr3());
      oraclecallablestatement.setDATE(47,this.getDExtAttr4());
      oraclecallablestatement.setDATE(48,this.getDExtAttr5());
      oraclecallablestatement.setDATE(49,this.getDExtAttr6());
      oraclecallablestatement.setDATE(50,this.getDExtAttr7());
      oraclecallablestatement.setDATE(51,this.getDExtAttr8());
      oraclecallablestatement.setDATE(52,this.getDExtAttr9());
      oraclecallablestatement.setDATE(53,this.getDExtAttr10());
      oraclecallablestatement.setDATE(54,this.getLastUpdateDate());
      oraclecallablestatement.setNUMBER(55,this.getLastUpdatedBy());
      oraclecallablestatement.setNUMBER(56,this.getLastUpdateLogin());
      oraclecallablestatement.setString(57,this.getBcPodFlag()); //Code Added by Reddy Sekar for Req# NAIT-61952 and 66520
       oraclecallablestatement.execute();
    }
    catch(SQLException sqlexception)
    {
        throw OAException.wrapperException(sqlexception);
    }
    catch(Exception	exception)
    {
        throw OAException.wrapperException(exception);
    }
	finally
        {
           try{
                if(oraclecallablestatement != null)
                   oraclecallablestatement.close();
              }
		   catch(Exception e){}
        }
    }//Update Row


    public void postChanges(TransactionEvent transactionevent)
  {
    /*
    String CustAcctId = getCustAccountId().toString();
    String errMsg = validateCustDoc(CustAcctId);
    OADBTransaction db=(OADBTransaction)getDBTransaction();
    ODUtil utl=new ODUtil(db);
    utl.log("Calling Post Changes. Test called once");
    if (errMsg!=null)
      throw new OAException("XXCRM",errMsg);
    */
    super.postChanges(transactionevent);
  }

  public void beforeCommit(TransactionEvent transactionevent)
  {
    /*
    OADBTransaction db=(OADBTransaction)getDBTransaction();
    ODUtil utl=new ODUtil(db);
    utl.log("Calling before Commit. Test Please work");
    */
    super.beforeCommit(transactionevent);
  }


    /**Gets the attribute value for BcPodFlag, using the alias name BcPodFlag
     */
    public String getBcPodFlag() {
        return (String)getAttributeInternal(BCPODFLAG);
    }

    /**Sets <code>value</code> as the attribute value for BcPodFlag
     */
    public void setBcPodFlag(String value) {
        setAttributeInternal(BCPODFLAG, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number extensionId) {
        return new Key(new Object[]{extensionId});
    }
}
