package od.oracle.apps.xxcrm.cs.csz.servicerequest.server;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class OD_XXCSTDSPARTSVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public OD_XXCSTDSPARTSVOImpl()
  {
  }
}