DROP TYPE XX_QP_MODIFIERS_PKG_MODIFIER_ FORCE; 
show errors
DROP TYPE QP_MODIFIERS_PUB_MODIFIERS_RE FORCE; 
show errors
DROP TYPE XX_QP_MODIFIERS_PKG_MODIFIERS FORCE; 
show errors
DROP TYPE QP_MODIFIERS_PUB_PRICING_ATTR FORCE; 
show errors
DROP TYPE XX_QP_MODIFIERS_PKG_PRICING_A FORCE; 
show errors
DROP TYPE QP_QUALIFIER_RULES_PUB_QUALIF FORCE; 
show errors
DROP TYPE XX_QP_MODIFIERS_PKG_QUALIFIER FORCE; 
show errors
DROP PACKAGE BPEL_PLMODIFIERSPROCESS;
exit
