<definitions
     name="GetODAmexL3CpcSrvc"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/GetODAmexL3CpcSrvc/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/GetODAmexL3CpcSrvc/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:imp1="http://www.officedepot.com/GetODAmexL3CpcSrvc"
     xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/ftp/"
     xmlns:ns3="http://www.openapplications.org/oagis/9"
    >
    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/" location="ftpAdapterInboundHeader.wsdl"/>
    <import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    
    <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://www.officedepot.com/GetODAmexL3CpcSrvc" schemaLocation="ODAMEXL3CPC.xsd" />
        
      </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.openapplications.org/oagis/9" schemaLocation="http://esbdev02.na.odcorp.net/orabpel/xmllib/eaixml/oagis/v91/message/bod/ProcessInvoice.xsd"/>
            <xsd:import namespace="http://schemas.oracle.com/service/bpel/common" schemaLocation="params.xsd"/>
            
        </xsd:schema>
    </types>
    <message name="container_msg">
        <part name="container" element="imp1:container"/>
    </message>
    <message name="ProcessInvMsg">
        <part name="payload" element="ns3:ProcessInvoice"/>
    </message>
    <portType name="Get_ptt">
        <operation name="Get">
            <input message="tns:container_msg"/>
        </operation>
    </portType>
    <binding name="Get_binding" type="tns:Get_ptt">
    <pc:inbound_binding  />
        <operation name="Get">
      <jca:operation
          FileType="ascii"
          LogicalDirectory="Outbound_Path"
          ActivationSpec="oracle.tip.adapter.ftp.inbound.FTPActivationSpec"
          LogicalArchiveDirectory="Archive_Path"
          DeleteFile="true"
          IncludeFiles="ODAMEXCPC.*\.set"
          PollingFrequency="1800"
          PublishSize="500"
          MinimumAge="60"
          FileModificationTime="FileSystem"
          ModificationTimeFormat="4,18,yyyyMMddHHmmSS"
          OpaqueSchema="false" >
      </jca:operation>
      <input>
        <jca:header message="hdr:InboundHeader_msg" part="inboundHeader"/>
      </input>
        </operation>
    </binding>
    <service name="GetODAmexL3CpcSrvc">
        <port name="Get_pt" binding="tns:Get_binding">
      <jca:address location="eis/ftp/EBSCentralExternal" UIincludeWildcard="ODAMEXL3CPC*.set" />
        </port>
    </service>
  <plt:partnerLinkType name="Get_plt" >
    <plt:role name="Get_role" >
      <plt:portType name="tns:Get_ptt" />
    </plt:role>
  </plt:partnerLinkType>
</definitions>
