-- Declare the SQL type for the PL/SQL type QP_MODIFIERS_PUB.MODIFIER_LIST_REC_TYPE
CREATE OR REPLACE TYPE XX_QP_MODIFIERS_PKG_MODIFIER_ AS OBJECT (
      ATTRIBUTE1 VARCHAR2(240),
      ATTRIBUTE10 VARCHAR2(240),
      ATTRIBUTE11 VARCHAR2(240),
      ATTRIBUTE12 VARCHAR2(240),
      ATTRIBUTE13 VARCHAR2(240),
      ATTRIBUTE14 VARCHAR2(240),
      ATTRIBUTE15 VARCHAR2(240),
      ATTRIBUTE2 VARCHAR2(240),
      ATTRIBUTE3 VARCHAR2(240),
      ATTRIBUTE4 VARCHAR2(240),
      ATTRIBUTE5 VARCHAR2(240),
      ATTRIBUTE6 VARCHAR2(240),
      ATTRIBUTE7 VARCHAR2(240),
      ATTRIBUTE8 VARCHAR2(240),
      ATTRIBUTE9 VARCHAR2(240),
      AUTOMATIC_FLAG VARCHAR2(1),
      COMMENTS VARCHAR2(2000),
      CONTEXT VARCHAR2(30),
      CREATED_BY NUMBER,
      CREATION_DATE DATE,
      CURRENCY_CODE VARCHAR2(30),
      DISCOUNT_LINES_FLAG VARCHAR2(1),
      END_DATE_ACTIVE DATE,
      FREIGHT_TERMS_CODE VARCHAR2(30),
      GSA_INDICATOR VARCHAR2(1),
      LAST_UPDATED_BY NUMBER,
      LAST_UPDATE_DATE DATE,
      LAST_UPDATE_LOGIN NUMBER,
      LIST_HEADER_ID NUMBER,
      LIST_TYPE_CODE VARCHAR2(30),
      PROGRAM_APPLICATION_ID NUMBER,
      PROGRAM_ID NUMBER,
      PROGRAM_UPDATE_DATE DATE,
      PRORATE_FLAG VARCHAR2(30),
      REQUEST_ID NUMBER,
      ROUNDING_FACTOR NUMBER,
      SHIP_METHOD_CODE VARCHAR2(30),
      START_DATE_ACTIVE DATE,
      TERMS_ID NUMBER,
      SOURCE_SYSTEM_CODE VARCHAR2(30),
      ACTIVE_FLAG VARCHAR2(1),
      PARENT_LIST_HEADER_ID NUMBER,
      START_DATE_ACTIVE_FIRST DATE,
      END_DATE_ACTIVE_FIRST DATE,
      ACTIVE_DATE_FIRST_TYPE VARCHAR2(30),
      START_DATE_ACTIVE_SECOND DATE,
      GLOBAL_FLAG VARCHAR2(1),
      END_DATE_ACTIVE_SECOND DATE,
      ACTIVE_DATE_SECOND_TYPE VARCHAR2(30),
      ASK_FOR_FLAG VARCHAR2(1),
      NAME VARCHAR2(240),
      DESCRIPTION VARCHAR2(2000),
      VERSION_NO VARCHAR2(30),
      RETURN_STATUS VARCHAR2(1),
      DB_FLAG VARCHAR2(1),
      OPERATION VARCHAR2(30),
      PTE_CODE VARCHAR2(30),
      LIST_SOURCE_CODE VARCHAR2(30),
      ORIG_SYSTEM_HEADER_REF VARCHAR2(50),
      SHAREABLE_FLAG VARCHAR2(1)
);
/
show errors
-- Declare the SQL type for the PL/SQL type QP_MODIFIERS_PUB.MODIFIERS_REC_TYPE
CREATE OR REPLACE TYPE QP_MODIFIERS_PUB_MODIFIERS_RE AS OBJECT (
      ARITHMETIC_OPERATOR VARCHAR2(30),
      ATTRIBUTE1 VARCHAR2(240),
      ATTRIBUTE10 VARCHAR2(240),
      ATTRIBUTE11 VARCHAR2(240),
      ATTRIBUTE12 VARCHAR2(240),
      ATTRIBUTE13 VARCHAR2(240),
      ATTRIBUTE14 VARCHAR2(240),
      ATTRIBUTE15 VARCHAR2(240),
      ATTRIBUTE2 VARCHAR2(240),
      ATTRIBUTE3 VARCHAR2(240),
      ATTRIBUTE4 VARCHAR2(240),
      ATTRIBUTE5 VARCHAR2(240),
      ATTRIBUTE6 VARCHAR2(240),
      ATTRIBUTE7 VARCHAR2(240),
      ATTRIBUTE8 VARCHAR2(240),
      ATTRIBUTE9 VARCHAR2(240),
      AUTOMATIC_FLAG VARCHAR2(1),
      COMMENTS VARCHAR2(2000),
      CONTEXT VARCHAR2(30),
      CREATED_BY NUMBER,
      CREATION_DATE DATE,
      EFFECTIVE_PERIOD_UOM VARCHAR2(3),
      END_DATE_ACTIVE DATE,
      ESTIM_ACCRUAL_RATE NUMBER,
      GENERATE_USING_FORMULA_ID NUMBER,
      INVENTORY_ITEM_ID NUMBER,
      LAST_UPDATED_BY NUMBER,
      LAST_UPDATE_DATE DATE,
      LAST_UPDATE_LOGIN NUMBER,
      LIST_HEADER_ID NUMBER,
      LIST_LINE_ID NUMBER,
      LIST_LINE_TYPE_CODE VARCHAR2(30),
      LIST_PRICE NUMBER,
      MODIFIER_LEVEL_CODE VARCHAR2(30),
      NUMBER_EFFECTIVE_PERIODS NUMBER,
      OPERAND NUMBER,
      ORGANIZATION_ID NUMBER,
      OVERRIDE_FLAG VARCHAR2(1),
      PERCENT_PRICE NUMBER,
      PRICE_BREAK_TYPE_CODE VARCHAR2(30),
      PRICE_BY_FORMULA_ID NUMBER,
      PRIMARY_UOM_FLAG VARCHAR2(1),
      PRINT_ON_INVOICE_FLAG VARCHAR2(1),
      PROGRAM_APPLICATION_ID NUMBER,
      PROGRAM_ID NUMBER,
      PROGRAM_UPDATE_DATE DATE,
      REBATE_TRXN_TYPE_CODE VARCHAR2(30),
      RELATED_ITEM_ID NUMBER,
      RELATIONSHIP_TYPE_ID NUMBER,
      REPRICE_FLAG VARCHAR2(1),
      REQUEST_ID NUMBER,
      REVISION VARCHAR2(50),
      REVISION_DATE DATE,
      REVISION_REASON_CODE VARCHAR2(30),
      START_DATE_ACTIVE DATE,
      SUBSTITUTION_ATTRIBUTE VARCHAR2(30),
      SUBSTITUTION_CONTEXT VARCHAR2(30),
      SUBSTITUTION_VALUE VARCHAR2(240),
      ACCRUAL_FLAG VARCHAR2(1),
      PRICING_GROUP_SEQUENCE NUMBER,
      INCOMPATIBILITY_GRP_CODE VARCHAR2(30),
      LIST_LINE_NO VARCHAR2(30),
      RLTD_MODIFIER_ID NUMBER,
      FROM_RLTD_MODIFIER_ID NUMBER,
      TO_RLTD_MODIFIER_ID NUMBER,
      RLTD_MODIFIER_GRP_NO NUMBER,
      RLTD_MODIFIER_GRP_TYPE VARCHAR2(30),
      PRICING_PHASE_ID NUMBER,
      PRODUCT_PRECEDENCE NUMBER,
      EXPIRATION_PERIOD_START_DATE DATE,
      NUMBER_EXPIRATION_PERIODS NUMBER,
      EXPIRATION_PERIOD_UOM VARCHAR2(3),
      EXPIRATION_DATE DATE,
      ESTIM_GL_VALUE NUMBER,
      BENEFIT_PRICE_LIST_LINE_ID NUMBER,
      BENEFIT_LIMIT NUMBER,
      CHARGE_TYPE_CODE VARCHAR2(30),
      CHARGE_SUBTYPE_CODE VARCHAR2(30),
      BENEFIT_QTY NUMBER,
      BENEFIT_UOM_CODE VARCHAR2(30),
      ACCRUAL_CONVERSION_RATE NUMBER,
      PRORATION_TYPE_CODE VARCHAR2(30),
      INCLUDE_ON_RETURNS_FLAG VARCHAR2(1),
      RETURN_STATUS VARCHAR2(1),
      DB_FLAG VARCHAR2(1),
      OPERATION VARCHAR2(30),
      MODIFIER_PARENT_INDEX NUMBER,
      QUALIFICATION_IND NUMBER,
      NET_AMOUNT_FLAG VARCHAR2(1),
      ACCUM_ATTRIBUTE VARCHAR2(240)
);
/
show errors
CREATE OR REPLACE TYPE XX_QP_MODIFIERS_PKG_MODIFIERS AS TABLE OF QP_MODIFIERS_PUB_MODIFIERS_RE; 
/
show errors
-- Declare the SQL type for the PL/SQL type QP_MODIFIERS_PUB.PRICING_ATTR_REC_TYPE
CREATE OR REPLACE TYPE QP_MODIFIERS_PUB_PRICING_ATTR AS OBJECT (
      ACCUMULATE_FLAG VARCHAR2(1),
      ATTRIBUTE1 VARCHAR2(240),
      ATTRIBUTE10 VARCHAR2(240),
      ATTRIBUTE11 VARCHAR2(240),
      ATTRIBUTE12 VARCHAR2(240),
      ATTRIBUTE13 VARCHAR2(240),
      ATTRIBUTE14 VARCHAR2(240),
      ATTRIBUTE15 VARCHAR2(240),
      ATTRIBUTE2 VARCHAR2(240),
      ATTRIBUTE3 VARCHAR2(240),
      ATTRIBUTE4 VARCHAR2(240),
      ATTRIBUTE5 VARCHAR2(240),
      ATTRIBUTE6 VARCHAR2(240),
      ATTRIBUTE7 VARCHAR2(240),
      ATTRIBUTE8 VARCHAR2(240),
      ATTRIBUTE9 VARCHAR2(240),
      ATTRIBUTE_GROUPING_NO NUMBER,
      CONTEXT VARCHAR2(30),
      CREATED_BY NUMBER,
      CREATION_DATE DATE,
      EXCLUDER_FLAG VARCHAR2(1),
      LAST_UPDATED_BY NUMBER,
      LAST_UPDATE_DATE DATE,
      LAST_UPDATE_LOGIN NUMBER,
      LIST_LINE_ID NUMBER,
      PRICING_ATTRIBUTE VARCHAR2(30),
      PRICING_ATTRIBUTE_CONTEXT VARCHAR2(30),
      PRICING_ATTRIBUTE_ID NUMBER,
      PRICING_ATTR_VALUE_FROM VARCHAR2(240),
      PRICING_ATTR_VALUE_TO VARCHAR2(240),
      PRODUCT_ATTRIBUTE VARCHAR2(30),
      PRODUCT_ATTRIBUTE_CONTEXT VARCHAR2(30),
      PRODUCT_ATTR_VALUE VARCHAR2(240),
      PRODUCT_UOM_CODE VARCHAR2(3),
      PROGRAM_APPLICATION_ID NUMBER,
      PROGRAM_ID NUMBER,
      PROGRAM_UPDATE_DATE DATE,
      PRODUCT_ATTRIBUTE_DATATYPE VARCHAR2(30),
      PRICING_ATTRIBUTE_DATATYPE VARCHAR2(30),
      COMPARISON_OPERATOR_CODE VARCHAR2(30),
      LIST_HEADER_ID NUMBER,
      PRICING_PHASE_ID NUMBER,
      REQUEST_ID NUMBER,
      PRICING_ATTR_VALUE_FROM_NUMBER NUMBER,
      PRICING_ATTR_VALUE_TO_NUMBER NUMBER,
      QUALIFICATION_IND NUMBER,
      RETURN_STATUS VARCHAR2(1),
      DB_FLAG VARCHAR2(1),
      OPERATION VARCHAR2(30),
      MODIFIERS_INDEX NUMBER
);
/
show errors
CREATE OR REPLACE TYPE XX_QP_MODIFIERS_PKG_PRICING_A AS TABLE OF QP_MODIFIERS_PUB_PRICING_ATTR; 
/
show errors
-- Declare the SQL type for the PL/SQL type QP_QUALIFIER_RULES_PUB.QUALIFIERS_REC_TYPE
CREATE OR REPLACE TYPE QP_QUALIFIER_RULES_PUB_QUALIF AS OBJECT (
      ATTRIBUTE1 VARCHAR2(240),
      ATTRIBUTE10 VARCHAR2(240),
      ATTRIBUTE11 VARCHAR2(240),
      ATTRIBUTE12 VARCHAR2(240),
      ATTRIBUTE13 VARCHAR2(240),
      ATTRIBUTE14 VARCHAR2(240),
      ATTRIBUTE15 VARCHAR2(240),
      ATTRIBUTE2 VARCHAR2(240),
      ATTRIBUTE3 VARCHAR2(240),
      ATTRIBUTE4 VARCHAR2(240),
      ATTRIBUTE5 VARCHAR2(240),
      ATTRIBUTE6 VARCHAR2(240),
      ATTRIBUTE7 VARCHAR2(240),
      ATTRIBUTE8 VARCHAR2(240),
      ATTRIBUTE9 VARCHAR2(240),
      COMPARISON_OPERATOR_CODE VARCHAR2(30),
      CONTEXT VARCHAR2(30),
      CREATED_BY NUMBER,
      CREATED_FROM_RULE_ID NUMBER,
      CREATION_DATE DATE,
      END_DATE_ACTIVE DATE,
      EXCLUDER_FLAG VARCHAR2(1),
      LAST_UPDATED_BY NUMBER,
      LAST_UPDATE_DATE DATE,
      LAST_UPDATE_LOGIN NUMBER,
      LIST_HEADER_ID NUMBER,
      LIST_LINE_ID NUMBER,
      PROGRAM_APPLICATION_ID NUMBER,
      PROGRAM_ID NUMBER,
      PROGRAM_UPDATE_DATE DATE,
      QUALIFIER_ATTRIBUTE VARCHAR2(30),
      QUALIFIER_ATTR_VALUE VARCHAR2(240),
      QUALIFIER_ATTR_VALUE_TO VARCHAR2(240),
      QUALIFIER_CONTEXT VARCHAR2(30),
      QUALIFIER_DATATYPE VARCHAR2(10),
      QUALIFIER_GROUPING_NO NUMBER,
      QUALIFIER_ID NUMBER,
      QUALIFIER_PRECEDENCE NUMBER,
      QUALIFIER_RULE_ID NUMBER,
      REQUEST_ID NUMBER,
      START_DATE_ACTIVE DATE,
      LIST_TYPE_CODE VARCHAR2(30),
      QUAL_ATTR_VALUE_FROM_NUMBER NUMBER,
      QUAL_ATTR_VALUE_TO_NUMBER NUMBER,
      ACTIVE_FLAG VARCHAR2(1),
      SEARCH_IND NUMBER,
      QUALIFIER_GROUP_CNT NUMBER,
      HEADER_QUALS_EXIST_FLAG VARCHAR2(1),
      DISTINCT_ROW_COUNT NUMBER,
      RETURN_STATUS VARCHAR2(1),
      DB_FLAG VARCHAR2(1),
      OPERATION VARCHAR2(30)
);
/
show errors
CREATE OR REPLACE TYPE XX_QP_MODIFIERS_PKG_QUALIFIER AS TABLE OF QP_QUALIFIER_RULES_PUB_QUALIF; 
/
show errors
-- Declare package containing conversion functions between SQL and PL/SQL types
CREATE OR REPLACE PACKAGE BPEL_PLMODIFIERSPROCESS AS
	-- Declare the conversion functions the PL/SQL type QP_MODIFIERS_PUB.MODIFIER_LIST_REC_TYPE
	FUNCTION PL_TO_SQL0(aPlsqlItem QP_MODIFIERS_PUB.MODIFIER_LIST_REC_TYPE)
 	RETURN XX_QP_MODIFIERS_PKG_MODIFIER_;
	FUNCTION SQL_TO_PL0(aSqlItem XX_QP_MODIFIERS_PKG_MODIFIER_)
	RETURN QP_MODIFIERS_PUB.MODIFIER_LIST_REC_TYPE;
	-- Declare the conversion functions the PL/SQL type QP_MODIFIERS_PUB.MODIFIERS_REC_TYPE
	FUNCTION PL_TO_SQL1(aPlsqlItem QP_MODIFIERS_PUB.MODIFIERS_REC_TYPE)
 	RETURN QP_MODIFIERS_PUB_MODIFIERS_RE;
	FUNCTION SQL_TO_PL4(aSqlItem QP_MODIFIERS_PUB_MODIFIERS_RE)
	RETURN QP_MODIFIERS_PUB.MODIFIERS_REC_TYPE;
	-- Declare the conversion functions the PL/SQL type QP_MODIFIERS_PUB.MODIFIERS_TBL_TYPE
	FUNCTION PL_TO_SQL2(aPlsqlItem QP_MODIFIERS_PUB.MODIFIERS_TBL_TYPE)
 	RETURN XX_QP_MODIFIERS_PKG_MODIFIERS;
	FUNCTION SQL_TO_PL1(aSqlItem XX_QP_MODIFIERS_PKG_MODIFIERS)
	RETURN QP_MODIFIERS_PUB.MODIFIERS_TBL_TYPE;
	-- Declare the conversion functions the PL/SQL type QP_MODIFIERS_PUB.PRICING_ATTR_REC_TYPE
	FUNCTION PL_TO_SQL3(aPlsqlItem QP_MODIFIERS_PUB.PRICING_ATTR_REC_TYPE)
 	RETURN QP_MODIFIERS_PUB_PRICING_ATTR;
	FUNCTION SQL_TO_PL5(aSqlItem QP_MODIFIERS_PUB_PRICING_ATTR)
	RETURN QP_MODIFIERS_PUB.PRICING_ATTR_REC_TYPE;
	-- Declare the conversion functions the PL/SQL type QP_MODIFIERS_PUB.PRICING_ATTR_TBL_TYPE
	FUNCTION PL_TO_SQL4(aPlsqlItem QP_MODIFIERS_PUB.PRICING_ATTR_TBL_TYPE)
 	RETURN XX_QP_MODIFIERS_PKG_PRICING_A;
	FUNCTION SQL_TO_PL2(aSqlItem XX_QP_MODIFIERS_PKG_PRICING_A)
	RETURN QP_MODIFIERS_PUB.PRICING_ATTR_TBL_TYPE;
	-- Declare the conversion functions the PL/SQL type QP_QUALIFIER_RULES_PUB.QUALIFIERS_REC_TYPE
	FUNCTION PL_TO_SQL5(aPlsqlItem QP_QUALIFIER_RULES_PUB.QUALIFIERS_REC_TYPE)
 	RETURN QP_QUALIFIER_RULES_PUB_QUALIF;
	FUNCTION SQL_TO_PL6(aSqlItem QP_QUALIFIER_RULES_PUB_QUALIF)
	RETURN QP_QUALIFIER_RULES_PUB.QUALIFIERS_REC_TYPE;
	-- Declare the conversion functions the PL/SQL type QP_QUALIFIER_RULES_PUB.QUALIFIERS_TBL_TYPE
	FUNCTION PL_TO_SQL6(aPlsqlItem QP_QUALIFIER_RULES_PUB.QUALIFIERS_TBL_TYPE)
 	RETURN XX_QP_MODIFIERS_PKG_QUALIFIER;
	FUNCTION SQL_TO_PL3(aSqlItem XX_QP_MODIFIERS_PKG_QUALIFIER)
	RETURN QP_QUALIFIER_RULES_PUB.QUALIFIERS_TBL_TYPE;
   PROCEDURE XX_QP_MODIFIERS_PKG$CREATE_MO (P_MODIFIER_HEADER_REC XX_QP_MODIFIERS_PKG_MODIFIER_,P_MODIFIER_LINES_TBL XX_QP_MODIFIERS_PKG_MODIFIERS,P_MODIFIER_ATTRIBUTES_TBL XX_QP_MODIFIERS_PKG_PRICING_A,P_MODIFIER_QUALIFIERS_TBL XX_QP_MODIFIERS_PKG_QUALIFIER,X_MESSAGE_CODE OUT NUMBER,X_MESSAGE_DATA OUT VARCHAR2);
END BPEL_PLMODIFIERSPROCESS;
/
show errors
CREATE OR REPLACE PACKAGE BODY BPEL_PLMODIFIERSPROCESS IS
	FUNCTION PL_TO_SQL0(aPlsqlItem QP_MODIFIERS_PUB.MODIFIER_LIST_REC_TYPE)
 	RETURN XX_QP_MODIFIERS_PKG_MODIFIER_ IS 
	aSqlItem XX_QP_MODIFIERS_PKG_MODIFIER_; 
	BEGIN 
		-- initialize the object
		aSqlItem := XX_QP_MODIFIERS_PKG_MODIFIER_(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
		aSqlItem.ATTRIBUTE1 := aPlsqlItem.ATTRIBUTE1;
		aSqlItem.ATTRIBUTE10 := aPlsqlItem.ATTRIBUTE10;
		aSqlItem.ATTRIBUTE11 := aPlsqlItem.ATTRIBUTE11;
		aSqlItem.ATTRIBUTE12 := aPlsqlItem.ATTRIBUTE12;
		aSqlItem.ATTRIBUTE13 := aPlsqlItem.ATTRIBUTE13;
		aSqlItem.ATTRIBUTE14 := aPlsqlItem.ATTRIBUTE14;
		aSqlItem.ATTRIBUTE15 := aPlsqlItem.ATTRIBUTE15;
		aSqlItem.ATTRIBUTE2 := aPlsqlItem.ATTRIBUTE2;
		aSqlItem.ATTRIBUTE3 := aPlsqlItem.ATTRIBUTE3;
		aSqlItem.ATTRIBUTE4 := aPlsqlItem.ATTRIBUTE4;
		aSqlItem.ATTRIBUTE5 := aPlsqlItem.ATTRIBUTE5;
		aSqlItem.ATTRIBUTE6 := aPlsqlItem.ATTRIBUTE6;
		aSqlItem.ATTRIBUTE7 := aPlsqlItem.ATTRIBUTE7;
		aSqlItem.ATTRIBUTE8 := aPlsqlItem.ATTRIBUTE8;
		aSqlItem.ATTRIBUTE9 := aPlsqlItem.ATTRIBUTE9;
		aSqlItem.AUTOMATIC_FLAG := aPlsqlItem.AUTOMATIC_FLAG;
		aSqlItem.COMMENTS := aPlsqlItem.COMMENTS;
		aSqlItem.CONTEXT := aPlsqlItem.CONTEXT;
		aSqlItem.CREATED_BY := aPlsqlItem.CREATED_BY;
		aSqlItem.CREATION_DATE := aPlsqlItem.CREATION_DATE;
		aSqlItem.CURRENCY_CODE := aPlsqlItem.CURRENCY_CODE;
		aSqlItem.DISCOUNT_LINES_FLAG := aPlsqlItem.DISCOUNT_LINES_FLAG;
		aSqlItem.END_DATE_ACTIVE := aPlsqlItem.END_DATE_ACTIVE;
		aSqlItem.FREIGHT_TERMS_CODE := aPlsqlItem.FREIGHT_TERMS_CODE;
		aSqlItem.GSA_INDICATOR := aPlsqlItem.GSA_INDICATOR;
		aSqlItem.LAST_UPDATED_BY := aPlsqlItem.LAST_UPDATED_BY;
		aSqlItem.LAST_UPDATE_DATE := aPlsqlItem.LAST_UPDATE_DATE;
		aSqlItem.LAST_UPDATE_LOGIN := aPlsqlItem.LAST_UPDATE_LOGIN;
		aSqlItem.LIST_HEADER_ID := aPlsqlItem.LIST_HEADER_ID;
		aSqlItem.LIST_TYPE_CODE := aPlsqlItem.LIST_TYPE_CODE;
		aSqlItem.PROGRAM_APPLICATION_ID := aPlsqlItem.PROGRAM_APPLICATION_ID;
		aSqlItem.PROGRAM_ID := aPlsqlItem.PROGRAM_ID;
		aSqlItem.PROGRAM_UPDATE_DATE := aPlsqlItem.PROGRAM_UPDATE_DATE;
		aSqlItem.PRORATE_FLAG := aPlsqlItem.PRORATE_FLAG;
		aSqlItem.REQUEST_ID := aPlsqlItem.REQUEST_ID;
		aSqlItem.ROUNDING_FACTOR := aPlsqlItem.ROUNDING_FACTOR;
		aSqlItem.SHIP_METHOD_CODE := aPlsqlItem.SHIP_METHOD_CODE;
		aSqlItem.START_DATE_ACTIVE := aPlsqlItem.START_DATE_ACTIVE;
		aSqlItem.TERMS_ID := aPlsqlItem.TERMS_ID;
		aSqlItem.SOURCE_SYSTEM_CODE := aPlsqlItem.SOURCE_SYSTEM_CODE;
		aSqlItem.ACTIVE_FLAG := aPlsqlItem.ACTIVE_FLAG;
		aSqlItem.PARENT_LIST_HEADER_ID := aPlsqlItem.PARENT_LIST_HEADER_ID;
		aSqlItem.START_DATE_ACTIVE_FIRST := aPlsqlItem.START_DATE_ACTIVE_FIRST;
		aSqlItem.END_DATE_ACTIVE_FIRST := aPlsqlItem.END_DATE_ACTIVE_FIRST;
		aSqlItem.ACTIVE_DATE_FIRST_TYPE := aPlsqlItem.ACTIVE_DATE_FIRST_TYPE;
		aSqlItem.START_DATE_ACTIVE_SECOND := aPlsqlItem.START_DATE_ACTIVE_SECOND;
		aSqlItem.GLOBAL_FLAG := aPlsqlItem.GLOBAL_FLAG;
		aSqlItem.END_DATE_ACTIVE_SECOND := aPlsqlItem.END_DATE_ACTIVE_SECOND;
		aSqlItem.ACTIVE_DATE_SECOND_TYPE := aPlsqlItem.ACTIVE_DATE_SECOND_TYPE;
		aSqlItem.ASK_FOR_FLAG := aPlsqlItem.ASK_FOR_FLAG;
		aSqlItem.NAME := aPlsqlItem.NAME;
		aSqlItem.DESCRIPTION := aPlsqlItem.DESCRIPTION;
		aSqlItem.VERSION_NO := aPlsqlItem.VERSION_NO;
		aSqlItem.RETURN_STATUS := aPlsqlItem.RETURN_STATUS;
		aSqlItem.DB_FLAG := aPlsqlItem.DB_FLAG;
		aSqlItem.OPERATION := aPlsqlItem.OPERATION;
		aSqlItem.PTE_CODE := aPlsqlItem.PTE_CODE;
		aSqlItem.LIST_SOURCE_CODE := aPlsqlItem.LIST_SOURCE_CODE;
		aSqlItem.ORIG_SYSTEM_HEADER_REF := aPlsqlItem.ORIG_SYSTEM_HEADER_REF;
		aSqlItem.SHAREABLE_FLAG := aPlsqlItem.SHAREABLE_FLAG;
		RETURN aSqlItem;
	END PL_TO_SQL0;
	FUNCTION SQL_TO_PL0(aSqlItem XX_QP_MODIFIERS_PKG_MODIFIER_) 
	RETURN QP_MODIFIERS_PUB.MODIFIER_LIST_REC_TYPE IS 
	aPlsqlItem QP_MODIFIERS_PUB.MODIFIER_LIST_REC_TYPE; 
	BEGIN 
		aPlsqlItem.ATTRIBUTE1 := aSqlItem.ATTRIBUTE1;
		aPlsqlItem.ATTRIBUTE10 := aSqlItem.ATTRIBUTE10;
		aPlsqlItem.ATTRIBUTE11 := aSqlItem.ATTRIBUTE11;
		aPlsqlItem.ATTRIBUTE12 := aSqlItem.ATTRIBUTE12;
		aPlsqlItem.ATTRIBUTE13 := aSqlItem.ATTRIBUTE13;
		aPlsqlItem.ATTRIBUTE14 := aSqlItem.ATTRIBUTE14;
		aPlsqlItem.ATTRIBUTE15 := aSqlItem.ATTRIBUTE15;
		aPlsqlItem.ATTRIBUTE2 := aSqlItem.ATTRIBUTE2;
		aPlsqlItem.ATTRIBUTE3 := aSqlItem.ATTRIBUTE3;
		aPlsqlItem.ATTRIBUTE4 := aSqlItem.ATTRIBUTE4;
		aPlsqlItem.ATTRIBUTE5 := aSqlItem.ATTRIBUTE5;
		aPlsqlItem.ATTRIBUTE6 := aSqlItem.ATTRIBUTE6;
		aPlsqlItem.ATTRIBUTE7 := aSqlItem.ATTRIBUTE7;
		aPlsqlItem.ATTRIBUTE8 := aSqlItem.ATTRIBUTE8;
		aPlsqlItem.ATTRIBUTE9 := aSqlItem.ATTRIBUTE9;
		aPlsqlItem.AUTOMATIC_FLAG := aSqlItem.AUTOMATIC_FLAG;
		aPlsqlItem.COMMENTS := aSqlItem.COMMENTS;
		aPlsqlItem.CONTEXT := aSqlItem.CONTEXT;
		aPlsqlItem.CREATED_BY := aSqlItem.CREATED_BY;
		aPlsqlItem.CREATION_DATE := aSqlItem.CREATION_DATE;
		aPlsqlItem.CURRENCY_CODE := aSqlItem.CURRENCY_CODE;
		aPlsqlItem.DISCOUNT_LINES_FLAG := aSqlItem.DISCOUNT_LINES_FLAG;
		aPlsqlItem.END_DATE_ACTIVE := aSqlItem.END_DATE_ACTIVE;
		aPlsqlItem.FREIGHT_TERMS_CODE := aSqlItem.FREIGHT_TERMS_CODE;
		aPlsqlItem.GSA_INDICATOR := aSqlItem.GSA_INDICATOR;
		aPlsqlItem.LAST_UPDATED_BY := aSqlItem.LAST_UPDATED_BY;
		aPlsqlItem.LAST_UPDATE_DATE := aSqlItem.LAST_UPDATE_DATE;
		aPlsqlItem.LAST_UPDATE_LOGIN := aSqlItem.LAST_UPDATE_LOGIN;
		aPlsqlItem.LIST_HEADER_ID := aSqlItem.LIST_HEADER_ID;
		aPlsqlItem.LIST_TYPE_CODE := aSqlItem.LIST_TYPE_CODE;
		aPlsqlItem.PROGRAM_APPLICATION_ID := aSqlItem.PROGRAM_APPLICATION_ID;
		aPlsqlItem.PROGRAM_ID := aSqlItem.PROGRAM_ID;
		aPlsqlItem.PROGRAM_UPDATE_DATE := aSqlItem.PROGRAM_UPDATE_DATE;
		aPlsqlItem.PRORATE_FLAG := aSqlItem.PRORATE_FLAG;
		aPlsqlItem.REQUEST_ID := aSqlItem.REQUEST_ID;
		aPlsqlItem.ROUNDING_FACTOR := aSqlItem.ROUNDING_FACTOR;
		aPlsqlItem.SHIP_METHOD_CODE := aSqlItem.SHIP_METHOD_CODE;
		aPlsqlItem.START_DATE_ACTIVE := aSqlItem.START_DATE_ACTIVE;
		aPlsqlItem.TERMS_ID := aSqlItem.TERMS_ID;
		aPlsqlItem.SOURCE_SYSTEM_CODE := aSqlItem.SOURCE_SYSTEM_CODE;
		aPlsqlItem.ACTIVE_FLAG := aSqlItem.ACTIVE_FLAG;
		aPlsqlItem.PARENT_LIST_HEADER_ID := aSqlItem.PARENT_LIST_HEADER_ID;
		aPlsqlItem.START_DATE_ACTIVE_FIRST := aSqlItem.START_DATE_ACTIVE_FIRST;
		aPlsqlItem.END_DATE_ACTIVE_FIRST := aSqlItem.END_DATE_ACTIVE_FIRST;
		aPlsqlItem.ACTIVE_DATE_FIRST_TYPE := aSqlItem.ACTIVE_DATE_FIRST_TYPE;
		aPlsqlItem.START_DATE_ACTIVE_SECOND := aSqlItem.START_DATE_ACTIVE_SECOND;
		aPlsqlItem.GLOBAL_FLAG := aSqlItem.GLOBAL_FLAG;
		aPlsqlItem.END_DATE_ACTIVE_SECOND := aSqlItem.END_DATE_ACTIVE_SECOND;
		aPlsqlItem.ACTIVE_DATE_SECOND_TYPE := aSqlItem.ACTIVE_DATE_SECOND_TYPE;
		aPlsqlItem.ASK_FOR_FLAG := aSqlItem.ASK_FOR_FLAG;
		aPlsqlItem.NAME := aSqlItem.NAME;
		aPlsqlItem.DESCRIPTION := aSqlItem.DESCRIPTION;
		aPlsqlItem.VERSION_NO := aSqlItem.VERSION_NO;
		aPlsqlItem.RETURN_STATUS := aSqlItem.RETURN_STATUS;
		aPlsqlItem.DB_FLAG := aSqlItem.DB_FLAG;
		aPlsqlItem.OPERATION := aSqlItem.OPERATION;
		aPlsqlItem.PTE_CODE := aSqlItem.PTE_CODE;
		aPlsqlItem.LIST_SOURCE_CODE := aSqlItem.LIST_SOURCE_CODE;
		aPlsqlItem.ORIG_SYSTEM_HEADER_REF := aSqlItem.ORIG_SYSTEM_HEADER_REF;
		aPlsqlItem.SHAREABLE_FLAG := aSqlItem.SHAREABLE_FLAG;
		RETURN aPlsqlItem;
	END SQL_TO_PL0;
	FUNCTION PL_TO_SQL1(aPlsqlItem QP_MODIFIERS_PUB.MODIFIERS_REC_TYPE)
 	RETURN QP_MODIFIERS_PUB_MODIFIERS_RE IS 
	aSqlItem QP_MODIFIERS_PUB_MODIFIERS_RE; 
	BEGIN 
		-- initialize the object
		aSqlItem := QP_MODIFIERS_PUB_MODIFIERS_RE(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
		aSqlItem.ARITHMETIC_OPERATOR := aPlsqlItem.ARITHMETIC_OPERATOR;
		aSqlItem.ATTRIBUTE1 := aPlsqlItem.ATTRIBUTE1;
		aSqlItem.ATTRIBUTE10 := aPlsqlItem.ATTRIBUTE10;
		aSqlItem.ATTRIBUTE11 := aPlsqlItem.ATTRIBUTE11;
		aSqlItem.ATTRIBUTE12 := aPlsqlItem.ATTRIBUTE12;
		aSqlItem.ATTRIBUTE13 := aPlsqlItem.ATTRIBUTE13;
		aSqlItem.ATTRIBUTE14 := aPlsqlItem.ATTRIBUTE14;
		aSqlItem.ATTRIBUTE15 := aPlsqlItem.ATTRIBUTE15;
		aSqlItem.ATTRIBUTE2 := aPlsqlItem.ATTRIBUTE2;
		aSqlItem.ATTRIBUTE3 := aPlsqlItem.ATTRIBUTE3;
		aSqlItem.ATTRIBUTE4 := aPlsqlItem.ATTRIBUTE4;
		aSqlItem.ATTRIBUTE5 := aPlsqlItem.ATTRIBUTE5;
		aSqlItem.ATTRIBUTE6 := aPlsqlItem.ATTRIBUTE6;
		aSqlItem.ATTRIBUTE7 := aPlsqlItem.ATTRIBUTE7;
		aSqlItem.ATTRIBUTE8 := aPlsqlItem.ATTRIBUTE8;
		aSqlItem.ATTRIBUTE9 := aPlsqlItem.ATTRIBUTE9;
		aSqlItem.AUTOMATIC_FLAG := aPlsqlItem.AUTOMATIC_FLAG;
		aSqlItem.COMMENTS := aPlsqlItem.COMMENTS;
		aSqlItem.CONTEXT := aPlsqlItem.CONTEXT;
		aSqlItem.CREATED_BY := aPlsqlItem.CREATED_BY;
		aSqlItem.CREATION_DATE := aPlsqlItem.CREATION_DATE;
		aSqlItem.EFFECTIVE_PERIOD_UOM := aPlsqlItem.EFFECTIVE_PERIOD_UOM;
		aSqlItem.END_DATE_ACTIVE := aPlsqlItem.END_DATE_ACTIVE;
		aSqlItem.ESTIM_ACCRUAL_RATE := aPlsqlItem.ESTIM_ACCRUAL_RATE;
		aSqlItem.GENERATE_USING_FORMULA_ID := aPlsqlItem.GENERATE_USING_FORMULA_ID;
		aSqlItem.INVENTORY_ITEM_ID := aPlsqlItem.INVENTORY_ITEM_ID;
		aSqlItem.LAST_UPDATED_BY := aPlsqlItem.LAST_UPDATED_BY;
		aSqlItem.LAST_UPDATE_DATE := aPlsqlItem.LAST_UPDATE_DATE;
		aSqlItem.LAST_UPDATE_LOGIN := aPlsqlItem.LAST_UPDATE_LOGIN;
		aSqlItem.LIST_HEADER_ID := aPlsqlItem.LIST_HEADER_ID;
		aSqlItem.LIST_LINE_ID := aPlsqlItem.LIST_LINE_ID;
		aSqlItem.LIST_LINE_TYPE_CODE := aPlsqlItem.LIST_LINE_TYPE_CODE;
		aSqlItem.LIST_PRICE := aPlsqlItem.LIST_PRICE;
		aSqlItem.MODIFIER_LEVEL_CODE := aPlsqlItem.MODIFIER_LEVEL_CODE;
		aSqlItem.NUMBER_EFFECTIVE_PERIODS := aPlsqlItem.NUMBER_EFFECTIVE_PERIODS;
		aSqlItem.OPERAND := aPlsqlItem.OPERAND;
		aSqlItem.ORGANIZATION_ID := aPlsqlItem.ORGANIZATION_ID;
		aSqlItem.OVERRIDE_FLAG := aPlsqlItem.OVERRIDE_FLAG;
		aSqlItem.PERCENT_PRICE := aPlsqlItem.PERCENT_PRICE;
		aSqlItem.PRICE_BREAK_TYPE_CODE := aPlsqlItem.PRICE_BREAK_TYPE_CODE;
		aSqlItem.PRICE_BY_FORMULA_ID := aPlsqlItem.PRICE_BY_FORMULA_ID;
		aSqlItem.PRIMARY_UOM_FLAG := aPlsqlItem.PRIMARY_UOM_FLAG;
		aSqlItem.PRINT_ON_INVOICE_FLAG := aPlsqlItem.PRINT_ON_INVOICE_FLAG;
		aSqlItem.PROGRAM_APPLICATION_ID := aPlsqlItem.PROGRAM_APPLICATION_ID;
		aSqlItem.PROGRAM_ID := aPlsqlItem.PROGRAM_ID;
		aSqlItem.PROGRAM_UPDATE_DATE := aPlsqlItem.PROGRAM_UPDATE_DATE;
		aSqlItem.REBATE_TRXN_TYPE_CODE := aPlsqlItem.REBATE_TRXN_TYPE_CODE;
		aSqlItem.RELATED_ITEM_ID := aPlsqlItem.RELATED_ITEM_ID;
		aSqlItem.RELATIONSHIP_TYPE_ID := aPlsqlItem.RELATIONSHIP_TYPE_ID;
		aSqlItem.REPRICE_FLAG := aPlsqlItem.REPRICE_FLAG;
		aSqlItem.REQUEST_ID := aPlsqlItem.REQUEST_ID;
		aSqlItem.REVISION := aPlsqlItem.REVISION;
		aSqlItem.REVISION_DATE := aPlsqlItem.REVISION_DATE;
		aSqlItem.REVISION_REASON_CODE := aPlsqlItem.REVISION_REASON_CODE;
		aSqlItem.START_DATE_ACTIVE := aPlsqlItem.START_DATE_ACTIVE;
		aSqlItem.SUBSTITUTION_ATTRIBUTE := aPlsqlItem.SUBSTITUTION_ATTRIBUTE;
		aSqlItem.SUBSTITUTION_CONTEXT := aPlsqlItem.SUBSTITUTION_CONTEXT;
		aSqlItem.SUBSTITUTION_VALUE := aPlsqlItem.SUBSTITUTION_VALUE;
		aSqlItem.ACCRUAL_FLAG := aPlsqlItem.ACCRUAL_FLAG;
		aSqlItem.PRICING_GROUP_SEQUENCE := aPlsqlItem.PRICING_GROUP_SEQUENCE;
		aSqlItem.INCOMPATIBILITY_GRP_CODE := aPlsqlItem.INCOMPATIBILITY_GRP_CODE;
		aSqlItem.LIST_LINE_NO := aPlsqlItem.LIST_LINE_NO;
		aSqlItem.RLTD_MODIFIER_ID := aPlsqlItem.RLTD_MODIFIER_ID;
		aSqlItem.FROM_RLTD_MODIFIER_ID := aPlsqlItem.FROM_RLTD_MODIFIER_ID;
		aSqlItem.TO_RLTD_MODIFIER_ID := aPlsqlItem.TO_RLTD_MODIFIER_ID;
		aSqlItem.RLTD_MODIFIER_GRP_NO := aPlsqlItem.RLTD_MODIFIER_GRP_NO;
		aSqlItem.RLTD_MODIFIER_GRP_TYPE := aPlsqlItem.RLTD_MODIFIER_GRP_TYPE;
		aSqlItem.PRICING_PHASE_ID := aPlsqlItem.PRICING_PHASE_ID;
		aSqlItem.PRODUCT_PRECEDENCE := aPlsqlItem.PRODUCT_PRECEDENCE;
		aSqlItem.EXPIRATION_PERIOD_START_DATE := aPlsqlItem.EXPIRATION_PERIOD_START_DATE;
		aSqlItem.NUMBER_EXPIRATION_PERIODS := aPlsqlItem.NUMBER_EXPIRATION_PERIODS;
		aSqlItem.EXPIRATION_PERIOD_UOM := aPlsqlItem.EXPIRATION_PERIOD_UOM;
		aSqlItem.EXPIRATION_DATE := aPlsqlItem.EXPIRATION_DATE;
		aSqlItem.ESTIM_GL_VALUE := aPlsqlItem.ESTIM_GL_VALUE;
		aSqlItem.BENEFIT_PRICE_LIST_LINE_ID := aPlsqlItem.BENEFIT_PRICE_LIST_LINE_ID;
		aSqlItem.BENEFIT_LIMIT := aPlsqlItem.BENEFIT_LIMIT;
		aSqlItem.CHARGE_TYPE_CODE := aPlsqlItem.CHARGE_TYPE_CODE;
		aSqlItem.CHARGE_SUBTYPE_CODE := aPlsqlItem.CHARGE_SUBTYPE_CODE;
		aSqlItem.BENEFIT_QTY := aPlsqlItem.BENEFIT_QTY;
		aSqlItem.BENEFIT_UOM_CODE := aPlsqlItem.BENEFIT_UOM_CODE;
		aSqlItem.ACCRUAL_CONVERSION_RATE := aPlsqlItem.ACCRUAL_CONVERSION_RATE;
		aSqlItem.PRORATION_TYPE_CODE := aPlsqlItem.PRORATION_TYPE_CODE;
		aSqlItem.INCLUDE_ON_RETURNS_FLAG := aPlsqlItem.INCLUDE_ON_RETURNS_FLAG;
		aSqlItem.RETURN_STATUS := aPlsqlItem.RETURN_STATUS;
		aSqlItem.DB_FLAG := aPlsqlItem.DB_FLAG;
		aSqlItem.OPERATION := aPlsqlItem.OPERATION;
		aSqlItem.MODIFIER_PARENT_INDEX := aPlsqlItem.MODIFIER_PARENT_INDEX;
		aSqlItem.QUALIFICATION_IND := aPlsqlItem.QUALIFICATION_IND;
		aSqlItem.NET_AMOUNT_FLAG := aPlsqlItem.NET_AMOUNT_FLAG;
		aSqlItem.ACCUM_ATTRIBUTE := aPlsqlItem.ACCUM_ATTRIBUTE;
		RETURN aSqlItem;
	END PL_TO_SQL1;
	FUNCTION SQL_TO_PL4(aSqlItem QP_MODIFIERS_PUB_MODIFIERS_RE) 
	RETURN QP_MODIFIERS_PUB.MODIFIERS_REC_TYPE IS 
	aPlsqlItem QP_MODIFIERS_PUB.MODIFIERS_REC_TYPE; 
	BEGIN 
		aPlsqlItem.ARITHMETIC_OPERATOR := aSqlItem.ARITHMETIC_OPERATOR;
		aPlsqlItem.ATTRIBUTE1 := aSqlItem.ATTRIBUTE1;
		aPlsqlItem.ATTRIBUTE10 := aSqlItem.ATTRIBUTE10;
		aPlsqlItem.ATTRIBUTE11 := aSqlItem.ATTRIBUTE11;
		aPlsqlItem.ATTRIBUTE12 := aSqlItem.ATTRIBUTE12;
		aPlsqlItem.ATTRIBUTE13 := aSqlItem.ATTRIBUTE13;
		aPlsqlItem.ATTRIBUTE14 := aSqlItem.ATTRIBUTE14;
		aPlsqlItem.ATTRIBUTE15 := aSqlItem.ATTRIBUTE15;
		aPlsqlItem.ATTRIBUTE2 := aSqlItem.ATTRIBUTE2;
		aPlsqlItem.ATTRIBUTE3 := aSqlItem.ATTRIBUTE3;
		aPlsqlItem.ATTRIBUTE4 := aSqlItem.ATTRIBUTE4;
		aPlsqlItem.ATTRIBUTE5 := aSqlItem.ATTRIBUTE5;
		aPlsqlItem.ATTRIBUTE6 := aSqlItem.ATTRIBUTE6;
		aPlsqlItem.ATTRIBUTE7 := aSqlItem.ATTRIBUTE7;
		aPlsqlItem.ATTRIBUTE8 := aSqlItem.ATTRIBUTE8;
		aPlsqlItem.ATTRIBUTE9 := aSqlItem.ATTRIBUTE9;
		aPlsqlItem.AUTOMATIC_FLAG := aSqlItem.AUTOMATIC_FLAG;
		aPlsqlItem.COMMENTS := aSqlItem.COMMENTS;
		aPlsqlItem.CONTEXT := aSqlItem.CONTEXT;
		aPlsqlItem.CREATED_BY := aSqlItem.CREATED_BY;
		aPlsqlItem.CREATION_DATE := aSqlItem.CREATION_DATE;
		aPlsqlItem.EFFECTIVE_PERIOD_UOM := aSqlItem.EFFECTIVE_PERIOD_UOM;
		aPlsqlItem.END_DATE_ACTIVE := aSqlItem.END_DATE_ACTIVE;
		aPlsqlItem.ESTIM_ACCRUAL_RATE := aSqlItem.ESTIM_ACCRUAL_RATE;
		aPlsqlItem.GENERATE_USING_FORMULA_ID := aSqlItem.GENERATE_USING_FORMULA_ID;
		aPlsqlItem.INVENTORY_ITEM_ID := aSqlItem.INVENTORY_ITEM_ID;
		aPlsqlItem.LAST_UPDATED_BY := aSqlItem.LAST_UPDATED_BY;
		aPlsqlItem.LAST_UPDATE_DATE := aSqlItem.LAST_UPDATE_DATE;
		aPlsqlItem.LAST_UPDATE_LOGIN := aSqlItem.LAST_UPDATE_LOGIN;
		aPlsqlItem.LIST_HEADER_ID := aSqlItem.LIST_HEADER_ID;
		aPlsqlItem.LIST_LINE_ID := aSqlItem.LIST_LINE_ID;
		aPlsqlItem.LIST_LINE_TYPE_CODE := aSqlItem.LIST_LINE_TYPE_CODE;
		aPlsqlItem.LIST_PRICE := aSqlItem.LIST_PRICE;
		aPlsqlItem.MODIFIER_LEVEL_CODE := aSqlItem.MODIFIER_LEVEL_CODE;
		aPlsqlItem.NUMBER_EFFECTIVE_PERIODS := aSqlItem.NUMBER_EFFECTIVE_PERIODS;
		aPlsqlItem.OPERAND := aSqlItem.OPERAND;
		aPlsqlItem.ORGANIZATION_ID := aSqlItem.ORGANIZATION_ID;
		aPlsqlItem.OVERRIDE_FLAG := aSqlItem.OVERRIDE_FLAG;
		aPlsqlItem.PERCENT_PRICE := aSqlItem.PERCENT_PRICE;
		aPlsqlItem.PRICE_BREAK_TYPE_CODE := aSqlItem.PRICE_BREAK_TYPE_CODE;
		aPlsqlItem.PRICE_BY_FORMULA_ID := aSqlItem.PRICE_BY_FORMULA_ID;
		aPlsqlItem.PRIMARY_UOM_FLAG := aSqlItem.PRIMARY_UOM_FLAG;
		aPlsqlItem.PRINT_ON_INVOICE_FLAG := aSqlItem.PRINT_ON_INVOICE_FLAG;
		aPlsqlItem.PROGRAM_APPLICATION_ID := aSqlItem.PROGRAM_APPLICATION_ID;
		aPlsqlItem.PROGRAM_ID := aSqlItem.PROGRAM_ID;
		aPlsqlItem.PROGRAM_UPDATE_DATE := aSqlItem.PROGRAM_UPDATE_DATE;
		aPlsqlItem.REBATE_TRXN_TYPE_CODE := aSqlItem.REBATE_TRXN_TYPE_CODE;
		aPlsqlItem.RELATED_ITEM_ID := aSqlItem.RELATED_ITEM_ID;
		aPlsqlItem.RELATIONSHIP_TYPE_ID := aSqlItem.RELATIONSHIP_TYPE_ID;
		aPlsqlItem.REPRICE_FLAG := aSqlItem.REPRICE_FLAG;
		aPlsqlItem.REQUEST_ID := aSqlItem.REQUEST_ID;
		aPlsqlItem.REVISION := aSqlItem.REVISION;
		aPlsqlItem.REVISION_DATE := aSqlItem.REVISION_DATE;
		aPlsqlItem.REVISION_REASON_CODE := aSqlItem.REVISION_REASON_CODE;
		aPlsqlItem.START_DATE_ACTIVE := aSqlItem.START_DATE_ACTIVE;
		aPlsqlItem.SUBSTITUTION_ATTRIBUTE := aSqlItem.SUBSTITUTION_ATTRIBUTE;
		aPlsqlItem.SUBSTITUTION_CONTEXT := aSqlItem.SUBSTITUTION_CONTEXT;
		aPlsqlItem.SUBSTITUTION_VALUE := aSqlItem.SUBSTITUTION_VALUE;
		aPlsqlItem.ACCRUAL_FLAG := aSqlItem.ACCRUAL_FLAG;
		aPlsqlItem.PRICING_GROUP_SEQUENCE := aSqlItem.PRICING_GROUP_SEQUENCE;
		aPlsqlItem.INCOMPATIBILITY_GRP_CODE := aSqlItem.INCOMPATIBILITY_GRP_CODE;
		aPlsqlItem.LIST_LINE_NO := aSqlItem.LIST_LINE_NO;
		aPlsqlItem.RLTD_MODIFIER_ID := aSqlItem.RLTD_MODIFIER_ID;
		aPlsqlItem.FROM_RLTD_MODIFIER_ID := aSqlItem.FROM_RLTD_MODIFIER_ID;
		aPlsqlItem.TO_RLTD_MODIFIER_ID := aSqlItem.TO_RLTD_MODIFIER_ID;
		aPlsqlItem.RLTD_MODIFIER_GRP_NO := aSqlItem.RLTD_MODIFIER_GRP_NO;
		aPlsqlItem.RLTD_MODIFIER_GRP_TYPE := aSqlItem.RLTD_MODIFIER_GRP_TYPE;
		aPlsqlItem.PRICING_PHASE_ID := aSqlItem.PRICING_PHASE_ID;
		aPlsqlItem.PRODUCT_PRECEDENCE := aSqlItem.PRODUCT_PRECEDENCE;
		aPlsqlItem.EXPIRATION_PERIOD_START_DATE := aSqlItem.EXPIRATION_PERIOD_START_DATE;
		aPlsqlItem.NUMBER_EXPIRATION_PERIODS := aSqlItem.NUMBER_EXPIRATION_PERIODS;
		aPlsqlItem.EXPIRATION_PERIOD_UOM := aSqlItem.EXPIRATION_PERIOD_UOM;
		aPlsqlItem.EXPIRATION_DATE := aSqlItem.EXPIRATION_DATE;
		aPlsqlItem.ESTIM_GL_VALUE := aSqlItem.ESTIM_GL_VALUE;
		aPlsqlItem.BENEFIT_PRICE_LIST_LINE_ID := aSqlItem.BENEFIT_PRICE_LIST_LINE_ID;
		aPlsqlItem.BENEFIT_LIMIT := aSqlItem.BENEFIT_LIMIT;
		aPlsqlItem.CHARGE_TYPE_CODE := aSqlItem.CHARGE_TYPE_CODE;
		aPlsqlItem.CHARGE_SUBTYPE_CODE := aSqlItem.CHARGE_SUBTYPE_CODE;
		aPlsqlItem.BENEFIT_QTY := aSqlItem.BENEFIT_QTY;
		aPlsqlItem.BENEFIT_UOM_CODE := aSqlItem.BENEFIT_UOM_CODE;
		aPlsqlItem.ACCRUAL_CONVERSION_RATE := aSqlItem.ACCRUAL_CONVERSION_RATE;
		aPlsqlItem.PRORATION_TYPE_CODE := aSqlItem.PRORATION_TYPE_CODE;
		aPlsqlItem.INCLUDE_ON_RETURNS_FLAG := aSqlItem.INCLUDE_ON_RETURNS_FLAG;
		aPlsqlItem.RETURN_STATUS := aSqlItem.RETURN_STATUS;
		aPlsqlItem.DB_FLAG := aSqlItem.DB_FLAG;
		aPlsqlItem.OPERATION := aSqlItem.OPERATION;
		aPlsqlItem.MODIFIER_PARENT_INDEX := aSqlItem.MODIFIER_PARENT_INDEX;
		aPlsqlItem.QUALIFICATION_IND := aSqlItem.QUALIFICATION_IND;
		aPlsqlItem.NET_AMOUNT_FLAG := aSqlItem.NET_AMOUNT_FLAG;
		aPlsqlItem.ACCUM_ATTRIBUTE := aSqlItem.ACCUM_ATTRIBUTE;
		RETURN aPlsqlItem;
	END SQL_TO_PL4;
	FUNCTION PL_TO_SQL2(aPlsqlItem QP_MODIFIERS_PUB.MODIFIERS_TBL_TYPE)
 	RETURN XX_QP_MODIFIERS_PKG_MODIFIERS IS 
	aSqlItem XX_QP_MODIFIERS_PKG_MODIFIERS; 
	BEGIN 
		-- initialize the table 
		aSqlItem := XX_QP_MODIFIERS_PKG_MODIFIERS();
		aSqlItem.EXTEND(aPlsqlItem.COUNT);
		FOR I IN aPlsqlItem.FIRST..aPlsqlItem.LAST LOOP
			aSqlItem(I + 1 - aPlsqlItem.FIRST) := PL_TO_SQL1(aPlsqlItem(I));
		END LOOP; 
		RETURN aSqlItem;
	END PL_TO_SQL2;
	FUNCTION SQL_TO_PL1(aSqlItem XX_QP_MODIFIERS_PKG_MODIFIERS) 
	RETURN QP_MODIFIERS_PUB.MODIFIERS_TBL_TYPE IS 
	aPlsqlItem QP_MODIFIERS_PUB.MODIFIERS_TBL_TYPE; 
	BEGIN 
		FOR I IN 1..aSqlItem.COUNT LOOP
			aPlsqlItem(I) := SQL_TO_PL4(aSqlItem(I));
		END LOOP; 
		RETURN aPlsqlItem;
	END SQL_TO_PL1;
	FUNCTION PL_TO_SQL3(aPlsqlItem QP_MODIFIERS_PUB.PRICING_ATTR_REC_TYPE)
 	RETURN QP_MODIFIERS_PUB_PRICING_ATTR IS 
	aSqlItem QP_MODIFIERS_PUB_PRICING_ATTR; 
	BEGIN 
		-- initialize the object
		aSqlItem := QP_MODIFIERS_PUB_PRICING_ATTR(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
		aSqlItem.ACCUMULATE_FLAG := aPlsqlItem.ACCUMULATE_FLAG;
		aSqlItem.ATTRIBUTE1 := aPlsqlItem.ATTRIBUTE1;
		aSqlItem.ATTRIBUTE10 := aPlsqlItem.ATTRIBUTE10;
		aSqlItem.ATTRIBUTE11 := aPlsqlItem.ATTRIBUTE11;
		aSqlItem.ATTRIBUTE12 := aPlsqlItem.ATTRIBUTE12;
		aSqlItem.ATTRIBUTE13 := aPlsqlItem.ATTRIBUTE13;
		aSqlItem.ATTRIBUTE14 := aPlsqlItem.ATTRIBUTE14;
		aSqlItem.ATTRIBUTE15 := aPlsqlItem.ATTRIBUTE15;
		aSqlItem.ATTRIBUTE2 := aPlsqlItem.ATTRIBUTE2;
		aSqlItem.ATTRIBUTE3 := aPlsqlItem.ATTRIBUTE3;
		aSqlItem.ATTRIBUTE4 := aPlsqlItem.ATTRIBUTE4;
		aSqlItem.ATTRIBUTE5 := aPlsqlItem.ATTRIBUTE5;
		aSqlItem.ATTRIBUTE6 := aPlsqlItem.ATTRIBUTE6;
		aSqlItem.ATTRIBUTE7 := aPlsqlItem.ATTRIBUTE7;
		aSqlItem.ATTRIBUTE8 := aPlsqlItem.ATTRIBUTE8;
		aSqlItem.ATTRIBUTE9 := aPlsqlItem.ATTRIBUTE9;
		aSqlItem.ATTRIBUTE_GROUPING_NO := aPlsqlItem.ATTRIBUTE_GROUPING_NO;
		aSqlItem.CONTEXT := aPlsqlItem.CONTEXT;
		aSqlItem.CREATED_BY := aPlsqlItem.CREATED_BY;
		aSqlItem.CREATION_DATE := aPlsqlItem.CREATION_DATE;
		aSqlItem.EXCLUDER_FLAG := aPlsqlItem.EXCLUDER_FLAG;
		aSqlItem.LAST_UPDATED_BY := aPlsqlItem.LAST_UPDATED_BY;
		aSqlItem.LAST_UPDATE_DATE := aPlsqlItem.LAST_UPDATE_DATE;
		aSqlItem.LAST_UPDATE_LOGIN := aPlsqlItem.LAST_UPDATE_LOGIN;
		aSqlItem.LIST_LINE_ID := aPlsqlItem.LIST_LINE_ID;
		aSqlItem.PRICING_ATTRIBUTE := aPlsqlItem.PRICING_ATTRIBUTE;
		aSqlItem.PRICING_ATTRIBUTE_CONTEXT := aPlsqlItem.PRICING_ATTRIBUTE_CONTEXT;
		aSqlItem.PRICING_ATTRIBUTE_ID := aPlsqlItem.PRICING_ATTRIBUTE_ID;
		aSqlItem.PRICING_ATTR_VALUE_FROM := aPlsqlItem.PRICING_ATTR_VALUE_FROM;
		aSqlItem.PRICING_ATTR_VALUE_TO := aPlsqlItem.PRICING_ATTR_VALUE_TO;
		aSqlItem.PRODUCT_ATTRIBUTE := aPlsqlItem.PRODUCT_ATTRIBUTE;
		aSqlItem.PRODUCT_ATTRIBUTE_CONTEXT := aPlsqlItem.PRODUCT_ATTRIBUTE_CONTEXT;
		aSqlItem.PRODUCT_ATTR_VALUE := aPlsqlItem.PRODUCT_ATTR_VALUE;
		aSqlItem.PRODUCT_UOM_CODE := aPlsqlItem.PRODUCT_UOM_CODE;
		aSqlItem.PROGRAM_APPLICATION_ID := aPlsqlItem.PROGRAM_APPLICATION_ID;
		aSqlItem.PROGRAM_ID := aPlsqlItem.PROGRAM_ID;
		aSqlItem.PROGRAM_UPDATE_DATE := aPlsqlItem.PROGRAM_UPDATE_DATE;
		aSqlItem.PRODUCT_ATTRIBUTE_DATATYPE := aPlsqlItem.PRODUCT_ATTRIBUTE_DATATYPE;
		aSqlItem.PRICING_ATTRIBUTE_DATATYPE := aPlsqlItem.PRICING_ATTRIBUTE_DATATYPE;
		aSqlItem.COMPARISON_OPERATOR_CODE := aPlsqlItem.COMPARISON_OPERATOR_CODE;
		aSqlItem.LIST_HEADER_ID := aPlsqlItem.LIST_HEADER_ID;
		aSqlItem.PRICING_PHASE_ID := aPlsqlItem.PRICING_PHASE_ID;
		aSqlItem.REQUEST_ID := aPlsqlItem.REQUEST_ID;
		aSqlItem.PRICING_ATTR_VALUE_FROM_NUMBER := aPlsqlItem.PRICING_ATTR_VALUE_FROM_NUMBER;
		aSqlItem.PRICING_ATTR_VALUE_TO_NUMBER := aPlsqlItem.PRICING_ATTR_VALUE_TO_NUMBER;
		aSqlItem.QUALIFICATION_IND := aPlsqlItem.QUALIFICATION_IND;
		aSqlItem.RETURN_STATUS := aPlsqlItem.RETURN_STATUS;
		aSqlItem.DB_FLAG := aPlsqlItem.DB_FLAG;
		aSqlItem.OPERATION := aPlsqlItem.OPERATION;
		aSqlItem.MODIFIERS_INDEX := aPlsqlItem.MODIFIERS_INDEX;
		RETURN aSqlItem;
	END PL_TO_SQL3;
	FUNCTION SQL_TO_PL5(aSqlItem QP_MODIFIERS_PUB_PRICING_ATTR) 
	RETURN QP_MODIFIERS_PUB.PRICING_ATTR_REC_TYPE IS 
	aPlsqlItem QP_MODIFIERS_PUB.PRICING_ATTR_REC_TYPE; 
	BEGIN 
		aPlsqlItem.ACCUMULATE_FLAG := aSqlItem.ACCUMULATE_FLAG;
		aPlsqlItem.ATTRIBUTE1 := aSqlItem.ATTRIBUTE1;
		aPlsqlItem.ATTRIBUTE10 := aSqlItem.ATTRIBUTE10;
		aPlsqlItem.ATTRIBUTE11 := aSqlItem.ATTRIBUTE11;
		aPlsqlItem.ATTRIBUTE12 := aSqlItem.ATTRIBUTE12;
		aPlsqlItem.ATTRIBUTE13 := aSqlItem.ATTRIBUTE13;
		aPlsqlItem.ATTRIBUTE14 := aSqlItem.ATTRIBUTE14;
		aPlsqlItem.ATTRIBUTE15 := aSqlItem.ATTRIBUTE15;
		aPlsqlItem.ATTRIBUTE2 := aSqlItem.ATTRIBUTE2;
		aPlsqlItem.ATTRIBUTE3 := aSqlItem.ATTRIBUTE3;
		aPlsqlItem.ATTRIBUTE4 := aSqlItem.ATTRIBUTE4;
		aPlsqlItem.ATTRIBUTE5 := aSqlItem.ATTRIBUTE5;
		aPlsqlItem.ATTRIBUTE6 := aSqlItem.ATTRIBUTE6;
		aPlsqlItem.ATTRIBUTE7 := aSqlItem.ATTRIBUTE7;
		aPlsqlItem.ATTRIBUTE8 := aSqlItem.ATTRIBUTE8;
		aPlsqlItem.ATTRIBUTE9 := aSqlItem.ATTRIBUTE9;
		aPlsqlItem.ATTRIBUTE_GROUPING_NO := aSqlItem.ATTRIBUTE_GROUPING_NO;
		aPlsqlItem.CONTEXT := aSqlItem.CONTEXT;
		aPlsqlItem.CREATED_BY := aSqlItem.CREATED_BY;
		aPlsqlItem.CREATION_DATE := aSqlItem.CREATION_DATE;
		aPlsqlItem.EXCLUDER_FLAG := aSqlItem.EXCLUDER_FLAG;
		aPlsqlItem.LAST_UPDATED_BY := aSqlItem.LAST_UPDATED_BY;
		aPlsqlItem.LAST_UPDATE_DATE := aSqlItem.LAST_UPDATE_DATE;
		aPlsqlItem.LAST_UPDATE_LOGIN := aSqlItem.LAST_UPDATE_LOGIN;
		aPlsqlItem.LIST_LINE_ID := aSqlItem.LIST_LINE_ID;
		aPlsqlItem.PRICING_ATTRIBUTE := aSqlItem.PRICING_ATTRIBUTE;
		aPlsqlItem.PRICING_ATTRIBUTE_CONTEXT := aSqlItem.PRICING_ATTRIBUTE_CONTEXT;
		aPlsqlItem.PRICING_ATTRIBUTE_ID := aSqlItem.PRICING_ATTRIBUTE_ID;
		aPlsqlItem.PRICING_ATTR_VALUE_FROM := aSqlItem.PRICING_ATTR_VALUE_FROM;
		aPlsqlItem.PRICING_ATTR_VALUE_TO := aSqlItem.PRICING_ATTR_VALUE_TO;
		aPlsqlItem.PRODUCT_ATTRIBUTE := aSqlItem.PRODUCT_ATTRIBUTE;
		aPlsqlItem.PRODUCT_ATTRIBUTE_CONTEXT := aSqlItem.PRODUCT_ATTRIBUTE_CONTEXT;
		aPlsqlItem.PRODUCT_ATTR_VALUE := aSqlItem.PRODUCT_ATTR_VALUE;
		aPlsqlItem.PRODUCT_UOM_CODE := aSqlItem.PRODUCT_UOM_CODE;
		aPlsqlItem.PROGRAM_APPLICATION_ID := aSqlItem.PROGRAM_APPLICATION_ID;
		aPlsqlItem.PROGRAM_ID := aSqlItem.PROGRAM_ID;
		aPlsqlItem.PROGRAM_UPDATE_DATE := aSqlItem.PROGRAM_UPDATE_DATE;
		aPlsqlItem.PRODUCT_ATTRIBUTE_DATATYPE := aSqlItem.PRODUCT_ATTRIBUTE_DATATYPE;
		aPlsqlItem.PRICING_ATTRIBUTE_DATATYPE := aSqlItem.PRICING_ATTRIBUTE_DATATYPE;
		aPlsqlItem.COMPARISON_OPERATOR_CODE := aSqlItem.COMPARISON_OPERATOR_CODE;
		aPlsqlItem.LIST_HEADER_ID := aSqlItem.LIST_HEADER_ID;
		aPlsqlItem.PRICING_PHASE_ID := aSqlItem.PRICING_PHASE_ID;
		aPlsqlItem.REQUEST_ID := aSqlItem.REQUEST_ID;
		aPlsqlItem.PRICING_ATTR_VALUE_FROM_NUMBER := aSqlItem.PRICING_ATTR_VALUE_FROM_NUMBER;
		aPlsqlItem.PRICING_ATTR_VALUE_TO_NUMBER := aSqlItem.PRICING_ATTR_VALUE_TO_NUMBER;
		aPlsqlItem.QUALIFICATION_IND := aSqlItem.QUALIFICATION_IND;
		aPlsqlItem.RETURN_STATUS := aSqlItem.RETURN_STATUS;
		aPlsqlItem.DB_FLAG := aSqlItem.DB_FLAG;
		aPlsqlItem.OPERATION := aSqlItem.OPERATION;
		aPlsqlItem.MODIFIERS_INDEX := aSqlItem.MODIFIERS_INDEX;
		RETURN aPlsqlItem;
	END SQL_TO_PL5;
	FUNCTION PL_TO_SQL4(aPlsqlItem QP_MODIFIERS_PUB.PRICING_ATTR_TBL_TYPE)
 	RETURN XX_QP_MODIFIERS_PKG_PRICING_A IS 
	aSqlItem XX_QP_MODIFIERS_PKG_PRICING_A; 
	BEGIN 
		-- initialize the table 
		aSqlItem := XX_QP_MODIFIERS_PKG_PRICING_A();
		aSqlItem.EXTEND(aPlsqlItem.COUNT);
		FOR I IN aPlsqlItem.FIRST..aPlsqlItem.LAST LOOP
			aSqlItem(I + 1 - aPlsqlItem.FIRST) := PL_TO_SQL3(aPlsqlItem(I));
		END LOOP; 
		RETURN aSqlItem;
	END PL_TO_SQL4;
	FUNCTION SQL_TO_PL2(aSqlItem XX_QP_MODIFIERS_PKG_PRICING_A) 
	RETURN QP_MODIFIERS_PUB.PRICING_ATTR_TBL_TYPE IS 
	aPlsqlItem QP_MODIFIERS_PUB.PRICING_ATTR_TBL_TYPE; 
	BEGIN 
		FOR I IN 1..aSqlItem.COUNT LOOP
			aPlsqlItem(I) := SQL_TO_PL5(aSqlItem(I));
		END LOOP; 
		RETURN aPlsqlItem;
	END SQL_TO_PL2;
	FUNCTION PL_TO_SQL5(aPlsqlItem QP_QUALIFIER_RULES_PUB.QUALIFIERS_REC_TYPE)
 	RETURN QP_QUALIFIER_RULES_PUB_QUALIF IS 
	aSqlItem QP_QUALIFIER_RULES_PUB_QUALIF; 
	BEGIN 
		-- initialize the object
		aSqlItem := QP_QUALIFIER_RULES_PUB_QUALIF(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
		aSqlItem.ATTRIBUTE1 := aPlsqlItem.ATTRIBUTE1;
		aSqlItem.ATTRIBUTE10 := aPlsqlItem.ATTRIBUTE10;
		aSqlItem.ATTRIBUTE11 := aPlsqlItem.ATTRIBUTE11;
		aSqlItem.ATTRIBUTE12 := aPlsqlItem.ATTRIBUTE12;
		aSqlItem.ATTRIBUTE13 := aPlsqlItem.ATTRIBUTE13;
		aSqlItem.ATTRIBUTE14 := aPlsqlItem.ATTRIBUTE14;
		aSqlItem.ATTRIBUTE15 := aPlsqlItem.ATTRIBUTE15;
		aSqlItem.ATTRIBUTE2 := aPlsqlItem.ATTRIBUTE2;
		aSqlItem.ATTRIBUTE3 := aPlsqlItem.ATTRIBUTE3;
		aSqlItem.ATTRIBUTE4 := aPlsqlItem.ATTRIBUTE4;
		aSqlItem.ATTRIBUTE5 := aPlsqlItem.ATTRIBUTE5;
		aSqlItem.ATTRIBUTE6 := aPlsqlItem.ATTRIBUTE6;
		aSqlItem.ATTRIBUTE7 := aPlsqlItem.ATTRIBUTE7;
		aSqlItem.ATTRIBUTE8 := aPlsqlItem.ATTRIBUTE8;
		aSqlItem.ATTRIBUTE9 := aPlsqlItem.ATTRIBUTE9;
		aSqlItem.COMPARISON_OPERATOR_CODE := aPlsqlItem.COMPARISON_OPERATOR_CODE;
		aSqlItem.CONTEXT := aPlsqlItem.CONTEXT;
		aSqlItem.CREATED_BY := aPlsqlItem.CREATED_BY;
		aSqlItem.CREATED_FROM_RULE_ID := aPlsqlItem.CREATED_FROM_RULE_ID;
		aSqlItem.CREATION_DATE := aPlsqlItem.CREATION_DATE;
		aSqlItem.END_DATE_ACTIVE := aPlsqlItem.END_DATE_ACTIVE;
		aSqlItem.EXCLUDER_FLAG := aPlsqlItem.EXCLUDER_FLAG;
		aSqlItem.LAST_UPDATED_BY := aPlsqlItem.LAST_UPDATED_BY;
		aSqlItem.LAST_UPDATE_DATE := aPlsqlItem.LAST_UPDATE_DATE;
		aSqlItem.LAST_UPDATE_LOGIN := aPlsqlItem.LAST_UPDATE_LOGIN;
		aSqlItem.LIST_HEADER_ID := aPlsqlItem.LIST_HEADER_ID;
		aSqlItem.LIST_LINE_ID := aPlsqlItem.LIST_LINE_ID;
		aSqlItem.PROGRAM_APPLICATION_ID := aPlsqlItem.PROGRAM_APPLICATION_ID;
		aSqlItem.PROGRAM_ID := aPlsqlItem.PROGRAM_ID;
		aSqlItem.PROGRAM_UPDATE_DATE := aPlsqlItem.PROGRAM_UPDATE_DATE;
		aSqlItem.QUALIFIER_ATTRIBUTE := aPlsqlItem.QUALIFIER_ATTRIBUTE;
		aSqlItem.QUALIFIER_ATTR_VALUE := aPlsqlItem.QUALIFIER_ATTR_VALUE;
		aSqlItem.QUALIFIER_ATTR_VALUE_TO := aPlsqlItem.QUALIFIER_ATTR_VALUE_TO;
		aSqlItem.QUALIFIER_CONTEXT := aPlsqlItem.QUALIFIER_CONTEXT;
		aSqlItem.QUALIFIER_DATATYPE := aPlsqlItem.QUALIFIER_DATATYPE;
		aSqlItem.QUALIFIER_GROUPING_NO := aPlsqlItem.QUALIFIER_GROUPING_NO;
		aSqlItem.QUALIFIER_ID := aPlsqlItem.QUALIFIER_ID;
		aSqlItem.QUALIFIER_PRECEDENCE := aPlsqlItem.QUALIFIER_PRECEDENCE;
		aSqlItem.QUALIFIER_RULE_ID := aPlsqlItem.QUALIFIER_RULE_ID;
		aSqlItem.REQUEST_ID := aPlsqlItem.REQUEST_ID;
		aSqlItem.START_DATE_ACTIVE := aPlsqlItem.START_DATE_ACTIVE;
		aSqlItem.LIST_TYPE_CODE := aPlsqlItem.LIST_TYPE_CODE;
		aSqlItem.QUAL_ATTR_VALUE_FROM_NUMBER := aPlsqlItem.QUAL_ATTR_VALUE_FROM_NUMBER;
		aSqlItem.QUAL_ATTR_VALUE_TO_NUMBER := aPlsqlItem.QUAL_ATTR_VALUE_TO_NUMBER;
		aSqlItem.ACTIVE_FLAG := aPlsqlItem.ACTIVE_FLAG;
		aSqlItem.SEARCH_IND := aPlsqlItem.SEARCH_IND;
		aSqlItem.QUALIFIER_GROUP_CNT := aPlsqlItem.QUALIFIER_GROUP_CNT;
		aSqlItem.HEADER_QUALS_EXIST_FLAG := aPlsqlItem.HEADER_QUALS_EXIST_FLAG;
		aSqlItem.DISTINCT_ROW_COUNT := aPlsqlItem.DISTINCT_ROW_COUNT;
		aSqlItem.RETURN_STATUS := aPlsqlItem.RETURN_STATUS;
		aSqlItem.DB_FLAG := aPlsqlItem.DB_FLAG;
		aSqlItem.OPERATION := aPlsqlItem.OPERATION;
		RETURN aSqlItem;
	END PL_TO_SQL5;
	FUNCTION SQL_TO_PL6(aSqlItem QP_QUALIFIER_RULES_PUB_QUALIF) 
	RETURN QP_QUALIFIER_RULES_PUB.QUALIFIERS_REC_TYPE IS 
	aPlsqlItem QP_QUALIFIER_RULES_PUB.QUALIFIERS_REC_TYPE; 
	BEGIN 
		aPlsqlItem.ATTRIBUTE1 := aSqlItem.ATTRIBUTE1;
		aPlsqlItem.ATTRIBUTE10 := aSqlItem.ATTRIBUTE10;
		aPlsqlItem.ATTRIBUTE11 := aSqlItem.ATTRIBUTE11;
		aPlsqlItem.ATTRIBUTE12 := aSqlItem.ATTRIBUTE12;
		aPlsqlItem.ATTRIBUTE13 := aSqlItem.ATTRIBUTE13;
		aPlsqlItem.ATTRIBUTE14 := aSqlItem.ATTRIBUTE14;
		aPlsqlItem.ATTRIBUTE15 := aSqlItem.ATTRIBUTE15;
		aPlsqlItem.ATTRIBUTE2 := aSqlItem.ATTRIBUTE2;
		aPlsqlItem.ATTRIBUTE3 := aSqlItem.ATTRIBUTE3;
		aPlsqlItem.ATTRIBUTE4 := aSqlItem.ATTRIBUTE4;
		aPlsqlItem.ATTRIBUTE5 := aSqlItem.ATTRIBUTE5;
		aPlsqlItem.ATTRIBUTE6 := aSqlItem.ATTRIBUTE6;
		aPlsqlItem.ATTRIBUTE7 := aSqlItem.ATTRIBUTE7;
		aPlsqlItem.ATTRIBUTE8 := aSqlItem.ATTRIBUTE8;
		aPlsqlItem.ATTRIBUTE9 := aSqlItem.ATTRIBUTE9;
		aPlsqlItem.COMPARISON_OPERATOR_CODE := aSqlItem.COMPARISON_OPERATOR_CODE;
		aPlsqlItem.CONTEXT := aSqlItem.CONTEXT;
		aPlsqlItem.CREATED_BY := aSqlItem.CREATED_BY;
		aPlsqlItem.CREATED_FROM_RULE_ID := aSqlItem.CREATED_FROM_RULE_ID;
		aPlsqlItem.CREATION_DATE := aSqlItem.CREATION_DATE;
		aPlsqlItem.END_DATE_ACTIVE := aSqlItem.END_DATE_ACTIVE;
		aPlsqlItem.EXCLUDER_FLAG := aSqlItem.EXCLUDER_FLAG;
		aPlsqlItem.LAST_UPDATED_BY := aSqlItem.LAST_UPDATED_BY;
		aPlsqlItem.LAST_UPDATE_DATE := aSqlItem.LAST_UPDATE_DATE;
		aPlsqlItem.LAST_UPDATE_LOGIN := aSqlItem.LAST_UPDATE_LOGIN;
		aPlsqlItem.LIST_HEADER_ID := aSqlItem.LIST_HEADER_ID;
		aPlsqlItem.LIST_LINE_ID := aSqlItem.LIST_LINE_ID;
		aPlsqlItem.PROGRAM_APPLICATION_ID := aSqlItem.PROGRAM_APPLICATION_ID;
		aPlsqlItem.PROGRAM_ID := aSqlItem.PROGRAM_ID;
		aPlsqlItem.PROGRAM_UPDATE_DATE := aSqlItem.PROGRAM_UPDATE_DATE;
		aPlsqlItem.QUALIFIER_ATTRIBUTE := aSqlItem.QUALIFIER_ATTRIBUTE;
		aPlsqlItem.QUALIFIER_ATTR_VALUE := aSqlItem.QUALIFIER_ATTR_VALUE;
		aPlsqlItem.QUALIFIER_ATTR_VALUE_TO := aSqlItem.QUALIFIER_ATTR_VALUE_TO;
		aPlsqlItem.QUALIFIER_CONTEXT := aSqlItem.QUALIFIER_CONTEXT;
		aPlsqlItem.QUALIFIER_DATATYPE := aSqlItem.QUALIFIER_DATATYPE;
		aPlsqlItem.QUALIFIER_GROUPING_NO := aSqlItem.QUALIFIER_GROUPING_NO;
		aPlsqlItem.QUALIFIER_ID := aSqlItem.QUALIFIER_ID;
		aPlsqlItem.QUALIFIER_PRECEDENCE := aSqlItem.QUALIFIER_PRECEDENCE;
		aPlsqlItem.QUALIFIER_RULE_ID := aSqlItem.QUALIFIER_RULE_ID;
		aPlsqlItem.REQUEST_ID := aSqlItem.REQUEST_ID;
		aPlsqlItem.START_DATE_ACTIVE := aSqlItem.START_DATE_ACTIVE;
		aPlsqlItem.LIST_TYPE_CODE := aSqlItem.LIST_TYPE_CODE;
		aPlsqlItem.QUAL_ATTR_VALUE_FROM_NUMBER := aSqlItem.QUAL_ATTR_VALUE_FROM_NUMBER;
		aPlsqlItem.QUAL_ATTR_VALUE_TO_NUMBER := aSqlItem.QUAL_ATTR_VALUE_TO_NUMBER;
		aPlsqlItem.ACTIVE_FLAG := aSqlItem.ACTIVE_FLAG;
		aPlsqlItem.SEARCH_IND := aSqlItem.SEARCH_IND;
		aPlsqlItem.QUALIFIER_GROUP_CNT := aSqlItem.QUALIFIER_GROUP_CNT;
		aPlsqlItem.HEADER_QUALS_EXIST_FLAG := aSqlItem.HEADER_QUALS_EXIST_FLAG;
		aPlsqlItem.DISTINCT_ROW_COUNT := aSqlItem.DISTINCT_ROW_COUNT;
		aPlsqlItem.RETURN_STATUS := aSqlItem.RETURN_STATUS;
		aPlsqlItem.DB_FLAG := aSqlItem.DB_FLAG;
		aPlsqlItem.OPERATION := aSqlItem.OPERATION;
		RETURN aPlsqlItem;
	END SQL_TO_PL6;
	FUNCTION PL_TO_SQL6(aPlsqlItem QP_QUALIFIER_RULES_PUB.QUALIFIERS_TBL_TYPE)
 	RETURN XX_QP_MODIFIERS_PKG_QUALIFIER IS 
	aSqlItem XX_QP_MODIFIERS_PKG_QUALIFIER; 
	BEGIN 
		-- initialize the table 
		aSqlItem := XX_QP_MODIFIERS_PKG_QUALIFIER();
		aSqlItem.EXTEND(aPlsqlItem.COUNT);
		FOR I IN aPlsqlItem.FIRST..aPlsqlItem.LAST LOOP
			aSqlItem(I + 1 - aPlsqlItem.FIRST) := PL_TO_SQL5(aPlsqlItem(I));
		END LOOP; 
		RETURN aSqlItem;
	END PL_TO_SQL6;
	FUNCTION SQL_TO_PL3(aSqlItem XX_QP_MODIFIERS_PKG_QUALIFIER) 
	RETURN QP_QUALIFIER_RULES_PUB.QUALIFIERS_TBL_TYPE IS 
	aPlsqlItem QP_QUALIFIER_RULES_PUB.QUALIFIERS_TBL_TYPE; 
	BEGIN 
		FOR I IN 1..aSqlItem.COUNT LOOP
			aPlsqlItem(I) := SQL_TO_PL6(aSqlItem(I));
		END LOOP; 
		RETURN aPlsqlItem;
	END SQL_TO_PL3;

   PROCEDURE XX_QP_MODIFIERS_PKG$CREATE_MO (P_MODIFIER_HEADER_REC XX_QP_MODIFIERS_PKG_MODIFIER_,P_MODIFIER_LINES_TBL XX_QP_MODIFIERS_PKG_MODIFIERS,P_MODIFIER_ATTRIBUTES_TBL XX_QP_MODIFIERS_PKG_PRICING_A,P_MODIFIER_QUALIFIERS_TBL XX_QP_MODIFIERS_PKG_QUALIFIER,X_MESSAGE_CODE OUT NUMBER,X_MESSAGE_DATA OUT VARCHAR2) IS
      P_MODIFIER_HEADER_REC_ APPS.QP_MODIFIERS_PUB.MODIFIER_LIST_REC_TYPE;
      P_MODIFIER_LINES_TBL_ APPS.QP_MODIFIERS_PUB.MODIFIERS_TBL_TYPE;
      P_MODIFIER_ATTRIBUTES_TBL_ APPS.QP_MODIFIERS_PUB.PRICING_ATTR_TBL_TYPE;
      P_MODIFIER_QUALIFIERS_TBL_ APPS.QP_QUALIFIER_RULES_PUB.QUALIFIERS_TBL_TYPE;
   BEGIN
      P_MODIFIER_HEADER_REC_ := BPEL_PLMODIFIERSPROCESS.SQL_TO_PL0(P_MODIFIER_HEADER_REC);
      P_MODIFIER_LINES_TBL_ := BPEL_PLMODIFIERSPROCESS.SQL_TO_PL1(P_MODIFIER_LINES_TBL);
      P_MODIFIER_ATTRIBUTES_TBL_ := BPEL_PLMODIFIERSPROCESS.SQL_TO_PL2(P_MODIFIER_ATTRIBUTES_TBL);
      P_MODIFIER_QUALIFIERS_TBL_ := BPEL_PLMODIFIERSPROCESS.SQL_TO_PL3(P_MODIFIER_QUALIFIERS_TBL);
      APPS.XX_QP_MODIFIERS_PKG.CREATE_MODIFIER_MAIN(P_MODIFIER_HEADER_REC_,P_MODIFIER_LINES_TBL_,P_MODIFIER_ATTRIBUTES_TBL_,P_MODIFIER_QUALIFIERS_TBL_,X_MESSAGE_CODE,X_MESSAGE_DATA);
   END XX_QP_MODIFIERS_PKG$CREATE_MO;

END BPEL_PLMODIFIERSPROCESS;
/
show errors
exit
