<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="SupplierEBSV1"
     targetNamespace="http://xmlns.officedepot.org/EnterpriseObjects/Core/EBO/Supplier/V1"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.officedepot.org/EnterpriseObjects/Core/EBO/Supplier/V1"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="SynchSupplierPSFTService">
        <plnk:role name="SynchSupplierEBS" portType="tns:SynchSupplierEBS"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.officedepot.org/EnterpriseObjects/Core/EBO/Supplier/V1"
         location="oramds:/apps/ODCommon/EnterpriseServices/Core/EBO/Supplier/V1/SupplierEBSV1.wsdl"/>
</wsdl:definitions>
