UPDATE XX_FIN_TRANSLATEVALUES
SET enabled_flag = 'N', END_DATE_ACTIVE = SYSDATE
WHERE TRANSLATE_ID = (select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD');
and source_value2 IN ('PREV_SHIPMENT_LEVEL','SUPPLIES_LABEL')


  
INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'CYAN_TONER_LEVEL', 'V', 'Cyan Toner', '0', 'AB', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'MAGENTA_TONER_LEVEL', 'V', 'Magenta Toner', '0', 'AC', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'YELLOW_TONER_LEVEL', 'V', 'Yellow Toner', '0', 'AD', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

COMMIT;