-- +============================================================================================+
-- |                        Office Depot - Project Simplify                                     |
-- |                                                                                            |
-- +============================================================================================+
-- | Name         : UPDATE XX_FIN_TRANSLATEVALUES for MINI AVF                                  |
-- | Rice Id      :                                                                             | 
-- | Description  : re-orrange the fields in the MINI AVF template            |  
-- | Purpose      : MODIFY                                           |
-- |                                                                                            |
-- |                                                                                            |
-- |Change Record:                                                                              |
-- |===============                                                                             |
-- |Version    Date          Author                Remarks                                      | 
-- |=======    ========    =================    ==============================================+
-- |DRAFT 1A   20-JUN-2014   Arun Gannarapu       Initial Version                           |
-- |                                                                                            |
-- +============================================================================================+


SET VERIFY      OFF
SET TERM        ON
SET FEEDBACK    OFF
SET SHOW        OFF
SET ECHO        OFF
SET TAB         OFF



PROMPT
PROMPT MODIFYING the Table XX_FIN_TRANSLATEVALUES......
PROMPT


UPDATE XX_FIN_TRANSLATEVALUES
SET enabled_flag = 'N', END_DATE_ACTIVE = SYSDATE
WHERE TRANSLATE_ID = (select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD');


/


INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'AOPS_CUST_NUMBER', 'V', 'Account Number', '0', 'A', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL, 'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'SERIAL_NO', 'V', 'Serial Number', '0', 'B', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'PARTY_NAME', 'V', 'Account Name', '0', 'C', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'SHIP_SEQ', 'V', 'Ship Seq', '0', 'D', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'PO_NUMBER', 'V', 'PO Number', '0', 'E', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'FLEET_SYSTEM', 'V', 'Fleet System', '0', 'F', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'ESSENTIALS_ATR_FLAG', 'V', 'ART Flag', '0', 'G', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'ACTIVE_STATUS', 'V', 'Active Status', '0', 'H', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'CONTRACT_NUMBER', 'V', 'Contract Number', '0', 'I', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'BLACK_CPC', 'N', 'Black CPC', '0', 'J', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'COLOR_CPC', 'N', 'Color CPC', '0', 'K', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'FLAT_RATE', 'N', 'Flat Rate', '0', 'L', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'ALLOWANCES', 'N', 'Black Allowances', '0', 'M', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'COLOR_ALLOWANCES', 'N', 'Color Allowances', '0', 'N', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'OVERAGE_COST', 'N', 'Black Overage Cost', '0', 'O', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'COLOR_OVERAGE_COST', 'N', 'Color Overage Cost', '0', 'P', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'PERIOD_COVERED_ST_DATE', 'D', 'Start Date(MM/DD/YYYY)', '0', 'Q', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'PERIOD_COVERED_END_DATE', 'D', 'End Date(MM/DD/YYYY)', '0', 'R', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'BILL_DATE', 'D', 'Bill Date (MM/DD/YYYY)', '0', 'S', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'SERVICE_COST', 'N', 'Service Cost', '0', 'T', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'EXPIRED_DATE', 'D', 'Expired Date (MM/DD/YYYY)', '0', 'U', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'BLACK_LIFE_CNT', 'N', 'Mono Life Count', '0', 'V', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'COLOR_LIFE_CNT', 'N', 'Color Life Count', '0', 'W', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'PREV_MONO_COUNT', 'N', 'Previous Mono count', '0', 'X', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'PREV_COLOR_COUNT', 'N', 'Previous Color Count', '0', 'Y', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'PREV_MONO_BILL_COUNT', 'N', 'Previous Mono Bill Count', '0', 'Z', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'PREV_COLOR_BILL_COUNT', 'N', 'Previous Color Bill Count', '0', 'AA', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'CYAN_TONER_LEVEL', 'V', 'Cyan Toner', '0', 'AB', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'MAGENTA_TONER_LEVEL', 'V', 'Magenta Toner', '0', 'AC', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);

INSERT INTO XX_FIN_TRANSLATEVALUES(TRANSLATE_ID, SOURCE_VALUE1, SOURCE_VALUE2, SOURCE_VALUE3, SOURCE_VALUE4, SOURCE_VALUE5, SOURCE_VALUE6, SOURCE_VALUE7, TARGET_VALUE1, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, START_DATE_ACTIVE, END_DATE_ACTIVE, ENABLED_FLAG, SOURCE_VALUE8, SOURCE_VALUE9, TRANSLATE_VALUE_ID)
VALUES ((select TRANSLATE_ID from apps.XX_FIN_TRANSLATEDEFINITION  where TRANSLATION_NAME = 'XX_CS_MPS_MINI_AVF_UPLOAD'), 'XX_CS_MPS_DEVICE_B_STG', 'YELLOW_TONER_LEVEL', 'V', 'Yellow Toner', '0', 'AD', '1', 'OD MPS Mini AVF Upload', SYSDATE, 26176, SYSDATE, 26176, 0, SYSDATE, NULL,'Y', 'CS', 'XX_CS_MPS_MINI_AVF_UPLD', XX_FIN_TRANSLATEVALUES_S.NEXTVAL);


COMMIT;

WHENEVER SQLERROR EXIT 1

PROMPT
PROMPT Exiting....
PROMPT

SET FEEDBACK ON

EXIT;
