SET VERIFY OFF;
SET SHOW OFF;
SET ECHO OFF;
SET TAB OFF;
SET FEEDBACK OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;

-- +===================================================================+
-- |                  Oracle GSD   - Hyderabad, India                  |
-- +===================================================================+
-- | Name  :    XX_CS_TDS_AP_INV_LINES_TBL                             |
-- | Description  : This script creates object type 		       |
-- |                                                                   |
-- |                                                                   |
-- |Change Record:                                                     |
-- |===============                                                    |
-- |Version   Date        Author           	Remarks                |
-- |=======   ==========  =============    	=======================|
-- |1.0      02-AUG-11  Sreenivasa Tirumala     Initial draft version  |
-- |                                                                   |
-- +===================================================================+

DROP TYPE XX_CS_TDS_AP_INV_LINES_TBL
/

SET TERM ON
PROMPT Creating Record type XX_CS_TDS_AP_INV_LINES_REC
SET TERM OFF

CREATE OR REPLACE   TYPE XX_CS_TDS_AP_INV_LINES_REC IS OBJECT (
"INVOICE_ID" NUMBER(15,0),
    "INVOICE_LINE_ID" NUMBER(15,0), 
    "LINE_NUMBER" NUMBER(15,0), 
    "LINE_TYPE_LOOKUP_CODE" VARCHAR2(25 BYTE), 
    "LINE_GROUP_NUMBER" NUMBER, 
    "AMOUNT" NUMBER, 
    "ACCOUNTING_DATE" DATE, 
    "DESCRIPTION" VARCHAR2(240 BYTE), 
    "AMOUNT_INCLUDES_TAX_FLAG" VARCHAR2(1 BYTE), 
    "PRORATE_ACROSS_FLAG" VARCHAR2(1 BYTE), 
    "TAX_CODE" VARCHAR2(15 BYTE), 
    "FINAL_MATCH_FLAG" VARCHAR2(1 BYTE), 
    "PO_HEADER_ID" NUMBER, 
    "PO_NUMBER" VARCHAR2(20 BYTE), 
    "PO_LINE_ID" NUMBER, 
    "PO_LINE_NUMBER" NUMBER, 
    "PO_LINE_LOCATION_ID" NUMBER, 
    "PO_SHIPMENT_NUM" NUMBER, 
    "PO_DISTRIBUTION_ID" NUMBER, 
    "PO_DISTRIBUTION_NUM" NUMBER, 
    "PO_UNIT_OF_MEASURE" VARCHAR2(25 BYTE), 
    "INVENTORY_ITEM_ID" NUMBER, 
    "ITEM_DESCRIPTION" VARCHAR2(240 BYTE), 
    "QUANTITY_INVOICED" NUMBER, 
    "SHIP_TO_LOCATION_CODE" VARCHAR2(60 BYTE), 
    "UNIT_PRICE" NUMBER, 
    "DISTRIBUTION_SET_ID" NUMBER(15,0), 
    "DISTRIBUTION_SET_NAME" VARCHAR2(50 BYTE), 
    "DIST_CODE_CONCATENATED" VARCHAR2(250 BYTE), 
    "DIST_CODE_COMBINATION_ID" NUMBER(15,0), 
    "AWT_GROUP_ID" NUMBER(15,0), 
    "AWT_GROUP_NAME" VARCHAR2(25 BYTE), 
    "LAST_UPDATED_BY" NUMBER(15,0), 
    "LAST_UPDATE_DATE" DATE, 
    "LAST_UPDATE_LOGIN" NUMBER(15,0), 
    "CREATED_BY" NUMBER(15,0), 
    "CREATION_DATE" DATE, 
    "ATTRIBUTE_CATEGORY" VARCHAR2(150 BYTE), 
    "ATTRIBUTE1" VARCHAR2(150 BYTE), 
    "ATTRIBUTE2" VARCHAR2(150 BYTE), 
    "ATTRIBUTE3" VARCHAR2(150 BYTE), 
    "ATTRIBUTE4" VARCHAR2(150 BYTE), 
    "ATTRIBUTE5" VARCHAR2(150 BYTE), 
    "ATTRIBUTE6" VARCHAR2(150 BYTE), 
    "ATTRIBUTE7" VARCHAR2(150 BYTE), 
    "ATTRIBUTE8" VARCHAR2(150 BYTE), 
    "ATTRIBUTE9" VARCHAR2(150 BYTE), 
    "ATTRIBUTE10" VARCHAR2(150 BYTE), 
    "ATTRIBUTE11" VARCHAR2(150 BYTE), 
    "ATTRIBUTE12" VARCHAR2(150 BYTE), 
    "ATTRIBUTE13" VARCHAR2(150 BYTE), 
    "ATTRIBUTE14" VARCHAR2(150 BYTE), 
    "ATTRIBUTE15" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE_CATEGORY" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE1" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE2" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE3" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE4" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE5" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE6" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE7" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE8" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE9" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE10" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE11" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE12" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE13" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE14" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE15" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE16" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE17" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE18" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE19" VARCHAR2(150 BYTE), 
    "GLOBAL_ATTRIBUTE20" VARCHAR2(150 BYTE), 
    "PO_RELEASE_ID" NUMBER, 
    "RELEASE_NUM" NUMBER, 
    "ACCOUNT_SEGMENT" VARCHAR2(25 BYTE), 
    "BALANCING_SEGMENT" VARCHAR2(25 BYTE), 
    "COST_CENTER_SEGMENT" VARCHAR2(25 BYTE), 
    "PROJECT_ID" NUMBER(15,0), 
    "TASK_ID" NUMBER(15,0), 
    "EXPENDITURE_TYPE" VARCHAR2(30 BYTE), 
    "EXPENDITURE_ITEM_DATE" DATE, 
    "EXPENDITURE_ORGANIZATION_ID" NUMBER(15,0), 
    "PROJECT_ACCOUNTING_CONTEXT" VARCHAR2(30 BYTE), 
    "PA_ADDITION_FLAG" VARCHAR2(1 BYTE), 
    "PA_QUANTITY" NUMBER(22,5), 
    "USSGL_TRANSACTION_CODE" VARCHAR2(30 BYTE), 
    "STAT_AMOUNT" NUMBER, 
    "TYPE_1099" VARCHAR2(10 BYTE), 
    "INCOME_TAX_REGION" VARCHAR2(10 BYTE), 
    "ASSETS_TRACKING_FLAG" VARCHAR2(1 BYTE), 
    "PRICE_CORRECTION_FLAG" VARCHAR2(1 BYTE), 
    "ORG_ID" NUMBER(15,0), 
    "RECEIPT_NUMBER" VARCHAR2(30 BYTE), 
    "RECEIPT_LINE_NUMBER" VARCHAR2(25 BYTE), 
    "MATCH_OPTION" VARCHAR2(25 BYTE), 
    "PACKING_SLIP" VARCHAR2(25 BYTE), 
    "RCV_TRANSACTION_ID" NUMBER, 
    "PA_CC_AR_INVOICE_ID" NUMBER(15,0), 
    "PA_CC_AR_INVOICE_LINE_NUM" NUMBER(15,0), 
    "REFERENCE_1" VARCHAR2(30 BYTE), 
    "REFERENCE_2" VARCHAR2(30 BYTE), 
    "PA_CC_PROCESSED_CODE" VARCHAR2(1 BYTE), 
    "TAX_RECOVERY_RATE" NUMBER, 
    "TAX_RECOVERY_OVERRIDE_FLAG" VARCHAR2(1 BYTE), 
    "TAX_RECOVERABLE_FLAG" VARCHAR2(1 BYTE), 
    "TAX_CODE_OVERRIDE_FLAG" VARCHAR2(1 BYTE), 
    "TAX_CODE_ID" NUMBER(15,0), 
    "CREDIT_CARD_TRX_ID" NUMBER(15,0), 
    "AWARD_ID" NUMBER(15,0), 
    "VENDOR_ITEM_NUM" VARCHAR2(25 BYTE), 
    "TAXABLE_FLAG" VARCHAR2(1 BYTE), 
    "PRICE_CORRECT_INV_NUM" VARCHAR2(50 BYTE), 
    "EXTERNAL_DOC_LINE_REF" VARCHAR2(240 BYTE)
   );
/

SET TERM ON
PROMPT Object Type created successfully
SET TERM OFF

SET TERM ON
PROMPT Creating tbl type XX_CS_TDS_AP_INV_LINES_TBL
SET TERM OFF


CREATE OR REPLACE TYPE XX_CS_TDS_AP_INV_LINES_TBL IS TABLE OF XX_CS_TDS_AP_INV_LINES_REC 
/

SET TERM ON
PROMPT Type created successfully
SET TERM OFF

SHOW ERROR


