create or replace
PACKAGE XX_CS_STANDBY_PKG AS 

 PROCEDURE SUBMIT_ANSWERS;

 PROCEDURE GET_SKUS_QUOTES;

 PROCEDURE CREATE_SR; 
 
 PROCEDURE MAIN_PROC( P_PROCESS IN VARCHAR2,
                      P_DATE IN VARCHAR2);
 
 PROCEDURE CREATE_TDS_SR;

END XX_CS_STANDBY_PKG;
/
