package od.oracle.apps.xxfin.ar.irec.accountDetails.pay.server;
import oracle.apps.ar.irec.accountDetails.pay.server.BankAccountTypesVOImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class OD_BankAccountTypesVOImpl extends BankAccountTypesVOImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public OD_BankAccountTypesVOImpl()
  {
  }
}