package ServiceStgTableInsert;

import java.util.Date;
import java.util.Vector;

public class XxApInvInterfaceStg {

    Vector xxApInvLinesInterfaceStgCollection;
    private Long invoiceId;
    private String invoiceNum;
    private String invoiceTypeLookupCode;
    private Date invoiceDate;
    private String poNumber;
    private Long vendorId;
    private String vendorNum;
    private String vendorName;
    private Long vendorSiteId;
    private String vendorSiteCode;
    private Integer invoiceAmount;
    private String invoiceCurrencyCode;
    private Integer exchangeRate;
    private String exchangeRateType;
    private Date exchangeDate;
    private Long termsId;
    private String termsName;
    private String description;
    private Long awtGroupId;
    private String awtGroupName;
    private Date lastUpdateDate;
    private Long lastUpdatedBy;
    private Long lastUpdateLogin;
    private Date creationDate;
    private Long createdBy;
    private String attributeCategory;
    private String attribute1;
    private String attribute2;
    private String attribute3;
    private String attribute4;
    private String attribute5;
    private String attribute6;
    private String attribute7;
    private String attribute8;
    private String attribute9;
    private String attribute10;
    private String attribute11;
    private String attribute12;
    private String attribute13;
    private String attribute14;
    private String attribute15;
    private String globalAttributeCategory;
    private String globalAttribute1;
    private String globalAttribute2;
    private String globalAttribute3;
    private String globalAttribute4;
    private String globalAttribute5;
    private String globalAttribute6;
    private String globalAttribute7;
    private String globalAttribute8;
    private String globalAttribute9;
    private String globalAttribute10;
    private String globalAttribute11;
    private String globalAttribute12;
    private String globalAttribute13;
    private String globalAttribute14;
    private String globalAttribute15;
    private String globalAttribute16;
    private String globalAttribute17;
    private String globalAttribute18;
    private String globalAttribute19;
    private String globalAttribute20;
    private String status;
    private String source;
    private String groupId;
    private Integer requestId;
    private String paymentCrossRateType;
    private Date paymentCrossRateDate;
    private Integer paymentCrossRate;
    private String paymentCurrencyCode;
    private String workflowFlag;
    private String docCategoryCode;
    private String voucherNum;
    private String paymentMethodLookupCode;
    private String payGroupLookupCode;
    private Date goodsReceivedDate;
    private Date invoiceReceivedDate;
    private Date glDate;
    private Long acctsPayCodeCombinationId;
    private String ussglTransactionCode;
    private String exclusivePaymentFlag;
    private Long orgId;
    private Integer amountApplicableToDiscount;
    private String prepayNum;
    private Long prepayDistNum;
    private Integer prepayApplyAmount;
    private Date prepayGlDate;
    private String invoiceIncludesPrepayFlag;
    private Integer noXrateBaseAmount;
    private String vendorEmailAddress;
    private Date termsDate;
    private Long requesterId;
    private String shipToLocation;
    private String externalDocRef;
    private String batchId;


}
