package od.oracle.apps.xxmer.allocation.server;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class AllocationHeaderVORowImpl extends OAViewRowImpl 
{


  protected static final int BATCHNO = 0;
  protected static final int BATCHDESC = 1;
  protected static final int ITEMID = 2;
  protected static final int DESCRIPTION = 3;
  protected static final int PRIMARYUNITOFMEASURE = 4;
  protected static final int VENDORNAME = 5;
  protected static final int FULLNAME = 6;
  protected static final int CREATIONDATE = 7;
  protected static final int LASTUPDATEDATE = 8;
  protected static final int ALLOCATIONHEADERID = 9;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public AllocationHeaderVORowImpl()
  {
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute BatchNo
   */
  public Number getBatchNo()
  {
    return (Number)getAttributeInternal(BATCHNO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute BatchNo
   */
  public void setBatchNo(Number value)
  {
    setAttributeInternal(BATCHNO, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute BatchDesc
   */
  public String getBatchDesc()
  {
    return (String)getAttributeInternal(BATCHDESC);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute BatchDesc
   */
  public void setBatchDesc(String value)
  {
    setAttributeInternal(BATCHDESC, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ItemId
   */
  public Number getItemId()
  {
    return (Number)getAttributeInternal(ITEMID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ItemId
   */
  public void setItemId(Number value)
  {
    setAttributeInternal(ITEMID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Description
   */
  public String getDescription()
  {
    return (String)getAttributeInternal(DESCRIPTION);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Description
   */
  public void setDescription(String value)
  {
    setAttributeInternal(DESCRIPTION, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute PrimaryUnitOfMeasure
   */
  public String getPrimaryUnitOfMeasure()
  {
    return (String)getAttributeInternal(PRIMARYUNITOFMEASURE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute PrimaryUnitOfMeasure
   */
  public void setPrimaryUnitOfMeasure(String value)
  {
    setAttributeInternal(PRIMARYUNITOFMEASURE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute VendorName
   */
  public String getVendorName()
  {
    return (String)getAttributeInternal(VENDORNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute VendorName
   */
  public void setVendorName(String value)
  {
    setAttributeInternal(VENDORNAME, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute FullName
   */
  public String getFullName()
  {
    return (String)getAttributeInternal(FULLNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute FullName
   */
  public void setFullName(String value)
  {
    setAttributeInternal(FULLNAME, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute AllocationHeaderId
   */
  public Number getAllocationHeaderId()
  {
    return (Number)getAttributeInternal(ALLOCATIONHEADERID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute AllocationHeaderId
   */
  public void setAllocationHeaderId(Number value)
  {
    setAttributeInternal(ALLOCATIONHEADERID, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case BATCHNO:
        return getBatchNo();
      case BATCHDESC:
        return getBatchDesc();
      case ITEMID:
        return getItemId();
      case DESCRIPTION:
        return getDescription();
      case PRIMARYUNITOFMEASURE:
        return getPrimaryUnitOfMeasure();
      case VENDORNAME:
        return getVendorName();
      case FULLNAME:
        return getFullName();
      case CREATIONDATE:
        return getCreationDate();
      case LASTUPDATEDATE:
        return getLastUpdateDate();
      case ALLOCATIONHEADERID:
        return getAllocationHeaderId();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case BATCHNO:
        setBatchNo((Number)value);
        return;
      case BATCHDESC:
        setBatchDesc((String)value);
        return;
      case ITEMID:
        setItemId((Number)value);
        return;
      case DESCRIPTION:
        setDescription((String)value);
        return;
      case PRIMARYUNITOFMEASURE:
        setPrimaryUnitOfMeasure((String)value);
        return;
      case VENDORNAME:
        setVendorName((String)value);
        return;
      case FULLNAME:
        setFullName((String)value);
        return;
      case CREATIONDATE:
        setCreationDate((Date)value);
        return;
      case LASTUPDATEDATE:
        setLastUpdateDate((Date)value);
        return;
      case ALLOCATIONHEADERID:
        setAllocationHeaderId((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
}