<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="APPS_XX_AR_CREDIT_CHECK_PKG_GET_AOPS_VK_CREDIT_CHECK.xsd"/>
      <rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/XX_AR_CREDIT_CHECK_PKG/GET_AOPS_VK_CREDIT_CHECK/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="VKCreditCheck_Response.xsd"/>
      <rootElement name="VKCreditCheckResponse" namespace="http://TargetNamespace.com/EnqueueResponse"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.3.0(build 070615.0525) AT [FRI NOV 16 14:13:24 EST 2007]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:tns="http://TargetNamespace.com/EnqueueResponse"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
                xmlns:extn="http://xmlns.oracle.com/pcbpel/nxsd/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/XX_AR_CREDIT_CHECK_PKG/GET_AOPS_VK_CREDIT_CHECK/"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                exclude-result-prefixes="xsl ns0 db tns nxsd extn bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <tns:VKCreditCheckResponse>
      <tns:RESPONSE-AREA>
        <tns:BUC_AMT_0>
          <xsl:value-of select="/db:OutputParameters/db:P_BUC_AMT_0_STR"/>
        </tns:BUC_AMT_0>
        <tns:BUC_AMT_1>
          <xsl:value-of select="/db:OutputParameters/db:P_BUC_AMT_1_STR"/>
        </tns:BUC_AMT_1>
        <tns:BUC_AMT_2>
          <xsl:value-of select="/db:OutputParameters/db:P_BUC_AMT_2_STR"/>
        </tns:BUC_AMT_2>
        <tns:BUC_AMT_3>
          <xsl:value-of select="/db:OutputParameters/db:P_BUC_AMT_3_STR"/>
        </tns:BUC_AMT_3>
        <tns:BUC_AMT_4>
          <xsl:value-of select="/db:OutputParameters/db:P_BUC_AMT_4_STR"/>
        </tns:BUC_AMT_4>
        <tns:OUT_BAL>
          <xsl:value-of select="/db:OutputParameters/db:P_OUT_BAL_STR"/>
        </tns:OUT_BAL>
        <tns:RCPT_DATE>
          <xsl:value-of select="/db:OutputParameters/db:P_RCPT_DATE"/>
        </tns:RCPT_DATE>
        <tns:COLLECTOR_ID>
          <xsl:value-of select="/db:OutputParameters/db:P_COLLECTOR_ID"/>
        </tns:COLLECTOR_ID>
        <tns:COLLECTOR_NAME>
          <xsl:value-of select="/db:OutputParameters/db:P_COLLECTOR_NAME"/>
        </tns:COLLECTOR_NAME>
        <tns:RESPONSE_CODE>
          <xsl:value-of select="/db:OutputParameters/db:P_RESPONSE_CODE"/>
        </tns:RESPONSE_CODE>
        <tns:RESPONSE_MESSAGE>
          <xsl:value-of select="/db:OutputParameters/db:P_RESPONSE_TEXT"/>
        </tns:RESPONSE_MESSAGE>
      </tns:RESPONSE-AREA>
    </tns:VKCreditCheckResponse>
  </xsl:template>
</xsl:stylesheet>
