<definitions name="plItemXrefProcess"
             targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/plItemXrefProcess/"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/plItemXrefProcess/"
             xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/XX_INV_ITEM_XREF_PKG/PROCESS_ITEM_XREF/"
             xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
             xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
             xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/db/">
    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/"
            location="DBAdapterOutboundHeader.wsdl"/>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/XX_INV_ITEM_XREF_PKG/PROCESS_ITEM_XREF/"
                    schemaLocation="APPS_XX_INV_ITEM_XREF_PKG_PROCESS_ITEM_XREF.xsd"/>
        </schema>
    </types>
    <message name="args_in_msg">
        <part name="InputParameters" element="db:InputParameters"/>
    </message>
    <message name="args_out_msg">
        <part name="OutputParameters" element="db:OutputParameters"/>
    </message>
    <portType name="plItemXrefProcess_ptt">
        <operation name="plItemXrefProcess">
            <input message="tns:args_in_msg"/>
            <output message="tns:args_out_msg"/>
        </operation>
    </portType>
    <binding name="plItemXrefProcess_binding" type="tns:plItemXrefProcess_ptt">
        <jca:binding/>
        <operation name="plItemXrefProcess">
            <jca:operation SchemaName="APPS" PackageName="XX_INV_ITEM_XREF_PKG"
                           ProcedureName="PROCESS_ITEM_XREF"
                           InteractionSpec="oracle.tip.adapter.db.DBStoredProcedureInteractionSpec"></jca:operation>
            <input>
                <jca:header message="hdr:OutboundHeader_msg"
                            part="outboundHeader"/>
            </input>
            <output/>
        </operation>
    </binding>
    <service name="plItemXrefProcess">
        <port name="plItemXrefProcess_pt"
              binding="tns:plItemXrefProcess_binding">
            <!--Your runtime connection is declared in 
J2EE_HOME/application-deployments/default/DbAdapter/oc4j-ra.xml 
These mcf properties here are from your design time connection and 
save you from having to edit that file and restart the application server 
if eis/db/EBSApps is missing. 
These mcf properties are safe to remove.-->
            <jca:address location="eis/db/EBSApps"
                         UIConnectionName="ebs_apps_gsidev02">
                <!--         ManagedConnectionFactory="oracle.tip.adapter.db.DBManagedConnectionFactory"
          mcf.DriverClassName="oracle.jdbc.OracleDriver"
          mcf.PlatformClassName="oracle.toplink.internal.databaseaccess.Oracle9Platform"
          mcf.ConnectionString="jdbc:oracle:thin:@//choldbr13d.na.odcorp.net:1541/gsidev02"
          mcf.UserName="apps"
          mcf.Password="589713C9226D58ECFC970AF706D8C533D62D1A19DF561D1E" />
-->
            </jca:address>
        </port>
    </service>
    <plt:partnerLinkType name="plItemXrefProcess_plt">
        <plt:role name="plItemXrefProcess_role">
            <plt:portType name="tns:plItemXrefProcess_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
</definitions>

