delete from xxcrm.XX_TM_NAM_TERR_DEFN;

delete from xxcrm.XX_TM_NAM_TERR_ENTITY_DTLS;

delete from xxcrm.xx_tm_nam_terr_rsc_dtls;

delete from xxcrm.XX_TM_NAM_GDW_BATCHES;

commit;

DROP SEQUENCE XXCRM.XX_TM_NAM_TERR_DEFN_S;

CREATE SEQUENCE XXCRM.XX_TM_NAM_TERR_DEFN_S
INCREMENT BY 1
START WITH 1000
NOMAXVALUE
NOCYCLE CACHE 1000 NOORDER;

GRANT ALL ON XXCRM.XX_TM_NAM_TERR_DEFN_S TO APPS;

DROP SEQUENCE XXCRM.XX_TM_NAM_TERR_ENTITY_DTLS_S;

CREATE SEQUENCE XXCRM.XX_TM_NAM_TERR_ENTITY_DTLS_S
INCREMENT BY 1
START WITH 1000
NOMAXVALUE
NOCYCLE CACHE 1000 NOORDER;

GRANT ALL ON XXCRM.XX_TM_NAM_TERR_ENTITY_DTLS_S TO APPS;

DROP SEQUENCE XXCRM.XX_TM_NAM_TERR_RSC_DTLS_S;

CREATE SEQUENCE XXCRM.XX_TM_NAM_TERR_RSC_DTLS_S
INCREMENT BY 1
START WITH 1000
NOMAXVALUE
NOCYCLE CACHE 1000 NOORDER;

GRANT ALL ON XXCRM.XX_TM_NAM_TERR_RSC_DTLS_S TO APPS;

CREATE OR REPLACE SYNONYM APPS.XX_TM_NAM_TERR_DEFN_S FOR XXCRM.XX_TM_NAM_TERR_DEFN_S;

CREATE OR REPLACE SYNONYM APPS.XX_TM_NAM_TERR_ENTITY_DTLS_S FOR XXCRM.XX_TM_NAM_TERR_ENTITY_DTLS_S;

CREATE OR REPLACE SYNONYM APPS.XX_TM_NAM_TERR_RSC_DTLS_S FOR XXCRM.XX_TM_NAM_TERR_RSC_DTLS_S;

SHOW ERRORS;
EXIT;


