DROP TYPE XX_PO_ASL_IN_PKG_G_ITEM_SUPP_ FORCE; 
show errors
DROP TYPE XX_PO_ASL_IN_PKG_G_ITEM_SUPP1 FORCE; 
show errors
DROP TYPE XX_PO_ASL_IN_PKG_G_ITEM_SUPP2 FORCE; 
show errors
DROP TYPE XX_PO_ASL_IN_PKG_G_ITEM_SUPP3 FORCE; 
show errors
DROP TYPE XX_PO_ASL_IN_PKG_G_ITEM_SUPP4 FORCE; 
show errors
DROP TYPE XX_PO_ASL_IN_PKG_G_ITEM_SUPP5 FORCE; 
show errors
DROP PACKAGE BPEL_WRAPPER_XX_PO_ASL_IN_PKG;
exit
