CREATE OR REPLACE SYNONYM APPS.XX_TM_NAM_TERR_DEFN_S FOR XXCRM.XX_TM_NAM_TERR_DEFN_S;

CREATE OR REPLACE SYNONYM APPS.XX_TM_NAM_TERR_ENTITY_DTLS_S FOR XXCRM.XX_TM_NAM_TERR_ENTITY_DTLS_S;

CREATE OR REPLACE SYNONYM APPS.XX_TM_NAM_TERR_RSC_DTLS_S FOR XXCRM.XX_TM_NAM_TERR_RSC_DTLS_S;

SHOW ERRORS;
EXIT;
