CREATE MATERIALIZED VIEW LOG ON OSM.as_sales_leads
WITH  ROWID INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON OSM.AS_LEADS_ALL
WITH ROWID INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON OSM.as_sales_lead_opportunity
WITH rowid, sequence(sales_lead_id)
INCLUDING NEW VALUES;
