GRANT ALL ON APPS.JTF_RS_ROLE_RELATIONS TO XXTOP_ADF;
GRANT SELECT ON APPS.JTF_RS_ROLES_VL TO XXTOP_ADF;
GRANT SELECT ON APPS.JTF_RS_RESOURCE_EXTNS_VL TO XXTOP_ADF;
GRANT SELECT ON APPS.JTF_RS_GROUPS_VL TO XXTOP_ADF;
GRANT SELECT ON APPS.JTF_RS_GROUP_MEMBERS TO XXTOP_ADF;

