
/*****************************************************************************
--  Note: This generated code is for demonstration purposes only and may
--        not be deployable.
*****************************************************************************/

CREATE OR REPLACE PACKAGE ""MP_C0024_ACCTSTEUSE"" AS
OWB$MAP_OBJECT_ID VARCHAR2(32) := '';
sql_stmt  VARCHAR2(32767);
get_abort BOOLEAN := FALSE;
get_abort_procedure BOOLEAN := FALSE;
get_trigger_success BOOLEAN := TRUE;
get_errors NUMBER(22) := 0;
get_status NUMBER(22) := 0;
get_error_ratio NUMBER(22) := 0;
get_global_names              VARCHAR2(10) := 'FALSE';
-- Status variable for Batch cursors
"XXOD_HZ_IMP_ACCT_SITEUSES_I_St" BOOLEAN := FALSE; 

"P_BATCH_ID" NUMBER;"P_AOPS_BATCH_ID" NUMBER;"CO_0_CR" VARCHAR2(30) := 'XXCONV';

-- Function Main 
-- Entry point in package ""MP_C0024_ACCTSTEUSE""
FUNCTION Main("P_BATCH_ID" IN NUMBER
 DEFAULT NULL, "P_AOPS_BATCH_ID" IN NUMBER
 DEFAULT NULL) RETURN NUMBER;  

END ""MP_C0024_ACCTSTEUSE"";

/

CREATE OR REPLACE PACKAGE BODY ""MP_C0024_ACCTSTEUSE"" AS




---------------------------------------------------------------------------
-- Function "XXOD_HZ_IMP_ACCT_SITEUSES_Bat"
--   performs batch extraction
--   Returns TRUE on success
--   Returns FALSE on failure
---------------------------------------------------------------------------
FUNCTION "XXOD_HZ_IMP_ACCT_SITEUSES_Bat" ("P_BATCH_ID" IN NUMBER
 DEFAULT NULL, "P_AOPS_BATCH_ID" IN NUMBER
 DEFAULT NULL) 
 RETURN BOOLEAN IS

BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION ENABLE PARALLEL DML';

  BEGIN
    INSERT
    INTO
      "XXOD_HZ_IMP_ACCT_SITEUSES_INT"
      ("BATCH_ID",
      "CREATED_BY_MODULE",
      "PARTY_ORIG_SYSTEM",
      "PARTY_ORIG_SYSTEM_REFERENCE",
      "ACCT_SITE_ORIG_SYSTEM",
      "ACCT_SITE_ORIG_SYSTEM_REF",
      "ACCOUNT_ORIG_SYSTEM",
      "ACCOUNT_ORIG_SYSTEM_REFERENCE",
      "SITE_USE_ATTRIBUTE_CATEGORY",
      "SITE_USE_ATTRIBUTE3",
      "SITE_USE_ATTRIBUTE4",
      "SITE_USE_ATTRIBUTE9",
      "SITE_USE_ATTRIBUTE10",
      "SITE_USE_ATTRIBUTE25",
      "SITE_USE_CODE",
      "LOCATION",
      "BILL_TO_ORIG_SYSTEM",
      "BILL_TO_ORIG_ADDRESS_REF",
      "PRIMARY_FLAG")
      (SELECT
/*+ NO_MERGE */
  "MP_C0024_ACCTSTEUSE"."P_BATCH_ID" "P_BATCH_ID$1",
  "MP_C0024_ACCTSTEUSE"."CO_0_CR" "CRTBYMOD",
  "ACCTSTEUSE"."PARTY_ORIG_SYSTEM" "PARTY_ORIG_SYSTEM",
  "ACCTSTEUSE"."PARTY_ORIG_SYSREF" "PARTY_ORIG_SYSREF",
  TRIM( "ACCTSTEUSE"."SITE_ORIG_SYSTEM" )/* EXPRESSION.OUTGRP1.ACCT_SITE_ORIG_SYSTEM */ "ACCT_SITE_ORIG_SYSTEM",
  TRIM( "ACCTSTEUSE"."SITE_ORIG_SYSREF" )/* EXPRESSION.OUTGRP1.ACCT_SITE_ORIG_SYSTEM_REF */ "ACCT_SITE_ORIG_SYSTEM_REF",
  TRIM( "ACCTSTEUSE"."ACCT_ORIG_SYSTEM" )/* EXPRESSION.OUTGRP1.ACCOUNT_ORIG_SYSTEM */ "ACCOUNT_ORIG_SYSTEM",
  TRIM( "ACCTSTEUSE"."ACCT_ORIG_SYSREF" )/* EXPRESSION.OUTGRP1.ACCOUNT_ORIG_SYSTEM_REFERENCE */ "ACCOUNT_ORIG_SYSTEM_REFERENCE",
  "ACCTSTEUSE"."SITEUSE_ATTR_CATEGORY" "SITEUSE_ATTR_CATEGORY",
  CASE
WHEN ( "ACCTSTEUSE"."SITE_USE_ATTR3" = 'H' AND  "ACCTSTEUSE"."SITEUSE_ATTR_CATEGORY" = 'SHIP_TO')
THEN 'HIDDEN'
WHEN ( "ACCTSTEUSE"."SITE_USE_ATTR3" = 'N' AND  "ACCTSTEUSE"."SITEUSE_ATTR_CATEGORY" = 'SHIP_TO')
THEN 'ALLOWED'
WHEN ( "ACCTSTEUSE"."SITE_USE_ATTR3" = 'V' AND  "ACCTSTEUSE"."SITEUSE_ATTR_CATEGORY" = 'SHIP_TO')
THEN 'VALIDATED'
WHEN (  "ACCTSTEUSE"."SITE_USE_ATTR3" = 'Y' AND  "ACCTSTEUSE"."SITEUSE_ATTR_CATEGORY" = 'SHIP_TO')
THEN 'REQUIRED'
WHEN  "ACCTSTEUSE"."SITE_USE_ATTR3" NOT IN ('H','N','V','Y') AND  "ACCTSTEUSE"."SITEUSE_ATTR_CATEGORY" = 'SHIP_TO'
THEN 'ALLOWED'
END/* EXPRESSION.OUTGRP1.SITE_USE_ATTRIBUTE3 */ "SITE_USE_ATTRIBUTE3",
  "ACCTSTEUSE"."SITE_USE_ATTR4" "SITE_USE_ATTR4",
  "ACCTSTEUSE"."SITE_USE_ATTR9" "SITE_USE_ATTR9",
  "ACCTSTEUSE"."SITE_USE_ATTR10" "SITE_USE_ATTR10",
  "ACCTSTEUSE"."SITE_USE_ATTR25" "SITE_USE_ATTR25",
  TRIM( "ACCTSTEUSE"."SITE_USE_CODE" )/* EXPRESSION.OUTGRP1.SITE_USE_CODE */ "SITE_USE_CODE",
  "ACCTSTEUSE"."ADDRESS_KEY" "ADDRESS_KEY",
  "ACCTSTEUSE"."BILLTO_ORIG_SYSTEM" "BILLTO_ORIG_SYSTEM",
  "ACCTSTEUSE"."BILLTO_ORIG_SYSREF" "BILLTO_ORIG_SYSREF",
  CASE WHEN  SUBSTR("ACCTSTEUSE"."SITE_ORIG_SYSREF",10,5) = '00001'
THEN 'Y'
ELSE 'N'
END/* EXPRESSION.OUTGRP1.PRIMARY_FLAG */ "PRIMARY_FLAG"
FROM
  "SIMPLIFY"."ACCTSTEUSE"@"GANDHI.NA.ODCORP.NET" "ACCTSTEUSE"
  WHERE 
  ( "ACCTSTEUSE"."BATCH_NBR" = "MP_C0024_ACCTSTEUSE"."P_AOPS_BATCH_ID" )
      );
    COMMIT;
  EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    COMMIT;
    RETURN FALSE;
  END;
  COMMIT;
  RETURN TRUE;
END "XXOD_HZ_IMP_ACCT_SITEUSES_Bat";

FUNCTION Main("P_BATCH_ID" IN NUMBER
 DEFAULT NULL, "P_AOPS_BATCH_ID" IN NUMBER
 DEFAULT NULL) RETURN NUMBER IS
get_batch_status           BOOLEAN := TRUE;
BEGIN
  -- Mapping input parameter global variable assignments
  "MP_C0024_ACCTSTEUSE"."P_BATCH_ID" := "MP_C0024_ACCTSTEUSE".Main."P_BATCH_ID";"MP_C0024_ACCTSTEUSE"."P_AOPS_BATCH_ID" := "MP_C0024_ACCTSTEUSE".Main."P_AOPS_BATCH_ID";
  

  
  
  
  
  
PROCEDURE EXEC_AUTONOMOUS_SQL(CMD IN VARCHAR2) IS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  EXECUTE IMMEDIATE (CMD);
  COMMIT;
END;
  -- Initialize all batch status variables
	"XXOD_HZ_IMP_ACCT_SITEUSES_I_St" := FALSE;



			
"XXOD_HZ_IMP_ACCT_SITEUSES_I_St" := "XXOD_HZ_IMP_ACCT_SITEUSES_Bat"; 


RETURN get_status;
END Main;
END ""MP_C0024_ACCTSTEUSE"";

/
