
/*****************************************************************************
--  Note: This generated code is for demonstration purposes only and may
--        not be deployable.
*****************************************************************************/

CREATE OR REPLACE PACKAGE ""MP_C0024_CNTPOINT"" AS
OWB$MAP_OBJECT_ID VARCHAR2(32) := '';
sql_stmt  VARCHAR2(32767);
get_abort BOOLEAN := FALSE;
get_abort_procedure BOOLEAN := FALSE;
get_trigger_success BOOLEAN := TRUE;
get_errors NUMBER(22) := 0;
get_status NUMBER(22) := 0;
get_error_ratio NUMBER(22) := 0;
get_global_names              VARCHAR2(10) := 'FALSE';
-- Status variable for Batch cursors
"XXOD_HZ_IMP_CONTACTPTS_INT_St" BOOLEAN := FALSE; 

"CS_0_CR" VARCHAR2(30) := 'XXCONV';"CS_1_LS" DATE := CURRENT_DATE;"CS_2_PR" NUMBER(22,15) := 55;"CS_3_ST" DATE := CURRENT_DATE;"CS_4_RE" VARCHAR2(1) := 'Y';"P_BATCH_ID" NUMBER;"P_AOPS_BATCH_ID" NUMBER;

-- Function Main 
-- Entry point in package ""MP_C0024_CNTPOINT""
FUNCTION Main("P_BATCH_ID" IN NUMBER
 DEFAULT NULL, "P_AOPS_BATCH_ID" IN NUMBER
 DEFAULT NULL) RETURN NUMBER;  

END ""MP_C0024_CNTPOINT"";

/

CREATE OR REPLACE PACKAGE BODY ""MP_C0024_CNTPOINT"" AS




---------------------------------------------------------------------------
-- Function "XXOD_HZ_IMP_CONTACTPTS_INT_Bat"
--   performs batch extraction
--   Returns TRUE on success
--   Returns FALSE on failure
---------------------------------------------------------------------------
FUNCTION "XXOD_HZ_IMP_CONTACTPTS_INT_Bat" ("P_BATCH_ID" IN NUMBER
 DEFAULT NULL, "P_AOPS_BATCH_ID" IN NUMBER
 DEFAULT NULL) 
 RETURN BOOLEAN IS

BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION ENABLE PARALLEL DML';

  BEGIN
    INSERT
    INTO
      "XXOD_HZ_IMP_CONTACTPTS_INT"
      ("ATTRIBUTE19",
      "ATTRIBUTE20",
      "BATCH_ID",
      "CONTACT_POINT_PURPOSE",
      "CONTACT_POINT_TYPE",
      "CP_ORIG_SYSTEM",
      "CP_ORIG_SYSTEM_REFERENCE",
      "CREATED_BY_MODULE",
      "EDI_REMITTANCE_INSTRUCTION",
      "EDI_REMITTANCE_METHOD",
      "EDI_TRANSACTION_HANDLING",
      "EMAIL_ADDRESS",
      "EMAIL_FORMAT",
      "LAST_UPDATE_DATE",
      "PARTY_ORIG_SYSTEM",
      "PARTY_ORIG_SYSTEM_REFERENCE",
      "PHONE_CALLING_CALENDAR",
      "PHONE_COUNTRY_CODE",
      "PHONE_EXTENSION",
      "PHONE_LINE_TYPE",
      "PHONE_NUMBER",
      "PRIMARY_FLAG",
      "RAW_PHONE_NUMBER",
      "SITE_ORIG_SYSTEM",
      "SITE_ORIG_SYSTEM_REFERENCE",
      "TELEX_NUMBER",
      "TIMEZONE_CODE",
      "URL",
      "WEB_TYPE",
      "REL_FLAG")
      (SELECT
/*+ NO_MERGE */
  TRIM( "CNTPOINT"."ORACLE_CP_ID" )/* EXP_TRIM.OUTGRP1.ORACLE_CP_ID */ "ORACLE_CP_ID",
  "CNTPOINT"."CP_ATTR20" "CP_ATTR20",
  "MP_C0024_CNTPOINT"."P_BATCH_ID" "P_BATCH_ID$1",
  CASE WHEN  "CNTPOINT"."CP_PURPOSE" = 'DUNNING'
THEN  "CNTPOINT"."CP_PURPOSE" 
WHEN  "CNTPOINT"."CP_TYPE" IN ('HFX','HPG','HPH','HEM')
THEN 'HOME'
WHEN  "CNTPOINT"."CP_TYPE" IN ('HMB')
THEN 'PERSONAL'
WHEN  "CNTPOINT"."CP_TYPE" IN ('WFX','WMB','WPG','WPH','WEM','WE1')
THEN 'BUSINESS'
WHEN  "CNTPOINT"."CP_TYPE" IN ('HUR')
THEN 'HOMEPAGE'
WHEN  "CNTPOINT"."CP_TYPE" IN ('WUR')
THEN 'BUSINESSURL'
WHEN  "CNTPOINT"."CP_TYPE" IN ('CPH','CFX','CEM')
THEN 'COLLECTIONS'
WHEN  "CNTPOINT"."CP_TYPE" IN ('TXT')
THEN 'SMS'
ELSE 
 "CNTPOINT"."CP_TYPE" 
END/* EXP_CNTPTTYP_TRNS.OUTGRP1.CONTACT_POINT_PURPOSE */ "CONTACT_POINT_PURPOSE",
  CASE WHEN  "CNTPOINT"."CP_TYPE" IN ('HFX','HMB','HPG','HPH','WFX','WMB','WPG','WPH',
                              'CPH','CFX','TXT')  
THEN 'PHONE'
WHEN  "CNTPOINT"."CP_TYPE" IN ('HEM', 'WEM','CEM','WE1')
THEN 'EMAIL'
WHEN  "CNTPOINT"."CP_TYPE" IN ('HUR','WUR')
THEN 'WEB'
END/* EXP_CNTPTTYP_TRNS.OUTGRP1.CONTACT_POINT_TYPE */ "CONTACT_POINT_TYPE",
  "CNTPOINT"."CP_ORIG_SYSTEM" "CP_ORIG_SYSTEM",
  "CNTPOINT"."CP_ORIG_SYSREF" "CP_ORIG_SYSREF",
  "MP_C0024_CNTPOINT"."CS_0_CR" "CRTBYMOD",
  "CNTPOINT"."CP_REMIT_INSTR" "CP_REMIT_INSTR",
  "CNTPOINT"."CP_REMIT_METHOD" "CP_REMIT_METHOD",
  "CNTPOINT"."CP_TRX_CODE" "CP_TRX_CODE",
  "CNTPOINT"."CP_EMAIL_ADDR" "CP_EMAIL_ADDR",
  CASE WHEN  "CNTPOINT"."CP_EMAIL_FMT"  = '*HTML' 
THEN 'MAILHTML'
WHEN  "CNTPOINT"."CP_EMAIL_FMT" = '*TEXT'
THEN 'MAILTEXT'
ELSE 
 "CNTPOINT"."CP_EMAIL_FMT" 
END/* EXP_EMLFMT_TRNS.OUTGRP1.EMAIL_FORMAT */ "EMAIL_FORMAT",
  "MP_C0024_CNTPOINT"."CS_1_LS" "LSTUPDDT",
  "CNTPOINT"."CP_PARTY_ORIG_SYSTEM" "CP_PARTY_ORIG_SYSTEM",
  "CNTPOINT"."CP_PARTY_ORIG_SYSRF" "CP_PARTY_ORIG_SYSRF",
  "CNTPOINT"."CP_CALL_CALENDAR" "CP_CALL_CALENDAR",
  "CNTPOINT"."CP_TEL_CNTRY_CD" "CP_TEL_CNTRY_CD",
  "CNTPOINT"."CP_TEL_EXT" "CP_TEL_EXT",
  CASE WHEN "CNTPOINT"."CP_TYPE" IN ('HFX','WFX','CFX')
THEN 'FAX'
WHEN "CNTPOINT"."CP_TYPE" IN ('HMB','WMB')
THEN 'MOBILE'
WHEN  "CNTPOINT"."CP_TYPE" IN ('HPG','WPG')
THEN 'PAGER'
WHEN  "CNTPOINT"."CP_TYPE" IN ('HPH','WPH','CPH')
THEN 'GEN'
WHEN  "CNTPOINT"."CP_TYPE" IN ('TXT')
THEN 'SMS'
ELSE ' '
END/* EXP_CNTPTTYP_TRNS.OUTGRP1.PHONE_LINE_TYPE */ "PHONE_LINE_TYPE",
  "CNTPOINT"."CP_TEL_NBR" "CP_TEL_NBR",
  "CNTPOINT"."CP_PRIMRY" "CP_PRIMRY",
  "CNTPOINT"."CP_TEL_RAW" "CP_TEL_RAW",
  "CNTPOINT"."CP_SITE_ORIG_SYSTEM" "CP_SITE_ORIG_SYSTEM",
  "CNTPOINT"."CP_SITE_ORIG_SYSRF" "CP_SITE_ORIG_SYSRF",
  "CNTPOINT"."CP_TELEX_NBR" "CP_TELEX_NBR",
  "CNTPOINT"."CP_TIME_ZONE_KEY" "CP_TIME_ZONE_KEY",
  "CNTPOINT"."CP_URL" "CP_URL",
  "CNTPOINT"."CP_WEB_TYPE" "CP_WEB_TYPE",
  "MP_C0024_CNTPOINT"."CS_4_RE" "REL_FLAG"
FROM
  "SIMPLIFY"."CNTPOINT"@"GANDHI.NA.ODCORP.NET" "CNTPOINT"
  WHERE 
  ( "CNTPOINT"."BATCH_NBR" = "MP_C0024_CNTPOINT"."P_AOPS_BATCH_ID" )
      );
    COMMIT;
  EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    COMMIT;
    RETURN FALSE;
  END;
  COMMIT;
  RETURN TRUE;
END "XXOD_HZ_IMP_CONTACTPTS_INT_Bat";

FUNCTION Main("P_BATCH_ID" IN NUMBER
 DEFAULT NULL, "P_AOPS_BATCH_ID" IN NUMBER
 DEFAULT NULL) RETURN NUMBER IS
get_batch_status           BOOLEAN := TRUE;
BEGIN
  -- Mapping input parameter global variable assignments
  "MP_C0024_CNTPOINT"."P_BATCH_ID" := "MP_C0024_CNTPOINT".Main."P_BATCH_ID";"MP_C0024_CNTPOINT"."P_AOPS_BATCH_ID" := "MP_C0024_CNTPOINT".Main."P_AOPS_BATCH_ID";
  

  
  
  
  
  
PROCEDURE EXEC_AUTONOMOUS_SQL(CMD IN VARCHAR2) IS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  EXECUTE IMMEDIATE (CMD);
  COMMIT;
END;
  -- Initialize all batch status variables
	"XXOD_HZ_IMP_CONTACTPTS_INT_St" := FALSE;



			
"XXOD_HZ_IMP_CONTACTPTS_INT_St" := "XXOD_HZ_IMP_CONTACTPTS_INT_Bat"; 


RETURN get_status;
END Main;
END ""MP_C0024_CNTPOINT"";

/

