
/*****************************************************************************
--  Note: This generated code is for demonstration purposes only and may
--        not be deployable.
*****************************************************************************/

CREATE OR REPLACE PACKAGE ""MP_C0024_CUSTACCTS"" AS
OWB$MAP_OBJECT_ID VARCHAR2(32) := '';
sql_stmt  VARCHAR2(32767);
get_abort BOOLEAN := FALSE;
get_abort_procedure BOOLEAN := FALSE;
get_trigger_success BOOLEAN := TRUE;
get_errors NUMBER(22) := 0;
get_status NUMBER(22) := 0;
get_error_ratio NUMBER(22) := 0;
get_global_names              VARCHAR2(10) := 'FALSE';
-- Status variable for Batch cursors
"XXOD_HZ_IMP_ACCOUNTS_INT_St" BOOLEAN := FALSE; 

"P_BATCH_ID" NUMBER;"P_AOPS_BATCH_ID" NUMBER;

-- Function Main 
-- Entry point in package ""MP_C0024_CUSTACCTS""
FUNCTION Main("P_BATCH_ID" IN NUMBER
 DEFAULT NULL, "P_AOPS_BATCH_ID" IN NUMBER
 DEFAULT NULL) RETURN NUMBER;  

END ""MP_C0024_CUSTACCTS"";

/

CREATE OR REPLACE PACKAGE BODY ""MP_C0024_CUSTACCTS"" AS




---------------------------------------------------------------------------
-- Function "XXOD_HZ_IMP_ACCOUNTS_INT_Bat"
--   performs batch extraction
--   Returns TRUE on success
--   Returns FALSE on failure
---------------------------------------------------------------------------
FUNCTION "XXOD_HZ_IMP_ACCOUNTS_INT_Bat" ("P_BATCH_ID" IN NUMBER
 DEFAULT NULL, "P_AOPS_BATCH_ID" IN NUMBER
 DEFAULT NULL) 
 RETURN BOOLEAN IS

BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION ENABLE PARALLEL DML';

  BEGIN
    INSERT
    /*+ APPEND PARALLEL("XXOD_HZ_IMP_ACCOUNTS_INT") */
    INTO
      "XXOD_HZ_IMP_ACCOUNTS_INT"
      ("BATCH_ID",
      "CREATED_BY_MODULE",
      "PARTY_ORIG_SYSTEM",
      "PARTY_ORIG_SYSTEM_REFERENCE",
      "ACCOUNT_ORIG_SYSTEM_REFERENCE",
      "CUSTOMER_ATTRIBUTE1",
      "CUSTOMER_ATTRIBUTE2",
      "CUSTOMER_ATTRIBUTE3",
      "CUSTOMER_ATTRIBUTE4",
      "CUSTOMER_ATTRIBUTE5",
      "CUSTOMER_ATTRIBUTE6",
      "CUSTOMER_ATTRIBUTE7",
      "CUSTOMER_ATTRIBUTE8",
      "CUSTOMER_ATTRIBUTE9",
      "CUSTOMER_ATTRIBUTE10",
      "CUSTOMER_ATTRIBUTE11",
      "CUSTOMER_ATTRIBUTE14",
      "CUSTOMER_ATTRIBUTE15",
      "CUSTOMER_ATTRIBUTE17",
      "CUSTOMER_ATTRIBUTE18",
      "CUSTOMER_ATTRIBUTE19",
      "CUSTOMER_ATTRIBUTE20",
      "ACCOUNT_NAME",
      "CUSTOMER_STATUS",
      "CUSTOMER_TYPE",
      "ACCOUNT_ORIG_SYSTEM",
      "SALES_CHANNEL_CODE",
      "LOYALTY_CODE",
      "SEGMENTATION_CODE")
      (SELECT
/*+ NO_MERGE */
  "MP_C0024_CUSTACCTS"."P_BATCH_ID" "P_BATCH_ID$1",
  'XXCONV' "CREATED_MODULE",
  "CUSTACCTS"."PARTY_ORIG_SYSTEM" "PARTY_ORIG_SYSTEM",
  "CUSTACCTS"."PARTY_ORIG_SYSREF" "PARTY_ORIG_SYSREF",
  TRIM( "CUSTACCTS"."ACCT_ORIG_SYSREF" )/* EXPRESSION.OUTGRP1.ACCOUNT_ORIG_SYSTEM_REFERENCE */ "ACCOUNT_ORIG_SYSTEM_REFERENCE",
  "CUSTACCTS"."ATTRIBUTE01" "ATTRIBUTE01",
  CASE WHEN  "CUSTACCTS"."ATTRIBUTE02" = 'N'
THEN 'ALLOWED'
WHEN  "CUSTACCTS"."ATTRIBUTE02" = 'V'
THEN 'VALIDATED'
WHEN  "CUSTACCTS"."ATTRIBUTE02" = 'Y'
THEN 'REQUIRED'
WHEN  "CUSTACCTS"."ATTRIBUTE02" = 'H'
THEN 'HIDDEN'
WHEN  "CUSTACCTS"."ATTRIBUTE02" = 'L'
THEN 'LINE'
WHEN  "CUSTACCTS"."ATTRIBUTE02" = 'S'
THEN 'SPLIT'
ELSE 'HIDDEN'
END/* EXPRESSION.OUTGRP1.CUSTOMER_ATTRIBUTE2 */ "CUSTOMER_ATTRIBUTE2",
  "CUSTACCTS"."ATTRIBUTE03" "ATTRIBUTE03",
  CASE WHEN  "CUSTACCTS"."ATTRIBUTE04" = 'H'
THEN 'HIDDEN'
WHEN  "CUSTACCTS"."ATTRIBUTE04" = 'N'
THEN 'ALLOWED'
WHEN  "CUSTACCTS"."ATTRIBUTE04" = 'V'
THEN 'VALIDATED'
WHEN  "CUSTACCTS"."ATTRIBUTE04" = 'Y'
THEN 'REQUIRED'
ELSE 'HIDDEN'
END/* EXPRESSION.OUTGRP1.CUSTOMER_ATTRIBUTE4 */ "CUSTOMER_ATTRIBUTE4",
  "CUSTACCTS"."ATTRIBUTE05" "ATTRIBUTE05",
  TO_CHAR(TO_DATE( "CUSTACCTS"."ATTRIBUTE06" ,'YYYYMMDD'),'DD-MON-YY')/* EXPRESSION.OUTGRP1.CUSTOMER_ATTRIBUTE6 */ "CUSTOMER_ATTRIBUTE6",
  "CUSTACCTS"."ATTRIBUTE07" "ATTRIBUTE07",
  "CUSTACCTS"."ATTRIBUTE08" "ATTRIBUTE08",
  CASE WHEN  "CUSTACCTS"."ATTRIBUTE09" = 'V'
THEN 'VALIDATED'
WHEN  "CUSTACCTS"."ATTRIBUTE09" = 'S'
THEN 'SPLIT'
WHEN  "CUSTACCTS"."ATTRIBUTE09" = 'H'
THEN 'HIDDEN'
WHEN  "CUSTACCTS"."ATTRIBUTE09" = 'N'
THEN 'ALLOWED'
WHEN  "CUSTACCTS"."ATTRIBUTE09" = 'Y'
THEN 'REQUIRED'
WHEN  "CUSTACCTS"."ATTRIBUTE09" = 'L'
THEN 'LINE'
ELSE 'HIDDEN'
END/* EXPRESSION.OUTGRP1.CUSTOMER_ATTRIBUTE9 */ "CUSTOMER_ATTRIBUTE9",
  "CUSTACCTS"."ATTRIBUTE10" "ATTRIBUTE10",
  CASE WHEN  "CUSTACCTS"."ATTRIBUTE11" = 'H'
THEN 'HIDDEN'
WHEN  "CUSTACCTS"."ATTRIBUTE11" = 'N'
THEN 'ALLOWED'
WHEN  "CUSTACCTS"."ATTRIBUTE11" = 'V'
THEN 'VALIDATED'
WHEN  "CUSTACCTS"."ATTRIBUTE11" = 'Y'
THEN 'REQUIRED'
ELSE 'HIDDEN'
END/* EXPRESSION.OUTGRP1.CUSTOMER_ATTRIBUTE11 */ "CUSTOMER_ATTRIBUTE11",
  CASE WHEN "CUSTACCTS"."ATTRIBUTE14" = 'N' 
THEN  "CUSTACCTS"."ATTRIBUTE14" 
else
 'Y' 
END/* EXPRESSION.OUTGRP1.CUSTOMER_ATTRIBUTE14 */ "CUSTOMER_ATTRIBUTE14",
  "CUSTACCTS"."ATTRIBUTE15" "ATTRIBUTE15",
  "CUSTACCTS"."ATTRIBUTE17" "ATTRIBUTE17",
  "CUSTACCTS"."ATTRIBUTE18" "ATTRIBUTE18",
  "CUSTACCTS"."ATTRIBUTE19" "ATTRIBUTE19",
  CASE WHEN  "CUSTACCTS"."ATTRIBUTE20" = 'Y'
THEN 'SIG_REQ_BOTH'
ELSE  'SIG_NOT_REQ'
END/* EXPRESSION.OUTGRP1.CUSTOMER_ATTRIBUTE20 */ "CUSTOMER_ATTRIBUTE20",
  "CUSTACCTS"."ACCT_NAME" "ACCT_NAME",
  CASE WHEN  "CUSTACCTS"."CST_STATUS" = 'A'
THEN 'A'
WHEN  "CUSTACCTS"."CST_STATUS" = 'I'
THEN 'I'
WHEN  "CUSTACCTS"."CST_STATUS" = 'P'
THEN 'I'
ELSE 'A'
END/* EXPRESSION.OUTGRP1.CUSTOMER_STATUS */ "CUSTOMER_STATUS",
  "CUSTACCTS"."CST_TYPE" "CST_TYPE",
  TRIM( "CUSTACCTS"."ACCT_ORIG_SYSTEM" )/* EXPRESSION.OUTGRP1.ACCOUNT_ORIG_SYSTEM */ "ACCOUNT_ORIG_SYSTEM",
  "CUSTACCTS"."CST_SALES_CHANNEL" "CST_SALES_CHANNEL",
  "CUSTACCTS"."LOYALTY" "LOYALTY",
  "CUSTACCTS"."SEGMENTATION" "SEGMENTATION"
FROM
  "SIMPLIFY"."CUSTACCTS"@"GANDHI.NA.ODCORP.NET" "CUSTACCTS"
  WHERE 
  ( "CUSTACCTS"."BATCH_NBR" = "MP_C0024_CUSTACCTS"."P_AOPS_BATCH_ID" )
      );
    COMMIT;
  EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    COMMIT;
    RETURN FALSE;
  END;
  COMMIT;
  RETURN TRUE;
END "XXOD_HZ_IMP_ACCOUNTS_INT_Bat";

FUNCTION Main("P_BATCH_ID" IN NUMBER
 DEFAULT NULL, "P_AOPS_BATCH_ID" IN NUMBER
 DEFAULT NULL) RETURN NUMBER IS
get_batch_status           BOOLEAN := TRUE;
BEGIN
  -- Mapping input parameter global variable assignments
  "MP_C0024_CUSTACCTS"."P_BATCH_ID" := "MP_C0024_CUSTACCTS".Main."P_BATCH_ID";"MP_C0024_CUSTACCTS"."P_AOPS_BATCH_ID" := "MP_C0024_CUSTACCTS".Main."P_AOPS_BATCH_ID";
  

  
  
  
  
  
PROCEDURE EXEC_AUTONOMOUS_SQL(CMD IN VARCHAR2) IS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  EXECUTE IMMEDIATE (CMD);
  COMMIT;
END;
  -- Initialize all batch status variables
	"XXOD_HZ_IMP_ACCOUNTS_INT_St" := FALSE;



			
"XXOD_HZ_IMP_ACCOUNTS_INT_St" := "XXOD_HZ_IMP_ACCOUNTS_INT_Bat"; 


RETURN get_status;
END Main;
END ""MP_C0024_CUSTACCTS"";

/

