
/*****************************************************************************
--  Note: This generated code is for demonstration purposes only and may
--        not be deployable.
*****************************************************************************/

CREATE OR REPLACE PACKAGE ""MP_C0024_CONTACTS"" AS
OWB$MAP_OBJECT_ID VARCHAR2(32) := '';
sql_stmt  VARCHAR2(32767);
get_abort BOOLEAN := FALSE;
get_abort_procedure BOOLEAN := FALSE;
get_trigger_success BOOLEAN := TRUE;
get_errors NUMBER(22) := 0;
get_status NUMBER(22) := 0;
get_error_ratio NUMBER(22) := 0;
get_global_names              VARCHAR2(10) := 'FALSE';
-- Status variable for Batch cursors
"XXOD_HZ_IMP_CONTACTS_INT_St" BOOLEAN := FALSE; 

"P_BATCH_ID" NUMBER;"P_AOPS_BATCH_ID" NUMBER;"CS_0_CR" VARCHAR2(30) := 'XXCONV';

-- Function Main 
-- Entry point in package ""MP_C0024_CONTACTS""
FUNCTION Main("P_BATCH_ID" IN NUMBER
 DEFAULT NULL, "P_AOPS_BATCH_ID" IN NUMBER
 DEFAULT NULL) RETURN NUMBER;  

END ""MP_C0024_CONTACTS"";

/

CREATE OR REPLACE PACKAGE BODY ""MP_C0024_CONTACTS"" AS




---------------------------------------------------------------------------
-- Function "XXOD_HZ_IMP_CONTACTS_INT_Bat"
--   performs batch extraction
--   Returns TRUE on success
--   Returns FALSE on failure
---------------------------------------------------------------------------
FUNCTION "XXOD_HZ_IMP_CONTACTS_INT_Bat" ("P_BATCH_ID" IN NUMBER
 DEFAULT NULL, "P_AOPS_BATCH_ID" IN NUMBER
 DEFAULT NULL) 
 RETURN BOOLEAN IS

BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION ENABLE PARALLEL DML';

  BEGIN
    INSERT
    INTO
      "XXOD_HZ_IMP_CONTACTS_INT"
      ("ATTRIBUTE19",
      "BATCH_ID",
      "COMMENTS",
      "CONTACT_NUMBER",
      "CONTACT_ORIG_SYSTEM",
      "CONTACT_ORIG_SYSTEM_REFERENCE",
      "CREATED_BY_MODULE",
      "DECISION_MAKER_FLAG",
      "DEPARTMENT",
      "DEPARTMENT_CODE",
      "JOB_TITLE",
      "JOB_TITLE_CODE",
      "OBJ_ORIG_SYSTEM",
      "OBJ_ORIG_SYSTEM_REFERENCE",
      "REFERENCE_USE_FLAG",
      "REL_COMMENTS",
      "RELATIONSHIP_CODE",
      "RELATIONSHIP_TYPE",
      "START_DATE",
      "SUB_ORIG_SYSTEM",
      "SUB_ORIG_SYSTEM_REFERENCE")
      (SELECT
/*+ NO_MERGE */
  TRIM( "CONTACTS"."ORACLE_CONTACT_ID" )/* EXP_TRIM.OUTGRP1.ORACLE_CONTACT_ID */ "ORACLE_CONTACT_ID",
  "MP_C0024_CONTACTS"."P_BATCH_ID" "P_BATCH_ID$1",
  "CONTACTS"."CN_COMMENTS" "CN_COMMENTS",
  "CONTACTS"."CONTACT_NBR" "CONTACT_NBR",
  TRIM( "CONTACTS"."CONT_ORIG_SYSTEM" )/* EXPRESSION_0.OUTGRP1.CONTACT_ORIG_SYSTEM */ "CONTACT_ORIG_SYSTEM",
  TRIM( "CONTACTS"."CONT_ORIG_SYSREF" )/* EXPRESSION_0.OUTGRP1.CONTACT_ORIG_SYSTEM_REFERENCE */ "CONTACT_ORIG_SYSTEM_REFERENCE",
  "MP_C0024_CONTACTS"."CS_0_CR" "CRTBYMOD",
  "CONTACTS"."CONT_DECISION_MKR" "CONT_DECISION_MKR",
  "CONTACTS"."CONTACT_DEPT" "CONTACT_DEPT",
  "CONTACTS"."CONT_DPT_CD" "CONT_DPT_CD",
  "CONTACTS"."CONT_JOB_TTL" "CONT_JOB_TTL",
  "CONTACTS"."CONT_JOB_COD" "CONT_JOB_COD",
  "CONTACTS"."CN_OBJ_ORG_SYS" "CN_OBJ_ORG_SYS",
  "CONTACTS"."CN_OBJ_ORIG_SREF" "CN_OBJ_ORIG_SREF",
  "CONTACTS"."CN_REFERENCE_OK" "CN_REFERENCE_OK",
  "CONTACTS"."CN_USER_COMM" "CN_USER_COMM",
  "CONTACTS"."CN_REL_CODE" "CN_REL_CODE",
  "CONTACTS"."CN_REL_TYPE" "CN_REL_TYPE",
  TO_DATE("CONTACTS"."CN_START_DT",'RRRRMMDD')/* EXPRESSION.OUTGRP1.START_DATE */ "START_DATE",
  "CONTACTS"."CN_SBJ_ORG_SYS" "CN_SBJ_ORG_SYS",
  "CONTACTS"."CN_SBJ_ORIG_SREF" "CN_SBJ_ORIG_SREF"
FROM
  "SIMPLIFY"."CONTACTS"@"GANDHI.NA.ODCORP.NET" "CONTACTS"
  WHERE 
  ( "CONTACTS"."BATCH_NBR" = "MP_C0024_CONTACTS"."P_AOPS_BATCH_ID" )
      );
    COMMIT;
  EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    COMMIT;
    RETURN FALSE;
  END;
  COMMIT;
  RETURN TRUE;
END "XXOD_HZ_IMP_CONTACTS_INT_Bat";

FUNCTION Main("P_BATCH_ID" IN NUMBER
 DEFAULT NULL, "P_AOPS_BATCH_ID" IN NUMBER
 DEFAULT NULL) RETURN NUMBER IS
get_batch_status           BOOLEAN := TRUE;
BEGIN
  -- Mapping input parameter global variable assignments
  "MP_C0024_CONTACTS"."P_BATCH_ID" := "MP_C0024_CONTACTS".Main."P_BATCH_ID";"MP_C0024_CONTACTS"."P_AOPS_BATCH_ID" := "MP_C0024_CONTACTS".Main."P_AOPS_BATCH_ID";
  

  
  
  
  
  
PROCEDURE EXEC_AUTONOMOUS_SQL(CMD IN VARCHAR2) IS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  EXECUTE IMMEDIATE (CMD);
  COMMIT;
END;
  -- Initialize all batch status variables
	"XXOD_HZ_IMP_CONTACTS_INT_St" := FALSE;



			
"XXOD_HZ_IMP_CONTACTS_INT_St" := "XXOD_HZ_IMP_CONTACTS_INT_Bat"; 


RETURN get_status;
END Main;
END ""MP_C0024_CONTACTS"";

/

