INSERT INTO apps.Q_OD_PB_TESTING_IV
    (      process_status, 
               organization_code ,
                  plan_name,
                  insert_type,
		  matching_elements,
		OD_PB_PROGRAM_TEST_TYPE           ,             
		OD_PB_DATE_REPORTED               ,             
		OD_PB_TECH_RPT_NUM                ,             
		OD_PB_CA_TYPE                     ,             
		OD_PB_RESULTS                     ,             
		OD_PB_APPROVAL_STATUS             ,             
		OD_PB_CLASS                       ,             
		OD_PB_COMMENTS                    ,             
		OD_PB_COMPARISON_NAME             ,             
		OD_PB_CTQ_LIST                    ,             
		OD_PB_CTQ_RESULTS                 ,             
		OD_PB_DATE_APPROVED               ,             
		OD_PB_DATE_DUE                    ,             
		OD_PB_DATE_KICKOFF                ,             
		OD_PB_DATE_OPENED                 ,             
		OD_PB_DATE_PROPOSAL_APPROVED      ,             
		OD_PB_DATE_PROPOSAL_PROVIDED      ,             
		OD_PB_DATE_REPORT_DUE             ,             
		OD_PB_DATE_TESTING_BEGINS         ,             
		OD_PB_DPPM                        ,             
		OD_PB_FACTORY_ID                  ,             
		OD_PB_1ST_ARTICLE_DEFECT_RATE     ,             
		OD_PB_MINOR                       ,             
		OD_PB_MAJOR                       ,             
		OD_PB_CRITICAL                    ,             
		OD_PB_MERCHANDISING_APPROVER      ,             
		OD_PB_PO_NUM                      ,             
		OD_PB_QA_APPROVER                 ,             
		OD_PB_SAMPLE_SIZE                 ,             
		OD_PB_SKU                         ,             
		OD_PB_DEPARTMENT                  ,             
		OD_PB_CONTACT                     ,             
		OD_PB_VENDORS_AWARDED             ,             
		OD_PB_VENDOR_COMMENTS             ,             
		OD_PB_AUDITOR_NAME                ,             
		OD_PB_ORG_AUDITED                 ,             
		OD_PB_FQA_SCORE                   ,             
		OD_PB_SPECIFICATION_NAME          ,             
		OD_PB_LOT_SIZE                   ,              
		OD_PB_DEFECT_SUM                 ,              
		OD_PB_OBJECTIVE                  ,              
		OD_PB_SUPPLIER                   ,              
		OD_PB_ATTACHMENT                 ,              
		OD_PB_FACTORY_NAME               ,              
		OD_PB_TESTINGPLAN_ID             ,              
		OD_PB_PROD_TEST_REPT_NUM         ,              
		OD_PB_PROD_TEST_RESULT           ,              
		OD_PB_TRANSIT_TEST_REPT_NUMBER   ,              
		OD_PB_TRANSIT_TEST_RESULT        ,              
		OD_PB_ART_TEST_REPORT_NUMBER     ,              
		OD_PB_ARTWORK_TEST_RESULT        ,              
		OD_PB_QA_ENGR_EMAIL              ,              
		OD_PB_ODC_QA_ENGINEER            ,              
	        qa_created_by_name	,
                qa_last_updated_by_name,
		od_pb_legacy_col_id,
		od_pb_legacy_ocr_id,
		od_pb_legacy_rec_id
        )
SELECT            '1',
                  'PRJ',
                  'OD_PB_TESTING',
                  '1', --1 for INSERT
              'OD_PB_RECORD_ID,OD_PB_PROGRAM_TEST_TYPE,OD_PB_SKU',
		OD_PB_PROGRAM_TEST_TYPE           ,             
		OD_PB_DATE_REPORTED               ,             
		OD_PB_TECH_RPT_NUM                ,             
		OD_PB_CA_TYPE                     ,             
		OD_PB_RESULTS                     ,             
		OD_PB_APPROVAL_STATUS             ,             
		OD_PB_CLASS                       ,             
		OD_PB_COMMENTS                    ,             
		OD_PB_COMPARISON_NAME             ,             
		OD_PB_CTQ_LIST                    ,             
		OD_PB_CTQ_RESULTS                 ,             
		OD_PB_DATE_APPROVED               ,             
		OD_PB_DATE_DUE                    ,             
		OD_PB_DATE_KICKOFF                ,             
		OD_PB_DATE_OPENED                 ,             
		OD_PB_DATE_PROPOSAL_APPROVED      ,             
		OD_PB_DATE_PROPOSAL_PROVIDED      ,             
		OD_PB_DATE_REPORT_DUE             ,             
		OD_PB_DATE_TESTING_BEGINS         ,             
		OD_PB_DPPM                        ,             
		OD_PB_FACTORY_ID                  ,             
		OD_PB_1ST_ARTICLE_DEFECT_RATE     ,             
		OD_PB_MINOR                       ,             
		OD_PB_MAJOR                       ,             
		OD_PB_CRITICAL                    ,             
		OD_PB_MERCHANDISING_APPROVER      ,             
		OD_PB_PO_NUM                      ,             
		OD_PB_QA_APPROVER                 ,             
		OD_PB_SAMPLE_SIZE                 ,             
		OD_PB_SKU                         ,             
		OD_PB_DEPARTMENT                  ,             
		OD_PB_CONTACT                     ,             
		OD_PB_VENDORS_AWARDED             ,             
		OD_PB_VENDOR_COMMENTS             ,             
		OD_PB_AUDITOR_NAME                ,             
		OD_PB_ORG_AUDITED                 ,             
		OD_PB_FQA_SCORE                   ,             
		OD_PB_SPECIFICATION_NAME          ,             
		OD_PB_LOT_SIZE                   ,              
		OD_PB_DEFECT_SUM                 ,              
		OD_PB_OBJECTIVE                  ,              
		OD_PB_SUPPLIER                   ,              
		OD_PB_ATTACHMENT                 ,              
		OD_PB_FACTORY_NAME               ,              
		OD_PB_TESTINGPLAN_ID             ,              
		OD_PB_PROD_TEST_REPT_NUM         ,              
		OD_PB_PROD_TEST_RESULT           ,              
		OD_PB_TRANSIT_TEST_REPT_NUMBER   ,              
		OD_PB_TRANSIT_TEST_RESULT        ,              
		OD_PB_ART_TEST_REPORT_NUMBER     ,              
		OD_PB_ARTWORK_TEST_RESULT        ,              
		OD_PB_QA_ENGR_EMAIL              ,              
		OD_PB_ODC_QA_ENGINEER            ,              
		d.user_name,
          e.user_name,
		a.collection_id,
		a.occurrence,
		a.OD_PB_RECORD_ID
 FROM     
    apps.fnd_user e,
    apps.fnd_user d,
    apps.fnd_user@GSIPRD01.NA.ODCORP.NET b,
    apps.fnd_user@GSIPRD01.NA.ODCORP.NET c,
        apps.Q_OD_PB_TESTING_V@GSIPRD01.NA.ODCORP.NET a
 WHERE  c.user_name=a.created_by
   AND  b.user_name=a.last_updated_by
   AND  d.user_name=c.user_name
   AND  e.user_name=b.user_name;
commit;
