begin
INSERT INTO XXCRM.XXBI_USER_SITE_DTL
(select x.rsd_user_id,
        rownum sort_id, 
        nvl(x.user_id, -1) user_id,
        nvl(x.m1_user_id, -1) m1_user_id,
        nvl(x.m2_user_id, -1) m2_user_id,
        nvl(x.m3_user_id, -1) m3_user_id,
        nvl(x.org_type, 'XX') org_type,
        nvl(x.potential_type_cd, 'NEW') potential_type_cd,
        nvl(x.od_site_full_sic_code, 'XX') od_site_full_sic_code,
        nvl((select sic.sic_group_type from xxcrm.xxbi_od_sic_code_mapping sic
             where sic.sic_code =  x.od_site_sic_code
            ), 'XX'
           ) od_site_sic_code,
        nvl(x.od_site_wcw, -1) od_site_wcw,
        nvl((select id from apps.xxbi_cust_wcw_range_dim_v wcw
             where  x.od_site_wcw between wcw.low_val and wcw.high_val and rownum <2 
            ), -1
           ) od_site_wcw_range,
        nvl(x.city, 'XX') city,
        nvl(x.state_province, 'XX') state_province,
        nvl(x.postal_code, 'XX') postal_code,
        nvl(x.cust_loyalty_code, 'XX') cust_loyalty_code,
        nvl(x.party_revenue_band, 'XX') party_revenue_band,
        nvl(x.site_use, 'XX') site_use_id,
        nvl((select value from apps.XXBI_PARTY_SITE_USES_DIM_V sud
             where sud.id = x.site_use and rownum <2 
            ), 'XX'
           ) site_use,
        nvl(x.org_site_status, 'X') org_site_status,
        x.comparable_potential_amt,
        x.org_number,
        x.org_name,
        x.org_site_number,
        x.site_name,
        x.site_address,
        x.last_activity_date,
        nvl(x.m4_user_id, -1) m4_user_id,
        nvl(x.m5_user_id, -1) m5_user_id,
        nvl(x.m6_user_id, -1) m6_user_id,
        x.party_site_id,
        x.party_id,
        x.location_id,
        nvl(x.site_rank, -1) site_rank,
        nvl(x.potential_type_nm, 'No Model') potential_type_nm,
        x.resource_name,
        x.m1_resource_name,
        x.m2_resource_name,
        x.m3_resource_name,
        x.m4_resource_name,
        x.m5_resource_name,
        x.m6_resource_name,
        x.cust_account_id,
        x.cust_acct_site_id,
        x.parent_party_id, 
        x.parent_party_name,
        x.gparent_party_id,
        x.gparent_party_name,
        x.resource_id,
        x.role_id,
        x.group_id,
        x.access_id,
        x.create_view_lead_oppty,
        x.cust_segment_code,
        x.contact_title,
        x.contact_name,
        x.contact_phone
 from   (       select /*+ parallel(a, 20) */
                b.rsd_user_id,
                b.user_id,
                b.m1_user_id,
                b.m2_user_id,
                b.m3_user_id,
                a.org_type,
                a.potential_type_cd,
                a.od_site_sic_code,
                a.od_site_wcw,
                a.city,
                a.state_province,
                a.postal_code,
                a.cust_loyalty_code,
                a.party_revenue_band,
                a.site_use,
                a.org_site_status,
                a.comparable_potential_amt,
                a.org_number,
                a.org_name,
                a.org_site_number,
                a.site_name,
                a.site_address,
                a.last_activity_date,
                b.m4_user_id,
                b.m5_user_id,
                b.m6_user_id,
                a.party_site_id,
                a.party_id,
                a.location_id,
                a.site_rank,
                a.potential_type_nm,
                b.resource_name,
                b.m1_resource_name,
                b.m2_resource_name,
                b.m3_resource_name,
                b.m4_resource_name,
                b.m5_resource_name,
                b.m6_resource_name,
                a.cust_account_id,
                a.cust_acct_site_id,
                a.parent_party_id,
                a.parent_party_name,
                a.gparent_party_id,
                a.gparent_party_name,
                a.resource_id,
                a.role_id,
                a.group_id,
                a.access_id,
                a.create_view_lead_oppty,
                a.od_site_full_sic_code,
                a.cust_segment_code,
                a.contact_title,
                a.contact_name,
                a.contact_phone
         from   xxcrm.xxbi_user_site_dtl_tbl a,
                apps.xxbi_group_mbr_info_mv b
         where  a.resource_id = b.resource_id
           and  a.role_id     = b.role_id
           and  a.group_id    = b.group_id
         order by b.rsd_user_id, a.site_rank desc, a.comparable_potential_amt desc
        ) x
      );

        
COMMIT; 
end;