DECLARE
  P_INIT_MSG_LIST VARCHAR2(200);
  P_RELATIONSHIP_REC APPS.HZ_RELATIONSHIP_V2PUB.RELATIONSHIP_REC_TYPE;
  P_OBJECT_VERSION_NUMBER NUMBER;
  P_PARTY_OBJECT_VERSION_NUMBER NUMBER;
  X_RETURN_STATUS VARCHAR2(200);
  X_MSG_COUNT NUMBER;
  X_MSG_DATA VARCHAR2(200);
BEGIN
  P_INIT_MSG_LIST := NULL;
  -- Modify the code to initialize the variable
  P_RELATIONSHIP_REC.relationship_id := 27516030;
  P_RELATIONSHIP_REC.status := 'I';
  P_OBJECT_VERSION_NUMBER := 2;
  P_PARTY_OBJECT_VERSION_NUMBER := 1;

  HZ_RELATIONSHIP_V2PUB.UPDATE_RELATIONSHIP(
    P_INIT_MSG_LIST => P_INIT_MSG_LIST,
    P_RELATIONSHIP_REC => P_RELATIONSHIP_REC,
    P_OBJECT_VERSION_NUMBER => P_OBJECT_VERSION_NUMBER,
    P_PARTY_OBJECT_VERSION_NUMBER => P_PARTY_OBJECT_VERSION_NUMBER,
    X_RETURN_STATUS => X_RETURN_STATUS,
    X_MSG_COUNT => X_MSG_COUNT,
    X_MSG_DATA => X_MSG_DATA
  );
  DBMS_OUTPUT.PUT_LINE('P_OBJECT_VERSION_NUMBER = ' || P_OBJECT_VERSION_NUMBER);
  DBMS_OUTPUT.PUT_LINE('P_PARTY_OBJECT_VERSION_NUMBER = ' || P_PARTY_OBJECT_VERSION_NUMBER);
  DBMS_OUTPUT.PUT_LINE('X_RETURN_STATUS = ' || X_RETURN_STATUS);
  DBMS_OUTPUT.PUT_LINE('X_MSG_COUNT = ' || X_MSG_COUNT);
  DBMS_OUTPUT.PUT_LINE('X_MSG_DATA = ' || X_MSG_DATA);
END;
/
