UPDATE XX_AR_EBL_FILE
SET STATUS='RENDER',
file_type='STUB'
where file_id=3707448;


UPDATE XX_AR_EBL_TRANSMISSION
SET status='SEND',TRANSMISSION_TYPE = 'EMAIL'
WHERE TRANSMISSION_ID=3477737;
 
COMMIT;   

SHOW ERRORS;

EXIT;