-- Declare package containing conversion functions between SQL and PL/SQL types
CREATE OR REPLACE PACKAGE UPDATEPROFILE_WRAPPERPACKAGE AS
   FUNCTION fnd_profile$save (X_NAME VARCHAR2,
	X_VALUE VARCHAR2,
	X_LEVEL_NAME VARCHAR2,
	X_LEVEL_VALUE VARCHAR2,
	X_LEVEL_VALUE_APP_ID VARCHAR2,
	X_LEVEL_VALUE2 VARCHAR2
	) RETURN INTEGER;
END UPDATEPROFILE_WRAPPERPACKAGE;
/
show errors
CREATE OR REPLACE PACKAGE BODY UPDATEPROFILE_WRAPPERPACKAGE IS

   FUNCTION fnd_profile$save (X_NAME VARCHAR2,
	X_VALUE VARCHAR2,
	X_LEVEL_NAME VARCHAR2,
	X_LEVEL_VALUE VARCHAR2,
	X_LEVEL_VALUE_APP_ID VARCHAR2,
	X_LEVEL_VALUE2 VARCHAR2
	) RETURN INTEGER IS
 RETURN_ INTEGER;
   BEGIN
      RETURN_ := SYS.SQLJUTL.BOOL2INT(APPS.FND_PROFILE.SAVE(X_NAME,
	X_VALUE,
	X_LEVEL_NAME,
	X_LEVEL_VALUE,
	X_LEVEL_VALUE_APP_ID,
	X_LEVEL_VALUE2
	));
      return RETURN_;
   END fnd_profile$save;

END UPDATEPROFILE_WRAPPERPACKAGE;
/
show errors
exit
