GRANT SELECT ON xxfin.XX_AR_SELF_SERV_BAD_ADDR TO "ERP_SYSTEM_TABLE_SELECT_ROLE";
GRANT SELECT ON xxfin.XX_AR_SELF_SERV_BAD_CONTACT TO "ERP_SYSTEM_TABLE_SELECT_ROLE";
GRANT SELECT ON xxfin.XX_AR_SELF_SERV_BAD_EMAIL TO "ERP_SYSTEM_TABLE_SELECT_ROLE";
GRANT SELECT ON xxfin.XX_AR_SS_CMN_TBL TO "ERP_SYSTEM_TABLE_SELECT_ROLE";
GRANT SELECT ON xxfin.XX_AR_SS_FILE_NAMES TO "ERP_SYSTEM_TABLE_SELECT_ROLE";
GRANT SELECT ON xxfin.XX_AR_SS_FILE_NAMES_HIST TO "ERP_SYSTEM_TABLE_SELECT_ROLE";
GRANT SELECT ON xxfin.XX_WEB_SERVICE_CALLS TO "ERP_SYSTEM_TABLE_SELECT_ROLE";