GRANT SELECT ON xxfin.XX_AR_SCAAS_FILES TO "ERP_SYSTEM_TABLE_SELECT_ROLE";
GRANT SELECT ON xxfin.XX_AR_SCAAS_FILES_HIST TO "ERP_SYSTEM_TABLE_SELECT_ROLE";
GRANT SELECT ON xxfin.XX_AR_SCAAS_INTERFACE TO "ERP_SYSTEM_TABLE_SELECT_ROLE";
GRANT SELECT ON xxfin.XX_AR_SCAAS_INTERFACE_HIST TO "ERP_SYSTEM_TABLE_SELECT_ROLE";