SET SHOW         OFF
SET VERIFY       OFF
SET ECHO         OFF
SET TAB          OFF
SET FEEDBACK     ON

---  AUTOINVOICE Indexes

CREATE INDEX XXFIN.XX_RA_INTERFACE_LINES_N1 ON AR.RA_INTERFACE_LINES_ALL(SALES_ORDER);


CREATE UNIQUE INDEX XXFIN.XX_RA_INTERFACE_LINES_N2 ON AR.RA_INTERFACE_LINES_ALL
(INTERFACE_LINE_CONTEXT, 
INTERFACE_LINE_ATTRIBUTE1,
INTERFACE_LINE_ATTRIBUTE2, 
INTERFACE_LINE_ATTRIBUTE3,
INTERFACE_LINE_ATTRIBUTE4,
INTERFACE_LINE_ATTRIBUTE5,
INTERFACE_LINE_ATTRIBUTE6,
INTERFACE_LINE_ATTRIBUTE7,
INTERFACE_LINE_ATTRIBUTE8,
INTERFACE_LINE_ATTRIBUTE9,
INTERFACE_LINE_ATTRIBUTE10,
INTERFACE_LINE_ATTRIBUTE11,
INTERFACE_LINE_ATTRIBUTE12,
INTERFACE_LINE_ATTRIBUTE13,
INTERFACE_LINE_ATTRIBUTE14);

CREATE INDEX XXFIN.XX_RA_INTERFACE_LINES_N4 ON AR.RA_INTERFACE_LINES_ALL
(LINK_TO_LINE_CONTEXT,
LINK_TO_LINE_ATTRIBUTE1,
LINK_TO_LINE_ATTRIBUTE2,
LINK_TO_LINE_ATTRIBUTE3,
LINK_TO_LINE_ATTRIBUTE4,
LINK_TO_LINE_ATTRIBUTE5,
LINK_TO_LINE_ATTRIBUTE6,
LINK_TO_LINE_ATTRIBUTE7,
LINK_TO_LINE_ATTRIBUTE8,
LINK_TO_LINE_ATTRIBUTE9,
LINK_TO_LINE_ATTRIBUTE10,
LINK_TO_LINE_ATTRIBUTE11,
LINK_TO_LINE_ATTRIBUTE12,
LINK_TO_LINE_ATTRIBUTE13,
LINK_TO_LINE_ATTRIBUTE14);


CREATE INDEX XXFIN.XX_RA_INTERFACE_DISTRIB_N1 ON AR.RA_INTERFACE_DISTRIBUTIONS_ALL
(INTERFACE_LINE_CONTEXT, 
INTERFACE_LINE_ATTRIBUTE1,
INTERFACE_LINE_ATTRIBUTE2, 
INTERFACE_LINE_ATTRIBUTE3,
INTERFACE_LINE_ATTRIBUTE4,
INTERFACE_LINE_ATTRIBUTE5,
INTERFACE_LINE_ATTRIBUTE6,
INTERFACE_LINE_ATTRIBUTE7,
INTERFACE_LINE_ATTRIBUTE8,
INTERFACE_LINE_ATTRIBUTE9,
INTERFACE_LINE_ATTRIBUTE10,
INTERFACE_LINE_ATTRIBUTE11,
INTERFACE_LINE_ATTRIBUTE12,
INTERFACE_LINE_ATTRIBUTE13,
INTERFACE_LINE_ATTRIBUTE14);


CREATE INDEX XXFIN.XX_RA_INTERFACE_DISTRIB_N2 ON AR.RA_INTERFACE_DISTRIBUTIONS_ALL(REQUEST_ID);


CREATE UNIQUE INDEX XXFIN.XX_RA_INTERFACE_SCREDIT_N1 ON AR.RA_INTERFACE_SALESCREDITS_ALL
(INTERFACE_LINE_CONTEXT, 
INTERFACE_LINE_ATTRIBUTE1,
INTERFACE_LINE_ATTRIBUTE2, 
INTERFACE_LINE_ATTRIBUTE3,
INTERFACE_LINE_ATTRIBUTE4,
INTERFACE_LINE_ATTRIBUTE5,
INTERFACE_LINE_ATTRIBUTE6,
INTERFACE_LINE_ATTRIBUTE7,
INTERFACE_LINE_ATTRIBUTE8,
INTERFACE_LINE_ATTRIBUTE9,
INTERFACE_LINE_ATTRIBUTE10,
INTERFACE_LINE_ATTRIBUTE11,
INTERFACE_LINE_ATTRIBUTE12,
INTERFACE_LINE_ATTRIBUTE13,
INTERFACE_LINE_ATTRIBUTE14);


CREATE INDEX XXFIN.XX_RA_INTERFACE_SCREDIT_N2 ON AR.RA_INTERFACE_SALESCREDITS_ALL(REQUEST_ID);


CREATE INDEX XXFIN.XX_AR_CUSTOMER_TRX_N1 ON AR.RA_CUSTOMER_TRX_ALL
(INTERFACE_HEADER_CONTEXT,
INTERFACE_HEADER_ATTRIBUTE1,
INTERFACE_HEADER_ATTRIBUTE2,
INTERFACE_HEADER_ATTRIBUTE3,
INTERFACE_HEADER_ATTRIBUTE4,
INTERFACE_HEADER_ATTRIBUTE5,
INTERFACE_HEADER_ATTRIBUTE6,
INTERFACE_HEADER_ATTRIBUTE7,
INTERFACE_HEADER_ATTRIBUTE8,
INTERFACE_HEADER_ATTRIBUTE9,
INTERFACE_HEADER_ATTRIBUTE10,
INTERFACE_HEADER_ATTRIBUTE11,
INTERFACE_HEADER_ATTRIBUTE12,
INTERFACE_HEADER_ATTRIBUTE13,
INTERFACE_HEADER_ATTRIBUTE14);



CREATE INDEX XXFIN.XX_RA_CUSTOMER_TRX_LINES_N1 ON AR.RA_CUSTOMER_TRX_LINES_ALL
(INTERFACE_LINE_CONTEXT, 
INTERFACE_LINE_ATTRIBUTE1,
INTERFACE_LINE_ATTRIBUTE2, 
INTERFACE_LINE_ATTRIBUTE3,
INTERFACE_LINE_ATTRIBUTE4,
INTERFACE_LINE_ATTRIBUTE5,
INTERFACE_LINE_ATTRIBUTE6,
INTERFACE_LINE_ATTRIBUTE7,
INTERFACE_LINE_ATTRIBUTE8,
INTERFACE_LINE_ATTRIBUTE9,
INTERFACE_LINE_ATTRIBUTE10,
INTERFACE_LINE_ATTRIBUTE11,
INTERFACE_LINE_ATTRIBUTE12,
INTERFACE_LINE_ATTRIBUTE13,
INTERFACE_LINE_ATTRIBUTE14);


CREATE INDEX XXFIN.XX_MTL_SYSTEMS_ITEMS_B_N1 ON INV.MTL_SYSTEM_ITEMS_B(SEGMENT1);


CREATE INDEX XXFIN.XX_RA_TERRITORIES_N1 ON AR.RA_TERRITORIES(SEGMENT1);

--CREATE INDEX XXFIN.XX_RA_INTERFACE_DISTRIB_N3 ON AR.RA_INTERFACE_DISTRIBUTIONS_ALL(SEGMENT1);
--commented the index as per Satish suggestion.

CREATE INDEX XXFIN.XX_AR_CUSTOMER_TRX_N2 ON AR.RA_CUSTOMER_TRX_ALL
(ATTRIBUTE14);

---Added by Raghu on 04/14/08 based on Samy's suggestion.
CREATE INDEX XXFIN.XX_RA_INTERFACE_DISTRIB_N3 
ON AR.RA_INTERFACE_DISTRIBUTIONS_ALL(INTERFACE_DISTRIBUTION_ID, ACCOUNT_CLASS, ORG_ID);

--Added for HVOP purpose as per Manish's request
CREATE INDEX XXFIN.XX_RA_CUSTOMER_TRX_LINES_N2 ON AR.RA_CUSTOMER_TRX_LINES_ALL
 (INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE6);

CREATE INDEX XXFIN.XX_RA_INTERFACE_LINES_N5 ON AR.RA_INTERFACE_LINES_ALL
(INTERFACE_LINE_CONTEXT, INTERFACE_LINE_ATTRIBUTE6);


-- Added for performance of COGS GL Interface - Prakash Sankaran 5/10/2008
CREATE INDEX XXFIN.XX_RA_CUST_TRX_LINE_GL_DIST_N1
ON AR.RA_CUST_TRX_LINE_GL_DIST_ALL(ACCOUNT_CLASS, ATTRIBUTE_CATEGORY, ATTRIBUTE6);