SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;

PROMPT
PROMPT Creating OBJECT TYPE APPS.XX_CRM_ROLE_JOB_DEL 
PROMPT

create or replace
TYPE APPS.XX_CRM_ROLE_JOB_DEL AS OBJECT
(
  JOB_ROLE_ID NUMBER(15,0),
  OBJECT_VERSION_NUM  NUMBER(15,0)
);
/

WHENEVER SQLERROR CONTINUE

PROMPT
PROMPT Exiting....
PROMPT

SET FEEDBACK ON

EXIT;
