SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;

PROMPT
PROMPT Creating OBJECT TYPE APPS.XX_CRM_ROLE_RELATE_MOD 
PROMPT

create or replace
TYPE       APPS.XX_CRM_ROLE_RELATE_MOD AS OBJECT(
      ROLE_RELATE_ID              NUMBER(15,0),
      OBJECT_VERSION_NUMBER     VARCHAR2(30)
);
/

WHENEVER SQLERROR CONTINUE

PROMPT
PROMPT Exiting....
PROMPT

SET FEEDBACK ON

EXIT;
