--drop table XXCRM.XX_CRM_INACTIVED_PROSPECTS;
CREATE TABLE XXCRM.XX_CRM_INACTIVED_PROSPECTS 
(	
     PARTY_ID                    NUMBER
);

CREATE INDEX XXCRM.XX_CRM_INACTIVED_PROSPECTS_N1 ON XXCRM.XX_CRM_INACTIVED_PROSPECTS (PARTY_ID);