SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;
-- +============================================================================================+
-- |                  Office Depot - Project Simplify                                           |
-- +============================================================================================+
-- | Name        : XX_CRM_CUST360DETAILS_PKG.pkb                                                     |
-- | Description : XX_CRM_CUST360DETAILS_PKG                                                                    |
-- |                                                                                            |
-- |                                                                                            |
-- |Change Record:                                                                              |
-- |===============                                                                             |
-- |Version     Date           Author               Remarks                                     |
-- |=======    ==========      ================     ============================================|
-- |1.0        18-May-2016     Shubashree R        Removed the schema reference for GSCC compliance QC#37898|
-- +============================================================================================+
create or replace
PACKAGE BODY XX_CRM_CUST360DETAILS_PKG
AS
PROCEDURE GET_CUST_INFO (
                           P_AOPS_ACCT_ID  IN   NUMBER,
                           P_CUST_OUT      OUT  XX_CRM_FULL_CUST_INFO_BO
)
AS

XX_CRM_AR_COLLECTOR_OBJS_T   XX_CRM_AR_COLLECTOR_OBJS :=   XX_CRM_AR_COLLECTOR_OBJS();
XX_CRM_GRAND_PARENT_OBJS_T   XX_CRM_GRAND_PARENT_OBJS :=   XX_CRM_GRAND_PARENT_OBJS(); 
XX_CRM_CREDIT_LIMTS_OBJS_T   XX_CRM_CREDIT_LIMTS_OBJS :=   XX_CRM_CREDIT_LIMTS_OBJS(); 
XX_CRM_AGING_BUCKET_OBJS_T   XX_CRM_AGING_BUCKET_OBJS :=   XX_CRM_AGING_BUCKET_OBJS(); 
XX_CRM_EBILL_CONTACT_OBJS_T  XX_CRM_EBILL_CONTACT_OBJS :=  XX_CRM_EBILL_CONTACT_OBJS();
XX_CRM_PAYMENT_TERMS_OBJS_T  XX_CRM_PAYMENT_TERMS_OBJS :=  XX_CRM_PAYMENT_TERMS_OBJS();

FULL_CUST_INFO_BO   XX_CRM_FULL_CUST_INFO_BO;

BEGIN

SELECT CAST(MULTISET
 ( SELECT RSC_EMP.SOURCE_NAME   COLLECTOR_NAME,
         COL.NAME              COLLECTOR_EMP_NUMBER,
         RSC_EMP.SOURCE_EMAIL  COLLECTOR_EMAIL_ADDRESS,
         RSC_SUP.SOURCE_NAME   COLLECTOR_SUPERVISOR_NAME,
         RSC_SUP.SOURCE_EMAIL  COLLECTOR_SUPERVISOR_EMAIL,
         DECODE(HP_EMP.PRIMARY_PHONE_LINE_TYPE,'PHONE',HP_EMP.PRIMARY_PHONE_NUMBER,NULL) COLLECTOR_PHONE_NUMBER,
         DECODE(HP_EMP.PRIMARY_PHONE_LINE_TYPE,'FAX',HP_EMP.PRIMARY_PHONE_NUMBER,NULL) COLLECTOR_FAX_NUMBER,
         DECODE(HP_SUPP.PRIMARY_PHONE_LINE_TYPE,'PHONE',HP_SUPP.PRIMARY_PHONE_NUMBER,NULL) COLLECTOR_SUP_PHONE_NUMBER,
         DECODE(HP_SUPP.PRIMARY_PHONE_LINE_TYPE,'FAX',HP_SUPP.PRIMARY_PHONE_NUMBER,NULL) COLLECTOR_SUP_FAX_NUMBER
  FROM HZ_CUSTOMER_PROFILES PROF,
    HZ_CUST_ACCOUNTS ACCT,
    AR_COLLECTORS COL,
    JTF_RS_RESOURCE_EXTNS RSC_EMP,
    JTF_RS_RESOURCE_EXTNS RSC_SUP,
    HZ_PARTIES HP_EMP,
    HZ_PARTIES HP_SUPP
  WHERE ACCT.CUST_ACCOUNT_ID     =PROF.CUST_ACCOUNT_ID
  AND COL.COLLECTOR_ID(+)        = PROF.COLLECTOR_ID
  AND ACCT.ORIG_SYSTEM_REFERENCE = LPAD(P_AOPS_ACCT_ID, 8, '0') || '-00001-A0'
  AND PROF.SITE_USE_ID      IS NULL
  AND COL.STATUS             ='A'
  AND RSC_EMP.RESOURCE_ID    =COL.RESOURCE_ID
  AND RSC_EMP.SOURCE_MGR_ID  =RSC_SUP.SOURCE_ID
  AND RSC_EMP.PERSON_PARTY_ID=HP_EMP.PARTY_ID
  AND RSC_SUP.PERSON_PARTY_ID=HP_SUPP.PARTY_ID
  AND ROWNUM                 = 1
 ) AS XX_CRM_AR_COLLECTOR_OBJS)
 INTO XX_CRM_AR_COLLECTOR_OBJS_T
 FROM DUAL;
  
SELECT CAST(MULTISET
 ( 
  SELECT X.GP_ID                   GP_ID,
         X.GP_NAME                 GP_NAME,
         X.ORIG_SYSTEM_REFERENCE   ORIG_SYSTEM_REFERENCE
  FROM
    (SELECT  GP.GP_ID,
             GP.GP_NAME,
             ACT.ORIG_SYSTEM_REFERENCE
    FROM     HZ_CUST_ACCOUNTS ACT,
             HZ_RELATIONSHIPS GREL,
             XX_CDH_GP_MASTER GP
    WHERE    ACT.ORIG_SYSTEM_REFERENCE = LPAD(P_AOPS_ACCT_ID, 8, '0') || '-00001-A0'
    AND      GP.PARTY_ID            = GREL.SUBJECT_ID
    AND      ACT.PARTY_ID           = GREL.OBJECT_ID
    AND      GREL.RELATIONSHIP_CODE = 'GRANDPARENT'
    AND      GREL.RELATIONSHIP_TYPE = 'OD_CUST_HIER'
    AND      GREL.DIRECTION_CODE    = 'P'
    AND      GREL.STATUS            = 'A'
    AND      SYSDATE BETWEEN GREL.START_DATE AND GREL.END_DATE
    UNION
    SELECT   GP.GP_ID,
             GP.GP_NAME,
             ACT.ORIG_SYSTEM_REFERENCE
    FROM     HZ_CUST_ACCOUNTS ACT,
             HZ_RELATIONSHIPS GREL,
             HZ_RELATIONSHIPS PREL,
             XX_CDH_GP_MASTER GP
    WHERE    ACT.ORIG_SYSTEM_REFERENCE = LPAD(P_AOPS_ACCT_ID, 8, '0') || '-00001-A0'
      AND    GREL.OBJECT_ID         = PREL.SUBJECT_ID
      AND    GREL.SUBJECT_ID        = GP.PARTY_ID
      AND    ACT.PARTY_ID           = PREL.OBJECT_ID
      AND    GREL.RELATIONSHIP_CODE = 'GRANDPARENT'
      AND    GREL.RELATIONSHIP_TYPE = 'OD_CUST_HIER'
      AND    GREL.DIRECTION_CODE    = 'P'
      AND    GREL.STATUS            = 'A'
      AND    PREL.RELATIONSHIP_CODE = 'PARENT_COMPANY'
      AND    PREL.RELATIONSHIP_TYPE = 'OD_CUST_HIER'
      AND    PREL.DIRECTION_CODE    = 'P'
      AND    PREL.STATUS            = 'A'
      AND    SYSDATE BETWEEN GREL.START_DATE AND GREL.END_DATE
    ) X
  WHERE ROWNUM = 1
 ) AS XX_CRM_GRAND_PARENT_OBJS)
 INTO XX_CRM_GRAND_PARENT_OBJS_T
 FROM DUAL;
  
SELECT CAST(MULTISET
 (
  SELECT HCPA.CURRENCY_CODE          CURRENCY_CODE,
         HCPA.OVERALL_CREDIT_LIMIT   OVERALL_CREDIT_LIMIT,
         HCPA.TRX_CREDIT_LIMIT       TRX_CREDIT_LIMIT
  FROM   HZ_CUST_ACCOUNTS       HCA,
         HZ_CUST_PROFILE_AMTS   HCPA
  WHERE  HCA.ORIG_SYSTEM_REFERENCE = LPAD(P_AOPS_ACCT_ID, 8, '0') || '-00001-A0'
    AND  HCPA.CUST_ACCOUNT_ID      = HCA.CUST_ACCOUNT_ID
    AND  SITE_USE_ID IS NULL
    AND  ROWNUM < 21
   ORDER BY
   CASE
     WHEN HCPA.CURRENCY_CODE = 'USD' THEN 
       0
     ELSE
       1
   END ) AS XX_CRM_CREDIT_LIMTS_OBJS)
 INTO XX_CRM_CREDIT_LIMTS_OBJS_T
 FROM DUAL;

SELECT CAST(MULTISET
 (
  SELECT  SUM(
    CASE
      WHEN FLOOR(SYSDATE-DUE_DATE) BETWEEN -9999999 AND 0
      THEN AMOUNT_DUE_REMAINING
      ELSE 0
    END) CURRENT_BAL,
    SUM(
    CASE
      WHEN FLOOR(SYSDATE-DUE_DATE) BETWEEN 1 AND 30
      THEN AMOUNT_DUE_REMAINING
      ELSE 0
    END) DAYS_1_30,
    SUM(
    CASE
      WHEN FLOOR(SYSDATE-DUE_DATE) BETWEEN 31 AND 60
      THEN AMOUNT_DUE_REMAINING
      ELSE 0
    END) DAYS_31_60,
    SUM(
    CASE
      WHEN FLOOR(SYSDATE-DUE_DATE) BETWEEN 61 AND 90
      THEN AMOUNT_DUE_REMAINING
      ELSE 0
    END) DAYS_61_90,
    SUM(
    CASE
      WHEN FLOOR(SYSDATE-DUE_DATE) BETWEEN 91 AND 180
      THEN AMOUNT_DUE_REMAINING
      ELSE 0
    END) DAYS_91_180,
    SUM(
    CASE
      WHEN FLOOR(SYSDATE-DUE_DATE) BETWEEN 181 AND 365
      THEN AMOUNT_DUE_REMAINING
      ELSE 0
    END) DAYS_181_365,
    SUM(
    CASE
      WHEN FLOOR(SYSDATE-DUE_DATE) BETWEEN 366 AND 99999999
      THEN  AMOUNT_DUE_REMAINING 
      ELSE 0
    END) DAYS_366_PLUS
        FROM AR_PAYMENT_SCHEDULES_ALL ARPAYMENTSCHEDULESV,
          HZ_CUST_ACCOUNTS ACCT,
          AR_LOOKUPS AL
        WHERE  ARPAYMENTSCHEDULESV.CUSTOMER_ID           = ACCT.CUST_ACCOUNT_ID
        AND ARPAYMENTSCHEDULESV.STATUS                = 'OP'      
        AND ARPAYMENTSCHEDULESV.INVOICE_CURRENCY_CODE = 'USD'
        AND ACCT.ORIG_SYSTEM_REFERENCE = LPAD(P_AOPS_ACCT_ID, 8, '0') || '-00001-A0'
        AND AL.LOOKUP_TYPE                            ='ARI_PMT_APPROVAL_STATUS'
        AND AL.LOOKUP_CODE                            =NVL(ARPAYMENTSCHEDULESV.PAYMENT_APPROVAL,'PENDING')
      AND ARPAYMENTSCHEDULESV.CLASS IN  ('INV', 'DM', 'CB', 'DEP')) AS XX_CRM_AGING_BUCKET_OBJS)
 INTO XX_CRM_AGING_BUCKET_OBJS_T
 FROM DUAL;

SELECT CAST(MULTISET
 (
  SELECT RESP_TYPE ,
    CONTACT_POINT_ID,
    SALUTATION ,
    PARTY_ID,
    FIRST_NAME ,
    LAST_NAME ,
    JOB_TITLE ,
    CONTACT_POINT_TYPE ,
    EMAIL_ADDRESS ,
    PHONE_LN_TYPE,
    PHONE_LN_TYPE_DESC,
    PHONE_COUNTRY_CODE ,
    PHONE_AREA_CODE ,
    PHONE_NUMBER ,
    EXTENSION ,
    PRIMARY_CONTACT_POINT,
    PREFERRED_FLAG
  FROM
    (SELECT HRR.RESPONSIBILITY_TYPE RESP_TYPE ,
      HCP.CONTACT_POINT_ID CONTACT_POINT_ID,
      HP.SALUTATION SALUTATION ,
      HP.PARTY_ID,
      SUBSTRB (HP.PERSON_FIRST_NAME ,1 ,40 ) FIRST_NAME ,
      SUBSTRB (HP.PERSON_LAST_NAME ,1 ,50 ) LAST_NAME ,
      ORG_CONT.JOB_TITLE JOB_TITLE ,
      HCP.CONTACT_POINT_TYPE CONTACT_POINT_TYPE ,
      HCP.EMAIL_ADDRESS EMAIL_ADDRESS ,
      PHONE_LINE_TYPE PHONE_LN_TYPE,
      (SELECT MEANING
      FROM FND_LOOKUP_VALUES
      WHERE LOOKUP_TYPE = 'PHONE_LINE_TYPE'
      AND LANGUAGE      = SYS_CONTEXT('USERENV', 'LANG')
      AND LOOKUP_CODE   = PHONE_LINE_TYPE
      AND ROWNUM        =1
      ) PHONE_LN_TYPE_DESC,
      HCP.PHONE_COUNTRY_CODE PHONE_COUNTRY_CODE ,
      HCP.PHONE_AREA_CODE PHONE_AREA_CODE ,
      HCP.PHONE_NUMBER PHONE_NUMBER ,
      HCP.PHONE_EXTENSION EXTENSION ,
      HCP.PRIMARY_FLAG PRIMARY_CONTACT_POINT,
      HCP.PRIMARY_BY_PURPOSE PREFERRED_FLAG
    FROM HZ_CUST_ACCT_SITES_ALL HCAS ,
      HZ_CUST_SITE_USES_ALL HCSUA ,
      HZ_PARTIES HP ,
      HZ_PARTY_SITES HPS ,
      HZ_CUST_ACCOUNT_ROLES HCAR ,
      HZ_RELATIONSHIPS HR ,
      HZ_ORG_CONTACTS ORG_CONT ,
      HZ_ROLE_RESPONSIBILITY HRR ,
      HZ_CONTACT_POINTS HCP ,
      HZ_CUST_ACCOUNTS ACCT
    WHERE ACCT.CUST_ACCOUNT_ID      = HCAS.CUST_ACCOUNT_ID
    AND HCAS.CUST_ACCT_SITE_ID      = HCSUA.CUST_ACCT_SITE_ID
    AND HCAS.PARTY_SITE_ID          = HPS.PARTY_SITE_ID
    AND HPS.IDENTIFYING_ADDRESS_FLAG='Y'
    AND HCSUA.SITE_USE_CODE         = 'BILL_TO'
    AND HP.PARTY_ID                 = HR.SUBJECT_ID
    AND HCAR.PARTY_ID               = HR.PARTY_ID
    AND HCAR.CUST_ACCT_SITE_ID      = HCSUA.CUST_ACCT_SITE_ID
    AND HRR.CUST_ACCOUNT_ROLE_ID    = HCAR.CUST_ACCOUNT_ROLE_ID
    AND HR.SUBJECT_TYPE             = 'PERSON'
    AND HR.RELATIONSHIP_ID          = ORG_CONT.PARTY_RELATIONSHIP_ID
    AND HCAR.STATUS                 = 'A'
    AND HCAR.PARTY_ID               = HCP.OWNER_TABLE_ID
    AND HCP.STATUS                  = 'A'
    AND HRR.RESPONSIBILITY_TYPE     = 'BILLING'
    AND CONTACT_POINT_TYPE         IN ('PHONE', 'EMAIL')
    AND ACCT.ORIG_SYSTEM_REFERENCE  = LPAD(P_AOPS_ACCT_ID, 8, '0') || '-00001-A0'
    AND ROWNUM <16
    UNION
    SELECT HRR.RESPONSIBILITY_TYPE RESP_TYPE ,
      HCP.CONTACT_POINT_ID CONTACT_POINT_ID,
      HP.SALUTATION SALUTATION ,
      HP.PARTY_ID,
      SUBSTRB (HP.PERSON_FIRST_NAME ,1 ,40 ) FIRST_NAME ,
      SUBSTRB (HP.PERSON_LAST_NAME ,1 ,50 ) LAST_NAME ,
      ORG_CONT.JOB_TITLE JOB_TITLE ,
      HCP.CONTACT_POINT_TYPE CONTACT_POINT_TYPE ,
      HCP.EMAIL_ADDRESS EMAIL_ADDRESS ,
      PHONE_LINE_TYPE PHONE_LINE_TYPE,
      (SELECT MEANING
      FROM FND_LOOKUP_VALUES
      WHERE LOOKUP_TYPE = 'PHONE_LINE_TYPE'
      AND LANGUAGE      = SYS_CONTEXT('USERENV', 'LANG')
      AND LOOKUP_CODE   = PHONE_LINE_TYPE
      AND ROWNUM        =1
      ) PHONE_LN_TYPE_DESC,
      HCP.PHONE_COUNTRY_CODE PHONE_COUNTRY_CODE ,
      HCP.PHONE_AREA_CODE PHONE_AREA_CODE ,
      HCP.PHONE_NUMBER PHONE_NUMBER ,
      HCP.PHONE_EXTENSION EXTENSION ,
      HCP.PRIMARY_FLAG PRIMARY_CONTACT_POINT,
      HCP.PRIMARY_BY_PURPOSE PREFERRED_FLAG
    FROM HZ_CUST_ACCT_SITES_ALL HCAS ,
      HZ_CUST_SITE_USES_ALL HCSUA ,
      HZ_PARTIES HP ,
      HZ_PARTY_SITES HPS ,
      HZ_CUST_ACCOUNT_ROLES HCAR ,
      HZ_RELATIONSHIPS HR ,
      HZ_ORG_CONTACTS ORG_CONT ,
      HZ_ROLE_RESPONSIBILITY HRR ,
      HZ_CONTACT_POINTS HCP ,
      HZ_CUST_ACCOUNTS ACCT
    WHERE ACCT.CUST_ACCOUNT_ID      = HCAS.CUST_ACCOUNT_ID
    AND HCAS.CUST_ACCT_SITE_ID      = HCSUA.CUST_ACCT_SITE_ID
    AND HCAS.PARTY_SITE_ID          = HPS.PARTY_SITE_ID
    AND HPS.IDENTIFYING_ADDRESS_FLAG='Y'
    AND HCSUA.SITE_USE_CODE         = 'BILL_TO'
    AND HP.PARTY_ID                 = HR.SUBJECT_ID
    AND HCAR.PARTY_ID               = HR.PARTY_ID
    AND HCAR.CUST_ACCT_SITE_ID      = HCSUA.CUST_ACCT_SITE_ID
    AND HRR.CUST_ACCOUNT_ROLE_ID    = HCAR.CUST_ACCOUNT_ROLE_ID
    AND HR.SUBJECT_TYPE             = 'PERSON'
    AND HR.RELATIONSHIP_ID          = ORG_CONT.PARTY_RELATIONSHIP_ID
    AND HCAR.STATUS                 = 'A'
    AND HCAR.PARTY_ID               = HCP.OWNER_TABLE_ID
    AND HCP.STATUS                  = 'A'
    AND HRR.RESPONSIBILITY_TYPE     = 'DUN'
    AND HCP.CONTACT_POINT_PURPOSE   = 'DUNNING'
    AND CONTACT_POINT_TYPE         IN ('PHONE', 'EMAIL')
    AND ACCT.ORIG_SYSTEM_REFERENCE  = LPAD(P_AOPS_ACCT_ID, 8, '0') || '-00001-A0'
    AND ROWNUM < 16
    ) ORDER BY PARTY_ID,
    PREFERRED_FLAG DESC,
    CASE
    WHEN PHONE_LN_TYPE = 'GEN' THEN
      '0'
    WHEN PHONE_LN_TYPE = 'FAX' THEN
      '1'
    WHEN PHONE_LN_TYPE = 'MOBILE' THEN
      '2'
    ELSE
      PHONE_LN_TYPE
    END) AS XX_CRM_EBILL_CONTACT_OBJS)
 INTO XX_CRM_EBILL_CONTACT_OBJS_T
 FROM DUAL;

SELECT CAST(MULTISET
 (
  SELECT PROF.ATTRIBUTE3              AB_BILLING_FLAG,
    NVL(TERM.DESCRIPTION, TERM.NAME)  PAYMENT_TERM,
    TERM.ATTRIBUTE1                   PAYTERM_FREQUENCY,
    TERM.ATTRIBUTE2                   PAYTERM_REPORTING_DAY,
    TERM.ATTRIBUTE3                   PAYTERM_PERCENTAGE,
    BILL.C_EXT_ATTR1                  BILLDOCS_DOC_TYPE,
    BILL.C_EXT_ATTR3                  BILLDOCS_DELIVERY_METH,
    BILL.C_EXT_ATTR4                  BILLDOCS_SPECIAL_HANDLING,
    BILL.C_EXT_ATTR5                  BILLDOCS_SIG_REQ,
    BILL.C_EXT_ATTR7                  BILLDOCS_DIRECT_FLAG,
    BILL.C_EXT_ATTR8                  BILLDOCS_AUTO_REPRINT,
    BILL.C_EXT_ATTR17                 BILLDOCS_COMMENTS1,
    BILL.C_EXT_ATTR18                 BILLDOCS_COMMENTS2,
    BILL.C_EXT_ATTR19                 BILLDOCS_COMMENTS3,
    BILL.C_EXT_ATTR20                 BILLDOCS_COMMENTS4,
    BILL.C_EXT_ATTR15                 BILLDOCS_MAIL_ATTENTION,
    BILL.D_EXT_ATTR1                  BILLDOCS_EFF_FROM_DATE,
    BILL.D_EXT_ATTR2                  BILLDOCS_EFF_TO_DATE,
    LOC.LOCATION_ID                   LOCATION_ID ,
    LOC.ADDRESS1                      ADDRESS1 ,
    LOC.ADDRESS2                      ADDRESS2 ,
    LOC.CITY                          CITY ,
    LOC.POSTAL_CODE                   POSTAL_CODE ,
    LOC.STATE                         STATE ,
    LOC.PROVINCE                      PROVINCE ,
    LOC.COUNTY                        COUNTY ,
    LOC.COUNTRY                       COUNTRY
  FROM HZ_CUST_ACCOUNTS ACCT
  JOIN HZ_CUST_ACCT_SITES_ALL HCAS
  ON ACCT.CUST_ACCOUNT_ID = HCAS.CUST_ACCOUNT_ID
  JOIN HZ_CUST_SITE_USES_ALL HCSUA
  ON HCAS.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID
  AND HCSUA.SITE_USE_CODE   = 'BILL_TO'
  JOIN HZ_PARTY_SITES HPS
  ON HCAS.PARTY_SITE_ID           = HPS.PARTY_SITE_ID
  AND HPS.IDENTIFYING_ADDRESS_FLAG='Y'
  JOIN HZ_LOCATIONS LOC
  ON HPS.LOCATION_ID = LOC.LOCATION_ID
  LEFT JOIN HZ_CUSTOMER_PROFILES PROF
  ON ACCT.CUST_ACCOUNT_ID = PROF.CUST_ACCOUNT_ID
  AND PROF.SITE_USE_ID   IS NULL
  LEFT JOIN RA_TERMS TERM
  ON PROF.STANDARD_TERMS = TERM.TERM_ID
  LEFT JOIN XX_CDH_CUST_ACCT_EXT_B BILL
  ON ACCT.CUST_ACCOUNT_ID         = BILL.CUST_ACCOUNT_ID
  AND BILL.C_EXT_ATTR2            = 'Y'
  AND NVL(BILL.C_EXT_ATTR13,'DB') = 'DB'
  AND TRUNC(SYSDATE) BETWEEN NVL(BILL.D_EXT_ATTR1, SYSDATE -1) AND NVL(BILL.D_EXT_ATTR2, SYSDATE +1)
  AND BILL.ATTR_GROUP_ID           = 166
  AND BILL.C_EXT_ATTR16            = 'COMPLETE'
  WHERE ACCT.ORIG_SYSTEM_REFERENCE = LPAD(P_AOPS_ACCT_ID, 8, '0') || '-00001-A0'
  AND ROWNUM = 1) AS XX_CRM_PAYMENT_TERMS_OBJS)
 INTO XX_CRM_PAYMENT_TERMS_OBJS_T
 FROM DUAL; 

 FULL_CUST_INFO_BO :=
 XX_CRM_FULL_CUST_INFO_BO.create_object(
  P_AR_COLLECTOR_TAB  => XX_CRM_AR_COLLECTOR_OBJS_T ,
  P_GRAND_PARENT_TAB  => XX_CRM_GRAND_PARENT_OBJS_T ,
  P_CREDIT_LIMTS_TAB  => XX_CRM_CREDIT_LIMTS_OBJS_T ,
  P_AGING_BUCKET_TAB  => XX_CRM_AGING_BUCKET_OBJS_T ,
  P_EBILL_CONTACT_TAB => XX_CRM_EBILL_CONTACT_OBJS_T,
  P_PAYMENT_TERMS_TAB => XX_CRM_PAYMENT_TERMS_OBJS_T 
 );

  P_CUST_OUT := FULL_CUST_INFO_BO;

END GET_CUST_INFO;

END XX_CRM_CUST360DETAILS_PKG;
/
show errors;