SET VERIFY        OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;


CREATE OR REPLACE
PACKAGE "XX_CS_QUALIFIER_PKG" AS

PROCEDURE Q_ORDER;
PROCEDURE Q_VENDOR;
PROCEDURE Q_WAREHOUSE;

END XX_CS_QUALIFIER_PKG;
/

SHOW ERRORS;
EXIT;
