SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;

PROMPT
PROMPT Creating OBJECT TYPE APPS.XX_CRM_ROLE_JOB_DEL_TBL 
PROMPT

create or replace
type XX_CRM_ROLE_JOB_DEL_TBL is table of XX_CRM_ROLE_JOB_DEL;
/

WHENEVER SQLERROR CONTINUE

PROMPT
PROMPT Exiting....
PROMPT

SET FEEDBACK ON

EXIT;
