SET SERVEROUTPUT ON;
/*update apps.ra_customer_trx_all
    set attribute15 = 'Y'
    where trx_number = '519994142001';*/
DELETE FROM XX_FIN_TRANSLATEDEFINITION 
WHERE TRANSLATION_NAME = 'XX_CDH_EBL_TXT_SP_DETAILS';

DELETE FROM XXFIN.XX_FIN_TRANSLATERESPONSIBILITY
WHERE TRANSLATE_ID = 63432;

DELETE FROM XX_FIN_TRANSLATEVALUES
WHERE TRANSLATE_ID = 63432;

COMMIT;
/

SHOW ERRORS;
EXIT;