 CREATE OR REPLACE FORCE VIEW   "APPS"."IEX_F_ACCOUNTS_V" ("CUSTOMER_SITE_USE_ID", "CUST_ACCOUNT_ID") AS 
  SELECT DISTINCT CUSTOMER_SITE_USE_ID,CUST_ACCOUNT_ID FROM IEX_DELINQUENCIES WHERE STATUS <> 'CURRENT';
 