SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;

PROMPT
PROMPT Creating OBJECT TYPE APPS.XX_CRM_ROLE
PROMPT

create or replace
TYPE      APPS.XX_CRM_ROLE AS OBJECT(
      ROLE_ID             NUMBER(15,0),
      ROLE_CODE           VARCHAR2(30),
      ROLE_TYPE_CODE      VARCHAR2(240),
      ROLE_NAME           VARCHAR2(60),
      ROLE_DESC           VARCHAR2(120),
      ACTIVE_FLAG         VARCHAR2(1),
      SEEDED_FLAG         VARCHAR2(1),
      MEMBER_FLAG         VARCHAR2(1),
      ADMIN_FLAG          VARCHAR2(1),
      LEAD_FLAG           VARCHAR2(1),
      MANAGER_FLAG        VARCHAR2(1),
      ATTRIBUTE1          VARCHAR2(150),
      ATTRIBUTE2          VARCHAR2(150),
      ATTRIBUTE3          VARCHAR2(150),
      ATTRIBUTE4          VARCHAR2(150),
      ATTRIBUTE5          VARCHAR2(150),
      ATTRIBUTE6          VARCHAR2(150),
      ATTRIBUTE7          VARCHAR2(150),
      ATTRIBUTE8          VARCHAR2(150),
      ATTRIBUTE9          VARCHAR2(150),
      ATTRIBUTE10         VARCHAR2(150),
      ATTRIBUTE11         VARCHAR2(150),
      ATTRIBUTE12         VARCHAR2(150),
      ATTRIBUTE13         VARCHAR2(150),
      ATTRIBUTE14         VARCHAR2(150),
      ATTRIBUTE15         VARCHAR2(150),
      ATTRIBUTE_CATEGORY  VARCHAR2(30),
      OBJECT_VERSION_NUMBER NUMBER(15,0)
);
/

WHENEVER SQLERROR CONTINUE

PROMPT
PROMPT Exiting....
PROMPT

SET FEEDBACK ON

EXIT;
