CREATE OR REPLACE
PACKAGE BODY XX_CDH_END_RELSHIPS                                                                                                                                                                                                                                                                                                                                                                                
-- +=========================================================================================+                                                                                                                                                                                                                                                                                                                  
-- |                  Office Depot - Project Simplify                                        |                                                                                                                                                                                                                                                                                                                  
-- +=========================================================================================+                                                                                                                                                                                                                                                                                                                  
-- | Name        : XX_CDH_END_RELSHIPS                                                       |                                                                                                                                                                                                                                                                                                                  
-- | Description : Package to End Date OD_CUST_HIER Relationships                            |                                                                                                                                                                                                                                                                                                                  
-- |                                                                                         |                                                                                                                                                                                                                                                                                                                  
-- |                                                                                         |                                                                                                                                                                                                                                                                                                                  
-- |Change Record:                                                                           |                                                                                                                                                                                                                                                                                                                  
-- |===============                                                                          |                                                                                                                                                                                                                                                                                                                  
-- |Version     Date           Author               Remarks                                  |                                                                                                                                                                                                                                                                                                                  
-- |=======    ==========      ================     =========================================|                                                                                                                                                                                                                                                                                                                  
-- |1.0        07-Jul-2009     Indra Varada        Initial version                           |   
-- |2.0        24-Mar-2016     Havish Kasina       Removed the schema references as per R12.2|
-- |                                               Changes                                   |                                                                                                                                                                                                                                                                                                                 
-- +=========================================================================================+                                                                                                                                                                                                                                                                                                                  
AS                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                
  PROCEDURE end_relships                                                                                                                                                                                                                                                                                                                                                                                        
  (                                                                                                                                                                                                                                                                                                                                                                                                             
     x_errbuf       OUT     VARCHAR2                                                                                                                                                                                                                                                                                                                                                                            
    ,x_retcode      OUT     VARCHAR2                                                                                                                                                                                                                                                                                                                                                                            
    ,p_summ_id      IN      NUMBER                                                                                                                                                                                                                                                                                                                                                                              
    ,p_rel_code     IN      VARCHAR2                                                                                                                                                                                                                                                                                                                                                                            
    ,p_commit       IN      VARCHAR2                                                                                                                                                                                                                                                                                                                                                                            
  ) AS                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                
  CURSOR cust_hier_rel (p_summ_id NUMBER,p_rel_code VARCHAR2) IS                                                                                                                                                                                                                                                                                                                                                
  SELECT r.relationship_id,r.object_version_number                                                                                                                                                                                                                                                                                                                                                              
  FROM hz_relationships r,                                                                                                                                                                                                                                                                                                                                                                                 
       xxod_hz_summary s                                                                                                                                                                                                                                                                                                                                                                                   
  WHERE r.relationship_type = 'OD_CUST_HIER'                                                                                                                                                                                                                                                                                                                                                                    
  AND   r.relationship_code = p_rel_code                                                                                                                                                                                                                                                                                                                                                                        
  AND r.direction_code = 'P'                                                                                                                                                                                                                                                                                                                                                                                    
  AND r.subject_id = s.party_id                                                                                                                                                                                                                                                                                                                                                                                 
  AND s.summary_id = p_summ_id                                                                                                                                                                                                                                                                                                                                                                                  
  AND r.status = 'A'                                                                                                                                                                                                                                                                                                                                                                                            
  AND r.end_date > SYSDATE;                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                
  l_succ_count         		   NUMBER := 0;                                                                                                                                                                                                                                                                                                                                                                        
  l_error_count        		   NUMBER := 0;                                                                                                                                                                                                                                                                                                                                                                        
  ln_party_object_version_number   NUMBER;                                                                                                                                                                                                                                                                                                                                                                      
  x_return_status                  VARCHAR2(2000);                                                                                                                                                                                                                                                                                                                                                              
  x_msg_count                      NUMBER;                                                                                                                                                                                                                                                                                                                                                                      
  x_msg_data                       VARCHAR2(2000);                                                                                                                                                                                                                                                                                                                                                              
  ln_msg_text                      VARCHAR2(32000);                                                                                                                                                                                                                                                                                                                                                             
  l_rel_rec                        hz_relationship_v2pub.relationship_rec_type;                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                
  BEGIN                                                                                                                                                                                                                                                                                                                                                                                                         
    FOR i_rel IN cust_hier_rel (p_summ_id, p_rel_code) LOOP                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                
    l_rel_rec.relationship_id   :=  i_rel.relationship_id;                                                                                                                                                                                                                                                                                                                                                      
    l_rel_rec.end_date          :=  SYSDATE;                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                
    hz_relationship_v2pub.update_relationship (                                                                                                                                                                                                                                                                                                                                                                 
    p_init_msg_list                => FND_API.G_TRUE,                                                                                                                                                                                                                                                                                                                                                           
    p_relationship_rec             => l_rel_rec,                                                                                                                                                                                                                                                                                                                                                                
    p_object_version_number        => i_rel.object_version_number,                                                                                                                                                                                                                                                                                                                                              
    p_party_object_version_number  => ln_party_object_version_number,                                                                                                                                                                                                                                                                                                                                           
    x_return_status                => x_return_status,                                                                                                                                                                                                                                                                                                                                                          
    x_msg_count                    => x_msg_count,                                                                                                                                                                                                                                                                                                                                                              
    x_msg_data                     => x_msg_data                                                                                                                                                                                                                                                                                                                                                                
    );                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
    IF x_return_status = FND_API.G_RET_STS_SUCCESS THEN                                                                                                                                                                                                                                                                                                                                                         
       l_succ_count    :=  l_succ_count  +  1;                                                                                                                                                                                                                                                                                                                                                                  
    ELSE                                                                                                                                                                                                                                                                                                                                                                                                        
           l_error_count  := l_error_count + 1;                                                                                                                                                                                                                                                                                                                                                                 
           ln_msg_text    := NULL;                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                
           IF x_msg_count > 0 THEN                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                
              fnd_file.put_line (fnd_file.log,'Error While Processing Relationship ID - ' || i_rel.relationship_id);                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                
              FOR counter IN 1..x_msg_count                                                                                                                                                                                                                                                                                                                                                                     
              LOOP                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                
                ln_msg_text := ln_msg_text||' '||FND_MSG_PUB.Get(counter, FND_API.G_FALSE);                                                                                                                                                                                                                                                                                                                     
                fnd_file.put_line (fnd_file.log,'Error - '|| FND_MSG_PUB.Get(counter, FND_API.G_FALSE));                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                
              END LOOP;                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                
           FND_MSG_PUB.Delete_Msg;                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                
           END IF;                                                                                                                                                                                                                                                                                                                                                                                              
     END IF;                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                
     IF p_commit = 'Y' AND MOD(l_succ_count,200) = 0 THEN                                                                                                                                                                                                                                                                                                                                                       
        COMMIT;                                                                                                                                                                                                                                                                                                                                                                                                 
     END IF;                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                
 END LOOP;                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                
     IF p_commit = 'Y' THEN                                                                                                                                                                                                                                                                                                                                                                                     
        COMMIT;                                                                                                                                                                                                                                                                                                                                                                                                 
     ELSE                                                                                                                                                                                                                                                                                                                                                                                                       
        ROLLBACK;                                                                                                                                                                                                                                                                                                                                                                                               
     END IF;                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                
  fnd_file.put_line(fnd_file.output,'Relationship Update Successful:' || l_succ_count);                                                                                                                                                                                                                                                                                                                         
  fnd_file.put_line(fnd_file.output,'Relationship Update Errors:' || l_error_count);                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                
EXCEPTION WHEN OTHERS THEN                                                                                                                                                                                                                                                                                                                                                                                      
  fnd_file.put_line (fnd_file.log,'Unexpected Error In Method: ' || SQLERRM);                                                                                                                                                                                                                                                                                                                                   
END end_relships;                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                
END XX_CDH_END_RELSHIPS;   
/

SHOW ERRORS;                                                                                                                                                                                                                                                                                                                                                                                     

