SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;

PROMPT
PROMPT Creating OBJECT TYPE APPS.XX_CRM_ROLE_RELATE_MOD_TBL 
PROMPT

create or replace
TYPE       APPS.XX_CRM_ROLE_RELATE_MOD_TBL IS TABLE OF XX_CRM_ROLE_RELATE_MOD;
/

WHENEVER SQLERROR CONTINUE

PROMPT
PROMPT Exiting....
PROMPT

SET FEEDBACK ON

EXIT;
