SET VERIFY OFF;
SET SHOW OFF;
SET TAB OFF;
SET ECHO OFF;
SET FEEDBACK OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;



PROMPT
PROMPT Providing grant on custom table XX_CS_CLOSE_LOOP_DATE_PKG
PROMPT

GRANT ALL ON  XX_CS_CLOSE_LOOP_DATE_PKG TO APPS;       

SHOW ERROR
