CREATE OR REPLACE SYNONYM APPS.XX_GL_INTERFACE_NA FOR GL.XX_GL_INTERFACE_NA;
ALTER TABLE GL.XX_GL_INTERFACE_NA_TEMP ADD (LEDGER_ID NUMBER(15));
UPDATE GL.XX_GL_INTERFACE_NA_TEMP 
SET LEDGER_ID = SET_OF_BOOKS_ID;
COMMIT;
INSERT INTO APPS.XX_GL_INTERFACE_NA SELECT * FROM GL.XX_GL_INTERFACE_NA_TEMP;
COMMIT;
/