ALTER TABLE GL.XX_GL_INTERFACE_NA RENAME TO XX_GL_INTERFACE_NA_TEMP;
ALTER TABLE XXFIN.XX_GL_INTERFACE_NA_STG ADD (LEDGER_ID NUMBER(15));
ALTER TABLE XXFIN.XX_GL_INTERFACE_NA_ERROR ADD (LEDGER_ID NUMBER(15));
UPDATE XX_GL_INTERFACE_NA_STG SET LEDGER_ID=SET_OF_BOOKS_ID;
COMMIT;
UPDATE XX_GL_INTERFACE_NA_ERROR SET LEDGER_ID=SET_OF_BOOKS_ID;
COMMIT;
/