GRANT EXECUTE ON APPS.XX_JTF_RS_NAMED_ACC_TERR_PUB TO PUBLIC
/

GRANT ALL ON XXCRM.XX_TM_NAM_TERR_DEFN TO APPS
/

GRANT ALL ON XXCRM.XX_TM_NAM_TERR_DEFN TO APPS_RW
/

GRANT ALL ON XXCRM.XX_TM_NAM_TERR_RSC_DTLS TO APPS
/

GRANT ALL ON XXCRM.XX_TM_NAM_TERR_RSC_DTLS TO APPS_RW
/

GRANT ALL ON XXCRM.XX_TM_NAM_TERR_ENTITY_DTLS TO APPS
/

GRANT ALL ON XXCRM.XX_TM_NAM_TERR_ENTITY_DTLS TO APPS_RW
/

