 CREATE TABLE XX_OD_XNET_REPORT_DATA(PARTY_ID number,
 party_site_id  number,
 PARENT_ID number,
 TOP_PARENT_FLAG varchar2(10),
 PARTY_NUMBER varchar2(100),
 PARTY_NAME varchar2(300),
 SHORT_CUST_NAME_1 varchar2(300),   
 CUST_NO_1 varchar2(300),
 ACCOUNT_NUMBER varchar2(300),
 CUST_ACCT_ID number,
 CUST_SORT_1 number,    
 TOTAL_CUST_AMT_1 number,
 CREDIT_LIMIT_1 number,
 COLLECTOR_NAME_P varchar2(300),
 collector_name varchar2(300),
 COLLECTOR_EMAIL varchar2(300),
 PARENT_BALANCE NUMBER
 );