SET SHOW         OFF
SET VERIFY       OFF
SET ECHO         OFF
SET TAB          OFF
SET FEEDBACK     ON

PROMPT Insert data in transalate table for PO/Receipts Conversion

PROMPT Program exits IF the creation IS NOT SUCCESSFUL

WHENEVER SQLERROR CONTINUE

Insert into APPS.XX_COM_CONVERSIONS_CONV
   (CONVERSION_ID, CONVERSION_CODE, BATCH_SIZE, MAX_THREADS, EXTRACT_OR_LOAD, SYSTEM_CODE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
 Values
   (XXCOMN.XX_COM_CONVERSIONS_CONV_S1.NEXTVAL, 'CXXXX_PurchaseOrders', 100, 10, 'L', 'XX_PO', -1, sysdate, -1, sysdate);

Insert into APPS.XX_COM_CONVERSIONS_CONV
   (CONVERSION_ID, CONVERSION_CODE, BATCH_SIZE, MAX_THREADS, EXTRACT_OR_LOAD, SYSTEM_CODE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
 Values
   (XXCOMN.XX_COM_CONVERSIONS_CONV_S1.NEXTVAL, 'CXXXX_Receipts', 0, 4, 'L', 'XX_PO', -1, sysdate, -1, sysdate);
COMMIT;

