DECLARE

v_translate_id NUMBER;

BEGIN

  BEGIN
    SELECT translate_id
      INTO v_translate_id
      FROM XX_FIN_TRANSLATEDEFINITION
     WHERE translation_name='XXFA_PWC_DEPRN'
       AND enabled_flag='Y';
  EXCEPTION
    WHEN others THEN
      v_translate_id:=NULL;
      dbms_output.put_line('Translation XXFA_PWC_DEPRN not set up');
  END;

  BEGIN
    delete
      FROM xx_fin_translatevalues
     WHERE translate_id = v_translate_id
       AND enabled_flag='Y';
  EXCEPTION
    WHEN others THEN
      v_translate_id:=NULL;
      dbms_output.put_line('Delete for XXFA_PWC_DEPRN not executed');
  END;

  IF v_translate_id IS NOT NULL THEN

     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '150%','1','No Bonus - GDS 150 1 Year HY','STL','12','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '150%','5','No Bonus - GDS 150 5 Year HY','150DB','60','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '150%','15','150 DDB HY 15 YEAR','150DB','180','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '150%','15','No Bonus - GDS 150 15 Year HY','AMT HY','180','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '150%','15','Yes Bonus - GDS 150 15 Year HY','AMT200HY-30B','180','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '150%','20','150 DDB HY 20 YEAR','150DB','240','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '150%','40','No Bonus - GDS 150 40 Year HY','MACRS STL HY','480','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','1','No Bonus - GDS 200 1 Year HY','STL','12','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','1','Yes Bonus - GDS 200 1 Year HY','STL','12','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','3','No Bonus - GDS 200 3 Year HY','200DB','36','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','3','Yes Bonus - GDS 200 3 Year HY','MACRS STL50B','36','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','5','200 DDB HY 5 YEAR','200DB','60','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','5','No Bonus - GDS 200 5 Year HY','MACRS HY','60','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','5','Yes Bonus - GDS 200 5 Year HY','MACRS 50B HY','60','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','7','200 DDB HY 7 YEAR','200DB','84','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','7','No Bonus - GDS 200 7 Year HY','200DB','84','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','7','Yes Bonus - GDS 200 7 Year HY','MACRS 50B HY','84','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','15','No Bonus - GDS 200 15 Year HY','MACRS HY','180','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','15','Yes Bonus - GDS 200 15 Year HY','MACRS 50B HY','180','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','30','No Bonus - GDS 200 30 Year HY','200DB','360','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','30','Yes Bonus - GDS 200 30 Year HY','200DB','360','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','39','No Bonus - GDS 200 39 Year HY','MACRS STL HY','468','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','39','Yes Bonus - GDS 200 39 Year HY','MACRS STL50B','468','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','1','Straight-Line FM 1 YEAR','STL','12','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','1','Straight-Line HY 1 YEAR','STL','12','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','3','Straight-Line FM 3 YEAR','MACRS STL HY','36','FULL MONTH',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','3','No Bonus - GDS SL 3 Year HY','MACRS STL HY','36','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','3','Yes Bonus - GDS SL 3 Year HY','STL 50B','36','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','5','No Bonus - GDS SL 5 Year HY','MACRS STL HY','60','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','5','Yes Bonus - GDS SL 5 Year HY','MACRS STL HY','60','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','5','No Bonus - GDS SL 5 Year MM','MACRS STL50B','60','MID MONTH',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','7','No Bonus - GDS SL 7 Year HY','MACRS STL HY','84','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','7','Yes Bonus - GDS SL 7 Year HY','MACRS STL HY','84','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','7','No Bonus - GDS SL 7 Year MM','MACRS STL MQ','84','MID MONTH',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','15','No Bonus - GDS SL 15 Year HY','MACRS STL HY','180','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','15','Straight-Line HY 15 YEAR','MACRS STL HY','180','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','15','Yes Bonus - GDS SL 15 Year HY','STL 100B HY','180','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','15','No Bonus - GDS SL 15 Year MM','MACRS STL50B','180','MID MONTH',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','28','No Bonus - GDS SL 28 Year MM','MACRS STL HY','336','MID MONTH',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','30','No Bonus - GDS SL 30 Year MM','STL','360','MID MONTH',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','31.5','No Bonus - GDS SL 31.5 Year MM','MACRS STL MM','378','MID MONTH',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','31.5','Yes Bonus - GDS SL 31.5 Year MM','MACRS STL MM','378','MID MONTH',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','35','No Bonus - GDS SL 35 Year MM','ACRS RSTLMM','420','MID MONTH',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','39','No Bonus - GDS SL 39 Year HY','AMT HY','468','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','39','Yes Bonus - GDS SL 39 Year HY','AMT HY','468','HALF YEAR',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','39','No Bonus - GDS SL 39 Year MM','AMT MQ','468','MID MONTH',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','39','Straight-Line MM 39 YEAR','STL','468','MID MONTH',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','40','No Bonus - GDS SL 40 Year MM','AMT MQ','480','MID MONTH',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','50','No Bonus - GDS SL 50 Year MM','AMT HY','600','MID MONTH',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','60','No Bonus - GDS SL 60 Year MM','200DB','720','MID MONTH',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,source_value3,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','999','Non Depreciable','STL','1','MID MONTH',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);

  END IF;  
  COMMIT;
EXCEPTION
  WHEN others THEN
    dbms_output.put_line('When others :'||SQLERRM);
END;
/
