create or replace
PACKAGE  XX_TWE_ISO_USETAX_PKG AS

  PROCEDURE XX_TWE_ISO_USETAX_PRC(P_SOB_ID IN NUMBER,
  P_PERIOD_NUM_FROM IN NUMBER, 
  P_PERIOD_NUM_TO IN NUMBER);

END  XX_TWE_ISO_USETAX_PKG;
/