SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;

CREATE OR REPLACE VIEW XXBI_OPP_TOT_AMT_SMRY_DIM_V
AS
SELECT  DISTINCT TOTAL_AMOUNT_ID  ID, TOTAL_AMOUNT_DESC VALUE
FROM XXBI_SLS_OPP_SMRY_V

----------------------------------------------------------
-- Grant to XXCRM
----------------------------------------------------------
GRANT ALL ON APPS.XXBI_OPP_TOT_AMT_SMRY_DIM_V TO XXCRM;

SHOW ERRORS;
EXIT;