SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;

CREATE OR REPLACE VIEW XXBI_OPPTY_TOTAL_AMT_DIM_V
AS
SELECT  DISTINCT TOTAL_AMOUNT  ID, TOTAL_AMOUNT VALUE
FROM XXBI_SALES_OPPTY_FCT_V

----------------------------------------------------------
-- Grant to XXCRM
----------------------------------------------------------
GRANT ALL ON APPS.XXBI_OPPTY_TOTAL_AMT_DIM_V TO XXCRM;

SHOW ERRORS;
EXIT;