SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;

  CREATE OR REPLACE FORCE VIEW APPS.XXBI_FISCAL_PERIOD_DIM_V (ID, VALUE, FISCAL_QTR_ID) AS 
  select distinct  fiscal_period_id as id, fiscal_period_descr as value,  fiscal_qtr_id from XXBI_OD_FISCAL_CALENDAR_V
/
SHOW ERRORS;
EXIT;