SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;

CREATE OR REPLACE VIEW XXBI_OD_SIC_GROUP_TYPES_DIM_V AS
SELECT DISTINCT SIC_GROUP_TYPE ID, SIC_GROUP_TYPE VALUE
FROM XXCRM.XXBI_OD_SIC_GROUP_TYPES;
/
SHOW ERRORS;
EXIT;