SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;

CREATE OR  REPLACE VIEW XXBI_CUST_CLASSIFICATION_DIM_V AS
SELECT LOOKUP_CODE AS ID, MEANING AS VALUE FROM FND_LOOKUP_VALUES WHERE 
LOOKUP_TYPE = 'XX_TM_TERR_CLASSIFICATION' AND ENABLED_FLAG = 'Y';

SHOW ERRORS;
EXIT;