SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;
  
  CREATE OR REPLACE FORCE VIEW APPS.XXBI_QTR_NUMBERS_DIM_V (ID, VALUE) AS 
  select distinct quarter_number as id, quarter_number as value from XXBI_OD_FISCAL_CALENDAR_V
/
SHOW ERRORS;
EXIT;