
SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;

insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('01','OT','Other');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('02','OT','Other');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('07','OT','Other');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('08','OT','Other');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('09','OT','Other');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('10','OT','Other');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('12','OT','Other');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('13','OT','Other');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('14','OT','Other');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('15','CO','Construction/Contractors');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('16','CO','Construction/Contractors');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('17','CO','Construction/Contractors');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('20','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('21','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('22','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('23','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('24','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('25','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('26','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('27','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('28','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('29','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('30','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('31','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('32','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('33','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('34','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('35','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('36','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('37','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('38','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('39','MN','Manufacturing/Printing');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('40','UT','Transportation/Communications/Utilities');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('41','UT','Transportation/Communications/Utilities');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('42','UT','Transportation/Communications/Utilities');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('43','UT','Transportation/Communications/Utilities');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('44','UT','Transportation/Communications/Utilities');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('45','UT','Transportation/Communications/Utilities');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('46','UT','Transportation/Communications/Utilities');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('47','UT','Transportation/Communications/Utilities');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('48','UT','Transportation/Communications/Utilities');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('49','UT','Transportation/Communications/Utilities');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('50','WT','Wholesale Trade');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('51','WT','Wholesale Trade');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('52','RT','Retail/Restaurants');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('53','RT','Retail/Restaurants');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('54','RT','Retail/Restaurants');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('55','RT','Retail/Restaurants');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('56','RT','Retail/Restaurants');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('57','RT','Retail/Restaurants');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('58','RT','Retail/Restaurants');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('59','RT','Retail/Restaurants');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('60','FN','Finance');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('61','FN','Finance');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('62','FN','Finance');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('63','IN','Insurance');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('64','IN','Insurance');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('65','RE','Real Estate');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('67','IN','Insurance');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('70','BS','Business Services');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('72','OT','Other');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('73','BS','Business Services');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('75','OT','Other');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('76','OT','Other');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('78','BS','Business Services');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('79','BS','Business Services');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('80','MH','Medical/Health Services');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('81','LG','Legal');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('82','ES','Education/Schools');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('83','SS','Social Services');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('84','OR','Membership/Organizations');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('86','OR','Membership/Organizations');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('87','AC','Accounting');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('87','EA','Engineering/Architecture/Consulting');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('89','OT','Other');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('91','GV','Government');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('92','GV','Government');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('93','GV','Government');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('94','GV','Government');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('95','GV','Government');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('96','GV','Government');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('97','GV','Government');
insert into xxcrm.XXBI_OD_SIC_GROUP_TYPES values('99','OT','Other');
commit;

SHOW ERRORS;
EXIT;