SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;

CREATE OR REPLACE VIEW  XXBI_CUSTOMER_LOYALTY_DIM_V AS
SELECT LOOKUP_CODE AS ID, MEANING AS VALUE FROM APPS.FND_LOOKUP_VALUES 
WHERE LOOKUP_TYPE = 'Customer Loyalty' AND ENABLED_FLAG  = 'Y'
UNION ALL
SELECT 'XX' ID, 'Not Available' FROM DUAL
ORDER BY VALUE;

SHOW ERRORS;
EXIT;