SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;

CREATE OR REPLACE VIEW XXBI_MEMBER_ROLES_DIM_V AS
SELECT DISTINCT ROLE_ID id, ROLE_NAME value FROM APPS.JTF_RS_ROLES_VL 
WHERE ROLE_TYPE_CODE IN ('SALES', 'TELESALES')
AND MEMBER_FLAG = 'Y' AND ACTIVE_FLAG = 'Y';

SHOW ERRORS;
EXIT;