SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;
  
  CREATE OR REPLACE FORCE VIEW APPS.XXBI_FISCAL_YEAR_DIM_V (ID, VALUE) AS 
  select distinct fiscal_year_id as id, fiscal_year_id as value from XXBI_OD_FISCAL_CALENDAR_V
/
SHOW ERRORS;
EXIT;