SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;

  CREATE OR REPLACE FORCE VIEW APPS.XXBI_FISCAL_DATE_DIM_V (ID, VALUE, FISCAL_WEEK_ID) AS 
  select julian_id as id, trunc(accounting_date) as value, fiscal_week_id from XXBI_OD_FISCAL_CALENDAR_V
/
SHOW ERRORS;
EXIT;