SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;
  
  CREATE OR REPLACE FORCE VIEW APPS.XXBI_FISCAL_QTR_DIM_V (ID, VALUE, FISCAL_YEAR_ID) AS 
  select distinct  fiscal_qtr_id as id, fiscal_qtr_id as value, fiscal_year_id from XXBI_OD_FISCAL_CALENDAR_V
/
SHOW ERRORS;
EXIT;