SET VERIFY OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;
  
  CREATE OR REPLACE FORCE VIEW APPS.XXBI_WEEK_NUMBERS_DIM_V (ID, VALUE) AS 
  select distinct fiscal_week_number as id, fiscal_week_number  as value from XXBI_OD_FISCAL_CALENDAR_V
/
SHOW ERRORS;
EXIT;