--------------------------------------------------------
--  DDL for Object XX_CDH_HZ_EXT_ATTRIBS_BO
--------------------------------------------------------
 --DROP TYPE XX_CDH_HZ_EXT_ATTRIBS_BO;
  CREATE OR REPLACE TYPE XX_CDH_HZ_EXT_ATTRIBS_BO AS OBJECT (    
        ACTION_TYPE                    VARCHAR2(30),
        COMMON_OBJ_ID                  VARCHAR2(255),
        ORIG_SYSTEM                    VARCHAR2(30), 
        ORIG_SYSTEM_REFERENCE          VARCHAR2(240), 
        INTERFACE_ENTITY_NAME          VARCHAR2(30), 
        INTERFACE_ENTITY_REFERENCE     VARCHAR2(240), 
        ATTRIBUTE_GROUP_CODE           VARCHAR2(30), 
        CREATED_BY                     NUMBER(15), 
        CREATED_BY_MODULE              VARCHAR2(150), 
        CREATION_DATE                  DATE, 
        LAST_UPDATE_DATE               DATE, 
        LAST_UPDATE_LOGIN              NUMBER(15), 
        LAST_UPDATED_BY                NUMBER(15), 
        PROGRAM_APPLICATION_ID         NUMBER(15), 
        PROGRAM_ID                     NUMBER(15), 
        PROGRAM_UPDATE_DATE            DATE, 
        REQUEST_ID                     NUMBER(15), 
        C_EXT_ATTR1                    VARCHAR2(150), 
        C_EXT_ATTR2                    VARCHAR2(150), 
        C_EXT_ATTR3                    VARCHAR2(150), 
        C_EXT_ATTR4                    VARCHAR2(150), 
        C_EXT_ATTR5                    VARCHAR2(150), 
        C_EXT_ATTR6                    VARCHAR2(150), 
        C_EXT_ATTR7                    VARCHAR2(150), 
        C_EXT_ATTR8                    VARCHAR2(150), 
        C_EXT_ATTR9                    VARCHAR2(150), 
        C_EXT_ATTR10                   VARCHAR2(150), 
        C_EXT_ATTR11                   VARCHAR2(150), 
        C_EXT_ATTR12                   VARCHAR2(150), 
        C_EXT_ATTR13                   VARCHAR2(150), 
        C_EXT_ATTR14                   VARCHAR2(150), 
        C_EXT_ATTR15                   VARCHAR2(150), 
        C_EXT_ATTR16                   VARCHAR2(150), 
        C_EXT_ATTR17                   VARCHAR2(150), 
        C_EXT_ATTR18                   VARCHAR2(150), 
        C_EXT_ATTR19                   VARCHAR2(150), 
        C_EXT_ATTR20                   VARCHAR2(150), 
        N_EXT_ATTR1                    NUMBER(22,5), 
        N_EXT_ATTR2                    NUMBER(22,5), 
        N_EXT_ATTR3                    NUMBER(22,5), 
        N_EXT_ATTR4                    NUMBER(22,5), 
        N_EXT_ATTR5                    NUMBER(22,5), 
        N_EXT_ATTR6                    NUMBER(22,5), 
        N_EXT_ATTR7                    NUMBER(22,5), 
        N_EXT_ATTR8                    NUMBER(22,5), 
        N_EXT_ATTR9                    NUMBER(22,5), 
        N_EXT_ATTR10                   NUMBER(22,5), 
        N_EXT_ATTR11                   NUMBER(22,5), 
        N_EXT_ATTR12                   NUMBER(22,5), 
        N_EXT_ATTR13                   NUMBER(22,5), 
        N_EXT_ATTR14                   NUMBER(22,5), 
        N_EXT_ATTR15                   NUMBER(22,5), 
        N_EXT_ATTR16                   NUMBER(22,5), 
        N_EXT_ATTR17                   NUMBER(22,5), 
        N_EXT_ATTR18                   NUMBER(22,5), 
        N_EXT_ATTR19                   NUMBER(22,5), 
        N_EXT_ATTR20                   NUMBER(22,5), 
        D_EXT_ATTR1                    DATE, 
        D_EXT_ATTR2                    DATE, 
        D_EXT_ATTR3                    DATE, 
        D_EXT_ATTR4                    DATE, 
        D_EXT_ATTR5                    DATE, 
        D_EXT_ATTR6                    DATE, 
        D_EXT_ATTR7                    DATE, 
        D_EXT_ATTR8                    DATE, 
        D_EXT_ATTR9                    DATE, 
        D_EXT_ATTR10                   DATE, 
        TL_EXT_ATTR1                   VARCHAR2(1000), 
        TL_EXT_ATTR2                   VARCHAR2(1000), 
        TL_EXT_ATTR3                   VARCHAR2(1000), 
        TL_EXT_ATTR4                   VARCHAR2(1000), 
        TL_EXT_ATTR5                   VARCHAR2(1000), 
        TL_EXT_ATTR6                   VARCHAR2(1000), 
        TL_EXT_ATTR7                   VARCHAR2(1000), 
        TL_EXT_ATTR8                   VARCHAR2(1000), 
        TL_EXT_ATTR9                   VARCHAR2(1000), 
        TL_EXT_ATTR10                  VARCHAR2(1000), 
        TL_EXT_ATTR11                  VARCHAR2(1000), 
        TL_EXT_ATTR12                  VARCHAR2(1000), 
        TL_EXT_ATTR13                  VARCHAR2(1000), 
        TL_EXT_ATTR14                  VARCHAR2(1000), 
        TL_EXT_ATTR15                  VARCHAR2(1000), 
        TL_EXT_ATTR16                  VARCHAR2(1000), 
        TL_EXT_ATTR17                  VARCHAR2(1000), 
        TL_EXT_ATTR18                  VARCHAR2(1000), 
        TL_EXT_ATTR19                  VARCHAR2(1000), 
        TL_EXT_ATTR20                  VARCHAR2(1000), 
        OWNER_TABLE_NAME               VARCHAR2(50), 
        OWNER_TABLE_ID                 NUMBER,
        STATIC FUNCTION create_object(     
          P_ORIG_SYSTEM                  IN  VARCHAR2    := NULL,
          P_ORIG_SYSTEM_REFERENCE        IN  VARCHAR2    := NULL,
          P_INTERFACE_ENTITY_NAME        IN  VARCHAR2    := NULL,
          P_INTERFACE_ENTITY_REFERENCE   IN  VARCHAR2    := NULL,
          P_ATTRIBUTE_GROUP_CODE         IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR1                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR2                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR3                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR4                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR5                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR6                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR7                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR8                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR9                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR10                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR11                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR12                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR13                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR14                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR15                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR16                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR17                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR18                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR19                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR20                 IN  VARCHAR2    := NULL,
          P_N_EXT_ATTR1                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR2                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR3                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR4                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR5                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR6                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR7                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR8                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR9                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR10                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR11                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR12                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR13                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR14                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR15                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR16                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR17                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR18                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR19                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR20                 IN  NUMBER      := NULL,
          P_D_EXT_ATTR1                  IN  DATE        := NULL,
          P_D_EXT_ATTR2                  IN  DATE        := NULL,
          P_D_EXT_ATTR3                  IN  DATE        := NULL,
          P_D_EXT_ATTR4                  IN  DATE        := NULL,
          P_D_EXT_ATTR5                  IN  DATE        := NULL,
          P_D_EXT_ATTR6                  IN  DATE        := NULL,
          P_D_EXT_ATTR7                  IN  DATE        := NULL,
          P_D_EXT_ATTR8                  IN  DATE        := NULL,
          P_D_EXT_ATTR9                  IN  DATE        := NULL,
          P_D_EXT_ATTR10                 IN  DATE        := NULL,
          P_TL_EXT_ATTR1                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR2                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR3                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR4                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR5                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR6                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR7                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR8                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR9                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR10                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR11                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR12                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR13                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR14                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR15                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR16                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR17                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR18                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR19                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR20                IN  VARCHAR2    := NULL
        ) RETURN XX_CDH_HZ_EXT_ATTRIBS_BO        
   );
   /
   SHOW ERRORS;
   CREATE OR REPLACE TYPE BODY XX_CDH_HZ_EXT_ATTRIBS_BO AS
     STATIC FUNCTION create_object(
          P_ORIG_SYSTEM                  IN  VARCHAR2    := NULL,
          P_ORIG_SYSTEM_REFERENCE        IN  VARCHAR2    := NULL,
          P_INTERFACE_ENTITY_NAME        IN  VARCHAR2    := NULL,
          P_INTERFACE_ENTITY_REFERENCE   IN  VARCHAR2    := NULL,
          P_ATTRIBUTE_GROUP_CODE         IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR1                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR2                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR3                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR4                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR5                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR6                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR7                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR8                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR9                  IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR10                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR11                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR12                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR13                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR14                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR15                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR16                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR17                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR18                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR19                 IN  VARCHAR2    := NULL,
          P_C_EXT_ATTR20                 IN  VARCHAR2    := NULL,
          P_N_EXT_ATTR1                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR2                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR3                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR4                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR5                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR6                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR7                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR8                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR9                  IN  NUMBER      := NULL,
          P_N_EXT_ATTR10                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR11                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR12                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR13                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR14                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR15                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR16                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR17                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR18                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR19                 IN  NUMBER      := NULL,
          P_N_EXT_ATTR20                 IN  NUMBER      := NULL,
          P_D_EXT_ATTR1                  IN  DATE        := NULL,
          P_D_EXT_ATTR2                  IN  DATE        := NULL,
          P_D_EXT_ATTR3                  IN  DATE        := NULL,
          P_D_EXT_ATTR4                  IN  DATE        := NULL,
          P_D_EXT_ATTR5                  IN  DATE        := NULL,
          P_D_EXT_ATTR6                  IN  DATE        := NULL,
          P_D_EXT_ATTR7                  IN  DATE        := NULL,
          P_D_EXT_ATTR8                  IN  DATE        := NULL,
          P_D_EXT_ATTR9                  IN  DATE        := NULL,
          P_D_EXT_ATTR10                 IN  DATE        := NULL,
          P_TL_EXT_ATTR1                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR2                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR3                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR4                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR5                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR6                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR7                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR8                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR9                 IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR10                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR11                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR12                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR13                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR14                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR15                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR16                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR17                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR18                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR19                IN  VARCHAR2    := NULL,
          P_TL_EXT_ATTR20                IN  VARCHAR2    := NULL
     ) RETURN XX_CDH_HZ_EXT_ATTRIBS_BO 
     AS
     BEGIN
       RETURN XX_CDH_HZ_EXT_ATTRIBS_BO(
         ACTION_TYPE                    => NULL                         ,      
         COMMON_OBJ_ID                  => NULL                         , 
         ORIG_SYSTEM                    => P_ORIG_SYSTEM                , 
         ORIG_SYSTEM_REFERENCE          => P_ORIG_SYSTEM_REFERENCE      , 
         INTERFACE_ENTITY_NAME          => P_INTERFACE_ENTITY_NAME      , 
         INTERFACE_ENTITY_REFERENCE     => P_INTERFACE_ENTITY_REFERENCE , 
         ATTRIBUTE_GROUP_CODE           => P_ATTRIBUTE_GROUP_CODE       , 
         CREATED_BY                     => NULL                         , 
         CREATED_BY_MODULE              => NULL                         , 
         CREATION_DATE                  => NULL                         , 
         LAST_UPDATE_DATE               => NULL                         , 
         LAST_UPDATE_LOGIN              => NULL                         , 
         LAST_UPDATED_BY                => NULL                         , 
         PROGRAM_APPLICATION_ID         => NULL                         , 
         PROGRAM_ID                     => NULL                         , 
         PROGRAM_UPDATE_DATE            => NULL                         , 
         REQUEST_ID                     => NULL                         , 
         C_EXT_ATTR1                    => P_C_EXT_ATTR1                , 
         C_EXT_ATTR2                    => P_C_EXT_ATTR2                , 
         C_EXT_ATTR3                    => P_C_EXT_ATTR3                , 
         C_EXT_ATTR4                    => P_C_EXT_ATTR4                , 
         C_EXT_ATTR5                    => P_C_EXT_ATTR5                , 
         C_EXT_ATTR6                    => P_C_EXT_ATTR6                , 
         C_EXT_ATTR7                    => P_C_EXT_ATTR7                , 
         C_EXT_ATTR8                    => P_C_EXT_ATTR8                , 
         C_EXT_ATTR9                    => P_C_EXT_ATTR9                , 
         C_EXT_ATTR10                   => P_C_EXT_ATTR10               , 
         C_EXT_ATTR11                   => P_C_EXT_ATTR11               , 
         C_EXT_ATTR12                   => P_C_EXT_ATTR12               , 
         C_EXT_ATTR13                   => P_C_EXT_ATTR13               , 
         C_EXT_ATTR14                   => P_C_EXT_ATTR14               , 
         C_EXT_ATTR15                   => P_C_EXT_ATTR15               , 
         C_EXT_ATTR16                   => P_C_EXT_ATTR16               , 
         C_EXT_ATTR17                   => P_C_EXT_ATTR17               , 
         C_EXT_ATTR18                   => P_C_EXT_ATTR18               , 
         C_EXT_ATTR19                   => P_C_EXT_ATTR19               , 
         C_EXT_ATTR20                   => P_C_EXT_ATTR20               , 
         N_EXT_ATTR1                    => P_N_EXT_ATTR1                , 
         N_EXT_ATTR2                    => P_N_EXT_ATTR2                , 
         N_EXT_ATTR3                    => P_N_EXT_ATTR3                , 
         N_EXT_ATTR4                    => P_N_EXT_ATTR4                , 
         N_EXT_ATTR5                    => P_N_EXT_ATTR5                , 
         N_EXT_ATTR6                    => P_N_EXT_ATTR6                , 
         N_EXT_ATTR7                    => P_N_EXT_ATTR7                , 
         N_EXT_ATTR8                    => P_N_EXT_ATTR8                , 
         N_EXT_ATTR9                    => P_N_EXT_ATTR9                , 
         N_EXT_ATTR10                   => P_N_EXT_ATTR10               , 
         N_EXT_ATTR11                   => P_N_EXT_ATTR11               , 
         N_EXT_ATTR12                   => P_N_EXT_ATTR12               , 
         N_EXT_ATTR13                   => P_N_EXT_ATTR13               , 
         N_EXT_ATTR14                   => P_N_EXT_ATTR14               , 
         N_EXT_ATTR15                   => P_N_EXT_ATTR15               , 
         N_EXT_ATTR16                   => P_N_EXT_ATTR16               , 
         N_EXT_ATTR17                   => P_N_EXT_ATTR17               , 
         N_EXT_ATTR18                   => P_N_EXT_ATTR18               , 
         N_EXT_ATTR19                   => P_N_EXT_ATTR19               , 
         N_EXT_ATTR20                   => P_N_EXT_ATTR20               , 
         D_EXT_ATTR1                    => P_D_EXT_ATTR1                , 
         D_EXT_ATTR2                    => P_D_EXT_ATTR2                , 
         D_EXT_ATTR3                    => P_D_EXT_ATTR3                , 
         D_EXT_ATTR4                    => P_D_EXT_ATTR4                , 
         D_EXT_ATTR5                    => P_D_EXT_ATTR5                , 
         D_EXT_ATTR6                    => P_D_EXT_ATTR6                , 
         D_EXT_ATTR7                    => P_D_EXT_ATTR7                , 
         D_EXT_ATTR8                    => P_D_EXT_ATTR8                , 
         D_EXT_ATTR9                    => P_D_EXT_ATTR9                , 
         D_EXT_ATTR10                   => P_D_EXT_ATTR10               , 
         TL_EXT_ATTR1                   => P_TL_EXT_ATTR1               , 
         TL_EXT_ATTR2                   => P_TL_EXT_ATTR2               , 
         TL_EXT_ATTR3                   => P_TL_EXT_ATTR3               , 
         TL_EXT_ATTR4                   => P_TL_EXT_ATTR4               , 
         TL_EXT_ATTR5                   => P_TL_EXT_ATTR5               , 
         TL_EXT_ATTR6                   => P_TL_EXT_ATTR6               , 
         TL_EXT_ATTR7                   => P_TL_EXT_ATTR7               , 
         TL_EXT_ATTR8                   => P_TL_EXT_ATTR8               , 
         TL_EXT_ATTR9                   => P_TL_EXT_ATTR9               , 
         TL_EXT_ATTR10                  => P_TL_EXT_ATTR10              , 
         TL_EXT_ATTR11                  => P_TL_EXT_ATTR11              , 
         TL_EXT_ATTR12                  => P_TL_EXT_ATTR12              , 
         TL_EXT_ATTR13                  => P_TL_EXT_ATTR13              , 
         TL_EXT_ATTR14                  => P_TL_EXT_ATTR14              , 
         TL_EXT_ATTR15                  => P_TL_EXT_ATTR15              , 
         TL_EXT_ATTR16                  => P_TL_EXT_ATTR16              , 
         TL_EXT_ATTR17                  => P_TL_EXT_ATTR17              , 
         TL_EXT_ATTR18                  => P_TL_EXT_ATTR18              , 
         TL_EXT_ATTR19                  => P_TL_EXT_ATTR19              , 
         TL_EXT_ATTR20                  => P_TL_EXT_ATTR20              , 
         OWNER_TABLE_NAME               => NULL                         , 
         OWNER_TABLE_ID                 => NULL              
       );
     END create_object;
   END;
   /
   SHOW ERRORS;
   
   grant all on XX_CDH_HZ_EXT_ATTRIBS_BO to APPS with GRANT option;
   /
   SHOW ERRORS;   
   CREATE OR REPLACE TYPE XX_CDH_HZ_EXT_ATTRIBS_BO_TBL AS TABLE OF XX_CDH_HZ_EXT_ATTRIBS_BO;
   /
   SHOW ERRORS;
   grant all on XX_CDH_HZ_EXT_ATTRIBS_BO_TBL to APPS with GRANT option;
   /
   SHOW ERRORS;