delete from XXOD_TOPS_RETIRE_TABLE;
commit;
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE','BK_XX_CDH_SOLAR_ACTIVITIES_IM','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_BATCH_ID','Y'	,'N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_CONTACTIMAGE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_CONTACT_EXTR','Y','N'	);
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_CONVERSION_GR','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_CONVGRP_EXTR0','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_CONVGRP_EXTR1','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_CONVGRP_EXTR2','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_CONVGRP_EXTR3','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_CONVGRP_EXTR4','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_CONVGRP_USERD','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_CUST_ASGN_405','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_CUST_ASGN_EX1','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_CUST_ASGN_EX2','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_CUST_ASGN_EX3','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_CUST_ASGN_UPD','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_DISTRICTIMAGE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_FINAL_LEADS_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_INCUMBENTS','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_LEADS_DUMCONT','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_NOTEIMAGE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_NOTEIMAGE_RAW','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_NOTEIMAGE_TEX','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_NOTES_EXTR1','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_NOTES_EXTR2','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_NOTES_EXTR3','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_OPPORIMAGE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_OPPR_EXTR1','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_ORG_LEADS_STG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_PROSPECT_ADDR','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_PROSPECT_EXTR','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_PROS_ASGN_EX1','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_PROS_ASGN_EX2','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_PROS_ASGN_EX3','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_PROS_ASGN_UPD','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_RULES_EXTR','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_SALUTATION','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_SHIPTO_INT','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_SITEIMAGE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_SITEIMAGE_ALL','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_SITEIMAGE_SHI','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_SITE_CONTACT','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_STATE_COUNTRY','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'BK_XX_CDH_SOLAR_TODOIMAGE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_ACTIVITIES_IMAGE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_BATCH_ID','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_CONTACTIMAGE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_CONTACT_EXTR','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_CONVERSION_GROUP','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_CONVGRP_EXTR0','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_CONVGRP_EXTR1','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_CONVGRP_EXTR2','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_CONVGRP_EXTR3','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_CONVGRP_EXTR4','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_CONVGRP_USERDATA','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_CUST_ASGN_405_UPD','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_CUST_ASGN_EXTR1','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_CUST_ASGN_EXTR2','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_CUST_ASGN_EXTR3','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_CUST_ASGN_UPDATE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_DISTRICTIMAGE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_FINAL_LEADS_STG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_INCUMBENTS','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_LEADS_DUMCONT_STG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_NOTEIMAGE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_NOTEIMAGE_RAW','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_NOTEIMAGE_TEXTALL','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_NOTES_EXTR1','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_NOTES_EXTR2','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_NOTES_EXTR3','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_OPPORIMAGE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_OPPR_EXTR1','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_ORG_LEADS_STG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_PROSPECT_ADDR','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_PROSPECT_EXTR','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_PROS_ASGN_EXTR1','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_PROS_ASGN_EXTR2','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_PROS_ASGN_EXTR3','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_PROS_ASGN_UPDATE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_RULES_EXTR','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_SALUTATION','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_SHIPTO_INT','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_SITEIMAGE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_SITEIMAGE_ALL','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_SITEIMAGE_SHIPTO','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_SITE_CONTACT','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_STATE_COUNTRY','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_TODOIMAGE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_CDH_SOLAR_USPS_ZIPCODES','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_JTF_IMP_TASK_ASSGN_INT','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_JTF_IMP_TASK_RECUR_INT','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_JTF_IMP_TASK_REFS_INT','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_JTF_IMP_TASKS_DEPEND_INT','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_JTF_IMP_TASKS_INT','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_JTF_NOTE_CTX_INT','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','TABLE'	,'XX_JTF_NOTES_INT','Y','N'); 

INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','SEQUENCE','XX_CDH_SOLAR_BATCH_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','SEQUENCE','XX_CDH_SOLAR_CUSASG_UPDATE_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','SEQUENCE','XX_CDH_SOLAR_LEADS_STG_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','SEQUENCE','XX_JTF_IMP_TASK_ASSGN_INT_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','SEQUENCE','XX_JTF_IMP_TASK_RECUR_INT_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','SEQUENCE','XX_JTF_IMP_TASKS_DEPEND_INT_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','SEQUENCE','XX_JTF_IMP_TASK_REFS_INT_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','SEQUENCE','XX_JTF_IMP_TASKS_INT_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','SEQUENCE','XX_JTF_NOTE_CTX_INT_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCNV','SEQUENCE','XX_JTF_NOTES_INT_S','Y','N');

Commit;

INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_ASSIGN_IDS','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_CONTACT','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXCRM_REP_STORE_MAP','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_OPP_CONTACT','Y','N'); 
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_PROSPECT_IDS','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_SPID','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_USER','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_GOALS','Y','N'); 
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_TPS_SITE_REQUESTS_STG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_NOTES_ALL','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_DATALOADER_ERROR','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_TASKS_ALL','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_ACTIVITIES_FCT_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_CONTACT_MV_TBL','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_GROUP_MBR_INFO_MV','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_OD_STORE_NUM_DIM_MV','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_PARTY_SITE_DATA_FCT_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_SALES_OPPTY_FCT_MV','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_TASKS_FCT_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_TERENT_ASGNMNT_FCT_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_TM_NAM_GDW_BATCHES','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_TM_NAM_TERR_ENTITY_ORIG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_TM_NAM_TERR_HISTORY_DTLS','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_CS_POTENTIAL_CDH_MV','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_CS_POTENTIAL_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_LEAD_CURR_ASSIGN_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_SITE_CURR_ASSIGN_MV','Y','N');




INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','SEQUENCE','XX_TM_NAM_TERR_RSC_DTLS_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','SEQUENCE','XX_TM_NAM_TERR_DEFN_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','SEQUENCE','XX_TM_NAM_TERR_ENTITY_DTLS_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','SEQUENCE','XX_CRM_EXP_CONTACT_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','SEQUENCE','XX_CRM_EXP_LEAD_REC_ID_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','SEQUENCE','XX_CRM_EXP_OPP_CONTACT_ID_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','SEQUENCE','XX_CRM_EXP_OPP_REC_ID_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','SEQUENCE','XX_CRM_EXP_PROSPECT_IDS_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','SEQUENCE','XX_CRM_EXP_SP_REC_ID_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','SEQUENCE','XX_CRM_EXP_USER_REC_ID_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','SEQUENCE','XX_TM_NAM_TERR_HISTORY_DTLS_S','Y','N');

INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','OMX_PRIMARY_ASSIGNMENT_STG_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_CRM_EXP_NOTES_PKG','Y','N'); 
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_NAMED_ACCT_PREPROCESSOR','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_REASSIGNMENT_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_CRM_CLOSE_LEAD_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_CRM_CPD_DEPLOYMENT_CHK_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_CRM_CREATE_ACCESSES_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_CRM_INCENTCOMP_FEED_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_CRM_SFA_LEAD_REP','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_CRM_TOPS_ASSIGNMENT_RPT','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_CRM_UPDATE_WIN_PROB_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_BL_SLREP_GDW_PST_CRTN','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_BL_SLREP_PST_CRTN','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_CUSTOM_QUALIFIER_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_LOAD_TERRALIGN_DATA','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_NMDACC_CREATE_TERR','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_NOTES_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_RS_NAMED_ACC_TERR_PUB','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_SALES_REP_BL_LEAD_CRTN','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_SALES_REP_BL_OPPTY_CRTN','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_SALES_REP_LEAD_SYNC','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_SALES_REP_OPPTY_SYNC','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_SL_REP_UNASSGN_INT_CUST','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_SLS_REP_NW_DIV_PTY_SITE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_TASKS_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_TERR_RSC_REP','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_TERR_SM_POSTAL_CODE_REP','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_TERR_WITHOUT_RSC_REP','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_TERRITORIES_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_TERRITORY_REP','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_UNASSGN_PST_EXP_REP','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_UNASSIGN_PTY_SITE_REP','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_UPDATE_CUST_ACCOUNT_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_UPDATE_CUST_ACCT_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_LEAD_ADDR_DATA_FIX_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_SFA_CPD_LEADS_ASSIGNED_RES','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_SFA_CUSTOM_TASK_REF_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_SFA_LEAD_REFERRAL_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_SFA_LEAD_REFF_CREATE_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_SFA_LEADREF_RSD_WAVES_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_SFA_OPPORTUNITY_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_SFA_LEADS_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_SFA_OPPTY_RPT_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_SFA_PERZ_GEN_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_SFA_PROSPECT_CUST_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_SFA_TECH_LEADS_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_SFA_WORK_DIST_REP','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_SOLAR_AUTONAMED_RPT_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_ASSGN_TPS_REPORT_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_ASSIGN_RESOURCE_TO_TERR','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_ASSIGNMENTS_OUTBOUND_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_BLK_ASSGN_TPS_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_GET_WINNERS_ON_QUALS','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_INSERT_TPS_STG_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_NAM_TERR_HIST_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_NMDACCT_GDW_PREPROC','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_NMDACCT_NWDIV_PREPROC','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_RESOURCE_REP','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_RM_RESOURCE_GROUPS_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_SETUP_RSC_ASSIGNMENT_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XXBI_ACTIVITY_DT_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XXBI_FAST_REFRESH_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XXBI_LEAD_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XXBI_OPPORTUNITY_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XXBI_UTILITY_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XXCRM_OPPTY_FIX_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XXCRM_OPPTY_RESOURCE_FIX_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XXCRM_TASK_DASHBOARD_HELPER','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XXCRM_TASK_DASHBOARD_HELPER','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XXCRM_UPDATE_TASKS','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XXSCS_CONT_STRATEGY_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XXSCS_LOAD_STG_DATA','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XXSCS_PRF_TO_SIT_DATA_CPY','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XXSCS_SIT_TO_PRF_DATA_CPY','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XXSCS_UTILITY_PKG','Y','N');

 
Commit;

INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_GOAL_ADJUSTMENT_RULES','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_GOALCALC_LINE_ITEMS_TL','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_GOALCALC_LINE_ITEMS_B','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_BBQ_GROUP_MBR_ROLE','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_AOPS_CRM031F_STG','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_AOPS_CCU030F_STG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_OVRL_PRCS_GRP_CHG_TMP','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_OVRL_ASSIGNMENT_SITES','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_OVRL_ASSGNMENT_STG_ARC','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_OVRL_ASSGNMENT_STG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_OVRL_ASSGNMENT_ARCHIVE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_RS_MONTH_GOAL_DETAILS','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_RS_GOALPERIOD_GOALS','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_RS_GOAL_SPLIT_TXNS','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_RS_GOAL_MOVE_TXNS','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_HOLIDAYS_CALANDER','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_PARTY_SITE_EXTNS','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_OVRL_PROCESS_PRGRSS_SMRY','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XTPS_OVRL_PROCESS_ALL_REC_TMP','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_OVRL_PRG_ENTITY_DTL_TMP','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_OVRL_RM_RULES','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_SALES_TERM_DISPLAYS','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_OVERLAY_TIES_LOG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_OMX_CUSTOMER_XREF','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_LOAD_ADJUSTMENTS_STG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_AUTO_ADJUST_RUN_CONTROL','Y'	,'N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_OMX_ASSIGNMENT_STG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_ROLE_RESTRICTION','Y','N'	);
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_RM_CHANGE_TEMP','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_PROCESS_SEG_CHG_STG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XX_OMX_RELS_UPDATE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XX_OMX_RELATIONSHIPS','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XX_OMX_PRIMARY_ASSIGNMENT_STG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XX_OMX_BSD_CUSTOMER','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_SITE_REQUEST','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_SITE_GRADUATIONS','Y','N');



INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_GOAL_ADJUST_RULE_ID_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_GOALCALC_RUNCTL_ID_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_OVRL_ENTITY_ASGNMNTS_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','BBQ_GROUP_MBR_ID_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XX_CDH_SOLAR_LEADS_STG_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_RS_GOAL_SPLIT_TXN_ID_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_AUTOADJUST_RUNCTL_ID_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XX_OVRL_PRG_PROCESS_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_SITE_GRADUATION_ID_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_SALES_TERM_DISPLAY_ID_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_ROLE_RESTRICTION_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_RS_MTH_GOAL_DET_ID_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_RS_GOALCOMP_GOAL_ID_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_RS_GOAL_MOVE_TXN_ID_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_RS_GOAL_DETAIL_ID_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_OVRL_RM_RULES_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_OVERLAY_TIES_LOG_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_OVRL_RLTNSHPS_DTLS_S','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_OVRL_RELATIONSHIPS_S','Y','N');


INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_MV_REFRESH_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_ABN_SITES_RPT_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_ALL_GOAL_CALC','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_ASSIGNMENT_REQUEST_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_BBQ_GROUP_MBR_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_DSM_GOAL_CALC','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_DW_INT','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_GOALING_PVT','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_GROUP_PARAM_V','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_OVRLY_RELN_SRCH_VW','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_LOAD_LGCY_SALES_FORCE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_MOVE_GOALS','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_OVRL_EXPORT_ASSIGNMENT','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_OVRL_PERF_RPT','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_OVRLY_RELN_RPT_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_PROCESS_OVRL_RULES_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_RM_CHANGES_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_RSD_GOAL_CALC','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_SC_GOAL_CALC','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_TERRITORY_UTIL_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_TERRITORY_UTIL_PKG_W','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_CRM_OVERLAY_RULE','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_RS_NAMED_ACC_TERR','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_SALES_REP_LEAD_CRTN','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_SALES_REP_OPPTY_CRTN','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_JTF_SALES_REP_PTY_SITE_CRTN','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_CRM_EXP_TASKS_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_OVRL_ASGNMNT_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_OVRL_RELATIONSHIP_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_OVRL_UTILS_PKG','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_REP_GOAL_CALC','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_UTIL_PUB','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_OVRL_RLTNS_V','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_RS_GOALCOMP_GOALS_V','Y','N');


--- Materialized views for deside

INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_USER_SUMMARY_FCT_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_SALES_LEADS_FCT_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_TASKS_FCT_SUMMARY_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_LEAD_LINE_COMPTTR_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_SLS_LDS_SMRY_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_GROUP_MBR_USER_ID_MV','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_CONTACTS_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_LAST_SITE_CONTACT_ID_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_LAST_SITE_CONTACT_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_ENT_TYPES_DIM_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_SLS_OPP_SMRY_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_ORGNL_SALES_GOAL_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_SALES_LEAD_FCT_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_CUST_WCW_RANGE_MV','Y','N');
INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XXBI_CUSTOMER_FCT_MV','Y','N');


 

commit;

-- Retrofit Tables once approved drop these
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_NOTES_OPP_MASTER','Y','N'); 
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_TASKS_LEAD_MASTER','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_TASKS_PARTY','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_TASKS_OPP_MASTER','Y','N'); 
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_TASKS_OPPORTUNITY','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_TASKS_TASK_MASTER','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_TASKS_TASK','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_TASKS_SITE_MASTER','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_TASKS_PARTY_MASTER','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_TASKS_PARTY_SITE','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_LEAD','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_OPPORTUNITY','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_TM_NAM_TERR_DEFN','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_TM_NAM_TERR_ENTITY_DTLS','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_TM_NAM_TERR_RSC_DTLS','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_GOALS_ALL','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_GOAL_ADJUSTMENTS','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_GOAL_ADJUST_SPREADS','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_GOAL_CALC_RUNCONTROL','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_GOAL_COMPONENTS','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_GOAL_PERIODS','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_OVRL_ENTITY_ASGNMNTS','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_OVRL_RELATIONSHIPS','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_OVRL_RLTNSHPS_DTLS','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_PARTY_SITE_AGG','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_RS_GOALCOMP_GOALS','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_RS_GOAL_DETAILS','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_GROUP_MBR_INFO_MV','Y','N');



 
 


--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_AN_RSC_SYNC_REPORT_PKG','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','PACKAGE','XX_TM_RM_HIERARCHY_REPORT_PKG','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_TEMPLATE_FILE_UPLOADS','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_FILE_UPLOADS_CMN_PKG','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_FILE_UPLOADS_PKG','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_RESOURCES_UTIL','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_SALES_TERMS_PKG','Y','N');




---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','SEQUENCE','XX_CRM_SFDC_CONTACTS_S','Y','N');


-------INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_ASSIGNMENTS','Y','N');

-----INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_NOTES_LEAD','Y','N');
-----INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_NOTES_LEAD_MASTER','Y','N'); 
-----INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_NOTES_OPPORTUNITY','Y','N'); 

------INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_TASKS_LEAD','Y','N');
------INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_NOTES_SITE_MASTER','Y','N');
-----INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_NOTES_PARTY_SITE','Y','N');
-----INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_NOTES_PARTY_MASTER','Y','N'); 
-----INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_EXP_NOTES_PARTY','Y','N');

-----INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXCRM','TABLE'	,'XX_CRM_SFDC_CONTACTS','Y','N');

--- Trigeer

-- INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_SITE_REQUEST_ID_S','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_FILE_UPLOAD_ID_S','Y','N');


----- BULK PKG
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','PACKAGE','XXTPS_BULK_TEMPLATES_PKG','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_RS_GOAL_OVERLAY_ID_S','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_RS_GROUP_GOAL_ID_S','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_SITE_BULK_REQUEST_ID_S','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_RS_ROLE_GOAL_ID_S','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_GOAL_ADJUSTMENT_ID_S','Y','N');


--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_GOAL_ID_S','Y','N');

--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_GOAL_PERIOD_ID_S','Y','N');

-- INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_GOAL_COMPONENT_ID_S','Y','N');

----INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_OMX_ASSIG_EXCP','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_RS_ROLE_GOAL_SPREADS','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_RS_ROLE_GOALS','Y','N');
---INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_RS_GOAL_OVERLAYS','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_RS_ROLE_GOAL_MARGINS','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_SALES_TERMS_ALL','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','SEQUENCE','XXTPS_SALES_TERM_ID_S','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_RS_GROUP_GOALS','Y','N');
--INSERT INTO XXOD_TOPS_RETIRE_TABLE VALUES('XXTPS','TABLE'	,'XXTPS_RS_GROUP_GOAL_SPREADS','Y','N');


/

