<?xml version="1.0" encoding="UTF-8"?>
<definitions name="plOrgLocStg"
             targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/plOrgLocStg/"
             xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/plOrgLocStg/"
             xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
             xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
             xmlns:pc="http://xmlns.oracle.com/pcbpel/"
             xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/plOrgLocStg"
             xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/db/"
             xmlns="http://schemas.xmlsoap.org/wsdl/">
    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/"
            location="DBAdapterOutboundHeader.wsdl"/>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/plOrgLocStg"
                    schemaLocation="plOrgLocStg_table.xsd"/>
        </schema>
    </types>
    <message name="XxInvOrgLocDefStgCollection_msg">
        <part name="XxInvOrgLocDefStgCollection"
              element="top:XxInvOrgLocDefStgCollection"/>
    </message>
    <portType name="plOrgLocStg_ptt">
        <operation name="insert">
            <input message="tns:XxInvOrgLocDefStgCollection_msg"/>
        </operation>
    </portType>
    <binding name="plOrgLocStg_binding" type="tns:plOrgLocStg_ptt">
        <jca:binding/>
        <operation name="insert">
            <jca:operation InteractionSpec="oracle.tip.adapter.db.DBWriteInteractionSpec"
                           DescriptorName="plOrgLocStg.XxInvOrgLocDefStg"
                           DmlType="insert" DetectOmissions="true"
                           OptimizeMerge="true"
                           MappingsMetaDataURL="plOrgLocStg_toplink_mappings.xml"/>
            <input>
                <jca:header message="hdr:OutboundHeader_msg"
                            part="outboundHeader"/>
            </input>
        </operation>
    </binding>
    <!-- Your runtime connection is declared in
        J2EE_HOME/application-deployments/default/DbAdapter/oc4j-ra.xml
        These 'mcf' properties here are from your design time connection and 
        save you from having to edit that file and restart the application server
        if eis/db/EBSApps is missing.
        These 'mcf' properties are safe to remove.
    -->
    <service name="plOrgLocStg">
        <port name="plOrgLocStg_pt" binding="tns:plOrgLocStg_binding">
            <jca:address location="eis/db/EBSApps"
                         UIConnectionName="ebs_apps_gsidev02">
                <!--               ManagedConnectionFactory="oracle.tip.adapter.db.DBManagedConnectionFactory"
                mcf.DriverClassName="oracle.jdbc.OracleDriver"
                mcf.PlatformClassName="oracle.toplink.platform.database.oracle.Oracle10Platform"
                mcf.ConnectionString="jdbc:oracle:thin:@//choldbr13d.na.odcorp.net:1541/gsidev02"
                mcf.UserName="apps"
                mcf.Password="589713C9226D58ECFC970AF706D8C533D62D1A19DF561D1E"
            />-->
            </jca:address>
        </port>
    </service>
    <plt:partnerLinkType name="plOrgLocStg_plt">
        <plt:role name="plOrgLocStg_role">
            <plt:portType name="tns:plOrgLocStg_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
</definitions>
