DROP TYPE XX_OM_LEG_POS_SHIP_CONF_PKG_X FORCE; 
show errors
DROP TYPE XX_OM_LEG_POS_SHIP_CONF_PKG_10 FORCE; 
show errors
DROP TYPE XX_OM_LEG_POS_SHIP_CONF_PKG_7 FORCE; 
show errors
DROP TYPE XX_OM_LEG_POS_SHIP_CONF_PKG11 FORCE; 
show errors
DROP TYPE XX_OM_LEG_POS_SHIP_CONF_PKG_8 FORCE; 
show errors
DROP TYPE XX_OM_LEG_POS_SHIP_CONF_PKG12 FORCE; 
show errors
DROP TYPE XX_OM_LEG_POS_SHIP_CONF_PKG_9 FORCE; 
show errors
DROP PACKAGE XX_BPEL_SVCLEGACYPOSREAD;
exit
