package od.oracle.apps.xxcrm.asn.common.customer.server;
import oracle.apps.asn.common.customer.server.CustSearchResultsSVOImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class ODCustSearchResultsSVOImpl extends CustSearchResultsSVOImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public ODCustSearchResultsSVOImpl()
  {
  }
}