-- +===========================================================================================+
-- |                  Office Depot - Project Simplify                                          |
-- +===========================================================================================+
-- | Name        : Insert_xx_fin_translatevalues_txt_skutax                                    |
-- | Description : This Script is used to insert the SKU level details                         |
-- |               field into translations values                                              |
-- |Change Record:                                                                             |
-- |===============                                                                            |
-- |Version   Date          Author                 Remarks                                     |
-- |=======   ==========   =============           ============================================|
-- |DRAFT 1.0 28-AUG-2018  Capgemini               Defect# NAIT-58403                          |
-- +===========================================================================================+
--Inserting values for eXLS SKU Level Tax and SKU Level Total

INSERT INTO XX_FIN_TRANSLATEVALUES (TRANSLATE_ID,SOURCE_VALUE1,SOURCE_VALUE2,SOURCE_VALUE3,SOURCE_VALUE4,SOURCE_VALUE5,SOURCE_VALUE6,SOURCE_VALUE7,TARGET_VALUE1,TARGET_VALUE2,TARGET_VALUE3,TARGET_VALUE4,TARGET_VALUE5,TARGET_VALUE6,TARGET_VALUE7,TARGET_VALUE8,TARGET_VALUE9,TARGET_VALUE10,TARGET_VALUE11,TARGET_VALUE12,TARGET_VALUE13,TARGET_VALUE14,TARGET_VALUE15,TARGET_VALUE16,TARGET_VALUE17,TARGET_VALUE18,TARGET_VALUE19,TARGET_VALUE20,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,START_DATE_ACTIVE,END_DATE_ACTIVE,READ_ONLY_FLAG,ENABLED_FLAG,SOURCE_VALUE8,SOURCE_VALUE9,SOURCE_VALUE10,TRANSLATE_VALUE_ID,TARGET_VALUE21,TARGET_VALUE22,TARGET_VALUE23,TARGET_VALUE24,TARGET_VALUE25,TARGET_VALUE26,TARGET_VALUE27,TARGET_VALUE28,TARGET_VALUE29,TARGET_VALUE30) values (57362,'40166','SKU Level Tax',null,'SKU_LEVEL_TAX',null,'Y','Y','NUMERIC','0.00','12',null,'N','Added for NAIT 58403',null,null,null,null,null,null,'1','Y',null,null,'D','Y','DT','Lines',sysdate,3828430,sysdate,3828430,69427092,sysdate,null,null,'Y','Y','N','Y',XX_FIN_TRANSLATEVALUES_S.NEXTVAL,'N','N',null,null,'N','N',null,null,null,null);
INSERT INTO XX_FIN_TRANSLATEVALUES (TRANSLATE_ID,SOURCE_VALUE1,SOURCE_VALUE2,SOURCE_VALUE3,SOURCE_VALUE4,SOURCE_VALUE5,SOURCE_VALUE6,SOURCE_VALUE7,TARGET_VALUE1,TARGET_VALUE2,TARGET_VALUE3,TARGET_VALUE4,TARGET_VALUE5,TARGET_VALUE6,TARGET_VALUE7,TARGET_VALUE8,TARGET_VALUE9,TARGET_VALUE10,TARGET_VALUE11,TARGET_VALUE12,TARGET_VALUE13,TARGET_VALUE14,TARGET_VALUE15,TARGET_VALUE16,TARGET_VALUE17,TARGET_VALUE18,TARGET_VALUE19,TARGET_VALUE20,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,START_DATE_ACTIVE,END_DATE_ACTIVE,READ_ONLY_FLAG,ENABLED_FLAG,SOURCE_VALUE8,SOURCE_VALUE9,SOURCE_VALUE10,TRANSLATE_VALUE_ID,TARGET_VALUE21,TARGET_VALUE22,TARGET_VALUE23,TARGET_VALUE24,TARGET_VALUE25,TARGET_VALUE26,TARGET_VALUE27,TARGET_VALUE28,TARGET_VALUE29,TARGET_VALUE30) values (57362,'40167','SKU Level Total',null,'SKU_LEVEL_TOTAL',null,'Y','Y','NUMERIC','0.00','12',null,'N','Added for NAIT 58403',null,null,null,null,null,null,'1','Y',null,null,'D','Y','DT','Lines',sysdate,3828430,sysdate,3828430,69427092,sysdate,null,null,'Y','Y','N','Y',XX_FIN_TRANSLATEVALUES_S.NEXTVAL,'N','N',null,null,'N','N',null,null,null,null);

Commit;