create or replace 
PACKAGE XX_AP_RWOLXML_PKG
AS
P_DATE_FROM DATE;
P_DATE_TO DATE;
P_SUPPLIER_SITE_CODE varchar2(240);
P_CONC_REQUEST_ID NUMBER :=0;
FUNCTION beforeReport RETURN BOOLEAN;
FUNCTION afterReport RETURN BOOLEAN;
END;
/