CREATE TABLE XXOD_OMX_CNV_AR_CUST_STG_HIST
 ( 
    RECORD_ID             NUMBER,
	ODN_CUST_NUM          VARCHAR2(30),
    ODN_CUST_NAME         VARCHAR2(360),
    ORG_ADDRESS1          VARCHAR2(240),
    ORG_ADDRESS2          VARCHAR2(240),
    ORG_CITY              VARCHAR2(60),
    ORG_STATE             VARCHAR2(60),
    ORG_ZIPCODE           VARCHAR2(60),
    ORG_CONTACT_NAME      VARCHAR2(360),
    ORG_CONTACT_EMAIL     VARCHAR2(2000),
    ORG_CONTACT_PHONE     VARCHAR2(40),
    BILL_TO_CNSGNO        VARCHAR2(60),
    BILL_TO_ADDRESS1      VARCHAR2(240),
    BILL_TO_ADDRESS2      VARCHAR2(240),
    BILL_TO_CITY          VARCHAR2(60),
    BILL_TO_STATE         VARCHAR2(60),
    BILL_TO_ZIPCODE       VARCHAR2(60),
    BILL_TO_CONTACT_NAME  VARCHAR2(360),
    BILL_TO_CONTACT_EMAIL VARCHAR2(2000),
    BILL_TO_CONTACT_PHONE VARCHAR2(40),
    SHIP_TO_CNSGNO        VARCHAR2(60),
    SHIP_TO_ADDRESS1      VARCHAR2(240),
    SHIP_TO_ADDRESS2      VARCHAR2(240),
    SHIP_TO_CITY          VARCHAR2(60),
    SHIP_TO_STATE         VARCHAR2(60),
    SHIP_TO_ZIPCODE       VARCHAR2(60),
    SHIP_TO_CONTACT_NAME  VARCHAR2(360),
    SHIP_TO_CONTACT_EMAIL VARCHAR2(2000),
    SHIP_TO_CONTACT_PHONE VARCHAR2(40),
    INTERFACE_ID          NUMBER,
    REQUEST_ID            NUMBER,
    RECORD_STATUS         VARCHAR2(1),
    CONV_ERROR_MSG        VARCHAR2(4000),
    CREATION_DATE         DATE,
    CREATED_BY            NUMBER,
    LAST_UPDATE_DATE      DATE,
    LAST_UPDATED_BY       NUMBER,
    LAST_UPDATE_LOGIN     NUMBER,
    BATCH_ID		      NUMBER
  );






