  CREATE GLOBAL TEMPORARY TABLE "XXFIN"."XXTWE_ISO_USETAX_TMP" 
   (	"DATE_CREATED" DATE, 
	"SEGMENT1" VARCHAR2(25 BYTE), 
	"STATE" VARCHAR2(60 BYTE), 
	"TAX_VALUE" NUMBER, 
	"ORDER_NUMBER" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"UNIT_SELLING_PRICE" NUMBER, 
	"ITEM_DESCRIPTION" VARCHAR2(240 BYTE)
   ) ON COMMIT DELETE ROWS;