package od.oracle.apps.xxcrm.customer.account.server;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class ODContractTemplatesVORowImpl extends OAViewRowImpl 
{


  protected static final int CONTRACTTEMPLATEID = 0;
  protected static final int TEMPLATENAME = 1;
  protected static final int REVENUEBANDCODE = 2;
  protected static final int CONTRACTDESCRIPTION = 3;
  protected static final int PRIORITY = 4;
  protected static final int CUSTOM = 5;
  protected static final int CREATEDBY = 6;
  protected static final int CREATIONDATE = 7;
  protected static final int LASTUPDATEDBY = 8;
  protected static final int LASTUPDATEDATE = 9;
  protected static final int LASTUPDATELOGIN = 10;
  protected static final int SALESROLE = 11;
  protected static final int CONTRACTNUMBER = 12;
  protected static final int CUSTPRODXREF = 13;
  protected static final int OFFCONTRACTCODE = 14;
  protected static final int OFFCONTRACTPERCENT = 15;
  protected static final int OFFWHOLESALECODE = 16;
  protected static final int OFFWHOLESALEPERCENT = 17;
  protected static final int GPFLOORPERCENT = 18;
  protected static final int FREIGHTCHARGE = 19;
  protected static final int PARENTID = 20;
  protected static final int TEMPLATELOCKEDFLAG = 21;
  protected static final int PRICEPLANLOCKEDFLAG = 22;
  protected static final int ASSNCONTRLOCKEDFLAG = 23;
  protected static final int PRICEPLANMANDATORYFLAG = 24;
  protected static final int REV = 25;
  protected static final int ODCONTRACTSPRICEPLANVO = 26;
  protected static final int ODCONTRACTSASSIGNEDVO1 = 27;
  protected static final int ODCDHCONTRACTPROGCODESVO = 28;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public ODContractTemplatesVORowImpl()
  {
  }

  /**
   * 
   * Gets ODCdhContractTemplateEO entity object.
   */
  public od.oracle.apps.xxcrm.customer.account.schema.server.ODCdhContractTemplateEOImpl getODCdhContractTemplateEO()
  {
    return (od.oracle.apps.xxcrm.customer.account.schema.server.ODCdhContractTemplateEOImpl)getEntity(0);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ContractTemplateId
   */
  public Number getContractTemplateId()
  {
    return (Number)getAttributeInternal(CONTRACTTEMPLATEID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ContractTemplateId
   */
  public void setContractTemplateId(Number value)
  {
    setAttributeInternal(CONTRACTTEMPLATEID, value);
  }





















































































  /**
   * 
   * Gets the associated <code>RowIterator</code> using master-detail link ODContractsAssignedVO1
   */
  public oracle.jbo.RowIterator getODContractsAssignedVO1()
  {
    return (oracle.jbo.RowIterator)getAttributeInternal(ODCONTRACTSASSIGNEDVO1);
  }

  /**
   * 
   * Gets the associated <code>RowIterator</code> using master-detail link ODContractsPricePlanVO
   */
  public oracle.jbo.RowIterator getODContractsPricePlanVO()
  {
    return (oracle.jbo.RowIterator)getAttributeInternal(ODCONTRACTSPRICEPLANVO);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CONTRACTTEMPLATEID:
        return getContractTemplateId();
      case TEMPLATENAME:
        return getTemplateName();
      case REVENUEBANDCODE:
        return getRevenueBandCode();
      case CONTRACTDESCRIPTION:
        return getContractDescription();
      case PRIORITY:
        return getPriority();
      case CUSTOM:
        return getCustom();
      case CREATEDBY:
        return getCreatedBy();
      case CREATIONDATE:
        return getCreationDate();
      case LASTUPDATEDBY:
        return getLastUpdatedBy();
      case LASTUPDATEDATE:
        return getLastUpdateDate();
      case LASTUPDATELOGIN:
        return getLastUpdateLogin();
      case SALESROLE:
        return getSalesRole();
      case CONTRACTNUMBER:
        return getContractNumber();
      case CUSTPRODXREF:
        return getCustProdXref();
      case OFFCONTRACTCODE:
        return getOffContractCode();
      case OFFCONTRACTPERCENT:
        return getOffContractPercent();
      case OFFWHOLESALECODE:
        return getOffWholesaleCode();
      case OFFWHOLESALEPERCENT:
        return getOffWholesalePercent();
      case GPFLOORPERCENT:
        return getGpFloorPercent();
      case FREIGHTCHARGE:
        return getFreightCharge();
      case PARENTID:
        return getParentId();
      case TEMPLATELOCKEDFLAG:
        return getTemplateLockedFlag();
      case PRICEPLANLOCKEDFLAG:
        return getPriceplanLockedFlag();
      case ASSNCONTRLOCKEDFLAG:
        return getAssncontrLockedFlag();
      case PRICEPLANMANDATORYFLAG:
        return getPriceplanMandatoryFlag();
      case REV:
        return getRev();
      case ODCONTRACTSPRICEPLANVO:
        return getODContractsPricePlanVO();
      case ODCONTRACTSASSIGNEDVO1:
        return getODContractsAssignedVO1();
      case ODCDHCONTRACTPROGCODESVO:
        return getODCdhContractProgCodesVO();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CONTRACTTEMPLATEID:
        setContractTemplateId((Number)value);
        return;
      case TEMPLATENAME:
        setTemplateName((String)value);
        return;
      case REVENUEBANDCODE:
        setRevenueBandCode((String)value);
        return;
      case CONTRACTDESCRIPTION:
        setContractDescription((String)value);
        return;
      case PRIORITY:
        setPriority((String)value);
        return;
      case CUSTOM:
        setCustom((String)value);
        return;
      case CREATEDBY:
        setCreatedBy((Number)value);
        return;
      case CREATIONDATE:
        setCreationDate((Date)value);
        return;
      case LASTUPDATEDBY:
        setLastUpdatedBy((Number)value);
        return;
      case LASTUPDATEDATE:
        setLastUpdateDate((Date)value);
        return;
      case LASTUPDATELOGIN:
        setLastUpdateLogin((Number)value);
        return;
      case SALESROLE:
        setSalesRole((String)value);
        return;
      case CONTRACTNUMBER:
        setContractNumber((String)value);
        return;
      case CUSTPRODXREF:
        setCustProdXref((String)value);
        return;
      case OFFCONTRACTCODE:
        setOffContractCode((String)value);
        return;
      case OFFCONTRACTPERCENT:
        setOffContractPercent((Number)value);
        return;
      case OFFWHOLESALECODE:
        setOffWholesaleCode((String)value);
        return;
      case OFFWHOLESALEPERCENT:
        setOffWholesalePercent((Number)value);
        return;
      case GPFLOORPERCENT:
        setGpFloorPercent((Number)value);
        return;
      case FREIGHTCHARGE:
        setFreightCharge((String)value);
        return;
      case PARENTID:
        setParentId((String)value);
        return;
      case TEMPLATELOCKEDFLAG:
        setTemplateLockedFlag((String)value);
        return;
      case PRICEPLANLOCKEDFLAG:
        setPriceplanLockedFlag((String)value);
        return;
      case ASSNCONTRLOCKEDFLAG:
        setAssncontrLockedFlag((String)value);
        return;
      case PRICEPLANMANDATORYFLAG:
        setPriceplanMandatoryFlag((String)value);
        return;
      case REV:
        setRev((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the attribute value for TEMPLATE_NAME using the alias name TemplateName
   */
  public String getTemplateName()
  {
    return (String)getAttributeInternal(TEMPLATENAME);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for TEMPLATE_NAME using the alias name TemplateName
   */
  public void setTemplateName(String value)
  {
    setAttributeInternal(TEMPLATENAME, value);
  }

  /**
   * 
   * Gets the attribute value for REVENUE_BAND_CODE using the alias name RevenueBandCode
   */
  public String getRevenueBandCode()
  {
    return (String)getAttributeInternal(REVENUEBANDCODE);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for REVENUE_BAND_CODE using the alias name RevenueBandCode
   */
  public void setRevenueBandCode(String value)
  {
    setAttributeInternal(REVENUEBANDCODE, value);
  }

  /**
   * 
   * Gets the attribute value for CONTRACT_DESCRIPTION using the alias name ContractDescription
   */
  public String getContractDescription()
  {
    return (String)getAttributeInternal(CONTRACTDESCRIPTION);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for CONTRACT_DESCRIPTION using the alias name ContractDescription
   */
  public void setContractDescription(String value)
  {
    setAttributeInternal(CONTRACTDESCRIPTION, value);
  }

  /**
   * 
   * Gets the attribute value for PRIORITY using the alias name Priority
   */
  public String getPriority()
  {
    return (String)getAttributeInternal(PRIORITY);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for PRIORITY using the alias name Priority
   */
  public void setPriority(String value)
  {
    setAttributeInternal(PRIORITY, value);
  }

  /**
   * 
   * Gets the attribute value for CUSTOM using the alias name Custom
   */
  public String getCustom()
  {
    return (String)getAttributeInternal(CUSTOM);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for CUSTOM using the alias name Custom
   */
  public void setCustom(String value)
  {
    setAttributeInternal(CUSTOM, value);
  }

  /**
   * 
   * Gets the attribute value for CREATED_BY using the alias name CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for CREATION_DATE using the alias name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * 
   * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**
   * 
   * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin()
  {
    return (Number)getAttributeInternal(LASTUPDATELOGIN);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value)
  {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**
   * 
   * Gets the attribute value for SALES_ROLE using the alias name SalesRole
   */
  public String getSalesRole()
  {
    return (String)getAttributeInternal(SALESROLE);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for SALES_ROLE using the alias name SalesRole
   */
  public void setSalesRole(String value)
  {
    setAttributeInternal(SALESROLE, value);
  }

  /**
   * 
   * Gets the attribute value for CONTRACT_NUMBER using the alias name ContractNumber
   */
  public String getContractNumber()
  {
    return (String)getAttributeInternal(CONTRACTNUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for CONTRACT_NUMBER using the alias name ContractNumber
   */
  public void setContractNumber(String value)
  {
    setAttributeInternal(CONTRACTNUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for CUST_PROD_XREF using the alias name CustProdXref
   */
  public String getCustProdXref()
  {
    return (String)getAttributeInternal(CUSTPRODXREF);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for CUST_PROD_XREF using the alias name CustProdXref
   */
  public void setCustProdXref(String value)
  {
    setAttributeInternal(CUSTPRODXREF, value);
  }

  /**
   * 
   * Gets the attribute value for OFF_CONTRACT_CODE using the alias name OffContractCode
   */
  public String getOffContractCode()
  {
    return (String)getAttributeInternal(OFFCONTRACTCODE);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for OFF_CONTRACT_CODE using the alias name OffContractCode
   */
  public void setOffContractCode(String value)
  {
    setAttributeInternal(OFFCONTRACTCODE, value);
  }

  /**
   * 
   * Gets the attribute value for OFF_CONTRACT_PERCENT using the alias name OffContractPercent
   */
  public Number getOffContractPercent()
  {
    return (Number)getAttributeInternal(OFFCONTRACTPERCENT);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for OFF_CONTRACT_PERCENT using the alias name OffContractPercent
   */
  public void setOffContractPercent(Number value)
  {
    setAttributeInternal(OFFCONTRACTPERCENT, value);
  }

  /**
   * 
   * Gets the attribute value for OFF_WHOLESALE_CODE using the alias name OffWholesaleCode
   */
  public String getOffWholesaleCode()
  {
    return (String)getAttributeInternal(OFFWHOLESALECODE);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for OFF_WHOLESALE_CODE using the alias name OffWholesaleCode
   */
  public void setOffWholesaleCode(String value)
  {
    setAttributeInternal(OFFWHOLESALECODE, value);
  }

  /**
   * 
   * Gets the attribute value for OFF_WHOLESALE_PERCENT using the alias name OffWholesalePercent
   */
  public Number getOffWholesalePercent()
  {
    return (Number)getAttributeInternal(OFFWHOLESALEPERCENT);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for OFF_WHOLESALE_PERCENT using the alias name OffWholesalePercent
   */
  public void setOffWholesalePercent(Number value)
  {
    setAttributeInternal(OFFWHOLESALEPERCENT, value);
  }

  /**
   * 
   * Gets the attribute value for GP_FLOOR_PERCENT using the alias name GpFloorPercent
   */
  public Number getGpFloorPercent()
  {
    return (Number)getAttributeInternal(GPFLOORPERCENT);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for GP_FLOOR_PERCENT using the alias name GpFloorPercent
   */
  public void setGpFloorPercent(Number value)
  {
    setAttributeInternal(GPFLOORPERCENT, value);
  }

  /**
   * 
   * Gets the attribute value for FREIGHT_CHARGE using the alias name FreightCharge
   */
  public String getFreightCharge()
  {
    return (String)getAttributeInternal(FREIGHTCHARGE);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for FREIGHT_CHARGE using the alias name FreightCharge
   */
  public void setFreightCharge(String value)
  {
    setAttributeInternal(FREIGHTCHARGE, value);
  }

  /**
   * 
   * Gets the attribute value for PARENT_ID using the alias name ParentId
   */
  public String getParentId()
  {
    return (String)getAttributeInternal(PARENTID);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for PARENT_ID using the alias name ParentId
   */
  public void setParentId(String value)
  {
    setAttributeInternal(PARENTID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Rev
   */
  public String getRev()
  {
    return (String)getAttributeInternal(REV);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Rev
   */
  public void setRev(String value)
  {
    setAttributeInternal(REV, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute TemplateLockedFlag
   */
  public String getTemplateLockedFlag()
  {
    return (String)getAttributeInternal(TEMPLATELOCKEDFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute TemplateLockedFlag
   */
  public void setTemplateLockedFlag(String value)
  {
    setAttributeInternal(TEMPLATELOCKEDFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute PriceplanLockedFlag
   */
  public String getPriceplanLockedFlag()
  {
    return (String)getAttributeInternal(PRICEPLANLOCKEDFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute PriceplanLockedFlag
   */
  public void setPriceplanLockedFlag(String value)
  {
    setAttributeInternal(PRICEPLANLOCKEDFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute AssncontrLockedFlag
   */
  public String getAssncontrLockedFlag()
  {
    return (String)getAttributeInternal(ASSNCONTRLOCKEDFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute AssncontrLockedFlag
   */
  public void setAssncontrLockedFlag(String value)
  {
    setAttributeInternal(ASSNCONTRLOCKEDFLAG, value);
  }

  /**
   * 
   * Gets the associated <code>RowIterator</code> using master-detail link ODCdhContractProgCodesVO
   */
  public oracle.jbo.RowIterator getODCdhContractProgCodesVO()
  {
    return (oracle.jbo.RowIterator)getAttributeInternal(ODCDHCONTRACTPROGCODESVO);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute PriceplanMandatoryFlag
   */
  public String getPriceplanMandatoryFlag()
  {
    return (String)getAttributeInternal(PRICEPLANMANDATORYFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute PriceplanMandatoryFlag
   */
  public void setPriceplanMandatoryFlag(String value)
  {
    setAttributeInternal(PRICEPLANMANDATORYFLAG, value);
  }





}