<definitions
     name="Dummy_OAGIS"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/Dummy_OAGIS/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/Dummy_OAGIS/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:imp1="http://www.openapplications.org/oagis/9"
     xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/ftp/"
    >
    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/" location="ftpAdapterInboundHeader.wsdl"/>
    <import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://www.openapplications.org/oagis/9" schemaLocation="http://chilsoa01d.na.odcorp.net:7778/orabpel/xmllib/eaixml/oagis/v91/message/bod/PostJournalEntry.xsd" />
      </schema>       
    </types>
    <message name="PostJournalEntry_msg">
        <part name="PostJournalEntry" element="imp1:PostJournalEntry"/>
    </message>
    <portType name="Get_ptt">
        <operation name="Get">
            <input message="tns:PostJournalEntry_msg"/>
        </operation>
    </portType>
    <binding name="Get_binding" type="tns:Get_ptt">
    <pc:inbound_binding  />
        <operation name="Get">
      <jca:operation
          FileType="ascii"
          PhysicalDirectory="DUMMY"
          ActivationSpec="oracle.tip.adapter.ftp.inbound.FTPActivationSpec"
          DeleteFile="true"
          IncludeFiles="DUMMY"
          PollingFrequency="60"
          MinimumAge="0"
          OpaqueSchema="false" >
      </jca:operation>
      <input>
        <jca:header message="hdr:InboundHeader_msg" part="inboundHeader"/>
      </input>
        </operation>
    </binding>
    <service name="Dummy_OAGIS">
        <port name="Get_pt" binding="tns:Get_binding">
      <jca:address location="eis/Ftp/FtpAdapter" UIincludeWildcard="DUMMY" />
        </port>
    </service>
  <plt:partnerLinkType name="Get_plt" >
    <plt:role name="Get_role" >
      <plt:portType name="tns:Get_ptt" />
    </plt:role>
  </plt:partnerLinkType>
</definitions>
