package od.oracle.apps.xxmer.plmpjrdashboard.server;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class OD_MyAssignmentsVORowImpl extends OAViewRowImpl 
{




  protected static final int PROJECTID = 0;
  protected static final int PROJNAME = 1;
  protected static final int PROJNUMBER = 2;
  protected static final int TASKID = 3;
  protected static final int TASKNAME = 4;
  protected static final int TASKNUMBER = 5;
  protected static final int TASKSTATUS = 6;
  protected static final int SCHEDULEDSTARTDATE = 7;
  protected static final int SCHEDULEDFINISHDATE = 8;
  protected static final int PARENTTASKID = 9;
  protected static final int DEPARTMENT = 10;
  protected static final int CLASS1 = 11;
  protected static final int DIVISION = 12;
  protected static final int TASKMANAGERPERSONID = 13;
  protected static final int SELECTCHECKBOX = 14;
  protected static final int NOTES = 15;
  protected static final int TASKGROUP = 16;
  protected static final int STATUSFLAG = 17;
  protected static final int ACTUALFINISHDATE = 18;
  protected static final int OWNERNAME = 19;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public OD_MyAssignmentsVORowImpl()
  {
  }
























  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case PROJECTID:
        return getProjectId();
      case PROJNAME:
        return getProjName();
      case PROJNUMBER:
        return getProjNumber();
      case TASKID:
        return getTaskId();
      case TASKNAME:
        return getTaskName();
      case TASKNUMBER:
        return getTaskNumber();
      case TASKSTATUS:
        return getTaskStatus();
      case SCHEDULEDSTARTDATE:
        return getScheduledStartDate();
      case SCHEDULEDFINISHDATE:
        return getScheduledFinishDate();
      case PARENTTASKID:
        return getParentTaskId();
      case DEPARTMENT:
        return getDepartment();
      case CLASS1:
        return getClass1();
      case DIVISION:
        return getDivision();
      case TASKMANAGERPERSONID:
        return getTaskManagerPersonId();
      case SELECTCHECKBOX:
        return getSelectCheckbox();
      case NOTES:
        return getNotes();
      case TASKGROUP:
        return getTaskGroup();
      case STATUSFLAG:
        return getStatusflag();
      case ACTUALFINISHDATE:
        return getActualFinishDate();
      case OWNERNAME:
        return getOwnerName();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case SELECTCHECKBOX:
        setSelectCheckbox((String)value);
        return;
      case TASKGROUP:
        setTaskGroup((String)value);
        return;
      case STATUSFLAG:
        setStatusflag((String)value);
        return;
      case ACTUALFINISHDATE:
        setActualFinishDate((Date)value);
        return;
      case OWNERNAME:
        setOwnerName((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ProjectId
   */
  public String getProjectId()
  {
    return (String)getAttributeInternal(PROJECTID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ProjectId
   */
  public void setProjectId(String value)
  {
    setAttributeInternal(PROJECTID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ProjName
   */
  public String getProjName()
  {
    return (String)getAttributeInternal(PROJNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ProjName
   */
  public void setProjName(String value)
  {
    setAttributeInternal(PROJNAME, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ProjNumber
   */
  public String getProjNumber()
  {
    return (String)getAttributeInternal(PROJNUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ProjNumber
   */
  public void setProjNumber(String value)
  {
    setAttributeInternal(PROJNUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute TaskId
   */
  public String getTaskId()
  {
    return (String)getAttributeInternal(TASKID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute TaskId
   */
  public void setTaskId(String value)
  {
    setAttributeInternal(TASKID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute TaskNumber
   */
  public String getTaskNumber()
  {
    return (String)getAttributeInternal(TASKNUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute TaskNumber
   */
  public void setTaskNumber(String value)
  {
    setAttributeInternal(TASKNUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute TaskStatus
   */
  public String getTaskStatus()
  {
    return (String)getAttributeInternal(TASKSTATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute TaskStatus
   */
  public void setTaskStatus(String value)
  {
    setAttributeInternal(TASKSTATUS, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ScheduledFinishDate
   */
  public String getScheduledFinishDate()
  {
    return (String)getAttributeInternal(SCHEDULEDFINISHDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ScheduledFinishDate
   */
  public void setScheduledFinishDate(String value)
  {
    setAttributeInternal(SCHEDULEDFINISHDATE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ParentTaskId
   */
  public String getParentTaskId()
  {
    return (String)getAttributeInternal(PARENTTASKID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ParentTaskId
   */
  public void setParentTaskId(String value)
  {
    setAttributeInternal(PARENTTASKID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Department
   */
  public String getDepartment()
  {
    return (String)getAttributeInternal(DEPARTMENT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Department
   */
  public void setDepartment(String value)
  {
    setAttributeInternal(DEPARTMENT, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Class1
   */
  public String getClass1()
  {
    return (String)getAttributeInternal(CLASS1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Class1
   */
  public void setClass1(String value)
  {
    setAttributeInternal(CLASS1, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Division
   */
  public String getDivision()
  {
    return (String)getAttributeInternal(DIVISION);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Division
   */
  public void setDivision(String value)
  {
    setAttributeInternal(DIVISION, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute TaskManagerPersonId
   */
  public String getTaskManagerPersonId()
  {
    return (String)getAttributeInternal(TASKMANAGERPERSONID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute TaskManagerPersonId
   */
  public void setTaskManagerPersonId(String value)
  {
    setAttributeInternal(TASKMANAGERPERSONID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute TaskName
   */
  public String getTaskName()
  {
    return (String)getAttributeInternal(TASKNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute TaskName
   */
  public void setTaskName(String value)
  {
    setAttributeInternal(TASKNAME, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ScheduledStartDate
   */
  public String getScheduledStartDate()
  {
    return (String)getAttributeInternal(SCHEDULEDSTARTDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ScheduledStartDate
   */
  public void setScheduledStartDate(String value)
  {
    setAttributeInternal(SCHEDULEDSTARTDATE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute SelectCheckbox
   */
  public String getSelectCheckbox()
  {
    return (String)getAttributeInternal(SELECTCHECKBOX);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute SelectCheckbox
   */
  public void setSelectCheckbox(String value)
  {
    setAttributeInternal(SELECTCHECKBOX, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Notes
   */
  public String getNotes()
  {
    return (String)getAttributeInternal(NOTES);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Notes
   */
  public void setNotes(String value)
  {
    setAttributeInternal(NOTES, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute TaskGroup
   */
  public String getTaskGroup()
  {
    return (String)getAttributeInternal(TASKGROUP);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute TaskGroup
   */
  public void setTaskGroup(String value)
  {
    setAttributeInternal(TASKGROUP, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Statusflag
   */
  public String getStatusflag()
  {
    return (String)getAttributeInternal(STATUSFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Statusflag
   */
  public void setStatusflag(String value)
  {
    setAttributeInternal(STATUSFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ActualFinishDate
   */
  public Date getActualFinishDate()
  {
    return (Date)getAttributeInternal(ACTUALFINISHDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ActualFinishDate
   */
  public void setActualFinishDate(Date value)
  {
    setAttributeInternal(ACTUALFINISHDATE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute OwnerName
   */
  public String getOwnerName()
  {
    return (String)getAttributeInternal(OWNERNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute OwnerName
   */
  public void setOwnerName(String value)
  {
    setAttributeInternal(OWNERNAME, value);
  }







}