package od.oracle.apps.xxmer.xxGsoPlmPOTracking.server;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.AttributeList;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class xxPODtl_shipNinsp_EOImpl extends OAEntityImpl 
{
  protected static final int POHEADERID = 0;
  protected static final int POLINEID = 1;
  protected static final int POLINENO = 2;
  protected static final int LINESTATUS = 3;
  protected static final int BVSTATUS = 4;
  protected static final int ITEM = 5;
  protected static final int DESCRIPTION = 6;
  protected static final int UOM = 7;
  protected static final int VPC = 8;
  protected static final int CATEGORY = 9;
  protected static final int ODMERCHANT = 10;
  protected static final int DIVISION = 11;
  protected static final int DEPT = 12;
  protected static final int CLASS1 = 13;
  protected static final int ORDEREDQTY = 14;
  protected static final int SHIPMENTDATE = 15;
  protected static final int BATCHID = 16;
  protected static final int STDPACK = 17;
  protected static final int CARTONPACK = 18;
  protected static final int CARTONCUBE = 19;
  protected static final int CARTONWEIGHT = 20;
  protected static final int MASTERCARTON = 21;
  protected static final int RETAILCOST = 22;
  protected static final int MASTERFOBCOST = 23;
  protected static final int FOBORIGINCOST = 24;
  protected static final int ESTLANDCOST = 25;
  protected static final int ACTLANDCOST = 26;
  protected static final int MERCHDECCOST = 27;
  protected static final int SOURCEPORTNAME = 28;
  protected static final int DESTNPORTNAME = 29;
  protected static final int ORIGINALPOSHIPDATE = 30;
  protected static final int CHANGEDPOSHIPDATE = 31;
  protected static final int REASONCODE = 32;
  protected static final int REMARKS = 33;
  protected static final int PARTIALLINEFLAG = 34;
  protected static final int LATESTLINEFLAG = 35;
  protected static final int NEWITEMFLAG = 36;
  protected static final int OVERSHIPPEDFLAG = 37;
  protected static final int LATESHIPMENTALERT = 38;
  protected static final int KNBOOKINGALERT = 39;
  protected static final int KNRECEIVINGALERT = 40;
  protected static final int BVBOOKINGALERT = 41;
  protected static final int INSPBOOKALERT = 42;
  protected static final int ATTRIBUTE1 = 43;
  protected static final int ATTRIBUTE2 = 44;
  protected static final int ATTRIBUTE3 = 45;
  protected static final int ATTRIBUTE4 = 46;
  protected static final int ATTRIBUTE5 = 47;
  protected static final int ATTRIBUTE6 = 48;
  protected static final int ATTRIBUTE7 = 49;
  protected static final int ATTRIBUTE8 = 50;
  protected static final int ATTRIBUTE9 = 51;
  protected static final int ATTRIBUTE10 = 52;
  protected static final int ATTRIBUTE11 = 53;
  protected static final int ATTRIBUTE12 = 54;
  protected static final int ATTRIBUTE13 = 55;
  protected static final int ATTRIBUTE14 = 56;
  protected static final int ATTRIBUTE15 = 57;
  protected static final int CREATIONDATE = 58;
  protected static final int CREATEDBY = 59;
  protected static final int LASTUPDATEDATE = 60;
  protected static final int LASTUPDATEDBY = 61;
  protected static final int LASTUPDATELOGIN = 62;
  protected static final int FOBUSDCOST = 63;
  protected static final int INSPQTY = 64;
  protected static final int SHIPPEDQTY = 65;
  protected static final int BVCODE = 66;
  protected static final int BVREASON = 67;
  protected static final int GSODEPTID = 68;
  protected static final int ORIGIN = 69;
  protected static final int NBFLAG = 70;
  protected static final int INLINEFLAG = 71;
  protected static final int SAFETYSTOCKFLAG = 72;
  protected static final int BVFLAG = 73;
  protected static final int FIRSTSHIPMENTFLAG = 74;
  protected static final int BOOKEDQTY = 75;
  protected static final int RECEIVEDQTY = 76;
  protected static final int GSOMO = 77;
  protected static final int DELAYCODE = 78;
  protected static final int DELAYREASON = 79;
  protected static final int DIFFPRICE = 80;
  protected static final int SHIPMENTSTATUS = 81;
  protected static final int LINETOTAL = 82;


  private static oracle.apps.fnd.framework.server.OAEntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public xxPODtl_shipNinsp_EOImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (oracle.apps.fnd.framework.server.OAEntityDefImpl)EntityDefImpl.findDefObject("od.oracle.apps.xxmer.xxGsoPlmPOTracking.server.xxPODtl_shipNinsp_EO");
    }
    return mDefinitionObject;
  }



  /**
   * 
   * Add attribute defaulting logic in this method.
   */
  public void create(AttributeList attributeList)
  {
    super.create(attributeList);
  }

  /**
   * 
   * Add entity remove logic in this method.
   */
  public void remove()
  {
    super.remove();
  }

  /**
   * 
   * Add Entity validation code in this method.
   */
  protected void validateEntity()
  {
    super.validateEntity();
  }

  /**
   * 
   * Add locking logic here.
   */
  public void lock()
  {
    super.lock();
  }

  /**
   * 
   * Custom DML update/insert/delete logic here.
   */
  protected void doDML(int operation, TransactionEvent e)
  {
    super.doDML(operation, e);
  }

  /**
   * 
   * Gets the attribute value for PoHeaderId, using the alias name PoHeaderId
   */
  public Number getPoHeaderId()
  {
    return (Number)getAttributeInternal(POHEADERID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PoHeaderId
   */
  public void setPoHeaderId(Number value)
  {
    setAttributeInternal(POHEADERID, value);
  }

  /**
   * 
   * Gets the attribute value for PoLineId, using the alias name PoLineId
   */
  public Number getPoLineId()
  {
    return (Number)getAttributeInternal(POLINEID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PoLineId
   */
  public void setPoLineId(Number value)
  {
    setAttributeInternal(POLINEID, value);
  }

  /**
   * 
   * Gets the attribute value for PoLineNo, using the alias name PoLineNo
   */
  public Number getPoLineNo()
  {
    return (Number)getAttributeInternal(POLINENO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PoLineNo
   */
  public void setPoLineNo(Number value)
  {
    setAttributeInternal(POLINENO, value);
  }

  /**
   * 
   * Gets the attribute value for LineStatus, using the alias name LineStatus
   */
  public String getLineStatus()
  {
    return (String)getAttributeInternal(LINESTATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LineStatus
   */
  public void setLineStatus(String value)
  {
    setAttributeInternal(LINESTATUS, value);
  }

  /**
   * 
   * Gets the attribute value for BvStatus, using the alias name BvStatus
   */
  public String getBvStatus()
  {
    return (String)getAttributeInternal(BVSTATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BvStatus
   */
  public void setBvStatus(String value)
  {
    setAttributeInternal(BVSTATUS, value);
  }

  /**
   * 
   * Gets the attribute value for Item, using the alias name Item
   */
  public String getItem()
  {
    return (String)getAttributeInternal(ITEM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Item
   */
  public void setItem(String value)
  {
    setAttributeInternal(ITEM, value);
  }

  /**
   * 
   * Gets the attribute value for Description, using the alias name Description
   */
  public String getDescription()
  {
    return (String)getAttributeInternal(DESCRIPTION);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Description
   */
  public void setDescription(String value)
  {
    setAttributeInternal(DESCRIPTION, value);
  }

  /**
   * 
   * Gets the attribute value for Uom, using the alias name Uom
   */
  public String getUom()
  {
    return (String)getAttributeInternal(UOM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Uom
   */
  public void setUom(String value)
  {
    setAttributeInternal(UOM, value);
  }

  /**
   * 
   * Gets the attribute value for Vpc, using the alias name Vpc
   */
  public String getVpc()
  {
    return (String)getAttributeInternal(VPC);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Vpc
   */
  public void setVpc(String value)
  {
    setAttributeInternal(VPC, value);
  }

  /**
   * 
   * Gets the attribute value for Category, using the alias name Category
   */
  public String getCategory()
  {
    return (String)getAttributeInternal(CATEGORY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Category
   */
  public void setCategory(String value)
  {
    setAttributeInternal(CATEGORY, value);
  }

  /**
   * 
   * Gets the attribute value for OdMerchant, using the alias name OdMerchant
   */
  public String getOdMerchant()
  {
    return (String)getAttributeInternal(ODMERCHANT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for OdMerchant
   */
  public void setOdMerchant(String value)
  {
    setAttributeInternal(ODMERCHANT, value);
  }

  /**
   * 
   * Gets the attribute value for Division, using the alias name Division
   */
  public Number getDivision()
  {
    return (Number)getAttributeInternal(DIVISION);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Division
   */
  public void setDivision(Number value)
  {
    setAttributeInternal(DIVISION, value);
  }

  /**
   * 
   * Gets the attribute value for Dept, using the alias name Dept
   */
  public Number getDept()
  {
    return (Number)getAttributeInternal(DEPT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Dept
   */
  public void setDept(Number value)
  {
    setAttributeInternal(DEPT, value);
  }

  /**
   * 
   * Gets the attribute value for Class1, using the alias name Class1
   */
  public Number getClass1()
  {
    return (Number)getAttributeInternal(CLASS1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Class1
   */
  public void setClass1(Number value)
  {
    setAttributeInternal(CLASS1, value);
  }

  /**
   * 
   * Gets the attribute value for OrderedQty, using the alias name OrderedQty
   */
  public Number getOrderedQty()
  {
    return (Number)getAttributeInternal(ORDEREDQTY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for OrderedQty
   */
  public void setOrderedQty(Number value)
  {
    setAttributeInternal(ORDEREDQTY, value);
  }

  /**
   * 
   * Gets the attribute value for ShipmentDate, using the alias name ShipmentDate
   */
  public Date getShipmentDate()
  {
    return (Date)getAttributeInternal(SHIPMENTDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ShipmentDate
   */
  public void setShipmentDate(Date value)
  {
    setAttributeInternal(SHIPMENTDATE, value);
  }

  /**
   * 
   * Gets the attribute value for BatchId, using the alias name BatchId
   */
  public Number getBatchId()
  {
    return (Number)getAttributeInternal(BATCHID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BatchId
   */
  public void setBatchId(Number value)
  {
    setAttributeInternal(BATCHID, value);
  }

  /**
   * 
   * Gets the attribute value for StdPack, using the alias name StdPack
   */
  public Number getStdPack()
  {
    return (Number)getAttributeInternal(STDPACK);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for StdPack
   */
  public void setStdPack(Number value)
  {
    setAttributeInternal(STDPACK, value);
  }

  /**
   * 
   * Gets the attribute value for CartonPack, using the alias name CartonPack
   */
  public Number getCartonPack()
  {
    return (Number)getAttributeInternal(CARTONPACK);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CartonPack
   */
  public void setCartonPack(Number value)
  {
    setAttributeInternal(CARTONPACK, value);
  }

  /**
   * 
   * Gets the attribute value for CartonCube, using the alias name CartonCube
   */
  public Number getCartonCube()
  {
    return (Number)getAttributeInternal(CARTONCUBE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CartonCube
   */
  public void setCartonCube(Number value)
  {
    setAttributeInternal(CARTONCUBE, value);
  }

  /**
   * 
   * Gets the attribute value for CartonWeight, using the alias name CartonWeight
   */
  public Number getCartonWeight()
  {
    return (Number)getAttributeInternal(CARTONWEIGHT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CartonWeight
   */
  public void setCartonWeight(Number value)
  {
    setAttributeInternal(CARTONWEIGHT, value);
  }

  /**
   * 
   * Gets the attribute value for MasterCarton, using the alias name MasterCarton
   */
  public Number getMasterCarton()
  {
    return (Number)getAttributeInternal(MASTERCARTON);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for MasterCarton
   */
  public void setMasterCarton(Number value)
  {
    setAttributeInternal(MASTERCARTON, value);
  }

  /**
   * 
   * Gets the attribute value for RetailCost, using the alias name RetailCost
   */
  public Number getRetailCost()
  {
    return (Number)getAttributeInternal(RETAILCOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RetailCost
   */
  public void setRetailCost(Number value)
  {
    setAttributeInternal(RETAILCOST, value);
  }

  /**
   * 
   * Gets the attribute value for MasterFobCost, using the alias name MasterFobCost
   */
  public Number getMasterFobCost()
  {
    return (Number)getAttributeInternal(MASTERFOBCOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for MasterFobCost
   */
  public void setMasterFobCost(Number value)
  {
    setAttributeInternal(MASTERFOBCOST, value);
  }

  /**
   * 
   * Gets the attribute value for FobOriginCost, using the alias name FobOriginCost
   */
  public Number getFobOriginCost()
  {
    return (Number)getAttributeInternal(FOBORIGINCOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for FobOriginCost
   */
  public void setFobOriginCost(Number value)
  {
    setAttributeInternal(FOBORIGINCOST, value);
  }

  /**
   * 
   * Gets the attribute value for EstLandCost, using the alias name EstLandCost
   */
  public Number getEstLandCost()
  {
    return (Number)getAttributeInternal(ESTLANDCOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for EstLandCost
   */
  public void setEstLandCost(Number value)
  {
    setAttributeInternal(ESTLANDCOST, value);
  }

  /**
   * 
   * Gets the attribute value for ActLandCost, using the alias name ActLandCost
   */
  public Number getActLandCost()
  {
    return (Number)getAttributeInternal(ACTLANDCOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ActLandCost
   */
  public void setActLandCost(Number value)
  {
    setAttributeInternal(ACTLANDCOST, value);
  }

  /**
   * 
   * Gets the attribute value for MerchDecCost, using the alias name MerchDecCost
   */
  public Number getMerchDecCost()
  {
    return (Number)getAttributeInternal(MERCHDECCOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for MerchDecCost
   */
  public void setMerchDecCost(Number value)
  {
    setAttributeInternal(MERCHDECCOST, value);
  }

  /**
   * 
   * Gets the attribute value for SourcePortName, using the alias name SourcePortName
   */
  public String getSourcePortName()
  {
    return (String)getAttributeInternal(SOURCEPORTNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SourcePortName
   */
  public void setSourcePortName(String value)
  {
    setAttributeInternal(SOURCEPORTNAME, value);
  }

  /**
   * 
   * Gets the attribute value for DestnPortName, using the alias name DestnPortName
   */
  public String getDestnPortName()
  {
    return (String)getAttributeInternal(DESTNPORTNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DestnPortName
   */
  public void setDestnPortName(String value)
  {
    setAttributeInternal(DESTNPORTNAME, value);
  }

  /**
   * 
   * Gets the attribute value for OriginalPoShipdate, using the alias name OriginalPoShipdate
   */
  public Date getOriginalPoShipdate()
  {
    return (Date)getAttributeInternal(ORIGINALPOSHIPDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for OriginalPoShipdate
   */
  public void setOriginalPoShipdate(Date value)
  {
    setAttributeInternal(ORIGINALPOSHIPDATE, value);
  }

  /**
   * 
   * Gets the attribute value for ChangedPoShipdate, using the alias name ChangedPoShipdate
   */
  public Date getChangedPoShipdate()
  {
    return (Date)getAttributeInternal(CHANGEDPOSHIPDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ChangedPoShipdate
   */
  public void setChangedPoShipdate(Date value)
  {
    setAttributeInternal(CHANGEDPOSHIPDATE, value);
  }

  /**
   * 
   * Gets the attribute value for ReasonCode, using the alias name ReasonCode
   */
  public String getReasonCode()
  {
    return (String)getAttributeInternal(REASONCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ReasonCode
   */
  public void setReasonCode(String value)
  {
    setAttributeInternal(REASONCODE, value);
  }

  /**
   * 
   * Gets the attribute value for Remarks, using the alias name Remarks
   */
  public String getRemarks()
  {
    return (String)getAttributeInternal(REMARKS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Remarks
   */
  public void setRemarks(String value)
  {
    setAttributeInternal(REMARKS, value);
  }

  /**
   * 
   * Gets the attribute value for PartialLineFlag, using the alias name PartialLineFlag
   */
  public String getPartialLineFlag()
  {
    return (String)getAttributeInternal(PARTIALLINEFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PartialLineFlag
   */
  public void setPartialLineFlag(String value)
  {
    setAttributeInternal(PARTIALLINEFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for LatestLineFlag, using the alias name LatestLineFlag
   */
  public String getLatestLineFlag()
  {
    return (String)getAttributeInternal(LATESTLINEFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LatestLineFlag
   */
  public void setLatestLineFlag(String value)
  {
    setAttributeInternal(LATESTLINEFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for NewItemFlag, using the alias name NewItemFlag
   */
  public String getNewItemFlag()
  {
    return (String)getAttributeInternal(NEWITEMFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NewItemFlag
   */
  public void setNewItemFlag(String value)
  {
    setAttributeInternal(NEWITEMFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for OverShippedFlag, using the alias name OverShippedFlag
   */
  public String getOverShippedFlag()
  {
    return (String)getAttributeInternal(OVERSHIPPEDFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for OverShippedFlag
   */
  public void setOverShippedFlag(String value)
  {
    setAttributeInternal(OVERSHIPPEDFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for LateShipmentAlert, using the alias name LateShipmentAlert
   */
  public String getLateShipmentAlert()
  {
    return (String)getAttributeInternal(LATESHIPMENTALERT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LateShipmentAlert
   */
  public void setLateShipmentAlert(String value)
  {
    setAttributeInternal(LATESHIPMENTALERT, value);
  }

  /**
   * 
   * Gets the attribute value for KnBookingAlert, using the alias name KnBookingAlert
   */
  public String getKnBookingAlert()
  {
    return (String)getAttributeInternal(KNBOOKINGALERT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for KnBookingAlert
   */
  public void setKnBookingAlert(String value)
  {
    setAttributeInternal(KNBOOKINGALERT, value);
  }

  /**
   * 
   * Gets the attribute value for KnReceivingAlert, using the alias name KnReceivingAlert
   */
  public String getKnReceivingAlert()
  {
    return (String)getAttributeInternal(KNRECEIVINGALERT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for KnReceivingAlert
   */
  public void setKnReceivingAlert(String value)
  {
    setAttributeInternal(KNRECEIVINGALERT, value);
  }

  /**
   * 
   * Gets the attribute value for BvBookingAlert, using the alias name BvBookingAlert
   */
  public String getBvBookingAlert()
  {
    return (String)getAttributeInternal(BVBOOKINGALERT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BvBookingAlert
   */
  public void setBvBookingAlert(String value)
  {
    setAttributeInternal(BVBOOKINGALERT, value);
  }

  /**
   * 
   * Gets the attribute value for InspBookAlert, using the alias name InspBookAlert
   */
  public String getInspBookAlert()
  {
    return (String)getAttributeInternal(INSPBOOKALERT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for InspBookAlert
   */
  public void setInspBookAlert(String value)
  {
    setAttributeInternal(INSPBOOKALERT, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute1, using the alias name Attribute1
   */
  public String getAttribute1()
  {
    return (String)getAttributeInternal(ATTRIBUTE1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute1
   */
  public void setAttribute1(String value)
  {
    setAttributeInternal(ATTRIBUTE1, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute2, using the alias name Attribute2
   */
  public String getAttribute2()
  {
    return (String)getAttributeInternal(ATTRIBUTE2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute2
   */
  public void setAttribute2(String value)
  {
    setAttributeInternal(ATTRIBUTE2, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute3, using the alias name Attribute3
   */
  public String getAttribute3()
  {
    return (String)getAttributeInternal(ATTRIBUTE3);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute3
   */
  public void setAttribute3(String value)
  {
    setAttributeInternal(ATTRIBUTE3, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute4, using the alias name Attribute4
   */
  public String getAttribute4()
  {
    return (String)getAttributeInternal(ATTRIBUTE4);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute4
   */
  public void setAttribute4(String value)
  {
    setAttributeInternal(ATTRIBUTE4, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute5, using the alias name Attribute5
   */
  public String getAttribute5()
  {
    return (String)getAttributeInternal(ATTRIBUTE5);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute5
   */
  public void setAttribute5(String value)
  {
    setAttributeInternal(ATTRIBUTE5, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute6, using the alias name Attribute6
   */
  public String getAttribute6()
  {
    return (String)getAttributeInternal(ATTRIBUTE6);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute6
   */
  public void setAttribute6(String value)
  {
    setAttributeInternal(ATTRIBUTE6, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute7, using the alias name Attribute7
   */
  public String getAttribute7()
  {
    return (String)getAttributeInternal(ATTRIBUTE7);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute7
   */
  public void setAttribute7(String value)
  {
    setAttributeInternal(ATTRIBUTE7, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute8, using the alias name Attribute8
   */
  public String getAttribute8()
  {
    return (String)getAttributeInternal(ATTRIBUTE8);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute8
   */
  public void setAttribute8(String value)
  {
    setAttributeInternal(ATTRIBUTE8, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute9, using the alias name Attribute9
   */
  public String getAttribute9()
  {
    return (String)getAttributeInternal(ATTRIBUTE9);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute9
   */
  public void setAttribute9(String value)
  {
    setAttributeInternal(ATTRIBUTE9, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute10, using the alias name Attribute10
   */
  public String getAttribute10()
  {
    return (String)getAttributeInternal(ATTRIBUTE10);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute10
   */
  public void setAttribute10(String value)
  {
    setAttributeInternal(ATTRIBUTE10, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute11, using the alias name Attribute11
   */
  public String getAttribute11()
  {
    return (String)getAttributeInternal(ATTRIBUTE11);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute11
   */
  public void setAttribute11(String value)
  {
    setAttributeInternal(ATTRIBUTE11, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute12, using the alias name Attribute12
   */
  public String getAttribute12()
  {
    return (String)getAttributeInternal(ATTRIBUTE12);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute12
   */
  public void setAttribute12(String value)
  {
    setAttributeInternal(ATTRIBUTE12, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute13, using the alias name Attribute13
   */
  public String getAttribute13()
  {
    return (String)getAttributeInternal(ATTRIBUTE13);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute13
   */
  public void setAttribute13(String value)
  {
    setAttributeInternal(ATTRIBUTE13, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute14, using the alias name Attribute14
   */
  public String getAttribute14()
  {
    return (String)getAttributeInternal(ATTRIBUTE14);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute14
   */
  public void setAttribute14(String value)
  {
    setAttributeInternal(ATTRIBUTE14, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute15, using the alias name Attribute15
   */
  public String getAttribute15()
  {
    return (String)getAttributeInternal(ATTRIBUTE15);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute15
   */
  public void setAttribute15(String value)
  {
    setAttributeInternal(ATTRIBUTE15, value);
  }

  /**
   * 
   * Gets the attribute value for CreationDate, using the alias name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * 
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin()
  {
    return (Number)getAttributeInternal(LASTUPDATELOGIN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value)
  {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**
   * 
   * Gets the attribute value for FobUsdCost, using the alias name FobUsdCost
   */
  public Number getFobUsdCost()
  {
    return (Number)getAttributeInternal(FOBUSDCOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for FobUsdCost
   */
  public void setFobUsdCost(Number value)
  {
    setAttributeInternal(FOBUSDCOST, value);
  }

  /**
   * 
   * Gets the attribute value for InspQty, using the alias name InspQty
   */
  public Number getInspQty()
  {
    return (Number)getAttributeInternal(INSPQTY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for InspQty
   */
  public void setInspQty(Number value)
  {
    setAttributeInternal(INSPQTY, value);
  }

  /**
   * 
   * Gets the attribute value for ShippedQty, using the alias name ShippedQty
   */
  public Number getShippedQty()
  {
    return (Number)getAttributeInternal(SHIPPEDQTY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ShippedQty
   */
  public void setShippedQty(Number value)
  {
    setAttributeInternal(SHIPPEDQTY, value);
  }

  /**
   * 
   * Gets the attribute value for BvCode, using the alias name BvCode
   */
  public String getBvCode()
  {
    return (String)getAttributeInternal(BVCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BvCode
   */
  public void setBvCode(String value)
  {
    setAttributeInternal(BVCODE, value);
  }

  /**
   * 
   * Gets the attribute value for BvReason, using the alias name BvReason
   */
  public String getBvReason()
  {
    return (String)getAttributeInternal(BVREASON);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BvReason
   */
  public void setBvReason(String value)
  {
    setAttributeInternal(BVREASON, value);
  }

  /**
   * 
   * Gets the attribute value for GsoDeptId, using the alias name GsoDeptId
   */
  public Number getGsoDeptId()
  {
    return (Number)getAttributeInternal(GSODEPTID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for GsoDeptId
   */
  public void setGsoDeptId(Number value)
  {
    setAttributeInternal(GSODEPTID, value);
  }

  /**
   * 
   * Gets the attribute value for Origin, using the alias name Origin
   */
  public String getOrigin()
  {
    return (String)getAttributeInternal(ORIGIN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Origin
   */
  public void setOrigin(String value)
  {
    setAttributeInternal(ORIGIN, value);
  }

  /**
   * 
   * Gets the attribute value for NbFlag, using the alias name NbFlag
   */
  public String getNbFlag()
  {
    return (String)getAttributeInternal(NBFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NbFlag
   */
  public void setNbFlag(String value)
  {
    setAttributeInternal(NBFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for InlineFlag, using the alias name InlineFlag
   */
  public String getInlineFlag()
  {
    return (String)getAttributeInternal(INLINEFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for InlineFlag
   */
  public void setInlineFlag(String value)
  {
    setAttributeInternal(INLINEFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for SafetyStockFlag, using the alias name SafetyStockFlag
   */
  public String getSafetyStockFlag()
  {
    return (String)getAttributeInternal(SAFETYSTOCKFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SafetyStockFlag
   */
  public void setSafetyStockFlag(String value)
  {
    setAttributeInternal(SAFETYSTOCKFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for BvFlag, using the alias name BvFlag
   */
  public String getBvFlag()
  {
    return (String)getAttributeInternal(BVFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BvFlag
   */
  public void setBvFlag(String value)
  {
    setAttributeInternal(BVFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for FirstShipmentFlag, using the alias name FirstShipmentFlag
   */
  public String getFirstShipmentFlag()
  {
    return (String)getAttributeInternal(FIRSTSHIPMENTFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for FirstShipmentFlag
   */
  public void setFirstShipmentFlag(String value)
  {
    setAttributeInternal(FIRSTSHIPMENTFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for BookedQty, using the alias name BookedQty
   */
  public Number getBookedQty()
  {
    return (Number)getAttributeInternal(BOOKEDQTY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BookedQty
   */
  public void setBookedQty(Number value)
  {
    setAttributeInternal(BOOKEDQTY, value);
  }

  /**
   * 
   * Gets the attribute value for ReceivedQty, using the alias name ReceivedQty
   */
  public Number getReceivedQty()
  {
    return (Number)getAttributeInternal(RECEIVEDQTY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ReceivedQty
   */
  public void setReceivedQty(Number value)
  {
    setAttributeInternal(RECEIVEDQTY, value);
  }

  /**
   * 
   * Gets the attribute value for GsoMo, using the alias name GsoMo
   */
  public String getGsoMo()
  {
    return (String)getAttributeInternal(GSOMO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for GsoMo
   */
  public void setGsoMo(String value)
  {
    setAttributeInternal(GSOMO, value);
  }

  /**
   * 
   * Gets the attribute value for DelayCode, using the alias name DelayCode
   */
  public String getDelayCode()
  {
    return (String)getAttributeInternal(DELAYCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DelayCode
   */
  public void setDelayCode(String value)
  {
    setAttributeInternal(DELAYCODE, value);
  }

  /**
   * 
   * Gets the attribute value for DelayReason, using the alias name DelayReason
   */
  public String getDelayReason()
  {
    return (String)getAttributeInternal(DELAYREASON);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DelayReason
   */
  public void setDelayReason(String value)
  {
    setAttributeInternal(DELAYREASON, value);
  }

  /**
   * 
   * Gets the attribute value for DiffPrice, using the alias name DiffPrice
   */
  public String getDiffPrice()
  {
    return (String)getAttributeInternal(DIFFPRICE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DiffPrice
   */
  public void setDiffPrice(String value)
  {
    setAttributeInternal(DIFFPRICE, value);
  }

  /**
   * 
   * Gets the attribute value for ShipmentStatus, using the alias name ShipmentStatus
   */
  public String getShipmentStatus()
  {
    return (String)getAttributeInternal(SHIPMENTSTATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ShipmentStatus
   */
  public void setShipmentStatus(String value)
  {
    setAttributeInternal(SHIPMENTSTATUS, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case POHEADERID:
        return getPoHeaderId();
      case POLINEID:
        return getPoLineId();
      case POLINENO:
        return getPoLineNo();
      case LINESTATUS:
        return getLineStatus();
      case BVSTATUS:
        return getBvStatus();
      case ITEM:
        return getItem();
      case DESCRIPTION:
        return getDescription();
      case UOM:
        return getUom();
      case VPC:
        return getVpc();
      case CATEGORY:
        return getCategory();
      case ODMERCHANT:
        return getOdMerchant();
      case DIVISION:
        return getDivision();
      case DEPT:
        return getDept();
      case CLASS1:
        return getClass1();
      case ORDEREDQTY:
        return getOrderedQty();
      case SHIPMENTDATE:
        return getShipmentDate();
      case BATCHID:
        return getBatchId();
      case STDPACK:
        return getStdPack();
      case CARTONPACK:
        return getCartonPack();
      case CARTONCUBE:
        return getCartonCube();
      case CARTONWEIGHT:
        return getCartonWeight();
      case MASTERCARTON:
        return getMasterCarton();
      case RETAILCOST:
        return getRetailCost();
      case MASTERFOBCOST:
        return getMasterFobCost();
      case FOBORIGINCOST:
        return getFobOriginCost();
      case ESTLANDCOST:
        return getEstLandCost();
      case ACTLANDCOST:
        return getActLandCost();
      case MERCHDECCOST:
        return getMerchDecCost();
      case SOURCEPORTNAME:
        return getSourcePortName();
      case DESTNPORTNAME:
        return getDestnPortName();
      case ORIGINALPOSHIPDATE:
        return getOriginalPoShipdate();
      case CHANGEDPOSHIPDATE:
        return getChangedPoShipdate();
      case REASONCODE:
        return getReasonCode();
      case REMARKS:
        return getRemarks();
      case PARTIALLINEFLAG:
        return getPartialLineFlag();
      case LATESTLINEFLAG:
        return getLatestLineFlag();
      case NEWITEMFLAG:
        return getNewItemFlag();
      case OVERSHIPPEDFLAG:
        return getOverShippedFlag();
      case LATESHIPMENTALERT:
        return getLateShipmentAlert();
      case KNBOOKINGALERT:
        return getKnBookingAlert();
      case KNRECEIVINGALERT:
        return getKnReceivingAlert();
      case BVBOOKINGALERT:
        return getBvBookingAlert();
      case INSPBOOKALERT:
        return getInspBookAlert();
      case ATTRIBUTE1:
        return getAttribute1();
      case ATTRIBUTE2:
        return getAttribute2();
      case ATTRIBUTE3:
        return getAttribute3();
      case ATTRIBUTE4:
        return getAttribute4();
      case ATTRIBUTE5:
        return getAttribute5();
      case ATTRIBUTE6:
        return getAttribute6();
      case ATTRIBUTE7:
        return getAttribute7();
      case ATTRIBUTE8:
        return getAttribute8();
      case ATTRIBUTE9:
        return getAttribute9();
      case ATTRIBUTE10:
        return getAttribute10();
      case ATTRIBUTE11:
        return getAttribute11();
      case ATTRIBUTE12:
        return getAttribute12();
      case ATTRIBUTE13:
        return getAttribute13();
      case ATTRIBUTE14:
        return getAttribute14();
      case ATTRIBUTE15:
        return getAttribute15();
      case CREATIONDATE:
        return getCreationDate();
      case CREATEDBY:
        return getCreatedBy();
      case LASTUPDATEDATE:
        return getLastUpdateDate();
      case LASTUPDATEDBY:
        return getLastUpdatedBy();
      case LASTUPDATELOGIN:
        return getLastUpdateLogin();
      case FOBUSDCOST:
        return getFobUsdCost();
      case INSPQTY:
        return getInspQty();
      case SHIPPEDQTY:
        return getShippedQty();
      case BVCODE:
        return getBvCode();
      case BVREASON:
        return getBvReason();
      case GSODEPTID:
        return getGsoDeptId();
      case ORIGIN:
        return getOrigin();
      case NBFLAG:
        return getNbFlag();
      case INLINEFLAG:
        return getInlineFlag();
      case SAFETYSTOCKFLAG:
        return getSafetyStockFlag();
      case BVFLAG:
        return getBvFlag();
      case FIRSTSHIPMENTFLAG:
        return getFirstShipmentFlag();
      case BOOKEDQTY:
        return getBookedQty();
      case RECEIVEDQTY:
        return getReceivedQty();
      case GSOMO:
        return getGsoMo();
      case DELAYCODE:
        return getDelayCode();
      case DELAYREASON:
        return getDelayReason();
      case DIFFPRICE:
        return getDiffPrice();
      case SHIPMENTSTATUS:
        return getShipmentStatus();
      case LINETOTAL:
        return getLineTotal();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case POHEADERID:
        setPoHeaderId((Number)value);
        return;
      case POLINEID:
        setPoLineId((Number)value);
        return;
      case POLINENO:
        setPoLineNo((Number)value);
        return;
      case LINESTATUS:
        setLineStatus((String)value);
        return;
      case BVSTATUS:
        setBvStatus((String)value);
        return;
      case ITEM:
        setItem((String)value);
        return;
      case DESCRIPTION:
        setDescription((String)value);
        return;
      case UOM:
        setUom((String)value);
        return;
      case VPC:
        setVpc((String)value);
        return;
      case CATEGORY:
        setCategory((String)value);
        return;
      case ODMERCHANT:
        setOdMerchant((String)value);
        return;
      case DIVISION:
        setDivision((Number)value);
        return;
      case DEPT:
        setDept((Number)value);
        return;
      case CLASS1:
        setClass1((Number)value);
        return;
      case ORDEREDQTY:
        setOrderedQty((Number)value);
        return;
      case SHIPMENTDATE:
        setShipmentDate((Date)value);
        return;
      case BATCHID:
        setBatchId((Number)value);
        return;
      case STDPACK:
        setStdPack((Number)value);
        return;
      case CARTONPACK:
        setCartonPack((Number)value);
        return;
      case CARTONCUBE:
        setCartonCube((Number)value);
        return;
      case CARTONWEIGHT:
        setCartonWeight((Number)value);
        return;
      case MASTERCARTON:
        setMasterCarton((Number)value);
        return;
      case RETAILCOST:
        setRetailCost((Number)value);
        return;
      case MASTERFOBCOST:
        setMasterFobCost((Number)value);
        return;
      case FOBORIGINCOST:
        setFobOriginCost((Number)value);
        return;
      case ESTLANDCOST:
        setEstLandCost((Number)value);
        return;
      case ACTLANDCOST:
        setActLandCost((Number)value);
        return;
      case MERCHDECCOST:
        setMerchDecCost((Number)value);
        return;
      case SOURCEPORTNAME:
        setSourcePortName((String)value);
        return;
      case DESTNPORTNAME:
        setDestnPortName((String)value);
        return;
      case ORIGINALPOSHIPDATE:
        setOriginalPoShipdate((Date)value);
        return;
      case CHANGEDPOSHIPDATE:
        setChangedPoShipdate((Date)value);
        return;
      case REASONCODE:
        setReasonCode((String)value);
        return;
      case REMARKS:
        setRemarks((String)value);
        return;
      case PARTIALLINEFLAG:
        setPartialLineFlag((String)value);
        return;
      case LATESTLINEFLAG:
        setLatestLineFlag((String)value);
        return;
      case NEWITEMFLAG:
        setNewItemFlag((String)value);
        return;
      case OVERSHIPPEDFLAG:
        setOverShippedFlag((String)value);
        return;
      case LATESHIPMENTALERT:
        setLateShipmentAlert((String)value);
        return;
      case KNBOOKINGALERT:
        setKnBookingAlert((String)value);
        return;
      case KNRECEIVINGALERT:
        setKnReceivingAlert((String)value);
        return;
      case BVBOOKINGALERT:
        setBvBookingAlert((String)value);
        return;
      case INSPBOOKALERT:
        setInspBookAlert((String)value);
        return;
      case ATTRIBUTE1:
        setAttribute1((String)value);
        return;
      case ATTRIBUTE2:
        setAttribute2((String)value);
        return;
      case ATTRIBUTE3:
        setAttribute3((String)value);
        return;
      case ATTRIBUTE4:
        setAttribute4((String)value);
        return;
      case ATTRIBUTE5:
        setAttribute5((String)value);
        return;
      case ATTRIBUTE6:
        setAttribute6((String)value);
        return;
      case ATTRIBUTE7:
        setAttribute7((String)value);
        return;
      case ATTRIBUTE8:
        setAttribute8((String)value);
        return;
      case ATTRIBUTE9:
        setAttribute9((String)value);
        return;
      case ATTRIBUTE10:
        setAttribute10((String)value);
        return;
      case ATTRIBUTE11:
        setAttribute11((String)value);
        return;
      case ATTRIBUTE12:
        setAttribute12((String)value);
        return;
      case ATTRIBUTE13:
        setAttribute13((String)value);
        return;
      case ATTRIBUTE14:
        setAttribute14((String)value);
        return;
      case ATTRIBUTE15:
        setAttribute15((String)value);
        return;
      case CREATIONDATE:
        setCreationDate((Date)value);
        return;
      case CREATEDBY:
        setCreatedBy((Number)value);
        return;
      case LASTUPDATEDATE:
        setLastUpdateDate((Date)value);
        return;
      case LASTUPDATEDBY:
        setLastUpdatedBy((Number)value);
        return;
      case LASTUPDATELOGIN:
        setLastUpdateLogin((Number)value);
        return;
      case FOBUSDCOST:
        setFobUsdCost((Number)value);
        return;
      case INSPQTY:
        setInspQty((Number)value);
        return;
      case SHIPPEDQTY:
        setShippedQty((Number)value);
        return;
      case BVCODE:
        setBvCode((String)value);
        return;
      case BVREASON:
        setBvReason((String)value);
        return;
      case GSODEPTID:
        setGsoDeptId((Number)value);
        return;
      case ORIGIN:
        setOrigin((String)value);
        return;
      case NBFLAG:
        setNbFlag((String)value);
        return;
      case INLINEFLAG:
        setInlineFlag((String)value);
        return;
      case SAFETYSTOCKFLAG:
        setSafetyStockFlag((String)value);
        return;
      case BVFLAG:
        setBvFlag((String)value);
        return;
      case FIRSTSHIPMENTFLAG:
        setFirstShipmentFlag((String)value);
        return;
      case BOOKEDQTY:
        setBookedQty((Number)value);
        return;
      case RECEIVEDQTY:
        setReceivedQty((Number)value);
        return;
      case GSOMO:
        setGsoMo((String)value);
        return;
      case DELAYCODE:
        setDelayCode((String)value);
        return;
      case DELAYREASON:
        setDelayReason((String)value);
        return;
      case DIFFPRICE:
        setDiffPrice((String)value);
        return;
      case SHIPMENTSTATUS:
        setShipmentStatus((String)value);
        return;
      case LINETOTAL:
        setLineTotal((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }



  /**
   * 
   * Gets the attribute value for LineTotal, using the alias name LineTotal
   */
  public Number getLineTotal()
  {
    return (Number)getAttributeInternal(LINETOTAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LineTotal
   */
  public void setLineTotal(Number value)
  {
    setAttributeInternal(LINETOTAL, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number poLineId)
  {
    return new Key(new Object[] {poLineId});
  }


}