create or replace 
package XX_UTIL_SKU_REPORTS
IS
 FUNCTION CLOSE_DATE(P_PARTY_ID IN NUMBER,P_SERIAL_NO IN VARCHAR2,P_TONER_ORDER_NUMBER IN NUMBER)RETURN DATE;
end XX_UTIL_SKU_REPORTS;
/

SHOW ERROR
