<definitions
     name="I0030_CARTONIZATION_EBS_IN"
     targetNamespace="http://xmlns.oracle.com/I0030_CARTONIZATION_EBS_IN"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://schemas.oracle.com/bpel/extension"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/I0030_CARTONIZATION_EBS_IN"
    >
    <import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/I0030_CARTONIZATION_EBS_IN" schemaLocation="I0030_CARTONIZATION_EBS_IN.xsd"/>
        </schema>
    </types>
    <message name="I0030_CARTONIZATION_EBS_INRequestMessage">
        <part name="payload" element="client:I0030_CARTONIZATION_EBS_INProcessRequest"/>
    </message>
    <message name="I0030_CARTONIZATION_EBS_INResponseMessage">
        <part name="payload" element="client:I0030_CARTONIZATION_EBS_INProcessResponse"/>
    </message>
    <portType name="I0030_CARTONIZATION_EBS_IN">
        <operation name="process">
            <input message="client:I0030_CARTONIZATION_EBS_INRequestMessage"/>
            <output message="client:I0030_CARTONIZATION_EBS_INResponseMessage"/>
            <fault message="client:I0030_CARTONIZATION_EBS_INResponseMessage" name="faultMessage"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="I0030_CARTONIZATION_EBS_IN">
        <plnk:role name="I0030_CARTONIZATION_EBS_INProvider">
            <plnk:portType name="client:I0030_CARTONIZATION_EBS_IN"/>
        </plnk:role>
    </plnk:partnerLinkType>
</definitions>
