<?xml version="1.0" encoding="UTF-8"?>
<definitions 
    name="StgTableInsert"
    targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/StgTableInsert/"
    xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/StgTableInsert/"
    xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
    xmlns:pc="http://xmlns.oracle.com/pcbpel/"
    xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/StgTableInsert"
    xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/db/"
    xmlns="http://schemas.xmlsoap.org/wsdl/">

    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/" location="DBAdapterOutboundHeader.wsdl"/>

    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/StgTableInsert"
                schemaLocation="StgTableInsert_table.xsd"/>
        </schema>
    </types>

    <message name="XxApInvInterfaceStgCollection_msg">
        <part name="XxApInvInterfaceStgCollection" element="top:XxApInvInterfaceStgCollection"/>
    </message>


    <portType name="StgTableInsert_ptt">
        <operation name="insert">
            <input message="tns:XxApInvInterfaceStgCollection_msg"/>
        </operation>
    </portType>

    <binding name="StgTableInsert_binding" type="tns:StgTableInsert_ptt">
        <jca:binding />
        <operation name="insert">
            <jca:operation
                InteractionSpec="oracle.tip.adapter.db.DBWriteInteractionSpec"

                DescriptorName="StgTableInsert.XxApInvInterfaceStg"
                DmlType="insert"
                DetectOmissions="true"
                OptimizeMerge="true"
                MappingsMetaDataURL="StgTableInsert_toplink_mappings.xml" />
            <input>
                <jca:header message="hdr:OutboundHeader_msg" part="outboundHeader"/>
            </input>
        </operation>
    </binding>

    <!-- Your runtime connection is declared in
        J2EE_HOME/application-deployments/default/DbAdapter/oc4j-ra.xml
        These 'mcf' properties here are from your design time connection and 
        save you from having to edit that file and restart the application server
        if eis/db/EBSAppsFin is missing.
        These 'mcf' properties are safe to remove.
    -->
    <service name="StgTableInsert">
        <port name="StgTableInsert_pt" binding="tns:StgTableInsert_binding">
            <jca:address location="eis/db/EBSAppsFin"
                UIConnectionName="GSIDEV01"
                ManagedConnectionFactory="oracle.tip.adapter.db.DBManagedConnectionFactory"                
            />
        </port>
    </service>

    <plt:partnerLinkType name="StgTableInsert_plt" >
        <plt:role name="StgTableInsert_role" >
            <plt:portType name="tns:StgTableInsert_ptt" />
        </plt:role>
    </plt:partnerLinkType>

</definitions>
