/*===========================================================================+
 |                       Office Depot - Project Simplify                     |
 |            Oracle NAIO/WIPRO/Office Depot/Consulting Organization         |
 +===========================================================================+
 |  FILENAME                                                                 |
 |             ODPartySitesAddrVORowImpl.java                                |
 |                                                                           |
 |  DESCRIPTION                                                              |
 |     Party Sites VO Row Impl                                               | 
 |                                                                           |
 |  NOTES                                                                    |
 |                                                                           |
 |                                                                           |
 |  DEPENDENCIES                                                             |
 |    No dependencies.                                                       |
 |                                                                           |
 |  HISTORY                                                                  |
 |                                                                           |
 |    01/OCT/2007 Sudeept Maharana   Created  / Generated                    |
 |                                                                           |
 +===========================================================================*/
package od.oracle.apps.xxcrm.asn.partysite.server;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class ODPartySitesAddrVORowImpl extends OAViewRowImpl 
{


  protected static final int PARTYSITEID = 0;
  protected static final int PARTYID = 1;
  protected static final int LOCATIONID = 2;
  protected static final int ACTUALCONTENTSOURCE = 3;
  protected static final int IDENTIFYINGADDRESSFLAG = 4;
  protected static final int STATUS = 5;
  protected static final int ORIGSYSTEMREFERENCE = 6;
  protected static final int PARTYSITENUMBER = 7;
  protected static final int PARTYSITENAME = 8;
  protected static final int ADDRESS = 9;
  protected static final int COUNTRYCODE = 10;
  protected static final int COUNTRY = 11;
  protected static final int STATE = 12;
  protected static final int PROVINCE = 13;
  protected static final int COUNTY = 14;
  protected static final int POSTALCODE = 15;
  protected static final int ALLPURPOSES = 16;
  protected static final int USE = 17;
  protected static final int UPDATEYESNO = 18;
  protected static final int REMOVEYES1NO1 = 19;
  protected static final int SELECTED = 20;
  protected static final int PARTYNAME = 21;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public ODPartySitesAddrVORowImpl()
  {
  }

  /**
   * 
   * Gets PartySitesEO entity object.
   */
  public od.oracle.apps.xxcrm.asn.partysite.schema.server.ODPartySitesEOImpl getPartySitesEO()
  {
    return (od.oracle.apps.xxcrm.asn.partysite.schema.server.ODPartySitesEOImpl)getEntity(0);
  }

  /**
   * 
   * Gets the attribute value for PARTY_SITE_ID using the alias name PartySiteId
   */
  public Number getPartySiteId()
  {
    return (Number)getAttributeInternal(PARTYSITEID);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for PARTY_SITE_ID using the alias name PartySiteId
   */
  public void setPartySiteId(Number value)
  {
    setAttributeInternal(PARTYSITEID, value);
  }

  /**
   * 
   * Gets the attribute value for PARTY_ID using the alias name PartyId
   */
  public Number getPartyId()
  {
    return (Number)getAttributeInternal(PARTYID);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for PARTY_ID using the alias name PartyId
   */
  public void setPartyId(Number value)
  {
    setAttributeInternal(PARTYID, value);
  }

  /**
   * 
   * Gets the attribute value for LOCATION_ID using the alias name LocationId
   */
  public Number getLocationId()
  {
    return (Number)getAttributeInternal(LOCATIONID);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for LOCATION_ID using the alias name LocationId
   */
  public void setLocationId(Number value)
  {
    setAttributeInternal(LOCATIONID, value);
  }

  /**
   * 
   * Gets the attribute value for IDENTIFYING_ADDRESS_FLAG using the alias name IdentifyingAddressFlag
   */
  public String getIdentifyingAddressFlag()
  {
    return (String)getAttributeInternal(IDENTIFYINGADDRESSFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for IDENTIFYING_ADDRESS_FLAG using the alias name IdentifyingAddressFlag
   */
  public void setIdentifyingAddressFlag(String value)
  {
    setAttributeInternal(IDENTIFYINGADDRESSFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for STATUS using the alias name Status
   */
  public String getStatus()
  {
    return (String)getAttributeInternal(STATUS);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for STATUS using the alias name Status
   */
  public void setStatus(String value)
  {
    setAttributeInternal(STATUS, value);
  }

  /**
   * 
   * Gets the attribute value for ORIG_SYSTEM_REFERENCE using the alias name OrigSystemReference
   */
  public String getOrigSystemReference()
  {
    return (String)getAttributeInternal(ORIGSYSTEMREFERENCE);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for ORIG_SYSTEM_REFERENCE using the alias name OrigSystemReference
   */
  public void setOrigSystemReference(String value)
  {
    setAttributeInternal(ORIGSYSTEMREFERENCE, value);
  }

  /**
   * 
   * Gets the attribute value for PARTY_SITE_NUMBER using the alias name PartySiteNumber
   */
  public String getPartySiteNumber()
  {
    return (String)getAttributeInternal(PARTYSITENUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for PARTY_SITE_NUMBER using the alias name PartySiteNumber
   */
  public void setPartySiteNumber(String value)
  {
    setAttributeInternal(PARTYSITENUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for PARTY_SITE_NAME using the alias name PartySiteName
   */
  public String getPartySiteName()
  {
    return (String)getAttributeInternal(PARTYSITENAME);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for PARTY_SITE_NAME using the alias name PartySiteName
   */
  public void setPartySiteName(String value)
  {
    setAttributeInternal(PARTYSITENAME, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Address
   */
  public String getAddress()
  {
    return (String)getAttributeInternal(ADDRESS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Address
   */
  public void setAddress(String value)
  {
    setAttributeInternal(ADDRESS, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute CountryCode
   */
  public String getCountryCode()
  {
    return (String)getAttributeInternal(COUNTRYCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute CountryCode
   */
  public void setCountryCode(String value)
  {
    setAttributeInternal(COUNTRYCODE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Country
   */
  public String getCountry()
  {
    return (String)getAttributeInternal(COUNTRY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Country
   */
  public void setCountry(String value)
  {
    setAttributeInternal(COUNTRY, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute State
   */
  public String getState()
  {
    return (String)getAttributeInternal(STATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute State
   */
  public void setState(String value)
  {
    setAttributeInternal(STATE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Province
   */
  public String getProvince()
  {
    return (String)getAttributeInternal(PROVINCE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Province
   */
  public void setProvince(String value)
  {
    setAttributeInternal(PROVINCE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute County
   */
  public String getCounty()
  {
    return (String)getAttributeInternal(COUNTY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute County
   */
  public void setCounty(String value)
  {
    setAttributeInternal(COUNTY, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute PostalCode
   */
  public String getPostalCode()
  {
    return (String)getAttributeInternal(POSTALCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute PostalCode
   */
  public void setPostalCode(String value)
  {
    setAttributeInternal(POSTALCODE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute AllPurposes
   */
  public String getAllPurposes()
  {
    return (String)getAttributeInternal(ALLPURPOSES);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute AllPurposes
   */
  public void setAllPurposes(String value)
  {
    setAttributeInternal(ALLPURPOSES, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Use
   */
  public String getUse()
  {
    return (String)getAttributeInternal(USE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Use
   */
  public void setUse(String value)
  {
    setAttributeInternal(USE, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case PARTYSITEID:
        return getPartySiteId();
      case PARTYID:
        return getPartyId();
      case LOCATIONID:
        return getLocationId();
      case ACTUALCONTENTSOURCE:
        return getActualContentSource();
      case IDENTIFYINGADDRESSFLAG:
        return getIdentifyingAddressFlag();
      case STATUS:
        return getStatus();
      case ORIGSYSTEMREFERENCE:
        return getOrigSystemReference();
      case PARTYSITENUMBER:
        return getPartySiteNumber();
      case PARTYSITENAME:
        return getPartySiteName();
      case ADDRESS:
        return getAddress();
      case COUNTRYCODE:
        return getCountryCode();
      case COUNTRY:
        return getCountry();
      case STATE:
        return getState();
      case PROVINCE:
        return getProvince();
      case COUNTY:
        return getCounty();
      case POSTALCODE:
        return getPostalCode();
      case ALLPURPOSES:
        return getAllPurposes();
      case USE:
        return getUse();
      case UPDATEYESNO:
        return getUpdateyesno();
      case REMOVEYES1NO1:
        return getRemoveyes1no1();
      case SELECTED:
        return getSelected();
      case PARTYNAME:
        return getPartyName();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case PARTYSITEID:
        setPartySiteId((Number)value);
        return;
      case PARTYID:
        setPartyId((Number)value);
        return;
      case LOCATIONID:
        setLocationId((Number)value);
        return;
      case ACTUALCONTENTSOURCE:
        setActualContentSource((String)value);
        return;
      case IDENTIFYINGADDRESSFLAG:
        setIdentifyingAddressFlag((String)value);
        return;
      case STATUS:
        setStatus((String)value);
        return;
      case ORIGSYSTEMREFERENCE:
        setOrigSystemReference((String)value);
        return;
      case PARTYSITENUMBER:
        setPartySiteNumber((String)value);
        return;
      case PARTYSITENAME:
        setPartySiteName((String)value);
        return;
      case ADDRESS:
        setAddress((String)value);
        return;
      case COUNTRYCODE:
        setCountryCode((String)value);
        return;
      case COUNTRY:
        setCountry((String)value);
        return;
      case STATE:
        setState((String)value);
        return;
      case PROVINCE:
        setProvince((String)value);
        return;
      case COUNTY:
        setCounty((String)value);
        return;
      case POSTALCODE:
        setPostalCode((String)value);
        return;
      case ALLPURPOSES:
        setAllPurposes((String)value);
        return;
      case USE:
        setUse((String)value);
        return;
      case UPDATEYESNO:
        setUpdateyesno((String)value);
        return;
      case REMOVEYES1NO1:
        setRemoveyes1no1((String)value);
        return;
      case SELECTED:
        setSelected((String)value);
        return;
      case PARTYNAME:
        setPartyName((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the attribute value for ACTUAL_CONTENT_SOURCE using the alias name ActualContentSource
   */
  public String getActualContentSource()
  {
    return (String)getAttributeInternal(ACTUALCONTENTSOURCE);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for ACTUAL_CONTENT_SOURCE using the alias name ActualContentSource
   */
  public void setActualContentSource(String value)
  {
    setAttributeInternal(ACTUALCONTENTSOURCE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Updateyesno
   */
  public String getUpdateyesno()
  {
    return (String)getAttributeInternal(UPDATEYESNO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Updateyesno
   */
  public void setUpdateyesno(String value)
  {
    setAttributeInternal(UPDATEYESNO, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Removeyes1no1
   */
  public String getRemoveyes1no1()
  {
    return (String)getAttributeInternal(REMOVEYES1NO1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Removeyes1no1
   */
  public void setRemoveyes1no1(String value)
  {
    setAttributeInternal(REMOVEYES1NO1, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Selected
   */
  public String getSelected()
  {
    return (String)getAttributeInternal(SELECTED);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Selected
   */
  public void setSelected(String value)
  {
    setAttributeInternal(SELECTED, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute PartyName
   */
  public String getPartyName()
  {
    return (String)getAttributeInternal(PARTYNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute PartyName
   */
  public void setPartyName(String value)
  {
    setAttributeInternal(PARTYNAME, value);
  }
}