package od.oracle.apps.xxcrm.asn.partysite.common.server;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class ODPartySiteVORowImpl extends OAViewRowImpl 
{


  protected static final int PARTYID = 0;
  protected static final int PARTYSITEID = 1;
  protected static final int PARTYSITENAME = 2;
  protected static final int PARTYSITEADDRESS = 3;
  protected static final int REGISTRYID = 4;
  protected static final int STATUS = 5;
  protected static final int IDENTIFYINGADDRESSFLAG = 6;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public ODPartySiteVORowImpl()
  {
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute PartyId
   */
  public Number getPartyId()
  {
    return (Number)getAttributeInternal(PARTYID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute PartyId
   */
  public void setPartyId(Number value)
  {
    setAttributeInternal(PARTYID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute PartySiteId
   */
  public Number getPartySiteId()
  {
    return (Number)getAttributeInternal(PARTYSITEID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute PartySiteId
   */
  public void setPartySiteId(Number value)
  {
    setAttributeInternal(PARTYSITEID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute PartySiteName
   */
  public String getPartySiteName()
  {
    return (String)getAttributeInternal(PARTYSITENAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute PartySiteName
   */
  public void setPartySiteName(String value)
  {
    setAttributeInternal(PARTYSITENAME, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute PartySiteAddress
   */
  public String getPartySiteAddress()
  {
    return (String)getAttributeInternal(PARTYSITEADDRESS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute PartySiteAddress
   */
  public void setPartySiteAddress(String value)
  {
    setAttributeInternal(PARTYSITEADDRESS, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute RegistryId
   */
  public String getRegistryId()
  {
    return (String)getAttributeInternal(REGISTRYID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute RegistryId
   */
  public void setRegistryId(String value)
  {
    setAttributeInternal(REGISTRYID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Status
   */
  public String getStatus()
  {
    return (String)getAttributeInternal(STATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Status
   */
  public void setStatus(String value)
  {
    setAttributeInternal(STATUS, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case PARTYID:
        return getPartyId();
      case PARTYSITEID:
        return getPartySiteId();
      case PARTYSITENAME:
        return getPartySiteName();
      case PARTYSITEADDRESS:
        return getPartySiteAddress();
      case REGISTRYID:
        return getRegistryId();
      case STATUS:
        return getStatus();
      case IDENTIFYINGADDRESSFLAG:
        return getIdentifyingAddressFlag();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case PARTYID:
        setPartyId((Number)value);
        return;
      case PARTYSITEID:
        setPartySiteId((Number)value);
        return;
      case PARTYSITENAME:
        setPartySiteName((String)value);
        return;
      case PARTYSITEADDRESS:
        setPartySiteAddress((String)value);
        return;
      case REGISTRYID:
        setRegistryId((String)value);
        return;
      case STATUS:
        setStatus((String)value);
        return;
      case IDENTIFYINGADDRESSFLAG:
        setIdentifyingAddressFlag((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute IdentifyingAddressFlag
   */
  public String getIdentifyingAddressFlag()
  {
    return (String)getAttributeInternal(IDENTIFYINGADDRESSFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute IdentifyingAddressFlag
   */
  public void setIdentifyingAddressFlag(String value)
  {
    setAttributeInternal(IDENTIFYINGADDRESSFLAG, value);
  }
}