<?binding.jca IExpenseConcurrentProgram_apps.jca?>
<wsdl:definitions name="IExpenseConcurrentProgram" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/apps/IExpense/RouteIExpenseDetailsToAppsABCS/IExpenseConcurrentProgram" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/XX_MASTER_CARD_TRAN_VALID_PKG/CALL_MAIN/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/apps/IExpense/RouteIExpenseDetailsToAppsABCS/IExpenseConcurrentProgram" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="IExpenseConcurrentProgram_plt">
        <plt:role name="IExpenseConcurrentProgram_role">
            <plt:portType name="tns:IExpenseConcurrentProgram_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/XX_MASTER_CARD_TRAN_VALID_PKG/CALL_MAIN/" schemaLocation="xsd/APPS_XX_MASTER_CARD_TRAN_VALID_PKG_CALL_MAIN.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:portType name="IExpenseConcurrentProgram_ptt">
        <wsdl:operation name="IExpenseConcurrentProgram">
            <wsdl:input message="tns:args_in_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
