<definitions
     name="GetConcurrentProgramStatus"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetConcurrentProgramStatus/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/GetConcurrentProgramStatus/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/XX_BPEL_INTEGRATION_PKG/GET_CONCURRENT_REQUEST_STATUS/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/db/"
    >
    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/" location="DBAdapterOutboundHeader.wsdl"/>
    <types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/XX_BPEL_INTEGRATION_PKG/GET_CONCURRENT_REQUEST_STATUS/"
               schemaLocation="APPS_XX_BPEL_INTEGRATION_PKG_GET_CONCURRENT_REQUEST_STATUS.xsd" />
     </schema>
    </types>
    <message name="args_in_msg">
        <part name="InputParameters" element="db:InputParameters"/>
    </message>
    <message name="args_out_msg">
        <part name="OutputParameters" element="db:OutputParameters"/>
    </message>
    <portType name="GetConcurrentProgramStatus_ptt">
        <operation name="GetConcurrentProgramStatus">
            <input message="tns:args_in_msg"/>
            <output message="tns:args_out_msg"/>
        </operation>
    </portType>
    <binding name="GetConcurrentProgramStatus_binding" type="tns:GetConcurrentProgramStatus_ptt">
    <jca:binding  />
        <operation name="GetConcurrentProgramStatus">
      <jca:operation
          PackageName="XX_BPEL_INTEGRATION_PKG"
          ProcedureName="GET_CONCURRENT_REQUEST_STATUS"
          InteractionSpec="oracle.tip.adapter.db.DBStoredProcedureInteractionSpec" >
      </jca:operation>
      <input>
        <jca:header message="hdr:OutboundHeader_msg" part="outboundHeader"/>
      </input>
            <output/>
        </operation>
    </binding>
    <service name="GetConcurrentProgramStatus">
        <port name="GetConcurrentProgramStatus_pt" binding="tns:GetConcurrentProgramStatus_binding">
<!--Your runtime connection is declared in 
J2EE_HOME/application-deployments/default/DbAdapter/oc4j-ra.xml 
These mcf properties here are from your design time connection and 
save you from having to edit that file and restart the application server 
if eis/db/EBSApps is missing. 
These mcf properties are safe to remove.-->
      <jca:address location="eis/db/EBSAppsFin" UIConnectionName="EIS_APPS_EBS_APPS_DBConn"
          ManagedConnectionFactory="oracle.tip.adapter.db.DBManagedConnectionFactory"
      />
        </port>
    </service>
  <plt:partnerLinkType name="GetConcurrentProgramStatus_plt" >
    <plt:role name="GetConcurrentProgramStatus_role" >
      <plt:portType name="tns:GetConcurrentProgramStatus_ptt" />
    </plt:role>
  </plt:partnerLinkType>
</definitions>
