<definitions
     name="DPSCancel_SendSalesOrderInfo"
     targetNamespace="http://xmlns.oracle.com/DPSCancel_SendSalesOrderInfo"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://schemas.oracle.com/bpel/extension"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/DPSCancel_SendSalesOrderInfo"
    >
    <import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/DPSCancel_SendSalesOrderInfo" schemaLocation="DPSCancel_SendSalesOrderInfo.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.openapplications.org/oagis/9" schemaLocation="CancelOrder.xsd"/>
        </xsd:schema>
    </types>
    <message name="DPSCancel_SendSalesOrderInfoRequestMessage">
        <part name="payload" element="client:DPSCancel_SendSalesOrderInfoProcessRequest"/>
    </message>
    <message name="DPSCancel_SendSalesOrderInfoResponseMessage">
        <part name="payload" element="client:DPSCancel_SendSalesOrderInfoProcessResponse"/>
    </message>
    <portType name="DPSCancel_SendSalesOrderInfo">
        <operation name="process">
            <input message="client:DPSCancel_SendSalesOrderInfoRequestMessage"/>
            <output message="client:DPSCancel_SendSalesOrderInfoResponseMessage"/>
        </operation>
    </portType>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:import namespace="http://www.openapplications.org/oagis/9" schemaLocation="xmlParseDPSCancel.xsd"/>
    </xsd:schema>
    <plnk:partnerLinkType name="DPSCancel_SendSalesOrderInfo">
        <plnk:role name="DPSCancel_SendSalesOrderInfoProvider">
            <plnk:portType name="client:DPSCancel_SendSalesOrderInfo"/>
        </plnk:role>
    </plnk:partnerLinkType>
</definitions>
