package od.oracle.apps.xxom.xxomCustui.server;
import oracle.apps.fnd.framework.server.OAEntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class xxomOeOrderSourcesEOImpl extends OAEntityImpl 
{
  protected static final int ORDERSOURCEID = 0;
  protected static final int CREATIONDATE = 1;
  protected static final int CREATEDBY = 2;
  protected static final int LASTUPDATEDATE = 3;
  protected static final int LASTUPDATEDBY = 4;
  protected static final int LASTUPDATELOGIN = 5;
  protected static final int NAME = 6;
  protected static final int DESCRIPTION = 7;
  protected static final int ENABLEDFLAG = 8;
  protected static final int CREATECUSTOMERSFLAG = 9;
  protected static final int USEIDSFLAG = 10;
  private static oracle.apps.fnd.framework.server.OAEntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public xxomOeOrderSourcesEOImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (oracle.apps.fnd.framework.server.OAEntityDefImpl)EntityDefImpl.findDefObject("od.oracle.apps.xxom.xxomCustui.server.xxomOeOrderSourcesEO");
    }
    return mDefinitionObject;
  }

  /**
   * 
   * Gets the attribute value for OrderSourceId, using the alias name OrderSourceId
   */
  public Number getOrderSourceId()
  {
    return (Number)getAttributeInternal(ORDERSOURCEID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for OrderSourceId
   */
  public void setOrderSourceId(Number value)
  {
    setAttributeInternal(ORDERSOURCEID, value);
  }

  /**
   * 
   * Gets the attribute value for CreationDate, using the alias name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * 
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin()
  {
    return (Number)getAttributeInternal(LASTUPDATELOGIN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value)
  {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**
   * 
   * Gets the attribute value for Name, using the alias name Name
   */
  public String getName()
  {
    return (String)getAttributeInternal(NAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Name
   */
  public void setName(String value)
  {
    setAttributeInternal(NAME, value);
  }

  /**
   * 
   * Gets the attribute value for Description, using the alias name Description
   */
  public String getDescription()
  {
    return (String)getAttributeInternal(DESCRIPTION);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Description
   */
  public void setDescription(String value)
  {
    setAttributeInternal(DESCRIPTION, value);
  }

  /**
   * 
   * Gets the attribute value for EnabledFlag, using the alias name EnabledFlag
   */
  public String getEnabledFlag()
  {
    return (String)getAttributeInternal(ENABLEDFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for EnabledFlag
   */
  public void setEnabledFlag(String value)
  {
    setAttributeInternal(ENABLEDFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for CreateCustomersFlag, using the alias name CreateCustomersFlag
   */
  public String getCreateCustomersFlag()
  {
    return (String)getAttributeInternal(CREATECUSTOMERSFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CreateCustomersFlag
   */
  public void setCreateCustomersFlag(String value)
  {
    setAttributeInternal(CREATECUSTOMERSFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for UseIdsFlag, using the alias name UseIdsFlag
   */
  public String getUseIdsFlag()
  {
    return (String)getAttributeInternal(USEIDSFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for UseIdsFlag
   */
  public void setUseIdsFlag(String value)
  {
    setAttributeInternal(USEIDSFLAG, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ORDERSOURCEID:
        return getOrderSourceId();
      case CREATIONDATE:
        return getCreationDate();
      case CREATEDBY:
        return getCreatedBy();
      case LASTUPDATEDATE:
        return getLastUpdateDate();
      case LASTUPDATEDBY:
        return getLastUpdatedBy();
      case LASTUPDATELOGIN:
        return getLastUpdateLogin();
      case NAME:
        return getName();
      case DESCRIPTION:
        return getDescription();
      case ENABLEDFLAG:
        return getEnabledFlag();
      case CREATECUSTOMERSFLAG:
        return getCreateCustomersFlag();
      case USEIDSFLAG:
        return getUseIdsFlag();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ORDERSOURCEID:
        setOrderSourceId((Number)value);
        return;
      case CREATIONDATE:
        setCreationDate((Date)value);
        return;
      case CREATEDBY:
        setCreatedBy((Number)value);
        return;
      case LASTUPDATEDATE:
        setLastUpdateDate((Date)value);
        return;
      case LASTUPDATEDBY:
        setLastUpdatedBy((Number)value);
        return;
      case LASTUPDATELOGIN:
        setLastUpdateLogin((Number)value);
        return;
      case NAME:
        setName((String)value);
        return;
      case DESCRIPTION:
        setDescription((String)value);
        return;
      case ENABLEDFLAG:
        setEnabledFlag((String)value);
        return;
      case CREATECUSTOMERSFLAG:
        setCreateCustomersFlag((String)value);
        return;
      case USEIDSFLAG:
        setUseIdsFlag((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number orderSourceId)
  {
    return new Key(new Object[] {orderSourceId});
  }
}