DROP TYPE XX_GI_TRANSFER_PKG_XX_GI_XFER FORCE; 
show errors
DROP TYPE XX_GI_TRANSFER_PKG_XX_GI_XFE2 FORCE; 
show errors
DROP TYPE XX_GI_TRANSFER_PKG_XX_GI_XFE1 FORCE; 
show errors
DROP PACKAGE BPEL_PLINVENTORYTRANSFERPROCES;
exit
