DROP TYPE XX_INV_ITEM_IN_PKG_G_MASTER_I FORCE; 
show errors
DROP TYPE XX_INV_ITEM_IN_PKG_G_MASTER_1 FORCE; 
show errors
DROP TYPE XX_INV_ITEM_IN_PKG_ROWTYPE_SQ FORCE; 
show errors
DROP TYPE XXINVITEMINPKGGLOCATION_ROWTY FORCE; 
show errors
DROP TYPE XX_INV_ITEM_IN_PKG_G_LOCATION FORCE; 
show errors
DROP PACKAGE BPEL_PLITEMPROCESS;
exit
