<definitions
     name="I1164_EBS_ROADNET_OUT"
     targetNamespace="http://xmlns.oracle.com/I1164_EBS_ROADNET_OUT"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://www.openapplications.org/oagis/9"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:ns2="http://schemas.oracle.com/bpel/extension"
     xmlns:client="http://xmlns.oracle.com/I1164_EBS_ROADNET_OUT"
    >
    <import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/I1164_EBS_ROADNET_OUT" schemaLocation="I1164_EBS_ROADNET_OUT.xsd"/>
        </schema>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.openapplications.org/oagis/9" schemaLocation="GetCarrierRoute_1.xsd"/>
        </schema>
    </types>
    <message name="DeliveryToRoadnetRequestMessage">
        <part name="payload" element="ns1:CarrierRoute"/>
    </message>
    <message name="DeliveryToRoadnetResponseMessage">
        <part name="payload" element="client:DeliveryToRoadnetProcessResponse"/>
    </message>
    <portType name="I1164_EBS_ROADNET_OUT">
        <operation name="process">
            <input message="client:DeliveryToRoadnetRequestMessage"/>
            <output message="client:DeliveryToRoadnetResponseMessage"/>
            <fault name="EnqueueError" message="client:DeliveryToRoadnetResponseMessage"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="I1164_EBS_ROADNET_OUT">
        <plnk:role name="DeliveryToRoadnetProvider">
            <plnk:portType name="client:I1164_EBS_ROADNET_OUT"/>
        </plnk:role>
    </plnk:partnerLinkType>
</definitions>
