package od.oracle.apps.xxmer.schema.wfh.server;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VendorExistenceVVORowImpl extends OAViewRowImpl 
{
  protected static final int VENDORSITEID = 0;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VendorExistenceVVORowImpl()
  {
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute VendorSiteId
   */
  public Number getVendorSiteId()
  {
    return (Number)getAttributeInternal(VENDORSITEID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute VendorSiteId
   */
  public void setVendorSiteId(Number value)
  {
    setAttributeInternal(VENDORSITEID, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case VENDORSITEID:
        return getVendorSiteId();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case VENDORSITEID:
        setVendorSiteId((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
}