package od.oracle.apps.xxcrm.mps.schema.server;
import oracle.apps.fnd.framework.server.OAEntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.RowID;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class OD_MPSPartyDevicesEOImpl extends OAEntityImpl 
{
  protected static final int DEVICEID = 0;
  protected static final int DEVICENAME = 1;
  protected static final int GROUPID = 2;
  protected static final int GROUPNAME = 3;
  protected static final int SERIALNO = 4;
  protected static final int IPADDRESS = 5;
  protected static final int MANUFACTURER = 6;
  protected static final int MODEL = 7;
  protected static final int PARTYID = 8;
  protected static final int PARTYNAME = 9;
  protected static final int SHIPSITEID = 10;
  protected static final int SITECONTACT = 11;
  protected static final int SITECONTACTPHONE = 12;
  protected static final int SITEADDRESS1 = 13;
  protected static final int SITEADDRESS2 = 14;
  protected static final int SITECITY = 15;
  protected static final int SITESTATE = 16;
  protected static final int SITEZIPCODE = 17;
  protected static final int DEVICECONTACT = 18;
  protected static final int DEVICEPHONE = 19;
  protected static final int DEVICEFLOOR = 20;
  protected static final int DEVICEROOM = 21;
  protected static final int DEVICELOCATION = 22;
  protected static final int DEVICECOSTCENTER = 23;
  protected static final int DEVICEJIT = 24;
  protected static final int PROGRAMTYPE = 25;
  protected static final int MANAGEDSTATUS = 26;
  protected static final int SUPPORTCOVERAGE = 27;
  protected static final int SLACOVERAGE = 28;
  protected static final int MPSREPCOMMENTS = 29;
  protected static final int BSDREPCOMMENTS = 30;
  protected static final int ACTIVESTATUS = 31;
  protected static final int ATTRIBUTE1 = 32;
  protected static final int ATTRIBUTE2 = 33;
  protected static final int ATTRIBUTE3 = 34;
  protected static final int ATTRIBUTE4 = 35;
  protected static final int ATTRIBUTE5 = 36;
  protected static final int AVFSUBMIT = 37;
  protected static final int BLACKCPC = 38;
  protected static final int COLORCPC = 39;
  protected static final int ALLOWANCES = 40;
  protected static final int OVERAGECOST = 41;
  protected static final int FLATRATE = 42;
  protected static final int FLEETSYSTEM = 43;
  protected static final int NOTIFICATIONDATE = 44;
  protected static final int ESSENTIALSATRFLAG = 45;
  protected static final int SKUOPTION1 = 46;
  protected static final int SKUOPTION2 = 47;
  protected static final int SKUOPTION3 = 48;
  protected static final int ASSETNUMBER = 49;
  protected static final int CREATIONDATE = 50;
  protected static final int CREATEDBY = 51;
  protected static final int LASTUPDATEDATE = 52;
  protected static final int LASTUPDATEDBY = 53;
  protected static final int AOPSCUSTNUMBER = 54;
  protected static final int LEVELLIMIT = 55;
  protected static final int PONUMBER = 56;
  protected static final int USAGESENDLEADDAYS = 57;
  protected static final int USAGEDATASENTDATE = 58;
  protected static final int PERIODCOVEREDSTDATE = 59;
  protected static final int PERIODCOVEREDENDDATE = 60;
  protected static final int MODELID = 61;
  protected static final int BRANDID = 62;
  protected static final int COLORALLOWANCES = 63;
  protected static final int SERVICECOST = 64;
  protected static final int CONTRACTNUMBER = 65;
  protected static final int EXPIREDDATE = 66;
  protected static final int ROWID = 67;
  protected static final int COLOROVERAGECOST = 68;



  private static oracle.apps.fnd.framework.server.OAEntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public OD_MPSPartyDevicesEOImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (oracle.apps.fnd.framework.server.OAEntityDefImpl)EntityDefImpl.findDefObject("od.oracle.apps.xxcrm.mps.schema.server.OD_MPSPartyDevicesEO");
    }
    return mDefinitionObject;
  }




  /**
   * 
   * Gets the attribute value for DeviceId, using the alias name DeviceId
   */
  public String getDeviceId()
  {
    return (String)getAttributeInternal(DEVICEID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DeviceId
   */
  public void setDeviceId(String value)
  {
    setAttributeInternal(DEVICEID, value);
  }

  /**
   * 
   * Gets the attribute value for DeviceName, using the alias name DeviceName
   */
  public String getDeviceName()
  {
    return (String)getAttributeInternal(DEVICENAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DeviceName
   */
  public void setDeviceName(String value)
  {
    setAttributeInternal(DEVICENAME, value);
  }

  /**
   * 
   * Gets the attribute value for GroupId, using the alias name GroupId
   */
  public String getGroupId()
  {
    return (String)getAttributeInternal(GROUPID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for GroupId
   */
  public void setGroupId(String value)
  {
    setAttributeInternal(GROUPID, value);
  }

  /**
   * 
   * Gets the attribute value for GroupName, using the alias name GroupName
   */
  public String getGroupName()
  {
    return (String)getAttributeInternal(GROUPNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for GroupName
   */
  public void setGroupName(String value)
  {
    setAttributeInternal(GROUPNAME, value);
  }

  /**
   * 
   * Gets the attribute value for SerialNo, using the alias name SerialNo
   */
  public String getSerialNo()
  {
    return (String)getAttributeInternal(SERIALNO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SerialNo
   */
  public void setSerialNo(String value)
  {
    setAttributeInternal(SERIALNO, value);
  }

  /**
   * 
   * Gets the attribute value for IpAddress, using the alias name IpAddress
   */
  public String getIpAddress()
  {
    return (String)getAttributeInternal(IPADDRESS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IpAddress
   */
  public void setIpAddress(String value)
  {
    setAttributeInternal(IPADDRESS, value);
  }

  /**
   * 
   * Gets the attribute value for Manufacturer, using the alias name Manufacturer
   */
  public String getManufacturer()
  {
    return (String)getAttributeInternal(MANUFACTURER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Manufacturer
   */
  public void setManufacturer(String value)
  {
    setAttributeInternal(MANUFACTURER, value);
  }

  /**
   * 
   * Gets the attribute value for Model, using the alias name Model
   */
  public String getModel()
  {
    return (String)getAttributeInternal(MODEL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Model
   */
  public void setModel(String value)
  {
    setAttributeInternal(MODEL, value);
  }

  /**
   * 
   * Gets the attribute value for PartyId, using the alias name PartyId
   */
  public Number getPartyId()
  {
    return (Number)getAttributeInternal(PARTYID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PartyId
   */
  public void setPartyId(Number value)
  {
    setAttributeInternal(PARTYID, value);
  }

  /**
   * 
   * Gets the attribute value for PartyName, using the alias name PartyName
   */
  public String getPartyName()
  {
    return (String)getAttributeInternal(PARTYNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PartyName
   */
  public void setPartyName(String value)
  {
    setAttributeInternal(PARTYNAME, value);
  }

  /**
   * 
   * Gets the attribute value for ShipSiteId, using the alias name ShipSiteId
   */
  public Number getShipSiteId()
  {
    return (Number)getAttributeInternal(SHIPSITEID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ShipSiteId
   */
  public void setShipSiteId(Number value)
  {
    setAttributeInternal(SHIPSITEID, value);
  }

  /**
   * 
   * Gets the attribute value for SiteContact, using the alias name SiteContact
   */
  public String getSiteContact()
  {
    return (String)getAttributeInternal(SITECONTACT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SiteContact
   */
  public void setSiteContact(String value)
  {
    setAttributeInternal(SITECONTACT, value);
  }

  /**
   * 
   * Gets the attribute value for SiteContactPhone, using the alias name SiteContactPhone
   */
  public String getSiteContactPhone()
  {
    return (String)getAttributeInternal(SITECONTACTPHONE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SiteContactPhone
   */
  public void setSiteContactPhone(String value)
  {
    setAttributeInternal(SITECONTACTPHONE, value);
  }

  /**
   * 
   * Gets the attribute value for SiteAddress1, using the alias name SiteAddress1
   */
  public String getSiteAddress1()
  {
    return (String)getAttributeInternal(SITEADDRESS1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SiteAddress1
   */
  public void setSiteAddress1(String value)
  {
    setAttributeInternal(SITEADDRESS1, value);
  }

  /**
   * 
   * Gets the attribute value for SiteAddress2, using the alias name SiteAddress2
   */
  public String getSiteAddress2()
  {
    return (String)getAttributeInternal(SITEADDRESS2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SiteAddress2
   */
  public void setSiteAddress2(String value)
  {
    setAttributeInternal(SITEADDRESS2, value);
  }

  /**
   * 
   * Gets the attribute value for SiteCity, using the alias name SiteCity
   */
  public String getSiteCity()
  {
    return (String)getAttributeInternal(SITECITY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SiteCity
   */
  public void setSiteCity(String value)
  {
    setAttributeInternal(SITECITY, value);
  }

  /**
   * 
   * Gets the attribute value for SiteState, using the alias name SiteState
   */
  public String getSiteState()
  {
    return (String)getAttributeInternal(SITESTATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SiteState
   */
  public void setSiteState(String value)
  {
    setAttributeInternal(SITESTATE, value);
  }

  /**
   * 
   * Gets the attribute value for SiteZipCode, using the alias name SiteZipCode
   */
  public String getSiteZipCode()
  {
    return (String)getAttributeInternal(SITEZIPCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SiteZipCode
   */
  public void setSiteZipCode(String value)
  {
    setAttributeInternal(SITEZIPCODE, value);
  }

  /**
   * 
   * Gets the attribute value for DeviceContact, using the alias name DeviceContact
   */
  public String getDeviceContact()
  {
    return (String)getAttributeInternal(DEVICECONTACT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DeviceContact
   */
  public void setDeviceContact(String value)
  {
    setAttributeInternal(DEVICECONTACT, value);
  }

  /**
   * 
   * Gets the attribute value for DevicePhone, using the alias name DevicePhone
   */
  public String getDevicePhone()
  {
    return (String)getAttributeInternal(DEVICEPHONE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DevicePhone
   */
  public void setDevicePhone(String value)
  {
    setAttributeInternal(DEVICEPHONE, value);
  }

  /**
   * 
   * Gets the attribute value for DeviceFloor, using the alias name DeviceFloor
   */
  public String getDeviceFloor()
  {
    return (String)getAttributeInternal(DEVICEFLOOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DeviceFloor
   */
  public void setDeviceFloor(String value)
  {
    setAttributeInternal(DEVICEFLOOR, value);
  }

  /**
   * 
   * Gets the attribute value for DeviceRoom, using the alias name DeviceRoom
   */
  public String getDeviceRoom()
  {
    return (String)getAttributeInternal(DEVICEROOM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DeviceRoom
   */
  public void setDeviceRoom(String value)
  {
    setAttributeInternal(DEVICEROOM, value);
  }

  /**
   * 
   * Gets the attribute value for DeviceLocation, using the alias name DeviceLocation
   */
  public String getDeviceLocation()
  {
    return (String)getAttributeInternal(DEVICELOCATION);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DeviceLocation
   */
  public void setDeviceLocation(String value)
  {
    setAttributeInternal(DEVICELOCATION, value);
  }

  /**
   * 
   * Gets the attribute value for DeviceCostCenter, using the alias name DeviceCostCenter
   */
  public String getDeviceCostCenter()
  {
    return (String)getAttributeInternal(DEVICECOSTCENTER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DeviceCostCenter
   */
  public void setDeviceCostCenter(String value)
  {
    setAttributeInternal(DEVICECOSTCENTER, value);
  }

  /**
   * 
   * Gets the attribute value for DeviceJit, using the alias name DeviceJit
   */
  public String getDeviceJit()
  {
    return (String)getAttributeInternal(DEVICEJIT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DeviceJit
   */
  public void setDeviceJit(String value)
  {
    setAttributeInternal(DEVICEJIT, value);
  }

  /**
   * 
   * Gets the attribute value for ProgramType, using the alias name ProgramType
   */
  public String getProgramType()
  {
    return (String)getAttributeInternal(PROGRAMTYPE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ProgramType
   */
  public void setProgramType(String value)
  {
    setAttributeInternal(PROGRAMTYPE, value);
  }

  /**
   * 
   * Gets the attribute value for ManagedStatus, using the alias name ManagedStatus
   */
  public String getManagedStatus()
  {
    return (String)getAttributeInternal(MANAGEDSTATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ManagedStatus
   */
  public void setManagedStatus(String value)
  {
    setAttributeInternal(MANAGEDSTATUS, value);
  }

  /**
   * 
   * Gets the attribute value for SupportCoverage, using the alias name SupportCoverage
   */
  public String getSupportCoverage()
  {
    return (String)getAttributeInternal(SUPPORTCOVERAGE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SupportCoverage
   */
  public void setSupportCoverage(String value)
  {
    setAttributeInternal(SUPPORTCOVERAGE, value);
  }

  /**
   * 
   * Gets the attribute value for SlaCoverage, using the alias name SlaCoverage
   */
  public String getSlaCoverage()
  {
    return (String)getAttributeInternal(SLACOVERAGE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SlaCoverage
   */
  public void setSlaCoverage(String value)
  {
    setAttributeInternal(SLACOVERAGE, value);
  }

  /**
   * 
   * Gets the attribute value for MpsRepComments, using the alias name MpsRepComments
   */
  public String getMpsRepComments()
  {
    return (String)getAttributeInternal(MPSREPCOMMENTS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for MpsRepComments
   */
  public void setMpsRepComments(String value)
  {
    setAttributeInternal(MPSREPCOMMENTS, value);
  }

  /**
   * 
   * Gets the attribute value for BsdRepComments, using the alias name BsdRepComments
   */
  public String getBsdRepComments()
  {
    return (String)getAttributeInternal(BSDREPCOMMENTS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BsdRepComments
   */
  public void setBsdRepComments(String value)
  {
    setAttributeInternal(BSDREPCOMMENTS, value);
  }

  /**
   * 
   * Gets the attribute value for ActiveStatus, using the alias name ActiveStatus
   */
  public String getActiveStatus()
  {
    return (String)getAttributeInternal(ACTIVESTATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ActiveStatus
   */
  public void setActiveStatus(String value)
  {
    setAttributeInternal(ACTIVESTATUS, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute1, using the alias name Attribute1
   */
  public String getAttribute1()
  {
    return (String)getAttributeInternal(ATTRIBUTE1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute1
   */
  public void setAttribute1(String value)
  {
    setAttributeInternal(ATTRIBUTE1, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute2, using the alias name Attribute2
   */
  public String getAttribute2()
  {
    return (String)getAttributeInternal(ATTRIBUTE2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute2
   */
  public void setAttribute2(String value)
  {
    setAttributeInternal(ATTRIBUTE2, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute3, using the alias name Attribute3
   */
  public String getAttribute3()
  {
    return (String)getAttributeInternal(ATTRIBUTE3);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute3
   */
  public void setAttribute3(String value)
  {
    setAttributeInternal(ATTRIBUTE3, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute4, using the alias name Attribute4
   */
  public String getAttribute4()
  {
    return (String)getAttributeInternal(ATTRIBUTE4);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute4
   */
  public void setAttribute4(String value)
  {
    setAttributeInternal(ATTRIBUTE4, value);
  }

  /**
   * 
   * Gets the attribute value for Attribute5, using the alias name Attribute5
   */
  public String getAttribute5()
  {
    return (String)getAttributeInternal(ATTRIBUTE5);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Attribute5
   */
  public void setAttribute5(String value)
  {
    setAttributeInternal(ATTRIBUTE5, value);
  }

  /**
   * 
   * Gets the attribute value for AvfSubmit, using the alias name AvfSubmit
   */
  public String getAvfSubmit()
  {
    return (String)getAttributeInternal(AVFSUBMIT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AvfSubmit
   */
  public void setAvfSubmit(String value)
  {
    setAttributeInternal(AVFSUBMIT, value);
  }

  /**
   * 
   * Gets the attribute value for BlackCpc, using the alias name BlackCpc
   */
  public Number getBlackCpc()
  {
    return (Number)getAttributeInternal(BLACKCPC);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BlackCpc
   */
  public void setBlackCpc(Number value)
  {
    setAttributeInternal(BLACKCPC, value);
  }

  /**
   * 
   * Gets the attribute value for ColorCpc, using the alias name ColorCpc
   */
  public Number getColorCpc()
  {
    return (Number)getAttributeInternal(COLORCPC);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ColorCpc
   */
  public void setColorCpc(Number value)
  {
    setAttributeInternal(COLORCPC, value);
  }

  /**
   * 
   * Gets the attribute value for Allowances, using the alias name Allowances
   */
  public Number getAllowances()
  {
    return (Number)getAttributeInternal(ALLOWANCES);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Allowances
   */
  public void setAllowances(Number value)
  {
    setAttributeInternal(ALLOWANCES, value);
  }

  /**
   * 
   * Gets the attribute value for OverageCost, using the alias name OverageCost
   */
  public Number getOverageCost()
  {
    return (Number)getAttributeInternal(OVERAGECOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for OverageCost
   */
  public void setOverageCost(Number value)
  {
    setAttributeInternal(OVERAGECOST, value);
  }

  /**
   * 
   * Gets the attribute value for FlatRate, using the alias name FlatRate
   */
  public Number getFlatRate()
  {
    return (Number)getAttributeInternal(FLATRATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for FlatRate
   */
  public void setFlatRate(Number value)
  {
    setAttributeInternal(FLATRATE, value);
  }

  /**
   * 
   * Gets the attribute value for FleetSystem, using the alias name FleetSystem
   */
  public String getFleetSystem()
  {
    return (String)getAttributeInternal(FLEETSYSTEM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for FleetSystem
   */
  public void setFleetSystem(String value)
  {
    setAttributeInternal(FLEETSYSTEM, value);
  }

  /**
   * 
   * Gets the attribute value for NotificationDate, using the alias name NotificationDate
   */
  public Date getNotificationDate()
  {
    return (Date)getAttributeInternal(NOTIFICATIONDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NotificationDate
   */
  public void setNotificationDate(Date value)
  {
    setAttributeInternal(NOTIFICATIONDATE, value);
  }

  /**
   * 
   * Gets the attribute value for EssentialsAtrFlag, using the alias name EssentialsAtrFlag
   */
  public String getEssentialsAtrFlag()
  {
    return (String)getAttributeInternal(ESSENTIALSATRFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for EssentialsAtrFlag
   */
  public void setEssentialsAtrFlag(String value)
  {
    setAttributeInternal(ESSENTIALSATRFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for SkuOption1, using the alias name SkuOption1
   */
  public String getSkuOption1()
  {
    return (String)getAttributeInternal(SKUOPTION1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SkuOption1
   */
  public void setSkuOption1(String value)
  {
    setAttributeInternal(SKUOPTION1, value);
  }

  /**
   * 
   * Gets the attribute value for SkuOption2, using the alias name SkuOption2
   */
  public String getSkuOption2()
  {
    return (String)getAttributeInternal(SKUOPTION2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SkuOption2
   */
  public void setSkuOption2(String value)
  {
    setAttributeInternal(SKUOPTION2, value);
  }

  /**
   * 
   * Gets the attribute value for SkuOption3, using the alias name SkuOption3
   */
  public String getSkuOption3()
  {
    return (String)getAttributeInternal(SKUOPTION3);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SkuOption3
   */
  public void setSkuOption3(String value)
  {
    setAttributeInternal(SKUOPTION3, value);
  }

  /**
   * 
   * Gets the attribute value for AssetNumber, using the alias name AssetNumber
   */
  public String getAssetNumber()
  {
    return (String)getAttributeInternal(ASSETNUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AssetNumber
   */
  public void setAssetNumber(String value)
  {
    setAttributeInternal(ASSETNUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for CreationDate, using the alias name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * 
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for AopsCustNumber, using the alias name AopsCustNumber
   */
  public String getAopsCustNumber()
  {
    return (String)getAttributeInternal(AOPSCUSTNUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AopsCustNumber
   */
  public void setAopsCustNumber(String value)
  {
    setAttributeInternal(AOPSCUSTNUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for LevelLimit, using the alias name LevelLimit
   */
  public Number getLevelLimit()
  {
    return (Number)getAttributeInternal(LEVELLIMIT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LevelLimit
   */
  public void setLevelLimit(Number value)
  {
    setAttributeInternal(LEVELLIMIT, value);
  }

  /**
   * 
   * Gets the attribute value for PoNumber, using the alias name PoNumber
   */
  public String getPoNumber()
  {
    return (String)getAttributeInternal(PONUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PoNumber
   */
  public void setPoNumber(String value)
  {
    setAttributeInternal(PONUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for UsageSendLeadDays, using the alias name UsageSendLeadDays
   */
  public Number getUsageSendLeadDays()
  {
    return (Number)getAttributeInternal(USAGESENDLEADDAYS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for UsageSendLeadDays
   */
  public void setUsageSendLeadDays(Number value)
  {
    setAttributeInternal(USAGESENDLEADDAYS, value);
  }

  /**
   * 
   * Gets the attribute value for UsageDataSentDate, using the alias name UsageDataSentDate
   */
  public Date getUsageDataSentDate()
  {
    return (Date)getAttributeInternal(USAGEDATASENTDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for UsageDataSentDate
   */
  public void setUsageDataSentDate(Date value)
  {
    setAttributeInternal(USAGEDATASENTDATE, value);
  }

  /**
   * 
   * Gets the attribute value for PeriodCoveredStDate, using the alias name PeriodCoveredStDate
   */
  public Date getPeriodCoveredStDate()
  {
    return (Date)getAttributeInternal(PERIODCOVEREDSTDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PeriodCoveredStDate
   */
  public void setPeriodCoveredStDate(Date value)
  {
    setAttributeInternal(PERIODCOVEREDSTDATE, value);
  }

  /**
   * 
   * Gets the attribute value for PeriodCoveredEndDate, using the alias name PeriodCoveredEndDate
   */
  public Date getPeriodCoveredEndDate()
  {
    return (Date)getAttributeInternal(PERIODCOVEREDENDDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PeriodCoveredEndDate
   */
  public void setPeriodCoveredEndDate(Date value)
  {
    setAttributeInternal(PERIODCOVEREDENDDATE, value);
  }

  /**
   * 
   * Gets the attribute value for ModelId, using the alias name ModelId
   */
  public Number getModelId()
  {
    return (Number)getAttributeInternal(MODELID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ModelId
   */
  public void setModelId(Number value)
  {
    setAttributeInternal(MODELID, value);
  }

  /**
   * 
   * Gets the attribute value for BrandId, using the alias name BrandId
   */
  public Number getBrandId()
  {
    return (Number)getAttributeInternal(BRANDID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BrandId
   */
  public void setBrandId(Number value)
  {
    setAttributeInternal(BRANDID, value);
  }

  /**
   * 
   * Gets the attribute value for ColorAllowances, using the alias name ColorAllowances
   */
  public Number getColorAllowances()
  {
    return (Number)getAttributeInternal(COLORALLOWANCES);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ColorAllowances
   */
  public void setColorAllowances(Number value)
  {
    setAttributeInternal(COLORALLOWANCES, value);
  }

  /**
   * 
   * Gets the attribute value for ServiceCost, using the alias name ServiceCost
   */
  public Number getServiceCost()
  {
    return (Number)getAttributeInternal(SERVICECOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ServiceCost
   */
  public void setServiceCost(Number value)
  {
    setAttributeInternal(SERVICECOST, value);
  }

  /**
   * 
   * Gets the attribute value for ContractNumber, using the alias name ContractNumber
   */
  public String getContractNumber()
  {
    return (String)getAttributeInternal(CONTRACTNUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ContractNumber
   */
  public void setContractNumber(String value)
  {
    setAttributeInternal(CONTRACTNUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for ExpiredDate, using the alias name ExpiredDate
   */
  public Date getExpiredDate()
  {
    return (Date)getAttributeInternal(EXPIREDDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ExpiredDate
   */
  public void setExpiredDate(Date value)
  {
    setAttributeInternal(EXPIREDDATE, value);
  }

  public void setLastUpdateLogin(Number value)
  {
    
  } 
  /**
   * 
   * Gets the attribute value for RowID, using the alias name RowID
   */
  public RowID getRowID()
  {
    return (RowID)getAttributeInternal(ROWID);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case DEVICEID:
        return getDeviceId();
      case DEVICENAME:
        return getDeviceName();
      case GROUPID:
        return getGroupId();
      case GROUPNAME:
        return getGroupName();
      case SERIALNO:
        return getSerialNo();
      case IPADDRESS:
        return getIpAddress();
      case MANUFACTURER:
        return getManufacturer();
      case MODEL:
        return getModel();
      case PARTYID:
        return getPartyId();
      case PARTYNAME:
        return getPartyName();
      case SHIPSITEID:
        return getShipSiteId();
      case SITECONTACT:
        return getSiteContact();
      case SITECONTACTPHONE:
        return getSiteContactPhone();
      case SITEADDRESS1:
        return getSiteAddress1();
      case SITEADDRESS2:
        return getSiteAddress2();
      case SITECITY:
        return getSiteCity();
      case SITESTATE:
        return getSiteState();
      case SITEZIPCODE:
        return getSiteZipCode();
      case DEVICECONTACT:
        return getDeviceContact();
      case DEVICEPHONE:
        return getDevicePhone();
      case DEVICEFLOOR:
        return getDeviceFloor();
      case DEVICEROOM:
        return getDeviceRoom();
      case DEVICELOCATION:
        return getDeviceLocation();
      case DEVICECOSTCENTER:
        return getDeviceCostCenter();
      case DEVICEJIT:
        return getDeviceJit();
      case PROGRAMTYPE:
        return getProgramType();
      case MANAGEDSTATUS:
        return getManagedStatus();
      case SUPPORTCOVERAGE:
        return getSupportCoverage();
      case SLACOVERAGE:
        return getSlaCoverage();
      case MPSREPCOMMENTS:
        return getMpsRepComments();
      case BSDREPCOMMENTS:
        return getBsdRepComments();
      case ACTIVESTATUS:
        return getActiveStatus();
      case ATTRIBUTE1:
        return getAttribute1();
      case ATTRIBUTE2:
        return getAttribute2();
      case ATTRIBUTE3:
        return getAttribute3();
      case ATTRIBUTE4:
        return getAttribute4();
      case ATTRIBUTE5:
        return getAttribute5();
      case AVFSUBMIT:
        return getAvfSubmit();
      case BLACKCPC:
        return getBlackCpc();
      case COLORCPC:
        return getColorCpc();
      case ALLOWANCES:
        return getAllowances();
      case OVERAGECOST:
        return getOverageCost();
      case FLATRATE:
        return getFlatRate();
      case FLEETSYSTEM:
        return getFleetSystem();
      case NOTIFICATIONDATE:
        return getNotificationDate();
      case ESSENTIALSATRFLAG:
        return getEssentialsAtrFlag();
      case SKUOPTION1:
        return getSkuOption1();
      case SKUOPTION2:
        return getSkuOption2();
      case SKUOPTION3:
        return getSkuOption3();
      case ASSETNUMBER:
        return getAssetNumber();
      case CREATIONDATE:
        return getCreationDate();
      case CREATEDBY:
        return getCreatedBy();
      case LASTUPDATEDATE:
        return getLastUpdateDate();
      case LASTUPDATEDBY:
        return getLastUpdatedBy();
      case AOPSCUSTNUMBER:
        return getAopsCustNumber();
      case LEVELLIMIT:
        return getLevelLimit();
      case PONUMBER:
        return getPoNumber();
      case USAGESENDLEADDAYS:
        return getUsageSendLeadDays();
      case USAGEDATASENTDATE:
        return getUsageDataSentDate();
      case PERIODCOVEREDSTDATE:
        return getPeriodCoveredStDate();
      case PERIODCOVEREDENDDATE:
        return getPeriodCoveredEndDate();
      case MODELID:
        return getModelId();
      case BRANDID:
        return getBrandId();
      case COLORALLOWANCES:
        return getColorAllowances();
      case SERVICECOST:
        return getServiceCost();
      case CONTRACTNUMBER:
        return getContractNumber();
      case EXPIREDDATE:
        return getExpiredDate();
      case ROWID:
        return getRowID();
      case COLOROVERAGECOST:
        return getColorOverageCost();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case DEVICEID:
        setDeviceId((String)value);
        return;
      case DEVICENAME:
        setDeviceName((String)value);
        return;
      case GROUPID:
        setGroupId((String)value);
        return;
      case GROUPNAME:
        setGroupName((String)value);
        return;
      case SERIALNO:
        setSerialNo((String)value);
        return;
      case IPADDRESS:
        setIpAddress((String)value);
        return;
      case MANUFACTURER:
        setManufacturer((String)value);
        return;
      case MODEL:
        setModel((String)value);
        return;
      case PARTYID:
        setPartyId((Number)value);
        return;
      case PARTYNAME:
        setPartyName((String)value);
        return;
      case SHIPSITEID:
        setShipSiteId((Number)value);
        return;
      case SITECONTACT:
        setSiteContact((String)value);
        return;
      case SITECONTACTPHONE:
        setSiteContactPhone((String)value);
        return;
      case SITEADDRESS1:
        setSiteAddress1((String)value);
        return;
      case SITEADDRESS2:
        setSiteAddress2((String)value);
        return;
      case SITECITY:
        setSiteCity((String)value);
        return;
      case SITESTATE:
        setSiteState((String)value);
        return;
      case SITEZIPCODE:
        setSiteZipCode((String)value);
        return;
      case DEVICECONTACT:
        setDeviceContact((String)value);
        return;
      case DEVICEPHONE:
        setDevicePhone((String)value);
        return;
      case DEVICEFLOOR:
        setDeviceFloor((String)value);
        return;
      case DEVICEROOM:
        setDeviceRoom((String)value);
        return;
      case DEVICELOCATION:
        setDeviceLocation((String)value);
        return;
      case DEVICECOSTCENTER:
        setDeviceCostCenter((String)value);
        return;
      case DEVICEJIT:
        setDeviceJit((String)value);
        return;
      case PROGRAMTYPE:
        setProgramType((String)value);
        return;
      case MANAGEDSTATUS:
        setManagedStatus((String)value);
        return;
      case SUPPORTCOVERAGE:
        setSupportCoverage((String)value);
        return;
      case SLACOVERAGE:
        setSlaCoverage((String)value);
        return;
      case MPSREPCOMMENTS:
        setMpsRepComments((String)value);
        return;
      case BSDREPCOMMENTS:
        setBsdRepComments((String)value);
        return;
      case ACTIVESTATUS:
        setActiveStatus((String)value);
        return;
      case ATTRIBUTE1:
        setAttribute1((String)value);
        return;
      case ATTRIBUTE2:
        setAttribute2((String)value);
        return;
      case ATTRIBUTE3:
        setAttribute3((String)value);
        return;
      case ATTRIBUTE4:
        setAttribute4((String)value);
        return;
      case ATTRIBUTE5:
        setAttribute5((String)value);
        return;
      case AVFSUBMIT:
        setAvfSubmit((String)value);
        return;
      case BLACKCPC:
        setBlackCpc((Number)value);
        return;
      case COLORCPC:
        setColorCpc((Number)value);
        return;
      case ALLOWANCES:
        setAllowances((Number)value);
        return;
      case OVERAGECOST:
        setOverageCost((Number)value);
        return;
      case FLATRATE:
        setFlatRate((Number)value);
        return;
      case FLEETSYSTEM:
        setFleetSystem((String)value);
        return;
      case NOTIFICATIONDATE:
        setNotificationDate((Date)value);
        return;
      case ESSENTIALSATRFLAG:
        setEssentialsAtrFlag((String)value);
        return;
      case SKUOPTION1:
        setSkuOption1((String)value);
        return;
      case SKUOPTION2:
        setSkuOption2((String)value);
        return;
      case SKUOPTION3:
        setSkuOption3((String)value);
        return;
      case ASSETNUMBER:
        setAssetNumber((String)value);
        return;
      case CREATIONDATE:
        setCreationDate((Date)value);
        return;
      case CREATEDBY:
        setCreatedBy((Number)value);
        return;
      case LASTUPDATEDATE:
        setLastUpdateDate((Date)value);
        return;
      case LASTUPDATEDBY:
        setLastUpdatedBy((Number)value);
        return;
      case AOPSCUSTNUMBER:
        setAopsCustNumber((String)value);
        return;
      case LEVELLIMIT:
        setLevelLimit((Number)value);
        return;
      case PONUMBER:
        setPoNumber((String)value);
        return;
      case USAGESENDLEADDAYS:
        setUsageSendLeadDays((Number)value);
        return;
      case USAGEDATASENTDATE:
        setUsageDataSentDate((Date)value);
        return;
      case PERIODCOVEREDSTDATE:
        setPeriodCoveredStDate((Date)value);
        return;
      case PERIODCOVEREDENDDATE:
        setPeriodCoveredEndDate((Date)value);
        return;
      case MODELID:
        setModelId((Number)value);
        return;
      case BRANDID:
        setBrandId((Number)value);
        return;
      case COLORALLOWANCES:
        setColorAllowances((Number)value);
        return;
      case SERVICECOST:
        setServiceCost((Number)value);
        return;
      case CONTRACTNUMBER:
        setContractNumber((String)value);
        return;
      case EXPIREDDATE:
        setExpiredDate((Date)value);
        return;
      case COLOROVERAGECOST:
        setColorOverageCost((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the attribute value for ColorOverageCost, using the alias name ColorOverageCost
   */
  public Number getColorOverageCost()
  {
    return (Number)getAttributeInternal(COLOROVERAGECOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ColorOverageCost
   */
  public void setColorOverageCost(Number value)
  {
    setAttributeInternal(COLOROVERAGECOST, value);
  }
}