<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="CreatePartsQuotation"
     targetNamespace="http://xmlns.officedepot.com/TDS/PartQuotationInboundProvABCSImpl/CreatePartsQuotation"
     xmlns:ns2="http://xmlns.officedepot.com/TDS/PartQuotationInboundProvABCSImpl/PartsQuotationResponseEBM"
     xmlns:ns1="http://xmlns.officedepot.com/TDS/PartQuotationInboundProvABCSImpl/PartsQuotationEBM"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:ns3="http://www.officedepot.com/officedepot/ODComnErrorStructure/1.0"
     xmlns:client="http://xmlns.officedepot.com/TDS/PartQuotationInboundProvABCSImpl/CreatePartsQuotation"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="CreatePartsQuotation">
        <plnk:role name="CreatePartsQuotationProvider">
            <plnk:portType name="client:CreatePartsQuotation"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.officedepot.com/TDS/PartQuotationInboundProvABCSImpl/PartsQuotationEBM"
                 schemaLocation="xsd/PartsQuotationEBM.xsd"/>
        </schema>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.officedepot.com/TDS/PartQuotationInboundProvABCSImpl/PartsQuotationResponseEBM"
                 schemaLocation="xsd/PartsQuotationResponseEBM.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.officedepot.com/officedepot/ODComnErrorStructure/1.0"
                 schemaLocation="oramds:/apps/ODCommon/xmllib/common/error/xsd/ODComnErrorStructure.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="CreatePartsQuotationRequestMessage">
        <wsdl:part name="payload" element="ns1:PartsQuotationEBM"/>
    </wsdl:message>
    <wsdl:message name="CreatePartsQuotationResponseMessage">
        <wsdl:part name="payload" element="ns2:PartsQuotationResponseEBM"/>
    </wsdl:message>
    <wsdl:portType name="CreatePartsQuotation">
        <wsdl:operation name="createPartsQuotation">
            <wsdl:input message="client:CreatePartsQuotationRequestMessage"/>
            <wsdl:output message="client:CreatePartsQuotationResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
