DROP TYPE XX_OM_CARTONIZATION_WMS_PKG_6 FORCE; 
show errors
DROP TYPE XXOMCARTONIZATIONWMSPKG4_XX_O FORCE; 
show errors
DROP TYPE XX_OM_CARTONIZATION_WMS_PKG_4 FORCE; 
show errors
DROP TYPE XXOMCARTONIZATIONWMSPKG2_XX_O FORCE; 
show errors
DROP TYPE XX_OM_CARTONIZATION_WMS_PKG_2 FORCE; 
show errors
DROP TYPE XX_OM_CARTONIZATION_WMS_PKG_X FORCE; 
show errors
DROP PACKAGE BPEL_CARTONIZATION4WMS;
exit
