<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="SynchEmployeePSFTReqABCSImpl" targetNamespace="http://xmlns.oracle.com/PeopleSoftMigration/SynchEmployeePSFTReqABCS/SynchEmployeePSFTReqABCSImpl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/PeopleSoftMigration/SynchEmployeePSFTReqABCS/SynchEmployeePSFTReqABCSImpl" xmlns:ns1="http://xmlns.oracle.com/ApplicationMessage/HR/Custom/ABM/SyncEmployeeABM/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:psft="http://xmlns.oracle.com/Enterprise/Tools/services">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/Enterprise/Tools/services" schemaLocation="xsd/OD_EMPDATA_ASYNC_PUB.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="SynchEmployeePSFTReqABCSImplRequestMessage">
      <wsdl:part name="payload" element="psft:OD_EMPDATA_ASYNC_PUB"/>
   </wsdl:message>
   <wsdl:portType name="SynchEmployeePSFTReqABCSImpl">
      <wsdl:operation name="syncEmployee">
         <wsdl:input message="client:SynchEmployeePSFTReqABCSImplRequestMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="SynchEmployeePSFTReqABCSImpl">
      <plnk:role name="SynchEmployeePSFTReqABCSImplProvider">
         <plnk:portType name="client:SynchEmployeePSFTReqABCSImpl"/>
      </plnk:role>
   </plnk:partnerLinkType>
</wsdl:definitions>
