<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="UpdateEmployeeErrorCallBackPSFTProvABCS" targetNamespace="http://xmlns.oracle.com/PeopleSoftMigration/UpdateEmployeeErrorCallBackPSFTProvABCS/UpdateEmployeeErrorCallBackPSFTProvABCS" xmlns:ns1="http://xmlns.officedepot.com/PeopleSoftMigration/UpdateEmployeeErrorCallBackPSFTProvABCS/UpdateEmployeeErrorToPSFTEBM" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:client="http://xmlns.oracle.com/PeopleSoftMigration/UpdateEmployeeErrorCallBackPSFTProvABCS/UpdateEmployeeErrorCallBackPSFTProvABCS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <wsdl:documentation>
      <abstractWSDL>http://soadev01.na.odcorp.net/soa-infra/services/hr_rt/UpdateEmployeeErrorCallBackPSFTProvABCS!2.0/UpdateEmployeeErrorCallBackPSFTProvABCS.wsdl</abstractWSDL>
   </wsdl:documentation>
   <plnk:partnerLinkType name="UpdateEmployeeErrorCallBackPSFTProvABCS">
      <plnk:role name="UpdateEmployeeErrorCallBackPSFTProvABCSProvider" portType="client:UpdateEmployeeErrorCallBackPSFTProvABCS"/>
   </plnk:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.officedepot.com/PeopleSoftMigration/UpdateEmployeeErrorCallBackPSFTProvABCS/UpdateEmployeeErrorToPSFTEBM" schemaLocation="xsd/UpdateEmployeeErrorToPeopleSoftEBM.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="UpdateEmployeeErrorCallBackPSFTProvABCSRequestMessage">
      <wsdl:part name="payload" element="ns1:UpdateEmployeeErrorToPSFTEBM"/>
   </wsdl:message>
   <wsdl:portType name="UpdateEmployeeErrorCallBackPSFTProvABCS">
      <wsdl:operation name="updateEmployeeErrorDetailsToPSFT">
         <wsdl:input message="client:UpdateEmployeeErrorCallBackPSFTProvABCSRequestMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="UpdateEmployeeErrorCallBackPSFTProvABCSBinding" type="client:UpdateEmployeeErrorCallBackPSFTProvABCS">
      <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="updateEmployeeErrorDetailsToPSFT">
         <soap:operation style="document" soapAction="updateEmployeeErrorDetailsToPSFT"/>
         <wsdl:input>
            <soap:body use="literal" namespace="http://xmlns.oracle.com/PeopleSoftMigration/UpdateEmployeeErrorCallBackPSFTProvABCS/UpdateEmployeeErrorCallBackPSFTProvABCS"/>
         </wsdl:input>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="UpdateEmployeeErrorCallBackPSFTProvABCSImpl_client_ep_ep">
      <wsdl:port name="UpdateEmployeeErrorCallBackPSFTProvABCS_pt" binding="client:UpdateEmployeeErrorCallBackPSFTProvABCSBinding">
         <soap:address location="http://soadev01.na.odcorp.net:80/soa-infra/services/hr_rt/UpdateEmployeeErrorCallBackPSFTProvABCS!2.0*soa_ed7725dd-61a0-4dd3-831f-00b273fab87b/UpdateEmployeeErrorCallBackPSFTProvABCSImpl_client_ep_ep"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
