/*===========================================================================+
 |      		       Office Depot - Project Simplify                           |
 |            Oracle NAIO/WIPRO/Office Depot/Consulting Organization         |
 +===========================================================================+
 |  FILENAME                                                                 |
 |             ODFlexfieldInfoVOImpl.java                                    |
 |                                                                           |
 |  DESCRIPTION                                                              |
 |    View Object Class to display the DFF values                            |
 |                                                                           |
 |  NOTES                                                                    |
 |                                                                           |
 |                                                                           |
 |  DEPENDENCIES                                                             |
 |    This class file is built on ODFlexfieldInfoEOImpl.java                 |
 |    This class is invoked from ODSoftAcctAMImpl.java                       |
 |                                                                           |
 |  HISTORY                                                                  |
 |                                                                           |
 |    04/03/2007     Sathya Prabha Rani       Created                        |
 |                                                                           |
 +===========================================================================*/

package od.oracle.apps.xxcrm.imc.softacct.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class ODFlexfieldInfoVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public ODFlexfieldInfoVOImpl()
  {
  }
}