package od.oracle.apps.xxcrm.cdh.uploads.bulk.server;
/* Subversion Info:
 * $HeadURL: http://svn.na.odcorp.net/svn/od/common/trunk/xxcomn/java/od/oracle/apps/xxcrm/cdh/uploads/bulk/server/ODImportToolTempVORowImpl.java $
 * $Rev: 260139 $
 * $Date: 2016-11-10 05:11:27 -0500 (Thu, 10 Nov 2016) $
*/
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.ClobDomain;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class ODImportToolTempVORowImpl extends OAViewRowImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public ODImportToolTempVORowImpl()
  {
  }
}