<?binding.jca UpdateSupplierGSSDBAdaptorV1_db.jca?>
<wsdl:definitions name="UpdateSupplierGSSDBAdaptorV1" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/VendorSynch/SynchSupplierGSSProvABCS/UpdateSupplierGSSDBAdaptorV1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/VendorSynch/SynchSupplierGSSProvABCS/UpdateSupplierGSSDBAdaptorV1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateSupplierGSSDBAdaptorV1">
    <plt:partnerLinkType name="UpdateSupplierGSSDBAdaptorV1_plt">
        <plt:role name="UpdateSupplierGSSDBAdaptorV1_role">
            <plt:portType name="tns:UpdateSupplierGSSDBAdaptorV1_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateSupplierGSSDBAdaptorV1" schemaLocation="xsd/UpdateSupplierGSSDBAdaptorV1_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="XxApGsapvenCollection_msg">
        <wsdl:part name="XxApGsapvenCollection" element="top:XxApGsapvenCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateSupplierGSSDBAdaptorV1_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:XxApGsapvenCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
