<definitions
     name="FTPNonStdFileGet"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/FTPNonStdFileGet/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/FTPNonStdFileGet/"
     xmlns:ns1="http://schemas.oracle.com/service/bpel/common"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:imp1="http://xmlns.oracle.com/pcbpel/adapter/file/attachment/"
     xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/ftp/"
    >
    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/" location="ftpAdapterInboundHeader.wsdl"/>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/file/attachment/" schemaLocation="attachment.xsd"/>
        </schema>
    </types>
    <message name="attachmentElement_msg">
        <part name="attachmentElement" element="imp1:attachmentElement"/>
    </message>
    <portType name="Get_ptt">
        <operation name="Get">
            <input message="tns:attachmentElement_msg"/>
        </operation>
    </portType>
    <binding name="Get_binding" type="tns:Get_ptt">
        <pc:inbound_binding/>
        <operation name="Get">
            <jca:operation FileType="ascii" LogicalDirectory="Inbound_Path" ActivationSpec="oracle.tip.adapter.ftp.inbound.FTPActivationSpec"
                 LogicalArchiveDirectory="Archive_Path" DeleteFile="true" IncludeFiles="AP_.*\.txt"
                 PollingFrequency="600" MinimumAge="100" FileModificationTime="FileSystem"
                 ModificationTimeFormat="4,18,yyyyMMddHHmmSS" OpaqueSchema="false" AsAttachment="true"/>
            <input>
                <jca:header message="hdr:InboundHeader_msg" part="inboundHeader"/>
            </input>
        </operation>
    </binding>
    <service name="FTPNonStdFileGet">
        <port name="Get_pt" binding="tns:Get_binding">
            <jca:address location="eis/ftp/EBSCentralExternal" UIincludeWildcard="AP_*.txt"/>
        </port>
    </service>
    <plt:partnerLinkType name="Get_plt">
        <plt:role name="Get_role">
            <plt:portType name="tns:Get_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
</definitions>
