<wsdl:definitions targetNamespace="http://officedepot.com/SendNotificationService" name="Email" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ems="http://officedepot.com/SendNotificationService" xmlns:emd="http://officedepot.com/SendNotificationService">
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://officedepot.com/SendNotificationService" schemaLocation="../schema/SendNotificationService.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="sendEmail">
		<wsdl:part name="sendEmail" element="emd:sendEmail"/>
	</wsdl:message>
	
	<wsdl:message name="sendEmailResponse">
		<wsdl:part name="sendEmailResponse" element="emd:sendEmailResponse"/>
	</wsdl:message>
	
	<wsdl:message name="sendEmailFault">
		<wsdl:part name="sendEmailFault" element="emd:sendEmailFault"/>
	</wsdl:message>
	
	<wsdl:portType name="EmailPort">
		<wsdl:operation name="sendEmail">
			<wsdl:input name="sendEmail" message="ems:sendEmail"/>
			<wsdl:output name="sendEmailResponse" message="ems:sendEmailResponse"/>
			<wsdl:fault name="sendEmailFault" message="ems:sendEmailFault"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="EmailBinding" type="ems:EmailPort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="sendEmail">
			<soap:operation soapAction=""/>
			<wsdl:input name="sendEmail">
				<soap:body parts="sendEmail" use="literal"/>
			</wsdl:input>
			<wsdl:output name="sendEmailResponse">
				<soap:body parts="sendEmailResponse" use="literal"/>
			</wsdl:output>
			<wsdl:fault name="sendEmailFault">
				<soap:fault name="sendEmailFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="EmailService">
		<wsdl:port name="EmailPort" binding="ems:EmailBinding">
			<soap:address location="http://officedepot.com/NotificationService"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>