package od.oracle.apps.xxcrm.mps.reports.server;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class XXCSMPSIncidentsOpenVORowImpl extends OAViewRowImpl 
{




  protected static final int PARTYNAME = 0;
  protected static final int AOPSCUSTNUMBER = 1;
  protected static final int INCIDENTNUMBER = 2;
  protected static final int STATUS = 3;
  protected static final int SUMMARY = 4;
  protected static final int OWNER = 5;
  protected static final int SRTYPE = 6;
  protected static final int URGENCY = 7;
  protected static final int SEVERITY = 8;
  protected static final int PROBLEMCODE = 9;
  protected static final int RESOLUTIONCODE = 10;
  protected static final int EXPECTEDRESOLUTIONDATE = 11;
  protected static final int EXPRESOLVEDATE = 12;
  protected static final int ORIGINALORDERNUMBER = 13;
  protected static final int INCRESPONDEDBYDATE = 14;
  protected static final int CREATIONDATE = 15;
  protected static final int CREATEDBY = 16;
  protected static final int RESOLUTIONDESCRIPTION = 17;
  protected static final int ATTRIBUTE7 = 18;
  protected static final int INCIDENTSTATUS = 19;
  protected static final int INCIDENTSTATUSTYPE = 20;
  protected static final int INCIDENTTYPEID = 21;
  protected static final int INCIDENTSTATUSID = 22;
  protected static final int DEVICELOCATION = 23;
  protected static final int DEVICECOSTCENTER = 24;
  protected static final int MODEL = 25;
  protected static final int IPADDRESS = 26;
  protected static final int DEVICECONTACT = 27;
  protected static final int DEVICEPHONE = 28;
  protected static final int PROGRAMTYPE = 29;
  protected static final int SITEADDRESS1 = 30;
  protected static final int SITECITY = 31;
  protected static final int SITESTATE = 32;
  protected static final int SITEZIPCODE = 33;
  protected static final int SERIALNO = 34;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public XXCSMPSIncidentsOpenVORowImpl()
  {
  }


























  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case PARTYNAME:
        return getPartyName();
      case AOPSCUSTNUMBER:
        return getAopsCustNumber();
      case INCIDENTNUMBER:
        return getIncidentNumber();
      case STATUS:
        return getStatus();
      case SUMMARY:
        return getSummary();
      case OWNER:
        return getOwner();
      case SRTYPE:
        return getSrType();
      case URGENCY:
        return getUrgency();
      case SEVERITY:
        return getSeverity();
      case PROBLEMCODE:
        return getProblemCode();
      case RESOLUTIONCODE:
        return getResolutionCode();
      case EXPECTEDRESOLUTIONDATE:
        return getExpectedResolutionDate();
      case EXPRESOLVEDATE:
        return getExpResolveDate();
      case ORIGINALORDERNUMBER:
        return getOriginalOrderNumber();
      case INCRESPONDEDBYDATE:
        return getIncRespondedByDate();
      case CREATIONDATE:
        return getCreationDate();
      case CREATEDBY:
        return getCreatedby();
      case RESOLUTIONDESCRIPTION:
        return getResolutionDescription();
      case ATTRIBUTE7:
        return getAttribute7();
      case INCIDENTSTATUS:
        return getIncidentStatus();
      case INCIDENTSTATUSTYPE:
        return getIncidentStatusType();
      case INCIDENTTYPEID:
        return getIncidentTypeId();
      case INCIDENTSTATUSID:
        return getIncidentStatusId();
      case DEVICELOCATION:
        return getDeviceLocation();
      case DEVICECOSTCENTER:
        return getDeviceCostCenter();
      case MODEL:
        return getModel();
      case IPADDRESS:
        return getIpAddress();
      case DEVICECONTACT:
        return getDeviceContact();
      case DEVICEPHONE:
        return getDevicePhone();
      case PROGRAMTYPE:
        return getProgramType();
      case SITEADDRESS1:
        return getSiteAddress1();
      case SITECITY:
        return getSiteCity();
      case SITESTATE:
        return getSiteState();
      case SITEZIPCODE:
        return getSiteZipCode();
      case SERIALNO:
        return getSerialNo();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case PARTYNAME:
        setPartyName((String)value);
        return;
      case AOPSCUSTNUMBER:
        setAopsCustNumber((String)value);
        return;
      case INCIDENTNUMBER:
        setIncidentNumber((String)value);
        return;
      case STATUS:
        setStatus((String)value);
        return;
      case SUMMARY:
        setSummary((String)value);
        return;
      case OWNER:
        setOwner((String)value);
        return;
      case SRTYPE:
        setSrType((String)value);
        return;
      case URGENCY:
        setUrgency((String)value);
        return;
      case SEVERITY:
        setSeverity((String)value);
        return;
      case PROBLEMCODE:
        setProblemCode((String)value);
        return;
      case RESOLUTIONCODE:
        setResolutionCode((String)value);
        return;
      case EXPECTEDRESOLUTIONDATE:
        setExpectedResolutionDate((Date)value);
        return;
      case EXPRESOLVEDATE:
        setExpResolveDate((Date)value);
        return;
      case ORIGINALORDERNUMBER:
        setOriginalOrderNumber((Number)value);
        return;
      case INCRESPONDEDBYDATE:
        setIncRespondedByDate((Date)value);
        return;
      case CREATIONDATE:
        setCreationDate((Date)value);
        return;
      case CREATEDBY:
        setCreatedby((String)value);
        return;
      case RESOLUTIONDESCRIPTION:
        setResolutionDescription((String)value);
        return;
      case ATTRIBUTE7:
        setAttribute7((String)value);
        return;
      case INCIDENTSTATUS:
        setIncidentStatus((String)value);
        return;
      case INCIDENTSTATUSTYPE:
        setIncidentStatusType((String)value);
        return;
      case INCIDENTTYPEID:
        setIncidentTypeId((Number)value);
        return;
      case INCIDENTSTATUSID:
        setIncidentStatusId((Number)value);
        return;
      case DEVICELOCATION:
        setDeviceLocation((String)value);
        return;
      case DEVICECOSTCENTER:
        setDeviceCostCenter((String)value);
        return;
      case MODEL:
        setModel((String)value);
        return;
      case IPADDRESS:
        setIpAddress((String)value);
        return;
      case DEVICECONTACT:
        setDeviceContact((String)value);
        return;
      case DEVICEPHONE:
        setDevicePhone((String)value);
        return;
      case PROGRAMTYPE:
        setProgramType((String)value);
        return;
      case SITEADDRESS1:
        setSiteAddress1((String)value);
        return;
      case SITECITY:
        setSiteCity((String)value);
        return;
      case SITESTATE:
        setSiteState((String)value);
        return;
      case SITEZIPCODE:
        setSiteZipCode((String)value);
        return;
      case SERIALNO:
        setSerialNo((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute PartyName
   */
  public String getPartyName()
  {
    return (String)getAttributeInternal(PARTYNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute PartyName
   */
  public void setPartyName(String value)
  {
    setAttributeInternal(PARTYNAME, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute AopsCustNumber
   */
  public String getAopsCustNumber()
  {
    return (String)getAttributeInternal(AOPSCUSTNUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute AopsCustNumber
   */
  public void setAopsCustNumber(String value)
  {
    setAttributeInternal(AOPSCUSTNUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute IncidentNumber
   */
  public String getIncidentNumber()
  {
    return (String)getAttributeInternal(INCIDENTNUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute IncidentNumber
   */
  public void setIncidentNumber(String value)
  {
    setAttributeInternal(INCIDENTNUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Status
   */
  public String getStatus()
  {
    return (String)getAttributeInternal(STATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Status
   */
  public void setStatus(String value)
  {
    setAttributeInternal(STATUS, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Summary
   */
  public String getSummary()
  {
    return (String)getAttributeInternal(SUMMARY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Summary
   */
  public void setSummary(String value)
  {
    setAttributeInternal(SUMMARY, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Owner
   */
  public String getOwner()
  {
    return (String)getAttributeInternal(OWNER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Owner
   */
  public void setOwner(String value)
  {
    setAttributeInternal(OWNER, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute SrType
   */
  public String getSrType()
  {
    return (String)getAttributeInternal(SRTYPE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute SrType
   */
  public void setSrType(String value)
  {
    setAttributeInternal(SRTYPE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Urgency
   */
  public String getUrgency()
  {
    return (String)getAttributeInternal(URGENCY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Urgency
   */
  public void setUrgency(String value)
  {
    setAttributeInternal(URGENCY, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Severity
   */
  public String getSeverity()
  {
    return (String)getAttributeInternal(SEVERITY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Severity
   */
  public void setSeverity(String value)
  {
    setAttributeInternal(SEVERITY, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ProblemCode
   */
  public String getProblemCode()
  {
    return (String)getAttributeInternal(PROBLEMCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ProblemCode
   */
  public void setProblemCode(String value)
  {
    setAttributeInternal(PROBLEMCODE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ResolutionCode
   */
  public String getResolutionCode()
  {
    return (String)getAttributeInternal(RESOLUTIONCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ResolutionCode
   */
  public void setResolutionCode(String value)
  {
    setAttributeInternal(RESOLUTIONCODE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ExpectedResolutionDate
   */
  public Date getExpectedResolutionDate()
  {
    return (Date)getAttributeInternal(EXPECTEDRESOLUTIONDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ExpectedResolutionDate
   */
  public void setExpectedResolutionDate(Date value)
  {
    setAttributeInternal(EXPECTEDRESOLUTIONDATE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ExpResolveDate
   */
  public Date getExpResolveDate()
  {
    return (Date)getAttributeInternal(EXPRESOLVEDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ExpResolveDate
   */
  public void setExpResolveDate(Date value)
  {
    setAttributeInternal(EXPRESOLVEDATE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute OriginalOrderNumber
   */
  public Number getOriginalOrderNumber()
  {
    return (Number)getAttributeInternal(ORIGINALORDERNUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute OriginalOrderNumber
   */
  public void setOriginalOrderNumber(Number value)
  {
    setAttributeInternal(ORIGINALORDERNUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute IncRespondedByDate
   */
  public Date getIncRespondedByDate()
  {
    return (Date)getAttributeInternal(INCRESPONDEDBYDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute IncRespondedByDate
   */
  public void setIncRespondedByDate(Date value)
  {
    setAttributeInternal(INCRESPONDEDBYDATE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Createdby
   */
  public String getCreatedby()
  {
    return (String)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Createdby
   */
  public void setCreatedby(String value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ResolutionDescription
   */
  public String getResolutionDescription()
  {
    return (String)getAttributeInternal(RESOLUTIONDESCRIPTION);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ResolutionDescription
   */
  public void setResolutionDescription(String value)
  {
    setAttributeInternal(RESOLUTIONDESCRIPTION, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Attribute7
   */
  public String getAttribute7()
  {
    return (String)getAttributeInternal(ATTRIBUTE7);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Attribute7
   */
  public void setAttribute7(String value)
  {
    setAttributeInternal(ATTRIBUTE7, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute IncidentStatus
   */
  public String getIncidentStatus()
  {
    return (String)getAttributeInternal(INCIDENTSTATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute IncidentStatus
   */
  public void setIncidentStatus(String value)
  {
    setAttributeInternal(INCIDENTSTATUS, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute IncidentStatusType
   */
  public String getIncidentStatusType()
  {
    return (String)getAttributeInternal(INCIDENTSTATUSTYPE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute IncidentStatusType
   */
  public void setIncidentStatusType(String value)
  {
    setAttributeInternal(INCIDENTSTATUSTYPE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute IncidentTypeId
   */
  public Number getIncidentTypeId()
  {
    return (Number)getAttributeInternal(INCIDENTTYPEID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute IncidentTypeId
   */
  public void setIncidentTypeId(Number value)
  {
    setAttributeInternal(INCIDENTTYPEID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute IncidentStatusId
   */
  public Number getIncidentStatusId()
  {
    return (Number)getAttributeInternal(INCIDENTSTATUSID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute IncidentStatusId
   */
  public void setIncidentStatusId(Number value)
  {
    setAttributeInternal(INCIDENTSTATUSID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute DeviceLocation
   */
  public String getDeviceLocation()
  {
    return (String)getAttributeInternal(DEVICELOCATION);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute DeviceLocation
   */
  public void setDeviceLocation(String value)
  {
    setAttributeInternal(DEVICELOCATION, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute DeviceCostCenter
   */
  public String getDeviceCostCenter()
  {
    return (String)getAttributeInternal(DEVICECOSTCENTER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute DeviceCostCenter
   */
  public void setDeviceCostCenter(String value)
  {
    setAttributeInternal(DEVICECOSTCENTER, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Model
   */
  public String getModel()
  {
    return (String)getAttributeInternal(MODEL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Model
   */
  public void setModel(String value)
  {
    setAttributeInternal(MODEL, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute IpAddress
   */
  public String getIpAddress()
  {
    return (String)getAttributeInternal(IPADDRESS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute IpAddress
   */
  public void setIpAddress(String value)
  {
    setAttributeInternal(IPADDRESS, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute DeviceContact
   */
  public String getDeviceContact()
  {
    return (String)getAttributeInternal(DEVICECONTACT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute DeviceContact
   */
  public void setDeviceContact(String value)
  {
    setAttributeInternal(DEVICECONTACT, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute DevicePhone
   */
  public String getDevicePhone()
  {
    return (String)getAttributeInternal(DEVICEPHONE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute DevicePhone
   */
  public void setDevicePhone(String value)
  {
    setAttributeInternal(DEVICEPHONE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ProgramType
   */
  public String getProgramType()
  {
    return (String)getAttributeInternal(PROGRAMTYPE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ProgramType
   */
  public void setProgramType(String value)
  {
    setAttributeInternal(PROGRAMTYPE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute SiteAddress1
   */
  public String getSiteAddress1()
  {
    return (String)getAttributeInternal(SITEADDRESS1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute SiteAddress1
   */
  public void setSiteAddress1(String value)
  {
    setAttributeInternal(SITEADDRESS1, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute SiteCity
   */
  public String getSiteCity()
  {
    return (String)getAttributeInternal(SITECITY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute SiteCity
   */
  public void setSiteCity(String value)
  {
    setAttributeInternal(SITECITY, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute SiteState
   */
  public String getSiteState()
  {
    return (String)getAttributeInternal(SITESTATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute SiteState
   */
  public void setSiteState(String value)
  {
    setAttributeInternal(SITESTATE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute SiteZipCode
   */
  public String getSiteZipCode()
  {
    return (String)getAttributeInternal(SITEZIPCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute SiteZipCode
   */
  public void setSiteZipCode(String value)
  {
    setAttributeInternal(SITEZIPCODE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute SerialNo
   */
  public String getSerialNo()
  {
    return (String)getAttributeInternal(SERIALNO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute SerialNo
   */
  public void setSerialNo(String value)
  {
    setAttributeInternal(SERIALNO, value);
  }

































































}