package od.oracle.apps.xxcrm.cdh.uploads.poplist.server;
/* Subversion Info:
 * $HeadURL$
 * $Rev$
 * $Date$
*/
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class ODImportToolTemplatePVORowImpl extends OAViewRowImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public ODImportToolTemplatePVORowImpl()
  {
  }
}