package od.oracle.apps.xxcrm.addattr.tempcl.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ODCurrencyVORowImpl extends OAViewRowImpl {
    public static final int CURRENCYCODE = 0;
    public static final int ACCOUNTNUMBER = 1;
    public static final int CUSTACCOUNTID = 2;
    public static final int CUSTACCOUNTPROFILEID = 3;
    public static final int CUSTACCTPROFILEAMTID = 4;

    /**This is the default constructor (do not remove)
     */
    public ODCurrencyVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute CurrencyCode
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CurrencyCode
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**Gets the attribute value for the calculated attribute AccountNumber
     */
    public String getAccountNumber() {
        return (String) getAttributeInternal(ACCOUNTNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AccountNumber
     */
    public void setAccountNumber(String value) {
        setAttributeInternal(ACCOUNTNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute CustAccountId
     */
    public Number getCustAccountId() {
        return (Number) getAttributeInternal(CUSTACCOUNTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CustAccountId
     */
    public void setCustAccountId(Number value) {
        setAttributeInternal(CUSTACCOUNTID, value);
    }

    /**Gets the attribute value for the calculated attribute CustAccountProfileId
     */
    public Number getCustAccountProfileId() {
        return (Number) getAttributeInternal(CUSTACCOUNTPROFILEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CustAccountProfileId
     */
    public void setCustAccountProfileId(Number value) {
        setAttributeInternal(CUSTACCOUNTPROFILEID, value);
    }

    /**Gets the attribute value for the calculated attribute CustAcctProfileAmtId
     */
    public Number getCustAcctProfileAmtId() {
        return (Number) getAttributeInternal(CUSTACCTPROFILEAMTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CustAcctProfileAmtId
     */
    public void setCustAcctProfileAmtId(Number value) {
        setAttributeInternal(CUSTACCTPROFILEAMTID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CURRENCYCODE:
            return getCurrencyCode();
        case ACCOUNTNUMBER:
            return getAccountNumber();
        case CUSTACCOUNTID:
            return getCustAccountId();
        case CUSTACCOUNTPROFILEID:
            return getCustAccountProfileId();
        case CUSTACCTPROFILEAMTID:
            return getCustAcctProfileAmtId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CURRENCYCODE:
            setCurrencyCode((String)value);
            return;
        case ACCOUNTNUMBER:
            setAccountNumber((String)value);
            return;
        case CUSTACCOUNTID:
            setCustAccountId((Number)value);
            return;
        case CUSTACCOUNTPROFILEID:
            setCustAccountProfileId((Number)value);
            return;
        case CUSTACCTPROFILEAMTID:
            setCustAcctProfileAmtId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
