-- Declare the SQL type for the PL/SQL type ROWTYPE_PL9
-- uncomment to overwrite existing types
-- CREATE OR REPLACE TYPE XX_CS_TDS_AP_INX1326404X1X98 AS OBJECT (
--       INVOICE_ID NUMBER(15),
--       INVOICE_LINE_ID NUMBER(15),
--       LINE_NUMBER NUMBER(15),
--       LINE_TYPE_LOOKUP_CODE VARCHAR2(25),
--       LINE_GROUP_NUMBER NUMBER,
--       AMOUNT NUMBER,
--       ACCOUNTING_DATE DATE,
--       DESCRIPTION VARCHAR2(240),
--       AMOUNT_INCLUDES_TAX_FLAG VARCHAR2(1),
--       PRORATE_ACROSS_FLAG VARCHAR2(1),
--       TAX_CODE VARCHAR2(15),
--       FINAL_MATCH_FLAG VARCHAR2(1),
--       PO_HEADER_ID NUMBER,
--       PO_NUMBER VARCHAR2(20),
--       PO_LINE_ID NUMBER,
--       PO_LINE_NUMBER NUMBER,
--       PO_LINE_LOCATION_ID NUMBER,
--       PO_SHIPMENT_NUM NUMBER,
--       PO_DISTRIBUTION_ID NUMBER,
--       PO_DISTRIBUTION_NUM NUMBER,
--       PO_UNIT_OF_MEASURE VARCHAR2(25),
--       INVENTORY_ITEM_ID NUMBER,
--       ITEM_DESCRIPTION VARCHAR2(240),
--       QUANTITY_INVOICED NUMBER,
--       SHIP_TO_LOCATION_CODE VARCHAR2(60),
--       UNIT_PRICE NUMBER,
--       DISTRIBUTION_SET_ID NUMBER(15),
--       DISTRIBUTION_SET_NAME VARCHAR2(50),
--       DIST_CODE_CONCATENATED VARCHAR2(250),
--       DIST_CODE_COMBINATION_ID NUMBER(15),
--       AWT_GROUP_ID NUMBER(15),
--       AWT_GROUP_NAME VARCHAR2(25),
--       LAST_UPDATED_BY NUMBER(15),
--       LAST_UPDATE_DATE DATE,
--       LAST_UPDATE_LOGIN NUMBER(15),
--       CREATED_BY NUMBER(15),
--       CREATION_DATE DATE,
--       ATTRIBUTE_CATEGORY VARCHAR2(150),
--       ATTRIBUTE1 VARCHAR2(150),
--       ATTRIBUTE2 VARCHAR2(150),
--       ATTRIBUTE3 VARCHAR2(150),
--       ATTRIBUTE4 VARCHAR2(150),
--       ATTRIBUTE5 VARCHAR2(150),
--       ATTRIBUTE6 VARCHAR2(150),
--       ATTRIBUTE7 VARCHAR2(150),
--       ATTRIBUTE8 VARCHAR2(150),
--       ATTRIBUTE9 VARCHAR2(150),
--       ATTRIBUTE10 VARCHAR2(150),
--       ATTRIBUTE11 VARCHAR2(150),
--       ATTRIBUTE12 VARCHAR2(150),
--       ATTRIBUTE13 VARCHAR2(150),
--       ATTRIBUTE14 VARCHAR2(150),
--       ATTRIBUTE15 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE_CATEGORY VARCHAR2(150),
--       GLOBAL_ATTRIBUTE1 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE2 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE3 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE4 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE5 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE6 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE7 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE8 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE9 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE10 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE11 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE12 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE13 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE14 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE15 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE16 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE17 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE18 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE19 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE20 VARCHAR2(150),
--       PO_RELEASE_ID NUMBER,
--       RELEASE_NUM NUMBER,
--       ACCOUNT_SEGMENT VARCHAR2(25),
--       BALANCING_SEGMENT VARCHAR2(25),
--       COST_CENTER_SEGMENT VARCHAR2(25),
--       PROJECT_ID NUMBER(15),
--       TASK_ID NUMBER(15),
--       EXPENDITURE_TYPE VARCHAR2(30),
--       EXPENDITURE_ITEM_DATE DATE,
--       EXPENDITURE_ORGANIZATION_ID NUMBER(15),
--       PROJECT_ACCOUNTING_CONTEXT VARCHAR2(30),
--       PA_ADDITION_FLAG VARCHAR2(1),
--       PA_QUANTITY NUMBER(22, 5),
--       USSGL_TRANSACTION_CODE VARCHAR2(30),
--       STAT_AMOUNT NUMBER,
--       TYPE_1099 VARCHAR2(10),
--       INCOME_TAX_REGION VARCHAR2(10),
--       ASSETS_TRACKING_FLAG VARCHAR2(1),
--       PRICE_CORRECTION_FLAG VARCHAR2(1),
--       ORG_ID NUMBER(15),
--       RECEIPT_NUMBER VARCHAR2(30),
--       RECEIPT_LINE_NUMBER VARCHAR2(25),
--       MATCH_OPTION VARCHAR2(25),
--       PACKING_SLIP VARCHAR2(25),
--       RCV_TRANSACTION_ID NUMBER,
--       PA_CC_AR_INVOICE_ID NUMBER(15),
--       PA_CC_AR_INVOICE_LINE_NUM NUMBER(15),
--       REFERENCE_1 VARCHAR2(30),
--       REFERENCE_2 VARCHAR2(30),
--       PA_CC_PROCESSED_CODE VARCHAR2(1),
--       TAX_RECOVERY_RATE NUMBER,
--       TAX_RECOVERY_OVERRIDE_FLAG VARCHAR2(1),
--       TAX_RECOVERABLE_FLAG VARCHAR2(1),
--       TAX_CODE_OVERRIDE_FLAG VARCHAR2(1),
--       TAX_CODE_ID NUMBER(15),
--       CREDIT_CARD_TRX_ID NUMBER(15),
--       AWARD_ID NUMBER(15),
--       VENDOR_ITEM_NUM VARCHAR2(25),
--       TAXABLE_FLAG VARCHAR2(1),
--       PRICE_CORRECT_INV_NUM VARCHAR2(50),
--       EXTERNAL_DOC_LINE_REF VARCHAR2(240)-- 
-- );
-- /
-- show errors
-- uncomment to overwrite existing types
-- CREATE OR REPLACE TYPE XX_CS_TDS_AP_INX1326404X1X97 AS TABLE OF XX_CS_TDS_AP_INX1326404X1X98; 
-- /
-- show errors
-- Declare the SQL type for the PL/SQL type ROWTYPE_PL8
-- uncomment to overwrite existing types
-- CREATE OR REPLACE TYPE XX_CS_TDS_AP_INVX1326404X1X1 AS OBJECT (
--       INVOICE_ID NUMBER(15),
--       INVOICE_NUM VARCHAR2(50),
--       INVOICE_TYPE_LOOKUP_CODE VARCHAR2(25),
--       INVOICE_DATE DATE,
--       PO_NUMBER VARCHAR2(20),
--       VENDOR_ID NUMBER(15),
--       VENDOR_NUM VARCHAR2(30),
--       VENDOR_NAME VARCHAR2(240),
--       VENDOR_SITE_ID NUMBER(15),
--       VENDOR_SITE_CODE VARCHAR2(15),
--       INVOICE_AMOUNT NUMBER,
--       INVOICE_CURRENCY_CODE VARCHAR2(15),
--       EXCHANGE_RATE NUMBER,
--       EXCHANGE_RATE_TYPE VARCHAR2(30),
--       EXCHANGE_DATE DATE,
--       TERMS_ID NUMBER(15),
--       TERMS_NAME VARCHAR2(50),
--       DESCRIPTION VARCHAR2(240),
--       AWT_GROUP_ID NUMBER(15),
--       AWT_GROUP_NAME VARCHAR2(25),
--       LAST_UPDATE_DATE DATE,
--       LAST_UPDATED_BY NUMBER(15),
--       LAST_UPDATE_LOGIN NUMBER(15),
--       CREATION_DATE DATE,
--       CREATED_BY NUMBER(15),
--       ATTRIBUTE_CATEGORY VARCHAR2(150),
--       ATTRIBUTE1 VARCHAR2(150),
--       ATTRIBUTE2 VARCHAR2(150),
--       ATTRIBUTE3 VARCHAR2(150),
--       ATTRIBUTE4 VARCHAR2(150),
--       ATTRIBUTE5 VARCHAR2(150),
--       ATTRIBUTE6 VARCHAR2(150),
--       ATTRIBUTE7 VARCHAR2(150),
--       ATTRIBUTE8 VARCHAR2(150),
--       ATTRIBUTE9 VARCHAR2(150),
--       ATTRIBUTE10 VARCHAR2(150),
--       ATTRIBUTE11 VARCHAR2(150),
--       ATTRIBUTE12 VARCHAR2(150),
--       ATTRIBUTE13 VARCHAR2(150),
--       ATTRIBUTE14 VARCHAR2(150),
--       ATTRIBUTE15 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE_CATEGORY VARCHAR2(150),
--       GLOBAL_ATTRIBUTE1 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE2 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE3 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE4 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE5 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE6 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE7 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE8 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE9 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE10 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE11 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE12 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE13 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE14 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE15 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE16 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE17 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE18 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE19 VARCHAR2(150),
--       GLOBAL_ATTRIBUTE20 VARCHAR2(150),
--       STATUS VARCHAR2(25),
--       SOURCE VARCHAR2(80),
--       GROUP_ID VARCHAR2(80),
--       REQUEST_ID NUMBER,
--       PAYMENT_CROSS_RATE_TYPE VARCHAR2(30),
--       PAYMENT_CROSS_RATE_DATE DATE,
--       PAYMENT_CROSS_RATE NUMBER,
--       PAYMENT_CURRENCY_CODE VARCHAR2(15),
--       WORKFLOW_FLAG VARCHAR2(1),
--       DOC_CATEGORY_CODE VARCHAR2(30),
--       VOUCHER_NUM VARCHAR2(50),
--       PAYMENT_METHOD_LOOKUP_CODE VARCHAR2(25),
--       PAY_GROUP_LOOKUP_CODE VARCHAR2(25),
--       GOODS_RECEIVED_DATE DATE,
--       INVOICE_RECEIVED_DATE DATE,
--       GL_DATE DATE,
--       ACCTS_PAY_CODE_COMBINATION_ID NUMBER(15),
--       USSGL_TRANSACTION_CODE VARCHAR2(30),
--       EXCLUSIVE_PAYMENT_FLAG VARCHAR2(1),
--       ORG_ID NUMBER(15),
--       AMOUNT_APPLICABLE_TO_DISCOUNT NUMBER,
--       PREPAY_NUM VARCHAR2(50),
--       PREPAY_DIST_NUM NUMBER(15),
--       PREPAY_APPLY_AMOUNT NUMBER,
--       PREPAY_GL_DATE DATE,
--       INVOICE_INCLUDES_PREPAY_FLAG VARCHAR2(1),
--       NO_XRATE_BASE_AMOUNT NUMBER,
--       VENDOR_EMAIL_ADDRESS VARCHAR2(2000),
--       TERMS_DATE DATE,
--       REQUESTER_ID NUMBER(10),
--       SHIP_TO_LOCATION VARCHAR2(40),
--       EXTERNAL_DOC_REF VARCHAR2(240),
--       ACCTS_PAY_CODE_CONCATENATED VARCHAR2(250)-- 
-- );
-- /
-- show errors
-- Declare package containing conversion functions between SQL and PL/SQL types
CREATE OR REPLACE PACKAGE XX_CS_TDS_AP_INVOICE_BPEL_PKG AS
	-- Redefine a PL/SQL RECORD type originally defined via CURSOR%ROWTYPE
	TYPE ROWTYPE_PL9 IS RECORD (
		INVOICE_ID NUMBER(15),
		INVOICE_LINE_ID NUMBER(15),
		LINE_NUMBER NUMBER(15),
		LINE_TYPE_LOOKUP_CODE VARCHAR2(25),
		LINE_GROUP_NUMBER NUMBER,
		AMOUNT NUMBER,
		ACCOUNTING_DATE DATE,
		DESCRIPTION VARCHAR2(240),
		AMOUNT_INCLUDES_TAX_FLAG VARCHAR2(1),
		PRORATE_ACROSS_FLAG VARCHAR2(1),
		TAX_CODE VARCHAR2(15),
		FINAL_MATCH_FLAG VARCHAR2(1),
		PO_HEADER_ID NUMBER,
		PO_NUMBER VARCHAR2(20),
		PO_LINE_ID NUMBER,
		PO_LINE_NUMBER NUMBER,
		PO_LINE_LOCATION_ID NUMBER,
		PO_SHIPMENT_NUM NUMBER,
		PO_DISTRIBUTION_ID NUMBER,
		PO_DISTRIBUTION_NUM NUMBER,
		PO_UNIT_OF_MEASURE VARCHAR2(25),
		INVENTORY_ITEM_ID NUMBER,
		ITEM_DESCRIPTION VARCHAR2(240),
		QUANTITY_INVOICED NUMBER,
		SHIP_TO_LOCATION_CODE VARCHAR2(60),
		UNIT_PRICE NUMBER,
		DISTRIBUTION_SET_ID NUMBER(15),
		DISTRIBUTION_SET_NAME VARCHAR2(50),
		DIST_CODE_CONCATENATED VARCHAR2(250),
		DIST_CODE_COMBINATION_ID NUMBER(15),
		AWT_GROUP_ID NUMBER(15),
		AWT_GROUP_NAME VARCHAR2(25),
		LAST_UPDATED_BY NUMBER(15),
		LAST_UPDATE_DATE DATE,
		LAST_UPDATE_LOGIN NUMBER(15),
		CREATED_BY NUMBER(15),
		CREATION_DATE DATE,
		ATTRIBUTE_CATEGORY VARCHAR2(150),
		ATTRIBUTE1 VARCHAR2(150),
		ATTRIBUTE2 VARCHAR2(150),
		ATTRIBUTE3 VARCHAR2(150),
		ATTRIBUTE4 VARCHAR2(150),
		ATTRIBUTE5 VARCHAR2(150),
		ATTRIBUTE6 VARCHAR2(150),
		ATTRIBUTE7 VARCHAR2(150),
		ATTRIBUTE8 VARCHAR2(150),
		ATTRIBUTE9 VARCHAR2(150),
		ATTRIBUTE10 VARCHAR2(150),
		ATTRIBUTE11 VARCHAR2(150),
		ATTRIBUTE12 VARCHAR2(150),
		ATTRIBUTE13 VARCHAR2(150),
		ATTRIBUTE14 VARCHAR2(150),
		ATTRIBUTE15 VARCHAR2(150),
		GLOBAL_ATTRIBUTE_CATEGORY VARCHAR2(150),
		GLOBAL_ATTRIBUTE1 VARCHAR2(150),
		GLOBAL_ATTRIBUTE2 VARCHAR2(150),
		GLOBAL_ATTRIBUTE3 VARCHAR2(150),
		GLOBAL_ATTRIBUTE4 VARCHAR2(150),
		GLOBAL_ATTRIBUTE5 VARCHAR2(150),
		GLOBAL_ATTRIBUTE6 VARCHAR2(150),
		GLOBAL_ATTRIBUTE7 VARCHAR2(150),
		GLOBAL_ATTRIBUTE8 VARCHAR2(150),
		GLOBAL_ATTRIBUTE9 VARCHAR2(150),
		GLOBAL_ATTRIBUTE10 VARCHAR2(150),
		GLOBAL_ATTRIBUTE11 VARCHAR2(150),
		GLOBAL_ATTRIBUTE12 VARCHAR2(150),
		GLOBAL_ATTRIBUTE13 VARCHAR2(150),
		GLOBAL_ATTRIBUTE14 VARCHAR2(150),
		GLOBAL_ATTRIBUTE15 VARCHAR2(150),
		GLOBAL_ATTRIBUTE16 VARCHAR2(150),
		GLOBAL_ATTRIBUTE17 VARCHAR2(150),
		GLOBAL_ATTRIBUTE18 VARCHAR2(150),
		GLOBAL_ATTRIBUTE19 VARCHAR2(150),
		GLOBAL_ATTRIBUTE20 VARCHAR2(150),
		PO_RELEASE_ID NUMBER,
		RELEASE_NUM NUMBER,
		ACCOUNT_SEGMENT VARCHAR2(25),
		BALANCING_SEGMENT VARCHAR2(25),
		COST_CENTER_SEGMENT VARCHAR2(25),
		PROJECT_ID NUMBER(15),
		TASK_ID NUMBER(15),
		EXPENDITURE_TYPE VARCHAR2(30),
		EXPENDITURE_ITEM_DATE DATE,
		EXPENDITURE_ORGANIZATION_ID NUMBER(15),
		PROJECT_ACCOUNTING_CONTEXT VARCHAR2(30),
		PA_ADDITION_FLAG VARCHAR2(1),
		PA_QUANTITY NUMBER(22, 5),
		USSGL_TRANSACTION_CODE VARCHAR2(30),
		STAT_AMOUNT NUMBER,
		TYPE_1099 VARCHAR2(10),
		INCOME_TAX_REGION VARCHAR2(10),
		ASSETS_TRACKING_FLAG VARCHAR2(1),
		PRICE_CORRECTION_FLAG VARCHAR2(1),
		ORG_ID NUMBER(15),
		RECEIPT_NUMBER VARCHAR2(30),
		RECEIPT_LINE_NUMBER VARCHAR2(25),
		MATCH_OPTION VARCHAR2(25),
		PACKING_SLIP VARCHAR2(25),
		RCV_TRANSACTION_ID NUMBER,
		PA_CC_AR_INVOICE_ID NUMBER(15),
		PA_CC_AR_INVOICE_LINE_NUM NUMBER(15),
		REFERENCE_1 VARCHAR2(30),
		REFERENCE_2 VARCHAR2(30),
		PA_CC_PROCESSED_CODE VARCHAR2(1),
		TAX_RECOVERY_RATE NUMBER,
		TAX_RECOVERY_OVERRIDE_FLAG VARCHAR2(1),
		TAX_RECOVERABLE_FLAG VARCHAR2(1),
		TAX_CODE_OVERRIDE_FLAG VARCHAR2(1),
		TAX_CODE_ID NUMBER(15),
		CREDIT_CARD_TRX_ID NUMBER(15),
		AWARD_ID NUMBER(15),
		VENDOR_ITEM_NUM VARCHAR2(25),
		TAXABLE_FLAG VARCHAR2(1),
		PRICE_CORRECT_INV_NUM VARCHAR2(50),
		EXTERNAL_DOC_LINE_REF VARCHAR2(240));
	-- Declare the conversion functions the PL/SQL type ROWTYPE_PL9
	FUNCTION PL_TO_SQL0(aPlsqlItem ROWTYPE_PL9)
 	RETURN XX_CS_TDS_AP_INX1326404X1X98;
	FUNCTION SQL_TO_PL2(aSqlItem XX_CS_TDS_AP_INX1326404X1X98)
	RETURN ROWTYPE_PL9;
	-- Declare the conversion functions the PL/SQL type XX_CS_TDS_AP_INVOICE_PKG.T_INVDETRECTBL
	FUNCTION PL_TO_SQL1(aPlsqlItem XX_CS_TDS_AP_INVOICE_PKG.T_INVDETRECTBL)
 	RETURN XX_CS_TDS_AP_INX1326404X1X97;
	FUNCTION SQL_TO_PL1(aSqlItem XX_CS_TDS_AP_INX1326404X1X97)
	RETURN XX_CS_TDS_AP_INVOICE_PKG.T_INVDETRECTBL;
	-- Redefine a PL/SQL RECORD type originally defined via CURSOR%ROWTYPE
	TYPE ROWTYPE_PL8 IS RECORD (
		INVOICE_ID NUMBER(15),
		INVOICE_NUM VARCHAR2(50),
		INVOICE_TYPE_LOOKUP_CODE VARCHAR2(25),
		INVOICE_DATE DATE,
		PO_NUMBER VARCHAR2(20),
		VENDOR_ID NUMBER(15),
		VENDOR_NUM VARCHAR2(30),
		VENDOR_NAME VARCHAR2(240),
		VENDOR_SITE_ID NUMBER(15),
		VENDOR_SITE_CODE VARCHAR2(15),
		INVOICE_AMOUNT NUMBER,
		INVOICE_CURRENCY_CODE VARCHAR2(15),
		EXCHANGE_RATE NUMBER,
		EXCHANGE_RATE_TYPE VARCHAR2(30),
		EXCHANGE_DATE DATE,
		TERMS_ID NUMBER(15),
		TERMS_NAME VARCHAR2(50),
		DESCRIPTION VARCHAR2(240),
		AWT_GROUP_ID NUMBER(15),
		AWT_GROUP_NAME VARCHAR2(25),
		LAST_UPDATE_DATE DATE,
		LAST_UPDATED_BY NUMBER(15),
		LAST_UPDATE_LOGIN NUMBER(15),
		CREATION_DATE DATE,
		CREATED_BY NUMBER(15),
		ATTRIBUTE_CATEGORY VARCHAR2(150),
		ATTRIBUTE1 VARCHAR2(150),
		ATTRIBUTE2 VARCHAR2(150),
		ATTRIBUTE3 VARCHAR2(150),
		ATTRIBUTE4 VARCHAR2(150),
		ATTRIBUTE5 VARCHAR2(150),
		ATTRIBUTE6 VARCHAR2(150),
		ATTRIBUTE7 VARCHAR2(150),
		ATTRIBUTE8 VARCHAR2(150),
		ATTRIBUTE9 VARCHAR2(150),
		ATTRIBUTE10 VARCHAR2(150),
		ATTRIBUTE11 VARCHAR2(150),
		ATTRIBUTE12 VARCHAR2(150),
		ATTRIBUTE13 VARCHAR2(150),
		ATTRIBUTE14 VARCHAR2(150),
		ATTRIBUTE15 VARCHAR2(150),
		GLOBAL_ATTRIBUTE_CATEGORY VARCHAR2(150),
		GLOBAL_ATTRIBUTE1 VARCHAR2(150),
		GLOBAL_ATTRIBUTE2 VARCHAR2(150),
		GLOBAL_ATTRIBUTE3 VARCHAR2(150),
		GLOBAL_ATTRIBUTE4 VARCHAR2(150),
		GLOBAL_ATTRIBUTE5 VARCHAR2(150),
		GLOBAL_ATTRIBUTE6 VARCHAR2(150),
		GLOBAL_ATTRIBUTE7 VARCHAR2(150),
		GLOBAL_ATTRIBUTE8 VARCHAR2(150),
		GLOBAL_ATTRIBUTE9 VARCHAR2(150),
		GLOBAL_ATTRIBUTE10 VARCHAR2(150),
		GLOBAL_ATTRIBUTE11 VARCHAR2(150),
		GLOBAL_ATTRIBUTE12 VARCHAR2(150),
		GLOBAL_ATTRIBUTE13 VARCHAR2(150),
		GLOBAL_ATTRIBUTE14 VARCHAR2(150),
		GLOBAL_ATTRIBUTE15 VARCHAR2(150),
		GLOBAL_ATTRIBUTE16 VARCHAR2(150),
		GLOBAL_ATTRIBUTE17 VARCHAR2(150),
		GLOBAL_ATTRIBUTE18 VARCHAR2(150),
		GLOBAL_ATTRIBUTE19 VARCHAR2(150),
		GLOBAL_ATTRIBUTE20 VARCHAR2(150),
		STATUS VARCHAR2(25),
		SOURCE VARCHAR2(80),
		GROUP_ID VARCHAR2(80),
		REQUEST_ID NUMBER,
		PAYMENT_CROSS_RATE_TYPE VARCHAR2(30),
		PAYMENT_CROSS_RATE_DATE DATE,
		PAYMENT_CROSS_RATE NUMBER,
		PAYMENT_CURRENCY_CODE VARCHAR2(15),
		WORKFLOW_FLAG VARCHAR2(1),
		DOC_CATEGORY_CODE VARCHAR2(30),
		VOUCHER_NUM VARCHAR2(50),
		PAYMENT_METHOD_LOOKUP_CODE VARCHAR2(25),
		PAY_GROUP_LOOKUP_CODE VARCHAR2(25),
		GOODS_RECEIVED_DATE DATE,
		INVOICE_RECEIVED_DATE DATE,
		GL_DATE DATE,
		ACCTS_PAY_CODE_COMBINATION_ID NUMBER(15),
		USSGL_TRANSACTION_CODE VARCHAR2(30),
		EXCLUSIVE_PAYMENT_FLAG VARCHAR2(1),
		ORG_ID NUMBER(15),
		AMOUNT_APPLICABLE_TO_DISCOUNT NUMBER,
		PREPAY_NUM VARCHAR2(50),
		PREPAY_DIST_NUM NUMBER(15),
		PREPAY_APPLY_AMOUNT NUMBER,
		PREPAY_GL_DATE DATE,
		INVOICE_INCLUDES_PREPAY_FLAG VARCHAR2(1),
		NO_XRATE_BASE_AMOUNT NUMBER,
		VENDOR_EMAIL_ADDRESS VARCHAR2(2000),
		TERMS_DATE DATE,
		REQUESTER_ID NUMBER(10),
		SHIP_TO_LOCATION VARCHAR2(40),
		EXTERNAL_DOC_REF VARCHAR2(240),
		ACCTS_PAY_CODE_CONCATENATED VARCHAR2(250));
	-- Declare the conversion functions the PL/SQL type ROWTYPE_PL8
	FUNCTION PL_TO_SQL2(aPlsqlItem ROWTYPE_PL8)
 	RETURN XX_CS_TDS_AP_INVX1326404X1X1;
	FUNCTION SQL_TO_PL0(aSqlItem XX_CS_TDS_AP_INVX1326404X1X1)
	RETURN ROWTYPE_PL8;
   PROCEDURE xx_cs_tds_ap_invoice_pkg$inse (P_HEADER_REC XX_CS_TDS_AP_INVX1326404X1X1,
	P_LINES_TAB APPS.XX_CS_TDS_AP_INX1326404X1X97,
	X_STATUS OUT VARCHAR2,
	X_MSG_DATA OUT VARCHAR2
	);
END XX_CS_TDS_AP_INVOICE_BPEL_PKG;
/
show errors
CREATE OR REPLACE PACKAGE BODY XX_CS_TDS_AP_INVOICE_BPEL_PKG IS
	FUNCTION PL_TO_SQL0(aPlsqlItem ROWTYPE_PL9)
 	RETURN XX_CS_TDS_AP_INX1326404X1X98 IS 
	aSqlItem XX_CS_TDS_AP_INX1326404X1X98; 
	BEGIN 
		-- initialize the object
		aSqlItem := XX_CS_TDS_AP_INX1326404X1X98(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL);
		aSqlItem.INVOICE_ID := aPlsqlItem.INVOICE_ID;
		aSqlItem.INVOICE_LINE_ID := aPlsqlItem.INVOICE_LINE_ID;
		aSqlItem.LINE_NUMBER := aPlsqlItem.LINE_NUMBER;
		aSqlItem.LINE_TYPE_LOOKUP_CODE := aPlsqlItem.LINE_TYPE_LOOKUP_CODE;
		aSqlItem.LINE_GROUP_NUMBER := aPlsqlItem.LINE_GROUP_NUMBER;
		aSqlItem.AMOUNT := aPlsqlItem.AMOUNT;
		aSqlItem.ACCOUNTING_DATE := aPlsqlItem.ACCOUNTING_DATE;
		aSqlItem.DESCRIPTION := aPlsqlItem.DESCRIPTION;
		aSqlItem.AMOUNT_INCLUDES_TAX_FLAG := aPlsqlItem.AMOUNT_INCLUDES_TAX_FLAG;
		aSqlItem.PRORATE_ACROSS_FLAG := aPlsqlItem.PRORATE_ACROSS_FLAG;
		aSqlItem.TAX_CODE := aPlsqlItem.TAX_CODE;
		aSqlItem.FINAL_MATCH_FLAG := aPlsqlItem.FINAL_MATCH_FLAG;
		aSqlItem.PO_HEADER_ID := aPlsqlItem.PO_HEADER_ID;
		aSqlItem.PO_NUMBER := aPlsqlItem.PO_NUMBER;
		aSqlItem.PO_LINE_ID := aPlsqlItem.PO_LINE_ID;
		aSqlItem.PO_LINE_NUMBER := aPlsqlItem.PO_LINE_NUMBER;
		aSqlItem.PO_LINE_LOCATION_ID := aPlsqlItem.PO_LINE_LOCATION_ID;
		aSqlItem.PO_SHIPMENT_NUM := aPlsqlItem.PO_SHIPMENT_NUM;
		aSqlItem.PO_DISTRIBUTION_ID := aPlsqlItem.PO_DISTRIBUTION_ID;
		aSqlItem.PO_DISTRIBUTION_NUM := aPlsqlItem.PO_DISTRIBUTION_NUM;
		aSqlItem.PO_UNIT_OF_MEASURE := aPlsqlItem.PO_UNIT_OF_MEASURE;
		aSqlItem.INVENTORY_ITEM_ID := aPlsqlItem.INVENTORY_ITEM_ID;
		aSqlItem.ITEM_DESCRIPTION := aPlsqlItem.ITEM_DESCRIPTION;
		aSqlItem.QUANTITY_INVOICED := aPlsqlItem.QUANTITY_INVOICED;
		aSqlItem.SHIP_TO_LOCATION_CODE := aPlsqlItem.SHIP_TO_LOCATION_CODE;
		aSqlItem.UNIT_PRICE := aPlsqlItem.UNIT_PRICE;
		aSqlItem.DISTRIBUTION_SET_ID := aPlsqlItem.DISTRIBUTION_SET_ID;
		aSqlItem.DISTRIBUTION_SET_NAME := aPlsqlItem.DISTRIBUTION_SET_NAME;
		aSqlItem.DIST_CODE_CONCATENATED := aPlsqlItem.DIST_CODE_CONCATENATED;
		aSqlItem.DIST_CODE_COMBINATION_ID := aPlsqlItem.DIST_CODE_COMBINATION_ID;
		aSqlItem.AWT_GROUP_ID := aPlsqlItem.AWT_GROUP_ID;
		aSqlItem.AWT_GROUP_NAME := aPlsqlItem.AWT_GROUP_NAME;
		aSqlItem.LAST_UPDATED_BY := aPlsqlItem.LAST_UPDATED_BY;
		aSqlItem.LAST_UPDATE_DATE := aPlsqlItem.LAST_UPDATE_DATE;
		aSqlItem.LAST_UPDATE_LOGIN := aPlsqlItem.LAST_UPDATE_LOGIN;
		aSqlItem.CREATED_BY := aPlsqlItem.CREATED_BY;
		aSqlItem.CREATION_DATE := aPlsqlItem.CREATION_DATE;
		aSqlItem.ATTRIBUTE_CATEGORY := aPlsqlItem.ATTRIBUTE_CATEGORY;
		aSqlItem.ATTRIBUTE1 := aPlsqlItem.ATTRIBUTE1;
		aSqlItem.ATTRIBUTE2 := aPlsqlItem.ATTRIBUTE2;
		aSqlItem.ATTRIBUTE3 := aPlsqlItem.ATTRIBUTE3;
		aSqlItem.ATTRIBUTE4 := aPlsqlItem.ATTRIBUTE4;
		aSqlItem.ATTRIBUTE5 := aPlsqlItem.ATTRIBUTE5;
		aSqlItem.ATTRIBUTE6 := aPlsqlItem.ATTRIBUTE6;
		aSqlItem.ATTRIBUTE7 := aPlsqlItem.ATTRIBUTE7;
		aSqlItem.ATTRIBUTE8 := aPlsqlItem.ATTRIBUTE8;
		aSqlItem.ATTRIBUTE9 := aPlsqlItem.ATTRIBUTE9;
		aSqlItem.ATTRIBUTE10 := aPlsqlItem.ATTRIBUTE10;
		aSqlItem.ATTRIBUTE11 := aPlsqlItem.ATTRIBUTE11;
		aSqlItem.ATTRIBUTE12 := aPlsqlItem.ATTRIBUTE12;
		aSqlItem.ATTRIBUTE13 := aPlsqlItem.ATTRIBUTE13;
		aSqlItem.ATTRIBUTE14 := aPlsqlItem.ATTRIBUTE14;
		aSqlItem.ATTRIBUTE15 := aPlsqlItem.ATTRIBUTE15;
		aSqlItem.GLOBAL_ATTRIBUTE_CATEGORY := aPlsqlItem.GLOBAL_ATTRIBUTE_CATEGORY;
		aSqlItem.GLOBAL_ATTRIBUTE1 := aPlsqlItem.GLOBAL_ATTRIBUTE1;
		aSqlItem.GLOBAL_ATTRIBUTE2 := aPlsqlItem.GLOBAL_ATTRIBUTE2;
		aSqlItem.GLOBAL_ATTRIBUTE3 := aPlsqlItem.GLOBAL_ATTRIBUTE3;
		aSqlItem.GLOBAL_ATTRIBUTE4 := aPlsqlItem.GLOBAL_ATTRIBUTE4;
		aSqlItem.GLOBAL_ATTRIBUTE5 := aPlsqlItem.GLOBAL_ATTRIBUTE5;
		aSqlItem.GLOBAL_ATTRIBUTE6 := aPlsqlItem.GLOBAL_ATTRIBUTE6;
		aSqlItem.GLOBAL_ATTRIBUTE7 := aPlsqlItem.GLOBAL_ATTRIBUTE7;
		aSqlItem.GLOBAL_ATTRIBUTE8 := aPlsqlItem.GLOBAL_ATTRIBUTE8;
		aSqlItem.GLOBAL_ATTRIBUTE9 := aPlsqlItem.GLOBAL_ATTRIBUTE9;
		aSqlItem.GLOBAL_ATTRIBUTE10 := aPlsqlItem.GLOBAL_ATTRIBUTE10;
		aSqlItem.GLOBAL_ATTRIBUTE11 := aPlsqlItem.GLOBAL_ATTRIBUTE11;
		aSqlItem.GLOBAL_ATTRIBUTE12 := aPlsqlItem.GLOBAL_ATTRIBUTE12;
		aSqlItem.GLOBAL_ATTRIBUTE13 := aPlsqlItem.GLOBAL_ATTRIBUTE13;
		aSqlItem.GLOBAL_ATTRIBUTE14 := aPlsqlItem.GLOBAL_ATTRIBUTE14;
		aSqlItem.GLOBAL_ATTRIBUTE15 := aPlsqlItem.GLOBAL_ATTRIBUTE15;
		aSqlItem.GLOBAL_ATTRIBUTE16 := aPlsqlItem.GLOBAL_ATTRIBUTE16;
		aSqlItem.GLOBAL_ATTRIBUTE17 := aPlsqlItem.GLOBAL_ATTRIBUTE17;
		aSqlItem.GLOBAL_ATTRIBUTE18 := aPlsqlItem.GLOBAL_ATTRIBUTE18;
		aSqlItem.GLOBAL_ATTRIBUTE19 := aPlsqlItem.GLOBAL_ATTRIBUTE19;
		aSqlItem.GLOBAL_ATTRIBUTE20 := aPlsqlItem.GLOBAL_ATTRIBUTE20;
		aSqlItem.PO_RELEASE_ID := aPlsqlItem.PO_RELEASE_ID;
		aSqlItem.RELEASE_NUM := aPlsqlItem.RELEASE_NUM;
		aSqlItem.ACCOUNT_SEGMENT := aPlsqlItem.ACCOUNT_SEGMENT;
		aSqlItem.BALANCING_SEGMENT := aPlsqlItem.BALANCING_SEGMENT;
		aSqlItem.COST_CENTER_SEGMENT := aPlsqlItem.COST_CENTER_SEGMENT;
		aSqlItem.PROJECT_ID := aPlsqlItem.PROJECT_ID;
		aSqlItem.TASK_ID := aPlsqlItem.TASK_ID;
		aSqlItem.EXPENDITURE_TYPE := aPlsqlItem.EXPENDITURE_TYPE;
		aSqlItem.EXPENDITURE_ITEM_DATE := aPlsqlItem.EXPENDITURE_ITEM_DATE;
		aSqlItem.EXPENDITURE_ORGANIZATION_ID := aPlsqlItem.EXPENDITURE_ORGANIZATION_ID;
		aSqlItem.PROJECT_ACCOUNTING_CONTEXT := aPlsqlItem.PROJECT_ACCOUNTING_CONTEXT;
		aSqlItem.PA_ADDITION_FLAG := aPlsqlItem.PA_ADDITION_FLAG;
		aSqlItem.PA_QUANTITY := aPlsqlItem.PA_QUANTITY;
		aSqlItem.USSGL_TRANSACTION_CODE := aPlsqlItem.USSGL_TRANSACTION_CODE;
		aSqlItem.STAT_AMOUNT := aPlsqlItem.STAT_AMOUNT;
		aSqlItem.TYPE_1099 := aPlsqlItem.TYPE_1099;
		aSqlItem.INCOME_TAX_REGION := aPlsqlItem.INCOME_TAX_REGION;
		aSqlItem.ASSETS_TRACKING_FLAG := aPlsqlItem.ASSETS_TRACKING_FLAG;
		aSqlItem.PRICE_CORRECTION_FLAG := aPlsqlItem.PRICE_CORRECTION_FLAG;
		aSqlItem.ORG_ID := aPlsqlItem.ORG_ID;
		aSqlItem.RECEIPT_NUMBER := aPlsqlItem.RECEIPT_NUMBER;
		aSqlItem.RECEIPT_LINE_NUMBER := aPlsqlItem.RECEIPT_LINE_NUMBER;
		aSqlItem.MATCH_OPTION := aPlsqlItem.MATCH_OPTION;
		aSqlItem.PACKING_SLIP := aPlsqlItem.PACKING_SLIP;
		aSqlItem.RCV_TRANSACTION_ID := aPlsqlItem.RCV_TRANSACTION_ID;
		aSqlItem.PA_CC_AR_INVOICE_ID := aPlsqlItem.PA_CC_AR_INVOICE_ID;
		aSqlItem.PA_CC_AR_INVOICE_LINE_NUM := aPlsqlItem.PA_CC_AR_INVOICE_LINE_NUM;
		aSqlItem.REFERENCE_1 := aPlsqlItem.REFERENCE_1;
		aSqlItem.REFERENCE_2 := aPlsqlItem.REFERENCE_2;
		aSqlItem.PA_CC_PROCESSED_CODE := aPlsqlItem.PA_CC_PROCESSED_CODE;
		aSqlItem.TAX_RECOVERY_RATE := aPlsqlItem.TAX_RECOVERY_RATE;
		aSqlItem.TAX_RECOVERY_OVERRIDE_FLAG := aPlsqlItem.TAX_RECOVERY_OVERRIDE_FLAG;
		aSqlItem.TAX_RECOVERABLE_FLAG := aPlsqlItem.TAX_RECOVERABLE_FLAG;
		aSqlItem.TAX_CODE_OVERRIDE_FLAG := aPlsqlItem.TAX_CODE_OVERRIDE_FLAG;
		aSqlItem.TAX_CODE_ID := aPlsqlItem.TAX_CODE_ID;
		aSqlItem.CREDIT_CARD_TRX_ID := aPlsqlItem.CREDIT_CARD_TRX_ID;
		aSqlItem.AWARD_ID := aPlsqlItem.AWARD_ID;
		aSqlItem.VENDOR_ITEM_NUM := aPlsqlItem.VENDOR_ITEM_NUM;
		aSqlItem.TAXABLE_FLAG := aPlsqlItem.TAXABLE_FLAG;
		aSqlItem.PRICE_CORRECT_INV_NUM := aPlsqlItem.PRICE_CORRECT_INV_NUM;
		aSqlItem.EXTERNAL_DOC_LINE_REF := aPlsqlItem.EXTERNAL_DOC_LINE_REF;
		RETURN aSqlItem;
	END PL_TO_SQL0;
	FUNCTION SQL_TO_PL2(aSqlItem XX_CS_TDS_AP_INX1326404X1X98) 
	RETURN ROWTYPE_PL9 IS 
	aPlsqlItem ROWTYPE_PL9; 
	BEGIN 
		aPlsqlItem.INVOICE_ID := aSqlItem.INVOICE_ID;
		aPlsqlItem.INVOICE_LINE_ID := aSqlItem.INVOICE_LINE_ID;
		aPlsqlItem.LINE_NUMBER := aSqlItem.LINE_NUMBER;
		aPlsqlItem.LINE_TYPE_LOOKUP_CODE := aSqlItem.LINE_TYPE_LOOKUP_CODE;
		aPlsqlItem.LINE_GROUP_NUMBER := aSqlItem.LINE_GROUP_NUMBER;
		aPlsqlItem.AMOUNT := aSqlItem.AMOUNT;
		aPlsqlItem.ACCOUNTING_DATE := aSqlItem.ACCOUNTING_DATE;
		aPlsqlItem.DESCRIPTION := aSqlItem.DESCRIPTION;
		aPlsqlItem.AMOUNT_INCLUDES_TAX_FLAG := aSqlItem.AMOUNT_INCLUDES_TAX_FLAG;
		aPlsqlItem.PRORATE_ACROSS_FLAG := aSqlItem.PRORATE_ACROSS_FLAG;
		aPlsqlItem.TAX_CODE := aSqlItem.TAX_CODE;
		aPlsqlItem.FINAL_MATCH_FLAG := aSqlItem.FINAL_MATCH_FLAG;
		aPlsqlItem.PO_HEADER_ID := aSqlItem.PO_HEADER_ID;
		aPlsqlItem.PO_NUMBER := aSqlItem.PO_NUMBER;
		aPlsqlItem.PO_LINE_ID := aSqlItem.PO_LINE_ID;
		aPlsqlItem.PO_LINE_NUMBER := aSqlItem.PO_LINE_NUMBER;
		aPlsqlItem.PO_LINE_LOCATION_ID := aSqlItem.PO_LINE_LOCATION_ID;
		aPlsqlItem.PO_SHIPMENT_NUM := aSqlItem.PO_SHIPMENT_NUM;
		aPlsqlItem.PO_DISTRIBUTION_ID := aSqlItem.PO_DISTRIBUTION_ID;
		aPlsqlItem.PO_DISTRIBUTION_NUM := aSqlItem.PO_DISTRIBUTION_NUM;
		aPlsqlItem.PO_UNIT_OF_MEASURE := aSqlItem.PO_UNIT_OF_MEASURE;
		aPlsqlItem.INVENTORY_ITEM_ID := aSqlItem.INVENTORY_ITEM_ID;
		aPlsqlItem.ITEM_DESCRIPTION := aSqlItem.ITEM_DESCRIPTION;
		aPlsqlItem.QUANTITY_INVOICED := aSqlItem.QUANTITY_INVOICED;
		aPlsqlItem.SHIP_TO_LOCATION_CODE := aSqlItem.SHIP_TO_LOCATION_CODE;
		aPlsqlItem.UNIT_PRICE := aSqlItem.UNIT_PRICE;
		aPlsqlItem.DISTRIBUTION_SET_ID := aSqlItem.DISTRIBUTION_SET_ID;
		aPlsqlItem.DISTRIBUTION_SET_NAME := aSqlItem.DISTRIBUTION_SET_NAME;
		aPlsqlItem.DIST_CODE_CONCATENATED := aSqlItem.DIST_CODE_CONCATENATED;
		aPlsqlItem.DIST_CODE_COMBINATION_ID := aSqlItem.DIST_CODE_COMBINATION_ID;
		aPlsqlItem.AWT_GROUP_ID := aSqlItem.AWT_GROUP_ID;
		aPlsqlItem.AWT_GROUP_NAME := aSqlItem.AWT_GROUP_NAME;
		aPlsqlItem.LAST_UPDATED_BY := aSqlItem.LAST_UPDATED_BY;
		aPlsqlItem.LAST_UPDATE_DATE := aSqlItem.LAST_UPDATE_DATE;
		aPlsqlItem.LAST_UPDATE_LOGIN := aSqlItem.LAST_UPDATE_LOGIN;
		aPlsqlItem.CREATED_BY := aSqlItem.CREATED_BY;
		aPlsqlItem.CREATION_DATE := aSqlItem.CREATION_DATE;
		aPlsqlItem.ATTRIBUTE_CATEGORY := aSqlItem.ATTRIBUTE_CATEGORY;
		aPlsqlItem.ATTRIBUTE1 := aSqlItem.ATTRIBUTE1;
		aPlsqlItem.ATTRIBUTE2 := aSqlItem.ATTRIBUTE2;
		aPlsqlItem.ATTRIBUTE3 := aSqlItem.ATTRIBUTE3;
		aPlsqlItem.ATTRIBUTE4 := aSqlItem.ATTRIBUTE4;
		aPlsqlItem.ATTRIBUTE5 := aSqlItem.ATTRIBUTE5;
		aPlsqlItem.ATTRIBUTE6 := aSqlItem.ATTRIBUTE6;
		aPlsqlItem.ATTRIBUTE7 := aSqlItem.ATTRIBUTE7;
		aPlsqlItem.ATTRIBUTE8 := aSqlItem.ATTRIBUTE8;
		aPlsqlItem.ATTRIBUTE9 := aSqlItem.ATTRIBUTE9;
		aPlsqlItem.ATTRIBUTE10 := aSqlItem.ATTRIBUTE10;
		aPlsqlItem.ATTRIBUTE11 := aSqlItem.ATTRIBUTE11;
		aPlsqlItem.ATTRIBUTE12 := aSqlItem.ATTRIBUTE12;
		aPlsqlItem.ATTRIBUTE13 := aSqlItem.ATTRIBUTE13;
		aPlsqlItem.ATTRIBUTE14 := aSqlItem.ATTRIBUTE14;
		aPlsqlItem.ATTRIBUTE15 := aSqlItem.ATTRIBUTE15;
		aPlsqlItem.GLOBAL_ATTRIBUTE_CATEGORY := aSqlItem.GLOBAL_ATTRIBUTE_CATEGORY;
		aPlsqlItem.GLOBAL_ATTRIBUTE1 := aSqlItem.GLOBAL_ATTRIBUTE1;
		aPlsqlItem.GLOBAL_ATTRIBUTE2 := aSqlItem.GLOBAL_ATTRIBUTE2;
		aPlsqlItem.GLOBAL_ATTRIBUTE3 := aSqlItem.GLOBAL_ATTRIBUTE3;
		aPlsqlItem.GLOBAL_ATTRIBUTE4 := aSqlItem.GLOBAL_ATTRIBUTE4;
		aPlsqlItem.GLOBAL_ATTRIBUTE5 := aSqlItem.GLOBAL_ATTRIBUTE5;
		aPlsqlItem.GLOBAL_ATTRIBUTE6 := aSqlItem.GLOBAL_ATTRIBUTE6;
		aPlsqlItem.GLOBAL_ATTRIBUTE7 := aSqlItem.GLOBAL_ATTRIBUTE7;
		aPlsqlItem.GLOBAL_ATTRIBUTE8 := aSqlItem.GLOBAL_ATTRIBUTE8;
		aPlsqlItem.GLOBAL_ATTRIBUTE9 := aSqlItem.GLOBAL_ATTRIBUTE9;
		aPlsqlItem.GLOBAL_ATTRIBUTE10 := aSqlItem.GLOBAL_ATTRIBUTE10;
		aPlsqlItem.GLOBAL_ATTRIBUTE11 := aSqlItem.GLOBAL_ATTRIBUTE11;
		aPlsqlItem.GLOBAL_ATTRIBUTE12 := aSqlItem.GLOBAL_ATTRIBUTE12;
		aPlsqlItem.GLOBAL_ATTRIBUTE13 := aSqlItem.GLOBAL_ATTRIBUTE13;
		aPlsqlItem.GLOBAL_ATTRIBUTE14 := aSqlItem.GLOBAL_ATTRIBUTE14;
		aPlsqlItem.GLOBAL_ATTRIBUTE15 := aSqlItem.GLOBAL_ATTRIBUTE15;
		aPlsqlItem.GLOBAL_ATTRIBUTE16 := aSqlItem.GLOBAL_ATTRIBUTE16;
		aPlsqlItem.GLOBAL_ATTRIBUTE17 := aSqlItem.GLOBAL_ATTRIBUTE17;
		aPlsqlItem.GLOBAL_ATTRIBUTE18 := aSqlItem.GLOBAL_ATTRIBUTE18;
		aPlsqlItem.GLOBAL_ATTRIBUTE19 := aSqlItem.GLOBAL_ATTRIBUTE19;
		aPlsqlItem.GLOBAL_ATTRIBUTE20 := aSqlItem.GLOBAL_ATTRIBUTE20;
		aPlsqlItem.PO_RELEASE_ID := aSqlItem.PO_RELEASE_ID;
		aPlsqlItem.RELEASE_NUM := aSqlItem.RELEASE_NUM;
		aPlsqlItem.ACCOUNT_SEGMENT := aSqlItem.ACCOUNT_SEGMENT;
		aPlsqlItem.BALANCING_SEGMENT := aSqlItem.BALANCING_SEGMENT;
		aPlsqlItem.COST_CENTER_SEGMENT := aSqlItem.COST_CENTER_SEGMENT;
		aPlsqlItem.PROJECT_ID := aSqlItem.PROJECT_ID;
		aPlsqlItem.TASK_ID := aSqlItem.TASK_ID;
		aPlsqlItem.EXPENDITURE_TYPE := aSqlItem.EXPENDITURE_TYPE;
		aPlsqlItem.EXPENDITURE_ITEM_DATE := aSqlItem.EXPENDITURE_ITEM_DATE;
		aPlsqlItem.EXPENDITURE_ORGANIZATION_ID := aSqlItem.EXPENDITURE_ORGANIZATION_ID;
		aPlsqlItem.PROJECT_ACCOUNTING_CONTEXT := aSqlItem.PROJECT_ACCOUNTING_CONTEXT;
		aPlsqlItem.PA_ADDITION_FLAG := aSqlItem.PA_ADDITION_FLAG;
		aPlsqlItem.PA_QUANTITY := aSqlItem.PA_QUANTITY;
		aPlsqlItem.USSGL_TRANSACTION_CODE := aSqlItem.USSGL_TRANSACTION_CODE;
		aPlsqlItem.STAT_AMOUNT := aSqlItem.STAT_AMOUNT;
		aPlsqlItem.TYPE_1099 := aSqlItem.TYPE_1099;
		aPlsqlItem.INCOME_TAX_REGION := aSqlItem.INCOME_TAX_REGION;
		aPlsqlItem.ASSETS_TRACKING_FLAG := aSqlItem.ASSETS_TRACKING_FLAG;
		aPlsqlItem.PRICE_CORRECTION_FLAG := aSqlItem.PRICE_CORRECTION_FLAG;
		aPlsqlItem.ORG_ID := aSqlItem.ORG_ID;
		aPlsqlItem.RECEIPT_NUMBER := aSqlItem.RECEIPT_NUMBER;
		aPlsqlItem.RECEIPT_LINE_NUMBER := aSqlItem.RECEIPT_LINE_NUMBER;
		aPlsqlItem.MATCH_OPTION := aSqlItem.MATCH_OPTION;
		aPlsqlItem.PACKING_SLIP := aSqlItem.PACKING_SLIP;
		aPlsqlItem.RCV_TRANSACTION_ID := aSqlItem.RCV_TRANSACTION_ID;
		aPlsqlItem.PA_CC_AR_INVOICE_ID := aSqlItem.PA_CC_AR_INVOICE_ID;
		aPlsqlItem.PA_CC_AR_INVOICE_LINE_NUM := aSqlItem.PA_CC_AR_INVOICE_LINE_NUM;
		aPlsqlItem.REFERENCE_1 := aSqlItem.REFERENCE_1;
		aPlsqlItem.REFERENCE_2 := aSqlItem.REFERENCE_2;
		aPlsqlItem.PA_CC_PROCESSED_CODE := aSqlItem.PA_CC_PROCESSED_CODE;
		aPlsqlItem.TAX_RECOVERY_RATE := aSqlItem.TAX_RECOVERY_RATE;
		aPlsqlItem.TAX_RECOVERY_OVERRIDE_FLAG := aSqlItem.TAX_RECOVERY_OVERRIDE_FLAG;
		aPlsqlItem.TAX_RECOVERABLE_FLAG := aSqlItem.TAX_RECOVERABLE_FLAG;
		aPlsqlItem.TAX_CODE_OVERRIDE_FLAG := aSqlItem.TAX_CODE_OVERRIDE_FLAG;
		aPlsqlItem.TAX_CODE_ID := aSqlItem.TAX_CODE_ID;
		aPlsqlItem.CREDIT_CARD_TRX_ID := aSqlItem.CREDIT_CARD_TRX_ID;
		aPlsqlItem.AWARD_ID := aSqlItem.AWARD_ID;
		aPlsqlItem.VENDOR_ITEM_NUM := aSqlItem.VENDOR_ITEM_NUM;
		aPlsqlItem.TAXABLE_FLAG := aSqlItem.TAXABLE_FLAG;
		aPlsqlItem.PRICE_CORRECT_INV_NUM := aSqlItem.PRICE_CORRECT_INV_NUM;
		aPlsqlItem.EXTERNAL_DOC_LINE_REF := aSqlItem.EXTERNAL_DOC_LINE_REF;
		RETURN aPlsqlItem;
	END SQL_TO_PL2;
	FUNCTION PL_TO_SQL1(aPlsqlItem XX_CS_TDS_AP_INVOICE_PKG.T_INVDETRECTBL)
 	RETURN XX_CS_TDS_AP_INX1326404X1X97 IS 
	aSqlItem XX_CS_TDS_AP_INX1326404X1X97; 
	BEGIN 
		-- initialize the table 
		aSqlItem := XX_CS_TDS_AP_INX1326404X1X97();
		IF aPlsqlItem IS NOT NULL THEN
		aSqlItem.EXTEND(aPlsqlItem.COUNT);
		IF aPlsqlItem.COUNT>0 THEN
		FOR I IN aPlsqlItem.FIRST..aPlsqlItem.LAST LOOP
			aSqlItem(I + 1 - aPlsqlItem.FIRST) := PL_TO_SQL0(aPlsqlItem(I));
		END LOOP; 
		END IF; 
		END IF; 
		RETURN aSqlItem;
	END PL_TO_SQL1;
	FUNCTION SQL_TO_PL1(aSqlItem XX_CS_TDS_AP_INX1326404X1X97) 
	RETURN XX_CS_TDS_AP_INVOICE_PKG.T_INVDETRECTBL IS 
	aPlsqlItem XX_CS_TDS_AP_INVOICE_PKG.T_INVDETRECTBL; 
	BEGIN 
		IF aSqlItem.COUNT>0 THEN
		FOR I IN 1..aSqlItem.COUNT LOOP
			aPlsqlItem(I) := SQL_TO_PL2(aSqlItem(I));
		END LOOP; 
		END IF;
		RETURN aPlsqlItem;
	END SQL_TO_PL1;
	FUNCTION PL_TO_SQL2(aPlsqlItem ROWTYPE_PL8)
 	RETURN XX_CS_TDS_AP_INVX1326404X1X1 IS 
	aSqlItem XX_CS_TDS_AP_INVX1326404X1X1; 
	BEGIN 
		-- initialize the object
		aSqlItem := XX_CS_TDS_AP_INVX1326404X1X1(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL);
		aSqlItem.INVOICE_ID := aPlsqlItem.INVOICE_ID;
		aSqlItem.INVOICE_NUM := aPlsqlItem.INVOICE_NUM;
		aSqlItem.INVOICE_TYPE_LOOKUP_CODE := aPlsqlItem.INVOICE_TYPE_LOOKUP_CODE;
		aSqlItem.INVOICE_DATE := aPlsqlItem.INVOICE_DATE;
		aSqlItem.PO_NUMBER := aPlsqlItem.PO_NUMBER;
		aSqlItem.VENDOR_ID := aPlsqlItem.VENDOR_ID;
		aSqlItem.VENDOR_NUM := aPlsqlItem.VENDOR_NUM;
		aSqlItem.VENDOR_NAME := aPlsqlItem.VENDOR_NAME;
		aSqlItem.VENDOR_SITE_ID := aPlsqlItem.VENDOR_SITE_ID;
		aSqlItem.VENDOR_SITE_CODE := aPlsqlItem.VENDOR_SITE_CODE;
		aSqlItem.INVOICE_AMOUNT := aPlsqlItem.INVOICE_AMOUNT;
		aSqlItem.INVOICE_CURRENCY_CODE := aPlsqlItem.INVOICE_CURRENCY_CODE;
		aSqlItem.EXCHANGE_RATE := aPlsqlItem.EXCHANGE_RATE;
		aSqlItem.EXCHANGE_RATE_TYPE := aPlsqlItem.EXCHANGE_RATE_TYPE;
		aSqlItem.EXCHANGE_DATE := aPlsqlItem.EXCHANGE_DATE;
		aSqlItem.TERMS_ID := aPlsqlItem.TERMS_ID;
		aSqlItem.TERMS_NAME := aPlsqlItem.TERMS_NAME;
		aSqlItem.DESCRIPTION := aPlsqlItem.DESCRIPTION;
		aSqlItem.AWT_GROUP_ID := aPlsqlItem.AWT_GROUP_ID;
		aSqlItem.AWT_GROUP_NAME := aPlsqlItem.AWT_GROUP_NAME;
		aSqlItem.LAST_UPDATE_DATE := aPlsqlItem.LAST_UPDATE_DATE;
		aSqlItem.LAST_UPDATED_BY := aPlsqlItem.LAST_UPDATED_BY;
		aSqlItem.LAST_UPDATE_LOGIN := aPlsqlItem.LAST_UPDATE_LOGIN;
		aSqlItem.CREATION_DATE := aPlsqlItem.CREATION_DATE;
		aSqlItem.CREATED_BY := aPlsqlItem.CREATED_BY;
		aSqlItem.ATTRIBUTE_CATEGORY := aPlsqlItem.ATTRIBUTE_CATEGORY;
		aSqlItem.ATTRIBUTE1 := aPlsqlItem.ATTRIBUTE1;
		aSqlItem.ATTRIBUTE2 := aPlsqlItem.ATTRIBUTE2;
		aSqlItem.ATTRIBUTE3 := aPlsqlItem.ATTRIBUTE3;
		aSqlItem.ATTRIBUTE4 := aPlsqlItem.ATTRIBUTE4;
		aSqlItem.ATTRIBUTE5 := aPlsqlItem.ATTRIBUTE5;
		aSqlItem.ATTRIBUTE6 := aPlsqlItem.ATTRIBUTE6;
		aSqlItem.ATTRIBUTE7 := aPlsqlItem.ATTRIBUTE7;
		aSqlItem.ATTRIBUTE8 := aPlsqlItem.ATTRIBUTE8;
		aSqlItem.ATTRIBUTE9 := aPlsqlItem.ATTRIBUTE9;
		aSqlItem.ATTRIBUTE10 := aPlsqlItem.ATTRIBUTE10;
		aSqlItem.ATTRIBUTE11 := aPlsqlItem.ATTRIBUTE11;
		aSqlItem.ATTRIBUTE12 := aPlsqlItem.ATTRIBUTE12;
		aSqlItem.ATTRIBUTE13 := aPlsqlItem.ATTRIBUTE13;
		aSqlItem.ATTRIBUTE14 := aPlsqlItem.ATTRIBUTE14;
		aSqlItem.ATTRIBUTE15 := aPlsqlItem.ATTRIBUTE15;
		aSqlItem.GLOBAL_ATTRIBUTE_CATEGORY := aPlsqlItem.GLOBAL_ATTRIBUTE_CATEGORY;
		aSqlItem.GLOBAL_ATTRIBUTE1 := aPlsqlItem.GLOBAL_ATTRIBUTE1;
		aSqlItem.GLOBAL_ATTRIBUTE2 := aPlsqlItem.GLOBAL_ATTRIBUTE2;
		aSqlItem.GLOBAL_ATTRIBUTE3 := aPlsqlItem.GLOBAL_ATTRIBUTE3;
		aSqlItem.GLOBAL_ATTRIBUTE4 := aPlsqlItem.GLOBAL_ATTRIBUTE4;
		aSqlItem.GLOBAL_ATTRIBUTE5 := aPlsqlItem.GLOBAL_ATTRIBUTE5;
		aSqlItem.GLOBAL_ATTRIBUTE6 := aPlsqlItem.GLOBAL_ATTRIBUTE6;
		aSqlItem.GLOBAL_ATTRIBUTE7 := aPlsqlItem.GLOBAL_ATTRIBUTE7;
		aSqlItem.GLOBAL_ATTRIBUTE8 := aPlsqlItem.GLOBAL_ATTRIBUTE8;
		aSqlItem.GLOBAL_ATTRIBUTE9 := aPlsqlItem.GLOBAL_ATTRIBUTE9;
		aSqlItem.GLOBAL_ATTRIBUTE10 := aPlsqlItem.GLOBAL_ATTRIBUTE10;
		aSqlItem.GLOBAL_ATTRIBUTE11 := aPlsqlItem.GLOBAL_ATTRIBUTE11;
		aSqlItem.GLOBAL_ATTRIBUTE12 := aPlsqlItem.GLOBAL_ATTRIBUTE12;
		aSqlItem.GLOBAL_ATTRIBUTE13 := aPlsqlItem.GLOBAL_ATTRIBUTE13;
		aSqlItem.GLOBAL_ATTRIBUTE14 := aPlsqlItem.GLOBAL_ATTRIBUTE14;
		aSqlItem.GLOBAL_ATTRIBUTE15 := aPlsqlItem.GLOBAL_ATTRIBUTE15;
		aSqlItem.GLOBAL_ATTRIBUTE16 := aPlsqlItem.GLOBAL_ATTRIBUTE16;
		aSqlItem.GLOBAL_ATTRIBUTE17 := aPlsqlItem.GLOBAL_ATTRIBUTE17;
		aSqlItem.GLOBAL_ATTRIBUTE18 := aPlsqlItem.GLOBAL_ATTRIBUTE18;
		aSqlItem.GLOBAL_ATTRIBUTE19 := aPlsqlItem.GLOBAL_ATTRIBUTE19;
		aSqlItem.GLOBAL_ATTRIBUTE20 := aPlsqlItem.GLOBAL_ATTRIBUTE20;
		aSqlItem.STATUS := aPlsqlItem.STATUS;
		aSqlItem.SOURCE := aPlsqlItem.SOURCE;
		aSqlItem.GROUP_ID := aPlsqlItem.GROUP_ID;
		aSqlItem.REQUEST_ID := aPlsqlItem.REQUEST_ID;
		aSqlItem.PAYMENT_CROSS_RATE_TYPE := aPlsqlItem.PAYMENT_CROSS_RATE_TYPE;
		aSqlItem.PAYMENT_CROSS_RATE_DATE := aPlsqlItem.PAYMENT_CROSS_RATE_DATE;
		aSqlItem.PAYMENT_CROSS_RATE := aPlsqlItem.PAYMENT_CROSS_RATE;
		aSqlItem.PAYMENT_CURRENCY_CODE := aPlsqlItem.PAYMENT_CURRENCY_CODE;
		aSqlItem.WORKFLOW_FLAG := aPlsqlItem.WORKFLOW_FLAG;
		aSqlItem.DOC_CATEGORY_CODE := aPlsqlItem.DOC_CATEGORY_CODE;
		aSqlItem.VOUCHER_NUM := aPlsqlItem.VOUCHER_NUM;
		aSqlItem.PAYMENT_METHOD_LOOKUP_CODE := aPlsqlItem.PAYMENT_METHOD_LOOKUP_CODE;
		aSqlItem.PAY_GROUP_LOOKUP_CODE := aPlsqlItem.PAY_GROUP_LOOKUP_CODE;
		aSqlItem.GOODS_RECEIVED_DATE := aPlsqlItem.GOODS_RECEIVED_DATE;
		aSqlItem.INVOICE_RECEIVED_DATE := aPlsqlItem.INVOICE_RECEIVED_DATE;
		aSqlItem.GL_DATE := aPlsqlItem.GL_DATE;
		aSqlItem.ACCTS_PAY_CODE_COMBINATION_ID := aPlsqlItem.ACCTS_PAY_CODE_COMBINATION_ID;
		aSqlItem.USSGL_TRANSACTION_CODE := aPlsqlItem.USSGL_TRANSACTION_CODE;
		aSqlItem.EXCLUSIVE_PAYMENT_FLAG := aPlsqlItem.EXCLUSIVE_PAYMENT_FLAG;
		aSqlItem.ORG_ID := aPlsqlItem.ORG_ID;
		aSqlItem.AMOUNT_APPLICABLE_TO_DISCOUNT := aPlsqlItem.AMOUNT_APPLICABLE_TO_DISCOUNT;
		aSqlItem.PREPAY_NUM := aPlsqlItem.PREPAY_NUM;
		aSqlItem.PREPAY_DIST_NUM := aPlsqlItem.PREPAY_DIST_NUM;
		aSqlItem.PREPAY_APPLY_AMOUNT := aPlsqlItem.PREPAY_APPLY_AMOUNT;
		aSqlItem.PREPAY_GL_DATE := aPlsqlItem.PREPAY_GL_DATE;
		aSqlItem.INVOICE_INCLUDES_PREPAY_FLAG := aPlsqlItem.INVOICE_INCLUDES_PREPAY_FLAG;
		aSqlItem.NO_XRATE_BASE_AMOUNT := aPlsqlItem.NO_XRATE_BASE_AMOUNT;
		aSqlItem.VENDOR_EMAIL_ADDRESS := aPlsqlItem.VENDOR_EMAIL_ADDRESS;
		aSqlItem.TERMS_DATE := aPlsqlItem.TERMS_DATE;
		aSqlItem.REQUESTER_ID := aPlsqlItem.REQUESTER_ID;
		aSqlItem.SHIP_TO_LOCATION := aPlsqlItem.SHIP_TO_LOCATION;
		aSqlItem.EXTERNAL_DOC_REF := aPlsqlItem.EXTERNAL_DOC_REF;
		aSqlItem.ACCTS_PAY_CODE_CONCATENATED := aPlsqlItem.ACCTS_PAY_CODE_CONCATENATED;
		RETURN aSqlItem;
	END PL_TO_SQL2;
	FUNCTION SQL_TO_PL0(aSqlItem XX_CS_TDS_AP_INVX1326404X1X1) 
	RETURN ROWTYPE_PL8 IS 
	aPlsqlItem ROWTYPE_PL8; 
	BEGIN 
		aPlsqlItem.INVOICE_ID := aSqlItem.INVOICE_ID;
		aPlsqlItem.INVOICE_NUM := aSqlItem.INVOICE_NUM;
		aPlsqlItem.INVOICE_TYPE_LOOKUP_CODE := aSqlItem.INVOICE_TYPE_LOOKUP_CODE;
		aPlsqlItem.INVOICE_DATE := aSqlItem.INVOICE_DATE;
		aPlsqlItem.PO_NUMBER := aSqlItem.PO_NUMBER;
		aPlsqlItem.VENDOR_ID := aSqlItem.VENDOR_ID;
		aPlsqlItem.VENDOR_NUM := aSqlItem.VENDOR_NUM;
		aPlsqlItem.VENDOR_NAME := aSqlItem.VENDOR_NAME;
		aPlsqlItem.VENDOR_SITE_ID := aSqlItem.VENDOR_SITE_ID;
		aPlsqlItem.VENDOR_SITE_CODE := aSqlItem.VENDOR_SITE_CODE;
		aPlsqlItem.INVOICE_AMOUNT := aSqlItem.INVOICE_AMOUNT;
		aPlsqlItem.INVOICE_CURRENCY_CODE := aSqlItem.INVOICE_CURRENCY_CODE;
		aPlsqlItem.EXCHANGE_RATE := aSqlItem.EXCHANGE_RATE;
		aPlsqlItem.EXCHANGE_RATE_TYPE := aSqlItem.EXCHANGE_RATE_TYPE;
		aPlsqlItem.EXCHANGE_DATE := aSqlItem.EXCHANGE_DATE;
		aPlsqlItem.TERMS_ID := aSqlItem.TERMS_ID;
		aPlsqlItem.TERMS_NAME := aSqlItem.TERMS_NAME;
		aPlsqlItem.DESCRIPTION := aSqlItem.DESCRIPTION;
		aPlsqlItem.AWT_GROUP_ID := aSqlItem.AWT_GROUP_ID;
		aPlsqlItem.AWT_GROUP_NAME := aSqlItem.AWT_GROUP_NAME;
		aPlsqlItem.LAST_UPDATE_DATE := aSqlItem.LAST_UPDATE_DATE;
		aPlsqlItem.LAST_UPDATED_BY := aSqlItem.LAST_UPDATED_BY;
		aPlsqlItem.LAST_UPDATE_LOGIN := aSqlItem.LAST_UPDATE_LOGIN;
		aPlsqlItem.CREATION_DATE := aSqlItem.CREATION_DATE;
		aPlsqlItem.CREATED_BY := aSqlItem.CREATED_BY;
		aPlsqlItem.ATTRIBUTE_CATEGORY := aSqlItem.ATTRIBUTE_CATEGORY;
		aPlsqlItem.ATTRIBUTE1 := aSqlItem.ATTRIBUTE1;
		aPlsqlItem.ATTRIBUTE2 := aSqlItem.ATTRIBUTE2;
		aPlsqlItem.ATTRIBUTE3 := aSqlItem.ATTRIBUTE3;
		aPlsqlItem.ATTRIBUTE4 := aSqlItem.ATTRIBUTE4;
		aPlsqlItem.ATTRIBUTE5 := aSqlItem.ATTRIBUTE5;
		aPlsqlItem.ATTRIBUTE6 := aSqlItem.ATTRIBUTE6;
		aPlsqlItem.ATTRIBUTE7 := aSqlItem.ATTRIBUTE7;
		aPlsqlItem.ATTRIBUTE8 := aSqlItem.ATTRIBUTE8;
		aPlsqlItem.ATTRIBUTE9 := aSqlItem.ATTRIBUTE9;
		aPlsqlItem.ATTRIBUTE10 := aSqlItem.ATTRIBUTE10;
		aPlsqlItem.ATTRIBUTE11 := aSqlItem.ATTRIBUTE11;
		aPlsqlItem.ATTRIBUTE12 := aSqlItem.ATTRIBUTE12;
		aPlsqlItem.ATTRIBUTE13 := aSqlItem.ATTRIBUTE13;
		aPlsqlItem.ATTRIBUTE14 := aSqlItem.ATTRIBUTE14;
		aPlsqlItem.ATTRIBUTE15 := aSqlItem.ATTRIBUTE15;
		aPlsqlItem.GLOBAL_ATTRIBUTE_CATEGORY := aSqlItem.GLOBAL_ATTRIBUTE_CATEGORY;
		aPlsqlItem.GLOBAL_ATTRIBUTE1 := aSqlItem.GLOBAL_ATTRIBUTE1;
		aPlsqlItem.GLOBAL_ATTRIBUTE2 := aSqlItem.GLOBAL_ATTRIBUTE2;
		aPlsqlItem.GLOBAL_ATTRIBUTE3 := aSqlItem.GLOBAL_ATTRIBUTE3;
		aPlsqlItem.GLOBAL_ATTRIBUTE4 := aSqlItem.GLOBAL_ATTRIBUTE4;
		aPlsqlItem.GLOBAL_ATTRIBUTE5 := aSqlItem.GLOBAL_ATTRIBUTE5;
		aPlsqlItem.GLOBAL_ATTRIBUTE6 := aSqlItem.GLOBAL_ATTRIBUTE6;
		aPlsqlItem.GLOBAL_ATTRIBUTE7 := aSqlItem.GLOBAL_ATTRIBUTE7;
		aPlsqlItem.GLOBAL_ATTRIBUTE8 := aSqlItem.GLOBAL_ATTRIBUTE8;
		aPlsqlItem.GLOBAL_ATTRIBUTE9 := aSqlItem.GLOBAL_ATTRIBUTE9;
		aPlsqlItem.GLOBAL_ATTRIBUTE10 := aSqlItem.GLOBAL_ATTRIBUTE10;
		aPlsqlItem.GLOBAL_ATTRIBUTE11 := aSqlItem.GLOBAL_ATTRIBUTE11;
		aPlsqlItem.GLOBAL_ATTRIBUTE12 := aSqlItem.GLOBAL_ATTRIBUTE12;
		aPlsqlItem.GLOBAL_ATTRIBUTE13 := aSqlItem.GLOBAL_ATTRIBUTE13;
		aPlsqlItem.GLOBAL_ATTRIBUTE14 := aSqlItem.GLOBAL_ATTRIBUTE14;
		aPlsqlItem.GLOBAL_ATTRIBUTE15 := aSqlItem.GLOBAL_ATTRIBUTE15;
		aPlsqlItem.GLOBAL_ATTRIBUTE16 := aSqlItem.GLOBAL_ATTRIBUTE16;
		aPlsqlItem.GLOBAL_ATTRIBUTE17 := aSqlItem.GLOBAL_ATTRIBUTE17;
		aPlsqlItem.GLOBAL_ATTRIBUTE18 := aSqlItem.GLOBAL_ATTRIBUTE18;
		aPlsqlItem.GLOBAL_ATTRIBUTE19 := aSqlItem.GLOBAL_ATTRIBUTE19;
		aPlsqlItem.GLOBAL_ATTRIBUTE20 := aSqlItem.GLOBAL_ATTRIBUTE20;
		aPlsqlItem.STATUS := aSqlItem.STATUS;
		aPlsqlItem.SOURCE := aSqlItem.SOURCE;
		aPlsqlItem.GROUP_ID := aSqlItem.GROUP_ID;
		aPlsqlItem.REQUEST_ID := aSqlItem.REQUEST_ID;
		aPlsqlItem.PAYMENT_CROSS_RATE_TYPE := aSqlItem.PAYMENT_CROSS_RATE_TYPE;
		aPlsqlItem.PAYMENT_CROSS_RATE_DATE := aSqlItem.PAYMENT_CROSS_RATE_DATE;
		aPlsqlItem.PAYMENT_CROSS_RATE := aSqlItem.PAYMENT_CROSS_RATE;
		aPlsqlItem.PAYMENT_CURRENCY_CODE := aSqlItem.PAYMENT_CURRENCY_CODE;
		aPlsqlItem.WORKFLOW_FLAG := aSqlItem.WORKFLOW_FLAG;
		aPlsqlItem.DOC_CATEGORY_CODE := aSqlItem.DOC_CATEGORY_CODE;
		aPlsqlItem.VOUCHER_NUM := aSqlItem.VOUCHER_NUM;
		aPlsqlItem.PAYMENT_METHOD_LOOKUP_CODE := aSqlItem.PAYMENT_METHOD_LOOKUP_CODE;
		aPlsqlItem.PAY_GROUP_LOOKUP_CODE := aSqlItem.PAY_GROUP_LOOKUP_CODE;
		aPlsqlItem.GOODS_RECEIVED_DATE := aSqlItem.GOODS_RECEIVED_DATE;
		aPlsqlItem.INVOICE_RECEIVED_DATE := aSqlItem.INVOICE_RECEIVED_DATE;
		aPlsqlItem.GL_DATE := aSqlItem.GL_DATE;
		aPlsqlItem.ACCTS_PAY_CODE_COMBINATION_ID := aSqlItem.ACCTS_PAY_CODE_COMBINATION_ID;
		aPlsqlItem.USSGL_TRANSACTION_CODE := aSqlItem.USSGL_TRANSACTION_CODE;
		aPlsqlItem.EXCLUSIVE_PAYMENT_FLAG := aSqlItem.EXCLUSIVE_PAYMENT_FLAG;
		aPlsqlItem.ORG_ID := aSqlItem.ORG_ID;
		aPlsqlItem.AMOUNT_APPLICABLE_TO_DISCOUNT := aSqlItem.AMOUNT_APPLICABLE_TO_DISCOUNT;
		aPlsqlItem.PREPAY_NUM := aSqlItem.PREPAY_NUM;
		aPlsqlItem.PREPAY_DIST_NUM := aSqlItem.PREPAY_DIST_NUM;
		aPlsqlItem.PREPAY_APPLY_AMOUNT := aSqlItem.PREPAY_APPLY_AMOUNT;
		aPlsqlItem.PREPAY_GL_DATE := aSqlItem.PREPAY_GL_DATE;
		aPlsqlItem.INVOICE_INCLUDES_PREPAY_FLAG := aSqlItem.INVOICE_INCLUDES_PREPAY_FLAG;
		aPlsqlItem.NO_XRATE_BASE_AMOUNT := aSqlItem.NO_XRATE_BASE_AMOUNT;
		aPlsqlItem.VENDOR_EMAIL_ADDRESS := aSqlItem.VENDOR_EMAIL_ADDRESS;
		aPlsqlItem.TERMS_DATE := aSqlItem.TERMS_DATE;
		aPlsqlItem.REQUESTER_ID := aSqlItem.REQUESTER_ID;
		aPlsqlItem.SHIP_TO_LOCATION := aSqlItem.SHIP_TO_LOCATION;
		aPlsqlItem.EXTERNAL_DOC_REF := aSqlItem.EXTERNAL_DOC_REF;
		aPlsqlItem.ACCTS_PAY_CODE_CONCATENATED := aSqlItem.ACCTS_PAY_CODE_CONCATENATED;
		RETURN aPlsqlItem;
	END SQL_TO_PL0;

   PROCEDURE xx_cs_tds_ap_invoice_pkg$inse (P_HEADER_REC XX_CS_TDS_AP_INVX1326404X1X1,
	P_LINES_TAB APPS.XX_CS_TDS_AP_INX1326404X1X97,
	X_STATUS OUT VARCHAR2,
	X_MSG_DATA OUT VARCHAR2
	) IS
 P_HEADER_REC_ ROWTYPE_PL8;
 P_LINES_TAB_ APPS.XX_CS_TDS_AP_INVOICE_PKG.T_INVDETRECTBL;
   BEGIN
 P_HEADER_REC_ := XX_CS_TDS_AP_INVOICE_BPEL_PKG.SQL_TO_PL0(P_HEADER_REC);
 P_LINES_TAB_ := XX_CS_TDS_AP_INVOICE_BPEL_PKG.SQL_TO_PL1(P_LINES_TAB);
      APPS.XX_CS_TDS_AP_INVOICE_PKG.INSERT_PROC(P_HEADER_REC_,
	P_LINES_TAB_,
	X_STATUS,
	X_MSG_DATA
	);
   END xx_cs_tds_ap_invoice_pkg$inse;

END XX_CS_TDS_AP_INVOICE_BPEL_PKG;
/
show errors
exit
