/*===========================================================================+
 |      		       Office Depot - Project Simplify                     |
 |           			 WIPRO/Office Depot  				     |
 +===========================================================================+
 |  FILENAME                                                                 |
 |             ODOpptySearchVO4RowImpl.java                                   |
 |                                                                           |
 |  DESCRIPTION                                                              |
 |  Subversion Info:
 |  $HeadURL: http://svn.na.odcorp.net/svn/od/common/trunk/xxcomn/java/od/oracle/apps/xxcrm/asn/opportunity/server/ODOpptySearchVO4RowImpl.java $
 |  $Rev: 91791 $
 |  $Date: 2010-01-27 00:19:14 -0500 (Wed, 27 Jan 2010) $
 |                                                                           |                                                                           
 |                                                                           |
 |  NOTES                                                                    |
 |                                                                           |
 |                                                                           |
 |                                                                           |
 |  HISTORY                                                                  |
 |                                                                           |
 |    05-Jan-2010 Annapoorani Rajaguru  Defect #2264                         |
 +===========================================================================*/

package od.oracle.apps.xxcrm.asn.opportunity.server;

import oracle.apps.asn.opportunity.schema.server.OpportunityEOImpl;
import oracle.apps.asn.opportunity.server.OpptySearchVORowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import java.sql.SQLException;
import java.sql.Types;

import oracle.apps.asn.common.fwk.server.ASNApplicationModuleImpl;
import oracle.apps.fnd.framework.server.OADBTransaction;

import oracle.jdbc.internal.OracleCallableStatement;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ODOpptySearchVO4RowImpl extends OpptySearchVORowImpl {
    public static final int MAXATTRCONST = oracle.jbo.server.ViewDefImpl.getMaxAttrConst("oracle.apps.asn.opportunity.server.OpptySearchVO");

    /**This is the default constructor (do not remove)
     */
    public ODOpptySearchVO4RowImpl() {
    }

    /**Gets OpportunityEO entity object.
     */
    public OpportunityEOImpl getOpportunityEO() {
        return (OpportunityEOImpl)getEntity(0);
    }

    /**Gets the attribute value for LEAD_ID using the alias name LeadId
     */
    public Number getLeadId() {
        return super.getLeadId();
    }

    /**Sets <code>value</code> as attribute value for LEAD_ID using the alias name LeadId
     */
    public void setLeadId(Number value) {
        super.setLeadId(value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return super.getLastUpdateDate();
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        super.setLastUpdateDate(value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return super.getCreationDate();
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        super.setCreationDate(value);
    }

    /**Gets the attribute value for LEAD_NUMBER using the alias name LeadNumber
     */
    public String getLeadNumber() {
        return super.getLeadNumber();
    }

    /**Sets <code>value</code> as attribute value for LEAD_NUMBER using the alias name LeadNumber
     */
    public void setLeadNumber(String value) {
        super.setLeadNumber(value);
    }

    /**Gets the attribute value for CUSTOMER_ID using the alias name CustomerId
     */
    public Number getCustomerId() {
        return super.getCustomerId();
    }

    /**Sets <code>value</code> as attribute value for CUSTOMER_ID using the alias name CustomerId
     */
    public void setCustomerId(Number value) {
        super.setCustomerId(value);
    }

    /**Gets the attribute value for TOTAL_AMOUNT using the alias name TotalAmount
     */
    public Number getTotalAmount() {
        return super.getTotalAmount();
    }

    /**Sets <code>value</code> as attribute value for TOTAL_AMOUNT using the alias name TotalAmount
     */
    public void setTotalAmount(Number value) {
        super.setTotalAmount(value);
    }

    /**Gets the attribute value for DECISION_DATE using the alias name DecisionDate
     */
    public Date getDecisionDate() {
        return super.getDecisionDate();
    }

    /**Sets <code>value</code> as attribute value for DECISION_DATE using the alias name DecisionDate
     */
    public void setDecisionDate(Date value) {
        super.setDecisionDate(value);
    }

    /**Gets the attribute value for WIN_PROBABILITY using the alias name WinProbability
     */
    public Number getWinProbability() {
        return super.getWinProbability();
    }

    /**Sets <code>value</code> as attribute value for WIN_PROBABILITY using the alias name WinProbability
     */
    public void setWinProbability(Number value) {
        super.setWinProbability(value);
    }

    /**Gets the attribute value for DESCRIPTION using the alias name Description
     */
    public String getDescription() {
        return super.getDescription();
    }

    /**Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description
     */
    public void setDescription(String value) {
        super.setDescription(value);
    }

    /**Gets the attribute value for CURRENCY_CODE using the alias name CurrencyCode
     */
    public String getCurrencyCode() {
        return super.getCurrencyCode();
    }

    /**Sets <code>value</code> as attribute value for CURRENCY_CODE using the alias name CurrencyCode
     */
    public void setCurrencyCode(String value) {
        super.setCurrencyCode(value);
    }

    /**Gets the attribute value for SOURCE_PROMOTION_ID using the alias name SourcePromotionId
     */
    public Number getSourcePromotionId() {
        return super.getSourcePromotionId();
    }

    /**Sets <code>value</code> as attribute value for SOURCE_PROMOTION_ID using the alias name SourcePromotionId
     */
    public void setSourcePromotionId(Number value) {
        super.setSourcePromotionId(value);
    }

    /**Gets the attribute value for OWNER_SALESFORCE_ID using the alias name OwnerSalesforceId
     */
    public Number getOwnerSalesforceId() {
        return super.getOwnerSalesforceId();
    }

    /**Sets <code>value</code> as attribute value for OWNER_SALESFORCE_ID using the alias name OwnerSalesforceId
     */
    public void setOwnerSalesforceId(Number value) {
        super.setOwnerSalesforceId(value);
    }

    /**Gets the attribute value for TOTAL_REVENUE_OPP_FORECAST_AMT using the alias name TotalForecastAmount
     */
    public Number getTotalForecastAmount() {
        return super.getTotalForecastAmount();
    }

    /**Sets <code>value</code> as attribute value for TOTAL_REVENUE_OPP_FORECAST_AMT using the alias name TotalForecastAmount
     */
    public void setTotalForecastAmount(Number value) {
        super.setTotalForecastAmount(value);
    }

    /**Gets the attribute value for the calculated attribute VehicleResponseCode
     */
    public String getVehicleResponseCode() {
        return super.getVehicleResponseCode();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VehicleResponseCode
     */
    public void setVehicleResponseCode(String value) {
        super.setVehicleResponseCode(value);
    }

    /**Gets the attribute value for the calculated attribute OpptyStatusName
     */
    public String getOpptyStatusName() {
        return super.getOpptyStatusName();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OpptyStatusName
     */
    public void setOpptyStatusName(String value) {
        super.setOpptyStatusName(value);
    }

    /**Gets the attribute value for the calculated attribute CurrencyName
     */
    public String getCurrencyName() {
        return super.getCurrencyName();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CurrencyName
     */
    public void setCurrencyName(String value) {
        super.setCurrencyName(value);
    }

    /**Gets the attribute value for the calculated attribute SalesStageName
     */
    public String getSalesStageName() {
        return super.getSalesStageName();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SalesStageName
     */
    public void setSalesStageName(String value) {
        super.setSalesStageName(value);
    }

    /**Gets the attribute value for the calculated attribute PartyName
     */
    public String getPartyName() {
        return super.getPartyName();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PartyName
     */
    public void setPartyName(String value) {
        super.setPartyName(value);
    }

    /**Gets the attribute value for the calculated attribute CustomerCategory
     */
    public String getCustomerCategory() {
        return super.getCustomerCategory();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CustomerCategory
     */
    public void setCustomerCategory(String value) {
        super.setCustomerCategory(value);
    }

    /**Gets the attribute value for the calculated attribute PersonId
     */
    public Number getPersonId() {
        return super.getPersonId();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PersonId
     */
    public void setPersonId(Number value) {
        super.setPersonId(value);
    }

    /**Gets the attribute value for the calculated attribute ContactName
     */
    public String getContactName() {
        return super.getContactName();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ContactName
     */
    public void setContactName(String value) {
        super.setContactName(value);
    }

    /**Gets the attribute value for the calculated attribute PersonFirstName
     */
    public String getPersonFirstName() {
        return super.getPersonFirstName();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PersonFirstName
     */
    public void setPersonFirstName(String value) {
        super.setPersonFirstName(value);
    }

    /**Gets the attribute value for the calculated attribute PersonLastName
     */
    public String getPersonLastName() {
        return super.getPersonLastName();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PersonLastName
     */
    public void setPersonLastName(String value) {
        super.setPersonLastName(value);
    }

    /**Gets the attribute value for the calculated attribute PersonMiddleName
     */
    public String getPersonMiddleName() {
        return super.getPersonMiddleName();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PersonMiddleName
     */
    public void setPersonMiddleName(String value) {
        super.setPersonMiddleName(value);
    }

    /**Gets the attribute value for the calculated attribute Salutation
     */
    public String getSalutation() {
        return super.getSalutation();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Salutation
     */
    public void setSalutation(String value) {
        super.setSalutation(value);
    }

    /**Gets the attribute value for the calculated attribute EmailAddress
     */
    public String getEmailAddress() {
        return super.getEmailAddress();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmailAddress
     */
    public void setEmailAddress(String value) {
        super.setEmailAddress(value);
    }

    /**Gets the attribute value for the calculated attribute JobTitle
     */
    public String getJobTitle() {
        return super.getJobTitle();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute JobTitle
     */
    public void setJobTitle(String value) {
        super.setJobTitle(value);
    }

    /**Gets the attribute value for the calculated attribute FormattedPhone
     */
    public String getFormattedPhone() {
        return super.getFormattedPhone();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FormattedPhone
     */
    public void setFormattedPhone(String value) {
        super.setFormattedPhone(value);
    }

    /**Gets the attribute value for the calculated attribute State
     */
    public String getState() {
        return super.getState();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute State
     */
    public void setState(String value) {
        super.setState(value);
    }

    /**Gets the attribute value for the calculated attribute City
     */
    public String getCity() {
        return super.getCity();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute City
     */
    public void setCity(String value) {
        super.setCity(value);
    }

    /**Gets the attribute value for the calculated attribute Country
     */
    public String getCountry() {
        return super.getCountry();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Country
     */
    public void setCountry(String value) {
        super.setCountry(value);
    }

    /**Gets the attribute value for the calculated attribute Province
     */
    public String getProvince() {
        return super.getProvince();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Province
     */
    public void setProvince(String value) {
        super.setProvince(value);
    }

    /**Gets the attribute value for the calculated attribute PostalCode
     */
    public String getPostalCode() {
        return super.getPostalCode();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PostalCode
     */
    public void setPostalCode(String value) {
        super.setPostalCode(value);
    }

    /**Gets the attribute value for the calculated attribute Address
     */
    public String getAddress() {
        return super.getAddress();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Address
     */
    public void setAddress(String value) {
        super.setAddress(value);
    }

    /**Gets the attribute value for the calculated attribute SourceName
     */
    public String getSourceName() {
        return super.getSourceName();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SourceName
     */
    public void setSourceName(String value) {
        super.setSourceName(value);
    }

    /**Gets the attribute value for the calculated attribute ResourceName
     */
    public String getResourceName() {
        return super.getResourceName();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ResourceName
     */
    public void setResourceName(String value) {
        super.setResourceName(value);
    }

    /**Gets the attribute value for the calculated attribute SalesChannel
     */
    public String getSalesChannel() {
        return super.getSalesChannel();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SalesChannel
     */
    public void setSalesChannel(String value) {
        super.setSalesChannel(value);
    }

    /**Gets the attribute value for the calculated attribute RelationShipId
     */
    public Number getRelationShipId() {
        return super.getRelationShipId();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RelationShipId
     */
    public void setRelationShipId(Number value) {
        super.setRelationShipId(value);
    }

    /**Gets the attribute value for the calculated attribute PrimaryContactPartyId
     */
    public Number getPrimaryContactPartyId() {
        return super.getPrimaryContactPartyId();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PrimaryContactPartyId
     */
    public void setPrimaryContactPartyId(Number value) {
        super.setPrimaryContactPartyId(value);
    }

    /**Gets the attribute value for the calculated attribute CustState
     */
    public String getCustState() {
        return super.getCustState();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CustState
     */
    public void setCustState(String value) {
        super.setCustState(value);
    }

    /**Gets the attribute value for the calculated attribute CustCity
     */
    public String getCustCity() {
        return super.getCustCity();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CustCity
     */
    public void setCustCity(String value) {
        super.setCustCity(value);
    }

    /**Gets the attribute value for the calculated attribute CustCountry
     */
    public String getCustCountry() {
        return super.getCustCountry();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CustCountry
     */
    public void setCustCountry(String value) {
        super.setCustCountry(value);
    }

    /**Gets the attribute value for the calculated attribute CustProvince
     */
    public String getCustProvince() {
        return super.getCustProvince();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CustProvince
     */
    public void setCustProvince(String value) {
        super.setCustProvince(value);
    }

    /**Gets the attribute value for the calculated attribute CustPostalCode
     */
    public String getCustPostalCode() {
        return super.getCustPostalCode();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CustPostalCode
     */
    public void setCustPostalCode(String value) {
        super.setCustPostalCode(value);
    }

    /**Gets the attribute value for the calculated attribute CustAddress
     */
    public String getCustAddress() {
        return super.getCustAddress();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CustAddress
     */
    public void setCustAddress(String value) {
        super.setCustAddress(value);
    }

    /**Gets the attribute value for the calculated attribute OpptyUpdatedBy
     */
    public String getOpptyUpdatedBy() {
        return super.getOpptyUpdatedBy();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OpptyUpdatedBy
     */
    public void setOpptyUpdatedBy(String value) {
        super.setOpptyUpdatedBy(value);
    }

    /**Gets the attribute value for the calculated attribute OpptyCreatedBy
     */
    public String getOpptyCreatedBy() {
        return super.getOpptyCreatedBy();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OpptyCreatedBy
     */
    public void setOpptyCreatedBy(String value) {
        super.setOpptyCreatedBy(value);
    }

    /**Gets the attribute value for the calculated attribute MethodologyNm
     */
    public String getMethodologyNm() {
        return super.getMethodologyNm();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MethodologyNm
     */
    public void setMethodologyNm(String value) {
        super.setMethodologyNm(value);
    }

    /**Gets the attribute value for the calculated attribute CloseReason
     */
    public String getCloseReason() {
        return super.getCloseReason();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CloseReason
     */
    public void setCloseReason(String value) {
        super.setCloseReason(value);
    }

    /**Gets the attribute value for the calculated attribute AssignmentStatusNm
     */
    public String getAssignmentStatusNm() {
        return super.getAssignmentStatusNm();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AssignmentStatusNm
     */
    public void setAssignmentStatusNm(String value) {
        super.setAssignmentStatusNm(value);
    }

    /**Gets the attribute value for the calculated attribute ReferralCode
     */
    public String getReferralCode() {
        return super.getReferralCode();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ReferralCode
     */
    public void setReferralCode(String value) {
        super.setReferralCode(value);
    }

    /**Gets the attribute value for the calculated attribute SelectFlag
     */
    public String getSelectFlag() {
        return super.getSelectFlag();
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SelectFlag
     */
    public void setSelectFlag(String value) {
        super.setSelectFlag(value);
    }
    
    /*QC 2264 Changes - Annapoorani begin*/
    /**Gets the attribute value for the calculated attribute ProspectCust
     */
    public String getProspectCust() {
        String lProsCust = "Prospectt";
        ASNApplicationModuleImpl asnapplicationmoduleimpl = (ASNApplicationModuleImpl)getApplicationModule();
        OADBTransaction dbtransaction = asnapplicationmoduleimpl.getOADBTransaction();
        OracleCallableStatement oraclecallablestatement = null;
        Number custId = this.getCustomerId();
        lProsCust = custId.toString();
      
        try
        {
            oraclecallablestatement = (OracleCallableStatement)dbtransaction.createCallableStatement("begin :1 := XX_SFA_PROSPECT_CUST_PKG.XX_PROSPECT_CUST_FUNC(:2); end;", 1);
            oraclecallablestatement.registerOutParameter(1, Types.VARCHAR);
            oraclecallablestatement.setNUMBER(2, custId);
            oraclecallablestatement.execute();
            lProsCust = oraclecallablestatement.getString(1);
            oraclecallablestatement.close();
        }
        catch(SQLException sqlexception)
        {
            lProsCust = sqlexception.toString();
        }
        return lProsCust;    
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProspectCust
     */
    public void setProspectCust(String value) {
        }
    /*QC 2264 Changes - Annapoorani end*/

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {super.setAttrInvokeAccessor(index, value, attrDef);
        return;
    }
}
