<definitions
     name="EBSDeliveryUpdate"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/EBSDeliveryUpdate/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/EBSDeliveryUpdate/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/BPEL_ROADNET_DATEBASE/XX_OM_ROADNET_TO_EBS_PKG-24IMPO/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/db/"
    >
    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/" location="DBAdapterOutboundHeader.wsdl"/>
    <types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/APPS/BPEL_ROADNET_DATEBASE/XX_OM_ROADNET_TO_EBS_PKG-24IMPO/"
               schemaLocation="APPS_BPEL_ROADNET_DATEBASE_XX_OM_ROADNET_TO_EBS_PKG-24IMPO.xsd" />
     </schema>
    </types>
    <message name="args_in_msg">
        <part name="InputParameters" element="db:InputParameters"/>
    </message>
    <portType name="EBSDeliveryUpdate_ptt">
        <operation name="EBSDeliveryUpdate">
            <input message="tns:args_in_msg"/>
        </operation>
    </portType>
    <binding name="EBSDeliveryUpdate_binding" type="tns:EBSDeliveryUpdate_ptt">
    <jca:binding  />
        <operation name="EBSDeliveryUpdate">
      <jca:operation
          SchemaName="APPS"
          PackageName="BPEL_ROADNET_DATEBASE"
          ProcedureName="XX_OM_ROADNET_TO_EBS_PKG$IMPO"
          InteractionSpec="oracle.tip.adapter.db.DBStoredProcedureInteractionSpec" >
      </jca:operation>
      <input>
        <jca:header message="hdr:OutboundHeader_msg" part="outboundHeader"/>
      </input>
        </operation>
    </binding>
    <service name="EBSDeliveryUpdate">
        <port name="EBSDeliveryUpdate_pt" binding="tns:EBSDeliveryUpdate_binding">
<!--Your runtime connection is declared in 
J2EE_HOME/application-deployments/default/DbAdapter/oc4j-ra.xml 
These mcf properties here are from your design time connection and 
save you from having to edit that file and restart the application server 
if eis/DB/LocalAPPS is missing. 
These mcf properties are safe to remove.-->
      <jca:address location="eis/DB/LocalAPPS" UIConnectionName="LocalAPPS"
          ManagedConnectionFactory="oracle.tip.adapter.db.DBManagedConnectionFactory"
          mcf.DriverClassName="oracle.jdbc.OracleDriver"
          mcf.PlatformClassName="oracle.toplink.internal.databaseaccess.Oracle9Platform"
          mcf.ConnectionString="jdbc:oracle:thin:@OSSI-0825:1521:GRAM"
          mcf.UserName="apps"
          mcf.Password="53CB0F044A0D3DD2C063679F18F89870" />
        </port>
    </service>
  <plt:partnerLinkType name="EBSDeliveryUpdate_plt" >
    <plt:role name="EBSDeliveryUpdate_role" >
      <plt:portType name="tns:EBSDeliveryUpdate_ptt" />
    </plt:role>
  </plt:partnerLinkType>
</definitions>
