-- Declare the SQL type for the PL/SQL type XX_QP_PRICELIST_PKG.OD_PRICE_LIST_REC_TYPE
CREATE OR REPLACE TYPE XX_QP_PRICELIST_PKG_OD_PRICE_ AS OBJECT (
      OPERATINGUNIT VARCHAR2(30),
      OPERATIONH VARCHAR2(30),
      OPERATIONL VARCHAR2(30),
      OPERATIONA VARCHAR2(30),
      NAME VARCHAR2(240),
      DESCRIPTION VARCHAR2(2000),
      CURRENCY_CODE VARCHAR2(30),
      ROUNDING_FACTOR NUMBER,
      ACTIVE_FLAG VARCHAR2(1),
      ATTRIBUTE6 VARCHAR2(240),
      ATTRIBUTE7 VARCHAR2(240),
      LANGUAGEH VARCHAR2(30),
      PRODUCT_ATTR_VALUE VARCHAR2(240),
      START_DATE_ACTIVEH DATE,
      END_DATE_ACTIVEH DATE,
      START_DATE_ACTIVEL DATE,
      END_DATE_ACTIVEL DATE,
      OPERAND NUMBER,
      PRODUCT_UOM_CODE VARCHAR2(3),
      MULTI_UNIT1 VARCHAR2(240),
      MULTI_UNIT2 VARCHAR2(240),
      MULTI_UNIT3 VARCHAR2(240),
      MULTI_UNIT4 VARCHAR2(240),
      MULTI_UNIT5 VARCHAR2(240),
      MULTI_UNIT6 VARCHAR2(240),
      MULTI_UNIT7 VARCHAR2(240),
      MULTI_UNIT8 VARCHAR2(240),
      MULTI_UNIT9 VARCHAR2(240),
      MULTI_UNIT10 VARCHAR2(240),
      MULTI_UNIT11 VARCHAR2(240),
      MULTI_UNIT12 VARCHAR2(240),
      MULTI_UNIT13 VARCHAR2(240),
      MULTI_UNIT14 VARCHAR2(240),
      MULTI_UNIT15 VARCHAR2(240),
      MULTI_UNIT16 VARCHAR2(240),
      MULTI_UNIT_RTL1 NUMBER,
      MULTI_UNIT_RTL2 NUMBER,
      MULTI_UNIT_RTL3 NUMBER,
      MULTI_UNIT_RTL4 NUMBER,
      MULTI_UNIT_RTL5 NUMBER,
      MULTI_UNIT_RTL6 NUMBER,
      MULTI_UNIT_RTL7 NUMBER,
      MULTI_UNIT_RTL8 NUMBER,
      MULTI_UNIT_RTL9 NUMBER,
      MULTI_UNIT_RTL10 NUMBER,
      MULTI_UNIT_RTL11 NUMBER,
      MULTI_UNIT_RTL12 NUMBER,
      MULTI_UNIT_RTL13 NUMBER,
      MULTI_UNIT_RTL14 NUMBER,
      MULTI_UNIT_RTL15 NUMBER,
      MULTI_UNIT_RTL16 NUMBER,
      PRODUCT_PRECEDENCE NUMBER,
      PUBLISHSTATUSCODE VARCHAR2(30),
      CREATION_DATE DATE,
      SOURCEAPPLID VARCHAR2(30),
      PRICE_BY_FORMULA_ID NUMBER
);
/
show errors
-- Declare package containing conversion functions between SQL and PL/SQL types
CREATE OR REPLACE PACKAGE BPEL_PLPRICELISTPROCESS AS
	-- Declare the conversion functions the PL/SQL type XX_QP_PRICELIST_PKG.OD_PRICE_LIST_REC_TYPE
	FUNCTION PL_TO_SQL0(aPlsqlItem XX_QP_PRICELIST_PKG.OD_PRICE_LIST_REC_TYPE)
 	RETURN XX_QP_PRICELIST_PKG_OD_PRICE_;
	FUNCTION SQL_TO_PL0(aSqlItem XX_QP_PRICELIST_PKG_OD_PRICE_)
	RETURN XX_QP_PRICELIST_PKG.OD_PRICE_LIST_REC_TYPE;
   PROCEDURE XX_QP_PRICELIST_PKG$CREATE_PR (P_OD_PRICE_LIST_REC_TYPE XX_QP_PRICELIST_PKG_OD_PRICE_,X_MESSAGE_DATA OUT VARCHAR2);
END BPEL_PLPRICELISTPROCESS;
/
show errors
CREATE OR REPLACE PACKAGE BODY BPEL_PLPRICELISTPROCESS IS
	FUNCTION PL_TO_SQL0(aPlsqlItem XX_QP_PRICELIST_PKG.OD_PRICE_LIST_REC_TYPE)
 	RETURN XX_QP_PRICELIST_PKG_OD_PRICE_ IS 
	aSqlItem XX_QP_PRICELIST_PKG_OD_PRICE_; 
	BEGIN 
		-- initialize the object
		aSqlItem := XX_QP_PRICELIST_PKG_OD_PRICE_(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
		aSqlItem.OPERATINGUNIT := aPlsqlItem.OPERATINGUNIT;
		aSqlItem.OPERATIONH := aPlsqlItem.OPERATIONH;
		aSqlItem.OPERATIONL := aPlsqlItem.OPERATIONL;
		aSqlItem.OPERATIONA := aPlsqlItem.OPERATIONA;
		aSqlItem.NAME := aPlsqlItem.NAME;
		aSqlItem.DESCRIPTION := aPlsqlItem.DESCRIPTION;
		aSqlItem.CURRENCY_CODE := aPlsqlItem.CURRENCY_CODE;
		aSqlItem.ROUNDING_FACTOR := aPlsqlItem.ROUNDING_FACTOR;
		aSqlItem.ACTIVE_FLAG := aPlsqlItem.ACTIVE_FLAG;
		aSqlItem.ATTRIBUTE6 := aPlsqlItem.ATTRIBUTE6;
		aSqlItem.ATTRIBUTE7 := aPlsqlItem.ATTRIBUTE7;
		aSqlItem.LANGUAGEH := aPlsqlItem.LANGUAGEH;
		aSqlItem.PRODUCT_ATTR_VALUE := aPlsqlItem.PRODUCT_ATTR_VALUE;
		aSqlItem.START_DATE_ACTIVEH := aPlsqlItem.START_DATE_ACTIVEH;
		aSqlItem.END_DATE_ACTIVEH := aPlsqlItem.END_DATE_ACTIVEH;
		aSqlItem.START_DATE_ACTIVEL := aPlsqlItem.START_DATE_ACTIVEL;
		aSqlItem.END_DATE_ACTIVEL := aPlsqlItem.END_DATE_ACTIVEL;
		aSqlItem.OPERAND := aPlsqlItem.OPERAND;
		aSqlItem.PRODUCT_UOM_CODE := aPlsqlItem.PRODUCT_UOM_CODE;
		aSqlItem.MULTI_UNIT1 := aPlsqlItem.MULTI_UNIT1;
		aSqlItem.MULTI_UNIT2 := aPlsqlItem.MULTI_UNIT2;
		aSqlItem.MULTI_UNIT3 := aPlsqlItem.MULTI_UNIT3;
		aSqlItem.MULTI_UNIT4 := aPlsqlItem.MULTI_UNIT4;
		aSqlItem.MULTI_UNIT5 := aPlsqlItem.MULTI_UNIT5;
		aSqlItem.MULTI_UNIT6 := aPlsqlItem.MULTI_UNIT6;
		aSqlItem.MULTI_UNIT7 := aPlsqlItem.MULTI_UNIT7;
		aSqlItem.MULTI_UNIT8 := aPlsqlItem.MULTI_UNIT8;
		aSqlItem.MULTI_UNIT9 := aPlsqlItem.MULTI_UNIT9;
		aSqlItem.MULTI_UNIT10 := aPlsqlItem.MULTI_UNIT10;
		aSqlItem.MULTI_UNIT11 := aPlsqlItem.MULTI_UNIT11;
		aSqlItem.MULTI_UNIT12 := aPlsqlItem.MULTI_UNIT12;
		aSqlItem.MULTI_UNIT13 := aPlsqlItem.MULTI_UNIT13;
		aSqlItem.MULTI_UNIT14 := aPlsqlItem.MULTI_UNIT14;
		aSqlItem.MULTI_UNIT15 := aPlsqlItem.MULTI_UNIT15;
		aSqlItem.MULTI_UNIT16 := aPlsqlItem.MULTI_UNIT16;
		aSqlItem.MULTI_UNIT_RTL1 := aPlsqlItem.MULTI_UNIT_RTL1;
		aSqlItem.MULTI_UNIT_RTL2 := aPlsqlItem.MULTI_UNIT_RTL2;
		aSqlItem.MULTI_UNIT_RTL3 := aPlsqlItem.MULTI_UNIT_RTL3;
		aSqlItem.MULTI_UNIT_RTL4 := aPlsqlItem.MULTI_UNIT_RTL4;
		aSqlItem.MULTI_UNIT_RTL5 := aPlsqlItem.MULTI_UNIT_RTL5;
		aSqlItem.MULTI_UNIT_RTL6 := aPlsqlItem.MULTI_UNIT_RTL6;
		aSqlItem.MULTI_UNIT_RTL7 := aPlsqlItem.MULTI_UNIT_RTL7;
		aSqlItem.MULTI_UNIT_RTL8 := aPlsqlItem.MULTI_UNIT_RTL8;
		aSqlItem.MULTI_UNIT_RTL9 := aPlsqlItem.MULTI_UNIT_RTL9;
		aSqlItem.MULTI_UNIT_RTL10 := aPlsqlItem.MULTI_UNIT_RTL10;
		aSqlItem.MULTI_UNIT_RTL11 := aPlsqlItem.MULTI_UNIT_RTL11;
		aSqlItem.MULTI_UNIT_RTL12 := aPlsqlItem.MULTI_UNIT_RTL12;
		aSqlItem.MULTI_UNIT_RTL13 := aPlsqlItem.MULTI_UNIT_RTL13;
		aSqlItem.MULTI_UNIT_RTL14 := aPlsqlItem.MULTI_UNIT_RTL14;
		aSqlItem.MULTI_UNIT_RTL15 := aPlsqlItem.MULTI_UNIT_RTL15;
		aSqlItem.MULTI_UNIT_RTL16 := aPlsqlItem.MULTI_UNIT_RTL16;
		aSqlItem.PRODUCT_PRECEDENCE := aPlsqlItem.PRODUCT_PRECEDENCE;
		aSqlItem.PUBLISHSTATUSCODE := aPlsqlItem.PUBLISHSTATUSCODE;
		aSqlItem.CREATION_DATE := aPlsqlItem.CREATION_DATE;
		aSqlItem.SOURCEAPPLID := aPlsqlItem.SOURCEAPPLID;
		aSqlItem.PRICE_BY_FORMULA_ID := aPlsqlItem.PRICE_BY_FORMULA_ID;
		RETURN aSqlItem;
	END PL_TO_SQL0;
	FUNCTION SQL_TO_PL0(aSqlItem XX_QP_PRICELIST_PKG_OD_PRICE_) 
	RETURN XX_QP_PRICELIST_PKG.OD_PRICE_LIST_REC_TYPE IS 
	aPlsqlItem XX_QP_PRICELIST_PKG.OD_PRICE_LIST_REC_TYPE; 
	BEGIN 
		aPlsqlItem.OPERATINGUNIT := aSqlItem.OPERATINGUNIT;
		aPlsqlItem.OPERATIONH := aSqlItem.OPERATIONH;
		aPlsqlItem.OPERATIONL := aSqlItem.OPERATIONL;
		aPlsqlItem.OPERATIONA := aSqlItem.OPERATIONA;
		aPlsqlItem.NAME := aSqlItem.NAME;
		aPlsqlItem.DESCRIPTION := aSqlItem.DESCRIPTION;
		aPlsqlItem.CURRENCY_CODE := aSqlItem.CURRENCY_CODE;
		aPlsqlItem.ROUNDING_FACTOR := aSqlItem.ROUNDING_FACTOR;
		aPlsqlItem.ACTIVE_FLAG := aSqlItem.ACTIVE_FLAG;
		aPlsqlItem.ATTRIBUTE6 := aSqlItem.ATTRIBUTE6;
		aPlsqlItem.ATTRIBUTE7 := aSqlItem.ATTRIBUTE7;
		aPlsqlItem.LANGUAGEH := aSqlItem.LANGUAGEH;
		aPlsqlItem.PRODUCT_ATTR_VALUE := aSqlItem.PRODUCT_ATTR_VALUE;
		aPlsqlItem.START_DATE_ACTIVEH := aSqlItem.START_DATE_ACTIVEH;
		aPlsqlItem.END_DATE_ACTIVEH := aSqlItem.END_DATE_ACTIVEH;
		aPlsqlItem.START_DATE_ACTIVEL := aSqlItem.START_DATE_ACTIVEL;
		aPlsqlItem.END_DATE_ACTIVEL := aSqlItem.END_DATE_ACTIVEL;
		aPlsqlItem.OPERAND := aSqlItem.OPERAND;
		aPlsqlItem.PRODUCT_UOM_CODE := aSqlItem.PRODUCT_UOM_CODE;
		aPlsqlItem.MULTI_UNIT1 := aSqlItem.MULTI_UNIT1;
		aPlsqlItem.MULTI_UNIT2 := aSqlItem.MULTI_UNIT2;
		aPlsqlItem.MULTI_UNIT3 := aSqlItem.MULTI_UNIT3;
		aPlsqlItem.MULTI_UNIT4 := aSqlItem.MULTI_UNIT4;
		aPlsqlItem.MULTI_UNIT5 := aSqlItem.MULTI_UNIT5;
		aPlsqlItem.MULTI_UNIT6 := aSqlItem.MULTI_UNIT6;
		aPlsqlItem.MULTI_UNIT7 := aSqlItem.MULTI_UNIT7;
		aPlsqlItem.MULTI_UNIT8 := aSqlItem.MULTI_UNIT8;
		aPlsqlItem.MULTI_UNIT9 := aSqlItem.MULTI_UNIT9;
		aPlsqlItem.MULTI_UNIT10 := aSqlItem.MULTI_UNIT10;
		aPlsqlItem.MULTI_UNIT11 := aSqlItem.MULTI_UNIT11;
		aPlsqlItem.MULTI_UNIT12 := aSqlItem.MULTI_UNIT12;
		aPlsqlItem.MULTI_UNIT13 := aSqlItem.MULTI_UNIT13;
		aPlsqlItem.MULTI_UNIT14 := aSqlItem.MULTI_UNIT14;
		aPlsqlItem.MULTI_UNIT15 := aSqlItem.MULTI_UNIT15;
		aPlsqlItem.MULTI_UNIT16 := aSqlItem.MULTI_UNIT16;
		aPlsqlItem.MULTI_UNIT_RTL1 := aSqlItem.MULTI_UNIT_RTL1;
		aPlsqlItem.MULTI_UNIT_RTL2 := aSqlItem.MULTI_UNIT_RTL2;
		aPlsqlItem.MULTI_UNIT_RTL3 := aSqlItem.MULTI_UNIT_RTL3;
		aPlsqlItem.MULTI_UNIT_RTL4 := aSqlItem.MULTI_UNIT_RTL4;
		aPlsqlItem.MULTI_UNIT_RTL5 := aSqlItem.MULTI_UNIT_RTL5;
		aPlsqlItem.MULTI_UNIT_RTL6 := aSqlItem.MULTI_UNIT_RTL6;
		aPlsqlItem.MULTI_UNIT_RTL7 := aSqlItem.MULTI_UNIT_RTL7;
		aPlsqlItem.MULTI_UNIT_RTL8 := aSqlItem.MULTI_UNIT_RTL8;
		aPlsqlItem.MULTI_UNIT_RTL9 := aSqlItem.MULTI_UNIT_RTL9;
		aPlsqlItem.MULTI_UNIT_RTL10 := aSqlItem.MULTI_UNIT_RTL10;
		aPlsqlItem.MULTI_UNIT_RTL11 := aSqlItem.MULTI_UNIT_RTL11;
		aPlsqlItem.MULTI_UNIT_RTL12 := aSqlItem.MULTI_UNIT_RTL12;
		aPlsqlItem.MULTI_UNIT_RTL13 := aSqlItem.MULTI_UNIT_RTL13;
		aPlsqlItem.MULTI_UNIT_RTL14 := aSqlItem.MULTI_UNIT_RTL14;
		aPlsqlItem.MULTI_UNIT_RTL15 := aSqlItem.MULTI_UNIT_RTL15;
		aPlsqlItem.MULTI_UNIT_RTL16 := aSqlItem.MULTI_UNIT_RTL16;
		aPlsqlItem.PRODUCT_PRECEDENCE := aSqlItem.PRODUCT_PRECEDENCE;
		aPlsqlItem.PUBLISHSTATUSCODE := aSqlItem.PUBLISHSTATUSCODE;
		aPlsqlItem.CREATION_DATE := aSqlItem.CREATION_DATE;
		aPlsqlItem.SOURCEAPPLID := aSqlItem.SOURCEAPPLID;
		aPlsqlItem.PRICE_BY_FORMULA_ID := aSqlItem.PRICE_BY_FORMULA_ID;
		RETURN aPlsqlItem;
	END SQL_TO_PL0;

   PROCEDURE XX_QP_PRICELIST_PKG$CREATE_PR (P_OD_PRICE_LIST_REC_TYPE XX_QP_PRICELIST_PKG_OD_PRICE_,X_MESSAGE_DATA OUT VARCHAR2) IS
      P_OD_PRICE_LIST_REC_TYPE_ APPS.XX_QP_PRICELIST_PKG.OD_PRICE_LIST_REC_TYPE;
   BEGIN
      P_OD_PRICE_LIST_REC_TYPE_ := BPEL_PLPRICELISTPROCESS.SQL_TO_PL0(P_OD_PRICE_LIST_REC_TYPE);
      APPS.XX_QP_PRICELIST_PKG.CREATE_PRICELIST_MAIN(P_OD_PRICE_LIST_REC_TYPE_,X_MESSAGE_DATA);
   END XX_QP_PRICELIST_PKG$CREATE_PR;

END BPEL_PLPRICELISTPROCESS;
/
show errors
exit
