package ServicePeopleSoftTableInsertUpdate;

import java.util.Date;

public class XxApPsVendorLoc {

    private String vndrLoc;
    private Date effdt;
    private String effStatus;
    private String currencyCd;
    private String curRtType;
    private String freightTerms;
    private String shipTypeId;
    private String dispMethod;
    private String pymntTermsCd;
    private String matchCntrlId;
    private String matchOpt;
    private String ersAction;
    private String ersFlag;
    private String vchrApprvlFlg;
    private String busprocname;
    private String apprRuleSet;
    private String vatDclrtnPoint;
    private String vatCalcType;
    private String vatTxnTypeCd;
    private String vatTolFlg;
    private Double vatTolPct;
    private Double vatTolAmt;
    private String vatTolCurCd;
    private String vatTolRtType;
    private String vatUseId;
    private String buyerId;
    private String remitSetid;
    private String remitVendor;
    private String remitLoc;
    private Double remitAddrSeqNum;
    private Double addrSeqNumOrdr;
    private String priceSetid;
    private String priceVendor;
    private String priceLoc;
    private String returnVendor;
    private Double retAddrSeqNum;
    private String dstCntrlId;
    private String preferredLanguage;
    private String rfqDispMthd;
    private String primaryVendor;
    private Double primAddrSeqNum;
    private String shiptoId;
    private String sutBaseId;
    private Double saletxTolAmt;
    private String saletxTolCurCd;
    private Double saletxTolPct;
    private String saletxTolRtType;
    private String saletxCdErs;
    private String salesUseTxFlg;
    private String autoAsnFlg;
    private String saletxTolFlg;
    private String shipLocFlg;
    private String wthdCd;
    private String docType;
    private String docTypeFlg;
    private String rtvDispatchMeth;
    private String rtvNotifyMeth;
    private String rtvDebitOpt;
    private String vndrSbiFlg;
    private String sbiApprovalFlg;
    private String account;
    private String altacct;
    private String operatingUnit;
    private String deptid;
    private String product;
    private String projectId;
    private String affiliate;
    private String consignedFlag;
    private String vchrConsignOpt;
    private String ersInvDtOpt;
    private Double bankAcctSeqNbr;
    private String acctTemplFlg;
    private String payTrmBseDtDft;
    private String recvOnlyMtchFlg;
    private String vchrMtchAdjDflt;
    private String ersInvDtDflt;
    private String ersTaxTypeDflt;
    private String ersTaxCdOpt;
    private Long lastSbiNum;
    private String sbiDocDflt;
    private String vchrTaxAdjDft;
    private String rtvVchrAdjDflt;
    private String vatSuspensionFlg;
    private String vatRoundRule;
    private Long comments2000;


}
