SET SERVEROUTPUT ON;

DECLARE

ln_count NUMBER := 0;

BEGIN

INSERT INTO xxtps.xxtps_template_file_uploads
(
SELECT
55, NULL, -1, sysdate, -1, sysdate, 'CREATE_FINHIER_RELS', 'CREATE OD_FIN_HIER RELATIONSHIPS','Template to create OD_FIN_HIER relationships',
q'{'PARENT_PARTY_NUMBER','RELATIONSHIP_TYPE','CHILD_PARTY_NUMBER','START_DATE','END_DATE'}',
'XX_FIN_RELS_CREDIT_UPLOAD_PKG.CREATE_REL',
q'{'PARENT_PARTY_NUMBER','RELATIONSHIP_TYPE','CHILD_PARTY_NUMBER','START_DATE','END_DATE','STATUS','NOTES'}',
q'{'PARENT_PARTY_NUMBER','RELATIONSHIP_TYPE','CHILD_PARTY_NUMBER','START_DATE','END_DATE','STATUS','ERROR'}',
to_clob(q'{PARENT_PARTY_NUMBER *,RELATIONSHIP_TYPE *,CHILD_PARTY_NUMBER *,START_DATE(MM/DD/YYYY),END_DATE(MM/DD/YYYY)}'),
to_clob(q'{The File should contain the following columns in the following order -  
-PARENT_PARTY_NUMBER * 
-RELATIONSHIP_TYPE * 
-CHILD_PARTY_NUMBER * 
-START_DATE (MM/DD/YYYY)
-END_DATE (MM/DD/YYYY)}'),
NULL,NULL,
NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL
FROM DUAL
);

  IF SQL%ROWCOUNT = 1
  THEN
    ln_count := ln_count + 1;
  END IF;


INSERT INTO xxtps.xxtps_template_file_uploads
(
SELECT
56, NULL, -1, sysdate, -1, sysdate, 'REMOVE_FINHIER_RELS', 'REMOVE OD_FIN_HIER RELATIONSHIPS','Template to end date OD_FIN_HIER relationships',
q'{'PARENT_PARTY_NUMBER','RELATIONSHIP_TYPE','CHILD_PARTY_NUMBER','END_DATE'}',
'XX_FIN_RELS_CREDIT_UPLOAD_PKG.REMOVE_REL',
q'{'PARENT_PARTY_NUMBER','RELATIONSHIP_TYPE','CHILD_PARTY_NUMBER','END_DATE','STATUS','NOTES'}',
q'{'PARENT_PARTY_NUMBER','RELATIONSHIP_TYPE','CHILD_PARTY_NUMBER','END_DATE','STATUS','ERROR'}',
to_clob(q'{PARENT_PARTY_NUMBER *,RELATIONSHIP_TYPE *,CHILD_PARTY_NUMBER *,END_DATE(MM/DD/YYYY)}'),
to_clob(q'{The File should contain the following columns in the following order -  
-PARENT_PARTY_NUMBER * 
-RELATIONSHIP_TYPE * 
-CHILD_PARTY_NUMBER * 
-END_DATE (MM/DD/YYYY)}'),
NULL,NULL,
NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL
FROM DUAL
);


  IF SQL%ROWCOUNT = 1
  THEN
    ln_count := ln_count + 1;
  END IF;


INSERT INTO xxtps.xxtps_template_file_uploads
(
SELECT
57, NULL, -1, sysdate, -1, sysdate, 'CREDIT_LIMIT', 'UPLOAD CUSTOMER CREDIT LIMIT','Template to upload customer credit limit',
q'{'ACCOUNT_NUMBER','CREDIT_LIMIT','CURRENCY_CODE'}',
'XX_FIN_RELS_CREDIT_UPLOAD_PKG.CREDIT_UPDATE',
q'{'ACCOUNT_NUMBER','CREDIT_LIMIT','CURRENCY_CODE','STATUS','NOTES'}',
q'{'ACCOUNT_NUMBER','CREDIT_LIMIT','CURRENCY_CODE','STATUS','ERROR'}',
to_clob(q'{ACCOUNT_NUMBER *,CREDIT_LIMIT *,CURRENCY_CODE }'),
to_clob(q'{The File should contain the following columns in the following order -  
-ACCOUNT_NUMBER * 
-CREDIT_LIMIT * 
-CURRENCY_CODE 
Note : If CURRENCY_CODE is blank, USD would be used by default.
}'),
NULL,NULL,
NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL,
NULL,NULL,NULL,NULL,NULL
FROM DUAL
);

  IF SQL%ROWCOUNT = 1
  THEN
    ln_count := ln_count + 1;
  END IF;


dbms_output.put_line ('Records processed :'||ln_count);


COMMIT;

END;