DECLARE

v_translate_id NUMBER;

BEGIN

  BEGIN
    SELECT translate_id
      INTO v_translate_id
      FROM XX_FIN_TRANSLATEDEFINITION
     WHERE translation_name='XXFA_PWC_DEPRN'
       AND enabled_flag='Y';
  EXCEPTION
    WHEN others THEN
      v_translate_id:=NULL;
      dbms_output.put_line('Translation XXFA_PWC_DEPRN not set up');
  END;

  IF v_translate_id IS NOT NULL THEN

     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '150%','1','STL','12','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '150%','5','150DB','60','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '150%','15','150DB','180','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '150%','15','AMT HY','180','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '150%','15','AMT200HY-30B','180','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '150%','20','150DB','240','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '150%','40','MACRS STL HY','480','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','1','STL','12','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','3','200DB','36','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','3','MACRS STL50B','36','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','5','200DB','60','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','5','MACRS HY','60','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','5','MACRS 50B HY','60','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','7','200DB','84','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','7','MACRS 50B HY','84','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','15','MACRS HY','180','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','15','MACRS 50B HY','180','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','30','200DB','360','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','39','MACRS STL HY','468','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, '200%','39','MACRS STL50B','468','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','1','STL','12','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','3','MACRS STL HY','36','Current Month',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','3','STL 50B','36','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','5','MACRS STL HY','60','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','5','MACRS STL50B','60','Mid-Month',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','7','MACRS STL HY','84','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','7','MACRS STL MQ','84','Mid-Month',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','15','MACRS STL HY','180','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','15','STL 100B HY','180','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','15','MACRS STL50B','180','Mid-Month',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','28','MACRS STL HY','336','Mid-Month',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','30','STL','360','Mid-Month',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','31.5','MACRS STL MM','378','Mid-Month',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','35','ACRS RSTLMM','420','Mid-Month',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','39','AMT HY','468','Half-Year',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','39','AMT MQ','468','Mid-Month',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','39','STL','468','Mid-Month',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','40','STL','480','Mid-Month',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','50','AMT HY','600','Mid-Month',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);
     insert into xx_fin_translatevalues (translate_id,source_value1,source_value2,target_value1,target_value2,target_value3,creation_date,created_by,last_update_date,last_updated_by,last_update_login,start_date_active,enabled_Flag,translate_value_id)VALUES(v_translate_id, 'SL','60','200DB','720','Mid-Month',sysdate,-1,sysdate,-1,-1,sysdate,'Y',XX_FIN_TRANSLATEVALUES_S.nextval);

  END IF;  
  COMMIT;
EXCEPTION
  WHEN others THEN
    dbms_output.put_line('When others :'||SQLERRM);
END;

