<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="SearchSchool"
     targetNamespace="http://oracle.com/sca/soapservice/BTS/SearchSchoolPOSReqABCSImpl/SearchSchool"
     xmlns:inp2="http://xmlns.officedepot.com/BTS/SearchSchoolIDPOSReqABCSImpl/SearchSchoolIDPOSResponse/V1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:inp1="http://xmlns.officedepot.com/BTS/SearchSchoolIDPOSReqABCSImpl/SearchSchoolIDPOSFault/V1"
     xmlns:tns="http://oracle.com/sca/soapservice/BTS/SearchSchoolPOSReqABCSImpl/SearchSchool"
     xmlns:inp3="http://xmlns.oracle.com/BTS/SearchSchoolIDPOSReqABCSImpl/SearchSchoolIDPOSFault/V1"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.officedepot.com/BTS/SearchSchoolIDPOSReqABCSImpl/SearchSchoolIDPOSFault/V1"
                 schemaLocation="xsd/SearchSchoolIDPOSRequest.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.officedepot.com/BTS/SearchSchoolIDPOSReqABCSImpl/SearchSchoolIDPOSResponse/V1"
                 schemaLocation="xsd/SearchSchoolIDPOSResponse.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.oracle.com/BTS/SearchSchoolIDPOSReqABCSImpl/SearchSchoolIDPOSFault/V1"
                 schemaLocation="xsd/SearchSchoolIDPOSFaultMessage.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="SearchRequest" element="inp1:Request"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="SearchResponse" element="inp2:OutputParameters"/>
    </wsdl:message>
    <wsdl:message name="faultMessage">
        <wsdl:part name="SearchFault" element="inp3:SearchSchoolIDPOSFaultMessage"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
            <wsdl:fault name="executefault" message="tns:faultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
