DROP TYPE XX_OM_POS_SHIP_CONF_PKG_XX_OM FORCE; 
show errors
DROP TYPE XX_OM_POS_SHIP_CONF_PKG_XX_O4 FORCE; 
show errors
DROP TYPE XX_OM_POS_SHIP_CONF_PKG_XX_O1 FORCE; 
show errors
DROP TYPE XX_OM_POS_SHIP_CONF_PKG_XX_O5 FORCE; 
show errors
DROP TYPE XX_OM_POS_SHIP_CONF_PKG_XX_O2 FORCE; 
show errors
DROP TYPE XX_OM_POS_SHIP_CONF_PKG_XX_O6 FORCE; 
show errors
DROP TYPE XX_OM_POS_SHIP_CONF_PKG_XX_O3 FORCE; 
show errors
DROP PACKAGE XX_BPEL_SVCJDAPOSREAD;
exit
