DROP TYPE XX_OM_CARTONIZATION_WMOS_PKG5 FORCE; 
show errors
DROP TYPE XXOMCARTONIZATIONWMOSPKG3_XX_ FORCE; 
show errors
DROP TYPE XX_OM_CARTONIZATION_WMOS_PKG3 FORCE; 
show errors
DROP TYPE XXOMCARTONIZATIONWMOSPKG1_XX_ FORCE; 
show errors
DROP TYPE XX_OM_CARTONIZATION_WMOS_PKG1 FORCE; 
show errors
DROP TYPE XX_OM_CARTONIZATION_WMOS_PKG_ FORCE; 
show errors
DROP PACKAGE BPEL_CARTONIZATION;
exit
