package od.oracle.apps.xxmer.schema.wfh.server;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
import oracle.jbo.domain.Number;

//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class LeafPlannerVVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public LeafPlannerVVOImpl()
  {
  }
  public void initQuery(Number plannerId) 
  {
    setWhereClauseParams(null);
    setWhereClauseParam(0, plannerId);
    executeQuery();
  }
}