package od.oracle.apps.xxmer.schema.wfh.server;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class ManagerExistenceVVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public ManagerExistenceVVOImpl()
  {
  }
  public void initQuery(Number managerId) 
  {
    setWhereClauseParams(null);
    setWhereClauseParam(0, managerId);
    executeQuery();
  }
}