package od.oracle.apps.xxmer.schema.server;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class AllocationQuantityVVOImpl extends OAViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public AllocationQuantityVVOImpl()
  {
  }

  public void initQuery(Number poHeaderId,Number poLineId, Number lineLocationId, Number allocLineId)
  {
    setWhereClauseParams(null);
    setWhereClauseParam(0,poHeaderId);
    setWhereClauseParam(1,poLineId);
    setWhereClauseParam(2,lineLocationId);
    setWhereClauseParam(3,allocLineId);
    
    executeQuery();
  }
}