SET SHOW         OFF
SET VERIFY       OFF
SET ECHO         OFF
SET TAB          OFF
SET FEEDBACK     ON

INSERT INTO BPELEH.XX_BPEL_ESP_SETUP (PROCESS_DOMAIN,PROCESS_NAME,FILE_PATTERN,JOB_NAME,ESP_APPLICATION,ESP_VERB,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY) VALUES ('financebatch','SynchEBStoMVSData','OD_GL_JRNL_DETAIL_IRS_MVSFTP','NOTDEFIN.EDUMMYJB','NOTDEFIN','RELEASE', sysdate,'BPELEH',sysdate,'BPELEH');
INSERT INTO BPELEH.XX_BPEL_ESP_SETUP (PROCESS_DOMAIN,PROCESS_NAME,FILE_PATTERN,JOB_NAME,ESP_APPLICATION,ESP_VERB,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY) VALUES ('financebatch','SynchEBStoMVSData','OD_GL_BALC_IRS_MVSFTP','NOTDEFIN.EDUMMYJB','NOTDEFIN','RELEASE', sysdate,'BPELEH',sysdate,'BPELEH');
INSERT INTO BPELEH.XX_BPEL_ESP_SETUP (PROCESS_DOMAIN,PROCESS_NAME,FILE_PATTERN,JOB_NAME,ESP_APPLICATION,ESP_VERB,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY) VALUES ('financebatch','SynchEBStoMVSData','OD_GL_COA_IRS_MVSFTP','NOTDEFIN.EDUMMYJB','NOTDEFIN','RELEASE', sysdate,'BPELEH',sysdate,'BPELEH');

COMMIT;
/