<definitions
     name="ProcessNowDocsReceive"
     targetNamespace="http://xmlns.oracle.com/ProcessNowDocsReceive"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://www.openapplications.org/oagis/9"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:ns2="http://schemas.oracle.com/bpel/extension"
     xmlns:client="http://xmlns.oracle.com/ProcessNowDocsReceive"
    >
    <import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/ProcessNowDocsReceive" schemaLocation="ProcessNowDocsReceive.xsd"/>
        </schema>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.openapplications.org/oagis/9" schemaLocation="CreateOrder.xsd"/>
        </schema>
    </types>
    <message name="ProcessNowDocsReceiveRequestMessage">
        <part name="payload" element="ns1:CreateSalesOrder"/>
    </message>
    <message name="ProcessNowDocsReceiveResponseMessage">
        <part name="payload" element="client:ProcessNowDocsReceiveProcessResponse"/>
    </message>
    <portType name="ProcessNowDocsReceive">
        <operation name="process">
            <input message="client:ProcessNowDocsReceiveRequestMessage"/>
            <output message="client:ProcessNowDocsReceiveResponseMessage"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="ProcessNowDocsReceive">
        <plnk:role name="ProcessNowDocsReceiveProvider">
            <plnk:portType name="client:ProcessNowDocsReceive"/>
        </plnk:role>
    </plnk:partnerLinkType>
</definitions>
