<?xml version="1.0" encoding="UTF-8"?>
<definitions 
    name="AJB999TableInsert"
    targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AJB999TableInsert/"
    xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AJB999TableInsert/"
    xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
    xmlns:pc="http://xmlns.oracle.com/pcbpel/"
    xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/AJB999TableInsert"
    xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/db/"
    xmlns="http://schemas.xmlsoap.org/wsdl/">

    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/" location="DBAdapterOutboundHeader.wsdl"/>

    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/AJB999TableInsert"
                schemaLocation="AJB999TableInsert_table.xsd"/>
        </schema>
    </types>

    <message name="XxCeAjb999Collection_msg">
        <part name="XxCeAjb999Collection" element="top:XxCeAjb999Collection"/>
    </message>


    <portType name="AJB999TableInsert_ptt">
        <operation name="insert">
            <input message="tns:XxCeAjb999Collection_msg"/>
        </operation>
    </portType>

    <binding name="AJB999TableInsert_binding" type="tns:AJB999TableInsert_ptt">
        <jca:binding />
        <operation name="insert">
            <jca:operation
                InteractionSpec="oracle.tip.adapter.db.DBWriteInteractionSpec"

                DescriptorName="AJB999TableInsert.XxCeAjb999"
                DmlType="insert"
                DetectOmissions="true"
                OptimizeMerge="true"
                MappingsMetaDataURL="AJB999TableInsert_toplink_mappings.xml" />
            <input>
                <jca:header message="hdr:OutboundHeader_msg" part="outboundHeader"/>
            </input>
        </operation>
    </binding>

    <!-- Your runtime connection is declared in
        J2EE_HOME/application-deployments/default/DbAdapter/oc4j-ra.xml
        These 'mcf' properties here are from your design time connection and 
        save you from having to edit that file and restart the application server
        if eis/db/EBSApps is missing.
        These 'mcf' properties are safe to remove.
    -->
    <service name="AJB999TableInsert">
        <port name="AJB999TableInsert_pt" binding="tns:AJB999TableInsert_binding">
            <jca:address location="eis/db/EBSAppsFin"
                UIConnectionName="EIS_APPS_EBS_APPS_DBConn"
                ManagedConnectionFactory="oracle.tip.adapter.db.DBManagedConnectionFactory"
            />
        </port>
    </service>

    <plt:partnerLinkType name="AJB999TableInsert_plt" >
        <plt:role name="AJB999TableInsert_role" >
            <plt:portType name="tns:AJB999TableInsert_ptt" />
        </plt:role>
    </plt:partnerLinkType>

</definitions>
