package od.oracle.apps.xxom.xxomCustui.server;
import oracle.apps.fnd.framework.server.OAEntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.AttributeList;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class xxomOrderLinesAttEOImpl extends OAEntityImpl 
{
  protected static final int LINEID = 0;
  protected static final int LICENCEADDRESS = 1;
  protected static final int VENDORCONFIGID = 2;
  protected static final int FULFILLMENTTYPE = 3;
  protected static final int LINETYPE = 4;
  protected static final int LINEMODIFIER = 5;
  protected static final int RELEASENUM = 6;
  protected static final int COSTCENTERDEPT = 7;
  protected static final int DESKTOPDELADDR = 8;
  protected static final int VENDORSITEID = 9;
  protected static final int POSTRXNUM = 10;
  protected static final int ONETIMEDEAL = 11;
  protected static final int TRANSLINESTATUS = 12;
  protected static final int CUSTPRICE = 13;
  protected static final int CUSTUOM = 14;
  protected static final int CUSTCOMMENTS = 15;
  protected static final int PIPCAMPAIGNID = 16;
  protected static final int EXTTOPMODELLINEID = 17;
  protected static final int EXTLINKTOLINEID = 18;
  protected static final int CONFIGCODE = 19;
  protected static final int GIFTMESSAGE = 20;
  protected static final int GIFTEMAIL = 21;
  protected static final int RETURNRGANUMBER = 22;
  protected static final int DELIVERYDATEFROM = 23;
  protected static final int DELIVERYDATETO = 24;
  protected static final int WHOLESALERFACCD = 25;
  protected static final int WHOLESALERACCTNUM = 26;
  protected static final int RETURNACTCATCODE = 27;
  protected static final int PODELDETAILS = 28;
  protected static final int RETREFHEADERID = 29;
  protected static final int RETREFLINEID = 30;
  protected static final int SHIPTOFLAG = 31;
  protected static final int ITEMNOTE = 32;
  protected static final int SPECIALDESC = 33;
  protected static final int NONCDLINETYPE = 34;
  protected static final int SUPPLIERTYPE = 35;
  protected static final int VENDORPRODUCTCODE = 36;
  protected static final int CONTRACTDETAILS = 37;
  protected static final int RETORIGORDERNUM = 38;
  protected static final int RETORIGORDERDATE = 39;
  protected static final int LINECOMMENTS = 40;
  protected static final int BACKORDEREDQTY = 41;
  protected static final int TAXABLEFLAG = 42;
  protected static final int WACAPARENTID = 43;
  protected static final int RETORIGORDERLINENUM = 44;
  protected static final int SKUDEPT = 45;
  protected static final int ITEMSOURCE = 46;
  protected static final int AVERAGECOST = 47;
  protected static final int CANADAPSTTAX = 48;
  protected static final int POCOST = 49;
  protected static final int RESOURCINGFLAG = 50;
  protected static final int WACASTATUS = 51;
  protected static final int CUSTITEMNUMBER = 52;
  protected static final int PODDATE = 53;
  protected static final int RETURNAUTHID = 54;
  protected static final int RETURNCODE = 55;
  protected static final int SKULISTPRICE = 56;
  protected static final int WACAITEMCTRNUM = 57;
  protected static final int NEWSCHEDULESHIPDATE = 58;
  protected static final int NEWSCHEDULEARRDATE = 59;
  protected static final int TAYLORUNITPRICE = 60;
  protected static final int TAYLORUNITCOST = 61;
  protected static final int XDOCKINVORGID = 62;
  protected static final int PAYMENTSUBTYPECODIND = 63;
  protected static final int DELTOPOSTOFFICEIND = 64;
  protected static final int WHOLESALERITEM = 65;
  protected static final int CUSTCOMMPREF = 66;
  protected static final int CUSTPREFEMAIL = 67;
  protected static final int CUSTPREFFAX = 68;
  protected static final int CUSTPREFPHONE = 69;
  protected static final int CUSTPREFPHEXTN = 70;
  protected static final int FREIGHTLINEID = 71;
  protected static final int FREIGHTPRIMARYLINEID = 72;
  protected static final int CREATIONDATE = 73;
  protected static final int CREATEDBY = 74;
  protected static final int LASTUPDATEDATE = 75;
  protected static final int LASTUPDATEDBY = 76;
  protected static final int LASTUPDATELOGIN = 77;
  protected static final int GSAFLAG = 78;
  protected static final int CONSIGNMENTBANKCODE = 79;
  protected static final int PRICECD = 80;
  protected static final int PRICECHANGEREASONCD = 81;
  protected static final int PRICEPREFIXCD = 82;
  protected static final int COMMISIONABLEIND = 83;
  protected static final int CUSTDEPTDESCRIPTION = 84;
  protected static final int UNITORIGSELLINGPRICE = 85;
  private static oracle.apps.fnd.framework.server.OAEntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public xxomOrderLinesAttEOImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (oracle.apps.fnd.framework.server.OAEntityDefImpl)EntityDefImpl.findDefObject("od.oracle.apps.xxom.xxomCustui.server.xxomOrderLinesAttEO");
    }
    return mDefinitionObject;
  }

  /**
   * 
   * Add attribute defaulting logic in this method.
   */
  public void create(AttributeList attributeList)
  {
    super.create(attributeList);
  }

  /**
   * 
   * Add entity remove logic in this method.
   */
  public void remove()
  {
    super.remove();
  }

  /**
   * 
   * Add Entity validation code in this method.
   */
  protected void validateEntity()
  {
    super.validateEntity();
  }

  /**
   * 
   * Gets the attribute value for LineId, using the alias name LineId
   */
  public Number getLineId()
  {
    return (Number)getAttributeInternal(LINEID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LineId
   */
  public void setLineId(Number value)
  {
    setAttributeInternal(LINEID, value);
  }

  /**
   * 
   * Gets the attribute value for LicenceAddress, using the alias name LicenceAddress
   */
  public String getLicenceAddress()
  {
    return (String)getAttributeInternal(LICENCEADDRESS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LicenceAddress
   */
  public void setLicenceAddress(String value)
  {
    setAttributeInternal(LICENCEADDRESS, value);
  }

  /**
   * 
   * Gets the attribute value for VendorConfigId, using the alias name VendorConfigId
   */
  public String getVendorConfigId()
  {
    return (String)getAttributeInternal(VENDORCONFIGID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for VendorConfigId
   */
  public void setVendorConfigId(String value)
  {
    setAttributeInternal(VENDORCONFIGID, value);
  }

  /**
   * 
   * Gets the attribute value for FulfillmentType, using the alias name FulfillmentType
   */
  public String getFulfillmentType()
  {
    return (String)getAttributeInternal(FULFILLMENTTYPE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for FulfillmentType
   */
  public void setFulfillmentType(String value)
  {
    setAttributeInternal(FULFILLMENTTYPE, value);
  }

  /**
   * 
   * Gets the attribute value for LineType, using the alias name LineType
   */
  public String getLineType()
  {
    return (String)getAttributeInternal(LINETYPE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LineType
   */
  public void setLineType(String value)
  {
    setAttributeInternal(LINETYPE, value);
  }

  /**
   * 
   * Gets the attribute value for LineModifier, using the alias name LineModifier
   */
  public String getLineModifier()
  {
    return (String)getAttributeInternal(LINEMODIFIER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LineModifier
   */
  public void setLineModifier(String value)
  {
    setAttributeInternal(LINEMODIFIER, value);
  }

  /**
   * 
   * Gets the attribute value for ReleaseNum, using the alias name ReleaseNum
   */
  public String getReleaseNum()
  {
    return (String)getAttributeInternal(RELEASENUM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ReleaseNum
   */
  public void setReleaseNum(String value)
  {
    setAttributeInternal(RELEASENUM, value);
  }

  /**
   * 
   * Gets the attribute value for CostCenterDept, using the alias name CostCenterDept
   */
  public String getCostCenterDept()
  {
    return (String)getAttributeInternal(COSTCENTERDEPT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CostCenterDept
   */
  public void setCostCenterDept(String value)
  {
    setAttributeInternal(COSTCENTERDEPT, value);
  }

  /**
   * 
   * Gets the attribute value for DesktopDelAddr, using the alias name DesktopDelAddr
   */
  public String getDesktopDelAddr()
  {
    return (String)getAttributeInternal(DESKTOPDELADDR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DesktopDelAddr
   */
  public void setDesktopDelAddr(String value)
  {
    setAttributeInternal(DESKTOPDELADDR, value);
  }

  /**
   * 
   * Gets the attribute value for VendorSiteId, using the alias name VendorSiteId
   */
  public Number getVendorSiteId()
  {
    return (Number)getAttributeInternal(VENDORSITEID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for VendorSiteId
   */
  public void setVendorSiteId(Number value)
  {
    setAttributeInternal(VENDORSITEID, value);
  }

  /**
   * 
   * Gets the attribute value for PosTrxNum, using the alias name PosTrxNum
   */
  public String getPosTrxNum()
  {
    return (String)getAttributeInternal(POSTRXNUM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PosTrxNum
   */
  public void setPosTrxNum(String value)
  {
    setAttributeInternal(POSTRXNUM, value);
  }

  /**
   * 
   * Gets the attribute value for OneTimeDeal, using the alias name OneTimeDeal
   */
  public String getOneTimeDeal()
  {
    return (String)getAttributeInternal(ONETIMEDEAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for OneTimeDeal
   */
  public void setOneTimeDeal(String value)
  {
    setAttributeInternal(ONETIMEDEAL, value);
  }

  /**
   * 
   * Gets the attribute value for TransLineStatus, using the alias name TransLineStatus
   */
  public String getTransLineStatus()
  {
    return (String)getAttributeInternal(TRANSLINESTATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for TransLineStatus
   */
  public void setTransLineStatus(String value)
  {
    setAttributeInternal(TRANSLINESTATUS, value);
  }

  /**
   * 
   * Gets the attribute value for CustPrice, using the alias name CustPrice
   */
  public Number getCustPrice()
  {
    return (Number)getAttributeInternal(CUSTPRICE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustPrice
   */
  public void setCustPrice(Number value)
  {
    setAttributeInternal(CUSTPRICE, value);
  }

  /**
   * 
   * Gets the attribute value for CustUom, using the alias name CustUom
   */
  public String getCustUom()
  {
    return (String)getAttributeInternal(CUSTUOM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustUom
   */
  public void setCustUom(String value)
  {
    setAttributeInternal(CUSTUOM, value);
  }

  /**
   * 
   * Gets the attribute value for CustComments, using the alias name CustComments
   */
  public String getCustComments()
  {
    return (String)getAttributeInternal(CUSTCOMMENTS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustComments
   */
  public void setCustComments(String value)
  {
    setAttributeInternal(CUSTCOMMENTS, value);
  }

  /**
   * 
   * Gets the attribute value for PipCampaignId, using the alias name PipCampaignId
   */
  public String getPipCampaignId()
  {
    return (String)getAttributeInternal(PIPCAMPAIGNID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PipCampaignId
   */
  public void setPipCampaignId(String value)
  {
    setAttributeInternal(PIPCAMPAIGNID, value);
  }

  /**
   * 
   * Gets the attribute value for ExtTopModelLineId, using the alias name ExtTopModelLineId
   */
  public Number getExtTopModelLineId()
  {
    return (Number)getAttributeInternal(EXTTOPMODELLINEID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ExtTopModelLineId
   */
  public void setExtTopModelLineId(Number value)
  {
    setAttributeInternal(EXTTOPMODELLINEID, value);
  }

  /**
   * 
   * Gets the attribute value for ExtLinkToLineId, using the alias name ExtLinkToLineId
   */
  public Number getExtLinkToLineId()
  {
    return (Number)getAttributeInternal(EXTLINKTOLINEID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ExtLinkToLineId
   */
  public void setExtLinkToLineId(Number value)
  {
    setAttributeInternal(EXTLINKTOLINEID, value);
  }

  /**
   * 
   * Gets the attribute value for ConfigCode, using the alias name ConfigCode
   */
  public String getConfigCode()
  {
    return (String)getAttributeInternal(CONFIGCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ConfigCode
   */
  public void setConfigCode(String value)
  {
    setAttributeInternal(CONFIGCODE, value);
  }

  /**
   * 
   * Gets the attribute value for GiftMessage, using the alias name GiftMessage
   */
  public String getGiftMessage()
  {
    return (String)getAttributeInternal(GIFTMESSAGE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for GiftMessage
   */
  public void setGiftMessage(String value)
  {
    setAttributeInternal(GIFTMESSAGE, value);
  }

  /**
   * 
   * Gets the attribute value for GiftEmail, using the alias name GiftEmail
   */
  public String getGiftEmail()
  {
    return (String)getAttributeInternal(GIFTEMAIL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for GiftEmail
   */
  public void setGiftEmail(String value)
  {
    setAttributeInternal(GIFTEMAIL, value);
  }

  /**
   * 
   * Gets the attribute value for ReturnRgaNumber, using the alias name ReturnRgaNumber
   */
  public String getReturnRgaNumber()
  {
    return (String)getAttributeInternal(RETURNRGANUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ReturnRgaNumber
   */
  public void setReturnRgaNumber(String value)
  {
    setAttributeInternal(RETURNRGANUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for DeliveryDateFrom, using the alias name DeliveryDateFrom
   */
  public Date getDeliveryDateFrom()
  {
    return (Date)getAttributeInternal(DELIVERYDATEFROM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DeliveryDateFrom
   */
  public void setDeliveryDateFrom(Date value)
  {
    setAttributeInternal(DELIVERYDATEFROM, value);
  }

  /**
   * 
   * Gets the attribute value for DeliveryDateTo, using the alias name DeliveryDateTo
   */
  public Date getDeliveryDateTo()
  {
    return (Date)getAttributeInternal(DELIVERYDATETO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DeliveryDateTo
   */
  public void setDeliveryDateTo(Date value)
  {
    setAttributeInternal(DELIVERYDATETO, value);
  }

  /**
   * 
   * Gets the attribute value for WholesalerFacCd, using the alias name WholesalerFacCd
   */
  public String getWholesalerFacCd()
  {
    return (String)getAttributeInternal(WHOLESALERFACCD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for WholesalerFacCd
   */
  public void setWholesalerFacCd(String value)
  {
    setAttributeInternal(WHOLESALERFACCD, value);
  }

  /**
   * 
   * Gets the attribute value for WholesalerAcctNum, using the alias name WholesalerAcctNum
   */
  public String getWholesalerAcctNum()
  {
    return (String)getAttributeInternal(WHOLESALERACCTNUM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for WholesalerAcctNum
   */
  public void setWholesalerAcctNum(String value)
  {
    setAttributeInternal(WHOLESALERACCTNUM, value);
  }

  /**
   * 
   * Gets the attribute value for ReturnActCatCode, using the alias name ReturnActCatCode
   */
  public String getReturnActCatCode()
  {
    return (String)getAttributeInternal(RETURNACTCATCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ReturnActCatCode
   */
  public void setReturnActCatCode(String value)
  {
    setAttributeInternal(RETURNACTCATCODE, value);
  }

  /**
   * 
   * Gets the attribute value for PoDelDetails, using the alias name PoDelDetails
   */
  public String getPoDelDetails()
  {
    return (String)getAttributeInternal(PODELDETAILS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PoDelDetails
   */
  public void setPoDelDetails(String value)
  {
    setAttributeInternal(PODELDETAILS, value);
  }

  /**
   * 
   * Gets the attribute value for RetRefHeaderId, using the alias name RetRefHeaderId
   */
  public Number getRetRefHeaderId()
  {
    return (Number)getAttributeInternal(RETREFHEADERID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RetRefHeaderId
   */
  public void setRetRefHeaderId(Number value)
  {
    setAttributeInternal(RETREFHEADERID, value);
  }

  /**
   * 
   * Gets the attribute value for RetRefLineId, using the alias name RetRefLineId
   */
  public Number getRetRefLineId()
  {
    return (Number)getAttributeInternal(RETREFLINEID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RetRefLineId
   */
  public void setRetRefLineId(Number value)
  {
    setAttributeInternal(RETREFLINEID, value);
  }

  /**
   * 
   * Gets the attribute value for ShipToFlag, using the alias name ShipToFlag
   */
  public String getShipToFlag()
  {
    return (String)getAttributeInternal(SHIPTOFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ShipToFlag
   */
  public void setShipToFlag(String value)
  {
    setAttributeInternal(SHIPTOFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for ItemNote, using the alias name ItemNote
   */
  public String getItemNote()
  {
    return (String)getAttributeInternal(ITEMNOTE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ItemNote
   */
  public void setItemNote(String value)
  {
    setAttributeInternal(ITEMNOTE, value);
  }

  /**
   * 
   * Gets the attribute value for SpecialDesc, using the alias name SpecialDesc
   */
  public String getSpecialDesc()
  {
    return (String)getAttributeInternal(SPECIALDESC);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SpecialDesc
   */
  public void setSpecialDesc(String value)
  {
    setAttributeInternal(SPECIALDESC, value);
  }

  /**
   * 
   * Gets the attribute value for NonCdLineType, using the alias name NonCdLineType
   */
  public String getNonCdLineType()
  {
    return (String)getAttributeInternal(NONCDLINETYPE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NonCdLineType
   */
  public void setNonCdLineType(String value)
  {
    setAttributeInternal(NONCDLINETYPE, value);
  }

  /**
   * 
   * Gets the attribute value for SupplierType, using the alias name SupplierType
   */
  public String getSupplierType()
  {
    return (String)getAttributeInternal(SUPPLIERTYPE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SupplierType
   */
  public void setSupplierType(String value)
  {
    setAttributeInternal(SUPPLIERTYPE, value);
  }

  /**
   * 
   * Gets the attribute value for VendorProductCode, using the alias name VendorProductCode
   */
  public String getVendorProductCode()
  {
    return (String)getAttributeInternal(VENDORPRODUCTCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for VendorProductCode
   */
  public void setVendorProductCode(String value)
  {
    setAttributeInternal(VENDORPRODUCTCODE, value);
  }

  /**
   * 
   * Gets the attribute value for ContractDetails, using the alias name ContractDetails
   */
  public String getContractDetails()
  {
    return (String)getAttributeInternal(CONTRACTDETAILS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ContractDetails
   */
  public void setContractDetails(String value)
  {
    setAttributeInternal(CONTRACTDETAILS, value);
  }

  /**
   * 
   * Gets the attribute value for RetOrigOrderNum, using the alias name RetOrigOrderNum
   */
  public String getRetOrigOrderNum()
  {
    return (String)getAttributeInternal(RETORIGORDERNUM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RetOrigOrderNum
   */
  public void setRetOrigOrderNum(String value)
  {
    setAttributeInternal(RETORIGORDERNUM, value);
  }

  /**
   * 
   * Gets the attribute value for RetOrigOrderDate, using the alias name RetOrigOrderDate
   */
  public Date getRetOrigOrderDate()
  {
    return (Date)getAttributeInternal(RETORIGORDERDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RetOrigOrderDate
   */
  public void setRetOrigOrderDate(Date value)
  {
    setAttributeInternal(RETORIGORDERDATE, value);
  }

  /**
   * 
   * Gets the attribute value for LineComments, using the alias name LineComments
   */
  public String getLineComments()
  {
    return (String)getAttributeInternal(LINECOMMENTS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LineComments
   */
  public void setLineComments(String value)
  {
    setAttributeInternal(LINECOMMENTS, value);
  }

  /**
   * 
   * Gets the attribute value for BackorderedQty, using the alias name BackorderedQty
   */
  public Number getBackorderedQty()
  {
    return (Number)getAttributeInternal(BACKORDEREDQTY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for BackorderedQty
   */
  public void setBackorderedQty(Number value)
  {
    setAttributeInternal(BACKORDEREDQTY, value);
  }

  /**
   * 
   * Gets the attribute value for TaxableFlag, using the alias name TaxableFlag
   */
  public String getTaxableFlag()
  {
    return (String)getAttributeInternal(TAXABLEFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for TaxableFlag
   */
  public void setTaxableFlag(String value)
  {
    setAttributeInternal(TAXABLEFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for WacaParentId, using the alias name WacaParentId
   */
  public Number getWacaParentId()
  {
    return (Number)getAttributeInternal(WACAPARENTID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for WacaParentId
   */
  public void setWacaParentId(Number value)
  {
    setAttributeInternal(WACAPARENTID, value);
  }

  /**
   * 
   * Gets the attribute value for RetOrigOrderLineNum, using the alias name RetOrigOrderLineNum
   */
  public String getRetOrigOrderLineNum()
  {
    return (String)getAttributeInternal(RETORIGORDERLINENUM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for RetOrigOrderLineNum
   */
  public void setRetOrigOrderLineNum(String value)
  {
    setAttributeInternal(RETORIGORDERLINENUM, value);
  }

  /**
   * 
   * Gets the attribute value for SkuDept, using the alias name SkuDept
   */
  public String getSkuDept()
  {
    return (String)getAttributeInternal(SKUDEPT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SkuDept
   */
  public void setSkuDept(String value)
  {
    setAttributeInternal(SKUDEPT, value);
  }

  /**
   * 
   * Gets the attribute value for ItemSource, using the alias name ItemSource
   */
  public String getItemSource()
  {
    return (String)getAttributeInternal(ITEMSOURCE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ItemSource
   */
  public void setItemSource(String value)
  {
    setAttributeInternal(ITEMSOURCE, value);
  }

  /**
   * 
   * Gets the attribute value for AverageCost, using the alias name AverageCost
   */
  public Number getAverageCost()
  {
    return (Number)getAttributeInternal(AVERAGECOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for AverageCost
   */
  public void setAverageCost(Number value)
  {
    setAttributeInternal(AVERAGECOST, value);
  }

  /**
   * 
   * Gets the attribute value for CanadaPstTax, using the alias name CanadaPstTax
   */
  public Number getCanadaPstTax()
  {
    return (Number)getAttributeInternal(CANADAPSTTAX);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CanadaPstTax
   */
  public void setCanadaPstTax(Number value)
  {
    setAttributeInternal(CANADAPSTTAX, value);
  }

  /**
   * 
   * Gets the attribute value for PoCost, using the alias name PoCost
   */
  public Number getPoCost()
  {
    return (Number)getAttributeInternal(POCOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PoCost
   */
  public void setPoCost(Number value)
  {
    setAttributeInternal(POCOST, value);
  }

  /**
   * 
   * Gets the attribute value for ResourcingFlag, using the alias name ResourcingFlag
   */
  public String getResourcingFlag()
  {
    return (String)getAttributeInternal(RESOURCINGFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ResourcingFlag
   */
  public void setResourcingFlag(String value)
  {
    setAttributeInternal(RESOURCINGFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for WacaStatus, using the alias name WacaStatus
   */
  public String getWacaStatus()
  {
    return (String)getAttributeInternal(WACASTATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for WacaStatus
   */
  public void setWacaStatus(String value)
  {
    setAttributeInternal(WACASTATUS, value);
  }

  /**
   * 
   * Gets the attribute value for CustItemNumber, using the alias name CustItemNumber
   */
  public String getCustItemNumber()
  {
    return (String)getAttributeInternal(CUSTITEMNUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustItemNumber
   */
  public void setCustItemNumber(String value)
  {
    setAttributeInternal(CUSTITEMNUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for PodDate, using the alias name PodDate
   */
  public Date getPodDate()
  {
    return (Date)getAttributeInternal(PODDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PodDate
   */
  public void setPodDate(Date value)
  {
    setAttributeInternal(PODDATE, value);
  }

  /**
   * 
   * Gets the attribute value for ReturnAuthId, using the alias name ReturnAuthId
   */
  public Number getReturnAuthId()
  {
    return (Number)getAttributeInternal(RETURNAUTHID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ReturnAuthId
   */
  public void setReturnAuthId(Number value)
  {
    setAttributeInternal(RETURNAUTHID, value);
  }

  /**
   * 
   * Gets the attribute value for ReturnCode, using the alias name ReturnCode
   */
  public String getReturnCode()
  {
    return (String)getAttributeInternal(RETURNCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ReturnCode
   */
  public void setReturnCode(String value)
  {
    setAttributeInternal(RETURNCODE, value);
  }

  /**
   * 
   * Gets the attribute value for SkuListPrice, using the alias name SkuListPrice
   */
  public Number getSkuListPrice()
  {
    return (Number)getAttributeInternal(SKULISTPRICE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SkuListPrice
   */
  public void setSkuListPrice(Number value)
  {
    setAttributeInternal(SKULISTPRICE, value);
  }

  /**
   * 
   * Gets the attribute value for WacaItemCtrNum, using the alias name WacaItemCtrNum
   */
  public String getWacaItemCtrNum()
  {
    return (String)getAttributeInternal(WACAITEMCTRNUM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for WacaItemCtrNum
   */
  public void setWacaItemCtrNum(String value)
  {
    setAttributeInternal(WACAITEMCTRNUM, value);
  }

  /**
   * 
   * Gets the attribute value for NewScheduleShipDate, using the alias name NewScheduleShipDate
   */
  public Date getNewScheduleShipDate()
  {
    return (Date)getAttributeInternal(NEWSCHEDULESHIPDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NewScheduleShipDate
   */
  public void setNewScheduleShipDate(Date value)
  {
    setAttributeInternal(NEWSCHEDULESHIPDATE, value);
  }

  /**
   * 
   * Gets the attribute value for NewScheduleArrDate, using the alias name NewScheduleArrDate
   */
  public Date getNewScheduleArrDate()
  {
    return (Date)getAttributeInternal(NEWSCHEDULEARRDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NewScheduleArrDate
   */
  public void setNewScheduleArrDate(Date value)
  {
    setAttributeInternal(NEWSCHEDULEARRDATE, value);
  }

  /**
   * 
   * Gets the attribute value for TaylorUnitPrice, using the alias name TaylorUnitPrice
   */
  public Number getTaylorUnitPrice()
  {
    return (Number)getAttributeInternal(TAYLORUNITPRICE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for TaylorUnitPrice
   */
  public void setTaylorUnitPrice(Number value)
  {
    setAttributeInternal(TAYLORUNITPRICE, value);
  }

  /**
   * 
   * Gets the attribute value for TaylorUnitCost, using the alias name TaylorUnitCost
   */
  public Number getTaylorUnitCost()
  {
    return (Number)getAttributeInternal(TAYLORUNITCOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for TaylorUnitCost
   */
  public void setTaylorUnitCost(Number value)
  {
    setAttributeInternal(TAYLORUNITCOST, value);
  }

  /**
   * 
   * Gets the attribute value for XdockInvOrgId, using the alias name XdockInvOrgId
   */
  public Number getXdockInvOrgId()
  {
    return (Number)getAttributeInternal(XDOCKINVORGID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for XdockInvOrgId
   */
  public void setXdockInvOrgId(Number value)
  {
    setAttributeInternal(XDOCKINVORGID, value);
  }

  /**
   * 
   * Gets the attribute value for PaymentSubtypeCodInd, using the alias name PaymentSubtypeCodInd
   */
  public String getPaymentSubtypeCodInd()
  {
    return (String)getAttributeInternal(PAYMENTSUBTYPECODIND);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PaymentSubtypeCodInd
   */
  public void setPaymentSubtypeCodInd(String value)
  {
    setAttributeInternal(PAYMENTSUBTYPECODIND, value);
  }

  /**
   * 
   * Gets the attribute value for DelToPostOfficeInd, using the alias name DelToPostOfficeInd
   */
  public String getDelToPostOfficeInd()
  {
    return (String)getAttributeInternal(DELTOPOSTOFFICEIND);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DelToPostOfficeInd
   */
  public void setDelToPostOfficeInd(String value)
  {
    setAttributeInternal(DELTOPOSTOFFICEIND, value);
  }

  /**
   * 
   * Gets the attribute value for WholesalerItem, using the alias name WholesalerItem
   */
  public String getWholesalerItem()
  {
    return (String)getAttributeInternal(WHOLESALERITEM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for WholesalerItem
   */
  public void setWholesalerItem(String value)
  {
    setAttributeInternal(WHOLESALERITEM, value);
  }

  /**
   * 
   * Gets the attribute value for CustCommPref, using the alias name CustCommPref
   */
  public String getCustCommPref()
  {
    return (String)getAttributeInternal(CUSTCOMMPREF);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustCommPref
   */
  public void setCustCommPref(String value)
  {
    setAttributeInternal(CUSTCOMMPREF, value);
  }

  /**
   * 
   * Gets the attribute value for CustPrefEmail, using the alias name CustPrefEmail
   */
  public String getCustPrefEmail()
  {
    return (String)getAttributeInternal(CUSTPREFEMAIL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustPrefEmail
   */
  public void setCustPrefEmail(String value)
  {
    setAttributeInternal(CUSTPREFEMAIL, value);
  }

  /**
   * 
   * Gets the attribute value for CustPrefFax, using the alias name CustPrefFax
   */
  public String getCustPrefFax()
  {
    return (String)getAttributeInternal(CUSTPREFFAX);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustPrefFax
   */
  public void setCustPrefFax(String value)
  {
    setAttributeInternal(CUSTPREFFAX, value);
  }

  /**
   * 
   * Gets the attribute value for CustPrefPhone, using the alias name CustPrefPhone
   */
  public String getCustPrefPhone()
  {
    return (String)getAttributeInternal(CUSTPREFPHONE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustPrefPhone
   */
  public void setCustPrefPhone(String value)
  {
    setAttributeInternal(CUSTPREFPHONE, value);
  }

  /**
   * 
   * Gets the attribute value for CustPrefPhextn, using the alias name CustPrefPhextn
   */
  public String getCustPrefPhextn()
  {
    return (String)getAttributeInternal(CUSTPREFPHEXTN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustPrefPhextn
   */
  public void setCustPrefPhextn(String value)
  {
    setAttributeInternal(CUSTPREFPHEXTN, value);
  }

  /**
   * 
   * Gets the attribute value for FreightLineId, using the alias name FreightLineId
   */
  public Number getFreightLineId()
  {
    return (Number)getAttributeInternal(FREIGHTLINEID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for FreightLineId
   */
  public void setFreightLineId(Number value)
  {
    setAttributeInternal(FREIGHTLINEID, value);
  }

  /**
   * 
   * Gets the attribute value for FreightPrimaryLineId, using the alias name FreightPrimaryLineId
   */
  public Number getFreightPrimaryLineId()
  {
    return (Number)getAttributeInternal(FREIGHTPRIMARYLINEID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for FreightPrimaryLineId
   */
  public void setFreightPrimaryLineId(Number value)
  {
    setAttributeInternal(FREIGHTPRIMARYLINEID, value);
  }

  /**
   * 
   * Gets the attribute value for CreationDate, using the alias name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * 
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin()
  {
    return (Number)getAttributeInternal(LASTUPDATELOGIN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value)
  {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**
   * 
   * Gets the attribute value for GsaFlag, using the alias name GsaFlag
   */
  public String getGsaFlag()
  {
    return (String)getAttributeInternal(GSAFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for GsaFlag
   */
  public void setGsaFlag(String value)
  {
    setAttributeInternal(GSAFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for ConsignmentBankCode, using the alias name ConsignmentBankCode
   */
  public String getConsignmentBankCode()
  {
    return (String)getAttributeInternal(CONSIGNMENTBANKCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ConsignmentBankCode
   */
  public void setConsignmentBankCode(String value)
  {
    setAttributeInternal(CONSIGNMENTBANKCODE, value);
  }

  /**
   * 
   * Gets the attribute value for PriceCd, using the alias name PriceCd
   */
  public String getPriceCd()
  {
    return (String)getAttributeInternal(PRICECD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PriceCd
   */
  public void setPriceCd(String value)
  {
    setAttributeInternal(PRICECD, value);
  }

  /**
   * 
   * Gets the attribute value for PriceChangeReasonCd, using the alias name PriceChangeReasonCd
   */
  public String getPriceChangeReasonCd()
  {
    return (String)getAttributeInternal(PRICECHANGEREASONCD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PriceChangeReasonCd
   */
  public void setPriceChangeReasonCd(String value)
  {
    setAttributeInternal(PRICECHANGEREASONCD, value);
  }

  /**
   * 
   * Gets the attribute value for PricePrefixCd, using the alias name PricePrefixCd
   */
  public String getPricePrefixCd()
  {
    return (String)getAttributeInternal(PRICEPREFIXCD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PricePrefixCd
   */
  public void setPricePrefixCd(String value)
  {
    setAttributeInternal(PRICEPREFIXCD, value);
  }

  /**
   * 
   * Gets the attribute value for CommisionableInd, using the alias name CommisionableInd
   */
  public String getCommisionableInd()
  {
    return (String)getAttributeInternal(COMMISIONABLEIND);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CommisionableInd
   */
  public void setCommisionableInd(String value)
  {
    setAttributeInternal(COMMISIONABLEIND, value);
  }

  /**
   * 
   * Gets the attribute value for CustDeptDescription, using the alias name CustDeptDescription
   */
  public String getCustDeptDescription()
  {
    return (String)getAttributeInternal(CUSTDEPTDESCRIPTION);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CustDeptDescription
   */
  public void setCustDeptDescription(String value)
  {
    setAttributeInternal(CUSTDEPTDESCRIPTION, value);
  }

  /**
   * 
   * Gets the attribute value for UnitOrigSellingPrice, using the alias name UnitOrigSellingPrice
   */
  public Number getUnitOrigSellingPrice()
  {
    return (Number)getAttributeInternal(UNITORIGSELLINGPRICE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for UnitOrigSellingPrice
   */
  public void setUnitOrigSellingPrice(Number value)
  {
    setAttributeInternal(UNITORIGSELLINGPRICE, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case LINEID:
        return getLineId();
      case LICENCEADDRESS:
        return getLicenceAddress();
      case VENDORCONFIGID:
        return getVendorConfigId();
      case FULFILLMENTTYPE:
        return getFulfillmentType();
      case LINETYPE:
        return getLineType();
      case LINEMODIFIER:
        return getLineModifier();
      case RELEASENUM:
        return getReleaseNum();
      case COSTCENTERDEPT:
        return getCostCenterDept();
      case DESKTOPDELADDR:
        return getDesktopDelAddr();
      case VENDORSITEID:
        return getVendorSiteId();
      case POSTRXNUM:
        return getPosTrxNum();
      case ONETIMEDEAL:
        return getOneTimeDeal();
      case TRANSLINESTATUS:
        return getTransLineStatus();
      case CUSTPRICE:
        return getCustPrice();
      case CUSTUOM:
        return getCustUom();
      case CUSTCOMMENTS:
        return getCustComments();
      case PIPCAMPAIGNID:
        return getPipCampaignId();
      case EXTTOPMODELLINEID:
        return getExtTopModelLineId();
      case EXTLINKTOLINEID:
        return getExtLinkToLineId();
      case CONFIGCODE:
        return getConfigCode();
      case GIFTMESSAGE:
        return getGiftMessage();
      case GIFTEMAIL:
        return getGiftEmail();
      case RETURNRGANUMBER:
        return getReturnRgaNumber();
      case DELIVERYDATEFROM:
        return getDeliveryDateFrom();
      case DELIVERYDATETO:
        return getDeliveryDateTo();
      case WHOLESALERFACCD:
        return getWholesalerFacCd();
      case WHOLESALERACCTNUM:
        return getWholesalerAcctNum();
      case RETURNACTCATCODE:
        return getReturnActCatCode();
      case PODELDETAILS:
        return getPoDelDetails();
      case RETREFHEADERID:
        return getRetRefHeaderId();
      case RETREFLINEID:
        return getRetRefLineId();
      case SHIPTOFLAG:
        return getShipToFlag();
      case ITEMNOTE:
        return getItemNote();
      case SPECIALDESC:
        return getSpecialDesc();
      case NONCDLINETYPE:
        return getNonCdLineType();
      case SUPPLIERTYPE:
        return getSupplierType();
      case VENDORPRODUCTCODE:
        return getVendorProductCode();
      case CONTRACTDETAILS:
        return getContractDetails();
      case RETORIGORDERNUM:
        return getRetOrigOrderNum();
      case RETORIGORDERDATE:
        return getRetOrigOrderDate();
      case LINECOMMENTS:
        return getLineComments();
      case BACKORDEREDQTY:
        return getBackorderedQty();
      case TAXABLEFLAG:
        return getTaxableFlag();
      case WACAPARENTID:
        return getWacaParentId();
      case RETORIGORDERLINENUM:
        return getRetOrigOrderLineNum();
      case SKUDEPT:
        return getSkuDept();
      case ITEMSOURCE:
        return getItemSource();
      case AVERAGECOST:
        return getAverageCost();
      case CANADAPSTTAX:
        return getCanadaPstTax();
      case POCOST:
        return getPoCost();
      case RESOURCINGFLAG:
        return getResourcingFlag();
      case WACASTATUS:
        return getWacaStatus();
      case CUSTITEMNUMBER:
        return getCustItemNumber();
      case PODDATE:
        return getPodDate();
      case RETURNAUTHID:
        return getReturnAuthId();
      case RETURNCODE:
        return getReturnCode();
      case SKULISTPRICE:
        return getSkuListPrice();
      case WACAITEMCTRNUM:
        return getWacaItemCtrNum();
      case NEWSCHEDULESHIPDATE:
        return getNewScheduleShipDate();
      case NEWSCHEDULEARRDATE:
        return getNewScheduleArrDate();
      case TAYLORUNITPRICE:
        return getTaylorUnitPrice();
      case TAYLORUNITCOST:
        return getTaylorUnitCost();
      case XDOCKINVORGID:
        return getXdockInvOrgId();
      case PAYMENTSUBTYPECODIND:
        return getPaymentSubtypeCodInd();
      case DELTOPOSTOFFICEIND:
        return getDelToPostOfficeInd();
      case WHOLESALERITEM:
        return getWholesalerItem();
      case CUSTCOMMPREF:
        return getCustCommPref();
      case CUSTPREFEMAIL:
        return getCustPrefEmail();
      case CUSTPREFFAX:
        return getCustPrefFax();
      case CUSTPREFPHONE:
        return getCustPrefPhone();
      case CUSTPREFPHEXTN:
        return getCustPrefPhextn();
      case FREIGHTLINEID:
        return getFreightLineId();
      case FREIGHTPRIMARYLINEID:
        return getFreightPrimaryLineId();
      case CREATIONDATE:
        return getCreationDate();
      case CREATEDBY:
        return getCreatedBy();
      case LASTUPDATEDATE:
        return getLastUpdateDate();
      case LASTUPDATEDBY:
        return getLastUpdatedBy();
      case LASTUPDATELOGIN:
        return getLastUpdateLogin();
      case GSAFLAG:
        return getGsaFlag();
      case CONSIGNMENTBANKCODE:
        return getConsignmentBankCode();
      case PRICECD:
        return getPriceCd();
      case PRICECHANGEREASONCD:
        return getPriceChangeReasonCd();
      case PRICEPREFIXCD:
        return getPricePrefixCd();
      case COMMISIONABLEIND:
        return getCommisionableInd();
      case CUSTDEPTDESCRIPTION:
        return getCustDeptDescription();
      case UNITORIGSELLINGPRICE:
        return getUnitOrigSellingPrice();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case LINEID:
        setLineId((Number)value);
        return;
      case LICENCEADDRESS:
        setLicenceAddress((String)value);
        return;
      case VENDORCONFIGID:
        setVendorConfigId((String)value);
        return;
      case FULFILLMENTTYPE:
        setFulfillmentType((String)value);
        return;
      case LINETYPE:
        setLineType((String)value);
        return;
      case LINEMODIFIER:
        setLineModifier((String)value);
        return;
      case RELEASENUM:
        setReleaseNum((String)value);
        return;
      case COSTCENTERDEPT:
        setCostCenterDept((String)value);
        return;
      case DESKTOPDELADDR:
        setDesktopDelAddr((String)value);
        return;
      case VENDORSITEID:
        setVendorSiteId((Number)value);
        return;
      case POSTRXNUM:
        setPosTrxNum((String)value);
        return;
      case ONETIMEDEAL:
        setOneTimeDeal((String)value);
        return;
      case TRANSLINESTATUS:
        setTransLineStatus((String)value);
        return;
      case CUSTPRICE:
        setCustPrice((Number)value);
        return;
      case CUSTUOM:
        setCustUom((String)value);
        return;
      case CUSTCOMMENTS:
        setCustComments((String)value);
        return;
      case PIPCAMPAIGNID:
        setPipCampaignId((String)value);
        return;
      case EXTTOPMODELLINEID:
        setExtTopModelLineId((Number)value);
        return;
      case EXTLINKTOLINEID:
        setExtLinkToLineId((Number)value);
        return;
      case CONFIGCODE:
        setConfigCode((String)value);
        return;
      case GIFTMESSAGE:
        setGiftMessage((String)value);
        return;
      case GIFTEMAIL:
        setGiftEmail((String)value);
        return;
      case RETURNRGANUMBER:
        setReturnRgaNumber((String)value);
        return;
      case DELIVERYDATEFROM:
        setDeliveryDateFrom((Date)value);
        return;
      case DELIVERYDATETO:
        setDeliveryDateTo((Date)value);
        return;
      case WHOLESALERFACCD:
        setWholesalerFacCd((String)value);
        return;
      case WHOLESALERACCTNUM:
        setWholesalerAcctNum((String)value);
        return;
      case RETURNACTCATCODE:
        setReturnActCatCode((String)value);
        return;
      case PODELDETAILS:
        setPoDelDetails((String)value);
        return;
      case RETREFHEADERID:
        setRetRefHeaderId((Number)value);
        return;
      case RETREFLINEID:
        setRetRefLineId((Number)value);
        return;
      case SHIPTOFLAG:
        setShipToFlag((String)value);
        return;
      case ITEMNOTE:
        setItemNote((String)value);
        return;
      case SPECIALDESC:
        setSpecialDesc((String)value);
        return;
      case NONCDLINETYPE:
        setNonCdLineType((String)value);
        return;
      case SUPPLIERTYPE:
        setSupplierType((String)value);
        return;
      case VENDORPRODUCTCODE:
        setVendorProductCode((String)value);
        return;
      case CONTRACTDETAILS:
        setContractDetails((String)value);
        return;
      case RETORIGORDERNUM:
        setRetOrigOrderNum((String)value);
        return;
      case RETORIGORDERDATE:
        setRetOrigOrderDate((Date)value);
        return;
      case LINECOMMENTS:
        setLineComments((String)value);
        return;
      case BACKORDEREDQTY:
        setBackorderedQty((Number)value);
        return;
      case TAXABLEFLAG:
        setTaxableFlag((String)value);
        return;
      case WACAPARENTID:
        setWacaParentId((Number)value);
        return;
      case RETORIGORDERLINENUM:
        setRetOrigOrderLineNum((String)value);
        return;
      case SKUDEPT:
        setSkuDept((String)value);
        return;
      case ITEMSOURCE:
        setItemSource((String)value);
        return;
      case AVERAGECOST:
        setAverageCost((Number)value);
        return;
      case CANADAPSTTAX:
        setCanadaPstTax((Number)value);
        return;
      case POCOST:
        setPoCost((Number)value);
        return;
      case RESOURCINGFLAG:
        setResourcingFlag((String)value);
        return;
      case WACASTATUS:
        setWacaStatus((String)value);
        return;
      case CUSTITEMNUMBER:
        setCustItemNumber((String)value);
        return;
      case PODDATE:
        setPodDate((Date)value);
        return;
      case RETURNAUTHID:
        setReturnAuthId((Number)value);
        return;
      case RETURNCODE:
        setReturnCode((String)value);
        return;
      case SKULISTPRICE:
        setSkuListPrice((Number)value);
        return;
      case WACAITEMCTRNUM:
        setWacaItemCtrNum((String)value);
        return;
      case NEWSCHEDULESHIPDATE:
        setNewScheduleShipDate((Date)value);
        return;
      case NEWSCHEDULEARRDATE:
        setNewScheduleArrDate((Date)value);
        return;
      case TAYLORUNITPRICE:
        setTaylorUnitPrice((Number)value);
        return;
      case TAYLORUNITCOST:
        setTaylorUnitCost((Number)value);
        return;
      case XDOCKINVORGID:
        setXdockInvOrgId((Number)value);
        return;
      case PAYMENTSUBTYPECODIND:
        setPaymentSubtypeCodInd((String)value);
        return;
      case DELTOPOSTOFFICEIND:
        setDelToPostOfficeInd((String)value);
        return;
      case WHOLESALERITEM:
        setWholesalerItem((String)value);
        return;
      case CUSTCOMMPREF:
        setCustCommPref((String)value);
        return;
      case CUSTPREFEMAIL:
        setCustPrefEmail((String)value);
        return;
      case CUSTPREFFAX:
        setCustPrefFax((String)value);
        return;
      case CUSTPREFPHONE:
        setCustPrefPhone((String)value);
        return;
      case CUSTPREFPHEXTN:
        setCustPrefPhextn((String)value);
        return;
      case FREIGHTLINEID:
        setFreightLineId((Number)value);
        return;
      case FREIGHTPRIMARYLINEID:
        setFreightPrimaryLineId((Number)value);
        return;
      case CREATIONDATE:
        setCreationDate((Date)value);
        return;
      case CREATEDBY:
        setCreatedBy((Number)value);
        return;
      case LASTUPDATEDATE:
        setLastUpdateDate((Date)value);
        return;
      case LASTUPDATEDBY:
        setLastUpdatedBy((Number)value);
        return;
      case LASTUPDATELOGIN:
        setLastUpdateLogin((Number)value);
        return;
      case GSAFLAG:
        setGsaFlag((String)value);
        return;
      case CONSIGNMENTBANKCODE:
        setConsignmentBankCode((String)value);
        return;
      case PRICECD:
        setPriceCd((String)value);
        return;
      case PRICECHANGEREASONCD:
        setPriceChangeReasonCd((String)value);
        return;
      case PRICEPREFIXCD:
        setPricePrefixCd((String)value);
        return;
      case COMMISIONABLEIND:
        setCommisionableInd((String)value);
        return;
      case CUSTDEPTDESCRIPTION:
        setCustDeptDescription((String)value);
        return;
      case UNITORIGSELLINGPRICE:
        setUnitOrigSellingPrice((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number lineId)
  {
    return new Key(new Object[] {lineId});
  }
}