<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="EncodeBPELProcess"
     targetNamespace="http://xmlns.oracle.com/SerializedCouponApplication/SerializedCouponConverter/EncodeBPELProcess"
     xmlns:ns1="http://www.officedepot.com/SerializableCouponConverter"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/SerializedCouponApplication/SerializedCouponConverter/EncodeBPELProcess"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="EncodeBPELProcess">
        <plnk:role name="EncodeBPELProcessProvider">
            <plnk:portType name="client:EncodeBPELProcess"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.officedepot.com/SerializableCouponConverter"
             xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:client="http://xmlns.oracle.com/SerializedCouponApplication/SerializedCouponConverter/EncodeBPELProcess"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
            <import namespace="http://www.officedepot.com/SerializableCouponConverter" schemaLocation="xsd/serializedCouponConverter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="EncodeBPELProcessRequestMessage">
        <wsdl:part name="payload" element="ns1:decodedSerializedCoupon"/>
    </wsdl:message>
    <wsdl:message name="EncodeBPELProcessResponseMessage">
        <wsdl:part name="payload" element="ns1:encodedSerializedCoupon"/>
    </wsdl:message>
    <wsdl:portType name="EncodeBPELProcess">
        <wsdl:operation name="process">
            <wsdl:input message="client:EncodeBPELProcessRequestMessage"/>
            <wsdl:output message="client:EncodeBPELProcessResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>