<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
     name="EJMRecordsHttpGetAdapter"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/http/MyJavaApplication/SelectProjectEJMReqABCSImpl/EJMRecordsHttpGetAdapter"
     xmlns:msg_in="http://TargetNamespace.com/http"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/http/MyJavaApplication/SelectProjectEJMReqABCSImpl/EJMRecordsHttpGetAdapter"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    >
    <plt:partnerLinkType name="Send_plt">
        <plt:role name="Send_role">
            <plt:portType name="tns:Send_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://TargetNamespace.com/http" schemaLocation="xsd/EJMRecordsHttpGetAdapter.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="root_msg_in">
        <wsdl:part name="root" element="msg_in:root"/>
    </wsdl:message>
    <wsdl:portType name="Send_ptt">
        <wsdl:operation name="Send">
            <wsdl:input message="tns:root_msg_in"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
