<?binding.jca getEJMDataDBAdapter_db.jca?>
<wsdl:definitions name="getEJMDataDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MyJavaApplication/SelectProjectEJMReqABCSImpl/getEJMDataDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MyJavaApplication/SelectProjectEJMReqABCSImpl/getEJMDataDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/getEJMDataDBAdapter">
    <plt:partnerLinkType name="getEJMDataDBAdapter_plt">
        <plt:role name="getEJMDataDBAdapter_role">
            <plt:portType name="tns:getEJMDataDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/getEJMDataDBAdapter" schemaLocation="xsd/getEJMDataDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="getEJMDataDBAdapterSelect_inputParameters">
        <wsdl:part name="getEJMDataDBAdapterSelect_inputParameters" element="top:getEJMDataDBAdapterSelectInputParameters"/>
    </wsdl:message>
    <wsdl:message name="VwEbsPaCollection_msg">
        <wsdl:part name="VwEbsPaCollection" element="top:VwEbsPaCollection"/>
    </wsdl:message>
    <wsdl:portType name="getEJMDataDBAdapter_ptt">
        <wsdl:operation name="getEJMDataDBAdapterSelect">
            <wsdl:input message="tns:getEJMDataDBAdapterSelect_inputParameters"/>
            <wsdl:output message="tns:VwEbsPaCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
