package od.oracle.apps.xxcrm.cn.payrun.server;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.BlobDomain;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class ODPayrollAuditHistVORowImpl extends OAViewRowImpl 
{


  protected static final int RECORDID = 0;
  protected static final int PAYRUN = 1;
  protected static final int PAYRUNDATE = 2;
  protected static final int BPELTRANSFERDATE = 3;
  protected static final int TRANSFERSTATUS = 4;
  protected static final int REASON = 5;
  protected static final int LOG = 6;
  protected static final int CREATIONDATE = 7;
  protected static final int CREATEDBY = 8;
  protected static final int LASTUPDATEDATE = 9;
  protected static final int LASTUPDATEDBY = 10;
  protected static final int LASTUPDATEDLOGIN = 11;
  protected static final int LOGFILE = 12;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public ODPayrollAuditHistVORowImpl()
  {
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute RecordId
   */
  public Number getRecordId()
  {
    return (Number)getAttributeInternal(RECORDID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute RecordId
   */
  public void setRecordId(Number value)
  {
    setAttributeInternal(RECORDID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Payrun
   */
  public String getPayrun()
  {
    return (String)getAttributeInternal(PAYRUN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Payrun
   */
  public void setPayrun(String value)
  {
    setAttributeInternal(PAYRUN, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute PayrunDate
   */
  public Date getPayrunDate()
  {
    return (Date)getAttributeInternal(PAYRUNDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute PayrunDate
   */
  public void setPayrunDate(Date value)
  {
    setAttributeInternal(PAYRUNDATE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute BpelTransferDate
   */
  public Date getBpelTransferDate()
  {
    return (Date)getAttributeInternal(BPELTRANSFERDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute BpelTransferDate
   */
  public void setBpelTransferDate(Date value)
  {
    setAttributeInternal(BPELTRANSFERDATE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute TransferStatus
   */
  public String getTransferStatus()
  {
    return (String)getAttributeInternal(TRANSFERSTATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute TransferStatus
   */
  public void setTransferStatus(String value)
  {
    setAttributeInternal(TRANSFERSTATUS, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Reason
   */
  public String getReason()
  {
    return (String)getAttributeInternal(REASON);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Reason
   */
  public void setReason(String value)
  {
    setAttributeInternal(REASON, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Log
   */
  public BlobDomain getLog()
  {
    return (BlobDomain)getAttributeInternal(LOG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Log
   */
  public void setLog(BlobDomain value)
  {
    setAttributeInternal(LOG, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute LastUpdatedLogin
   */
  public Number getLastUpdatedLogin()
  {
    return (Number)getAttributeInternal(LASTUPDATEDLOGIN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedLogin
   */
  public void setLastUpdatedLogin(Number value)
  {
    setAttributeInternal(LASTUPDATEDLOGIN, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case RECORDID:
        return getRecordId();
      case PAYRUN:
        return getPayrun();
      case PAYRUNDATE:
        return getPayrunDate();
      case BPELTRANSFERDATE:
        return getBpelTransferDate();
      case TRANSFERSTATUS:
        return getTransferStatus();
      case REASON:
        return getReason();
      case LOG:
        return getLog();
      case CREATIONDATE:
        return getCreationDate();
      case CREATEDBY:
        return getCreatedBy();
      case LASTUPDATEDATE:
        return getLastUpdateDate();
      case LASTUPDATEDBY:
        return getLastUpdatedBy();
      case LASTUPDATEDLOGIN:
        return getLastUpdatedLogin();
      case LOGFILE:
        return getLogfile();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case RECORDID:
        setRecordId((Number)value);
        return;
      case PAYRUN:
        setPayrun((String)value);
        return;
      case PAYRUNDATE:
        setPayrunDate((Date)value);
        return;
      case BPELTRANSFERDATE:
        setBpelTransferDate((Date)value);
        return;
      case TRANSFERSTATUS:
        setTransferStatus((String)value);
        return;
      case REASON:
        setReason((String)value);
        return;
      case LOG:
        setLog((BlobDomain)value);
        return;
      case CREATIONDATE:
        setCreationDate((Date)value);
        return;
      case CREATEDBY:
        setCreatedBy((Number)value);
        return;
      case LASTUPDATEDATE:
        setLastUpdateDate((Date)value);
        return;
      case LASTUPDATEDBY:
        setLastUpdatedBy((Number)value);
        return;
      case LASTUPDATEDLOGIN:
        setLastUpdatedLogin((Number)value);
        return;
      case LOGFILE:
        setLogfile((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Logfile
   */
  public String getLogfile()
  {
    return (String)getAttributeInternal(LOGFILE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Logfile
   */
  public void setLogfile(String value)
  {
    setAttributeInternal(LOGFILE, value);
  }
}