package od.oracle.apps.xxfin.ar.irec.reports.server;

import java.sql.Types;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.fnd.framework.server.OADBTransaction;
import oracle.jdbc.OracleCallableStatement;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
//import oracle.apps.fnd.framework.OAException;

//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class AccountsCloseToCreditLimitAMImpl extends OAApplicationModuleImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public AccountsCloseToCreditLimitAMImpl()
  {
  }

  /**
   * 
   * Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("od.oracle.apps.xxfin.ar.irec.reports.server", "AccountsCloseToCreditLimitAMLocal");
  }

  public String SubmitAccountsCloseToCreditLimitReport(String sOutstandingAmountLow, String sOutstandingAmountHigh,
                                                       String sCollectorNumberLow  , String sCollectorNumberHigh,
                                                       String sCollectorClass      , String sEmailList)
  {
      // Todo: replace hardcoded messages with FND_NEW_MESSAGE
      String sResult = "Unable to submit report;  Please try again later.";
      OracleCallableStatement sqlStmt = null;
      try
      {
         OADBTransaction txn = getOADBTransaction();
         sqlStmt = (OracleCallableStatement)txn.createCallableStatement("CALL XX_ARI_AD_HOC_REPORT_PKG.RUN_ACC_CLOSE_TO_CRD_LIMIT_RPT(?,?,?,?,?,?,?)", 1);
         sqlStmt.setString(1,sOutstandingAmountLow);
         sqlStmt.setString(2,sOutstandingAmountHigh);
         sqlStmt.setString(3,sCollectorNumberLow);
         sqlStmt.setString(4,sCollectorNumberHigh);
         sqlStmt.setString(5,sCollectorClass);
         sqlStmt.setString(6,sEmailList);
         sqlStmt.registerOutParameter(7, Types.VARCHAR);
         sqlStmt.execute();
         if (sqlStmt != null) {
            sResult = sqlStmt.getString(7);
            if (sResult!=null && sResult.equals("0")) sResult = "Unable to submit report;  Please try again later.";
            else sResult = "Request " + sResult + " has been submitted and will be emailed when complete.  Note, this report may take several minutes to prepare.";
            sqlStmt.close();
         }
      }
      catch (Exception ex) 
      {
         try {if (sqlStmt != null) sqlStmt.close();}
         catch(Exception ex2) {} // handle in PL/SQL
      }

      return sResult;
  }  




}