SET SERVEROUTPUT ON;
SPOOL import.log;

SET NEWPAGE 0;
SET SPACE 0;
SET LINESIZE 80;
SET PAGESIZE 0;
SET ECHO OFF;
SET FEEDBACK OFF;
SET VERIFY OFF;
SET HEADING OFF;
SET MARKUP HTML OFF SPOOL OFF;

SPOOL import.log;
EXECUTE ImportCustomer();
EXECUTE ImportClientSKU();
EXECUTE ImportCustExemptCert();
SELECT MESSAGE FROM IMPORT_ERROR_TEMP ORDER BY TIMERECORDED;

QUIT;