Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (65,'Test',null,null,null,null,to_date('15-MAR-18','DD-MON-RR'),3818034,to_date('15-MAR-18','DD-MON-RR'),3818034,69249251,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (1,'Company',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('15-MAR-18','DD-MON-RR'),3818034,69249251,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (2,'Correspondence
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (3,'Return To Vendor
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (4,'Purchase Order
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (5,'Payee
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (6,'AP Special Address
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (7,'Chief Fncl Officer
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (8,'Customer Service
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (9,'EDI Contact
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (10,'Product Liability
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (11,'Auto Dstry Contact
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (12,'Rgnl Sales Manager
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (13,'Replen Prfm Contct
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (14,'New Str Open Sched
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (15,'Senior Officer
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (16,'Natl Sales Manager
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (17,'Logistics Manager
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (18,'Vice President Sales
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (19,'Account Sales Manager
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (20,'Legal Contact
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (21,'CEO
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
Insert into xx_ap_sup_address_type (ADDRESS_TYPE,ADDRESS_TYPE_DESC,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN,ENABLE_FLAG) values (22,'3rd Party Sales Representative
',null,null,null,null,to_date('08-MAR-18','DD-MON-RR'),-1,to_date('08-MAR-18','DD-MON-RR'),-1,-1,'Y');
