DECLARE

 ln_hold_definition_id NUMBER;
 
BEGIN

   --Deriving the Sequence generated Hold Definition Id
   ----------------------------------------------------
   SELECT XX_OM_odholdframework_s1.NEXTVAL
   INTO   ln_hold_definition_id 
   FROM   DUAL;
   

INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1044, 'HOLD', 'A', 'O', 'B', NULL, 1, NULL, NULL, 'N', NULL, 2, 'N', 'CREATE OR REPLACE FUNCTION Eval_Od_Held_For_Quote( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER;  l_hold_period NUMBER;  l_holdexists_days NUMBER;  l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  l_ret_sts :=''Y''; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Held_For_Quote;'
, 'Eval_Od_Held_For_Quote',  TO_Date( '05/28/2007 01:36:03 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:36:03 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1041, 'HOLD', 'A', 'O', 'B', NULL, 1, 1, NULL, 'N', NULL, 3, 'N', 'CREATE OR REPLACE FUNCTION Eval_Od_Awaiting_External_App( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER;  l_hold_period NUMBER;  l_holdexists_days NUMBER;  l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  l_ret_sts :=''Y''; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Awaiting_External_App;'
, 'Eval_Od_Awaiting_External_App',  TO_Date( '05/28/2007 01:36:13 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:36:13 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1005, 'HOLD', 'A', 'O', 'B', 141, 1, 1, NULL, 'N', NULL, 4, 'N', 'CREATE OR REPLACE FUNCTION Eval_Od_Large_Order( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER; l_hold_period NUMBER; l_orgidm NUMBER; l_orgid NUMBER; l_holdexists_days NUMBER;  l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  SELECT COUNT(1) INTO l_count FROM oe_order_headers H,oe_order_lines L,xx_om_lines_attributes_all KFF WHERE H.header_id = NVL(I_OrdHdrId,H.header_id) AND L.line_id = DECODE(I_OrdLinId,0,L.line_id,I_OrdLinId) AND H.header_id = L.Header_id AND KFF.combination_id = L.attribute6 AND KFF.Segment8 =''LARGE''; BEGIN SELECT H.org_id INTO l_orgid FROM oe_order_headers H,oe_order_lines L WHERE H.header_id = NVL(I_OrdHdrId,H.header_id) AND L.line_id = DECODE(I_OrdLinId,0,L.line_id,I_OrdLinId) AND H.header_id = L.Header_id; EXCEPTION WHEN NO_DATA_FOUND THEN l_orgid:=NULL; WHEN OTHERS THEN l_orgid:=NULL; END; BEGIN SELECT NVL(M.org_id,0) INTO l_orgidm FROM Xx_Om_Od_Hold_Additional_Info M WHERE M.hold_id = I_HoldId; EXCEPTION WHEN NO_DATA_FOUND THEN l_orgidm:=NULL; WHEN OTHERS THEN l_orgidm:=NULL; END; IF NVL(l_orgidm,-1) = NVL(l_orgid,-9) THEN IF l_count > 0 THEN l_ret_sts :=''Y''; ELSE l_ret_sts :=''N''; END IF; END IF; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Large_Order;'
, 'Eval_Od_Large_Order',  TO_Date( '05/28/2007 01:36:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:36:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1012, 'HOLD', 'A', 'O', 'B', 161, 1, 1, NULL, 'Y', NULL, 5, 'N', 'CREATE OR REPLACE FUNCTION Eval_Od_Export_Hold( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_Orgids NUMBER;  l_Orgidm NUMBER;  l_hold_period NUMBER; l_holdexists_days NUMBER; l_ret_sts VARCHAR2(1) :=''N'';  BEGIN IF I_action =''APPLY'' THEN  BEGIN SELECT H.Org_Id INTO l_Orgids FROM oe_order_headers H ,oe_order_types_v T WHERE H.header_id = I_OrdHdrId AND H.order_type_id = T.order_type_id AND T.name LIKE ''OD%EXPORT%''; EXCEPTION WHEN NO_DATA_FOUND THEN l_Orgids:=NULL; WHEN OTHERS THEN l_Orgids:=NULL; END; BEGIN SELECT M.org_id INTO l_orgidm FROM Xx_Om_Od_Hold_Additional_Info M WHERE M.hold_id = I_HoldId; EXCEPTION WHEN NO_DATA_FOUND THEN l_orgidm:=NULL; WHEN OTHERS THEN l_orgidm:=NULL; END; IF NVL(l_Orgids,-1) = NVL(l_Orgidm,-2) THEN l_ret_sts :=''Y''; ELSE l_ret_sts :=''N''; END IF; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Export_Hold;'
, 'Eval_Od_Export_Hold',  TO_Date( '05/28/2007 01:36:55 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:36:55 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1009, 'HOLD', 'A', 'O', 'A', NULL, 1, 1, NULL, 'N', NULL, 6, 'N', 'CREATE OR REPLACE FUNCTION Eval_Od_Waiting_For_Payment( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER; l_hold_period NUMBER;  l_holdexists_days NUMBER;  l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  SELECT COUNT(1) INTO l_count FROM oe_order_headers H WHERE H.header_id = NVL(I_OrdHdrId,H.header_id) AND H.payment_type_code IN (''CASH'',''CHECK''); IF l_count > 0 THEN l_ret_sts :=''Y''; ELSE l_ret_sts :=''N''; END IF; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Waiting_For_Payment;'
, 'Eval_Od_Waiting_For_Payment',  TO_Date( '05/28/2007 01:37:03 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:37:03 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1002, 'HOLD', 'A', 'O', 'A', NULL, 1, NULL, NULL, 'Y', NULL, 7, 'N', 'CREATE OR REPLACE FUNCTION Eval_Od_Buyers_Remorse( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER; l_hold_period NUMBER; l_holdexists_days NUMBER; l_ret_sts VARCHAR2(1) := ''N''; BEGIN IF I_action =''APPLY'' THEN SELECT COUNT(1) INTO l_count FROM oe_order_headers H,oe_order_lines L  WHERE H.header_id = NVL(I_OrdHdrId,H.header_id) AND L.line_id = DECODE(I_OrdLinId,0,L.line_id,I_OrdLinId) AND H.header_id = L.Header_id AND L.Source_type_code = ''EXTERNAL''; IF l_count > 0 THEN  l_ret_sts := ''Y''; ELSE l_ret_sts := ''N''; END IF; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts;  EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Buyers_Remorse;'
, 'Eval_Od_Buyers_Remorse',  TO_Date( '05/28/2007 01:37:13 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:37:13 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1043, 'HOLD', 'A', 'O', 'A', NULL, 1, 1, NULL, 'N', NULL, 8, 'N', 'CREATE OR REPLACE FUNCTION Eval_Od_Aci_Hold( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER; l_hold_period NUMBER;  l_holdexists_days NUMBER;  l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  SELECT COUNT(1)  INTO l_count FROM oe_order_headers h,hz_cust_accounts c,hz_parties p WHERE h.header_id = I_OrdHdrId AND h.sold_to_org_id = c.cust_account_id AND c.party_id = p.party_id AND p.party_name=''AMAZON''; IF l_count > 0 THEN l_ret_sts :=''Y''; ELSE l_ret_sts :=''N''; END IF; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Aci_Hold;'
, 'Eval_Od_Aci_Hold',  TO_Date( '05/28/2007 01:37:22 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:37:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1048, 'HOLD', 'M', 'O', 'B', 141, 1, NULL, NULL, 'N', NULL, 1, 'N', 'CREATE OR REPLACE FUNCTION Eval_Od_Held_For_Comments( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER, I_hdrline VARCHAR2) RETURN CHAR IS l_count NUMBER; l_hold_period NUMBER;  l_holdexists_days NUMBER;  l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  IF I_hdrline=''O'' THEN  SELECT COUNT(1) INTO l_count FROM oe_order_headers H,xx_om_headers_attributes_all KFF WHERE KFF.combination_id = H.attribute7 AND H.header_id = I_OrdHdrId AND KFF.segment1 IS NOT NULL; IF l_count > 0 THEN l_ret_sts :=''Y''; ELSE l_ret_sts :=''N''; END IF; ELSIF I_hdrline=''L'' THEN  SELECT COUNT(1) INTO l_count FROM oe_order_lines L,xx_om_lines_attributes_all KFF WHERE KFF.combination_id = L.attribute8 AND L.header_id = I_OrdHdrId AND L.line_id = DECODE(I_OrdLinId,0,L.line_id,I_OrdLinId) AND KFF.segment1 IS NOT NULL; IF l_count > 0 THEN l_ret_sts :=''Y''; ELSE l_ret_sts :=''N''; END IF; END IF; ELSE BEGIN SELECT TRUNC(SYSDATE) - NVL(TRUNC(H.creation_date),TRUNC(SYSDATE)) INTO l_holdexists_days FROM oe_hold_sources S ,oe_order_holds H ,oe_hold_definitions D WHERE S.hold_entity_code=''O'' AND S.hold_entity_id=I_OrdHdrId AND S.hold_id=I_holdid AND S.released_flag=''N'' AND H.hold_source_id=S.hold_source_id AND S.hold_id=D.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_holdexists_days:= NULL; WHEN OTHERS THEN  l_holdexists_days:= NULL; END; IF I_hdrline=''O'' THEN  BEGIN SELECT NVL(M.no_of_days,0) INTO l_hold_period FROM Xx_Om_Od_Hold_Additional_Info M WHERE M.hold_id=I_holdid AND apply_to_order_or_line=I_hdrline; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; END; ELSIF I_hdrline=''L'' THEN  BEGIN SELECT NVL(M.no_of_days,0) INTO l_hold_period FROM Xx_Om_Od_Hold_Additional_Info M WHERE M.hold_id=I_holdid AND apply_to_order_or_line=I_hdrline; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; END; END IF; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Held_For_Comments;'
, 'Eval_Od_Held_For_Comments',  TO_Date( '05/28/2007 01:37:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:37:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1011, 'HOLD', 'M', 'O', 'B', NULL, 1, 1, NULL, 'N', NULL, 2, 'N', 'CREATE OR REPLACE FUNCTION Eval_Od_Price_Check( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER;  l_hold_period NUMBER;  l_holdexists_days NUMBER;  l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  l_ret_sts :=''Y''; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Price_Check;'
, 'Eval_Od_Price_Check',  TO_Date( '05/28/2007 01:38:35 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:38:35 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1042, 'HOLD', 'M', 'O', 'A', NULL, 1, 1, NULL, 'Y', NULL, 3, 'N', 'CREATE OR REPLACE FUNCTION Eval_Od_Billing_Hold( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER;  l_hold_period NUMBER;  l_holdexists_days NUMBER;  l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  l_ret_sts :=''Y''; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Billing_Hold;'
, 'Eval_Od_Billing_Hold',  TO_Date( '05/28/2007 01:38:50 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:38:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1045, 'HOLD', 'M', 'O', 'B', NULL, 1, NULL, NULL, 'N', NULL, 4, 'Y', 'CREATE OR REPLACE FUNCTION Eval_Od_Held_For_Approval( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER; l_hold_period NUMBER;  l_holdexists_days NUMBER;  l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  SELECT COUNT(1) INTO l_count FROM oe_order_headers h,oe_order_lines l WHERE H.header_id = NVL(I_OrdHdrId, H.header_id) AND L.line_id = DECODE(I_OrdLinId,0,L.line_id,I_OrdLinId) AND H.header_id = L.header_id AND L.line_category_code=''RETURN''; IF l_count > 0 THEN l_ret_sts :=''Y''; ELSE l_ret_sts :=''N''; END IF; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Held_For_Approval;'
, 'Eval_Od_Held_For_Approval',  TO_Date( '05/28/2007 01:39:04 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:39:04 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1046, 'HOLD', 'M', 'L', 'A', NULL, 1, NULL, NULL, 'N', NULL, 5, 'N', 'CREATE OR REPLACE FUNCTION Eval_Od_Held_For_Resourcing( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER;  l_hold_period NUMBER;  l_holdexists_days NUMBER;  l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  l_ret_sts :=''Y''; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Held_For_Resourcing;'
, 'Eval_Od_Held_For_Resourcing',  TO_Date( '05/28/2007 01:39:18 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:39:18 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1047, 'HOLD', 'M', 'L', 'A', NULL, 1, NULL, NULL, 'N', NULL, 6, 'N', 'CREATE OR REPLACE FUNCTION Eval_Od_Held_For_Waca( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER; l_hold_period NUMBER;  l_holdexists_days NUMBER;  l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  SELECT COUNT(1) INTO l_count FROM oe_order_lines L ,mtl_item_categories I ,mtl_categories_b C ,mtl_category_sets S WHERE L.line_id = DECODE(I_OrdLinId,0,L.line_id,I_OrdLinId) AND L.top_model_line_id =( SELECT TO_NUMBER(KFF.segment28) FROM xx_om_lines_attributes_all KFF WHERE KFF.combination_id = l.attribute6) AND L.inventory_item_id = I.inventory_item_id AND L.ship_from_org_id = I.organization_id AND I.category_id = C.category_id AND I.category_set_id = S.category_set_id AND C.structure_id = S.structure_id AND S.structure_id = (SELECT id_flex_num FROM fnd_id_flex_structures WHERE id_flex_structure_code= ''RMS_GEN_ITEM_ATTRIBUTES'') AND C.Segment6 =''E''; IF l_count > 0 THEN l_ret_sts :=''Y''; ELSE l_ret_sts :=''N''; END IF; ELSE  BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Held_For_Waca;'
, 'Eval_Od_Held_For_Waca',  TO_Date( '05/28/2007 01:39:33 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:39:33 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1049, 'HOLD', 'M', 'L', 'A', NULL, 1, NULL, NULL, 'N', NULL, 7, 'N', 'CREATE OR REPLACE FUNCTION Eval_Od_Non_Code_Hold_For_Fre( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER;  l_hold_period NUMBER;  l_holdexists_days NUMBER;  l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  l_ret_sts :=''Y''; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Non_Code_Hold_For_Fre;'
, 'Eval_Od_Non_Code_Hold_For_Fre',  TO_Date( '05/28/2007 01:40:07 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:40:07 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1016, 'HOLD', 'M', 'L', 'A', NULL, 1, NULL, NULL, 'N', NULL, 8, 'N', 'CREATE OR REPLACE FUNCTION Eval_Od_Pending_Collections( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER;  l_hold_period NUMBER;  l_holdexists_days NUMBER;  ln_rma_line_id NUMBER; l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  BEGIN SELECT TO_NUMBER(NVL(KFF.segment19,''0'')) INTO ln_rma_line_id FROM xx_om_lines_attributes_all KFF ,oe_order_lines L WHERE KFF.combination_id = L.attribute6  AND L.line_id  = DECODE(I_OrdLinId,0,L.line_id,I_OrdLinId) AND L.header_id = NVL(I_OrdHdrId,L.header_id); EXCEPTION WHEN NO_DATA_FOUND THEN ln_rma_line_id:=0; WHEN OTHERS THEN ln_rma_line_id:=0; END; IF ln_rma_line_id > 0 THEN SELECT COUNT(1) INTO l_count FROM rcv_shipment_headers RSH,rcv_shipment_lines RSL,oe_order_lines L ,oe_order_headers H WHERE L.line_id = ln_rma_line_id AND RSL.oe_order_header_id=L.header_id AND RSL.oe_order_line_id=L.line_id AND L.header_id=H.header_id AND RSH.shipment_header_id=RSL.shipment_header_id AND NVL(RSH.customer_id,-99)= NVL(H.sold_to_org_id,-99) AND RSH.receipt_num IS NOT NULL AND RSH.receipt_source_code=''CUSTOMER'' AND NVL(L.ordered_quantity,0)=(SELECT SUM(NVL(X.quantity_received,0)) FROM rcv_shipment_lines X WHERE RSL.shipment_header_id=RSH.shipment_header_id); IF NVL(l_count,0) = 0 THEN l_ret_sts :=''N''; ELSE l_ret_sts :=''Y''; END IF; END IF; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Pending_Collections;'
, 'Eval_Od_Pending_Collections',  TO_Date( '05/28/2007 01:40:20 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:40:20 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1007, 'HOLD', 'A', 'L', 'B', 141, 1, 1, NULL, 'N', NULL, 1, 'Y', 'CREATE OR REPLACE FUNCTION Eval_Od_Furniture_Review( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER; l_hold_period NUMBER; l_orgidm NUMBER; l_orgid NUMBER; l_holdexists_days NUMBER;  l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  SELECT COUNT(1) INTO l_count FROM oe_order_headers H,oe_order_lines L,mtl_item_categories I,mtl_categories_b C,mtl_category_sets S WHERE H.header_id = NVL(I_OrdHdrId,H.header_id) AND L.line_id = DECODE(I_OrdLinId,0,L.line_id,I_OrdLinId) AND H.header_id = L.Header_id AND L.inventory_item_id = I.inventory_item_id AND L.ship_from_org_id = I.organization_id AND I.category_id = C.category_id AND I.category_set_id = S.category_set_id AND C.structure_id = S. structure_id AND C.Segment1 =''1'' AND S.category_set_name =''Inventory''; BEGIN SELECT H.org_id INTO l_orgid FROM oe_order_headers H,oe_order_lines L WHERE H.header_id = NVL(I_OrdHdrId,H.header_id) AND L.line_id = DECODE(I_OrdLinId,0,L.line_id,I_OrdLinId) AND H.header_id = L.Header_id; EXCEPTION WHEN NO_DATA_FOUND THEN l_orgid:=NULL; WHEN OTHERS THEN l_orgid:=NULL; END; BEGIN SELECT NVL(M.org_id,0) INTO l_orgidm FROM Xx_Om_Od_Hold_Additional_Info M WHERE M.hold_id = I_HoldId; EXCEPTION WHEN NO_DATA_FOUND THEN l_orgidm:=NULL; WHEN OTHERS THEN l_orgidm:=NULL; END; IF NVL(l_orgidm,-1) = NVL(l_orgid,-9) THEN IF l_count > 0 THEN l_ret_sts :=''Y''; ELSE l_ret_sts :=''N''; END IF; END IF; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Furniture_Review;'
, 'Eval_Od_Furniture_Review',  TO_Date( '05/28/2007 01:33:43 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:33:43 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1010, 'HOLD', 'A', 'L', 'B', NULL, 1, 1, NULL, 'N', NULL, 2, 'Y', 'CREATE OR REPLACE FUNCTION Eval_Od_High_Returns_Problem( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER; l_hold_period NUMBER;  l_holdexists_days NUMBER;  l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  SELECT COUNT(1) INTO l_count FROM oe_order_headers H ,oe_order_lines L ,xx_od_high_risks_prod_tab P WHERE H.header_id = I_OrdHdrId AND H.header_id = L.header_id AND L.line_id = DECODE(I_OrdLinId,0,L.line_id,I_OrdLinId) AND L.inventory_item_id = P.inventory_item_id; IF l_count > 0 THEN l_ret_sts :=''Y''; ELSE l_ret_sts :=''N''; END IF; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_High_Returns_Problem;'
, 'Eval_Od_High_Returns_Problem',  TO_Date( '05/28/2007 01:34:20 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:34:20 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1013, 'HOLD', 'A', 'L', 'B', NULL, 1, 1, NULL, 'N', NULL, 3, 'Y', 'CREATE OR REPLACE FUNCTION Eval_Od_Waiting_For_Return( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER; l_hold_period NUMBER; l_holdexists_days NUMBER; ln_rma_line_id NUMBER; l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  BEGIN SELECT TO_NUMBER(NVL(KFF.segment19,''0'')) INTO ln_rma_line_id FROM xx_om_lines_attributes_all KFF ,oe_order_lines L WHERE KFF.combination_id = L.attribute6  AND L.line_id  = DECODE(I_OrdLinId,0,L.line_id,I_OrdLinId) AND L.header_id = NVL(I_OrdHdrId,L.header_id); EXCEPTION WHEN NO_DATA_FOUND THEN ln_rma_line_id:=0; WHEN OTHERS THEN ln_rma_line_id:=0; END; IF ln_rma_line_id > 0 THEN SELECT COUNT(1) INTO l_count FROM rcv_shipment_headers RSH,rcv_shipment_lines RSL,oe_order_lines L ,oe_order_headers H WHERE L.line_id = ln_rma_line_id AND RSL.oe_order_header_id=L.header_id AND RSL.oe_order_line_id=L.line_id AND L.header_id=H.header_id AND RSH.shipment_header_id=RSL.shipment_header_id AND NVL(RSH.customer_id,-99)= NVL(H.sold_to_org_id,-99) AND RSH.receipt_num IS NOT NULL AND RSH.receipt_source_code=''CUSTOMER'' AND NVL(L.ordered_quantity,0)=(SELECT SUM(NVL(X.quantity_received,0)) FROM rcv_shipment_lines X WHERE RSL.shipment_header_id=RSH.shipment_header_id); IF NVL(l_count,0) = 0 THEN l_ret_sts :=''Y''; ELSE l_ret_sts :=''N''; END IF; ELSE l_ret_sts :=''N''; END IF; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Waiting_For_Return;'
, 'Eval_Od_Waiting_For_Return',  TO_Date( '05/28/2007 01:34:39 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:34:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1048, 'HOLD', 'A', 'L', 'B', 141, 1, 1, NULL, 'N', NULL, 4, 'N', 'CREATE OR REPLACE FUNCTION Eval_Od_Held_For_Comments( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER, I_hdrline VARCHAR2) RETURN CHAR IS l_count NUMBER; l_hold_period NUMBER;  l_holdexists_days NUMBER;  l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  IF I_hdrline=''O'' THEN  SELECT COUNT(1) INTO l_count FROM oe_order_headers H,xx_om_headers_attributes_all KFF WHERE KFF.combination_id = H.attribute7 AND H.header_id = I_OrdHdrId AND KFF.segment1 IS NOT NULL; IF l_count > 0 THEN l_ret_sts :=''Y''; ELSE l_ret_sts :=''N''; END IF; ELSIF I_hdrline=''L'' THEN  SELECT COUNT(1) INTO l_count FROM oe_order_lines L,xx_om_lines_attributes_all KFF WHERE KFF.combination_id = L.attribute8 AND L.header_id = I_OrdHdrId AND L.line_id = DECODE(I_OrdLinId,0,L.line_id,I_OrdLinId) AND KFF.segment1 IS NOT NULL; IF l_count > 0 THEN l_ret_sts :=''Y''; ELSE l_ret_sts :=''N''; END IF; END IF; ELSE BEGIN SELECT TRUNC(SYSDATE) - NVL(TRUNC(H.creation_date),TRUNC(SYSDATE)) INTO l_holdexists_days FROM oe_hold_sources S ,oe_order_holds H ,oe_hold_definitions D WHERE S.hold_entity_code=''O'' AND S.hold_entity_id=I_OrdHdrId AND S.hold_id=I_holdid AND S.released_flag=''N'' AND H.hold_source_id=S.hold_source_id AND S.hold_id=D.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_holdexists_days:= NULL; WHEN OTHERS THEN  l_holdexists_days:= NULL; END; IF I_hdrline=''O'' THEN  BEGIN SELECT NVL(M.no_of_days,0) INTO l_hold_period FROM Xx_Om_Od_Hold_Additional_Info M WHERE M.hold_id=I_holdid AND apply_to_order_or_line=I_hdrline; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; END; ELSIF I_hdrline=''L'' THEN  BEGIN SELECT NVL(M.no_of_days,0) INTO l_hold_period FROM Xx_Om_Od_Hold_Additional_Info M WHERE M.hold_id=I_holdid AND apply_to_order_or_line=I_hdrline; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; END; END IF; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Held_For_Comments;'
, 'Eval_Od_Held_For_Comments',  TO_Date( '05/28/2007 01:34:53 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:34:53 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1081, 'HOLD', 'A', 'L', 'A', 141, 1, 1, NULL, 'N', NULL, 5, 'Y', 'CREATE OR REPLACE FUNCTION Eval_Od_Held_For_Crossdoc_Hol( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER;  l_hold_period NUMBER;  l_holdexists_days NUMBER;  l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  l_ret_sts :=''Y''; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Held_For_Crossdoc_Hol;'
, 'Eval_Od_Held_For_Crossdoc_Hol',  TO_Date( '05/28/2007 01:35:07 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:35:07 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1004, 'HOLD', 'A', 'L', 'A', NULL, 1, 1, NULL, 'N', NULL, 6, 'N', 'CREATE OR REPLACE FUNCTION Eval_Od_Dps_Print_Hold( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER; l_hold_period NUMBER;  l_holdexists_days NUMBER;  l_ret_sts VARCHAR2(1) :=''N'';  BEGIN  IF I_action =''APPLY'' THEN  SELECT COUNT(1) INTO l_count FROM oe_order_headers H,oe_order_lines L,xx_om_lines_attributes_all KFF WHERE H.header_id=NVL(I_OrdHdrId,H.header_id) AND L.line_id=DECODE(I_OrdLinId,0,L.line_id,I_OrdLinId) AND H.header_id=L.Header_id AND KFF.combination_id=L.attribute6 AND KFF.Segment7=''DPS''; IF l_count > 0 THEN l_ret_sts :=''Y''; ELSE l_ret_sts :=''N''; END IF; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts; EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Dps_Print_Hold;'
, 'Eval_Od_Dps_Print_Hold',  TO_Date( '05/28/2007 01:35:37 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:35:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
INSERT INTO XX_OM_OD_HOLD_ADDITIONAL_INFO ( HOLD_DEFINITION_ID, HOLD_ID, TYPE_CODE, HOLD_TYPE,
APPLY_TO_ORDER_OR_LINE, ORDER_BOOKING_STATUS, ORG_ID, NO_OF_DAYS, STOCK_RESERVED,
ESCALATION_NO_OF_DAYS, CREDIT_AUTHORIZATION, AUTHORITIES_TO_NOTIFY, PRIORITY, SEND_TO_POOL,
RULE_FUNCTION, RULE_FUNCTION_NAME, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE,
LAST_UPDATED_BY ) VALUES ( 
ln_hold_definition_id, 1001, 'HOLD', 'A', 'O', 'B', NULL, 1, 1, NULL, 'Y', NULL, 1, 'N', 'CREATE OR REPLACE FUNCTION Eval_Od_Customer_Request( I_action IN VARCHAR2, I_holdid IN NUMBER, I_OrdHdrId IN NUMBER, I_OrdLinId IN NUMBER) RETURN CHAR IS l_count NUMBER; l_hold_period NUMBER; l_holdexists_days NUMBER; l_ret_sts VARCHAR2(1) := ''N''; BEGIN IF I_action =''APPLY'' THEN l_ret_sts := ''Y''; ELSE BEGIN SELECT NVL(M.no_of_days,0) ,TRUNC(SYSDATE) - NVL(TRUNC(OH.creation_date),TRUNC(SYSDATE)) INTO l_hold_period ,l_holdexists_days FROM Xx_Om_Od_Hold_Additional_Info M,oe_order_holds OH,oe_hold_sources S,oe_hold_definitions D WHERE OH.header_id = NVL(I_OrdHdrId,OH.header_id) AND OH.hold_release_id IS NULL AND OH.released_flag =''N'' AND OH.hold_source_id = S.hold_source_id AND M.hold_id = I_holdid AND M.hold_id = D.hold_id AND D.hold_id = S.hold_id; EXCEPTION WHEN NO_DATA_FOUND THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; WHEN OTHERS THEN  l_hold_period:= NULL; l_holdexists_days:= NULL; END; IF NVL(l_holdexists_days,0) > NVL(l_hold_period,0) THEN l_ret_sts := ''Y'';  ELSE  l_ret_sts := ''N'';  END IF;  END IF; RETURN l_ret_sts;  EXCEPTION  WHEN OTHERS THEN  l_ret_sts:=''E''; RETURN l_ret_sts; END Eval_Od_Customer_Request;'
, 'Eval_Od_Customer_Request',  TO_Date( '05/28/2007 01:35:49 AM', 'MM/DD/YYYY HH:MI:SS AM')
, -1,  TO_Date( '05/28/2007 01:35:49 AM', 'MM/DD/YYYY HH:MI:SS AM'), -1); 
/
commit;
/ 

END;