<definitions
     name="DPSCancel_ClearStaging"
     targetNamespace="http://xmlns.oracle.com/DPSCancel_ClearStaging"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://schemas.oracle.com/bpel/extension"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/DPSCancel_ClearStaging"
    >
    <import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/DPSCancel_ClearStaging" schemaLocation="DPSCancel_ClearStaging.xsd"/>
        </schema>
    </types>
    <message name="DPSCancel_ClearStagingRequestMessage">
        <part name="payload" element="client:DPSCancel_ClearStagingProcessRequest"/>
    </message>
    <message name="DPSCancel_ClearStagingResponseMessage">
        <part name="payload" element="client:DPSCancel_ClearStagingProcessResponse"/>
    </message>
    <portType name="DPSCancel_ClearStaging">
        <operation name="process">
            <input message="client:DPSCancel_ClearStagingRequestMessage"/>
            <output message="client:DPSCancel_ClearStagingResponseMessage"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="DPSCancel_ClearStaging">
        <plnk:role name="DPSCancel_ClearStagingProvider">
            <plnk:portType name="client:DPSCancel_ClearStaging"/>
        </plnk:role>
    </plnk:partnerLinkType>
</definitions>
