package DBadapter2;

import java.util.Date;

public class RcvShipmentHeaders {

    private Integer shipmentHeaderId;
    private Date lastUpdateDate;
    private Integer lastUpdatedBy;
    private Date creationDate;
    private Integer createdBy;
    private Integer lastUpdateLogin;
    private String receiptSourceCode;
    private Integer vendorId;
    private Integer vendorSiteId;
    private Integer organizationId;
    private String shipmentNum;
    private String receiptNum;
    private Integer shipToLocationId;
    private String billOfLading;
    private String packingSlip;
    private Date shippedDate;
    private String freightCarrierCode;
    private Date expectedReceiptDate;
    private Integer employeeId;
    private Integer numOfContainers;
    private String waybillAirbillNum;
    private String comments;
    private String attributeCategory;
    private String attribute1;
    private String attribute2;
    private String attribute3;
    private String attribute4;
    private String attribute5;
    private String attribute6;
    private String attribute7;
    private String attribute8;
    private String attribute9;
    private String attribute10;
    private String attribute11;
    private String attribute12;
    private String attribute13;
    private String attribute14;
    private String attribute15;
    private String ussglTransactionCode;
    private String governmentContext;
    private Integer requestId;
    private Integer programApplicationId;
    private Integer programId;
    private Date programUpdateDate;
    private String asnType;
    private String ediControlNum;
    private Date noticeCreationDate;
    private Integer grossWeight;
    private String grossWeightUomCode;
    private Integer netWeight;
    private String netWeightUomCode;
    private Integer tarWeight;
    private String tarWeightUomCode;
    private String packagingCode;
    private String carrierMethod;
    private String carrierEquipment;
    private String carrierEquipmentNum;
    private String carrierEquipmentAlpha;
    private String specialHandlingCode;
    private String hazardCode;
    private String hazardClass;
    private String hazardDescription;
    private String freightTerms;
    private String freightBillNumber;
    private String invoiceNum;
    private Date invoiceDate;
    private Integer invoiceAmount;
    private String taxName;
    private Integer taxAmount;
    private Integer freightAmount;
    private String invoiceStatusCode;
    private String asnStatus;
    private String currencyCode;
    private String conversionRateType;
    private Integer conversionRate;
    private Date conversionDate;
    private Integer paymentTermsId;
    private String mrcConversionRateType;
    private String mrcConversionDate;
    private String mrcConversionRate;
    private Integer shipToOrgId;
    private Integer customerId;
    private Integer customerSiteId;
    private Integer remitToSiteId;


}
