<definitions
     name="svcMQPut"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/mq/headersvcMQPut/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/mq/headersvcMQPut/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:imp1="http://TargetNamespace.com/plWriteResponse"
     xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/mq/header"
    >
    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/mq/header" location="MQAdapterOutboundHeader.wsdl"/>
    <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://TargetNamespace.com/plWriteResponse" schemaLocation="I1026_MQ_Response.xsd" />
      </schema>
    </types>
    <message name="Response_msg">
        <part name="Response" element="imp1:Response"/>
    </message>
    <portType name="Enqueue_ptt">
        <operation name="Enqueue">
            <input message="tns:Response_msg"/>
        </operation>
    </portType>
    <binding name="Enqueue_binding" type="tns:Enqueue_ptt">
    <jca:binding 
          UITransmissionPrimitive="Enqueue" />
        <operation name="Enqueue">
      <jca:operation
          InteractionSpec="oracle.tip.adapter.mq.outbound.InteractionSpecImpl"
          QueueName="CREDIT_PROCESS_REPLY_QUEUE"
          MessageType="NORMAL"
          MessageFormat="NONE"
          Priority="AS_Q_DEF"
          Persistence="AS_Q_DEF"
          Expiry="NEVER"
          OpaqueSchema="false" >
      </jca:operation>
      <input>
        <jca:header message="hdr:OutboundHeader_msg" part="outboundHeader"/>
      </input>
        </operation>
    </binding>
    <service name="svcMQPut">
        <port name="Enqueue_pt" binding="tns:Enqueue_binding">
      <jca:address location="eis/mq/EBSAccountsReceivable" />
        </port>
    </service>
  <plt:partnerLinkType name="Enqueue_plt" >
    <plt:role name="Enqueue_role" >
      <plt:portType name="tns:Enqueue_ptt" />
    </plt:role>
  </plt:partnerLinkType>
</definitions>
