/*===========================================================================+
 |      Copyright (c) 2001 Oracle Corporation, Redwood Shores, CA, USA       |
 |                         All rights reserved.                              |
 +===========================================================================+
 |  HISTORY                                                                  |
 |  Aug-03   mkatraga Created                                                |
 |  Oct-07   Ashok Kumar T J                                                 |
 +===========================================================================*/

package od.oracle.apps.xxcrm.asn.common.customer.server;
import od.oracle.apps.xxcrm.asn.common.fwk.server.ODASNApplicationModuleImpl;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.apps.fnd.framework.server.OADBTransaction;
import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.OAFwkConstants;
import oracle.apps.fnd.common.MessageToken;
import oracle.apps.fnd.framework.OAException;
import oracle.apps.asn.common.server.PartyVOImpl;
import oracle.apps.asn.common.server.PartyVORowImpl;
import oracle.apps.asn.common.poplist.server.LookupsVOImpl;
import oracle.apps.asn.common.poplist.server.LookupsVORowImpl;

//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class ODOrgViewAMImpl extends ODASNApplicationModuleImpl
{
   public static final String RCS_ID="$Header: ODOrgViewAMImpl.java 115.8 2004/08/05 20:59:49 mkatraga ship $";
   public static final boolean RCS_ID_RECORDED =
        VersionInfo.recordClassVersion(RCS_ID, "od.oracle.apps.xxcrm.asn.common.customer.server");

  /**
   *
   * This is the default constructor (do not remove)
   */
  public ODOrgViewAMImpl()
  {
  }

/**
   *
   * Method for fetching the party name from the party identifier
   * @param partyId the customer party identifier
   */
  public String getPartyNameFromId(String partyId)
  {
    final String METHOD_NAME = "xxcrm.asn.common.customer.server.ODOrgViewAMImpl.getPartyNameFromId";
    OADBTransaction dbTrx = (OADBTransaction)getOADBTransaction();
    boolean isProcLogEnabled = dbTrx.isLoggingEnabled(OAFwkConstants.PROCEDURE);
    if (isProcLogEnabled)  {
      dbTrx.writeDiagnostics(METHOD_NAME, "Begin", OAFwkConstants.PROCEDURE);
      StringBuffer buf = new StringBuffer();
      buf.append("Input Parameters: partyId = ");
      buf.append(partyId);
      dbTrx.writeDiagnostics(METHOD_NAME,buf.toString(), OAFwkConstants.PROCEDURE);
    }

    PartyVOImpl vo = this.getPartyVO();
    if (vo == null)
    {
          MessageToken[] tokens = { new MessageToken("NAME", "PartyVO") };
          throw new OAException("ASN", "ASN_CMMN_OBJ_MISS_ERR", tokens);
    }
    vo.initQuery(partyId);

    String partyName = null;

    if ( vo != null && vo.isExecuted() )
    {

         PartyVORowImpl cRow = (PartyVORowImpl)vo.first();
         partyName = ((Object)cRow.getAttribute("PartyName")).toString();
    }

    if (isProcLogEnabled) {
      StringBuffer buf = new StringBuffer();
      buf.append("Output Parameters: partyName = ");
      buf.append(partyName);
      dbTrx.writeDiagnostics(METHOD_NAME,buf.toString(), OAFwkConstants.PROCEDURE);
      dbTrx.writeDiagnostics(METHOD_NAME, "End", OAFwkConstants.PROCEDURE);
    }

    return partyName;
  }
  /**
   *
   * Initializes the query for the customer actions poplist.
   *
   */
  public void initCustomerActionsQuery()
  {
    LookupsVOImpl vo = getLookupsVO();
    if (vo == null)
    {
        MessageToken[] tokens = { new MessageToken("NAME", "LookupsVO") };
        throw new OAException("ASN", "ASN_CMMN_OBJ_MISS_ERR", tokens);
    }
    vo.initQuery("ASN_CUSTOMER_ACTIONS", "0");

  }


  /**
   *
   * Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("od.oracle.apps.xxcrm.asn.common.customer.server", "ODOrgViewAMLocal");
  }

  /**
   *
   * Container's getter for PartyVO
   */
  public PartyVOImpl getPartyVO()
  {
    return (PartyVOImpl)findViewObject("PartyVO");
  }

  /**
   *
   * Container's getter for LookupsVO
   */
  public LookupsVOImpl getLookupsVO()
  {
    return (LookupsVOImpl)findViewObject("LookupsVO");
  }




}
