<?binding.jca UpdateTDSErrorLogEntries_db.jca?>
<wsdl:definitions name="UpdateTDSErrorLogEntries" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TDS/ModifyTDSErrorLogDetails/UpdateTDSErrorLogEntries" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TDS/ModifyTDSErrorLogDetails/UpdateTDSErrorLogEntries" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateTDSErrorLogEntries">
    <plt:partnerLinkType name="UpdateTDSErrorLogEntries_plt">
        <plt:role name="UpdateTDSErrorLogEntries_role">
            <plt:portType name="tns:UpdateTDSErrorLogEntries_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateTDSErrorLogEntries" schemaLocation="xsd/UpdateTDSErrorLogEntries_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="XxcomErrorLogCollection_msg">
        <wsdl:part name="XxcomErrorLogCollection" element="top:XxcomErrorLogCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateTDSErrorLogEntries_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:XxcomErrorLogCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
