DROP TYPE XX_GI_RECEIVING_PKG_ROWTYPE_2 FORCE; 
show errors
DROP TYPE XX_GI_RECEIVING_PKG_ROWTYPE_3 FORCE; 
show errors
DROP TYPE XX_GI_RECEIVING_PKG_DETAIL_R5 FORCE; 
show errors
DROP TYPE XX_GI_RECEIVING_PKG_DETAIL_T4 FORCE; 
show errors
DROP PACKAGE BPEL_PLPOPULATERCVXFRSTAGEPROC;
exit
