DROP TYPE XX_GI_RECEIVING_PKG_ROWTYPE_6 FORCE; 
show errors
DROP TYPE XX_GI_RECEIVING_PKG_ROWTYPE_7 FORCE; 
show errors
DROP TYPE XX_GI_RECEIVING_PKG_DETAIL_R9 FORCE; 
show errors
DROP TYPE XX_GI_RECEIVING_PKG_DETAIL_T8 FORCE; 
show errors
DROP PACKAGE BPEL_PLPOPULATERRCVPOSTAGEPROC;
exit
