-- Declare the SQL type for the PL/SQL type ROWTYPE_PL0
CREATE OR REPLACE TYPE XX_GI_RECEIVING_PKG_ROWTYPE_6 AS OBJECT (
      KEYREC_NBR NUMBER,
      LOC_NBR NUMBER,
      TYPE_CD VARCHAR2(2),
      STATUS_CD VARCHAR2(4),
      CARTON_CNT NUMBER,
      COMMENTS VARCHAR2(50),
      FREIGHT_CD VARCHAR2(2),
      FOB_CD VARCHAR2(2),
      FREIGHT_BILL_NBR VARCHAR2(15),
      CARRIER_NBR NUMBER,
      PROFORMA_NBR VARCHAR2(30),
      TOTAL_WEIGHT NUMBER,
      NEXT_AP_SEQ_NBR NUMBER,
      OB_USER_ID VARCHAR2(10),
      CREATED_BY NUMBER,
      CREATION_DATE DATE,
      LAST_UPDATED_BY NUMBER,
      LAST_UPDATE_DATE DATE,
      LAST_UPDATE_LOGIN NUMBER
);
/
show errors
-- Declare the SQL type for the PL/SQL type ROWTYPE_PL1
CREATE OR REPLACE TYPE XX_GI_RECEIVING_PKG_ROWTYPE_7 AS OBJECT (
      HEADER_INTERFACE_ID NUMBER,
      GROUP_ID NUMBER,
      EDI_CONTROL_NUM VARCHAR2(10),
      PROCESSING_STATUS_CODE VARCHAR2(25),
      RECEIPT_SOURCE_CODE VARCHAR2(25),
      ASN_TYPE VARCHAR2(25),
      TRANSACTION_TYPE VARCHAR2(25),
      AUTO_TRANSACT_CODE VARCHAR2(25),
      TEST_FLAG VARCHAR2(1),
      LAST_UPDATE_DATE DATE,
      LAST_UPDATED_BY NUMBER,
      LAST_UPDATE_LOGIN NUMBER,
      CREATION_DATE DATE,
      CREATED_BY NUMBER,
      NOTICE_CREATION_DATE DATE,
      SHIPMENT_NUM VARCHAR2(30),
      RECEIPT_NUM VARCHAR2(30),
      RECEIPT_HEADER_ID NUMBER,
      VENDOR_NAME VARCHAR2(240),
      VENDOR_NUM VARCHAR2(20),
      VENDOR_ID NUMBER,
      VENDOR_SITE_CODE VARCHAR2(35),
      VENDOR_SITE_ID NUMBER,
      FROM_ORGANIZATION_CODE VARCHAR2(3),
      FROM_ORGANIZATION_ID NUMBER,
      SHIP_TO_ORGANIZATION_CODE VARCHAR2(3),
      SHIP_TO_ORGANIZATION_ID NUMBER,
      LOCATION_CODE VARCHAR2(60),
      LOCATION_ID NUMBER,
      BILL_OF_LADING VARCHAR2(25),
      PACKING_SLIP VARCHAR2(25),
      SHIPPED_DATE DATE,
      FREIGHT_CARRIER_CODE VARCHAR2(25),
      EXPECTED_RECEIPT_DATE DATE,
      RECEIVER_ID NUMBER,
      NUM_OF_CONTAINERS NUMBER,
      WAYBILL_AIRBILL_NUM VARCHAR2(20),
      COMMENTS VARCHAR2(240),
      GROSS_WEIGHT NUMBER,
      GROSS_WEIGHT_UOM_CODE VARCHAR2(3),
      NET_WEIGHT NUMBER,
      NET_WEIGHT_UOM_CODE VARCHAR2(3),
      TAR_WEIGHT NUMBER,
      TAR_WEIGHT_UOM_CODE VARCHAR2(3),
      PACKAGING_CODE VARCHAR2(5),
      CARRIER_METHOD VARCHAR2(2),
      CARRIER_EQUIPMENT VARCHAR2(10),
      SPECIAL_HANDLING_CODE VARCHAR2(3),
      HAZARD_CODE VARCHAR2(1),
      HAZARD_CLASS VARCHAR2(4),
      HAZARD_DESCRIPTION VARCHAR2(80),
      FREIGHT_TERMS VARCHAR2(25),
      FREIGHT_BILL_NUMBER VARCHAR2(35),
      INVOICE_NUM VARCHAR2(30),
      INVOICE_DATE DATE,
      TOTAL_INVOICE_AMOUNT NUMBER,
      TAX_NAME VARCHAR2(15),
      TAX_AMOUNT NUMBER,
      FREIGHT_AMOUNT NUMBER,
      CURRENCY_CODE VARCHAR2(15),
      CONVERSION_RATE_TYPE VARCHAR2(30),
      CONVERSION_RATE NUMBER,
      CONVERSION_RATE_DATE DATE,
      PAYMENT_TERMS_NAME VARCHAR2(50),
      PAYMENT_TERMS_ID NUMBER,
      ATTRIBUTE_CATEGORY VARCHAR2(30),
      ATTRIBUTE1 VARCHAR2(150),
      ATTRIBUTE2 VARCHAR2(150),
      ATTRIBUTE3 VARCHAR2(150),
      ATTRIBUTE4 VARCHAR2(150),
      ATTRIBUTE5 VARCHAR2(150),
      ATTRIBUTE6 VARCHAR2(150),
      ATTRIBUTE7 VARCHAR2(150),
      ATTRIBUTE9 VARCHAR2(150),
      ATTRIBUTE10 VARCHAR2(150),
      ATTRIBUTE11 VARCHAR2(150),
      ATTRIBUTE12 VARCHAR2(150),
      ATTRIBUTE13 VARCHAR2(150),
      ATTRIBUTE14 VARCHAR2(150),
      ATTRIBUTE15 VARCHAR2(150),
      USGGL_TRANSACTION_CODE VARCHAR2(30),
      EMPLOYEE_NAME VARCHAR2(240),
      EMPLOYEE_ID NUMBER,
      INVOICE_STATUS_CODE VARCHAR2(25),
      VALIDATION_FLAG VARCHAR2(1),
      PROCESSING_REQUEST_ID NUMBER,
      CUSTOMER_ACCOUNT_NUMBER NUMBER,
      CUSTOMER_ID NUMBER,
      CUSTOMER_SITE_ID NUMBER,
      CUSTOMER_PARTY_NAME VARCHAR2(360),
      REMIT_TO_SITE_ID NUMBER,
      TRANSACTION_DATE DATE,
      ORG_ID NUMBER,
      OPERATING_UNIT VARCHAR2(240),
      SHIP_FROM_LOCATION_ID NUMBER,
      PERFORMANCE_PERIOD_FROM DATE,
      PERFORMANCE_PERIOD_TO DATE,
      REQUEST_DATE DATE,
      SHIP_FROM_LOCATION_CODE VARCHAR2(30),
      OD_RCV_STATUS_FLAG VARCHAR2(4),
      OD_RCV_FIRST_REC_TIME DATE,
      ATTRIBUTE8 VARCHAR2(150),
      OD_RCV_ERROR_DESCRIPTION VARCHAR2(150),
      LEGACY_TRANSACTION_TYPE VARCHAR2(30),
      LOC_NBR NUMBER
);
/
show errors
-- Declare the SQL type for the PL/SQL type XX_GI_RECEIVING_PKG.DETAIL_REC_TYPE
CREATE OR REPLACE TYPE XX_GI_RECEIVING_PKG_DETAIL_R9 AS OBJECT (
      INTERFACE_TRANSACTION_ID NUMBER,
      GROUP_ID NUMBER,
      LAST_UPDATE_DATE DATE,
      LAST_UPDATED_BY NUMBER,
      CREATION_DATE DATE,
      CREATED_BY NUMBER,
      LAST_UPDATE_LOGIN NUMBER,
      REQUEST_ID NUMBER,
      PROGRAM_APPLICATION_ID NUMBER,
      PROGRAM_ID NUMBER,
      PROGRAM_UPDATE_DATE DATE,
      TRANSACTION_TYPE VARCHAR2(25),
      TRANSACTION_DATE DATE,
      PROCESSING_STATUS_CODE VARCHAR2(25),
      PROCESSING_MODE_CODE VARCHAR2(25),
      PROCESSING_REQUEST_ID NUMBER,
      TRANSACTION_STATUS_CODE VARCHAR2(25),
      CATEGORY_ID NUMBER,
      QUANTITY NUMBER,
      UNIT_OF_MEASURE VARCHAR2(25),
      INTERFACE_SOURCE_CODE VARCHAR2(25),
      INTERFACE_SOURCE_LINE_ID NUMBER,
      INV_TRANSACTION_ID NUMBER,
      ITEM_ID NUMBER,
      ITEM_DESCRIPTION VARCHAR2(240),
      ITEM_REVISION VARCHAR2(3),
      UOM_CODE VARCHAR2(3),
      EMPLOYEE_ID NUMBER,
      AUTO_TRANSACT_CODE VARCHAR2(25),
      SHIPMENT_HEADER_ID NUMBER,
      SHIPMENT_LINE_ID NUMBER,
      SHIP_TO_LOCATION_ID NUMBER,
      PRIMARY_QUANTITY NUMBER,
      PRIMARY_UNIT_OF_MEASURE VARCHAR2(25),
      RECEIPT_SOURCE_CODE VARCHAR2(25),
      VENDOR_ID NUMBER,
      VENDOR_SITE_ID NUMBER,
      FROM_ORGANIZATION_ID NUMBER,
      FROM_SUBINVENTORY VARCHAR2(10),
      TO_ORGANIZATION_ID NUMBER,
      INTRANSIT_OWNING_ORG_ID NUMBER,
      ROUTING_HEADER_ID NUMBER,
      ROUTING_STEP_ID NUMBER,
      SOURCE_DOCUMENT_CODE VARCHAR2(25),
      PARENT_TRANSACTION_ID NUMBER,
      PO_HEADER_ID NUMBER,
      PO_REVISION_NUM NUMBER,
      PO_RELEASE_ID NUMBER,
      PO_LINE_ID NUMBER,
      PO_LINE_LOCATION_ID NUMBER,
      PO_UNIT_PRICE NUMBER,
      CURRENCY_CODE VARCHAR2(15),
      CURRENCY_CONVERSION_TYPE VARCHAR2(30),
      CURRENCY_CONVERSION_RATE NUMBER,
      CURRENCY_CONVERSION_DATE DATE,
      PO_DISTRIBUTION_ID NUMBER,
      REQUISITION_LINE_ID NUMBER,
      REQ_DISTRIBUTION_ID NUMBER,
      CHARGE_ACCOUNT_ID NUMBER,
      SUBSTITUTE_UNORDERED_CODE VARCHAR2(25),
      RECEIPT_EXCEPTION_FLAG VARCHAR2(1),
      ACCRUAL_STATUS_CODE VARCHAR2(25),
      INSPECTION_STATUS_CODE VARCHAR2(25),
      INSPECTION_QUALITY_CODE VARCHAR2(25),
      DESTINATION_TYPE_CODE VARCHAR2(25),
      DELIVER_TO_PERSON_ID NUMBER,
      LOCATION_ID NUMBER,
      DELIVER_TO_LOCATION_ID NUMBER,
      SUBINVENTORY VARCHAR2(10),
      LOCATOR_ID NUMBER,
      WIP_ENTITY_ID NUMBER,
      WIP_LINE_ID NUMBER,
      DEPARTMENT_CODE VARCHAR2(10),
      WIP_REPETITIVE_SCHEDULE_ID NUMBER,
      WIP_OPERATION_SEQ_NUM NUMBER,
      WIP_RESOURCE_SEQ_NUM NUMBER,
      BOM_RESOURCE_ID NUMBER,
      SHIPMENT_NUM VARCHAR2(30),
      FREIGHT_CARRIER_CODE VARCHAR2(25),
      BILL_OF_LADING VARCHAR2(25),
      PACKING_SLIP VARCHAR2(25),
      SHIPPED_DATE DATE,
      EXPECTED_RECEIPT_DATE DATE,
      ACTUAL_COST NUMBER,
      TRANSFER_COST NUMBER,
      TRANSPORTATION_COST NUMBER,
      TRANSPORTATION_ACCOUNT_ID NUMBER,
      NUM_OF_CONTAINERS NUMBER,
      WAYBILL_AIRBILL_NUM VARCHAR2(20),
      VENDOR_ITEM_NUM VARCHAR2(25),
      VENDOR_LOT_NUM VARCHAR2(30),
      RMA_REFERENCE VARCHAR2(30),
      COMMENTS VARCHAR2(240),
      ATTRIBUTE_CATEGORY VARCHAR2(30),
      ATTRIBUTE1 VARCHAR2(150),
      ATTRIBUTE2 VARCHAR2(150),
      ATTRIBUTE3 VARCHAR2(150),
      ATTRIBUTE4 VARCHAR2(150),
      ATTRIBUTE5 VARCHAR2(150),
      ATTRIBUTE6 VARCHAR2(150),
      ATTRIBUTE7 VARCHAR2(150),
      ATTRIBUTE9 VARCHAR2(150),
      ATTRIBUTE10 VARCHAR2(150),
      ATTRIBUTE11 VARCHAR2(150),
      ATTRIBUTE12 VARCHAR2(150),
      ATTRIBUTE13 VARCHAR2(150),
      ATTRIBUTE14 VARCHAR2(150),
      ATTRIBUTE15 VARCHAR2(150),
      SHIP_HEAD_ATTRIBUTE_CATEGORY VARCHAR2(30),
      SHIP_HEAD_ATTRIBUTE1 VARCHAR2(150),
      SHIP_HEAD_ATTRIBUTE2 VARCHAR2(150),
      SHIP_HEAD_ATTRIBUTE3 VARCHAR2(150),
      SHIP_HEAD_ATTRIBUTE4 VARCHAR2(150),
      SHIP_HEAD_ATTRIBUTE5 VARCHAR2(150),
      SHIP_HEAD_ATTRIBUTE6 VARCHAR2(150),
      SHIP_HEAD_ATTRIBUTE7 VARCHAR2(150),
      SHIP_HEAD_ATTRIBUTE8 VARCHAR2(150),
      SHIP_HEAD_ATTRIBUTE9 VARCHAR2(150),
      SHIP_HEAD_ATTRIBUTE10 VARCHAR2(150),
      SHIP_HEAD_ATTRIBUTE11 VARCHAR2(150),
      SHIP_HEAD_ATTRIBUTE12 VARCHAR2(150),
      SHIP_HEAD_ATTRIBUTE13 VARCHAR2(150),
      SHIP_HEAD_ATTRIBUTE14 VARCHAR2(150),
      SHIP_HEAD_ATTRIBUTE15 VARCHAR2(150),
      SHIP_LINE_ATTRIBUTE_CATEGORY VARCHAR2(30),
      SHIP_LINE_ATTRIBUTE1 VARCHAR2(150),
      SHIP_LINE_ATTRIBUTE2 VARCHAR2(150),
      SHIP_LINE_ATTRIBUTE3 VARCHAR2(150),
      SHIP_LINE_ATTRIBUTE4 VARCHAR2(150),
      SHIP_LINE_ATTRIBUTE5 VARCHAR2(150),
      SHIP_LINE_ATTRIBUTE6 VARCHAR2(150),
      SHIP_LINE_ATTRIBUTE7 VARCHAR2(150),
      SHIP_LINE_ATTRIBUTE8 VARCHAR2(150),
      SHIP_LINE_ATTRIBUTE9 VARCHAR2(150),
      SHIP_LINE_ATTRIBUTE10 VARCHAR2(150),
      SHIP_LINE_ATTRIBUTE11 VARCHAR2(150),
      SHIP_LINE_ATTRIBUTE12 VARCHAR2(150),
      SHIP_LINE_ATTRIBUTE13 VARCHAR2(150),
      SHIP_LINE_ATTRIBUTE14 VARCHAR2(150),
      SHIP_LINE_ATTRIBUTE15 VARCHAR2(150),
      USSGL_TRANSACTION_CODE VARCHAR2(30),
      GOVERNMENT_CONTEXT VARCHAR2(30),
      REASON_ID NUMBER,
      DESTINATION_CONTEXT VARCHAR2(30),
      SOURCE_DOC_QUANTITY NUMBER,
      SOURCE_DOC_UNIT_OF_MEASURE VARCHAR2(25),
      MOVEMENT_ID NUMBER,
      HEADER_INTERFACE_ID NUMBER,
      VENDOR_CUM_SHIPPED_QTY NUMBER,
      ITEM_NUM VARCHAR2(81),
      DOCUMENT_NUM VARCHAR2(30),
      DOCUMENT_LINE_NUM NUMBER,
      TRUCK_NUM VARCHAR2(35),
      SHIP_TO_LOCATION_CODE VARCHAR2(60),
      CONTAINER_NUM VARCHAR2(35),
      SUBSTITUTE_ITEM_NUM VARCHAR2(81),
      NOTICE_UNIT_PRICE NUMBER,
      ITEM_CATEGORY VARCHAR2(81),
      LOCATION_CODE VARCHAR2(60),
      VENDOR_NAME VARCHAR2(240),
      VENDOR_NUM VARCHAR2(30),
      VENDOR_SITE_CODE VARCHAR2(15),
      FROM_ORGANIZATION_CODE VARCHAR2(3),
      TO_ORGANIZATION_CODE VARCHAR2(3),
      INTRANSIT_OWNING_ORG_CODE VARCHAR2(3),
      ROUTING_CODE VARCHAR2(30),
      ROUTING_STEP VARCHAR2(30),
      RELEASE_NUM NUMBER,
      DOCUMENT_SHIPMENT_LINE_NUM NUMBER,
      DOCUMENT_DISTRIBUTION_NUM NUMBER,
      DELIVER_TO_PERSON_NAME VARCHAR2(240),
      DELIVER_TO_LOCATION_CODE VARCHAR2(60),
      USE_MTL_LOT NUMBER,
      USE_MTL_SERIAL NUMBER,
      LOCATOR VARCHAR2(81),
      REASON_NAME VARCHAR2(30),
      VALIDATION_FLAG VARCHAR2(1),
      SUBSTITUTE_ITEM_ID NUMBER,
      QUANTITY_SHIPPED NUMBER,
      QUANTITY_INVOICED NUMBER,
      TAX_NAME VARCHAR2(15),
      TAX_AMOUNT NUMBER,
      REQ_NUM VARCHAR2(25),
      REQ_LINE_NUM NUMBER,
      REQ_DISTRIBUTION_NUM NUMBER,
      WIP_ENTITY_NAME VARCHAR2(24),
      WIP_LINE_CODE VARCHAR2(10),
      RESOURCE_CODE VARCHAR2(30),
      SHIPMENT_LINE_STATUS_CODE VARCHAR2(25),
      BARCODE_LABEL VARCHAR2(35),
      TRANSFER_PERCENTAGE NUMBER,
      QA_COLLECTION_ID NUMBER,
      COUNTRY_OF_ORIGIN_CODE VARCHAR2(2),
      OE_ORDER_HEADER_ID NUMBER,
      OE_ORDER_LINE_ID NUMBER,
      CUSTOMER_ID NUMBER,
      CUSTOMER_SITE_ID NUMBER,
      CUSTOMER_ITEM_NUM VARCHAR2(50),
      CREATE_DEBIT_MEMO_FLAG VARCHAR2(1),
      PUT_AWAY_RULE_ID NUMBER,
      PUT_AWAY_STRATEGY_ID NUMBER,
      LPN_ID NUMBER,
      TRANSFER_LPN_ID NUMBER,
      COST_GROUP_ID NUMBER,
      MOBILE_TXN VARCHAR2(2),
      MMTT_TEMP_ID NUMBER,
      TRANSFER_COST_GROUP_ID NUMBER,
      SECONDARY_QUANTITY NUMBER,
      SECONDARY_UNIT_OF_MEASURE VARCHAR2(25),
      SECONDARY_UOM_CODE VARCHAR2(3),
      QC_GRADE VARCHAR2(150),
      FROM_LOCATOR VARCHAR2(81),
      FROM_LOCATOR_ID NUMBER,
      PARENT_SOURCE_TRANSACTION_NUM VARCHAR2(25),
      INTERFACE_AVAILABLE_QTY NUMBER,
      INTERFACE_TRANSACTION_QTY NUMBER,
      INTERFACE_AVAILABLE_AMT NUMBER,
      INTERFACE_TRANSACTION_AMT NUMBER,
      LICENSE_PLATE_NUMBER VARCHAR2(30),
      SOURCE_TRANSACTION_NUM VARCHAR2(25),
      TRANSFER_LICENSE_PLATE_NUMBER VARCHAR2(30),
      LPN_GROUP_ID NUMBER,
      ORDER_TRANSACTION_ID NUMBER,
      CUSTOMER_ACCOUNT_NUMBER NUMBER,
      CUSTOMER_PARTY_NAME VARCHAR2(360),
      OE_ORDER_LINE_NUM NUMBER,
      OE_ORDER_NUM NUMBER,
      PARENT_INTERFACE_TXN_ID NUMBER,
      CUSTOMER_ITEM_ID NUMBER,
      AMOUNT NUMBER,
      JOB_ID NUMBER,
      TIMECARD_ID NUMBER,
      TIMECARD_OVN NUMBER,
      ERECORD_ID NUMBER,
      PROJECT_ID NUMBER,
      TASK_ID NUMBER,
      ASN_ATTACH_ID NUMBER,
      ORG_ID NUMBER,
      OPERATING_UNIT VARCHAR2(240),
      REQUESTED_AMOUNT NUMBER,
      MATERIAL_STORED_AMOUNT NUMBER,
      AMOUNT_SHIPPED NUMBER,
      MATCHING_BASIS VARCHAR2(30),
      REPLENISH_ORDER_LINE_ID NUMBER,
      E0346_STATUS_FLAG VARCHAR2(1),
      OD_RCV_ERROR_DESCRIPTION VARCHAR2(2000),
      ATTRIBUTE8 VARCHAR2(150),
      OD_RVC_CORRECTION_FLAG VARCHAR2(10),
      OD_RCV_STATUS_FLAG VARCHAR2(10),
      LEGACY_TRANSACTION_TYPE VARCHAR2(30)
);
/
show errors
CREATE OR REPLACE TYPE XX_GI_RECEIVING_PKG_DETAIL_T8 AS TABLE OF XX_GI_RECEIVING_PKG_DETAIL_R9; 
/
show errors
-- Declare package containing conversion functions between SQL and PL/SQL types
CREATE OR REPLACE PACKAGE BPEL_PLPOPULATERRCVPOSTAGEPROC AS
	-- Redefine a PL/SQL RECORD type originally defined via CURSOR%ROWTYPE
	TYPE ROWTYPE_PL0 IS RECORD (
		KEYREC_NBR NUMBER,
		LOC_NBR NUMBER,
		TYPE_CD VARCHAR2(2),
		STATUS_CD VARCHAR2(4),
		CARTON_CNT NUMBER,
		COMMENTS VARCHAR2(50),
		FREIGHT_CD VARCHAR2(2),
		FOB_CD VARCHAR2(2),
		FREIGHT_BILL_NBR VARCHAR2(15),
		CARRIER_NBR NUMBER,
		PROFORMA_NBR VARCHAR2(30),
		TOTAL_WEIGHT NUMBER,
		NEXT_AP_SEQ_NBR NUMBER,
		OB_USER_ID VARCHAR2(10),
		CREATED_BY NUMBER,
		CREATION_DATE DATE,
		LAST_UPDATED_BY NUMBER,
		LAST_UPDATE_DATE DATE,
		LAST_UPDATE_LOGIN NUMBER);
	-- Declare the conversion functions the PL/SQL type ROWTYPE_PL0
	FUNCTION PL_TO_SQL8(aPlsqlItem ROWTYPE_PL0)
 	RETURN XX_GI_RECEIVING_PKG_ROWTYPE_6;
	FUNCTION SQL_TO_PL8(aSqlItem XX_GI_RECEIVING_PKG_ROWTYPE_6)
	RETURN ROWTYPE_PL0;
	-- Redefine a PL/SQL RECORD type originally defined via CURSOR%ROWTYPE
	TYPE ROWTYPE_PL1 IS RECORD (
		HEADER_INTERFACE_ID NUMBER,
		GROUP_ID NUMBER,
		EDI_CONTROL_NUM VARCHAR2(10),
		PROCESSING_STATUS_CODE VARCHAR2(25),
		RECEIPT_SOURCE_CODE VARCHAR2(25),
		ASN_TYPE VARCHAR2(25),
		TRANSACTION_TYPE VARCHAR2(25),
		AUTO_TRANSACT_CODE VARCHAR2(25),
		TEST_FLAG VARCHAR2(1),
		LAST_UPDATE_DATE DATE,
		LAST_UPDATED_BY NUMBER,
		LAST_UPDATE_LOGIN NUMBER,
		CREATION_DATE DATE,
		CREATED_BY NUMBER,
		NOTICE_CREATION_DATE DATE,
		SHIPMENT_NUM VARCHAR2(30),
		RECEIPT_NUM VARCHAR2(30),
		RECEIPT_HEADER_ID NUMBER,
		VENDOR_NAME VARCHAR2(240),
		VENDOR_NUM VARCHAR2(20),
		VENDOR_ID NUMBER,
		VENDOR_SITE_CODE VARCHAR2(35),
		VENDOR_SITE_ID NUMBER,
		FROM_ORGANIZATION_CODE VARCHAR2(3),
		FROM_ORGANIZATION_ID NUMBER,
		SHIP_TO_ORGANIZATION_CODE VARCHAR2(3),
		SHIP_TO_ORGANIZATION_ID NUMBER,
		LOCATION_CODE VARCHAR2(60),
		LOCATION_ID NUMBER,
		BILL_OF_LADING VARCHAR2(25),
		PACKING_SLIP VARCHAR2(25),
		SHIPPED_DATE DATE,
		FREIGHT_CARRIER_CODE VARCHAR2(25),
		EXPECTED_RECEIPT_DATE DATE,
		RECEIVER_ID NUMBER,
		NUM_OF_CONTAINERS NUMBER,
		WAYBILL_AIRBILL_NUM VARCHAR2(20),
		COMMENTS VARCHAR2(240),
		GROSS_WEIGHT NUMBER,
		GROSS_WEIGHT_UOM_CODE VARCHAR2(3),
		NET_WEIGHT NUMBER,
		NET_WEIGHT_UOM_CODE VARCHAR2(3),
		TAR_WEIGHT NUMBER,
		TAR_WEIGHT_UOM_CODE VARCHAR2(3),
		PACKAGING_CODE VARCHAR2(5),
		CARRIER_METHOD VARCHAR2(2),
		CARRIER_EQUIPMENT VARCHAR2(10),
		SPECIAL_HANDLING_CODE VARCHAR2(3),
		HAZARD_CODE VARCHAR2(1),
		HAZARD_CLASS VARCHAR2(4),
		HAZARD_DESCRIPTION VARCHAR2(80),
		FREIGHT_TERMS VARCHAR2(25),
		FREIGHT_BILL_NUMBER VARCHAR2(35),
		INVOICE_NUM VARCHAR2(30),
		INVOICE_DATE DATE,
		TOTAL_INVOICE_AMOUNT NUMBER,
		TAX_NAME VARCHAR2(15),
		TAX_AMOUNT NUMBER,
		FREIGHT_AMOUNT NUMBER,
		CURRENCY_CODE VARCHAR2(15),
		CONVERSION_RATE_TYPE VARCHAR2(30),
		CONVERSION_RATE NUMBER,
		CONVERSION_RATE_DATE DATE,
		PAYMENT_TERMS_NAME VARCHAR2(50),
		PAYMENT_TERMS_ID NUMBER,
		ATTRIBUTE_CATEGORY VARCHAR2(30),
		ATTRIBUTE1 VARCHAR2(150),
		ATTRIBUTE2 VARCHAR2(150),
		ATTRIBUTE3 VARCHAR2(150),
		ATTRIBUTE4 VARCHAR2(150),
		ATTRIBUTE5 VARCHAR2(150),
		ATTRIBUTE6 VARCHAR2(150),
		ATTRIBUTE7 VARCHAR2(150),
		ATTRIBUTE9 VARCHAR2(150),
		ATTRIBUTE10 VARCHAR2(150),
		ATTRIBUTE11 VARCHAR2(150),
		ATTRIBUTE12 VARCHAR2(150),
		ATTRIBUTE13 VARCHAR2(150),
		ATTRIBUTE14 VARCHAR2(150),
		ATTRIBUTE15 VARCHAR2(150),
		USGGL_TRANSACTION_CODE VARCHAR2(30),
		EMPLOYEE_NAME VARCHAR2(240),
		EMPLOYEE_ID NUMBER,
		INVOICE_STATUS_CODE VARCHAR2(25),
		VALIDATION_FLAG VARCHAR2(1),
		PROCESSING_REQUEST_ID NUMBER,
		CUSTOMER_ACCOUNT_NUMBER NUMBER,
		CUSTOMER_ID NUMBER,
		CUSTOMER_SITE_ID NUMBER,
		CUSTOMER_PARTY_NAME VARCHAR2(360),
		REMIT_TO_SITE_ID NUMBER,
		TRANSACTION_DATE DATE,
		ORG_ID NUMBER,
		OPERATING_UNIT VARCHAR2(240),
		SHIP_FROM_LOCATION_ID NUMBER,
		PERFORMANCE_PERIOD_FROM DATE,
		PERFORMANCE_PERIOD_TO DATE,
		REQUEST_DATE DATE,
		SHIP_FROM_LOCATION_CODE VARCHAR2(30),
		OD_RCV_STATUS_FLAG VARCHAR2(4),
		OD_RCV_FIRST_REC_TIME DATE,
		ATTRIBUTE8 VARCHAR2(150),
		OD_RCV_ERROR_DESCRIPTION VARCHAR2(150),
		LEGACY_TRANSACTION_TYPE VARCHAR2(30),
		LOC_NBR NUMBER);
	-- Declare the conversion functions the PL/SQL type ROWTYPE_PL1
	FUNCTION PL_TO_SQL9(aPlsqlItem ROWTYPE_PL1)
 	RETURN XX_GI_RECEIVING_PKG_ROWTYPE_7;
	FUNCTION SQL_TO_PL9(aSqlItem XX_GI_RECEIVING_PKG_ROWTYPE_7)
	RETURN ROWTYPE_PL1;
	-- Declare the conversion functions the PL/SQL type XX_GI_RECEIVING_PKG.DETAIL_REC_TYPE
	FUNCTION PL_TO_SQL11(aPlsqlItem XX_GI_RECEIVING_PKG.DETAIL_REC_TYPE)
 	RETURN XX_GI_RECEIVING_PKG_DETAIL_R9;
	FUNCTION SQL_TO_PL11(aSqlItem XX_GI_RECEIVING_PKG_DETAIL_R9)
	RETURN XX_GI_RECEIVING_PKG.DETAIL_REC_TYPE;
	-- Declare the conversion functions the PL/SQL type XX_GI_RECEIVING_PKG.DETAIL_TBL_TYPE
	FUNCTION PL_TO_SQL10(aPlsqlItem XX_GI_RECEIVING_PKG.DETAIL_TBL_TYPE)
 	RETURN XX_GI_RECEIVING_PKG_DETAIL_T8;
	FUNCTION SQL_TO_PL10(aSqlItem XX_GI_RECEIVING_PKG_DETAIL_T8)
	RETURN XX_GI_RECEIVING_PKG.DETAIL_TBL_TYPE;
   PROCEDURE XX_GI_RECEIVING_PKG$POPULATE_ (X_KEYREC_REC IN OUT XX_GI_RECEIVING_PKG_ROWTYPE_6,X_HEADER_REC IN OUT XX_GI_RECEIVING_PKG_ROWTYPE_7,X_DETAIL_TBL IN OUT XX_GI_RECEIVING_PKG_DETAIL_T8,X_RETURN_STATUS OUT VARCHAR2,X_RETURN_MESSAGE OUT VARCHAR2);
END BPEL_PLPOPULATERRCVPOSTAGEPROC;
/
show errors
CREATE OR REPLACE PACKAGE BODY BPEL_PLPOPULATERRCVPOSTAGEPROC IS
	FUNCTION PL_TO_SQL8(aPlsqlItem ROWTYPE_PL0)
 	RETURN XX_GI_RECEIVING_PKG_ROWTYPE_6 IS 
	aSqlItem XX_GI_RECEIVING_PKG_ROWTYPE_6; 
	BEGIN 
		-- initialize the object
		aSqlItem := XX_GI_RECEIVING_PKG_ROWTYPE_6(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
		aSqlItem.KEYREC_NBR := aPlsqlItem.KEYREC_NBR;
		aSqlItem.LOC_NBR := aPlsqlItem.LOC_NBR;
		aSqlItem.TYPE_CD := aPlsqlItem.TYPE_CD;
		aSqlItem.STATUS_CD := aPlsqlItem.STATUS_CD;
		aSqlItem.CARTON_CNT := aPlsqlItem.CARTON_CNT;
		aSqlItem.COMMENTS := aPlsqlItem.COMMENTS;
		aSqlItem.FREIGHT_CD := aPlsqlItem.FREIGHT_CD;
		aSqlItem.FOB_CD := aPlsqlItem.FOB_CD;
		aSqlItem.FREIGHT_BILL_NBR := aPlsqlItem.FREIGHT_BILL_NBR;
		aSqlItem.CARRIER_NBR := aPlsqlItem.CARRIER_NBR;
		aSqlItem.PROFORMA_NBR := aPlsqlItem.PROFORMA_NBR;
		aSqlItem.TOTAL_WEIGHT := aPlsqlItem.TOTAL_WEIGHT;
		aSqlItem.NEXT_AP_SEQ_NBR := aPlsqlItem.NEXT_AP_SEQ_NBR;
		aSqlItem.OB_USER_ID := aPlsqlItem.OB_USER_ID;
		aSqlItem.CREATED_BY := aPlsqlItem.CREATED_BY;
		aSqlItem.CREATION_DATE := aPlsqlItem.CREATION_DATE;
		aSqlItem.LAST_UPDATED_BY := aPlsqlItem.LAST_UPDATED_BY;
		aSqlItem.LAST_UPDATE_DATE := aPlsqlItem.LAST_UPDATE_DATE;
		aSqlItem.LAST_UPDATE_LOGIN := aPlsqlItem.LAST_UPDATE_LOGIN;
		RETURN aSqlItem;
	END PL_TO_SQL8;
	FUNCTION SQL_TO_PL8(aSqlItem XX_GI_RECEIVING_PKG_ROWTYPE_6) 
	RETURN ROWTYPE_PL0 IS 
	aPlsqlItem ROWTYPE_PL0; 
	BEGIN 
		aPlsqlItem.KEYREC_NBR := aSqlItem.KEYREC_NBR;
		aPlsqlItem.LOC_NBR := aSqlItem.LOC_NBR;
		aPlsqlItem.TYPE_CD := aSqlItem.TYPE_CD;
		aPlsqlItem.STATUS_CD := aSqlItem.STATUS_CD;
		aPlsqlItem.CARTON_CNT := aSqlItem.CARTON_CNT;
		aPlsqlItem.COMMENTS := aSqlItem.COMMENTS;
		aPlsqlItem.FREIGHT_CD := aSqlItem.FREIGHT_CD;
		aPlsqlItem.FOB_CD := aSqlItem.FOB_CD;
		aPlsqlItem.FREIGHT_BILL_NBR := aSqlItem.FREIGHT_BILL_NBR;
		aPlsqlItem.CARRIER_NBR := aSqlItem.CARRIER_NBR;
		aPlsqlItem.PROFORMA_NBR := aSqlItem.PROFORMA_NBR;
		aPlsqlItem.TOTAL_WEIGHT := aSqlItem.TOTAL_WEIGHT;
		aPlsqlItem.NEXT_AP_SEQ_NBR := aSqlItem.NEXT_AP_SEQ_NBR;
		aPlsqlItem.OB_USER_ID := aSqlItem.OB_USER_ID;
		aPlsqlItem.CREATED_BY := aSqlItem.CREATED_BY;
		aPlsqlItem.CREATION_DATE := aSqlItem.CREATION_DATE;
		aPlsqlItem.LAST_UPDATED_BY := aSqlItem.LAST_UPDATED_BY;
		aPlsqlItem.LAST_UPDATE_DATE := aSqlItem.LAST_UPDATE_DATE;
		aPlsqlItem.LAST_UPDATE_LOGIN := aSqlItem.LAST_UPDATE_LOGIN;
		RETURN aPlsqlItem;
	END SQL_TO_PL8;
	FUNCTION PL_TO_SQL9(aPlsqlItem ROWTYPE_PL1)
 	RETURN XX_GI_RECEIVING_PKG_ROWTYPE_7 IS 
	aSqlItem XX_GI_RECEIVING_PKG_ROWTYPE_7; 
	BEGIN 
		-- initialize the object
		aSqlItem := XX_GI_RECEIVING_PKG_ROWTYPE_7(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
		aSqlItem.HEADER_INTERFACE_ID := aPlsqlItem.HEADER_INTERFACE_ID;
		aSqlItem.GROUP_ID := aPlsqlItem.GROUP_ID;
		aSqlItem.EDI_CONTROL_NUM := aPlsqlItem.EDI_CONTROL_NUM;
		aSqlItem.PROCESSING_STATUS_CODE := aPlsqlItem.PROCESSING_STATUS_CODE;
		aSqlItem.RECEIPT_SOURCE_CODE := aPlsqlItem.RECEIPT_SOURCE_CODE;
		aSqlItem.ASN_TYPE := aPlsqlItem.ASN_TYPE;
		aSqlItem.TRANSACTION_TYPE := aPlsqlItem.TRANSACTION_TYPE;
		aSqlItem.AUTO_TRANSACT_CODE := aPlsqlItem.AUTO_TRANSACT_CODE;
		aSqlItem.TEST_FLAG := aPlsqlItem.TEST_FLAG;
		aSqlItem.LAST_UPDATE_DATE := aPlsqlItem.LAST_UPDATE_DATE;
		aSqlItem.LAST_UPDATED_BY := aPlsqlItem.LAST_UPDATED_BY;
		aSqlItem.LAST_UPDATE_LOGIN := aPlsqlItem.LAST_UPDATE_LOGIN;
		aSqlItem.CREATION_DATE := aPlsqlItem.CREATION_DATE;
		aSqlItem.CREATED_BY := aPlsqlItem.CREATED_BY;
		aSqlItem.NOTICE_CREATION_DATE := aPlsqlItem.NOTICE_CREATION_DATE;
		aSqlItem.SHIPMENT_NUM := aPlsqlItem.SHIPMENT_NUM;
		aSqlItem.RECEIPT_NUM := aPlsqlItem.RECEIPT_NUM;
		aSqlItem.RECEIPT_HEADER_ID := aPlsqlItem.RECEIPT_HEADER_ID;
		aSqlItem.VENDOR_NAME := aPlsqlItem.VENDOR_NAME;
		aSqlItem.VENDOR_NUM := aPlsqlItem.VENDOR_NUM;
		aSqlItem.VENDOR_ID := aPlsqlItem.VENDOR_ID;
		aSqlItem.VENDOR_SITE_CODE := aPlsqlItem.VENDOR_SITE_CODE;
		aSqlItem.VENDOR_SITE_ID := aPlsqlItem.VENDOR_SITE_ID;
		aSqlItem.FROM_ORGANIZATION_CODE := aPlsqlItem.FROM_ORGANIZATION_CODE;
		aSqlItem.FROM_ORGANIZATION_ID := aPlsqlItem.FROM_ORGANIZATION_ID;
		aSqlItem.SHIP_TO_ORGANIZATION_CODE := aPlsqlItem.SHIP_TO_ORGANIZATION_CODE;
		aSqlItem.SHIP_TO_ORGANIZATION_ID := aPlsqlItem.SHIP_TO_ORGANIZATION_ID;
		aSqlItem.LOCATION_CODE := aPlsqlItem.LOCATION_CODE;
		aSqlItem.LOCATION_ID := aPlsqlItem.LOCATION_ID;
		aSqlItem.BILL_OF_LADING := aPlsqlItem.BILL_OF_LADING;
		aSqlItem.PACKING_SLIP := aPlsqlItem.PACKING_SLIP;
		aSqlItem.SHIPPED_DATE := aPlsqlItem.SHIPPED_DATE;
		aSqlItem.FREIGHT_CARRIER_CODE := aPlsqlItem.FREIGHT_CARRIER_CODE;
		aSqlItem.EXPECTED_RECEIPT_DATE := aPlsqlItem.EXPECTED_RECEIPT_DATE;
		aSqlItem.RECEIVER_ID := aPlsqlItem.RECEIVER_ID;
		aSqlItem.NUM_OF_CONTAINERS := aPlsqlItem.NUM_OF_CONTAINERS;
		aSqlItem.WAYBILL_AIRBILL_NUM := aPlsqlItem.WAYBILL_AIRBILL_NUM;
		aSqlItem.COMMENTS := aPlsqlItem.COMMENTS;
		aSqlItem.GROSS_WEIGHT := aPlsqlItem.GROSS_WEIGHT;
		aSqlItem.GROSS_WEIGHT_UOM_CODE := aPlsqlItem.GROSS_WEIGHT_UOM_CODE;
		aSqlItem.NET_WEIGHT := aPlsqlItem.NET_WEIGHT;
		aSqlItem.NET_WEIGHT_UOM_CODE := aPlsqlItem.NET_WEIGHT_UOM_CODE;
		aSqlItem.TAR_WEIGHT := aPlsqlItem.TAR_WEIGHT;
		aSqlItem.TAR_WEIGHT_UOM_CODE := aPlsqlItem.TAR_WEIGHT_UOM_CODE;
		aSqlItem.PACKAGING_CODE := aPlsqlItem.PACKAGING_CODE;
		aSqlItem.CARRIER_METHOD := aPlsqlItem.CARRIER_METHOD;
		aSqlItem.CARRIER_EQUIPMENT := aPlsqlItem.CARRIER_EQUIPMENT;
		aSqlItem.SPECIAL_HANDLING_CODE := aPlsqlItem.SPECIAL_HANDLING_CODE;
		aSqlItem.HAZARD_CODE := aPlsqlItem.HAZARD_CODE;
		aSqlItem.HAZARD_CLASS := aPlsqlItem.HAZARD_CLASS;
		aSqlItem.HAZARD_DESCRIPTION := aPlsqlItem.HAZARD_DESCRIPTION;
		aSqlItem.FREIGHT_TERMS := aPlsqlItem.FREIGHT_TERMS;
		aSqlItem.FREIGHT_BILL_NUMBER := aPlsqlItem.FREIGHT_BILL_NUMBER;
		aSqlItem.INVOICE_NUM := aPlsqlItem.INVOICE_NUM;
		aSqlItem.INVOICE_DATE := aPlsqlItem.INVOICE_DATE;
		aSqlItem.TOTAL_INVOICE_AMOUNT := aPlsqlItem.TOTAL_INVOICE_AMOUNT;
		aSqlItem.TAX_NAME := aPlsqlItem.TAX_NAME;
		aSqlItem.TAX_AMOUNT := aPlsqlItem.TAX_AMOUNT;
		aSqlItem.FREIGHT_AMOUNT := aPlsqlItem.FREIGHT_AMOUNT;
		aSqlItem.CURRENCY_CODE := aPlsqlItem.CURRENCY_CODE;
		aSqlItem.CONVERSION_RATE_TYPE := aPlsqlItem.CONVERSION_RATE_TYPE;
		aSqlItem.CONVERSION_RATE := aPlsqlItem.CONVERSION_RATE;
		aSqlItem.CONVERSION_RATE_DATE := aPlsqlItem.CONVERSION_RATE_DATE;
		aSqlItem.PAYMENT_TERMS_NAME := aPlsqlItem.PAYMENT_TERMS_NAME;
		aSqlItem.PAYMENT_TERMS_ID := aPlsqlItem.PAYMENT_TERMS_ID;
		aSqlItem.ATTRIBUTE_CATEGORY := aPlsqlItem.ATTRIBUTE_CATEGORY;
		aSqlItem.ATTRIBUTE1 := aPlsqlItem.ATTRIBUTE1;
		aSqlItem.ATTRIBUTE2 := aPlsqlItem.ATTRIBUTE2;
		aSqlItem.ATTRIBUTE3 := aPlsqlItem.ATTRIBUTE3;
		aSqlItem.ATTRIBUTE4 := aPlsqlItem.ATTRIBUTE4;
		aSqlItem.ATTRIBUTE5 := aPlsqlItem.ATTRIBUTE5;
		aSqlItem.ATTRIBUTE6 := aPlsqlItem.ATTRIBUTE6;
		aSqlItem.ATTRIBUTE7 := aPlsqlItem.ATTRIBUTE7;
		aSqlItem.ATTRIBUTE9 := aPlsqlItem.ATTRIBUTE9;
		aSqlItem.ATTRIBUTE10 := aPlsqlItem.ATTRIBUTE10;
		aSqlItem.ATTRIBUTE11 := aPlsqlItem.ATTRIBUTE11;
		aSqlItem.ATTRIBUTE12 := aPlsqlItem.ATTRIBUTE12;
		aSqlItem.ATTRIBUTE13 := aPlsqlItem.ATTRIBUTE13;
		aSqlItem.ATTRIBUTE14 := aPlsqlItem.ATTRIBUTE14;
		aSqlItem.ATTRIBUTE15 := aPlsqlItem.ATTRIBUTE15;
		aSqlItem.USGGL_TRANSACTION_CODE := aPlsqlItem.USGGL_TRANSACTION_CODE;
		aSqlItem.EMPLOYEE_NAME := aPlsqlItem.EMPLOYEE_NAME;
		aSqlItem.EMPLOYEE_ID := aPlsqlItem.EMPLOYEE_ID;
		aSqlItem.INVOICE_STATUS_CODE := aPlsqlItem.INVOICE_STATUS_CODE;
		aSqlItem.VALIDATION_FLAG := aPlsqlItem.VALIDATION_FLAG;
		aSqlItem.PROCESSING_REQUEST_ID := aPlsqlItem.PROCESSING_REQUEST_ID;
		aSqlItem.CUSTOMER_ACCOUNT_NUMBER := aPlsqlItem.CUSTOMER_ACCOUNT_NUMBER;
		aSqlItem.CUSTOMER_ID := aPlsqlItem.CUSTOMER_ID;
		aSqlItem.CUSTOMER_SITE_ID := aPlsqlItem.CUSTOMER_SITE_ID;
		aSqlItem.CUSTOMER_PARTY_NAME := aPlsqlItem.CUSTOMER_PARTY_NAME;
		aSqlItem.REMIT_TO_SITE_ID := aPlsqlItem.REMIT_TO_SITE_ID;
		aSqlItem.TRANSACTION_DATE := aPlsqlItem.TRANSACTION_DATE;
		aSqlItem.ORG_ID := aPlsqlItem.ORG_ID;
		aSqlItem.OPERATING_UNIT := aPlsqlItem.OPERATING_UNIT;
		aSqlItem.SHIP_FROM_LOCATION_ID := aPlsqlItem.SHIP_FROM_LOCATION_ID;
		aSqlItem.PERFORMANCE_PERIOD_FROM := aPlsqlItem.PERFORMANCE_PERIOD_FROM;
		aSqlItem.PERFORMANCE_PERIOD_TO := aPlsqlItem.PERFORMANCE_PERIOD_TO;
		aSqlItem.REQUEST_DATE := aPlsqlItem.REQUEST_DATE;
		aSqlItem.SHIP_FROM_LOCATION_CODE := aPlsqlItem.SHIP_FROM_LOCATION_CODE;
		aSqlItem.OD_RCV_STATUS_FLAG := aPlsqlItem.OD_RCV_STATUS_FLAG;
		aSqlItem.OD_RCV_FIRST_REC_TIME := aPlsqlItem.OD_RCV_FIRST_REC_TIME;
		aSqlItem.ATTRIBUTE8 := aPlsqlItem.ATTRIBUTE8;
		aSqlItem.OD_RCV_ERROR_DESCRIPTION := aPlsqlItem.OD_RCV_ERROR_DESCRIPTION;
		aSqlItem.LEGACY_TRANSACTION_TYPE := aPlsqlItem.LEGACY_TRANSACTION_TYPE;
		aSqlItem.LOC_NBR := aPlsqlItem.LOC_NBR;
		RETURN aSqlItem;
	END PL_TO_SQL9;
	FUNCTION SQL_TO_PL9(aSqlItem XX_GI_RECEIVING_PKG_ROWTYPE_7) 
	RETURN ROWTYPE_PL1 IS 
	aPlsqlItem ROWTYPE_PL1; 
	BEGIN 
		aPlsqlItem.HEADER_INTERFACE_ID := aSqlItem.HEADER_INTERFACE_ID;
		aPlsqlItem.GROUP_ID := aSqlItem.GROUP_ID;
		aPlsqlItem.EDI_CONTROL_NUM := aSqlItem.EDI_CONTROL_NUM;
		aPlsqlItem.PROCESSING_STATUS_CODE := aSqlItem.PROCESSING_STATUS_CODE;
		aPlsqlItem.RECEIPT_SOURCE_CODE := aSqlItem.RECEIPT_SOURCE_CODE;
		aPlsqlItem.ASN_TYPE := aSqlItem.ASN_TYPE;
		aPlsqlItem.TRANSACTION_TYPE := aSqlItem.TRANSACTION_TYPE;
		aPlsqlItem.AUTO_TRANSACT_CODE := aSqlItem.AUTO_TRANSACT_CODE;
		aPlsqlItem.TEST_FLAG := aSqlItem.TEST_FLAG;
		aPlsqlItem.LAST_UPDATE_DATE := aSqlItem.LAST_UPDATE_DATE;
		aPlsqlItem.LAST_UPDATED_BY := aSqlItem.LAST_UPDATED_BY;
		aPlsqlItem.LAST_UPDATE_LOGIN := aSqlItem.LAST_UPDATE_LOGIN;
		aPlsqlItem.CREATION_DATE := aSqlItem.CREATION_DATE;
		aPlsqlItem.CREATED_BY := aSqlItem.CREATED_BY;
		aPlsqlItem.NOTICE_CREATION_DATE := aSqlItem.NOTICE_CREATION_DATE;
		aPlsqlItem.SHIPMENT_NUM := aSqlItem.SHIPMENT_NUM;
		aPlsqlItem.RECEIPT_NUM := aSqlItem.RECEIPT_NUM;
		aPlsqlItem.RECEIPT_HEADER_ID := aSqlItem.RECEIPT_HEADER_ID;
		aPlsqlItem.VENDOR_NAME := aSqlItem.VENDOR_NAME;
		aPlsqlItem.VENDOR_NUM := aSqlItem.VENDOR_NUM;
		aPlsqlItem.VENDOR_ID := aSqlItem.VENDOR_ID;
		aPlsqlItem.VENDOR_SITE_CODE := aSqlItem.VENDOR_SITE_CODE;
		aPlsqlItem.VENDOR_SITE_ID := aSqlItem.VENDOR_SITE_ID;
		aPlsqlItem.FROM_ORGANIZATION_CODE := aSqlItem.FROM_ORGANIZATION_CODE;
		aPlsqlItem.FROM_ORGANIZATION_ID := aSqlItem.FROM_ORGANIZATION_ID;
		aPlsqlItem.SHIP_TO_ORGANIZATION_CODE := aSqlItem.SHIP_TO_ORGANIZATION_CODE;
		aPlsqlItem.SHIP_TO_ORGANIZATION_ID := aSqlItem.SHIP_TO_ORGANIZATION_ID;
		aPlsqlItem.LOCATION_CODE := aSqlItem.LOCATION_CODE;
		aPlsqlItem.LOCATION_ID := aSqlItem.LOCATION_ID;
		aPlsqlItem.BILL_OF_LADING := aSqlItem.BILL_OF_LADING;
		aPlsqlItem.PACKING_SLIP := aSqlItem.PACKING_SLIP;
		aPlsqlItem.SHIPPED_DATE := aSqlItem.SHIPPED_DATE;
		aPlsqlItem.FREIGHT_CARRIER_CODE := aSqlItem.FREIGHT_CARRIER_CODE;
		aPlsqlItem.EXPECTED_RECEIPT_DATE := aSqlItem.EXPECTED_RECEIPT_DATE;
		aPlsqlItem.RECEIVER_ID := aSqlItem.RECEIVER_ID;
		aPlsqlItem.NUM_OF_CONTAINERS := aSqlItem.NUM_OF_CONTAINERS;
		aPlsqlItem.WAYBILL_AIRBILL_NUM := aSqlItem.WAYBILL_AIRBILL_NUM;
		aPlsqlItem.COMMENTS := aSqlItem.COMMENTS;
		aPlsqlItem.GROSS_WEIGHT := aSqlItem.GROSS_WEIGHT;
		aPlsqlItem.GROSS_WEIGHT_UOM_CODE := aSqlItem.GROSS_WEIGHT_UOM_CODE;
		aPlsqlItem.NET_WEIGHT := aSqlItem.NET_WEIGHT;
		aPlsqlItem.NET_WEIGHT_UOM_CODE := aSqlItem.NET_WEIGHT_UOM_CODE;
		aPlsqlItem.TAR_WEIGHT := aSqlItem.TAR_WEIGHT;
		aPlsqlItem.TAR_WEIGHT_UOM_CODE := aSqlItem.TAR_WEIGHT_UOM_CODE;
		aPlsqlItem.PACKAGING_CODE := aSqlItem.PACKAGING_CODE;
		aPlsqlItem.CARRIER_METHOD := aSqlItem.CARRIER_METHOD;
		aPlsqlItem.CARRIER_EQUIPMENT := aSqlItem.CARRIER_EQUIPMENT;
		aPlsqlItem.SPECIAL_HANDLING_CODE := aSqlItem.SPECIAL_HANDLING_CODE;
		aPlsqlItem.HAZARD_CODE := aSqlItem.HAZARD_CODE;
		aPlsqlItem.HAZARD_CLASS := aSqlItem.HAZARD_CLASS;
		aPlsqlItem.HAZARD_DESCRIPTION := aSqlItem.HAZARD_DESCRIPTION;
		aPlsqlItem.FREIGHT_TERMS := aSqlItem.FREIGHT_TERMS;
		aPlsqlItem.FREIGHT_BILL_NUMBER := aSqlItem.FREIGHT_BILL_NUMBER;
		aPlsqlItem.INVOICE_NUM := aSqlItem.INVOICE_NUM;
		aPlsqlItem.INVOICE_DATE := aSqlItem.INVOICE_DATE;
		aPlsqlItem.TOTAL_INVOICE_AMOUNT := aSqlItem.TOTAL_INVOICE_AMOUNT;
		aPlsqlItem.TAX_NAME := aSqlItem.TAX_NAME;
		aPlsqlItem.TAX_AMOUNT := aSqlItem.TAX_AMOUNT;
		aPlsqlItem.FREIGHT_AMOUNT := aSqlItem.FREIGHT_AMOUNT;
		aPlsqlItem.CURRENCY_CODE := aSqlItem.CURRENCY_CODE;
		aPlsqlItem.CONVERSION_RATE_TYPE := aSqlItem.CONVERSION_RATE_TYPE;
		aPlsqlItem.CONVERSION_RATE := aSqlItem.CONVERSION_RATE;
		aPlsqlItem.CONVERSION_RATE_DATE := aSqlItem.CONVERSION_RATE_DATE;
		aPlsqlItem.PAYMENT_TERMS_NAME := aSqlItem.PAYMENT_TERMS_NAME;
		aPlsqlItem.PAYMENT_TERMS_ID := aSqlItem.PAYMENT_TERMS_ID;
		aPlsqlItem.ATTRIBUTE_CATEGORY := aSqlItem.ATTRIBUTE_CATEGORY;
		aPlsqlItem.ATTRIBUTE1 := aSqlItem.ATTRIBUTE1;
		aPlsqlItem.ATTRIBUTE2 := aSqlItem.ATTRIBUTE2;
		aPlsqlItem.ATTRIBUTE3 := aSqlItem.ATTRIBUTE3;
		aPlsqlItem.ATTRIBUTE4 := aSqlItem.ATTRIBUTE4;
		aPlsqlItem.ATTRIBUTE5 := aSqlItem.ATTRIBUTE5;
		aPlsqlItem.ATTRIBUTE6 := aSqlItem.ATTRIBUTE6;
		aPlsqlItem.ATTRIBUTE7 := aSqlItem.ATTRIBUTE7;
		aPlsqlItem.ATTRIBUTE9 := aSqlItem.ATTRIBUTE9;
		aPlsqlItem.ATTRIBUTE10 := aSqlItem.ATTRIBUTE10;
		aPlsqlItem.ATTRIBUTE11 := aSqlItem.ATTRIBUTE11;
		aPlsqlItem.ATTRIBUTE12 := aSqlItem.ATTRIBUTE12;
		aPlsqlItem.ATTRIBUTE13 := aSqlItem.ATTRIBUTE13;
		aPlsqlItem.ATTRIBUTE14 := aSqlItem.ATTRIBUTE14;
		aPlsqlItem.ATTRIBUTE15 := aSqlItem.ATTRIBUTE15;
		aPlsqlItem.USGGL_TRANSACTION_CODE := aSqlItem.USGGL_TRANSACTION_CODE;
		aPlsqlItem.EMPLOYEE_NAME := aSqlItem.EMPLOYEE_NAME;
		aPlsqlItem.EMPLOYEE_ID := aSqlItem.EMPLOYEE_ID;
		aPlsqlItem.INVOICE_STATUS_CODE := aSqlItem.INVOICE_STATUS_CODE;
		aPlsqlItem.VALIDATION_FLAG := aSqlItem.VALIDATION_FLAG;
		aPlsqlItem.PROCESSING_REQUEST_ID := aSqlItem.PROCESSING_REQUEST_ID;
		aPlsqlItem.CUSTOMER_ACCOUNT_NUMBER := aSqlItem.CUSTOMER_ACCOUNT_NUMBER;
		aPlsqlItem.CUSTOMER_ID := aSqlItem.CUSTOMER_ID;
		aPlsqlItem.CUSTOMER_SITE_ID := aSqlItem.CUSTOMER_SITE_ID;
		aPlsqlItem.CUSTOMER_PARTY_NAME := aSqlItem.CUSTOMER_PARTY_NAME;
		aPlsqlItem.REMIT_TO_SITE_ID := aSqlItem.REMIT_TO_SITE_ID;
		aPlsqlItem.TRANSACTION_DATE := aSqlItem.TRANSACTION_DATE;
		aPlsqlItem.ORG_ID := aSqlItem.ORG_ID;
		aPlsqlItem.OPERATING_UNIT := aSqlItem.OPERATING_UNIT;
		aPlsqlItem.SHIP_FROM_LOCATION_ID := aSqlItem.SHIP_FROM_LOCATION_ID;
		aPlsqlItem.PERFORMANCE_PERIOD_FROM := aSqlItem.PERFORMANCE_PERIOD_FROM;
		aPlsqlItem.PERFORMANCE_PERIOD_TO := aSqlItem.PERFORMANCE_PERIOD_TO;
		aPlsqlItem.REQUEST_DATE := aSqlItem.REQUEST_DATE;
		aPlsqlItem.SHIP_FROM_LOCATION_CODE := aSqlItem.SHIP_FROM_LOCATION_CODE;
		aPlsqlItem.OD_RCV_STATUS_FLAG := aSqlItem.OD_RCV_STATUS_FLAG;
		aPlsqlItem.OD_RCV_FIRST_REC_TIME := aSqlItem.OD_RCV_FIRST_REC_TIME;
		aPlsqlItem.ATTRIBUTE8 := aSqlItem.ATTRIBUTE8;
		aPlsqlItem.OD_RCV_ERROR_DESCRIPTION := aSqlItem.OD_RCV_ERROR_DESCRIPTION;
		aPlsqlItem.LEGACY_TRANSACTION_TYPE := aSqlItem.LEGACY_TRANSACTION_TYPE;
		aPlsqlItem.LOC_NBR := aSqlItem.LOC_NBR;
		RETURN aPlsqlItem;
	END SQL_TO_PL9;
	FUNCTION PL_TO_SQL11(aPlsqlItem XX_GI_RECEIVING_PKG.DETAIL_REC_TYPE)
 	RETURN XX_GI_RECEIVING_PKG_DETAIL_R9 IS 
	aSqlItem XX_GI_RECEIVING_PKG_DETAIL_R9; 
	BEGIN 
		-- initialize the object
		aSqlItem := XX_GI_RECEIVING_PKG_DETAIL_R9(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
		aSqlItem.INTERFACE_TRANSACTION_ID := aPlsqlItem.INTERFACE_TRANSACTION_ID;
		aSqlItem.GROUP_ID := aPlsqlItem.GROUP_ID;
		aSqlItem.LAST_UPDATE_DATE := aPlsqlItem.LAST_UPDATE_DATE;
		aSqlItem.LAST_UPDATED_BY := aPlsqlItem.LAST_UPDATED_BY;
		aSqlItem.CREATION_DATE := aPlsqlItem.CREATION_DATE;
		aSqlItem.CREATED_BY := aPlsqlItem.CREATED_BY;
		aSqlItem.LAST_UPDATE_LOGIN := aPlsqlItem.LAST_UPDATE_LOGIN;
		aSqlItem.REQUEST_ID := aPlsqlItem.REQUEST_ID;
		aSqlItem.PROGRAM_APPLICATION_ID := aPlsqlItem.PROGRAM_APPLICATION_ID;
		aSqlItem.PROGRAM_ID := aPlsqlItem.PROGRAM_ID;
		aSqlItem.PROGRAM_UPDATE_DATE := aPlsqlItem.PROGRAM_UPDATE_DATE;
		aSqlItem.TRANSACTION_TYPE := aPlsqlItem.TRANSACTION_TYPE;
		aSqlItem.TRANSACTION_DATE := aPlsqlItem.TRANSACTION_DATE;
		aSqlItem.PROCESSING_STATUS_CODE := aPlsqlItem.PROCESSING_STATUS_CODE;
		aSqlItem.PROCESSING_MODE_CODE := aPlsqlItem.PROCESSING_MODE_CODE;
		aSqlItem.PROCESSING_REQUEST_ID := aPlsqlItem.PROCESSING_REQUEST_ID;
		aSqlItem.TRANSACTION_STATUS_CODE := aPlsqlItem.TRANSACTION_STATUS_CODE;
		aSqlItem.CATEGORY_ID := aPlsqlItem.CATEGORY_ID;
		aSqlItem.QUANTITY := aPlsqlItem.QUANTITY;
		aSqlItem.UNIT_OF_MEASURE := aPlsqlItem.UNIT_OF_MEASURE;
		aSqlItem.INTERFACE_SOURCE_CODE := aPlsqlItem.INTERFACE_SOURCE_CODE;
		aSqlItem.INTERFACE_SOURCE_LINE_ID := aPlsqlItem.INTERFACE_SOURCE_LINE_ID;
		aSqlItem.INV_TRANSACTION_ID := aPlsqlItem.INV_TRANSACTION_ID;
		aSqlItem.ITEM_ID := aPlsqlItem.ITEM_ID;
		aSqlItem.ITEM_DESCRIPTION := aPlsqlItem.ITEM_DESCRIPTION;
		aSqlItem.ITEM_REVISION := aPlsqlItem.ITEM_REVISION;
		aSqlItem.UOM_CODE := aPlsqlItem.UOM_CODE;
		aSqlItem.EMPLOYEE_ID := aPlsqlItem.EMPLOYEE_ID;
		aSqlItem.AUTO_TRANSACT_CODE := aPlsqlItem.AUTO_TRANSACT_CODE;
		aSqlItem.SHIPMENT_HEADER_ID := aPlsqlItem.SHIPMENT_HEADER_ID;
		aSqlItem.SHIPMENT_LINE_ID := aPlsqlItem.SHIPMENT_LINE_ID;
		aSqlItem.SHIP_TO_LOCATION_ID := aPlsqlItem.SHIP_TO_LOCATION_ID;
		aSqlItem.PRIMARY_QUANTITY := aPlsqlItem.PRIMARY_QUANTITY;
		aSqlItem.PRIMARY_UNIT_OF_MEASURE := aPlsqlItem.PRIMARY_UNIT_OF_MEASURE;
		aSqlItem.RECEIPT_SOURCE_CODE := aPlsqlItem.RECEIPT_SOURCE_CODE;
		aSqlItem.VENDOR_ID := aPlsqlItem.VENDOR_ID;
		aSqlItem.VENDOR_SITE_ID := aPlsqlItem.VENDOR_SITE_ID;
		aSqlItem.FROM_ORGANIZATION_ID := aPlsqlItem.FROM_ORGANIZATION_ID;
		aSqlItem.FROM_SUBINVENTORY := aPlsqlItem.FROM_SUBINVENTORY;
		aSqlItem.TO_ORGANIZATION_ID := aPlsqlItem.TO_ORGANIZATION_ID;
		aSqlItem.INTRANSIT_OWNING_ORG_ID := aPlsqlItem.INTRANSIT_OWNING_ORG_ID;
		aSqlItem.ROUTING_HEADER_ID := aPlsqlItem.ROUTING_HEADER_ID;
		aSqlItem.ROUTING_STEP_ID := aPlsqlItem.ROUTING_STEP_ID;
		aSqlItem.SOURCE_DOCUMENT_CODE := aPlsqlItem.SOURCE_DOCUMENT_CODE;
		aSqlItem.PARENT_TRANSACTION_ID := aPlsqlItem.PARENT_TRANSACTION_ID;
		aSqlItem.PO_HEADER_ID := aPlsqlItem.PO_HEADER_ID;
		aSqlItem.PO_REVISION_NUM := aPlsqlItem.PO_REVISION_NUM;
		aSqlItem.PO_RELEASE_ID := aPlsqlItem.PO_RELEASE_ID;
		aSqlItem.PO_LINE_ID := aPlsqlItem.PO_LINE_ID;
		aSqlItem.PO_LINE_LOCATION_ID := aPlsqlItem.PO_LINE_LOCATION_ID;
		aSqlItem.PO_UNIT_PRICE := aPlsqlItem.PO_UNIT_PRICE;
		aSqlItem.CURRENCY_CODE := aPlsqlItem.CURRENCY_CODE;
		aSqlItem.CURRENCY_CONVERSION_TYPE := aPlsqlItem.CURRENCY_CONVERSION_TYPE;
		aSqlItem.CURRENCY_CONVERSION_RATE := aPlsqlItem.CURRENCY_CONVERSION_RATE;
		aSqlItem.CURRENCY_CONVERSION_DATE := aPlsqlItem.CURRENCY_CONVERSION_DATE;
		aSqlItem.PO_DISTRIBUTION_ID := aPlsqlItem.PO_DISTRIBUTION_ID;
		aSqlItem.REQUISITION_LINE_ID := aPlsqlItem.REQUISITION_LINE_ID;
		aSqlItem.REQ_DISTRIBUTION_ID := aPlsqlItem.REQ_DISTRIBUTION_ID;
		aSqlItem.CHARGE_ACCOUNT_ID := aPlsqlItem.CHARGE_ACCOUNT_ID;
		aSqlItem.SUBSTITUTE_UNORDERED_CODE := aPlsqlItem.SUBSTITUTE_UNORDERED_CODE;
		aSqlItem.RECEIPT_EXCEPTION_FLAG := aPlsqlItem.RECEIPT_EXCEPTION_FLAG;
		aSqlItem.ACCRUAL_STATUS_CODE := aPlsqlItem.ACCRUAL_STATUS_CODE;
		aSqlItem.INSPECTION_STATUS_CODE := aPlsqlItem.INSPECTION_STATUS_CODE;
		aSqlItem.INSPECTION_QUALITY_CODE := aPlsqlItem.INSPECTION_QUALITY_CODE;
		aSqlItem.DESTINATION_TYPE_CODE := aPlsqlItem.DESTINATION_TYPE_CODE;
		aSqlItem.DELIVER_TO_PERSON_ID := aPlsqlItem.DELIVER_TO_PERSON_ID;
		aSqlItem.LOCATION_ID := aPlsqlItem.LOCATION_ID;
		aSqlItem.DELIVER_TO_LOCATION_ID := aPlsqlItem.DELIVER_TO_LOCATION_ID;
		aSqlItem.SUBINVENTORY := aPlsqlItem.SUBINVENTORY;
		aSqlItem.LOCATOR_ID := aPlsqlItem.LOCATOR_ID;
		aSqlItem.WIP_ENTITY_ID := aPlsqlItem.WIP_ENTITY_ID;
		aSqlItem.WIP_LINE_ID := aPlsqlItem.WIP_LINE_ID;
		aSqlItem.DEPARTMENT_CODE := aPlsqlItem.DEPARTMENT_CODE;
		aSqlItem.WIP_REPETITIVE_SCHEDULE_ID := aPlsqlItem.WIP_REPETITIVE_SCHEDULE_ID;
		aSqlItem.WIP_OPERATION_SEQ_NUM := aPlsqlItem.WIP_OPERATION_SEQ_NUM;
		aSqlItem.WIP_RESOURCE_SEQ_NUM := aPlsqlItem.WIP_RESOURCE_SEQ_NUM;
		aSqlItem.BOM_RESOURCE_ID := aPlsqlItem.BOM_RESOURCE_ID;
		aSqlItem.SHIPMENT_NUM := aPlsqlItem.SHIPMENT_NUM;
		aSqlItem.FREIGHT_CARRIER_CODE := aPlsqlItem.FREIGHT_CARRIER_CODE;
		aSqlItem.BILL_OF_LADING := aPlsqlItem.BILL_OF_LADING;
		aSqlItem.PACKING_SLIP := aPlsqlItem.PACKING_SLIP;
		aSqlItem.SHIPPED_DATE := aPlsqlItem.SHIPPED_DATE;
		aSqlItem.EXPECTED_RECEIPT_DATE := aPlsqlItem.EXPECTED_RECEIPT_DATE;
		aSqlItem.ACTUAL_COST := aPlsqlItem.ACTUAL_COST;
		aSqlItem.TRANSFER_COST := aPlsqlItem.TRANSFER_COST;
		aSqlItem.TRANSPORTATION_COST := aPlsqlItem.TRANSPORTATION_COST;
		aSqlItem.TRANSPORTATION_ACCOUNT_ID := aPlsqlItem.TRANSPORTATION_ACCOUNT_ID;
		aSqlItem.NUM_OF_CONTAINERS := aPlsqlItem.NUM_OF_CONTAINERS;
		aSqlItem.WAYBILL_AIRBILL_NUM := aPlsqlItem.WAYBILL_AIRBILL_NUM;
		aSqlItem.VENDOR_ITEM_NUM := aPlsqlItem.VENDOR_ITEM_NUM;
		aSqlItem.VENDOR_LOT_NUM := aPlsqlItem.VENDOR_LOT_NUM;
		aSqlItem.RMA_REFERENCE := aPlsqlItem.RMA_REFERENCE;
		aSqlItem.COMMENTS := aPlsqlItem.COMMENTS;
		aSqlItem.ATTRIBUTE_CATEGORY := aPlsqlItem.ATTRIBUTE_CATEGORY;
		aSqlItem.ATTRIBUTE1 := aPlsqlItem.ATTRIBUTE1;
		aSqlItem.ATTRIBUTE2 := aPlsqlItem.ATTRIBUTE2;
		aSqlItem.ATTRIBUTE3 := aPlsqlItem.ATTRIBUTE3;
		aSqlItem.ATTRIBUTE4 := aPlsqlItem.ATTRIBUTE4;
		aSqlItem.ATTRIBUTE5 := aPlsqlItem.ATTRIBUTE5;
		aSqlItem.ATTRIBUTE6 := aPlsqlItem.ATTRIBUTE6;
		aSqlItem.ATTRIBUTE7 := aPlsqlItem.ATTRIBUTE7;
		aSqlItem.ATTRIBUTE9 := aPlsqlItem.ATTRIBUTE9;
		aSqlItem.ATTRIBUTE10 := aPlsqlItem.ATTRIBUTE10;
		aSqlItem.ATTRIBUTE11 := aPlsqlItem.ATTRIBUTE11;
		aSqlItem.ATTRIBUTE12 := aPlsqlItem.ATTRIBUTE12;
		aSqlItem.ATTRIBUTE13 := aPlsqlItem.ATTRIBUTE13;
		aSqlItem.ATTRIBUTE14 := aPlsqlItem.ATTRIBUTE14;
		aSqlItem.ATTRIBUTE15 := aPlsqlItem.ATTRIBUTE15;
		aSqlItem.SHIP_HEAD_ATTRIBUTE_CATEGORY := aPlsqlItem.SHIP_HEAD_ATTRIBUTE_CATEGORY;
		aSqlItem.SHIP_HEAD_ATTRIBUTE1 := aPlsqlItem.SHIP_HEAD_ATTRIBUTE1;
		aSqlItem.SHIP_HEAD_ATTRIBUTE2 := aPlsqlItem.SHIP_HEAD_ATTRIBUTE2;
		aSqlItem.SHIP_HEAD_ATTRIBUTE3 := aPlsqlItem.SHIP_HEAD_ATTRIBUTE3;
		aSqlItem.SHIP_HEAD_ATTRIBUTE4 := aPlsqlItem.SHIP_HEAD_ATTRIBUTE4;
		aSqlItem.SHIP_HEAD_ATTRIBUTE5 := aPlsqlItem.SHIP_HEAD_ATTRIBUTE5;
		aSqlItem.SHIP_HEAD_ATTRIBUTE6 := aPlsqlItem.SHIP_HEAD_ATTRIBUTE6;
		aSqlItem.SHIP_HEAD_ATTRIBUTE7 := aPlsqlItem.SHIP_HEAD_ATTRIBUTE7;
		aSqlItem.SHIP_HEAD_ATTRIBUTE8 := aPlsqlItem.SHIP_HEAD_ATTRIBUTE8;
		aSqlItem.SHIP_HEAD_ATTRIBUTE9 := aPlsqlItem.SHIP_HEAD_ATTRIBUTE9;
		aSqlItem.SHIP_HEAD_ATTRIBUTE10 := aPlsqlItem.SHIP_HEAD_ATTRIBUTE10;
		aSqlItem.SHIP_HEAD_ATTRIBUTE11 := aPlsqlItem.SHIP_HEAD_ATTRIBUTE11;
		aSqlItem.SHIP_HEAD_ATTRIBUTE12 := aPlsqlItem.SHIP_HEAD_ATTRIBUTE12;
		aSqlItem.SHIP_HEAD_ATTRIBUTE13 := aPlsqlItem.SHIP_HEAD_ATTRIBUTE13;
		aSqlItem.SHIP_HEAD_ATTRIBUTE14 := aPlsqlItem.SHIP_HEAD_ATTRIBUTE14;
		aSqlItem.SHIP_HEAD_ATTRIBUTE15 := aPlsqlItem.SHIP_HEAD_ATTRIBUTE15;
		aSqlItem.SHIP_LINE_ATTRIBUTE_CATEGORY := aPlsqlItem.SHIP_LINE_ATTRIBUTE_CATEGORY;
		aSqlItem.SHIP_LINE_ATTRIBUTE1 := aPlsqlItem.SHIP_LINE_ATTRIBUTE1;
		aSqlItem.SHIP_LINE_ATTRIBUTE2 := aPlsqlItem.SHIP_LINE_ATTRIBUTE2;
		aSqlItem.SHIP_LINE_ATTRIBUTE3 := aPlsqlItem.SHIP_LINE_ATTRIBUTE3;
		aSqlItem.SHIP_LINE_ATTRIBUTE4 := aPlsqlItem.SHIP_LINE_ATTRIBUTE4;
		aSqlItem.SHIP_LINE_ATTRIBUTE5 := aPlsqlItem.SHIP_LINE_ATTRIBUTE5;
		aSqlItem.SHIP_LINE_ATTRIBUTE6 := aPlsqlItem.SHIP_LINE_ATTRIBUTE6;
		aSqlItem.SHIP_LINE_ATTRIBUTE7 := aPlsqlItem.SHIP_LINE_ATTRIBUTE7;
		aSqlItem.SHIP_LINE_ATTRIBUTE8 := aPlsqlItem.SHIP_LINE_ATTRIBUTE8;
		aSqlItem.SHIP_LINE_ATTRIBUTE9 := aPlsqlItem.SHIP_LINE_ATTRIBUTE9;
		aSqlItem.SHIP_LINE_ATTRIBUTE10 := aPlsqlItem.SHIP_LINE_ATTRIBUTE10;
		aSqlItem.SHIP_LINE_ATTRIBUTE11 := aPlsqlItem.SHIP_LINE_ATTRIBUTE11;
		aSqlItem.SHIP_LINE_ATTRIBUTE12 := aPlsqlItem.SHIP_LINE_ATTRIBUTE12;
		aSqlItem.SHIP_LINE_ATTRIBUTE13 := aPlsqlItem.SHIP_LINE_ATTRIBUTE13;
		aSqlItem.SHIP_LINE_ATTRIBUTE14 := aPlsqlItem.SHIP_LINE_ATTRIBUTE14;
		aSqlItem.SHIP_LINE_ATTRIBUTE15 := aPlsqlItem.SHIP_LINE_ATTRIBUTE15;
		aSqlItem.USSGL_TRANSACTION_CODE := aPlsqlItem.USSGL_TRANSACTION_CODE;
		aSqlItem.GOVERNMENT_CONTEXT := aPlsqlItem.GOVERNMENT_CONTEXT;
		aSqlItem.REASON_ID := aPlsqlItem.REASON_ID;
		aSqlItem.DESTINATION_CONTEXT := aPlsqlItem.DESTINATION_CONTEXT;
		aSqlItem.SOURCE_DOC_QUANTITY := aPlsqlItem.SOURCE_DOC_QUANTITY;
		aSqlItem.SOURCE_DOC_UNIT_OF_MEASURE := aPlsqlItem.SOURCE_DOC_UNIT_OF_MEASURE;
		aSqlItem.MOVEMENT_ID := aPlsqlItem.MOVEMENT_ID;
		aSqlItem.HEADER_INTERFACE_ID := aPlsqlItem.HEADER_INTERFACE_ID;
		aSqlItem.VENDOR_CUM_SHIPPED_QTY := aPlsqlItem.VENDOR_CUM_SHIPPED_QTY;
		aSqlItem.ITEM_NUM := aPlsqlItem.ITEM_NUM;
		aSqlItem.DOCUMENT_NUM := aPlsqlItem.DOCUMENT_NUM;
		aSqlItem.DOCUMENT_LINE_NUM := aPlsqlItem.DOCUMENT_LINE_NUM;
		aSqlItem.TRUCK_NUM := aPlsqlItem.TRUCK_NUM;
		aSqlItem.SHIP_TO_LOCATION_CODE := aPlsqlItem.SHIP_TO_LOCATION_CODE;
		aSqlItem.CONTAINER_NUM := aPlsqlItem.CONTAINER_NUM;
		aSqlItem.SUBSTITUTE_ITEM_NUM := aPlsqlItem.SUBSTITUTE_ITEM_NUM;
		aSqlItem.NOTICE_UNIT_PRICE := aPlsqlItem.NOTICE_UNIT_PRICE;
		aSqlItem.ITEM_CATEGORY := aPlsqlItem.ITEM_CATEGORY;
		aSqlItem.LOCATION_CODE := aPlsqlItem.LOCATION_CODE;
		aSqlItem.VENDOR_NAME := aPlsqlItem.VENDOR_NAME;
		aSqlItem.VENDOR_NUM := aPlsqlItem.VENDOR_NUM;
		aSqlItem.VENDOR_SITE_CODE := aPlsqlItem.VENDOR_SITE_CODE;
		aSqlItem.FROM_ORGANIZATION_CODE := aPlsqlItem.FROM_ORGANIZATION_CODE;
		aSqlItem.TO_ORGANIZATION_CODE := aPlsqlItem.TO_ORGANIZATION_CODE;
		aSqlItem.INTRANSIT_OWNING_ORG_CODE := aPlsqlItem.INTRANSIT_OWNING_ORG_CODE;
		aSqlItem.ROUTING_CODE := aPlsqlItem.ROUTING_CODE;
		aSqlItem.ROUTING_STEP := aPlsqlItem.ROUTING_STEP;
		aSqlItem.RELEASE_NUM := aPlsqlItem.RELEASE_NUM;
		aSqlItem.DOCUMENT_SHIPMENT_LINE_NUM := aPlsqlItem.DOCUMENT_SHIPMENT_LINE_NUM;
		aSqlItem.DOCUMENT_DISTRIBUTION_NUM := aPlsqlItem.DOCUMENT_DISTRIBUTION_NUM;
		aSqlItem.DELIVER_TO_PERSON_NAME := aPlsqlItem.DELIVER_TO_PERSON_NAME;
		aSqlItem.DELIVER_TO_LOCATION_CODE := aPlsqlItem.DELIVER_TO_LOCATION_CODE;
		aSqlItem.USE_MTL_LOT := aPlsqlItem.USE_MTL_LOT;
		aSqlItem.USE_MTL_SERIAL := aPlsqlItem.USE_MTL_SERIAL;
		aSqlItem.LOCATOR := aPlsqlItem.LOCATOR;
		aSqlItem.REASON_NAME := aPlsqlItem.REASON_NAME;
		aSqlItem.VALIDATION_FLAG := aPlsqlItem.VALIDATION_FLAG;
		aSqlItem.SUBSTITUTE_ITEM_ID := aPlsqlItem.SUBSTITUTE_ITEM_ID;
		aSqlItem.QUANTITY_SHIPPED := aPlsqlItem.QUANTITY_SHIPPED;
		aSqlItem.QUANTITY_INVOICED := aPlsqlItem.QUANTITY_INVOICED;
		aSqlItem.TAX_NAME := aPlsqlItem.TAX_NAME;
		aSqlItem.TAX_AMOUNT := aPlsqlItem.TAX_AMOUNT;
		aSqlItem.REQ_NUM := aPlsqlItem.REQ_NUM;
		aSqlItem.REQ_LINE_NUM := aPlsqlItem.REQ_LINE_NUM;
		aSqlItem.REQ_DISTRIBUTION_NUM := aPlsqlItem.REQ_DISTRIBUTION_NUM;
		aSqlItem.WIP_ENTITY_NAME := aPlsqlItem.WIP_ENTITY_NAME;
		aSqlItem.WIP_LINE_CODE := aPlsqlItem.WIP_LINE_CODE;
		aSqlItem.RESOURCE_CODE := aPlsqlItem.RESOURCE_CODE;
		aSqlItem.SHIPMENT_LINE_STATUS_CODE := aPlsqlItem.SHIPMENT_LINE_STATUS_CODE;
		aSqlItem.BARCODE_LABEL := aPlsqlItem.BARCODE_LABEL;
		aSqlItem.TRANSFER_PERCENTAGE := aPlsqlItem.TRANSFER_PERCENTAGE;
		aSqlItem.QA_COLLECTION_ID := aPlsqlItem.QA_COLLECTION_ID;
		aSqlItem.COUNTRY_OF_ORIGIN_CODE := aPlsqlItem.COUNTRY_OF_ORIGIN_CODE;
		aSqlItem.OE_ORDER_HEADER_ID := aPlsqlItem.OE_ORDER_HEADER_ID;
		aSqlItem.OE_ORDER_LINE_ID := aPlsqlItem.OE_ORDER_LINE_ID;
		aSqlItem.CUSTOMER_ID := aPlsqlItem.CUSTOMER_ID;
		aSqlItem.CUSTOMER_SITE_ID := aPlsqlItem.CUSTOMER_SITE_ID;
		aSqlItem.CUSTOMER_ITEM_NUM := aPlsqlItem.CUSTOMER_ITEM_NUM;
		aSqlItem.CREATE_DEBIT_MEMO_FLAG := aPlsqlItem.CREATE_DEBIT_MEMO_FLAG;
		aSqlItem.PUT_AWAY_RULE_ID := aPlsqlItem.PUT_AWAY_RULE_ID;
		aSqlItem.PUT_AWAY_STRATEGY_ID := aPlsqlItem.PUT_AWAY_STRATEGY_ID;
		aSqlItem.LPN_ID := aPlsqlItem.LPN_ID;
		aSqlItem.TRANSFER_LPN_ID := aPlsqlItem.TRANSFER_LPN_ID;
		aSqlItem.COST_GROUP_ID := aPlsqlItem.COST_GROUP_ID;
		aSqlItem.MOBILE_TXN := aPlsqlItem.MOBILE_TXN;
		aSqlItem.MMTT_TEMP_ID := aPlsqlItem.MMTT_TEMP_ID;
		aSqlItem.TRANSFER_COST_GROUP_ID := aPlsqlItem.TRANSFER_COST_GROUP_ID;
		aSqlItem.SECONDARY_QUANTITY := aPlsqlItem.SECONDARY_QUANTITY;
		aSqlItem.SECONDARY_UNIT_OF_MEASURE := aPlsqlItem.SECONDARY_UNIT_OF_MEASURE;
		aSqlItem.SECONDARY_UOM_CODE := aPlsqlItem.SECONDARY_UOM_CODE;
		aSqlItem.QC_GRADE := aPlsqlItem.QC_GRADE;
		aSqlItem.FROM_LOCATOR := aPlsqlItem.FROM_LOCATOR;
		aSqlItem.FROM_LOCATOR_ID := aPlsqlItem.FROM_LOCATOR_ID;
		aSqlItem.PARENT_SOURCE_TRANSACTION_NUM := aPlsqlItem.PARENT_SOURCE_TRANSACTION_NUM;
		aSqlItem.INTERFACE_AVAILABLE_QTY := aPlsqlItem.INTERFACE_AVAILABLE_QTY;
		aSqlItem.INTERFACE_TRANSACTION_QTY := aPlsqlItem.INTERFACE_TRANSACTION_QTY;
		aSqlItem.INTERFACE_AVAILABLE_AMT := aPlsqlItem.INTERFACE_AVAILABLE_AMT;
		aSqlItem.INTERFACE_TRANSACTION_AMT := aPlsqlItem.INTERFACE_TRANSACTION_AMT;
		aSqlItem.LICENSE_PLATE_NUMBER := aPlsqlItem.LICENSE_PLATE_NUMBER;
		aSqlItem.SOURCE_TRANSACTION_NUM := aPlsqlItem.SOURCE_TRANSACTION_NUM;
		aSqlItem.TRANSFER_LICENSE_PLATE_NUMBER := aPlsqlItem.TRANSFER_LICENSE_PLATE_NUMBER;
		aSqlItem.LPN_GROUP_ID := aPlsqlItem.LPN_GROUP_ID;
		aSqlItem.ORDER_TRANSACTION_ID := aPlsqlItem.ORDER_TRANSACTION_ID;
		aSqlItem.CUSTOMER_ACCOUNT_NUMBER := aPlsqlItem.CUSTOMER_ACCOUNT_NUMBER;
		aSqlItem.CUSTOMER_PARTY_NAME := aPlsqlItem.CUSTOMER_PARTY_NAME;
		aSqlItem.OE_ORDER_LINE_NUM := aPlsqlItem.OE_ORDER_LINE_NUM;
		aSqlItem.OE_ORDER_NUM := aPlsqlItem.OE_ORDER_NUM;
		aSqlItem.PARENT_INTERFACE_TXN_ID := aPlsqlItem.PARENT_INTERFACE_TXN_ID;
		aSqlItem.CUSTOMER_ITEM_ID := aPlsqlItem.CUSTOMER_ITEM_ID;
		aSqlItem.AMOUNT := aPlsqlItem.AMOUNT;
		aSqlItem.JOB_ID := aPlsqlItem.JOB_ID;
		aSqlItem.TIMECARD_ID := aPlsqlItem.TIMECARD_ID;
		aSqlItem.TIMECARD_OVN := aPlsqlItem.TIMECARD_OVN;
		aSqlItem.ERECORD_ID := aPlsqlItem.ERECORD_ID;
		aSqlItem.PROJECT_ID := aPlsqlItem.PROJECT_ID;
		aSqlItem.TASK_ID := aPlsqlItem.TASK_ID;
		aSqlItem.ASN_ATTACH_ID := aPlsqlItem.ASN_ATTACH_ID;
		aSqlItem.ORG_ID := aPlsqlItem.ORG_ID;
		aSqlItem.OPERATING_UNIT := aPlsqlItem.OPERATING_UNIT;
		aSqlItem.REQUESTED_AMOUNT := aPlsqlItem.REQUESTED_AMOUNT;
		aSqlItem.MATERIAL_STORED_AMOUNT := aPlsqlItem.MATERIAL_STORED_AMOUNT;
		aSqlItem.AMOUNT_SHIPPED := aPlsqlItem.AMOUNT_SHIPPED;
		aSqlItem.MATCHING_BASIS := aPlsqlItem.MATCHING_BASIS;
		aSqlItem.REPLENISH_ORDER_LINE_ID := aPlsqlItem.REPLENISH_ORDER_LINE_ID;
		aSqlItem.E0346_STATUS_FLAG := aPlsqlItem.E0346_STATUS_FLAG;
		aSqlItem.OD_RCV_ERROR_DESCRIPTION := aPlsqlItem.OD_RCV_ERROR_DESCRIPTION;
		aSqlItem.ATTRIBUTE8 := aPlsqlItem.ATTRIBUTE8;
		aSqlItem.OD_RVC_CORRECTION_FLAG := aPlsqlItem.OD_RVC_CORRECTION_FLAG;
		aSqlItem.OD_RCV_STATUS_FLAG := aPlsqlItem.OD_RCV_STATUS_FLAG;
		aSqlItem.LEGACY_TRANSACTION_TYPE := aPlsqlItem.LEGACY_TRANSACTION_TYPE;
		RETURN aSqlItem;
	END PL_TO_SQL11;
	FUNCTION SQL_TO_PL11(aSqlItem XX_GI_RECEIVING_PKG_DETAIL_R9) 
	RETURN XX_GI_RECEIVING_PKG.DETAIL_REC_TYPE IS 
	aPlsqlItem XX_GI_RECEIVING_PKG.DETAIL_REC_TYPE; 
	BEGIN 
		aPlsqlItem.INTERFACE_TRANSACTION_ID := aSqlItem.INTERFACE_TRANSACTION_ID;
		aPlsqlItem.GROUP_ID := aSqlItem.GROUP_ID;
		aPlsqlItem.LAST_UPDATE_DATE := aSqlItem.LAST_UPDATE_DATE;
		aPlsqlItem.LAST_UPDATED_BY := aSqlItem.LAST_UPDATED_BY;
		aPlsqlItem.CREATION_DATE := aSqlItem.CREATION_DATE;
		aPlsqlItem.CREATED_BY := aSqlItem.CREATED_BY;
		aPlsqlItem.LAST_UPDATE_LOGIN := aSqlItem.LAST_UPDATE_LOGIN;
		aPlsqlItem.REQUEST_ID := aSqlItem.REQUEST_ID;
		aPlsqlItem.PROGRAM_APPLICATION_ID := aSqlItem.PROGRAM_APPLICATION_ID;
		aPlsqlItem.PROGRAM_ID := aSqlItem.PROGRAM_ID;
		aPlsqlItem.PROGRAM_UPDATE_DATE := aSqlItem.PROGRAM_UPDATE_DATE;
		aPlsqlItem.TRANSACTION_TYPE := aSqlItem.TRANSACTION_TYPE;
		aPlsqlItem.TRANSACTION_DATE := aSqlItem.TRANSACTION_DATE;
		aPlsqlItem.PROCESSING_STATUS_CODE := aSqlItem.PROCESSING_STATUS_CODE;
		aPlsqlItem.PROCESSING_MODE_CODE := aSqlItem.PROCESSING_MODE_CODE;
		aPlsqlItem.PROCESSING_REQUEST_ID := aSqlItem.PROCESSING_REQUEST_ID;
		aPlsqlItem.TRANSACTION_STATUS_CODE := aSqlItem.TRANSACTION_STATUS_CODE;
		aPlsqlItem.CATEGORY_ID := aSqlItem.CATEGORY_ID;
		aPlsqlItem.QUANTITY := aSqlItem.QUANTITY;
		aPlsqlItem.UNIT_OF_MEASURE := aSqlItem.UNIT_OF_MEASURE;
		aPlsqlItem.INTERFACE_SOURCE_CODE := aSqlItem.INTERFACE_SOURCE_CODE;
		aPlsqlItem.INTERFACE_SOURCE_LINE_ID := aSqlItem.INTERFACE_SOURCE_LINE_ID;
		aPlsqlItem.INV_TRANSACTION_ID := aSqlItem.INV_TRANSACTION_ID;
		aPlsqlItem.ITEM_ID := aSqlItem.ITEM_ID;
		aPlsqlItem.ITEM_DESCRIPTION := aSqlItem.ITEM_DESCRIPTION;
		aPlsqlItem.ITEM_REVISION := aSqlItem.ITEM_REVISION;
		aPlsqlItem.UOM_CODE := aSqlItem.UOM_CODE;
		aPlsqlItem.EMPLOYEE_ID := aSqlItem.EMPLOYEE_ID;
		aPlsqlItem.AUTO_TRANSACT_CODE := aSqlItem.AUTO_TRANSACT_CODE;
		aPlsqlItem.SHIPMENT_HEADER_ID := aSqlItem.SHIPMENT_HEADER_ID;
		aPlsqlItem.SHIPMENT_LINE_ID := aSqlItem.SHIPMENT_LINE_ID;
		aPlsqlItem.SHIP_TO_LOCATION_ID := aSqlItem.SHIP_TO_LOCATION_ID;
		aPlsqlItem.PRIMARY_QUANTITY := aSqlItem.PRIMARY_QUANTITY;
		aPlsqlItem.PRIMARY_UNIT_OF_MEASURE := aSqlItem.PRIMARY_UNIT_OF_MEASURE;
		aPlsqlItem.RECEIPT_SOURCE_CODE := aSqlItem.RECEIPT_SOURCE_CODE;
		aPlsqlItem.VENDOR_ID := aSqlItem.VENDOR_ID;
		aPlsqlItem.VENDOR_SITE_ID := aSqlItem.VENDOR_SITE_ID;
		aPlsqlItem.FROM_ORGANIZATION_ID := aSqlItem.FROM_ORGANIZATION_ID;
		aPlsqlItem.FROM_SUBINVENTORY := aSqlItem.FROM_SUBINVENTORY;
		aPlsqlItem.TO_ORGANIZATION_ID := aSqlItem.TO_ORGANIZATION_ID;
		aPlsqlItem.INTRANSIT_OWNING_ORG_ID := aSqlItem.INTRANSIT_OWNING_ORG_ID;
		aPlsqlItem.ROUTING_HEADER_ID := aSqlItem.ROUTING_HEADER_ID;
		aPlsqlItem.ROUTING_STEP_ID := aSqlItem.ROUTING_STEP_ID;
		aPlsqlItem.SOURCE_DOCUMENT_CODE := aSqlItem.SOURCE_DOCUMENT_CODE;
		aPlsqlItem.PARENT_TRANSACTION_ID := aSqlItem.PARENT_TRANSACTION_ID;
		aPlsqlItem.PO_HEADER_ID := aSqlItem.PO_HEADER_ID;
		aPlsqlItem.PO_REVISION_NUM := aSqlItem.PO_REVISION_NUM;
		aPlsqlItem.PO_RELEASE_ID := aSqlItem.PO_RELEASE_ID;
		aPlsqlItem.PO_LINE_ID := aSqlItem.PO_LINE_ID;
		aPlsqlItem.PO_LINE_LOCATION_ID := aSqlItem.PO_LINE_LOCATION_ID;
		aPlsqlItem.PO_UNIT_PRICE := aSqlItem.PO_UNIT_PRICE;
		aPlsqlItem.CURRENCY_CODE := aSqlItem.CURRENCY_CODE;
		aPlsqlItem.CURRENCY_CONVERSION_TYPE := aSqlItem.CURRENCY_CONVERSION_TYPE;
		aPlsqlItem.CURRENCY_CONVERSION_RATE := aSqlItem.CURRENCY_CONVERSION_RATE;
		aPlsqlItem.CURRENCY_CONVERSION_DATE := aSqlItem.CURRENCY_CONVERSION_DATE;
		aPlsqlItem.PO_DISTRIBUTION_ID := aSqlItem.PO_DISTRIBUTION_ID;
		aPlsqlItem.REQUISITION_LINE_ID := aSqlItem.REQUISITION_LINE_ID;
		aPlsqlItem.REQ_DISTRIBUTION_ID := aSqlItem.REQ_DISTRIBUTION_ID;
		aPlsqlItem.CHARGE_ACCOUNT_ID := aSqlItem.CHARGE_ACCOUNT_ID;
		aPlsqlItem.SUBSTITUTE_UNORDERED_CODE := aSqlItem.SUBSTITUTE_UNORDERED_CODE;
		aPlsqlItem.RECEIPT_EXCEPTION_FLAG := aSqlItem.RECEIPT_EXCEPTION_FLAG;
		aPlsqlItem.ACCRUAL_STATUS_CODE := aSqlItem.ACCRUAL_STATUS_CODE;
		aPlsqlItem.INSPECTION_STATUS_CODE := aSqlItem.INSPECTION_STATUS_CODE;
		aPlsqlItem.INSPECTION_QUALITY_CODE := aSqlItem.INSPECTION_QUALITY_CODE;
		aPlsqlItem.DESTINATION_TYPE_CODE := aSqlItem.DESTINATION_TYPE_CODE;
		aPlsqlItem.DELIVER_TO_PERSON_ID := aSqlItem.DELIVER_TO_PERSON_ID;
		aPlsqlItem.LOCATION_ID := aSqlItem.LOCATION_ID;
		aPlsqlItem.DELIVER_TO_LOCATION_ID := aSqlItem.DELIVER_TO_LOCATION_ID;
		aPlsqlItem.SUBINVENTORY := aSqlItem.SUBINVENTORY;
		aPlsqlItem.LOCATOR_ID := aSqlItem.LOCATOR_ID;
		aPlsqlItem.WIP_ENTITY_ID := aSqlItem.WIP_ENTITY_ID;
		aPlsqlItem.WIP_LINE_ID := aSqlItem.WIP_LINE_ID;
		aPlsqlItem.DEPARTMENT_CODE := aSqlItem.DEPARTMENT_CODE;
		aPlsqlItem.WIP_REPETITIVE_SCHEDULE_ID := aSqlItem.WIP_REPETITIVE_SCHEDULE_ID;
		aPlsqlItem.WIP_OPERATION_SEQ_NUM := aSqlItem.WIP_OPERATION_SEQ_NUM;
		aPlsqlItem.WIP_RESOURCE_SEQ_NUM := aSqlItem.WIP_RESOURCE_SEQ_NUM;
		aPlsqlItem.BOM_RESOURCE_ID := aSqlItem.BOM_RESOURCE_ID;
		aPlsqlItem.SHIPMENT_NUM := aSqlItem.SHIPMENT_NUM;
		aPlsqlItem.FREIGHT_CARRIER_CODE := aSqlItem.FREIGHT_CARRIER_CODE;
		aPlsqlItem.BILL_OF_LADING := aSqlItem.BILL_OF_LADING;
		aPlsqlItem.PACKING_SLIP := aSqlItem.PACKING_SLIP;
		aPlsqlItem.SHIPPED_DATE := aSqlItem.SHIPPED_DATE;
		aPlsqlItem.EXPECTED_RECEIPT_DATE := aSqlItem.EXPECTED_RECEIPT_DATE;
		aPlsqlItem.ACTUAL_COST := aSqlItem.ACTUAL_COST;
		aPlsqlItem.TRANSFER_COST := aSqlItem.TRANSFER_COST;
		aPlsqlItem.TRANSPORTATION_COST := aSqlItem.TRANSPORTATION_COST;
		aPlsqlItem.TRANSPORTATION_ACCOUNT_ID := aSqlItem.TRANSPORTATION_ACCOUNT_ID;
		aPlsqlItem.NUM_OF_CONTAINERS := aSqlItem.NUM_OF_CONTAINERS;
		aPlsqlItem.WAYBILL_AIRBILL_NUM := aSqlItem.WAYBILL_AIRBILL_NUM;
		aPlsqlItem.VENDOR_ITEM_NUM := aSqlItem.VENDOR_ITEM_NUM;
		aPlsqlItem.VENDOR_LOT_NUM := aSqlItem.VENDOR_LOT_NUM;
		aPlsqlItem.RMA_REFERENCE := aSqlItem.RMA_REFERENCE;
		aPlsqlItem.COMMENTS := aSqlItem.COMMENTS;
		aPlsqlItem.ATTRIBUTE_CATEGORY := aSqlItem.ATTRIBUTE_CATEGORY;
		aPlsqlItem.ATTRIBUTE1 := aSqlItem.ATTRIBUTE1;
		aPlsqlItem.ATTRIBUTE2 := aSqlItem.ATTRIBUTE2;
		aPlsqlItem.ATTRIBUTE3 := aSqlItem.ATTRIBUTE3;
		aPlsqlItem.ATTRIBUTE4 := aSqlItem.ATTRIBUTE4;
		aPlsqlItem.ATTRIBUTE5 := aSqlItem.ATTRIBUTE5;
		aPlsqlItem.ATTRIBUTE6 := aSqlItem.ATTRIBUTE6;
		aPlsqlItem.ATTRIBUTE7 := aSqlItem.ATTRIBUTE7;
		aPlsqlItem.ATTRIBUTE9 := aSqlItem.ATTRIBUTE9;
		aPlsqlItem.ATTRIBUTE10 := aSqlItem.ATTRIBUTE10;
		aPlsqlItem.ATTRIBUTE11 := aSqlItem.ATTRIBUTE11;
		aPlsqlItem.ATTRIBUTE12 := aSqlItem.ATTRIBUTE12;
		aPlsqlItem.ATTRIBUTE13 := aSqlItem.ATTRIBUTE13;
		aPlsqlItem.ATTRIBUTE14 := aSqlItem.ATTRIBUTE14;
		aPlsqlItem.ATTRIBUTE15 := aSqlItem.ATTRIBUTE15;
		aPlsqlItem.SHIP_HEAD_ATTRIBUTE_CATEGORY := aSqlItem.SHIP_HEAD_ATTRIBUTE_CATEGORY;
		aPlsqlItem.SHIP_HEAD_ATTRIBUTE1 := aSqlItem.SHIP_HEAD_ATTRIBUTE1;
		aPlsqlItem.SHIP_HEAD_ATTRIBUTE2 := aSqlItem.SHIP_HEAD_ATTRIBUTE2;
		aPlsqlItem.SHIP_HEAD_ATTRIBUTE3 := aSqlItem.SHIP_HEAD_ATTRIBUTE3;
		aPlsqlItem.SHIP_HEAD_ATTRIBUTE4 := aSqlItem.SHIP_HEAD_ATTRIBUTE4;
		aPlsqlItem.SHIP_HEAD_ATTRIBUTE5 := aSqlItem.SHIP_HEAD_ATTRIBUTE5;
		aPlsqlItem.SHIP_HEAD_ATTRIBUTE6 := aSqlItem.SHIP_HEAD_ATTRIBUTE6;
		aPlsqlItem.SHIP_HEAD_ATTRIBUTE7 := aSqlItem.SHIP_HEAD_ATTRIBUTE7;
		aPlsqlItem.SHIP_HEAD_ATTRIBUTE8 := aSqlItem.SHIP_HEAD_ATTRIBUTE8;
		aPlsqlItem.SHIP_HEAD_ATTRIBUTE9 := aSqlItem.SHIP_HEAD_ATTRIBUTE9;
		aPlsqlItem.SHIP_HEAD_ATTRIBUTE10 := aSqlItem.SHIP_HEAD_ATTRIBUTE10;
		aPlsqlItem.SHIP_HEAD_ATTRIBUTE11 := aSqlItem.SHIP_HEAD_ATTRIBUTE11;
		aPlsqlItem.SHIP_HEAD_ATTRIBUTE12 := aSqlItem.SHIP_HEAD_ATTRIBUTE12;
		aPlsqlItem.SHIP_HEAD_ATTRIBUTE13 := aSqlItem.SHIP_HEAD_ATTRIBUTE13;
		aPlsqlItem.SHIP_HEAD_ATTRIBUTE14 := aSqlItem.SHIP_HEAD_ATTRIBUTE14;
		aPlsqlItem.SHIP_HEAD_ATTRIBUTE15 := aSqlItem.SHIP_HEAD_ATTRIBUTE15;
		aPlsqlItem.SHIP_LINE_ATTRIBUTE_CATEGORY := aSqlItem.SHIP_LINE_ATTRIBUTE_CATEGORY;
		aPlsqlItem.SHIP_LINE_ATTRIBUTE1 := aSqlItem.SHIP_LINE_ATTRIBUTE1;
		aPlsqlItem.SHIP_LINE_ATTRIBUTE2 := aSqlItem.SHIP_LINE_ATTRIBUTE2;
		aPlsqlItem.SHIP_LINE_ATTRIBUTE3 := aSqlItem.SHIP_LINE_ATTRIBUTE3;
		aPlsqlItem.SHIP_LINE_ATTRIBUTE4 := aSqlItem.SHIP_LINE_ATTRIBUTE4;
		aPlsqlItem.SHIP_LINE_ATTRIBUTE5 := aSqlItem.SHIP_LINE_ATTRIBUTE5;
		aPlsqlItem.SHIP_LINE_ATTRIBUTE6 := aSqlItem.SHIP_LINE_ATTRIBUTE6;
		aPlsqlItem.SHIP_LINE_ATTRIBUTE7 := aSqlItem.SHIP_LINE_ATTRIBUTE7;
		aPlsqlItem.SHIP_LINE_ATTRIBUTE8 := aSqlItem.SHIP_LINE_ATTRIBUTE8;
		aPlsqlItem.SHIP_LINE_ATTRIBUTE9 := aSqlItem.SHIP_LINE_ATTRIBUTE9;
		aPlsqlItem.SHIP_LINE_ATTRIBUTE10 := aSqlItem.SHIP_LINE_ATTRIBUTE10;
		aPlsqlItem.SHIP_LINE_ATTRIBUTE11 := aSqlItem.SHIP_LINE_ATTRIBUTE11;
		aPlsqlItem.SHIP_LINE_ATTRIBUTE12 := aSqlItem.SHIP_LINE_ATTRIBUTE12;
		aPlsqlItem.SHIP_LINE_ATTRIBUTE13 := aSqlItem.SHIP_LINE_ATTRIBUTE13;
		aPlsqlItem.SHIP_LINE_ATTRIBUTE14 := aSqlItem.SHIP_LINE_ATTRIBUTE14;
		aPlsqlItem.SHIP_LINE_ATTRIBUTE15 := aSqlItem.SHIP_LINE_ATTRIBUTE15;
		aPlsqlItem.USSGL_TRANSACTION_CODE := aSqlItem.USSGL_TRANSACTION_CODE;
		aPlsqlItem.GOVERNMENT_CONTEXT := aSqlItem.GOVERNMENT_CONTEXT;
		aPlsqlItem.REASON_ID := aSqlItem.REASON_ID;
		aPlsqlItem.DESTINATION_CONTEXT := aSqlItem.DESTINATION_CONTEXT;
		aPlsqlItem.SOURCE_DOC_QUANTITY := aSqlItem.SOURCE_DOC_QUANTITY;
		aPlsqlItem.SOURCE_DOC_UNIT_OF_MEASURE := aSqlItem.SOURCE_DOC_UNIT_OF_MEASURE;
		aPlsqlItem.MOVEMENT_ID := aSqlItem.MOVEMENT_ID;
		aPlsqlItem.HEADER_INTERFACE_ID := aSqlItem.HEADER_INTERFACE_ID;
		aPlsqlItem.VENDOR_CUM_SHIPPED_QTY := aSqlItem.VENDOR_CUM_SHIPPED_QTY;
		aPlsqlItem.ITEM_NUM := aSqlItem.ITEM_NUM;
		aPlsqlItem.DOCUMENT_NUM := aSqlItem.DOCUMENT_NUM;
		aPlsqlItem.DOCUMENT_LINE_NUM := aSqlItem.DOCUMENT_LINE_NUM;
		aPlsqlItem.TRUCK_NUM := aSqlItem.TRUCK_NUM;
		aPlsqlItem.SHIP_TO_LOCATION_CODE := aSqlItem.SHIP_TO_LOCATION_CODE;
		aPlsqlItem.CONTAINER_NUM := aSqlItem.CONTAINER_NUM;
		aPlsqlItem.SUBSTITUTE_ITEM_NUM := aSqlItem.SUBSTITUTE_ITEM_NUM;
		aPlsqlItem.NOTICE_UNIT_PRICE := aSqlItem.NOTICE_UNIT_PRICE;
		aPlsqlItem.ITEM_CATEGORY := aSqlItem.ITEM_CATEGORY;
		aPlsqlItem.LOCATION_CODE := aSqlItem.LOCATION_CODE;
		aPlsqlItem.VENDOR_NAME := aSqlItem.VENDOR_NAME;
		aPlsqlItem.VENDOR_NUM := aSqlItem.VENDOR_NUM;
		aPlsqlItem.VENDOR_SITE_CODE := aSqlItem.VENDOR_SITE_CODE;
		aPlsqlItem.FROM_ORGANIZATION_CODE := aSqlItem.FROM_ORGANIZATION_CODE;
		aPlsqlItem.TO_ORGANIZATION_CODE := aSqlItem.TO_ORGANIZATION_CODE;
		aPlsqlItem.INTRANSIT_OWNING_ORG_CODE := aSqlItem.INTRANSIT_OWNING_ORG_CODE;
		aPlsqlItem.ROUTING_CODE := aSqlItem.ROUTING_CODE;
		aPlsqlItem.ROUTING_STEP := aSqlItem.ROUTING_STEP;
		aPlsqlItem.RELEASE_NUM := aSqlItem.RELEASE_NUM;
		aPlsqlItem.DOCUMENT_SHIPMENT_LINE_NUM := aSqlItem.DOCUMENT_SHIPMENT_LINE_NUM;
		aPlsqlItem.DOCUMENT_DISTRIBUTION_NUM := aSqlItem.DOCUMENT_DISTRIBUTION_NUM;
		aPlsqlItem.DELIVER_TO_PERSON_NAME := aSqlItem.DELIVER_TO_PERSON_NAME;
		aPlsqlItem.DELIVER_TO_LOCATION_CODE := aSqlItem.DELIVER_TO_LOCATION_CODE;
		aPlsqlItem.USE_MTL_LOT := aSqlItem.USE_MTL_LOT;
		aPlsqlItem.USE_MTL_SERIAL := aSqlItem.USE_MTL_SERIAL;
		aPlsqlItem.LOCATOR := aSqlItem.LOCATOR;
		aPlsqlItem.REASON_NAME := aSqlItem.REASON_NAME;
		aPlsqlItem.VALIDATION_FLAG := aSqlItem.VALIDATION_FLAG;
		aPlsqlItem.SUBSTITUTE_ITEM_ID := aSqlItem.SUBSTITUTE_ITEM_ID;
		aPlsqlItem.QUANTITY_SHIPPED := aSqlItem.QUANTITY_SHIPPED;
		aPlsqlItem.QUANTITY_INVOICED := aSqlItem.QUANTITY_INVOICED;
		aPlsqlItem.TAX_NAME := aSqlItem.TAX_NAME;
		aPlsqlItem.TAX_AMOUNT := aSqlItem.TAX_AMOUNT;
		aPlsqlItem.REQ_NUM := aSqlItem.REQ_NUM;
		aPlsqlItem.REQ_LINE_NUM := aSqlItem.REQ_LINE_NUM;
		aPlsqlItem.REQ_DISTRIBUTION_NUM := aSqlItem.REQ_DISTRIBUTION_NUM;
		aPlsqlItem.WIP_ENTITY_NAME := aSqlItem.WIP_ENTITY_NAME;
		aPlsqlItem.WIP_LINE_CODE := aSqlItem.WIP_LINE_CODE;
		aPlsqlItem.RESOURCE_CODE := aSqlItem.RESOURCE_CODE;
		aPlsqlItem.SHIPMENT_LINE_STATUS_CODE := aSqlItem.SHIPMENT_LINE_STATUS_CODE;
		aPlsqlItem.BARCODE_LABEL := aSqlItem.BARCODE_LABEL;
		aPlsqlItem.TRANSFER_PERCENTAGE := aSqlItem.TRANSFER_PERCENTAGE;
		aPlsqlItem.QA_COLLECTION_ID := aSqlItem.QA_COLLECTION_ID;
		aPlsqlItem.COUNTRY_OF_ORIGIN_CODE := aSqlItem.COUNTRY_OF_ORIGIN_CODE;
		aPlsqlItem.OE_ORDER_HEADER_ID := aSqlItem.OE_ORDER_HEADER_ID;
		aPlsqlItem.OE_ORDER_LINE_ID := aSqlItem.OE_ORDER_LINE_ID;
		aPlsqlItem.CUSTOMER_ID := aSqlItem.CUSTOMER_ID;
		aPlsqlItem.CUSTOMER_SITE_ID := aSqlItem.CUSTOMER_SITE_ID;
		aPlsqlItem.CUSTOMER_ITEM_NUM := aSqlItem.CUSTOMER_ITEM_NUM;
		aPlsqlItem.CREATE_DEBIT_MEMO_FLAG := aSqlItem.CREATE_DEBIT_MEMO_FLAG;
		aPlsqlItem.PUT_AWAY_RULE_ID := aSqlItem.PUT_AWAY_RULE_ID;
		aPlsqlItem.PUT_AWAY_STRATEGY_ID := aSqlItem.PUT_AWAY_STRATEGY_ID;
		aPlsqlItem.LPN_ID := aSqlItem.LPN_ID;
		aPlsqlItem.TRANSFER_LPN_ID := aSqlItem.TRANSFER_LPN_ID;
		aPlsqlItem.COST_GROUP_ID := aSqlItem.COST_GROUP_ID;
		aPlsqlItem.MOBILE_TXN := aSqlItem.MOBILE_TXN;
		aPlsqlItem.MMTT_TEMP_ID := aSqlItem.MMTT_TEMP_ID;
		aPlsqlItem.TRANSFER_COST_GROUP_ID := aSqlItem.TRANSFER_COST_GROUP_ID;
		aPlsqlItem.SECONDARY_QUANTITY := aSqlItem.SECONDARY_QUANTITY;
		aPlsqlItem.SECONDARY_UNIT_OF_MEASURE := aSqlItem.SECONDARY_UNIT_OF_MEASURE;
		aPlsqlItem.SECONDARY_UOM_CODE := aSqlItem.SECONDARY_UOM_CODE;
		aPlsqlItem.QC_GRADE := aSqlItem.QC_GRADE;
		aPlsqlItem.FROM_LOCATOR := aSqlItem.FROM_LOCATOR;
		aPlsqlItem.FROM_LOCATOR_ID := aSqlItem.FROM_LOCATOR_ID;
		aPlsqlItem.PARENT_SOURCE_TRANSACTION_NUM := aSqlItem.PARENT_SOURCE_TRANSACTION_NUM;
		aPlsqlItem.INTERFACE_AVAILABLE_QTY := aSqlItem.INTERFACE_AVAILABLE_QTY;
		aPlsqlItem.INTERFACE_TRANSACTION_QTY := aSqlItem.INTERFACE_TRANSACTION_QTY;
		aPlsqlItem.INTERFACE_AVAILABLE_AMT := aSqlItem.INTERFACE_AVAILABLE_AMT;
		aPlsqlItem.INTERFACE_TRANSACTION_AMT := aSqlItem.INTERFACE_TRANSACTION_AMT;
		aPlsqlItem.LICENSE_PLATE_NUMBER := aSqlItem.LICENSE_PLATE_NUMBER;
		aPlsqlItem.SOURCE_TRANSACTION_NUM := aSqlItem.SOURCE_TRANSACTION_NUM;
		aPlsqlItem.TRANSFER_LICENSE_PLATE_NUMBER := aSqlItem.TRANSFER_LICENSE_PLATE_NUMBER;
		aPlsqlItem.LPN_GROUP_ID := aSqlItem.LPN_GROUP_ID;
		aPlsqlItem.ORDER_TRANSACTION_ID := aSqlItem.ORDER_TRANSACTION_ID;
		aPlsqlItem.CUSTOMER_ACCOUNT_NUMBER := aSqlItem.CUSTOMER_ACCOUNT_NUMBER;
		aPlsqlItem.CUSTOMER_PARTY_NAME := aSqlItem.CUSTOMER_PARTY_NAME;
		aPlsqlItem.OE_ORDER_LINE_NUM := aSqlItem.OE_ORDER_LINE_NUM;
		aPlsqlItem.OE_ORDER_NUM := aSqlItem.OE_ORDER_NUM;
		aPlsqlItem.PARENT_INTERFACE_TXN_ID := aSqlItem.PARENT_INTERFACE_TXN_ID;
		aPlsqlItem.CUSTOMER_ITEM_ID := aSqlItem.CUSTOMER_ITEM_ID;
		aPlsqlItem.AMOUNT := aSqlItem.AMOUNT;
		aPlsqlItem.JOB_ID := aSqlItem.JOB_ID;
		aPlsqlItem.TIMECARD_ID := aSqlItem.TIMECARD_ID;
		aPlsqlItem.TIMECARD_OVN := aSqlItem.TIMECARD_OVN;
		aPlsqlItem.ERECORD_ID := aSqlItem.ERECORD_ID;
		aPlsqlItem.PROJECT_ID := aSqlItem.PROJECT_ID;
		aPlsqlItem.TASK_ID := aSqlItem.TASK_ID;
		aPlsqlItem.ASN_ATTACH_ID := aSqlItem.ASN_ATTACH_ID;
		aPlsqlItem.ORG_ID := aSqlItem.ORG_ID;
		aPlsqlItem.OPERATING_UNIT := aSqlItem.OPERATING_UNIT;
		aPlsqlItem.REQUESTED_AMOUNT := aSqlItem.REQUESTED_AMOUNT;
		aPlsqlItem.MATERIAL_STORED_AMOUNT := aSqlItem.MATERIAL_STORED_AMOUNT;
		aPlsqlItem.AMOUNT_SHIPPED := aSqlItem.AMOUNT_SHIPPED;
		aPlsqlItem.MATCHING_BASIS := aSqlItem.MATCHING_BASIS;
		aPlsqlItem.REPLENISH_ORDER_LINE_ID := aSqlItem.REPLENISH_ORDER_LINE_ID;
		aPlsqlItem.E0346_STATUS_FLAG := aSqlItem.E0346_STATUS_FLAG;
		aPlsqlItem.OD_RCV_ERROR_DESCRIPTION := aSqlItem.OD_RCV_ERROR_DESCRIPTION;
		aPlsqlItem.ATTRIBUTE8 := aSqlItem.ATTRIBUTE8;
		aPlsqlItem.OD_RVC_CORRECTION_FLAG := aSqlItem.OD_RVC_CORRECTION_FLAG;
		aPlsqlItem.OD_RCV_STATUS_FLAG := aSqlItem.OD_RCV_STATUS_FLAG;
		aPlsqlItem.LEGACY_TRANSACTION_TYPE := aSqlItem.LEGACY_TRANSACTION_TYPE;
		RETURN aPlsqlItem;
	END SQL_TO_PL11;
	FUNCTION PL_TO_SQL10(aPlsqlItem XX_GI_RECEIVING_PKG.DETAIL_TBL_TYPE)
 	RETURN XX_GI_RECEIVING_PKG_DETAIL_T8 IS 
	aSqlItem XX_GI_RECEIVING_PKG_DETAIL_T8; 
	BEGIN 
		-- initialize the table 
		aSqlItem := XX_GI_RECEIVING_PKG_DETAIL_T8();
		aSqlItem.EXTEND(aPlsqlItem.COUNT);
		FOR I IN aPlsqlItem.FIRST..aPlsqlItem.LAST LOOP
			aSqlItem(I + 1 - aPlsqlItem.FIRST) := PL_TO_SQL11(aPlsqlItem(I));
		END LOOP; 
		RETURN aSqlItem;
	END PL_TO_SQL10;
	FUNCTION SQL_TO_PL10(aSqlItem XX_GI_RECEIVING_PKG_DETAIL_T8) 
	RETURN XX_GI_RECEIVING_PKG.DETAIL_TBL_TYPE IS 
	aPlsqlItem XX_GI_RECEIVING_PKG.DETAIL_TBL_TYPE; 
	BEGIN 
		FOR I IN 1..aSqlItem.COUNT LOOP
			aPlsqlItem(I) := SQL_TO_PL11(aSqlItem(I));
		END LOOP; 
		RETURN aPlsqlItem;
	END SQL_TO_PL10;

   PROCEDURE XX_GI_RECEIVING_PKG$POPULATE_ (X_KEYREC_REC IN OUT XX_GI_RECEIVING_PKG_ROWTYPE_6,X_HEADER_REC IN OUT XX_GI_RECEIVING_PKG_ROWTYPE_7,X_DETAIL_TBL IN OUT XX_GI_RECEIVING_PKG_DETAIL_T8,X_RETURN_STATUS OUT VARCHAR2,X_RETURN_MESSAGE OUT VARCHAR2) IS
      X_KEYREC_REC_ ROWTYPE_PL0;
      X_HEADER_REC_ ROWTYPE_PL1;
      X_DETAIL_TBL_ APPS.XX_GI_RECEIVING_PKG.DETAIL_TBL_TYPE;
   BEGIN
      X_KEYREC_REC_ := BPEL_PLPOPULATERRCVPOSTAGEPROC.SQL_TO_PL8(X_KEYREC_REC);
      X_HEADER_REC_ := BPEL_PLPOPULATERRCVPOSTAGEPROC.SQL_TO_PL9(X_HEADER_REC);
      X_DETAIL_TBL_ := BPEL_PLPOPULATERRCVPOSTAGEPROC.SQL_TO_PL10(X_DETAIL_TBL);
      APPS.XX_GI_RECEIVING_PKG.POPULATE_STG_PO_RECEIVING_DATA(X_KEYREC_REC_,X_HEADER_REC_,X_DETAIL_TBL_,X_RETURN_STATUS,X_RETURN_MESSAGE);
      X_KEYREC_REC := BPEL_PLPOPULATERRCVPOSTAGEPROC.PL_TO_SQL8(X_KEYREC_REC_);
      X_HEADER_REC := BPEL_PLPOPULATERRCVPOSTAGEPROC.PL_TO_SQL9(X_HEADER_REC_);
      X_DETAIL_TBL := BPEL_PLPOPULATERRCVPOSTAGEPROC.PL_TO_SQL10(X_DETAIL_TBL_);
   END XX_GI_RECEIVING_PKG$POPULATE_;

END BPEL_PLPOPULATERRCVPOSTAGEPROC;
/
show errors
exit
