<?xml version="1.0" encoding="UTF-8"?>
<definitions 
    name="GLStgTableInsert"
    targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GLStgTableInsert/"
    xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/GLStgTableInsert/"
    xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
    xmlns:pc="http://xmlns.oracle.com/pcbpel/"
    xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GLStgTableInsert"
    xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/db/"
    xmlns="http://schemas.xmlsoap.org/wsdl/">

    <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/" location="DBAdapterOutboundHeader.wsdl"/>

    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GLStgTableInsert"
                schemaLocation="GLStgTableInsert_table.xsd"/>
        </schema>
    </types>

    <message name="XxGlInterfaceNaStgCollection_msg">
        <part name="XxGlInterfaceNaStgCollection" element="top:XxGlInterfaceNaStgCollection"/>
    </message>


    <portType name="GLStgTableInsert_ptt">
        <operation name="insert">
            <input message="tns:XxGlInterfaceNaStgCollection_msg"/>
        </operation>
    </portType>

    <binding name="GLStgTableInsert_binding" type="tns:GLStgTableInsert_ptt">
        <jca:binding />
        <operation name="insert">
            <jca:operation
                InteractionSpec="oracle.tip.adapter.db.DBWriteInteractionSpec"

                DescriptorName="GLStgTableInsert.XxGlInterfaceNaStg"
                DmlType="insert"
                DetectOmissions="true"
                OptimizeMerge="true"
                MappingsMetaDataURL="GLStgTableInsert_toplink_mappings.xml" />
            <input>
                <jca:header message="hdr:OutboundHeader_msg" part="outboundHeader"/>
            </input>
        </operation>
    </binding>

    <!-- Your runtime connection is declared in
        J2EE_HOME/application-deployments/default/DbAdapter/oc4j-ra.xml
        These 'mcf' properties here are from your design time connection and 
        save you from having to edit that file and restart the application server
        if eis/db/EBSApps is missing.
        These 'mcf' properties are safe to remove.
    -->
    <service name="GLStgTableInsert">
        <port name="GLStgTableInsert_pt" binding="tns:GLStgTableInsert_binding">
            <jca:address location="eis/db/EBSAppsFin"
                UIConnectionName="EIS_APPS_EBS_APPS_DBConn"
                ManagedConnectionFactory="oracle.tip.adapter.db.DBManagedConnectionFactory"
            />
        </port>
    </service>

    <plt:partnerLinkType name="GLStgTableInsert_plt" >
        <plt:role name="GLStgTableInsert_role" >
            <plt:portType name="tns:GLStgTableInsert_ptt" />
        </plt:role>
    </plt:partnerLinkType>

</definitions>
