<definitions
     name="SendSalesOrderInfo"
     targetNamespace="http://xmlns.oracle.com/SendSalesOrderInfo"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://www.openapplications.org/oagis/9"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:ns2="http://schemas.oracle.com/bpel/extension"
     xmlns:client="http://xmlns.oracle.com/SendSalesOrderInfo"
    >
    <import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/SendSalesOrderInfo" schemaLocation="SendSalesOrderInfo.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.openapplications.org/oagis/9" schemaLocation="CreateOrder.xsd"/>
        </xsd:schema>
    </types>
    <message name="SendSalesOrderInfoRequestMessage">
        <part name="payload" element="client:SendSalesOrderInfoProcessRequest"/>
    </message>
    <message name="SendSalesOrderInfoResponseMessage">
        <part name="payload" element="client:SendSalesOrderInfoProcessResponse"/>
    </message>
    <portType name="SendSalesOrderInfo">
        <operation name="process">
            <input message="client:SendSalesOrderInfoRequestMessage"/>
            <output message="client:SendSalesOrderInfoResponseMessage"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="SendSalesOrderInfo">
        <plnk:role name="SendSalesOrderInfoProvider">
            <plnk:portType name="client:SendSalesOrderInfo"/>
        </plnk:role>
    </plnk:partnerLinkType>
</definitions>
