package od.oracle.apps.xxmer.plmpjrdashboard.lov.server;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class OD_PLMPJRDashboardLOVAMImpl extends OAApplicationModuleImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public OD_PLMPJRDashboardLOVAMImpl()
  {
  }

  /**
   * 
   * Container's getter for OD_TaskNameLOVVO
   */
  public OD_TaskNameLOVVOImpl getOD_TaskNameLOVVO()
  {
    return (OD_TaskNameLOVVOImpl)findViewObject("OD_TaskNameLOVVO");
  }

  /**
   * 
   * Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("od.oracle.apps.xxmer.plmpjrdashboard.lov.server", "OD_PLMPJRDashboardLOVAMLocal");
  }

  /**
   * 
   * Container's getter for OD_ProjectNameNumberLOVVO
   */
  public OD_ProjectNameNumberLOVVOImpl getOD_ProjectNameNumberLOVVO()
  {
    return (OD_ProjectNameNumberLOVVOImpl)findViewObject("OD_ProjectNameNumberLOVVO");
  }

  /**
   * 
   * Container's getter for OD_DivisionNameLOVVO
   */
  public OD_DivisionNameLOVVOImpl getOD_DivisionNameLOVVO()
  {
    return (OD_DivisionNameLOVVOImpl)findViewObject("OD_DivisionNameLOVVO");
  }

  /**
   * 
   * Container's getter for OD_DepartmentLOVVO
   */
  public OD_DepartmentLOVVOImpl getOD_DepartmentLOVVO()
  {
    return (OD_DepartmentLOVVOImpl)findViewObject("OD_DepartmentLOVVO");
  }

  /**
   * 
   * Container's getter for OD_ClassNameLOVVO
   */
  public OD_ClassNameLOVVOImpl getOD_ClassNameLOVVO()
  {
    return (OD_ClassNameLOVVOImpl)findViewObject("OD_ClassNameLOVVO");
  }

  /**
   * 
   * Container's getter for OD_TaskStatusLOVVO
   */
  public OD_TaskStatusLOVVOImpl getOD_TaskStatusLOVVO()
  {
    return (OD_TaskStatusLOVVOImpl)findViewObject("OD_TaskStatusLOVVO");
  }

  /**
   * 
   * Container's getter for OD_AssingUserLOVVO
   */
  public OD_AssingUserLOVVOImpl getOD_AssingUserLOVVO()
  {
    return (OD_AssingUserLOVVOImpl)findViewObject("OD_AssingUserLOVVO");
  }

  /**
   * 
   * Container's getter for OD_ProjectResourceLOVVO
   */
  public OD_ProjectResourceLOVVOImpl getOD_ProjectResourceLOVVO()
  {
    return (OD_ProjectResourceLOVVOImpl)findViewObject("OD_ProjectResourceLOVVO");
  }
}