<definitions
     name="ProcessInvoiceRealTime"
     targetNamespace="http://xmlns.oracle.com/ProcessInvoiceRealTime"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://www.openapplications.org/oagis/9"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/ProcessInvoiceRealTime"
    >
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.openapplications.org/oagis/9"
             xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:client="http://xmlns.oracle.com/ProcessInvoiceRealTime">
            <import namespace="http://xmlns.oracle.com/ProcessInvoiceRealTime" schemaLocation="ProcessInvoiceRealTime.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.openapplications.org/oagis/9"
             xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:client="http://xmlns.oracle.com/ProcessInvoiceRealTime">
            <xsd:import namespace="http://www.openapplications.org/oagis/9" schemaLocation="http://chilsoa01d.na.odcorp.net:7778/orabpel/xmllib/eaixml/oagis/v91/message/bod/ProcessInvoice.xsd"/>
        </xsd:schema>
    </types>
    <message name="ProcessInvoiceRealTimeResponseMessage">
        <part name="payload" element="client:ProcessInvoiceRealTimeProcessResponse"/>
    </message>
    <message name="ProcessInvoiceRealTimeRequestMessage">
        <part name="payload" element="ns1:ProcessInvoice"/>
    </message>
    <portType name="ProcessInvoiceRealTime">
        <operation name="process">
            <input message="client:ProcessInvoiceRealTimeRequestMessage"/>
            <output message="client:ProcessInvoiceRealTimeResponseMessage"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="ProcessInvoiceRealTime">
        <plnk:role name="ProcessInvoiceRealTimeProvider">
            <plnk:portType name="client:ProcessInvoiceRealTime"/>
        </plnk:role>
    </plnk:partnerLinkType>
</definitions>
