

DROP PROCEDURE ImportCustomer;
DROP PROCEDURE ImportClientSKU;
DROP PROCEDURE ImportCustExemptCert;

DROP TABLE CUSTOMER_TEMP;
DROP TABLE CUSTOMER_EXEMPTION_TEMP;
DROP TABLE CLIENT_GOODSVC_TEMP;
DROP TABLE IMPORT_ERROR_TEMP;

COMMIT;
QUIT;