
CREATE TABLE CUSTOMER_TEMP
(
  OU_CODE NVARCHAR2(40) ,
  BUSINESS_PARTY_CODE NVARCHAR2(40) ,
  BUSINESS_PARTY_NAME NVARCHAR2(40) ,
  THIRD_PARTY_FLAG CHAR(1) ,
  ENTITY_USE_ID NUMBER(9) 
);

CREATE TABLE CUSTOMER_EXEMPTION_TEMP
(
  ENTITY_USE_ID NUMBER(9),
  BUSINESS_PARTY_CODE NVARCHAR2(40),
  BUSINESS_PARTY_NAME NVARCHAR2(40),
  EXEMPTION_CERT_NO NVARCHAR2(40),
  COUNTRY NVARCHAR2(100),
  STATE NVARCHAR2(100),
  EFFECTIVE_DATE DATE,
  EXPIRY_DATE DATE,
  APPLY_TO_SUBTJ CHAR(1),
  RECEIVED_FLAG CHAR(1)
);

CREATE TABLE CLIENT_GOODSVC_TEMP
(
  OU_CODE NVARCHAR2(40),
  CLIENT_SKU_START_CODE NVARCHAR2(40),
  CLIENT_SKU_END_CODE NVARCHAR2(40),
  GSC_ID NUMBER(9)
);


CREATE TABLE IMPORT_ERROR_TEMP
(
  MESSAGE  VARCHAR2(1024),
  TIMERECORDED  TIMESTAMP  DEFAULT CURRENT_TIMESTAMP     NOT NULL
);

COMMIT;
QUIT;
