DELETE FROM EXEMPTION_CERTIFICATE
WHERE (UPPER(CREATED_BY) = 'IMPORT') 
	  AND (TO_CHAR(CREATED_DATE) = TO_CHAR(SYSDATE));

DELETE FROM BUSINESS_PARTY_ENTITY_USE
WHERE (UPPER(CREATED_BY) = 'IMPORT') 
	  AND (TO_CHAR(CREATED_DATE) = TO_CHAR(SYSDATE));

DELETE FROM BUSINESS_PARTY
WHERE (UPPER(CREATED_BY) = 'IMPORT') 
	  AND (TO_CHAR(CREATED_DATE) = TO_CHAR(SYSDATE));

DELETE FROM CLIENT_SKU
WHERE (UPPER(CREATED_BY) = 'IMPORT') 
	  AND (TO_CHAR(CREATED_DATE) = TO_CHAR(SYSDATE));

COMMIT;