
REM XXOM XX_CS_SR_ITEMS_LINK

  CREATE TABLE "XXOM"."XX_CS_SR_ITEMS_LINK" 
   (	"SERVICE_REQUEST_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_NUMBER" VARCHAR2(50 BYTE), 
	"ITEM_DESCRIPTION" VARCHAR2(200 BYTE), 
	"QUANTITY" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(50 BYTE), 
	"ORDER_LINK" VARCHAR2(2000 BYTE), 
	"ATTRIBUTE1" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE2" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE3" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE5" VARCHAR2(1000 BYTE)
   ) ;
 
REM XXOM XX_CS_SR_ITEMS_LINK_INDEX

  CREATE INDEX "XXOM"."XX_CS_SR_ITEMS_LINK_INDEX" ON "XXOM"."XX_CS_SR_ITEMS_LINK" ("SERVICE_REQUEST_ID") 
  ;
 /
 
 REM PUBLIC XX_CS_SR_ITEMS_LINK
 
   CREATE OR REPLACE PUBLIC SYNONYM "XX_CS_SR_ITEMS_LINK" FOR "XXOM"."XX_CS_SR_ITEMS_LINK";
 