SET SHOW          OFF;
SET VERIFY        OFF;
SET ECHO          OFF;
SET TAB           OFF;
SET FEEDBACK      OFF;
SET VERIFY        OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;

  -- +====================================================================================+
  -- |                  Office Depot - Project Simplify                                   |
  -- |                 Oracle NAIO Consulting Organization                                |
  -- +====================================================================================+
  -- |                                                                                    |
  -- | Name             :  XX_CDH_ROLE_RESTRICT_RMV_POLICY                                |
  -- | Rice ID          :  E0266_RoleRestrictionsMerges                                   |
  -- | Description      :  This custom block shall be executed to remove the policy       |
  -- |                     applied on tables.                                             |
  -- |                     This shall be run by DB Administrators.                        |
  -- |                                                                                    |
  -- |                                                                                    |
  -- | Change Record:                                                                     |
  -- |===============                                                                     |
  -- |Version   Date        Author           Remarks                                      |
  -- |=======   ==========  =============    =============================================|
  -- |Draft 1a  12-Jul-07   Prem Kumar       Initial draft version                        |
  -- |1.0       31-Aug-07   Hema Chikkanna   Baselined after review                       |
    -- |1.2       01-Aug-13   Pratesh Shukla   Updated for R12 RETROFIT  for RICE E0266
  -- |									     , changes made are table 'AP_BANK_ACCOUNT_USES' 
  --                                         replaced with 'IBY_PMT_INSTR_USES_ALL', table 
  --                                         'AP_BANK_ACCOUNTS' replaced with 'IBY_EXT_BANK_ACCOUNTS'
  -- +====================================================================================+

PROMPT
PROMPT 'Drop policy on TCA tables...'
PROMPT

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('IBY', 'IBY_PMT_INSTR_USES_ALL#', 'XX_CDH_UPD_PLCY_AP_BNK_ACT_USE');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('IBY', 'IBY_PMT_INSTR_USES_ALL#', 'XX_CDH_INS_PLCY_AP_BNK_ACT_USE');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('IBY', 'IBY_EXT_BANK_ACCOUNTS#', 'XX_CDH_UPD_PLCY_AP_BANK_ACCT');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('IBY', 'IBY_EXT_BANK_ACCOUNTS#', 'XX_CDH_INS_PLCY_AP_BANK_ACCT');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CODE_ASSIGNMENTS#', 'XX_CDH_UPD_PLCY_CODE_ASGN');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CODE_ASSIGNMENTS#', 'XX_CDH_INS_PLCY_CODE_ASGN');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_ROLE_RESPONSIBILITY#', 'XX_CDH_UPD_PLCY_ROLE_RESP');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_ROLE_RESPONSIBILITY#', 'XX_CDH_INS_PLCY_ROLE_RESP');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PARTY_SITES_EXT_TL#', 'XX_CDH_DEL_PLCY_PS_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PARTY_SITES_EXT_B#', 'XX_CDH_DEL_PLCY_PS_EXT_B');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PARTY_SITES_EXT_TL#', 'XX_CDH_UPD_PLCY_PS_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PARTY_SITES_EXT_B#', 'XX_CDH_UPD_PLCY_PS_EXT_B');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PARTY_SITES_EXT_TL#', 'XX_CDH_INS_PLCY_PS_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PARTY_SITES_EXT_B#', 'XX_CDH_INS_PLCY_PS_EXT_B');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PER_PROFILES_EXT_TL#', 'XX_CDH_DEL_PLCY_PERPRF_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PER_PROFILES_EXT_B#', 'XX_CDH_DEL_PLCY_PERPRF_EXT_B');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PER_PROFILES_EXT_TL#', 'XX_CDH_UPD_PLCY_PERPRF_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PER_PROFILES_EXT_TL#', 'XX_CDH_UPD_PLCY_PERPRF_EXT_B');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PER_PROFILES_EXT_TL#', 'XX_CDH_INS_PLCY_PERPRF_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PER_PROFILES_EXT_B#', 'XX_CDH_INS_PLCY_PERPRF_EXT_B');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_ORG_PROFILES_EXT_TL#', 'XX_CDH_DEL_PLCY_ORGPRF_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_ORG_PROFILES_EXT_B#', 'XX_CDH_DEL_PLCY_ORGPRF_EXT_B');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_ORG_PROFILES_EXT_TL#', 'XX_CDH_UPD_PLCY_ORGPRF_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_ORG_PROFILES_EXT_B#', 'XX_CDH_UPD_PLCY_ORGPRF_EXT_B');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_ORG_PROFILES_EXT_TL#', 'XX_CDH_INS_PLCY_ORGPRF_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_ORG_PROFILES_EXT_B#', 'XX_CDH_INS_PLCY_ORGPRF_EXT_B');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'RA_CUST_RECEIPT_METHODS#', 'XX_CDH_UPD_PLCY_RA_CST_REC');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'RA_CUST_RECEIPT_METHODS#', 'XX_CDH_INS_PLCY_RA_CST_REC');
END;
/


BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CUST_ACCT_RELATE_ALL#', 'XX_CDH_UPD_PLCY_HZ_CA_RLT');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CUST_ACCT_RELATE_ALL#', 'XX_CDH_INS_PLCY_HZ_CA_RLT');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CUST_PROFILE_AMTS#', 'XX_CDH_UPD_PLCY_HZ_CST_PRF_AMT');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CUST_PROFILE_AMTS#', 'XX_CDH_INS_PLCY_HZ_CST_PRF_AMT');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CUST_ACCOUNT_ROLES#', 'XX_CDH_UPD_PLCY_HZ_CACT_RLS');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CUST_ACCOUNT_ROLES#', 'XX_CDH_INS_PLCY_HZ_CACT_RLS');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CUST_SITE_USES_ALL#', 'XX_CDH_UPD_PLCY_HZ_CS_USES');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CUST_SITE_USES_ALL#', 'XX_CDH_INS_PLCY_HZ_CS_USES');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CUST_ACCT_SITES_ALL#', 'XX_CDH_UPD_PLCY_HZ_CUST_SITES');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CUST_ACCT_SITES_ALL#', 'XX_CDH_INS_PLCY_HZ_CUST_SITES');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CUSTOMER_PROFILES#', 'XX_CDH_UPD_PLCY_HZ_CUST_PRF');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CUSTOMER_PROFILES#', 'XX_CDH_INS_PLCY_HZ_CUST_PRF');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CUST_ACCOUNTS#', 'XX_CDH_UPD_PLCY_HZ_CUST_ACCT');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CUST_ACCOUNTS#', 'XX_CDH_INS_PLCY_HZ_CUST_ACCT');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_ORG_CONTACT_ROLES#', 'XX_CDH_UPD_PLCY_HZ_ORGCNT_RLS');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_ORG_CONTACT_ROLES#', 'XX_CDH_INS_PLCY_HZ_ORGCNT_RLS');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_ORG_CONTACTS#', 'XX_CDH_UPD_PLCY_HZ_ORG_CNCT');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_ORG_CONTACTS#', 'XX_CDH_INS_PLCY_HZ_ORG_CNCT');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CONTACT_POINTS#', 'XX_CDH_UPD_PLCY_HZ_CNCT_PNT');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_CONTACT_POINTS#', 'XX_CDH_INS_PLCY_HZ_CNCT_PNT');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_RELATIONSHIPS#', 'XX_CDH_UPD_PLCY_HZ_RELNS');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_RELATIONSHIPS#', 'XX_CDH_INS_PLCY_HZ_RELNS');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PERSON_PROFILES#', 'XX_CDH_UPD_PLCY_HZ_PER_PRF');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PERSON_PROFILES#', 'XX_CDH_INS_PLCY_HZ_PER_PRF');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_ORGANIZATION_PROFILES#', 'XX_CDH_UPD_PLCY_HZ_ORG_PRF');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_ORGANIZATION_PROFILES#', 'XX_CDH_INS_PLCY_HZ_ORG_PRF');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PARTY_SITE_USES#', 'XX_CDH_UPD_PLCY_HZ_PS_USES');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PARTY_SITE_USES#', 'XX_CDH_INS_PLCY_HZ_PS_USES');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PARTY_SITES#', 'XX_CDH_UPD_PLCY_HZ_PARTY_SITES');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PARTY_SITES#', 'XX_CDH_INS_PLCY_HZ_PARTY_SITES');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PARTIES#', 'XX_CDH_INS_PLCY_HZ_PARTIES');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('AR', 'HZ_PARTIES#', 'XX_CDH_UPD_PLCY_HZ_PARTIES');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_SITE_USES_EXT_TL#', 'XX_CDH_DEL_PLCY_AS_USES_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_SITE_USES_EXT_TL#', 'XX_CDH_UPD_PLCY_AS_USES_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_SITE_USES_EXT_TL#', 'XX_CDH_INS_PLCY_AS_USES_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_SITE_USES_EXT_B#', 'XX_CDH_DEL_PLCY_AS_USES_EXT_B');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_SITE_USES_EXT_B#', 'XX_CDH_UPD_PLCY_AS_USES_EXT_B');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_SITE_USES_EXT_B#', 'XX_CDH_INS_PLCY_AS_USES_EXT_B');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_ACCT_SITE_EXT_TL#', 'XX_CDH_DEL_PLCY_ACTSITE_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_ACCT_SITE_EXT_TL#', 'XX_CDH_UPD_PLCY_ACTSITE_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_ACCT_SITE_EXT_TL#', 'XX_CDH_INS_PLCY_ACTSITE_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_ACCT_SITE_EXT_B#', 'XX_CDH_DEL_PLCY_ACTSITE_EXT_B');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_ACCT_SITE_EXT_B#', 'XX_CDH_UPD_PLCY_ACTSITE_EXT_B');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_ACCT_SITE_EXT_B#', 'XX_CDH_INS_PLCY_ACTSITE_EXT_B');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_CUST_ACCT_EXT_TL#', 'XX_CDH_DEL_PLCY_CUST_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_CUST_ACCT_EXT_TL#', 'XX_CDH_UPD_PLCY_CUST_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_CUST_ACCT_EXT_TL#', 'XX_CDH_INS_PLCY_CUST_EXT_TL');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_CUST_ACCT_EXT_B#', 'XX_CDH_DEL_PLCY_CUST_EXT_B');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_CUST_ACCT_EXT_B#', 'XX_CDH_UPD_PLCY_CUST_EXT_B');
END;
/

BEGIN
FND_ACCESS_CONTROL_UTIL.DROP_POLICY ('XXCRM', 'XX_CDH_CUST_ACCT_EXT_B#', 'XX_CDH_INS_PLCY_CUST_EXT_B');
END;
/