REM INSERTING into xx_crm_wcelg_cust
Insert into xx_crm_wcelg_cust
(PARTY_ID,
CUST_ACCOUNT_ID,
ACCOUNT_NUMBER,
SITE_USE_ID,
INT_SOURCE,
EXTRACTION_DATE,
CUST_MAST_HEAD_EXT,
CUST_ADDR_EXT,
CUST_CONT_EXT,
CUST_HIER_EXT,
SLS_PER_EXT,
AR_TRANS_EXT,
REC_APP_EXT,
ADJ_EXT,
CASH_REC_EXT,
PS_EXT,
NOTES_PROCESSED_TO_WC,
LAST_UPDATE_DATE,
LAST_UPDATED_BY,
CREATION_DATE,
CREATED_BY,
REQUEST_ID,
PROGRAM_ID) values (3791788,55347,'47907',null,'AB',null,'N','N','N','N','N','N','N','N','N','N','N',to_date('28-OCT-11','DD-MON-RR'),-1,to_date('28-OCT-11','DD-MON-RR'),-1,-1,-1);

commit;