package od.oracle.apps.xxcrm.customer.account.server;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class ODContTempCUPVORowImpl extends OAViewRowImpl 
{


  protected static final int READONLY = 0;
  protected static final int RENDERED = 1;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public ODContTempCUPVORowImpl()
  {
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute ReadOnly
   */
  public Boolean getReadOnly()
  {
    return (Boolean)getAttributeInternal(READONLY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute ReadOnly
   */
  public void setReadOnly(Boolean value)
  {
    setAttributeInternal(READONLY, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Rendered
   */
  public Boolean getRendered()
  {
    return (Boolean)getAttributeInternal(RENDERED);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Rendered
   */
  public void setRendered(Boolean value)
  {
    setAttributeInternal(RENDERED, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case READONLY:
        return getReadOnly();
      case RENDERED:
        return getRendered();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case READONLY:
        setReadOnly((Boolean)value);
        return;
      case RENDERED:
        setRendered((Boolean)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
}