<?xml version="1.0" encoding="UTF-8"?>
<definitions
     name="SupplierEBSV1"
     targetNamespace="http://xmlns.officedepot.org/EnterpriseObjects/Core/EBO/Supplier/V1"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.officedepot.org/EnterpriseObjects/Core/EBO/Supplier/V1"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:supp="http://xmlns.officedepot.org/EnterpriseObjects/Core/EBO/Supplier/V1"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
    >
    <types>
        <xsd:schema targetNamespace="http://xmlns.officedepot.org/EnterpriseObjects/Core/EBO/Supplier/V1/types"
             elementFormDefault="qualified">
            <xsd:import schemaLocation="http://soadev01.na.odcorp.net:80/soa-infra/services/finance/SupplierEBS/SupplierEBSService?XSD=../../../../../EnterpriseObjects/Core/EBO/Supplier/V1/SupplierEBM.xsd"
                 namespace="http://xmlns.officedepot.org/EnterpriseObjects/Core/EBO/Supplier/V1"/>
        </xsd:schema>
    </types>
    <message name="SynchSupplierFileReqMsg">
        <part name="body" element="tns:SyncSupplierFileEBM"/>
    </message>
    <message name="SynchSupplierFileRespMsg">
        <part name="body" element="tns:SyncSupplierFileRespEBM"/>
    </message>
    <portType name="SynchSupplierEBS">
        <operation name="synchronizeSupplier">
            <input message="tns:SynchSupplierFileReqMsg"/>
            <output message="tns:SynchSupplierFileRespMsg"/>
        </operation>
    </portType>
    <binding name="SynchSupplierEBSBinding" type="tns:SynchSupplierEBS">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="synchronizeSupplier">
            <soap:operation style="document" soapAction="synchronizeSupplier"/>
            <input>
                <soap:body use="literal" namespace="http://xmlns.officedepot.org/EnterpriseObjects/Core/EBO/Supplier/V1"/>
            </input>
            <output>
                <soap:body use="literal" namespace="http://xmlns.officedepot.org/EnterpriseObjects/Core/EBO/Supplier/V1"/>
            </output>
        </operation>
    </binding>
    <service name="SupplierEBS">
        <port name="SynchSupplierEBS_pt" binding="tns:SynchSupplierEBSBinding">
            <soap:address location="http://soadev01.na.odcorp.net:80/soa-infra/services/finance/SupplierEBS/SupplierEBSService"/>
        </port>
    </service>
</definitions>
