CREATE OR REPLACE
PACKAGE BODY XX_COMN_WFERR_ABORT_PKG                                                                                                                                                                                                                                                                                                                                                                            
AS                                                                                                                                                                                                                                                                                                                                                                                                              
-- +=========================================================================================+                                                                                                                                                                                                                                                                                                                  
-- |                        Office Depot - Project Simplify                                  |                                                                                                                                                                                                                                                                                                                  
-- +=========================================================================================+                                                                                                                                                                                                                                                                                                                  
-- | Name    : XX_WFERR_ABORT_PKG                                                            |                                                                                                                                                                                                                                                                                                                  
-- |                                                                                         |                                                                                                                                                                                                                                                                                                                  
-- | Description:                                                                            |                                                                                                                                                                                                                                                                                                                  
-- | Common program to abort WFERROR workflows  [Origin: Defect 21878: ILM project           |                                                                                                                                                                                                                                                                                                                  
-- | To be used once you have investigated RCA and still want to abort                       |                                                                                                                                                                                                                                                                                                                  
-- | Date ranges so that you can control how many workflows become eligible for Purge .      |                                                                                                                                                                                                                                                                                                                  
-- | a) "OD: Error Workflow Max Abort per Run" limits the max number of wf's you can abort   |                                                                                                                                                                                                                                                                                                                  
-- |  so that too many workflows do not become eligible for purge, hence control UNDO growth |                                                                                                                                                                                                                                                                                                                  
-- |                                                                                         |                                                                                                                                                                                                                                                                                                                  
-- | b) "OD: Error Workflow Min Retention Days"[in days] allows wfs older than this age      |                                                                                                                                                                                                                                                                                                                  
--    to be eligible for abort. This will allow time for investigation of errors, and fixes  |                                                                                                                                                                                                                                                                                                                  
-- |Change Record:                                                                           |                                                                                                                                                                                                                                                                                                                  
-- |===============                                                                          |                                                                                                                                                                                                                                                                                                                  
-- |Version    Date              Author              Remarks                                 |                                                                                                                                                                                                                                                                                                                  
-- |=======    ==========        =============       ========================                |                                                                                                                                                                                                                                                                                                                  
-- |1.0        03-Mar-13         AMS                 Initiated from Defect 21878             |                                                                                                                                                                                                                                                                                                                  
-- |2.0        24-Mar-2016       Havish Kasina       Removed the schema references as per    |
-- |                                                 R12.2 Changes                           |                                                                                                                                                                                                                                                                                                                  
--============================================================================================                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                
  PROCEDURE main (                                                                                                                                                                                                                                                                                                                                                                                              
                 x_errbuf          OUT VARCHAR2,                                                                                                                                                                                                                                                                                                                                                                
                 x_retcode         OUT NUMBER,                                                                                                                                                                                                                                                                                                                                                                  
                 p_parent_itemtype IN  VARCHAR2,                                                                                                                                                                                                                                                                                                                                                                
                 p_start_date      IN  VARCHAR2,                                                                                                                                                                                                                                                                                                                                                                
                 p_end_date        IN  VARCHAR2,                                                                                                                                                                                                                                                                                                                                                                
                 p_wf_itemkey      IN  VARCHAR2,                                                                                                                                                                                                                                                                                                                                                                
                 p_force_purge     IN  VARCHAR2,                                                                                                                                                                                                                                                                                                                                                                
                 p_commit          IN  VARCHAR2                                                                                                                                                                                                                                                                                                                                                                 
                  )                                                                                                                                                                                                                                                                                                                                                                                             
   IS                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                
   CURSOR c_wf_abort(c_parentitemtype VARCHAR2,                                                                                                                                                                                                                                                                                                                                                                 
                     c_item_key       VARCHAR2,                                                                                                                                                                                                                                                                                                                                                                 
                     c_startdate      DATE,                                                                                                                                                                                                                                                                                                                                                                     
                     c_enddate        DATE                                                                                                                                                                                                                                                                                                                                                                      
                    )                                                                                                                                                                                                                                                                                                                                                                                           
    IS                                                                                                                                                                                                                                                                                                                                                                                                          
    SELECT wi.item_key, wi.item_type, wi.parent_item_key                                                                                                                                                                                                                                                                                                                                                        
    FROM WF_ITEMS wi                                                                                                                                                                                                                                                                                                                                                                                       
    WHERE wi.begin_date BETWEEN c_startdate AND c_enddate                                                                                                                                                                                                                                                                                                                                                       
    AND wi.end_date         IS NULL   ---Not completed already                                                                                                                                                                                                                                                                                                                                                  
    AND wi.item_type        = 'WFERROR'                                                                                                                                                                                                                                                                                                                                                                         
    AND wi.item_key         = NVL(c_item_key, wi.item_key)                                                                                                                                                                                                                                                                                                                                                      
    AND wi.parent_item_type = c_parentitemtype ;                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
   INVALID_INPUTS  EXCEPTION ;                                                                                                                                                                                                                                                                                                                                                                                  
   v_errbuf      VARCHAR2(4000);                                                                                                                                                                                                                                                                                                                                                                                
   l_abort_limit NUMBER := 0 ;                                                                                                                                                                                                                                                                                                                                                                                  
   l_abort_age   NUMBER := 0 ;                                                                                                                                                                                                                                                                                                                                                                                  
   ld_start_date DATE ;                                                                                                                                                                                                                                                                                                                                                                                         
   ld_end_date   DATE ;                                                                                                                                                                                                                                                                                                                                                                                         
   l_commit      VARCHAR2(1) := NVL(p_commit, 'N');                                                                                                                                                                                                                                                                                                                                                             
   l_force_purge VARCHAR2(1) := NVL(p_force_purge,'N');                                                                                                                                                                                                                                                                                                                                                         
   l_count       NUMBER := 0 ;                                                                                                                                                                                                                                                                                                                                                                                  
   l_err_count   NUMBER := 0 ;                                                                                                                                                                                                                                                                                                                                                                                  
   l_purged_count NUMBER := 0;                                                                                                                                                                                                                                                                                                                                                                                  
   l_wf_itemkey  WF_ITEMS.item_key%TYPE ;                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
  BEGIN                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                
     fnd_file.put_line(FND_FILE.log, 'Started: ');                                                                                                                                                                                                                                                                                                                                                              
     fnd_file.put_line(FND_FILE.log, 'Parent-Item type : '|| p_parent_itemtype );                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                
     v_errbuf := ' fetching maximum number of WFERROR workflows that can be purged' ;                                                                                                                                                                                                                                                                                                                           
     l_abort_limit := NVL( FND_PROFILE.VALUE('OD_COMN_WFERR_MAX_ABORT_NUMBER') , 1000);            --OD: Error Workflow Max Abort per Run                                                                                                                                                                                                                                                                       
     l_abort_age   := NVL( FND_PROFILE.VALUE('OD_COMN_WFERR_MIN_RETENTION_DAYS') , 30);            --OD: Error Workflow Min Retention Days                                                                                                                                                                                                                                                                      
     fnd_file.put_line(FND_FILE.log, 'Maximum WFERRORs you are allowed to abort is set to : '||l_abort_limit);                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
  if p_wf_itemkey is NULL THEN                                                                                                                                                                                                                                                                                                                                                                                  
   --Do the date validations only when specific-item-key has not been passed                                                                                                                                                                                                                                                                                                                                    
       v_errbuf := ' fetching start-date parameter';                                                                                                                                                                                                                                                                                                                                                            
       if p_start_date is null AND p_end_date is null                                                                                                                                                                                                                                                                                                                                                           
       THEN                                                                                                                                                                                                                                                                                                                                                                                                     
          --Say in scheduled mode, if date params not passed then abort 1 wks worth WFERRRORs for that parent, which are older than Abort-age                                                                                                                                                                                                                                                                   
           ld_end_date   :=  SYSDATE - l_abort_age -1 ;                                                                                                                                                                                                                                                                                                                                                         
           ld_start_date :=  ld_end_date -7 ;                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                
       elsif ( p_start_date is NOT null AND p_end_date is null ) THEN                                                                                                                                                                                                                                                                                                                                           
            ld_start_date  := FND_DATE.canonical_to_date(p_start_date);                                                                                                                                                                                                                                                                                                                                         
            ld_end_date   :=  SYSDATE - l_abort_age -1 ;                                                                                                                                                                                                                                                                                                                                                        
       elsif ( p_start_date is null AND p_end_date is NOT null ) THEN                                                                                                                                                                                                                                                                                                                                           
            ld_end_date   :=  FND_DATE.canonical_to_date(p_end_date);                                                                                                                                                                                                                                                                                                                                           
            ld_start_date  := ld_end_date - 7;                                                                                                                                                                                                                                                                                                                                                                  
       else                                                                                                                                                                                                                                                                                                                                                                                                     
            ld_start_date  := FND_DATE.canonical_to_date(p_start_date);                                                                                                                                                                                                                                                                                                                                         
            ld_end_date   :=  FND_DATE.canonical_to_date(p_end_date);                                                                                                                                                                                                                                                                                                                                           
       end if;                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                
       if ld_start_date is not NULL                                                                                                                                                                                                                                                                                                                                                                             
       THEN                                                                                                                                                                                                                                                                                                                                                                                                     
         ld_start_date := TO_DATE( TO_CHAR(ld_start_date, 'DD-MON-YYYY'), 'DD-MON-YYYY HH24:MI:SS') ;                                                                                                                                                                                                                                                                                                           
       ELSE                                                                                                                                                                                                                                                                                                                                                                                                     
          v_errbuf := ' Could not determine a Range start-date required for selecting eligible workflows to abort. ';                                                                                                                                                                                                                                                                                           
          RAISE INVALID_INPUTS ;                                                                                                                                                                                                                                                                                                                                                                                
       END IF;                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                
       if ld_end_date is not NULL                                                                                                                                                                                                                                                                                                                                                                               
       THEN                                                                                                                                                                                                                                                                                                                                                                                                     
         ld_end_date := TO_DATE( TO_CHAR(ld_end_date, 'DD-MON-YYYY')||' 23:59:00', 'DD-MON-YYYY HH24:MI:SS') ;                                                                                                                                                                                                                                                                                                  
       ELSE                                                                                                                                                                                                                                                                                                                                                                                                     
          v_errbuf := ' Could not determine a Range end-date required for selecting eligible workflows to abort. ';                                                                                                                                                                                                                                                                                             
          RAISE INVALID_INPUTS;                                                                                                                                                                                                                                                                                                                                                                                 
       END IF;                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                
      --Checking if derived start and end dates are valid, i.e. start < end, and both dont infringe upon the no-touch window set by profile: "OD: Error Workflow Min Retention Days"                                                                                                                                                                                                                            
       if  ld_end_date < ld_start_date then                                                                                                                                                                                                                                                                                                                                                                     
          v_errbuf := ' Please re-enter valid date parameters [FYI: You are allowed to abort Error-wfs older than '||l_abort_age||' days' ;                                                                                                                                                                                                                                                                     
          fnd_file.put_line(FND_FILE.log, v_errbuf);                                                                                                                                                                                                                                                                                                                                                            
          v_errbuf := ' Start-date: '||TO_CHAR(ld_start_date,'DD-MON-YYYY HH24:MI:SS')||' is greater than derived end-date.'||TO_CHAR(ld_end_date,'DD-MON-YYYY HH24:MI:SS')||'. Exiting' ;                                                                                                                                                                                                                      
          RAISE INVALID_INPUTS ;                                                                                                                                                                                                                                                                                                                                                                                
       elsif ( (ld_end_date > SYSDATE - l_abort_age) OR  (ld_start_date > SYSDATE - l_abort_age) ) THEN                                                                                                                                                                                                                                                                                                         
          v_errbuf := ' Please re-enter valid date parameters. You are not allowed to abort WFERROR wfs which are not older than '||l_abort_age||' days.  Start: '||ld_start_date||' ; End: '|| ld_end_date ;                                                                                                                                                                                                   
          RAISE INVALID_INPUTS ;                                                                                                                                                                                                                                                                                                                                                                                
       else                                                                                                                                                                                                                                                                                                                                                                                                     
          fnd_file.put_line(FND_FILE.log, 'Date range Start : '|| to_char(ld_start_date,'DD-MON-YYYY HH24:MI:SS') );                                                                                                                                                                                                                                                                                            
          fnd_file.put_line(FND_FILE.log, 'Date range End   : '|| to_char(ld_end_date,'DD-MON-YYYY HH24:MI:SS') );                                                                                                                                                                                                                                                                                              
       end if ;                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
  else  ---If running for a specific workflow itemkey                                                                                                                                                                                                                                                                                                                                                           
        l_wf_itemkey := p_wf_itemkey ;                                                                                                                                                                                                                                                                                                                                                                          
        fnd_file.put_line(FND_FILE.log, 'Specific item-key to be aborted : '|| l_wf_itemkey);                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                
        v_errbuf := ' checking info on '||l_wf_itemkey ;                                                                                                                                                                                                                                                                                                                                                        
        SELECT TO_DATE( TO_CHAR(wi.begin_date, 'DD-MON-YYYY'), 'DD-MON-YYYY HH24:MI:SS') ,                                                                                                                                                                                                                                                                                                                      
               TO_DATE( TO_CHAR(wi.begin_date, 'DD-MON-YYYY')||' 23:59:00', 'DD-MON-YYYY HH24:MI:SS')                                                                                                                                                                                                                                                                                                           
        INTO ld_start_date, ld_end_date                                                                                                                                                                                                                                                                                                                                                                         
        FROM WF_ITEMS wi                                                                                                                                                                                                                                                                                                                                                                                   
        WHERE wi.item_key = l_wf_itemkey ;                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                
  end if ; --  checking if p_wf_itemkey is passed..bypassing validations on date etc if passed                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                
     fnd_file.put_line(FND_FILE.log, 'Commit Operation: '||l_commit);                                                                                                                                                                                                                                                                                                                                           
     fnd_file.put_line(FND_FILE.log, 'Force-Purge : '||l_force_purge);                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
---If run for a date-range, then check how many workflows we might end up aborting.                                                                                                                                                                                                                                                                                                                             
          SELECT count(*)                                                                                                                                                                                                                                                                                                                                                                                       
          INTO l_count                                                                                                                                                                                                                                                                                                                                                                                          
          FROM  wf_items wp                                                                                                                                                                                                                                                                                                                                                                                
          WHERE wp.item_type = 'WFERROR'                                                                                                                                                                                                                                                                                                                                                                        
          AND   wp.begin_date BETWEEN ld_start_date AND ld_end_date                                                                                                                                                                                                                                                                                                                                             
          AND   wp.end_date is NULL                                                                                                                                                                                                                                                                                                                                                                             
          AND   wp.parent_item_type = p_parent_itemtype ;                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                
         IF l_count > l_abort_limit THEN                                                                                                                                                                                                                                                                                                                                                                        
            fnd_file.put_line(FND_FILE.log, 'Please re-enter Date range');                                                                                                                                                                                                                                                                                                                                      
            v_errbuf := ' You are not allowed to abort more than '||l_abort_limit||' WFERROR workflows. '|| l_count ||' workflows were found eligible for abort' ;                                                                                                                                                                                                                                              
            RAISE INVALID_INPUTS ;                                                                                                                                                                                                                                                                                                                                                                              
         END IF ;                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                
   IF l_commit = 'N' then                                                                                                                                                                                                                                                                                                                                                                                       
         fnd_file.put_line(FND_FILE.log, '**Information only Report**' );                                                                                                                                                                                                                                                                                                                                       
         fnd_file.put_line(FND_FILE.log, l_count || ' workflows are eligible for abort. FYI: Maximum allowable is: '||l_abort_limit );                                                                                                                                                                                                                                                                          
         fnd_file.put_line(FND_FILE.output, 'FYI: '||l_count || ' workflows are eligible for abort' );                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                
   ELSE                                                                                                                                                                                                                                                                                                                                                                                                         
       ---If Commit=Y, start processing eligible workflows for aborting....                                                                                                                                                                                                                                                                                                                                     
       l_count := 0 ;                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                
            FOR lc_wf_abort in c_wf_abort(p_parent_itemtype, l_wf_itemkey, ld_start_date, ld_end_date )                                                                                                                                                                                                                                                                                                         
            LOOP                                                                                                                                                                                                                                                                                                                                                                                                
               BEGIN                                                                                                                                                                                                                                                                                                                                                                                            
                   v_errbuf := ' aborting item-key: '||lc_wf_abort.item_key ;                                                                                                                                                                                                                                                                                                                                   
                   ----                                                                                                                                                                                                                                                                                                                                                                                         
                   WF_ENGINE.AbortProcess(lc_wf_abort.item_type, lc_wf_abort.item_key);                                                                                                                                                                                                                                                                                                                    
                   ----                                                                                                                                                                                                                                                                                                                                                                                         
                   COMMIT;                                                                                                                                                                                                                                                                                                                                                                                      
                   l_count := l_count + 1 ;                                                                                                                                                                                                                                                                                                                                                                     
                   fnd_file.put_line(FND_FILE.output, lc_wf_abort.item_key ||' , '||lc_wf_abort.parent_item_key);     --o/p will list all WFERROR and PARENT item-keys aborted. Can use for reporting                                                                                                                                                                                                           
                   fnd_file.put_line(FND_FILE.log, 'Aborted: '||lc_wf_abort.item_key ||' related to parent-item-key: '||lc_wf_abort.parent_item_key);                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                
                   if l_force_purge = 'Y' then                                                                                                                                                                                                                                                                                                                                                                  
                       v_errbuf := ' purging item-key: '||lc_wf_abort.item_key ;                                                                                                                                                                                                                                                                                                                                
                       ----                                                                                                                                                                                                                                                                                                                                                                                     
                       WF_PURGE.ITEMS (itemtype => 'WFERROR',                                                                                                                                                                                                                                                                                                                                                   
                                       itemkey => lc_wf_abort.item_key ,                                                                                                                                                                                                                                                                                                                                        
                                       enddate => SYSDATE,                                                                                                                                                                                                                                                                                                                                                      
                                       docommit => true,                                                                                                                                                                                                                                                                                                                                                        
                                       force => true );                                                                                                                                                                                                                                                                                                                                                         
                       ----                                                                                                                                                                                                                                                                                                                                                                                     
                       l_purged_count := l_purged_count + 1 ;                                                                                                                                                                                                                                                                                                                                                   
                       fnd_file.put_line(FND_FILE.log, 'Purged: '||lc_wf_abort.item_key);                                                                                                                                                                                                                                                                                                                       
                   end if; ---purge also..                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
               EXCEPTION                                                                                                                                                                                                                                                                                                                                                                                        
               WHEN OTHERS THEN                                                                                                                                                                                                                                                                                                                                                                                 
                  ROLLBACK ;                                                                                                                                                                                                                                                                                                                                                                                    
                  l_err_count := l_err_count +  1 ;                                                                                                                                                                                                                                                                                                                                                             
                  fnd_file.put_line(FND_FILE.log, SQLERRM||' while '|| v_errbuf );                                                                                                                                                                                                                                                                                                                              
                  --Continue to next one                                                                                                                                                                                                                                                                                                                                                                        
                END;                                                                                                                                                                                                                                                                                                                                                                                            
             END LOOP;                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
    fnd_file.put_line(FND_FILE.log, l_count || ' workflow(s) successfully aborted. '||l_err_count||' workflow(s) failed to abort ');                                                                                                                                                                                                                                                                            
    if l_force_purge = 'Y' then                                                                                                                                                                                                                                                                                                                                                                                 
       fnd_file.put_line(FND_FILE.log, l_purged_count || ' workflow(s) successfully Force-Purged. ');                                                                                                                                                                                                                                                                                                           
    end if;                                                                                                                                                                                                                                                                                                                                                                                                     
   END IF ;---Only if commit operation is set, process the abort. Else display info                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                
  EXCEPTION                                                                                                                                                                                                                                                                                                                                                                                                     
  WHEN INVALID_INPUTS THEN                                                                                                                                                                                                                                                                                                                                                                                      
    fnd_file.put_line(FND_FILE.log, v_errbuf );                                                                                                                                                                                                                                                                                                                                                                 
    x_errbuf  := v_errbuf ;                                                                                                                                                                                                                                                                                                                                                                                     
    x_retcode := 1 ;    --warning                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                
 WHEN OTHERS THEN                                                                                                                                                                                                                                                                                                                                                                                               
   ROLLBACK ;                                                                                                                                                                                                                                                                                                                                                                                                   
   v_errbuf := SQLERRM||' while '|| v_errbuf ;                                                                                                                                                                                                                                                                                                                                                                  
   fnd_file.put_line(FND_FILE.log, v_errbuf );                                                                                                                                                                                                                                                                                                                                                                  
   x_errbuf := v_errbuf ;                                                                                                                                                                                                                                                                                                                                                                                       
    x_retcode:=2;                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
 END main ;---end of procedure                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
END XX_COMN_WFERR_ABORT_PKG ;  
/

SHOW ERRORS;                                                                                                                                                                                                                                                                                                                                                                                 

