
PROMPT "---------------Droping Tables--------------"

PROMPT "Drop Table XX_AR_WC_UPD_PS..."
drop table XXFIN.XX_AR_WC_UPD_PS  CASCADE CONSTRAINTS;

PROMPT "Drop Table XX_AR_MT_WC_DETAILS  ..."
drop table XXFIN.XX_AR_MT_WC_DETAILS CASCADE CONSTRAINTS;

PROMPT "Drop Table XX_AR_TRANS_WC_STG  ..."
drop table XXFIN.XX_AR_TRANS_WC_STG CASCADE CONSTRAINTS;

PROMPT "Drop Table XX_AR_PS_WC_STG  ..."
drop table XXFIN.XX_AR_PS_WC_STG CASCADE CONSTRAINTS;

PROMPT "Drop Table XX_AR_RECAPPL_WC_STG  ..."
drop table XXFIN.XX_AR_RECAPPL_WC_STG CASCADE CONSTRAINTS;

PROMPT "Drop Table XX_AR_ADJ_WC_STG  ..."
drop table XXFIN.XX_AR_ADJ_WC_STG CASCADE CONSTRAINTS;

PROMPT "Drop Table XX_AR_CR_WC_STG  ..."
drop table XXFIN.XX_AR_CR_WC_STG CASCADE CONSTRAINTS;

PROMPT "Drop Table XX_AR_MT_WC_S  ..."
drop SEQUENCE XXFIN.XX_AR_MT_WC_S;

exit;
