
CREATE GLOBAL TEMPORARY TABLE XXFIN.XXOD_LC_ACH_FLAG_GT(c_ext_attr1 VARCHAR2(100),orig_system_reference VARCHAR2(240))
ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE XXFIN.XXOD_LC_ACH_PARENT_ACCT_GT(relationship_code VARCHAR2(100),orig_system_reference1 VARCHAR2(240),orig_system_reference2 VARCHAR2(240))
ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE XXFIN.XXOD_LN_ACH_PARENT_BAL_GT(amount NUMBER,party_id NUMBER,receipt_date DATE)
ON COMMIT PRESERVE ROWS;

                       
CREATE GLOBAL TEMPORARY TABLE XXFIN.XXOD_LN_ACH_ACCOUNT_BAL_GT(amount NUMBER,pay_from_customer NUMBER,receipt_date DATE)
ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE XXFIN.XXOD_LN_ACH_CHILD_BAL_GT(amount NUMBER,object_id NUMBER,receipt_date DATE)
ON COMMIT PRESERVE ROWS;

                                                 
CREATE GLOBAL TEMPORARY TABLE  XXFIN.XXOD_LN_CHILD_BAL_GT ( acctd_amount_due_remaining NUMBER,object_id NUMBER)
ON COMMIT PRESERVE ROWS;

  
CREATE GLOBAL TEMPORARY TABLE XXFIN.XXOD_LN_PARENT_BAL_GT(acctd_amount_due_remaining NUMBER,party_id NUMBER)
ON COMMIT PRESERVE ROWS;