SET SHOW          OFF;
SET VERIFY        OFF;
SET ECHO          OFF;
SET TAB           OFF;
SET FEEDBACK      OFF;
WHENEVER SQLERROR CONTINUE;
WHENEVER OSERROR EXIT FAILURE ROLLBACK;

CREATE OR REPLACE
PACKAGE BODY XX_RJS_TEST_1_PKG AS

PROCEDURE RJS_TEST(errbuf       OUT NOCOPY VARCHAR2,
                   retcode      OUT NOCOPY NUMBER)
IS

lc_string               VARCHAR2(40) := 'rjs test';

BEGIN

    FND_FILE.PUT_LINE(FND_FILE.LOG, 'XX_RJS_TEST_1_PKG Begin:');

    FND_FILE.PUT_LINE(FND_FILE.LOG, 'XX_RJS_TEST_1_PKG :'||lc_string);

    FND_FILE.PUT_LINE(FND_FILE.LOG, 'XX_RJS_TEST_1_PKG End:');


EXCEPTION
    WHEN OTHERS THEN
         FND_FILE.PUT_LINE(FND_FILE.LOG, 'XX_RJS_TEST_1_PKG OTHERS ERROR'||SQLERRM);
         RETCODE := 2;

END RJS_TEST;

END XX_RJS_TEST_1_PKG;
/
