CREATE OR REPLACE PROCEDURE XXOD_UPDATE_AP_CC_DATA(
    p_start_id IN NUMBER,
    p_end_id   IN NUMBER)
AS

BEGIN

  UPDATE AP_BANK_ACCOUNTS_ALL ABA
  SET aba.BANK_ACCOUNT_NUM = BANK_ACCOUNT_ID ||'***'
  WHERE aba.ACCOUNT_TYPE = 'EXTERNAL'
  AND aba.BANK_BRANCH_ID = 1 -- CREDIT CARD ONLY
  AND aba.BANK_ACCOUNT_ID BETWEEN p_start_id AND p_end_id;
  
  COMMIT;
END XXOD_UPDATE_AP_CC_DATA;
/
